### ISSUE TITLE
Visual anomalies in Firefox

### ISSUE THREAD

**Issue by pkaminski** [Reviewable/Reviewable#10]
- [ ] Some file matrix top and right borders disappear.
- [ ] File matrix bottom border disappears when expanding/collapsing obsolete files.
- [ ] Diff bound brackets render with a notch in the middle. 
  ![image](https://cloud.githubusercontent.com/assets/1646896/7785644/d1134f82-014d-11e5-87a4-3c1723407a1c.png)
- [ ] Revision cells have an extra blank stripe on the right (see image above).
- [ ] Margin notch vertical offset varies by up to 2px, overlaps top edge sometimes.
- [x] Draft comment textarea doesn't scale.
- [ ] Diff text selection appears discontinuous, highlights images, highlights unselectable fragments when window not focused, fails to highlight synthetic CSS content (like tabs), and does not retroactively deselect outside text upon entering diff area.
- [ ] Current subscription description aligned too low relative to organization name.
- [ ] In merge button, cycling between delete/retain jumps the text by a pixel (on review page only, not on dashboard).
- [ ] Bunny overlay is half-width when sliding up/down.
- [ ] Status bar dropdowns' vertical position is sometimes off by a pixel, as is the active item highlight bar.
- [ ] Dropdown bunny icon jerks up/down by a pixel when title area gains/loses content.

**Comment by jGleitz** [comment]
While I can’t reproduce most of the issues on the list, I think I found another: The “assigned to” icon jumps down for a few pixels when the toolbar gets fixed:

http://owncloud.joshuagleitze.de/index.php/s/gNZFXEtWWDNB2fx

**Comment by pkaminski** [comment]
Good catch, this is actually a regression in all browsers -- thanks.  Fix committed, will show up next time I push.

**Comment by pkaminski** [comment]
Closing since most of the issues are likely obsolete.
