### ISSUE TITLE
Feature request: Default PR comment to be made by a Reviewable bot

### ISSUE THREAD

**Issue by SanjayVas** [Reviewable/Reviewable#1001]
According to #522 (not sure if this is documented elsewhere), the person configuring Reviewable for a repository needs to provide a public GitHub user that has accepted Reviewable OAuth scopes to use the "In PR comment by" option. Otherwise, the comment will be made by the GitHub user who configured Reviewable for that repo.

This is not a sensible default, as it has the potential unintended side effect of having that user potentially treated as participating in every PR in a repo. Instead, Reviewable should provide a bot user that makes this comment rather than forcing the creation of a separate user.

**Comment by pkaminski** [comment]
Unfortunately, using a bot is not feasible.  Reviewable is an OAuth app, so has no identity of its own, and if we supplied a designated account as a bot then every customer would need to add that user to their team anyway so it'd be able to post comments in private repositories.  At that point, you might as well create your own "Reviewable bot" account that you have full control over, and tell Reviewable to use that -- with the obvious caveat that this'll use up a seat in your GitHub plan.

The long term solution is to migrate Reviewable to GitHub's non-OAuth App platform, but for various reasons this would be pretty challenging and is not a priority for us at this time.

If you can't create a dedicated "bot" user for this I'd recommend sticking with the default "in PR description" option.
