### ISSUE TITLE
Reviewable is not working across multiple browsers.

### ISSUE THREAD

**Issue by mwoehlke-kitware** [Reviewable/Reviewable#1004]
Reviewable stopped working on my Firefox some months back. It loads, but has me signed out. When I try to sign in, I get:
> Unable to sign in: Firebase: A network AuthError (such as timeout, interrupted connection or unreachable host) has occurred. (auth/network-request-failed).

Looking in the console, I see:
> Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://reviewable-prod.appspot-preview.com’) does not match the recipient window’s origin (‘https://reviewable.io’). 4 199

When I try a different browser (which also used to work until some weeks ago), it seems to work for a brief moment before throwing up a page-blocking "we're sorry" box, with the details:
> Failed to execute 'querySelectorAll' on 'Document': '.row.wrapper .row:not(.line.separator) .cell.waiting.on[data-v-3d15df71]' is not a valid selector.

**Comment by jwnimmer-tri** [comment]
I can anticipate the next questions:
- What firefox version / OS?
- Confirm that all extensions / customizations / blockers are disabled?
- Try in a private window (i.e., to start from zero-cookie state).

**Comment by pkaminski** [comment]
Indeed, these sound like some old browser versions.  Can you confirm @mwoehlke-kitware?  We generally support the last 2 versions of Firefox and Chrome (plus some recent version of Safari), but will occasionally make exceptions for LTS versions.

**Comment by mwoehlke-kitware** [comment]
Firefox 109.0.1 (64-bit).

**Comment by jwnimmer-tri** [comment]
I'm using FF 109.0 (64-bit) via Ubuntu 22's Snap package ("canonical-002 - 1.0") as my daily driver, and it's been fine with Reviewable for a couple months now since I started using it.

Possibly your distribution has configured it differently?  Or you have some privacy settings or extensions dialed in beyond what Reviewable knows how to deal with?

**Comment by pkaminski** [comment]
Ping -- any updates here?  Trying in an incognito window with no extensions would definitely be the first step in figuring things out.

**Comment by pkaminski** [comment]
Closing due to lack of details.  Please follow up and I'll gladly re-open.
