### ISSUE TITLE
Code suggestion workflow missing from user guide

### ISSUE THREAD

**Issue by jwnimmer-tri** [Reviewable/Reviewable#1008]
I wanted to show a co-worker how to use the "suggested change" feature, but I wasn't able to find it anywhere in https://docs.reviewable.io/ to point them to.

Eventually I settled on https://changelog.reviewable.io/create-code-suggestion-from-current-line-242025 to explain, but I think it would be helpful to have a section in the user manual as well.

**Comment by earlAchromatic** [comment]
@jwnimmer-tri Thanks for pointing this out. Docs are updated with instructions - see https://docs.reviewable.io/files.html#code-snippets-quoting-code-and-making-code-suggestions.
