### ISSUE TITLE
Commit messages being lost/truncated

### ISSUE THREAD

**Issue by jwnimmer-tri** [Reviewable/Reviewable#1009]
If I look at https://reviewable.io/reviews/RobotLocomotion/drake/18793 as of this moment, the merge box looks like this:

![image](https://user-images.githubusercontent.com/17596505/220432748-c3333f1c-a39e-4046-8b93-0f3f9d46ac59.png)

Note that there's only a title, no commit body.

However the pushed commit has a body.

![image](https://user-images.githubusercontent.com/17596505/220433021-86d949e8-d751-49ae-8ce6-c917414cf614.png)

It also seems (according to reports in https://github.com/RobotLocomotion/drake/pull/18809) that a recent merge lost its commit body.

**Comment by fahhem** [comment]
Hello Jeremy,

That block is affected by your GitHub repository's settings:

![image](https://user-images.githubusercontent.com/306100/220434307-af70ec63-66be-4434-aa26-0e6f896f6eb0.png)

You can access them here: https://github.com/RobotLocomotion/drake/settings#:~:text=When%20merging%20pull%20requests

If that setting is correct, then we'll consider this a bug

**Comment by jwnimmer-tri** [comment]
We have it set to "[x] Allow Squash Merging" with "Default message" in the picker.  We haven't changed that anytime recently, but it seems like we've started losing commit bodies recently.  Possibly GitHub themselves made some change?

**Comment by jwnimmer-tri** [comment]
The GitHub PR page's merge box is correct, though:
![image](https://user-images.githubusercontent.com/17596505/220436326-d3e4a2ad-17ad-4365-9488-14abfa358a76.png)

**Comment by fahhem** [comment]
Thank you for checking! We'll treat this as a bug and get back to you once we know what's going wrong!

**Comment by fahhem** [comment]
This has been fixed and deployed as of yesterday. @jwnimmer-tri please let us know if there are still any issues!
