### ISSUE TITLE
When using pentadactyl, single clicking on a line opens and then closes a new comment

### ISSUE THREAD

**Issue by tomprince** [Reviewable/Reviewable#101]
(http://5digits.org/pentadactyl)

When I try to open a new inline-comment, when using pentadactly, it opens a new comment, and then immediately hides it again. If I double click, it appears to properly open it.

**Comment by pkaminski** [comment]
Sounds like pentadactyl is causing the new draft to lose focus somehow, which will cause Reviewable to delete the draft if it's empty.  There's a somewhat delicate dance of DOM updates, animation, and focusing that takes place when creating a draft, so it may not take much to disrupt it.  I'm not able to go digging into the add-on to figure out exactly what's going on but would be happy to assist you (or the add-on's developers) if you'd like to investigate further.
