### ISSUE TITLE
Can I add more context before and after changes?

### ISSUE THREAD

**Issue by xEtherealx** [Reviewable/Reviewable#1010]
I typically want to see more context before and after changes when reviewing code. Is it possible to override this via stylesheet? I checked the [docs](https://docs.reviewable.io/tips.html#visual-tweaks) but don't see this mentioned.

**Comment by earlAchromatic** [comment]
You can expand the diffs - see this [section of the docs on collapsed code](https://docs.reviewable.io/files.html#collapsed-sections). Is that what you are looking for?

**Comment by earlAchromatic** [comment]
There is also an [open issue](https://github.com/Reviewable/Reviewable/issues/304) for exposing more control over how many lines of context are shown around changes, in case you want to track it.

**Comment by xEtherealx** [comment]
> There is also an https://github.com/Reviewable/Reviewable/issues/304 for exposing more control over how many lines of context are shown around changes, in case you want to track it.

Yeah that's what I'm looking for; expanding is fine but super cumbersome given the frequency that I'm doing it!

**Comment by earlAchromatic** [comment]
Gotcha! Going to close this as duplicate then. There is a lot you can do with the custom CSS but I'm afraid it won't work in this case, sorry.

In case you missed it though, you can click on the function (or class name) at the top of the diff, which is slightly lighter in color and that will expand the entire function. That may save you a few clicks.

**Comment by xEtherealx** [comment]
@earlAchromatic Re: the documentation,

```
If you see a small, light-colored declaration immediately below the collapsed section, this indicates the nearest syntactic unit that the code below is a part of — e.g., a function or a class. You can click this signature to expand the diff to show all of the syntactic unit.
```

I usually do not see this, and never noticed it but now that I'm looking for it I do see it *sometimes*... is it a bug that I'm not always seeing it? Seems like a useful feature!

**Comment by pkaminski** [comment]
This feature relies on our syntax highlighting assigning the right classes to code tokens.  If it's not working, it may be that highlight.js doesn't know how to highlight the file correctly, or it's assigning classes that we don't expect.  A pointer to the review (or screenshot + details if private) can help us figure out what's going on and perhaps fix it!

**Comment by xEtherealx** [comment]
@pkaminski I can't share a PR (Cruise Automation) but these two screenshots show what seems to be an easy case for detection. This is Go code.

![image](https://user-images.githubusercontent.com/3417501/222859693-b5b963b3-3b50-43cf-86cd-0be57d703c1f.png)
![image](https://user-images.githubusercontent.com/3417501/222859717-48352f7b-62ca-4b5f-ab67-c195c31f2a5e.png)

**Comment by pkaminski** [comment]
Reproduced and fix in hand -- thanks!

**Comment by pkaminski** [comment]
Fixed on reviewable.io.
