### ISSUE TITLE
Forever "Resuming session"

### ISSUE THREAD

**Issue by DamienCassou** [Reviewable/Reviewable#1011]
Since yesterday evening I've got the "Resuming session" message:
![image](https://user-images.githubusercontent.com/217543/222448418-53fa1ddb-d285-4725-9256-888d56b0b931.png)

This stays like this forever so I can't review. The problem happens in both Chromium (private navigation) and Firefox.

**Comment by fahhem** [comment]
Hello @DamienCassou , thank you for the report! Could you [open the console](https://developer.chrome.com/docs/devtools/open/#shortcuts) and screenshot or copy-paste any errors you see? That way we can track them down on our side.

After that, so you can continue, have you tried logging out and back in? Or clearing your cookies for our website?

**Comment by pkaminski** [comment]
Also, if there's nothing in the console, please try loading the page with `?debug=workers` appended and check again.  (A good chunk of the session resumption code lives in a shared worker, and this option forces the worker in-process so it will output to the tab's normal console.)

**Comment by DamienCassou** [comment]
It seems the problems happens especially when I open https://reviewable.io/reviews/foretagsplatsen/monitor/10517:
![image](https://user-images.githubusercontent.com/217543/222528795-272529f4-cbf3-401c-92ba-15e6e346688c.png)
![image](https://user-images.githubusercontent.com/217543/222528933-f0e5fd73-8705-4537-937f-5730d0c2fcb8.png)

Adding `?debug=workers` doesn't seem to print any additional information. 

I've seen the problem in other PRs (after I visited the one above) but right now it seems 10517 is the only one failing.

> After that, so you can continue, have you tried logging out and back in? Or clearing your cookies for our website?

I tried in Chromium which I never use: in both private mode and in a guest profile.

**Comment by pkaminski** [comment]
That's exceedingly strange.  Could you please try with `?debug=firebase` and report what gets logged to the console?  I'm particularly interested in the `onAuth` message:
![image](https://user-images.githubusercontent.com/1646896/222543241-1ab4d679-31bf-4ad0-bdfe-f5541542c8b1.png)
And any responses to its callback:
![image](https://user-images.githubusercontent.com/1646896/222543389-241ca9a2-81e0-4c38-b66a-cb4aae247474.png)
But anything else might be useful too.

**Comment by DamienCassou** [comment]
I don't see any response:
![image](https://user-images.githubusercontent.com/217543/222549551-a51dd46d-f5a4-4ec5-98a3-381b92e130f5.png)

That's all I see.

**Comment by pkaminski** [comment]
I assume it's the same if you try with `?debug=workers,firebase`?  This means that either the messages aren't getting to the worker, the worker isn't receiving them, or the worker isn't processing / replying correctly.  This is going to be pretty tricky to debug -- how comfortable are you with JS and your browser's built-in debugger?  One simple thing to try would be to run with `?debug=workers`, switch the JS console's context to `21585bb6.truss_worker.js`, and check whether `Fireworker._firstMessageReceived` is `true`.

**Comment by DamienCassou** [comment]
It feels like the browser manages to load the page a bit more:
![image](https://user-images.githubusercontent.com/217543/222668719-cc10a551-1388-46f4-a511-e57e4a809ad1.png)

But the browser is unresponsive. 

It seems I got an answer to the oAuth message:
![2023-03-03_09-16](https://user-images.githubusercontent.com/217543/222668873-87ccbe27-c4b9-490d-8705-068d8f7f8cd4.png)
(I drew 2 white rectangles to hide what I thought was private information)

I can find my way with the browser's debugging tools.

Here is a screenshot I took from Chromium. I'm not sure where I can find `Fireworker._firstMessageReceived` given that the debugger doesn't pause anywhere:
![image](https://user-images.githubusercontent.com/217543/222670870-e2c74ac5-8016-4ce4-bbd7-c11b3bee7d03.png)

What about a pair-programming session? I'm in Paris/France timezone and can make myself available provided it's not in the middle of the night.

**Comment by pkaminski** [comment]
Hmm, this additional information changes things.  It doesn't look like a session resumption issue any more but rather some kind of performance problem.  If you open Chrome's task manager (`shift+esc`), can you tell whether the main Reviewable tab or one of the shared workers is maxing out the CPU?  If it's the main tab, can you try running `Truss.computedPropertyStats.log(10)` in the console after it's been stuck for a bit and report the output?

Pair programming sounds good though it might be hard to sync up.  Would you be available around 7-8pm your time at some point?

**Comment by pkaminski** [comment]
Hey @DamienCassou, are you still seeing this?

**Comment by DamienCassou** [comment]
Hi @pkaminski,

> are you still seeing this?

yes

> can you tell whether the main Reviewable tab or one of the shared workers is maxing out the CPU? 

![2023-03-08_17-02](https://user-images.githubusercontent.com/217543/223764982-44a4ef36-e348-443a-85fb-39145ef222a2.png)

> can you try running `Truss.computedPropertyStats.log(10)`

I can't interact with the browser while the page loads so I can only do that after I let Firefox kill the process:

![2023-03-08_17-03](https://user-images.githubusercontent.com/217543/223765382-b7bb2034-a6ff-438b-bfa7-18bb0fd22725.png)

> Would you be available around 7-8pm your time at some point?

what about Thursday evening (for me) then?

**Comment by pkaminski** [comment]
OK, this is looking more and more like a good old performance (or infinite feedback loop) issue.  Did you let the page run for something like 2-3 minutes before killing the process and capturing the stats above?  If so, it looks like most of the time was spent in endlessly recomputing properties of the diff.

Is there anything unusual about the 10517 PR?  It looks to me like it has a lot of revisions but not too many files.  Does it load OK for other people?  Did it ever load OK from you, and if so about when (in terms of PR progression) did it start getting stuck?

I could make your Thursday evening but let's see if it's necessary first -- given the emerging shape of this problem there may not be much on-the-spot debugging we can do.

**Comment by DamienCassou** [comment]
>  Did you let the page run for something like 2-3 minutes before killing the process and capturing the stats above?

I haven't measured the time. Here is another one after more than 3 minutes:

![image](https://user-images.githubusercontent.com/217543/223841417-581ab222-af97-49bb-a7f0-c835db924a0c.png)

> Is there anything unusual about the 10517 PR?

Nothing I can think of.

> It looks to me like it has a lot of revisions but not too many files.

The PR was 9 commits which were rebased 3 times and we review by commit (= 27 revisions)

> Does it load OK for other people?

It loaded ok for the PR author at least. I can ask more colleagues if you need.

> Did it ever load OK from you

when there were only 9 revisions I did a first review without any problem. After the first rebase (= 18 revisions) I wasn't able to review anymore. I have already reviewed PRs with more revisions without problems.

**Comment by pkaminski** [comment]
Thanks.  Based on the information you reported so far I have a sneaking suspicion that we're caught in some kind of loop that keeps resetting the diff bounds on all the files.  As default bounds are user-specific it would also explain why this is happening for you but not for others.  Could you please load the page with `?debug=bounds` and report what gets logged to the console?  (If I'm right it's going to spam the console with tons of repetitive messages, so a representative sample that covers a full cycle of the presumed loop will be sufficient.)  Thanks!

**Comment by pkaminski** [comment]
BTW, given that you can't really use the console while the page is looping, there's probably not much point in doing a pair debugging session.  I think the best way forward will be for me to take a look at what you report for `?debug=bounds`, add more instrumentation, then repeat until we've narrowed things down enough for me to take a stab at a solution.

**Comment by DamienCassou** [comment]
Bad news, I can't get any information:
![2023-03-09_09-22](https://user-images.githubusercontent.com/217543/223965277-f4660e01-b9d7-4b97-a971-b85a0f39905d.png)
![2023-03-09_09-32](https://user-images.githubusercontent.com/217543/223965281-5465ec8e-df30-4949-8908-6900fe7651be.png)
 
Today, I haven't seen the message of Firefox asking me to kill the process in the page... Don't know why. Could it have an impact on the above result?

**Comment by DamienCassou** [comment]
Right after I did the experiment above, I tried to open a [small PR](https://reviewable.io/reviews/foretagsplatsen/monitor/10556) but got exactly the same issue: forever "resuming session".

**Comment by pkaminski** [comment]
Damn, that was my best bet to get something.  :(  I'm not sure how console logging works when JS won't relinquish the event loop but I was hoping the messages would still make it out somehow.  If Firefox isn't giving you a chance to kill the process, could you try manually pausing the code in the Debugger pane?  It's a long shot, but perhaps that will release buffered console messages.

Another (not great) idea would be to sample stack traces while it's looping by repeatedly pausing/resuming the code, and grabbing a copy of the stack each time.  Or maybe you can capture a performance trace in Chrome, if it'll let you?

At this point I'm pretty sure the issue isn't due to the size of the PR but rather some unusual configuration of revisions and personal progress state.  Not sure why it's hitting you specifically this hard, though.

**Comment by DamienCassou** [comment]
Adding `workers,firebase` to the `debug` query parameter gave me a lot of output, including what I think interests you:
![2023-03-10_21-12](https://user-images.githubusercontent.com/217543/224419772-cc2c4b94-ee0c-49f8-8055-cbdd73b3a64b.png)

**Comment by pkaminski** [comment]
Yes!  I don't know why adding more debug flags would get the console output unstuck but this gave me the information I needed.  I believe the root cause is a bug in the diff bound proposal logic working in commit-at-a-time review mode when a file was renamed and later reintroduced into the PR and some other state conditions hold.  I have a potential fix in hand that I'll push after review and let you know when to try again.

Thanks for working with us to get this bug identified and fixed, and sorry for the trouble!

**Comment by pkaminski** [comment]
All right, I deployed the putative fix, please give it another try.  If it's still stuck, please post any updated debug traces.  Thanks!

**Comment by DamienCassou** [comment]
The bug is fixed. Thank you very much!!
