### ISSUE TITLE
Is it possible to ignore, override, or configure the "pending discussions" check in github status?

### ISSUE THREAD

**Issue by lassemaatta** [Reviewable/Reviewable#1012]
Background:
- We use Reviewable for reviewing PRs
- Each PR is also subject to CI testing
- Both of these operations are shown as "checks" on the PR page in Github

The problem(s):
- It is almost impossible to satisfy the `"Pending — N files, M discussions left (<list of usernames>)"` check. Even if every participant approves the PR and comment, the check still complains about something.
- Therefore, the PR status in the PR listing in Github will forever show a orange symbol ("1/2 checks OK") and it's difficult for developers to see at a quick glance which PR's need attention.

Would it be possible to somehow control the criteria by which Reviewable decides whether or not the corresponding check is passed? E.g. something like "at least one participant has approved the PR"?

**Comment by fahhem** [comment]
Hello Lasse,

Yes, you can replace this condition with whatever you like: https://docs.reviewable.io/repositories.html?highlight=complet#custom-review-completion-condition

There are examples here https://github.com/Reviewable/Reviewable/tree/master/examples/conditions that you can base yours on as well

**Comment by lassemaatta** [comment]
Wow, great, that looks exactly what I was looking for! Thanks a lot!
