### ISSUE TITLE
Ignore author's file-review status when determining when to show files

### ISSUE THREAD

**Issue by xEtherealx** [Reviewable/Reviewable#1013]
If an author marks files as reviewed, they're collapsed by default. This is misleading when there are multiple reviewers, and while there may be some reasons to allow authors to mark files as reviewed I suspect that in 95% of cases the author's review status should not be factored into decision making, so this issue may extend to other surfaces in the product as well.

![image](https://user-images.githubusercontent.com/3417501/222805877-00529d9a-5561-46d6-8771-930de3e66d3c.png)

**Comment by pkaminski** [comment]
We're tracking this in #866, and have a plan for addressing the issue, just no time to execute on it yet.  😓
