### ISSUE TITLE
"New Comments for Me" seems to be over-inclusive

### ISSUE THREAD

**Issue by nate-thirdwave** [Reviewable/Reviewable#1017]
When the "new comments for me" section was enabled, if I go to a repository-specific page `https://reviewable.io/reviews/orgname/reponame#-` I now have some 200 reviews that come up for me as "comments for me". As far as I can tell, I haven't actually been mentioned in any (most?) of these, though if I pop to the review any comments are marked as "new comment", which I assume is part of the system?  I can't tell if this is because I had the misfortune of clicking on these reviews in the past, or if this listing is somehow the expected behavior?

I don't see this section on the general (all repositories) review page.

**Comment by pkaminski** [comment]
You're right, that section's selector is overbroad -- it's more like "reviews where I have unread comments, not necessarily for me".  It works fine on the main dashboard since all reviews there have something to do with you, but not so much on the repo-specific dashboards.  Let me see if I can fix it.

**Comment by pkaminski** [comment]
I made a try at fixing this but the semantics around which discussions are "for you" are pretty subtle.  Could you try again and let me know if things have improved?  Thanks.

**Comment by nate-thirdwave** [comment]
Well that certainly dropped the number displayed for me, though the words "comments for me" don't seem to apply still.  I'm not seeing mentions for me (which I would expect to show up in a Mentions section anyway). Is the general concept "Reviews that you've ever looked at that have new comments"?  If so, then perhaps the logic is correct, but the useful thing would be to push the section down to near the bottom, since "I've clicked in on this review once" is only slightly better than "Reviews Unrelated to me" in terms of my responsibilities to the review.  I might also propose the section name "Viewed reviews with new comments:" or somesuch.

Alternatively, I could see any of the following:
 * Being able to turn off lurker tracking and thus turn off the "I viewed this" concept, either org-wide, or personally
 * Being able to resign from such marked reviews
 * Being instead able to explicitly follow the review to populate this section. I think there's a GH "watching" concept, so maybe hook that directly?

**Comment by fahhem** [comment]
The new update should only be comments from threads that mentioned you. We'll look into the discrepancy.

Assuming the section only shows up when there's a review that actually mentions you, would that be acceptable? We never wanted this section to track all lurked reviews after all

**Comment by pkaminski** [comment]
We made further updates to the selection logic for this section -- could you check if it helped @nate-thirdwave?  I think we're now about as picky as we want to get, but if you see any more PRs in there that you think don't belong please send over repos/PR numbers along with reasons they ought to be excluded.  Thanks!

**Comment by pkaminski** [comment]
I'm going to assume this is fixed -- please let me know otherwise and I'll reopen.  Thanks!
