### ISSUE TITLE
Binary files rendered on one-file page

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#102]
I'm enjoying the new one-file-per-page view! I noticed that binary files are getting rendered on it, though, whereas they're suppressed on the single-page view.

For example: https://reviewable.io/reviews/hammerlab/cycledash/617/tests/pdifftests/images/website_about-page.png#..r2

**Comment by pkaminski** [comment]
Apologies, I overloaded the meaning of a flag inappropriately.  Should be fixed now.
