### ISSUE TITLE
Wrong dismisser shown in disposition dropdown

### ISSUE THREAD

**Issue by pkaminski** [Reviewable/Reviewable#1020]
After being dismissed from a discussion by a colleague, the dispositions dropdown is showing @misha-ridge as having dismissed himself:
![Screenshot202023-03-23%2009-45-34](https://user-images.githubusercontent.com/1646896/227265938-de2d0a50-6bb1-4df9-a66f-675f81111085.png)

**Comment by misha-ridge** [comment]
For the colleague who is not a dismisser, this renders properly.

**Comment by snoack** [comment]
How can I reproduce this? In my test environment, I don't even have the option to set disposition to dismissed.

**Comment by snoack** [comment]
@pkaminski  I tracked down that in `discussion-participants.vue`, we use the value of `locator.tracker.currentParticipant.$key` to be shown here which is clearly inaccurate (except for the user that issued the dismissal). I could easily remove the username here, if that is an accepted fix? Or is there a straight-forward way to get the name of the user that dismissed the discussion?

**Comment by pkaminski** [comment]
We store a `dismisserKey` in the tracker, we should be using that.  I suspect we already do in the other-participant disposition dropdown, but messed up the self-disposition dropdown, which needs different code.

**Comment by snoack** [comment]
Unfortunatelly, `tracker.dismisserKey` is `undefined` here. In `discussion-other-participant.vue` we use `participant.effectiveDismisserKey`, but that `participant` object doesn't exist in the context of `discussion-participants.vue`.

**Comment by snoack** [comment]
Figured it out, `locator.tracker.currentParticipant.effectiveDismisserKey` does the trick.
