### ISSUE TITLE
Add a button top right of comments to open the file in the Github edit UI

### ISSUE THREAD

**Issue by qwertzguy** [Reviewable/Reviewable#1024]
When fixing a small nit or typo it can sometimes be annoying to have to context switch the local dev environment just for making that small change a pushing a new commit.
A solution could be to add a new button in the top right of comments to open the file in the Github edit UI which has the URL of form: https://<github_instance_domain>/<company_name>/<repo>/edit/<branch_name>/<file_path>?pr=%2F<company_name>%2F<repo>%2Fpull%2F<pr_number>

**Comment by fahhem** [comment]
NOTE: This is valid internally, but the public release doesn't yet have the `{{headBranch}}` feature deployed. It will be valid early next week. I'll update this when that deploy goes out.

This currently is possible, here's the template string:
```
https://github.com/{{owner}}/{{repo}}/edit/{{headBranch}}/{{path}}?pr=%2F{{owner}}%2F{{repo}}%2Fpull%2F{{pr}}
```
You can configure it in your preferences. See the docs here: https://docs.reviewable.io/accountsettings.html?highlight=editor%20link#external-editor-line-link-template
![image](https://user-images.githubusercontent.com/306100/227670691-f06874bc-7004-4178-86b3-de2f279f77d0.png)

**Comment by qwertzguy** [comment]
Ah nice! Actually my first request when talking with @pkaminski was about adding a branch variable to the custom line link, because that's exactly what I tried to do at first.
But then I realized that I would still want to keep the possibility of opening in VScode when I'm going through a PR with more comments or ones where I prefer to have an IDE to make the change. So ideally I would want two buttons.

**Comment by fahhem** [comment]
We've added the headBranch and baseBranch variables, and even added a GitHub item in the dropdown so it's easy to use.

For being able to edit in GitHub and VS Code, we are going down a path of adding the link to open or edit in GitHub in another, new UI that we'll be launching soon. However, we wanted to get some version of this into production so it could be used in the meantime.

We'll keep this issue open against the ability to have both buttons (VS Code / your editor + GitHub) available.

**Comment by qwertzguy** [comment]
That's awesome! Thank you!
For the Github item in the dropdown, do you know if it automatically uses the github enterprise domain name if the repo is not on github.com?

And for the new UI that you'll be launching: I realized another use case which could be very convenient is showing a warning + button when github detects and merge conflict and having a button to open the github merge conflict editor UI (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github). Right now, from the Reviewable UI it's difficult to see when a conflict is present with the base branch and requires going to github to open the resolution UI (if it's relatively trivial and doesn't require an IDE of course). I think it could be awesome if it even show merge conflicts in the dashboard and place the PR in awaiting your action when that is the case.
I can make a new issue with this suggestion, but wanted to asked about it here since it's a bit related.

**Comment by pkaminski** [comment]
> For the Github item in the dropdown, do you know if it automatically uses the github enterprise domain name if the repo is not on github.com?

Yup, it adapts automatically to your environment.

> I can make a new issue with this suggestion, but wanted to asked about it here since it's a bit related.

Please open a separate issue --  it's related, but dealing with conflicts will likely need some new bits of UI to slot into.  Thanks!

**Comment by qwertzguy** [comment]
I opened #1039 for the other suggestion

**Comment by pkaminski** [comment]
We now have an item in the (new!) comment dropdown menu that links directly to the GitHub file editor, so it's possible to use it concurrently with a custom external editor config.
