### ISSUE TITLE
Opening user preferences dropdown changes code coloring CSS

### ISSUE THREAD

**Issue by fahhem** [Reviewable/Reviewable#1025]
Before:
![image](https://user-images.githubusercontent.com/306100/227669495-ca38d58c-fb10-4cba-979e-86e11fbbdc05.png)

Then I open the dropdown:
![image](https://user-images.githubusercontent.com/306100/227669514-07b26393-ab8d-4220-ba92-913086341ad5.png)

After:
![image](https://user-images.githubusercontent.com/306100/227669521-9509e207-0ecb-414b-bdfd-854d1b9e5573.png)

Refreshing resets the CSS

**Comment by pkaminski** [comment]
Looks like you have a 100% contrast setting and it doesn't get applied on page load for some reason.  This is a job for @earlAchromatic!
