### ISSUE TITLE
Consider adding a link back to reviews when scrolled to end of a review

### ISSUE THREAD

**Issue by fahhem** [Reviewable/Reviewable#1026]
From support@ email:

> Right now, you have to scroll back up to top to get the link to the main review list. You've got a lot of empty real estate on the screen, consider adding a link to jump back to the review list WITHOUT having to scroll back up to the top of the page. Or alternatively, use the "upwards scroll slides out the header" model. (See filmstrip on top of https://pinchofyum.com/ for example of what I mean.)  Or just duplicate the 'Reviews' button in left side of footer, since that is usually visible when you've scrolled to the end of a review.

**Comment by nneul** [comment]
@pkaminski Change is very appreciated, please consider adding same link to the result screen on a review after a merge.

**Comment by pkaminski** [comment]
Could you post a quick screenshot of a sample page where you'd expect to see the link but it's not showing?  There are a few states where I know it won't show but it's not clear which one you're running into.  Thanks!

**Comment by nneul** [comment]
![image](https://user-images.githubusercontent.com/828492/229227676-7e8371e5-7d9d-4b46-b77f-828f974c23d2.png)

It looks like "If I'm targetted to do the merge", it doesn't show up. Will try to pay attention on next review I do if different than above.

**Comment by pkaminski** [comment]
Thanks!  I can certainly add the link there, but is it really needed?  I expect that when the page is in this state, you're likely to never bother scrolling down in the first place and thus could use the link in the page header.  Or would you like it just for consistency?

**Comment by nneul** [comment]
I _think_ in the scenario I saw it, it wasn't my review, and I clicked to approve it, then there was no link to jump back. (It's odd, I get offered to performe the merge on some reviews that are not mine, but not others.)

Not 100% sure though, will pay closer attention on my next review that I complete.

**Comment by fahhem** [comment]
@nneul Since the medium term plan is to make the bunny logo take you back to the dashboard, we're going to avoid cluttering the UI too much. That version of the review page is very short, so scrolling up isn't a chore, so the tradeoff of usability and clutter, to us, falls on the other side.

Is that reasonable to you? Please feel free to reopen if you feel like we don't understand that workflow enough.
