### ISSUE TITLE
Poor performance on large review

### ISSUE THREAD

**Issue by larsbergstrom** [Reviewable/Reviewable#103]
Some of our reviews are pretty large. For example: https://reviewable.io/reviews/servo/servo/6141

On a year-old (but max specs) Macbook Pro, this gets the "slow script dialog" using Firefox and takes a very long time to load in Chrome as well (~5 seconds).

**Comment by pkaminski** [comment]
Yup, this is a limitation that's pretty much down to Reviewable's architecture, and is only likely to be addressed by faster VMs and Moore's Law.  Reviewable is designed for reviews of up to ~50 files, maybe 100 in a pinch -- for anything above that, the design goal is just to not crash the page / browser.  This still compares well to GitHub, which takes ~25 seconds to load the "files changed" tab initially in Chrome on my machine, and ~10 seconds to switch to it even when already loaded!

A partial workaround is to open the review in single-file mode by {ctrl,cmd,shift}-clicking on a filename in the matrix, but you'll lose a few features that way.  (To avoid loading the all-files page at all, you can just append anything to the URL path and it'll open in single-file mode with no file focused, like https://reviewable.io/reviews/servo/servo/6141/foo.)

But the real question I have for you is: how do you review such PRs?  A file-by-file, line-by-line review doesn't appear feasible to me at this scale, so what's the process?  Perhaps Reviewable could be specialized to better support that.

**Comment by larsbergstrom** [comment]
Typically, we review them commit-at-a-time. Even then, of course, some of the commits are rather huge, but that's definitely part of the reason we wanted the ability to do reviews of individual commits.

I suspect that our old system (Critic - https://critic.hoppipolla.co.uk/) prepared the info on the server side once instead of having everybody do it on the client side, but @jgraham can probably talk about how it handled these mega-reviews better than I.

We don't have them continuously, but I'd say we have something of this size on Servo about once a month, usually related to upgrading a major component or version of the compiler. Of course, we hope these would decrease over time as things stabilize, but we've been saying that for *years* :-)

**Comment by pkaminski** [comment]
Are you saying that you actually review ~9000 line deltas line-by-line?!  That's impressive, and possibly insane.  :smile:  Can you try out the single-file mode and let me know how that works for you?  At this point, I don't think there's any way to increase the performance of a monster review like that besides somehow cutting down on the number of files on display.

**Comment by jgraham** [comment]
My experience is that large projects always have occasional large diffs resulting from refactorings or upgrading dependencies or whatever. Especially for refactorings it's normal to review these, and therefore pretty annoying if the review tool can't handle large reviews.

Critic did indeed precompute some more expensive things. In particular I believe it computes the syntax highlighting in a background worker process on the server rather than on-demand or in the client.

**Comment by larsbergstrom** [comment]
Unfortunately, the single-file mode doesn't help as much for our workflow as, say, a single-commit mode would (a la #104).

**Comment by pkaminski** [comment]
So, given that large reviews are pretty rare, I think that taking a longer time to load the page is a reasonable trade-off: you'll be staring at the review for hours and hours anyway.  Reviewable's architecture also precludes precomputing things server-side, as mentioned earlier in the thread, and this allows me to make some strong guarantees about where your code will (and won't!) be stored, which is important for some of the private repo customers.

I will look at ways to address #104 and #61.  I'll also see if I can stagger building the UI for large reviews to give time slices to the browser event loop and avoid the "slow script" warning, but this is not a high priority since there's an easy workaround: patience.  :smile:

Sounds good?

**Comment by larsbergstrom** [comment]
The main alternative that the Firefox developers I've talked with have suggested (since you can't do server-side diffs) is to switch to using Web Workers (https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers ). Supported in pretty much every modern browser, it's a nice way to offload really long script computations to a background thread so that you don't get a slow script dialog (in Firefox) or just a UI that is unresponsive for tens of seconds (Chrome and debug builds of Firefox).

We're hitting this performance issue regularly enough on Servo that I'm getting a lot of pressure to find another code review alternative.

**Comment by pkaminski** [comment]
I already use a web worker for everything that doesn't touch the DOM, so this delay is most likely due to the initial creation and data-binding of the UI.  Just to be clear: the only concern is the initial delay when loading the page, *not* the performance once the page has fully loaded?

**Comment by larsbergstrom** [comment]
The load time is part of the issue. For example, in Chrome (which you've mentioned is the primary target), it takes over a minute to load: https://reviewable.io/reviews/servo/servo/6150

The other part is that even once it's loaded, Chrome takes over 1.5GB of RAM. It also takes a further three minutes (on a two year old macbook pro) before you can scroll to a position without a bunch of scroll position jank.

So it's a bad enough experience that I'm getting a lot of pressure to buy/build/partner for something that works for reviews this big. I mentioned that we usually only have one a month or so, but unfortunately when they're that big a significant number of people are looking at them and they take at least a couple of weeks to land, so the performance affects a bunch of the team quite heavily.

Is there any additional data I can get? I'm happy to use the FF or Chrome dev tools to get you a timeline view, etc. if that will help with profiling.

**Comment by larsbergstrom** [comment]
It does sound like the initial load time is the biggest issue for the team, though; we can always throw more RAM at the problem from our side :-)

**Comment by pkaminski** [comment]
> The load time is part of the issue. For example, in Chrome (which you've mentioned is the primary target), it takes over a minute to load: https://reviewable.io/reviews/servo/servo/6150

That's no pull request... that's a small moon!  I duplicated this into my dev system and will try to whittle down the load time a bit.  There's no single prevalent cause so it'll take a number of enhancements / fixes -- I'll keep this thread updated.  The first one is out now:  the review will automatically go into single-file mode when a large number of files is detected.  This brings down the load time some, and reduces the memory footprint to <600K in Chrome on my machine (though that will grow as you navigate between files).  More to come!

**Comment by larsbergstrom** [comment]
Fantastic - thanks a ton for looking into this!

**Comment by pkaminski** [comment]
Small update: I made the status bar "current file" mechanism much more efficient, getting rid of N*M table cells (N = number of files, M = number of revisions).  The PR of doom now loads about 2x faster on my machine, takes up 532MB, and scrolls smoothly within seconds after finishing loading.  I still have another 2 or 3 improvements I want to try so things should get even better tomorrow, with any luck.

**Comment by pkaminski** [comment]
Another update: I rewrote the revision cell renderer and inlined some templates for further performance gains.  Next up is redesigning the data sync mechanism to be more lazy, which in preliminary testing looks like it'll net another 2x performance increase or so.

**Comment by larsbergstrom** [comment]
Been asking around a little and folks are impressed, especially since the huge SM review is now much more usable - nice work!

**Comment by pkaminski** [comment]
I've now deployed the last batch of optimizations on my to-do list: lazy datastore bindings that postpone a lot of work until data starts changing, an avatar cache, and faster rendering for file matrix updates, batch diff bounds selection, and marking a file as reviewed.  At this point, the PR'o'doom loads in <15 seconds on my machine (to fully usable state), which I think is reasonable for something of that size, and selecting diff bounds for all 200+ files is fairly usable.

Can you report on what kind of performance your folks are now seeing on their machines / in Firefox?  Perhaps if it's good enough we can close this issue.  :smile:

**Comment by larsbergstrom** [comment]
@pkaminski I'm super happy! The review loads in < 10 seconds on Firefox (even faster than Chrome), so I'm OK with closing this. Thanks for all your hard work!

**Comment by sseo289** [comment]
https://crackzero.com/ccleaner-professional-crack/

https://crackzero.com/ccleaner-professional-crack/

https://crackzero.com/ccleaner-professional-crack/,
,

,
,
,


,
