### ISSUE TITLE
Ability to see if there is a repo set as the prototype, and which one it is

### ISSUE THREAD

**Issue by fahhem** [Reviewable/Reviewable#1035]
https://docs.reviewable.io/repositories.html#prototype-settings-for-new-repos

This currently just exposes a button to set it. It would be good if this indicated if you were going to override the current prototype repo, and for which repo is the current one.

**Comment by BlackVegetable** [comment]
This is challenging to investigate from the repositories page due to how often (always) that page crashes with a pop-over modal when someone with admin access to thousands of repositories tries to load it.

**Comment by fahhem** [comment]
Turns out this just needs better docs, since there is a tooltip that (if you're an owner) will either say "No prototype repository set." or "This is the current prototype repository" or "The current prototype repository is ____".

@BlackVegetable I'll open a separate issue for stability of that page
