### ISSUE TITLE
Maybe hide files not in the selected review range?

### ISSUE THREAD

**Issue by larsbergstrom** [Reviewable/Reviewable#104]
When reviewing commit by commit on PRs like https://reviewable.io/reviews/servo/servo/6175, I frequently am scrolling through pages and pages of "File not in pull request at selected revision." Since selecting commit ranges is already pretty advanced, maybe it's not too confusing to hide the files that are not in scope?

**Comment by pkaminski** [comment]
This is similar to #61 -- I'll try to think of a good way to address them both.  In the meantime, the same workaround should work: use n/p (or N/P) to cycle through files, as these shortcuts will automatically skip empty diffs.

**Comment by pkaminski** [comment]
This is now implemented.  Note that files will still show up anyway if they have comments, so as you progress through a review more and more "useless" files will appear.  I plan to address this via #94.
