### ISSUE TITLE
Color highlighting of patch file whitespace

### ISSUE THREAD

**Issue by jwnimmer-tri** [Reviewable/Reviewable#1041]
When displaying the contents of a `*.patch` file under review, we will often see something like this:

![image](https://user-images.githubusercontent.com/17596505/230106321-e701e1b9-9710-40b5-b85d-637aa6fdd7cb.png)

Note the red dot on line 7.  (This example is from RobotLocomotion/drake#17518.)

By habit, my team's reviewers will complain about trailing whitespace at the end of a line. Our code style guide disallows it, our linters find and fix it, and it almost never shows up in reviews. When it does, it's almost always a "nit" that needs to be fixed.

The cases where it's not a problem is where it is _required_ by the file format. In patch file hunks, a line with a single space is how it denotes an unchanged blank line in the patched file. Removing the space would break the patch.

However, the "little angry red dot" has conditioned my team to post a review discussion asking for it to be removed. Not everyone on the team is familiar with the syntax files of patch files.

My request is that for mime type `text/x-diff` files, the styling of line 7 here somehow changes to be distinct so that reviewers are less likely to jump on it.

I don't have great ideas on what that might look like.  Maybe a non-red `&blank;` (␣) instead?  Or maybe the leading space should be uniformly formatted on _all_ lines even those with text afterwards:

```
·}
·
·void ConsoleReporter::PrintHeader(const Run& run) {
+  const bool show_allocs = (run.memory_result != nullptr);
·  std::string str =
```

That would be consistent with "in patch file hunks the first character in a line is always special".

**Comment by fahhem** [comment]
Thank you @jwnimmer-tri! We agree that that should be fixed and will get it done soon.

**Comment by pkaminski** [comment]
Hey @jwnimmer-tri, what do you think about just rendering those initial spaces as, well, spaces?  I'm hesitant to show any injected characters in anything other than red, as it can lead to confusion about what's in the actual file vs just an artifact of the diff renderer.

**Comment by jwnimmer-tri** [comment]
Sure, I think that's just fine.  Having a plain blank space there should meet the goal of avoid drawing reviewers' eyes to the line.
