### ISSUE TITLE
"Thanks" disposition

### ISSUE THREAD

**Issue by jwnimmer-tri** [Reviewable/Reviewable#1043]
I am generally not a fan of "Thanks" becoming magic for "Informing" for all the same reasons as https://github.com/Reviewable/Reviewable/issues/944 -- it spams people besides the author with red bubbles.  I now need to train my team to never open a new thread with the word "Thanks" when they intend to only communicate with the author.

Saying "Thanks for this fix but it missed condition quux also" also does not work as intended -- it both spams other reviewers, and also doesn't end up blocking the review.

When the magic keywords go wrong, it's bad UX.  I would much rather that reviewers need to click their discussion disposition between blocking & discussion a little bit more often, than to have the tool infer _wrong_ dispositions.  False negatives are not very difficult to overcome.  (Even a spurious blocking "Thanks looks great!" is easily dismissed by the author.)  False positives are a real and surprising problem. The obvious words like "nit" and "typo" make a lot of sense -- very low false positive rate.  Casting a wider net with lower-precision terms like "Thanks" and the associated false positive rate is a detriment to usability.

---

Today we found another, more acute problem with "Thanks":

A typical discussion might go like:
- Reviewer posts "Here the code forgot to check for foobar condition." (blocking).
- Author fixes and pushes the code fix as well as some bonus fix as well, perhaps fixing some nearby documentation that was not quite precise and replies with "Done".
- The reviewer replies with "Thanks that's even better!" and clicks the "Resolved" button to close the discussion.

What happens now (apparently) is that the "Thanks" get a strikethrough and the review tool yells about not changing the disposition in the middle of a discussion.  There is no reason to strikethrough "Thanks" in this case, nor complain!  The discussion is completed, the resolution is set to resolved.  This is an unnecessary and confusing speed bump for users.

**Comment by pkaminski** [comment]
Thanks @jwnimmer-tri, you make a cogent argument as always.  We're inclined to revert the code.  @abrenneke, any thoughts given that you originally requested this feature?

**Comment by abrenneke** [comment]
While I don't quite understand the reasons and am bummed, go for it

**Comment by jwnimmer-tri** [comment]
If the problem was that "Thanks" was giving blocking by default, possibly a middle ground is "Discussing" instead of "Informing"?  Trying a few sample discussions with "nit" as a proxy for how this would work, I think it might suffice.

The main challenge is false positives for "Informing" being particularly troublesome.

**Comment by abrenneke** [comment]
I'm not picky, feel free to just undo if it's causing anyone else problems

**Comment by pkaminski** [comment]
I don't think we want to switch "thanks" to Discussing:  it's not an obvious semantic fit, the disposition already has plenty of keywords, and it would only make (some) sense for Discussing in a discussion-starting comment, which would be unlike all the other Discussing keywords.

We could try letting a first-comment (or even later-comment?) "thanks" set the disposition directly to Satisfied, though I'd need to check whether that breaks anything else in the system as we don't currently allow it.  This would avoid the over-notification problem of Informing, but not the false positives of "thanks, but".  It would also suffer from the above asymmetry with other Satisfied keywords.

At this point I think the cleanest solution is to acknowledge that the keyword is too generic and revert, but I'm going to sleep on it and see if any other ideas pop up.

**Comment by pkaminski** [comment]
After further reflection, it feels like what we're missing is another disposition type:  Informing-Author, which is resolved but when posted by a reviewer only unreplied for the PR author.  (If posted by the author it would still be unreplied for all reviewers.)  However, I'm not keen on adding more complexity to the disposition system at this point, and especially for such a minor use case.

A potential alternative might be to bind "thanks" to Discussing (as suggested above) but only for the first comment -- as a cheap facsimile of Informing-Author -- and to Satisfied if used in subsequent comments -- to avoid the crossed-out "invalid keyword" issue.  However, this doesn't address the "thanks, but" scenario and previous experiments with keywords that have different effects in first vs subsequent comments were a UX failure.

I'll revert the keyword later today unless somebody chimes in with a new idea.

**Comment by jwnimmer-tri** [comment]
FWIW, I agree with the analysis in the prior two messages.

**Comment by abrenneke** [comment]
Thanks for the discussion and thoughts! 😉

**Comment by pkaminski** [comment]
Reverted -- thanks all!
