### ISSUE TITLE
File Matrix: Collapse large groups by default

### ISSUE THREAD

**Issue by fahhem** [Reviewable/Reviewable#1047]
Large PR's (with 1k+ files) can make the File Matrix very slow to render. Consider collapsing groups (or even folders) with over 500 files since rendering them is slow, makes the page extraordinarily long, and the likelihood the user wants to do something to the whole group (mark reviewed, change the revision split, etc) is higher than they want to interact with all the files one-at-a-time, or even to interact with a specific file.

**Comment by jwnimmer-tri** [comment]
Something might have gone wrong here?

Today I've noticed that even tiny PRs like https://reviewable.io/reviews/RobotLocomotion/drake/19352 are collapsing the File Matrix by default, and I need to keep unfolding it myself often.

**Comment by fahhem** [comment]
We had an issue with this and we just deployed a fix an hour ago. Are you still seeing this?

Or are you talking about the toggling:
![image](https://user-images.githubusercontent.com/306100/236326712-8823e4bc-26e0-4995-a1af-5a1b8074e0b9.png)

**Comment by fahhem** [comment]
(you may need to refresh the tab to get the fix)

**Comment by jwnimmer-tri** [comment]
When I open https://reviewable.io/reviews/RobotLocomotion/drake/19352 (even if I force reload via "ctrl-shift-R"), I see this:

![image](https://user-images.githubusercontent.com/17596505/236328243-4ffde4ef-76b5-4964-b376-dfaa804a2ff3.png)

The matrix is collapsed by default.  I need to click on the slider-button thing to show the File Matrix table.

**Comment by fahhem** [comment]
Ah, yes, we noticed that as well. Looks like a bug that we introduced with this feature, so I'll open a new bug to track it.
