### ISSUE TITLE
Cursor navigation broken when editing multiline comments

### ISSUE THREAD

**Issue by mkow** [Reviewable/Reviewable#1050]
Hi,

Since ~today (I think) when I'm editing multiline comment drafts the cursor started to jump only between the first and the last line (when using arrow keys), there seems to be no way to place it at the other lines, even with mouse.

I'm on Firefox 102.10.0esr (64-bit). The issue is present on all PRs and all discussions inside them.

**Comment by earlAchromatic** [comment]
The issue doesn't reproduce in Firefox 112.0.2, so it seems to be specific to ESR. I was able to replicate the bug in the version you specified. We will need to investigate the exact cause.

**Comment by pkaminski** [comment]
Related issues: https://github.com/Reviewable/Reviewable/issues/869, https://github.com/Reviewable/Reviewable/issues/540.

The most likely cause is the recent extension of `user-select: none` to all elements by default.  The spec says that inputs and text areas are supposed to override any user styling in this respect but perhaps Firefox had a bug there.

**Comment by earlAchromatic** [comment]
This has been fixed @mkow.

**Comment by schreter** [comment]
> The most likely cause is the recent extension of user-select: none to all elements by default.

Ah, I was wondering why I can't copy & paste the title of the PR in the review (and other things as well). Probably it's not so good idea to mark it so everywhere.

At least any text which is dependent on the PR content (name, branch name, file names, etc.) should be definitely selectable (and ideally, where it makes sense, like the PR title, with user-select: all, so there is no need to really select it very carefully?).

**Comment by mkow** [comment]
> This has been fixed @mkow.

Works well again, thanks!

> Ah, I was wondering why I can't copy & paste the title of the PR in the review (and other things as well). Probably it's not so good idea to mark it so everywhere.
> 
> At least any text which is dependent on the PR content (name, branch name, file names, etc.) should be definitely selectable (and ideally, where it makes sense, like the PR title, with user-select: all, so there is no need to really select it very carefully?).

+1, I also find overusing of `user-select: none` quite annoying :)

**Comment by pkaminski** [comment]
Hey folks, the `user-select: none` is unfortunately needed to make multi-click text selections sane due to the lack of support for `user-select: contain` in today's browsers.  We do try to make every piece of (non-UI) text selectable or offer a copy button for it, with the exception of the toolbar because therein lie dragons.  :)  If you have specific things you'd like to be able to select/copy and can't please let us know and we'll open them up as well!  (Screenshots are ideal for that, as sometimes the same piece of information can appear in multiple spots.)  Thanks!

**Comment by mkow** [comment]
I see, too bad :( But thanks for the explanation!
