### ISSUE TITLE
Permalink to Github-initiated threads doesn't seem to work

### ISSUE THREAD

**Issue by seansfkelley** [Reviewable/Reviewable#1055]
I have a thread on a file that started with a single GitHub comment, but then moved to Reviewable for a few more comments back and forth.

I copy the permalink by clicking anywhere within the thread and copying the URL, receiving something like `https://reviewable.io/reviews/<org>/<repo>/12345#gh-123456789`. Trying to navigate to that URL in a new tab, though, I just get dropped at the top of the review page and the URL fragment changes to `#-`.

If it matters, the discussion I'm trying to link to is resolved. I _do_ get correct permalinking behavior when doing the same thing to Reviewable-initiated threads.

**Comment by pkaminski** [comment]
Use a regex, they said.  You won't have any problems, they said.  Hah!  Fixed -- thanks.  :)

**Comment by seansfkelley** [comment]
It works! Thanks much.
