### ISSUE TITLE
Improve thread permalink discoverability

### ISSUE THREAD

**Issue by seansfkelley** [Reviewable/Reviewable#1056]
I've been assuming/telling people for years that Reviewable doesn't support permalinks to threads. Oops. I only found out about it when coming here to file a request for the feature and finding https://github.com/Reviewable/Reviewable/issues/157#issuecomment-224070213.

Perhaps a link icon in the top right on hover?

<img width="204" alt="image" src="https://github.com/Reviewable/Reviewable/assets/2101409/414cf153-43fa-4e05-a3fe-7672f7482e26">

(It does not seem to be mentioned in https://docs.reviewable.io/discussions.html either.)

**Comment by pkaminski** [comment]
Hey Sean, this is a great idea -- so great, in fact, that we're already working on it as part of #907.  We ran into some technical issues that are requiring us to shave a few yaks but it should be ready soon-ish!

**Comment by seansfkelley** [comment]
Awesome! I didn't find that issue cause I was looking for "permalink". Looking forward to it.
