### ISSUE TITLE
Post correct Reviewable status checks for merge queue commits

### ISSUE THREAD

**Issue by pcorpet** [Reviewable/Reviewable#1059]
An issue with Reviewable + Merge Queue is that the Review completion check is not run in the merge queue. Therefore if we make it a requirement for GitHub protected branches: it can be successful on the PR, let GitHub add the PR to the merge queue, and then block in the merge queue as the status is never sent.

One (maybe easy) step would be to trigger the Review completion condition on merge_queue event, and probably update the review object when that's the case so we can add custom logic on whether the check is run within the queue or before.

See an [equivalent bug](https://github.com/orgs/community/discussions/39933).

**Comment by pkaminski** [comment]
Thanks Pascal -- you're right, we need to do something about this.  Might need to pony up for a GHE license so we can test all the queue stuff...

x-ref #1053

**Comment by pcorpet** [comment]
Hi Piotr, this is blocking us to use Reviewable as of today. Is this something you think will get implemented soon? any vague ETA would be welcome

**Comment by pkaminski** [comment]
Hi Pascal, I looked into this a bit more today and see two potential blockers (besides us not having GHE Cloud to test on -- working on it!):
1.  It's not clear if `merge_group` webhooks are sent for repo-level subscriptions.  The [docs](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#merge_group) claim they're only applicable to App-level ones, and as Reviewable is an OAuth App we have no access to those.  Would you be able to take a look at Reviewable's webhook configuration in your GitHub repo and see if `merge_group` events appear on the list of recent deliveries?  (The webhook should be specced for all events, so GitHub shouldn't be filtering things out upstream.  The event also requires some kind of "merge queues" permission to receive, but I can't find a related OAuth scope so I'm hoping the `repo` scope we already request covers it.)
2. To set the correct status on the group's commit we'd need to find the reviews it corresponds to and infer a combined status from those.  However, the event only includes the `head_sha` and IIUC it won't correspond to any commit SHAs in the "normal" repo as the commits being merged are rebased on top of each other.  It also doesn't look like merge groups have any representation in GitHub's API (only merge queues and merge queue entries do).  Are you able to tell if GitHub leaves some pointer to the original commits in the merge group's branch?

As a workaround in the meantime, you might want to set up a simple GitHub action that triggers on `merge_group` and posts a successful status with context `code-review/reviewable` to the head commit.  This should bypass Reviewable's check altogether for the merge queue, which isn't ideal but would at least get you unblocked.

**Comment by pkaminski** [comment]
Never mind Pascal -- I got a merge queue running and can poke around myself.  For the record, we don't get `merge_group` events but should be able to sniff a `push` event to `refs/heads/gh-readonly-queue/...`.  The second question is a bit trickier and I'm still trying to figure out if there's enough information in the push events to recover the original PRs.

**Comment by pcorpet** [comment]
Thanks for taking this on: in the merge queue you can find in every commit message at the end of the message the PR number. As we add them through GitHub it automatically adds the PR number when we merge.

So it goes like this

```
[Bug Fix] Make sure things are fixed. (#3622)

Rest of the description of the PR.
```

**Comment by pcorpet** [comment]
I like your workaround, I'll try it.

**Comment by pcorpet** [comment]
Hey @pkaminski , I've implemented your idea. It's a bit screwed because it appears that the GitHub token generated for merge queue actions are not enough to create commit statuses (I had a 403) so I used a personal access token.

However it's still not great because it means I have to blindly accept that my merge queue will merge as soon as all required checks have passed, which means that I cannot wait on some other checks.

How far are you in running the custom code on merge queue events?

**Comment by pcorpet** [comment]
I'm not sure how to check which events are sent. How our merge queue works:
- when a PR of ours has been reviewed and all checks are succesful, most of the time "automerge" is enabled, so GitHub picks it up and add it to the queue
- GitHub creates (or recreates) a branch for the queue and adds a squashed commit representing our PR (we use squash and rebase) on top of it
- GitHub runs all checks for that new commit: so it might include other PRs that were in the queue before, and other code that has might have been commited in the main branch
- If all required checks pass, then GitHub "moves" the main branch to that commit, ensuring that all checks have already run.

This allow us to make sure that nothing will arrive on the main branch without being tested, and allow PR to start getting merged even if they are not rebased at HEAD of the main branch. If the first PR of the queue is succesful, and the main HEAD is moved up to it, the rest of the queue is still happily checking (as they were already checking on top of that PR). If one PR fails, it gets kicked out of the queue, and all the PRs behind it are rebased on top of main without that PR (thus have to start checks again).

Ideally we would like to be able to run the "review completion" custom code on those merge commits, and run it each time there's a commit status update: that way we can have some custom code to decide which checks are required for this commit and make Reviewable status the only required check.

I'll play with the webhook APIs to see if I can monitor the various events.

**Comment by pcorpet** [comment]
I see a `pull_request.enqueued` call on the pull request itself,  then a `merge_group.check_requested`(which I believe means a check on the queue after the pull request was added including all changes that are before in the queue).

The merge_group.check_requested event has a JSON containing a `merge_group` object containing `"head_ref": "refs/heads/gh-readonly-queue/develop/pr-3698-6aaaaabbbbccccc1c647c76779155e5d039a192d",`(where `develop` is the branch on which I'm merging, `3698` is the PR I'm merging, and `6aaaaabbbbccccc1c647c76779155e5d039a192d`is the hash of the HEAD of `develop` before my merge). The `merge_group`object also has a `head_sha` property which contains the hash of the commit of my PR inside the queue.

Then there are multiple `status` events called with the head_sha above.

If you can follow on that on your side, detect the pull_request.enqueued on the PR, followed by the merge_group.check_requested, you could then "attach" the head_sha to the PR so that you could some commit statuses on that sha for the check_requested, but also for subsequent `status` calls.

**Comment by pkaminski** [comment]
Thanks, that's very useful.  Note that I'll be traveling today so won't be able to respond properly until later this week.  A couple quite notes/questions though:

You can see a list of events sent in a webhook's settings on GitHubs, under Recent Deliveries.

Can you confirm whether there's one `merge_group` event per PR enqueued?  As Reviewable is an OAuth app GitHub doesn't deliver this event to our hook.

Does the `merge_group`'s head SHA match the head SHA of the `push` to the queue branch?  (I expect it should, just double-checking.)

If the PR gets dequeued for some reason (manually, or for failing a check) and updated, then enqueued again, does it reuse the old branch or does a new one get created?

**Comment by pkaminski** [comment]
I got started on this and see a way forward, but the implementation is decidedly non-trivial.  We may be able to push something to production next week if all goes well.

**Comment by pkaminski** [comment]
We pushed a potential fix to production.  It should work going forward but may not affect PRs already in the queue.  Can you let me know whether it solves the problem?  Thanks!

**Comment by pcorpet** [comment]
@pkaminski is there a way to know that I'm in the queue when running the custom validation?

**Comment by pcorpet** [comment]
I'm not sure yet. I might want to check things differently:
- while reviewing, I want to check that Circle CI ran for some workflows but no need to run on all
- in the queue, I would want to make sure that all Circle CI workflows ran, because the next step after the queue is to bump the branch on which I'm merging.

A simple boolean in the review object would be enough

**Comment by pkaminski** [comment]
OK, I added a `review.pullRequest.mergeQueueCheck` flag.

**Comment by pcorpet** [comment]
You're the best. Thanks

**Comment by pcorpet** [comment]
Just noting, that in the playground, the `review.pullRequest.mergeQueueCheck` is always `False` even if the PR is inside a merge queue. Maybe it would be a neat improvement to set it to True?

**Comment by pkaminski** [comment]
`review.pullRequest.mergeQueueCheck` is intended to signal whether the current completion run is against the merge queue variant of the commit, _not_ whether the PR happens to currently be queue.  While the PR is queued, completion will run against both commits (separately).  I think it would be surprising if the playground defaulted to the merge queue state when the target PR happens to be queued but you can always override the flag manually.
