### ISSUE TITLE
unreviewed files is not actionable

### ISSUE THREAD

**Issue by mmlb** [Reviewable/Reviewable#106]
Similar in spirit to #84 I think. Once I am waiting for reviewer feedback the grey icon lists 1 unreviewed file but clicking it does not navigate to the file. Ditto via n or Shift-N.

Its a pain when there a lot of files in the review. Currently happening on https://reviewable.io/reviews/mistifyio/lochness-ansible/35

**Comment by pkaminski** [comment]
Fixed.
