### ISSUE TITLE
Key binding for setting disposition doesn't work while draft editor has focus

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#1065]
I bound `alt+d` to `setCurrentDiscussionDisposition('discussing')`.

**Expected:** while editing a draft, pressing `alt+d` sets the disposition to Discussing.

**Actual:** nothing happens.

**Workaround:** `mod+shift+p` `alt+d` `mod+shift+p` (assuming `mod+shift+p` is bound to `toggleCurrentDraftPreview()`).

**Comment by earlAchromatic** [comment]
Hey @feldgendler could you tell me what OS you are using when you experienced this?

**Comment by feldgendler** [comment]
Ubuntu 23.04 , Chrome 113.0.5672.126, Awesome 4.3 window manager.

Alt-D is not intercepted by the window manager (and it generally works, just not while the edit field is focused).

Note that Alt-D is also mapped to an action (“focus URL field”) in the browser. When I perform my “toggle draft preview” workaround, Alt-D works to set the disposition, and the browser's mapping does not get invoked. However, when the edit field is focused, Alt-D does invoke the browser's mapping.

**Comment by earlAchromatic** [comment]
@feldgendler Turns out that `alt` wasn't set up to work as a modifier inside of drafts but the fix is out now. Thanks for bringing this to our attention.

**Comment by feldgendler** [comment]
I confirm that the issue is fixed. Thank you!
