### ISSUE TITLE
"btw" follow-up comment unblocks a discussion

### ISSUE THREAD

**Issue by mkow** [Reviewable/Reviewable#1068]
I think "btw" keyword should impact the disposition only when creating a new discussion, not when replying. Example of a scenario where this doesn't work well now:
- I created a blocking discussion and published
- I reminded myself about a detail I forgot to include, so I added a reply with "Btw. something something".
- Now the discussion is not blocking anymore.

Partially-related discussions:
- https://github.com/Reviewable/Reviewable/issues/944
- https://github.com/Reviewable/Reviewable/issues/953

**Comment by pkaminski** [comment]
I find this argument convincing.  Any experience with this, @jwnimmer-tri?

In the past, though, having keywords that work only when the discussion is in a specific state has proven confusing [1], so this may be an argument for removing `BTW` altogether.  That would still leave `minor`, `typo` and `nit`.

[1] The only exception is `FYI` and `tip` that switch to "Informing", which is only a valid disposition for new discussions.

**Comment by mkow** [comment]
I think it should work similarly to `FYI` and `tip`, i.e. only in new discussions. But I'd also be fine with just removing its special meaning. 

Overall I'm not a big fan of tools trying to parse and understand what I wrote in natural language, because they are often bad at this :) I always have to check all the dispositions myself because I'm afraid that they could get changed by this unexpectedly. Ideally I'd just wish to have an easier way to change disposition, e.g. to unblock or switch to "resolving" in a single button click, instead of this feature. But not sure how this could look and work in UI exactly.

**Comment by pkaminski** [comment]
Pretty sure you're already aware @mkow, but for posterity:  we highlight keywords in the draft that caused a disposition change so unexpected activations should be easy to spot, and you can turn off natural language inference altogether in the disposition settings.  As for settings dispositions I don't think we'll be able to do better than the current two clicks since it's a "power user feature" and not something we want to dedicate sufficient primary UI space to to make it one click.

**Comment by mkow** [comment]
> Pretty sure you're already aware @mkow, but for posterity: we highlight keywords in the draft that caused a disposition change so unexpected activations should be easy to spot

Good point, now that I think of it, I think I just still have that habit from the times before the highlighting :)

> you can turn off natural language inference altogether in the disposition settings

I remember you mentioned this idea somewhere, but it seems that I missed it in the changelog, thanks for reminding me about it. Switched :)

> As for settings dispositions I don't think we'll be able to do better than the current two clicks since it's a "power user feature" and not something we want to dedicate sufficient primary UI space to to make it one click.

Sure, no worries :)

**Comment by jwnimmer-tri** [comment]
I don't have a lot to add here.  I don't recall anyone on my team complaining about surprise when BTW unblocks a discussion, but I can buy the argument that hurts more than it helps.

I think it would be an improvement to have non-new-discussion BTWs leave the disposition inference unchanged.

I do think its still worthwhile to have new-discussion BTWs use the non-blocking disposition as they do currently.

**Comment by jwnimmer-tri** [comment]
For consistency, I think it would also be OK to nix all of "Minor, Typo or Nit" as keywords in replies.  I think the same reasoning applies?  Maybe even "Major, Bug, or Hold on"?  In experience, the most common resolution-related replies are the "Done" flavor or the "Working" flavor (with the rare Pondering).  I don't recall seeing myself or others on my team ever flip between blocking and discussing with keywords.

**Comment by pkaminski** [comment]
We debated this back-and-forth for a while, but eventually settled on removing the "BTW" keyword altogether as the least bad option.  The alternative of restricting usage of Discussing and Blocking keywords is more invasive, and there are plenty of other less ambiguous keywords to use.  It's a close call, though, so I'm open to feedback.

**Comment by pkaminski** [comment]
An alternative would be to make BTW available only if the user is not yet an active participant (i.e., initial message or first reply).  This would lose some consistency but could be mitigated with a special tooltip in case of false negatives.  Also, it's the minimally invasive solution to the original issue.  Hmm...

**Comment by jwnimmer-tri** [comment]
When opening a totally new discussion thread, I think it would be pretty convenient to keep `BTW` as a signal for "Discussing".  A lot of my coworkers use that habitually.

> An alternative would be to make BTW available only if the user is not yet an active participant ...

This sounds pretty good.

**Comment by pkaminski** [comment]
I implemented that last idea.
