### ISSUE TITLE
Bug: Unable to Select Diff for code snippet 

### ISSUE THREAD

**Issue by Cellule** [Reviewable/Reviewable#1072]
I'm trying to give a code snippet, but I'm unable to click on the cursor to select lines further down because it is hidden behind the comment box.

<img width="920" alt="image" src="https://github.com/Reviewable/Reviewable/assets/4157103/54e05924-b03f-4112-925f-868710f0d06b">

**Comment by pkaminski** [comment]
Thanks for reporting this regression @Cellule -- should be fixed now!
