### ISSUE TITLE
"Edit in GitHub" opens wrong repository for PRs coming from a fork

### ISSUE THREAD

**Issue by jwnimmer-tri** [Reviewable/Reviewable#1088]
For example in https://reviewable.io/reviews/RobotLocomotion/drake/19778 if I click on a file to open a discussion and then select "Edit in GitHub" in the discussion header, it takes me to `https://github.com/RobotLocomotion/drake/edit/upgrade_abseil_cpp_internal/tools/workspace/abseil_cpp_internal/repository.bzl?pr=%2FRobotLocomotion%2Fdrake%2Fpull%2F19778#L8` but it should have gone to `https://github.com/BetsyMcPhail/drake/edit/upgrade_abseil_cpp_internal/tools/workspace/abseil_cpp_internal/repository.bzl?pr=%2FRobotLocomotion%2Fdrake%2Fpull%2F19778#L8` instead, i.e., the forked repo is the one that has such a named branch.

**Comment by fahhem** [comment]
Thanks @jwnimmer-tri, we have a PR out to fix this asap and should have it deployed soon!
