### ISSUE TITLE
Acknowledge cascades for all users

### ISSUE THREAD

**Issue by groy** [Reviewable/Reviewable#109]
Having multiple users review code, if a reviewer acknowledges a comment before the PR owner sees it, the comment is collapsed for all users. Including PR owner.

Suggestion: Make acknowledge only clear comments for the current user, as they are not necessarily wanting to see the expanded comments on that section of the code review and want to collapse those comments.

**Comment by pkaminski** [comment]
Good point, thanks.  I've changed the logic to always require an acknowledgement from the PR author (unless the discussion author resolves it away explicitly before anybody replies).  The change is retroactive.  I'll deal with collapsing / hiding unresolved discussions separately as part of #94.
