### ISSUE TITLE
Crash when expanding a thread

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#1091]
1. Open https://reviewable.io/reviews/ridge/tectonic/19740#-NZQfa0y7xThejc_GPno
2. Collapse the thread and expand it again.

Error message: `Cannot read properties of undefined (reading '0')`

**Comment by aedelstein** [comment]
I'm seeing the same thing on https://reviewable.io/reviews/PolicyReporter/policyr/7477#-NPvMTaRBrVKp8qnpEtH

More specifically, if I try to expand an already-concluded thread by clicking Show Discussion, the page crashes
![image](https://github.com/Reviewable/Reviewable/assets/4365598/fc3b5a99-7cba-4d4b-964a-c964b5883a99)

I see the following error

![image](https://github.com/Reviewable/Reviewable/assets/4365598/c10af465-815f-4912-97da-e810ffa5804e)


Also, if I try to see older comments in a thread with many comments, the page crashes the same way as well.

**Comment by earlAchromatic** [comment]
Fix is getting rolled out momentarily.
