### ISSUE TITLE
Cannot leave a comment on a line of code

### ISSUE THREAD

**Issue by miladz68** [Reviewable/Reviewable#1097]
when clicking on a line of in the UI, the box to enter the comment does not appear. In other words, clicking on a line of code has no affect, while a box to enter the comment must appear.

**Comment by Ostrzy** [comment]
I have the same problem. It is possible to select a piece of code and click suggest - comment box does appear in that case.

**Comment by jbmlaird** [comment]
Same problem. Chrome 114.0.5735.198 (Official Build) (arm64) on macOS Ventura 13.4

**Comment by pkaminski** [comment]
Oh man, that was a terrible regression.  Rolled back -- sorry about that.
