### ISSUE TITLE
page crashes on oath grants

### ISSUE THREAD

**Issue by asdiamond** [Reviewable/Reviewable#1102]
Steps to reproduce: 
- Log in with new user
- navigate to `/reviews`
- click on pull request to open github in a new tab
The oath grants page will be shown like below: 
![image](https://github.com/Reviewable/Reviewable/assets/22527032/74358fff-a893-4b89-9936-640bdb4dba88)

After granting permission the page will crash: 
<img width="1422" alt="Screenshot 2023-08-30 at 6 51 28 PM" src="https://github.com/Reviewable/Reviewable/assets/22527032/28b3313b-6b34-46f6-b361-745f00d09c4f">

**Comment by pkaminski** [comment]
Thanks!  We've seen this error before but could never figure out what triggered it.  Did the OAuth page open in a popup, or did it use a redirect flow?

**Comment by asdiamond** [comment]
Neither, I navigate to the review page and tried to open a PR. This opened GitHub in a new tab and github redirected me to the grants.

**Comment by pkaminski** [comment]
Reproduced and fixed, thanks!  This was a weird corner case... that also happened to be right on the obvious onboarding path for new users.  😳
