### ISSUE TITLE
Bug: Buttons in "Checks" panel are not clickable.

### ISSUE THREAD

**Issue by andrewheumann** [Reviewable/Reviewable#1103]
Recently, buttons in the "checks" dropdown stopped being clickable. 
![image](https://github.com/Reviewable/Reviewable/assets/31935763/7618b542-761d-4d8c-bedf-bb1968ffaf0d)

I have had to return to github to merge `main`/`master` into my branch. It looks to me like this is just a css issue; the underlying `a` tag is still clickable and works, but the `p.report` takes the cursor event. If in the dev tools I make `p.report` `pointer-events: none`, then the buttons work as expected.

**Comment by pkaminski** [comment]
Sorry, that was a regression we accidentally introduced a week ago or so -- thanks for the report.  Fixed!

**Comment by andrewheumann** [comment]
Hooray! thank you 😄
