### ISSUE TITLE
The whole file should be visible after hitting `n`/`p` on single page view

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#111]
On https://reviewable.io/reviews/hammerlab/cycledash/755 I can hit `n` and `p` to step back and forth through the files for review. When I do, however, the page scrolls so that I only see the first two or three lines of the file. I'd prefer if it scrolled the top of the file to the top of the page, so I can see as much as possible.

Hopefully this gif makes it clear what's going on:

![screen recording 2015-06-23 at 12 51 pm](https://cloud.githubusercontent.com/assets/98301/8311776/984d0f64-19a6-11e5-888d-c1fc23962e84.gif)

**Comment by pkaminski** [comment]
Should be fixed now, give it a try.

**Comment by danvk** [comment]
Confirmed -- fixed!
