### ISSUE TITLE
Unmappable inline comments from GitHub -- link to original?

### ISSUE THREAD

**Issue by seansfkelley** [Reviewable/Reviewable#1111]
Inline comments mapped from GitHub get this helpful note...

> _(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)_

...but when you have a lot of them in a review, it can be bothersome to go back to GitHub and ctrl-f until you find it, especially because GitHub will hide the middle chunk of comments behind a "Load more...".

Can you add a permalink back to the source comment on GitHub?

**Comment by pkaminski** [comment]
Good idea -- we'll see what we can do.

**Comment by snoack** [comment]
Implemented in Reviewable/reviewable-server#409. The change will become visible on reviewable.io after the next release.

**Comment by seansfkelley** [comment]
Thank you!
