### ISSUE TITLE
Do not block main functionality because of missing firebase connection

### ISSUE THREAD

**Issue by miladz68** [Reviewable/Reviewable#1113]
In some situations (some VPN connections), Firebase is refusing to connect from my browser, which makes it impossible for me to use Reviewable. It would be much better if you guys provide the basic functionality even if the firebase connection is not stablished, so people can continue to use Reviewable.  

![Screenshot_20231010_135004](https://github.com/Reviewable/Reviewable/assets/16287074/9f65b2be-e650-461c-b1b4-7e201bc8a691)

**Comment by pkaminski** [comment]
This would be nice to have but unfortunately architectural limitations make it unlikely in the foreseeable future.  Please see https://github.com/Reviewable/Reviewable/issues/1101 for a more complete explanation and workarounds that you can enable if you're willing to assume some risk of data loss.
