### ISSUE TITLE
`.dib` file format doesn't diff

### ISSUE THREAD

**Issue by andrewheumann** [Reviewable/Reviewable#1114]
Unfortunately, a `.dib` file can be one of two things:
- **D**evice **I**ndependent **B**itmap (a truly ancient bitmap format)
- **D**otnet **I**nteractive note**B**ook (a code nodebook format from the dotnet interactive team: https://github.com/dotnet/interactive)

Github handles the latter correctly, diffing them as text:
![image](https://github.com/Reviewable/Reviewable/assets/31935763/f349be29-8ece-4446-96e3-9c4c7017680f)
Whereas reviewable thinks they are an image and displays nothing:
![image](https://github.com/Reviewable/Reviewable/assets/31935763/d1f1116d-a3a0-4180-9740-c64463d71457)

**Comment by jwnimmer-tri** [comment]
(Reviewable user here.)  I'll let the maintainers respond about the "default value" here being the old bitmap, but in case it helps as a work-around, see these docs:

https://docs.reviewable.io/files.html#diff-customization

You can probably commit a `.gitattributes` file to your repo that governs the the file type.  Maybe even `**/*.dib diff=txt` would be an improvement.

**Comment by pkaminski** [comment]
You're right, these are ancient and we don't actually have special treatment for images at this point anyway.  I removed the image flag from the `bmp`, `dib`, and `xbm` extensions so they'll be diffed normally, or treated as binary if they actually happen to be an image.
