### ISSUE TITLE
Everything is suddenly left-justified

### ISSUE THREAD

**Issue by nate-thirdwave** [Reviewable/Reviewable#1123]
![image](https://github.com/Reviewable/Reviewable/assets/96086763/5c3d1a46-5c4f-45bc-8ae1-2fdfbbf8491d)
Everything is suddenly left-justified.  This seems to be an unintended change? Certainly it feels like a regression from a UX standpoint.

Expected: Content used to be center-aligned.

**Comment by nate-thirdwave** [comment]
Using browser:
Chrome on Ubuntu Linux
![image](https://github.com/Reviewable/Reviewable/assets/96086763/6408456b-1228-4113-ac6a-365105cd7dda)

**Comment by earlAchromatic** [comment]
Hey Nate, this is an intentional update to our layout as we work our way towards adding a sidebar, which will be a major improvement to the UI. I'm going to close the issue since it's behaving as expected.

**Comment by pkaminski** [comment]
We rolled back this change for now.  It'll come back in the near future once we've addressed the shortcomings you and others pointed out.  Thanks!

**Comment by nate-thirdwave** [comment]
Sounds good. Yeah, I think you'll want to roll it out only once you have your new sidebar in view so that the UX change comes with whatever improvement you're trying to make space for. Thanks!

**Comment by mohamedmohsen6331** [comment]
How can I make money from scratch?
