### ISSUE TITLE
Support Cairo language syntax highlighting

### ISSUE THREAD

**Issue by enitrat** [Reviewable/Reviewable#1127]
[Cairo](https://www.cairo-lang.org/) is a language used to generate create provable computations using Zero-Knowledge proof systems. Its syntax is very similar to Rust, so it is possible to simply highlight Cairo's syntax with rust settings.

Would it be possible to map `.cairo` files to use the Rust syntax highlighter?
Thank you!

**Comment by pkaminski** [comment]
Sure thing, done!
