### ISSUE TITLE
Clicking "6 Drafts to Send" button has no effect in single file mode

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#113]
When I click this button, it typically takes me through the set of drafts I've written:
![screen shot 2015-06-24 at 3 46 16 pm](https://cloud.githubusercontent.com/assets/98301/8339798/318bf4d8-1a88-11e5-955f-8cd26318f198.png)

However, when I'm in single file mode and there are no comments on the current file, clicking it does nothing. I'd expect it to take me to the next draft comment, even if it's in another file.

Alternatively, I wouldn't care about this if we had #69

**Comment by pkaminski** [comment]
Fixed.  As for #69, I have a design in mind but the feature hasn't bubbled to the top of the priority list yet.
