### ISSUE TITLE
Request: additional default language mappings by extension

### ISSUE THREAD

**Issue by seansfkelley** [Reviewable/Reviewable#1133]
I don't think Reviewable performs the current extension -> language mapping for syntax highlighting:

- `mjs`, `cjs`: JavaScript
- `mts`, `cts`: TypeScript

Can you add these as defaults?

**Comment by pkaminski** [comment]
We were already mapping `mjs` and `cjs`, but I added `mts` and `cts` as well.  Thanks!

**Comment by seansfkelley** [comment]
Oh, sorry, I must have crossed the streams. Thanks for the quick fix!
