### ISSUE TITLE
Default code comment dispositions for new developers

### ISSUE THREAD

**Issue by schreter** [Reviewable/Reviewable#1135]
In our workflow, we use "discussing" disposition as a soft blocker and "blocking" for a hard blocker. Reviewable defaults all new code comments to "blocking", unless set differently by the user.

I'm getting tired of reminding all new developers (and also some renitent long-term users) over and over again to set their default disposition to "discussing" to fit our workflow.

Can you please add a possibility to set the default dispositions to use by the admin? Or is there a possibility already? I didn't find it.

Similarly, for new self-review code comments (primarily to inform reviewers what parts to look at) we use "informing" disposition. IIRC this is also not the default. Setting a default for this would be a plus too.

Thanks.

BTW, for "fixing" the dispositions of those renitent long-term users, is there a way to change some key in Firebase to set the disposition for them (I didn't investigate)?

**Comment by pkaminski** [comment]
There's no way to set default dispositions at the org or repo level at the moment — I'll need a bit of time to figure out if that's a direction we want to go in, as there are both pros and cons.

In the meantime, as a workaround, you can set these directly for users via Firebase.  You'll need to look in `/users/github:NNN/settings` (where `NNN` is their numeric GitHub ID) and set any or all of the following keys:
```
defaultNewDiscussionRole
defaultNewAsAuthorDiscussionRole
defaultJoinedDiscussionRole
defaultJoinedAsAuthorDiscussionRole
```
Valid values are the various dispositions in all lowercase, though not every value is valid for every key.  (If you attempt to set an invalid one Firebase will deny the write, so it's safe to just try.)

**Comment by schreter** [comment]
Are there some news regarding this topic?

We have again some new colleagues who don't care about blocking everything by default. So either the default for new comments should be "Discussing" instead of "Blocking" or at least a means should be provided to specify a default for new users on the instance level.

Thanks.

**Comment by pkaminski** [comment]
Apologies, this fell off my radar.  I should be able to get it into the next release as an instance-level `REVIEWABLE_DISPOSITION_DEFAULTS` config, with separate settings for four distinct scenarios.  (It doesn't make sense to make this a repo- or org-level setting since it's applied at the user level, and users can belong to multiple organizations.  I don't want to complicate matters by making the user's setting org- or repo-specific.)
