### ISSUE TITLE
Duplicated commits in commit message diff

### ISSUE THREAD

**Issue by mkow** [Reviewable/Reviewable#1138]
There seem to be some recent regression in the commit message diffing. See https://reviewable.io/reviews/gramineproject/gramine/1746 - base vs r4 diff shows e740728 commit _twice_, despite this diff containing only a single commit.

This never happened to me before, and this PR is rather simple, so it's probably some new regression?

**Comment by pkaminski** [comment]
I think it's a side-effect of the fix to #1067.  Let me see what I can figure out.

**Comment by pkaminski** [comment]
I believe this should be fixed now, though not retroactively.
