### ISSUE TITLE
Should Reviewable honour GitHub's `linguist-generated` git attribute?

### ISSUE THREAD

**Issue by saj** [Reviewable/Reviewable#1144]
Hello!  We are new to Reviewable.

[Customizing how changed files appear on GitHub](https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github)

> To keep certain files from displaying in diffs by default, or counting toward the repository language, you can mark them with the linguist-generated attribute in a `.gitattributes` file.

We have this attribute set as follows.

```
/concourse/*.yaml linguist-generated
```

The diffs in GitHub's PR user interface honour this directive.

<img width="617" alt="image" src="https://github.com/Reviewable/Reviewable/assets/194389/d31cbe80-686c-4b29-b433-6997cbc85d0d">

`linguist-generated` is not currently honoured by Reviewable.
Should Reviewable also honour this attribute?

I have read the following documentation.
<https://docs.reviewable.io/files.html#generated-files>
<https://git-scm.com/docs/gitattributes#_generating_diff_text>

git's own `diff` attribute does not strike me as a _diff suppressant_.  It seems like it was intended mostly as a way of telling the VCS **how** a diff should be generated -- not **when** or **under what conditions**.  (At least two of us here came to that interpretation independently.)

I believe GitHub added support for `linguist-generated` much later -- probably after #73 and #158.

As a matter of UX, new users who are onboarding into Reviewable today will probably have repos configured for `linguist-generated`.  We could go and edit all of these `.gitattributes` files, and add duplicate `diff` unsets for Reviewable, yes.  Though, given Reviewable is intended to layer over GitHub, perhaps it would be reasonable to detect the `linguist-generated` attribute and remove the need for such mass edits.

Thank you!

**Comment by pkaminski** [comment]
Oh cool, I wasn't aware of this.  Yes, Reviewable should definitely support `linguist-generated` — I'll get it implemented soon.

I think `-diff` is fine for this purpose too, and has the advantage that it'll also be respected by `git diff` on your machine, but I certainly don't want to force people to update all their `.gitattributes` files.

**Comment by pkaminski** [comment]
This feature is now live!
