### ISSUE TITLE
Support diffing JSONC by default

### ISSUE THREAD

**Issue by seansfkelley** [Reviewable/Reviewable#1145]
We recently set some .gitattributes, and now I get this message a lot:

<img width="502" alt="image" src="https://github.com/Reviewable/Reviewable/assets/2101409/47477936-e81d-4971-a136-8c9fbe2feb5a">

Can you support JSONC diffing? If not, can you interpret it as JSON, so at least the majority (at least of mine) that don't actually have any comments are diffed by default?

**Comment by pkaminski** [comment]
Sure thing, done.

**Comment by seansfkelley** [comment]
Thank you!
