### ISSUE TITLE
`linguist-language=VBA` no longer diffed

### ISSUE THREAD

**Issue by gilbertbw** [Reviewable/Reviewable#1147]
Hello,

We have a project written in Visual Basic for Applications (VBA).

We have started getting the message `Custom diff specified in .gitattributes: VBA` for all our files with `linguist-language=VBA` set in .gitattributes e.g.
```
*.ACM linguist-language=VBA
```
I believe this is a result of #1144 

I would at least like an option to display these diffs by default again. I also see highlight.js has language support for `vbscript`. As VBA is a syntactic superset of vbscript, I think applying this would be better than no highlighting.

**Comment by gilbertbw** [comment]
I actually see https://github.com/dullin/highlightjs-vba provides VBA highlighting

**Comment by pkaminski** [comment]
Thanks for reporting this — I integrated the VBA syntax definition you found and hooked it up to `linguist-language=vba`.  Could you please verify that it's working for you?

Also, to improve matters further, do you know which file extensions we should automatically apply this syntax highlight for, other than `.vba`?  Thanks.

**Comment by gilbertbw** [comment]
@pkaminski That's working, thank you for the quick turn around. `.bas` (Basic Files) is used by default for VBA files when you export them from an office application. We use `.acm`, `.acf` and  `.acr` for Access Modules, Forms and Reports, but I don't think that is widespread.

**Comment by pkaminski** [comment]
Thanks, we'll add `.bas` as well then.
