### ISSUE TITLE
Moved file comments remain at old file path

### ISSUE THREAD

**Issue by kevinkehl** [Reviewable/Reviewable#115]
When a file moves when a pull request is already open, any comments that were published for the file at the previous location would stay at that location, on a blank file. Reviewable already indicates that the file has moved, so it is aware the file is just a rename. The comments should move along with it.

**Comment by pkaminski** [comment]
Agreed, this could be handled better.  I'll look into it when I have a chance.

**Comment by pkaminski** [comment]
Done.  Any chain of renamed files will now be collapsed into a single "virtual" file with all their combined revisions and comments.
