### ISSUE TITLE
Incorrect diff displayed for a renamed file

### ISSUE THREAD

**Issue by mkow** [Reviewable/Reviewable#1155]
See: https://reviewable.io/reviews/gramineproject/gramine/1843/.ci/linux-sgx-ubuntu22.04-gcc-release.jenkinsfile#-.

For this file Reviewable says "File renamed from .ci/linux-sgx-ubuntu20.04-gcc-release.jenkinsfile to .ci/linux-sgx-ubuntu22.04-gcc-release.jenkinsfile at r1." and shows a diff, which says that the old file was empty and all the contents were added in this PR, which is incorrect (the old file is not empty).

I think what happened here is that there was a rename at r1 which Reviewable correctly recognized, but then at some further revision it "unmatched" both files and started treating it as a new file added in that PR (but still showing it as renamed).

**Comment by pkaminski** [comment]
I believe this is working as expected:  notice how a bunch of files (including `.ci/linux-sgx-ubuntu20.04-gcc-release.jenkinsfile`) were reverted back at `r6`.  If you diff the new file against base at `r1` through `r5` you'll get the expected result; if you do so at `r6` or `r7` the original file was "taken back" from the rename, so the diff will show an add.

I think the rename history and/or the revision cells should call this out somehow but it's not clear to me what's the best way to do it.  What would've helped you understand what's going on?

**Comment by mkow** [comment]
> notice how a bunch of files (including `.ci/linux-sgx-ubuntu20.04-gcc-release.jenkinsfile`) were reverted back at `r6`

But this isn't shown anywhere in the link I provided? Am I missing something? The revisions axis only shows that there was a rebase at `r6`.

My problem is that I think that this view makes it indistinguishable (from the reviewer's point of view) from a case where the file was actually renamed and then filled with contents (and was empty originally).

> If you diff the new file against base at `r1` through `r5` [...]

Yeah, but that doesn't solve the problem - if I'd join the review in that state, I wouldn't be interested in the old revisions I've never seen and just diff base against the newest revision and see the confusing (IMO incorrect) diff.

> I think the rename history and/or the revision cells should call this out somehow but it's not clear to me what's the best way to do it. What would've helped you understand what's going on?

I think the "File renamed from [...]" text should match the code diff calculated, which I think isn't the case here? (i.e. depend on the selected diff range) If I understand correctly, both got out of sync in this case and thus present inconsistent information.

**Comment by pkaminski** [comment]
> But this isn't shown anywhere in the link I provided? Am I missing something?

Yes, take a look at the file matrix:
![image](https://github.com/Reviewable/Reviewable/assets/1646896/d02bd236-5b39-4402-867f-8a5fb5d432ba)

> The revisions axis only shows that there was a rebase at r6.
> I think the "File renamed from [...]" text should match the code diff calculated, which I think isn't the case here?

Yeah, that's really the crux of the issue:  how to show/tell that a renamed file has become not-renamed at some revision, because the original was recreated?  Note that in principle a file could shift multiple times between renamed/not renamed, at various revisions.

> just diff base against the newest revision and see the confusing (IMO incorrect) diff

I believe the diff is correct, given the revert of the renamed file.

**Comment by mkow** [comment]
> > But this isn't shown anywhere in the link I provided? Am I missing something?
> 
> Yes, take a look at the file matrix:

But that's not visible when reviewing `.ci/linux-sgx-ubuntu22.04-gcc-release.jenkinsfile`:

![reviewable-rename-diff](https://github.com/Reviewable/Reviewable/assets/5244565/7997097c-a002-41e4-acbf-f009cb26009a)

Would this view be any different if that file was actually an empty `.ci/linux-sgx-ubuntu20.04-gcc-release.jenkinsfile` renamed to `.ci/linux-sgx-ubuntu22.04-gcc-release.jenkinsfile` in r1?

> Yeah, that's really the crux of the issue: how to show/tell that a renamed file has become not-renamed at some revision, because the original was recreated? Note that in principle a file could shift multiple times between renamed/not renamed, at various revisions.

Why not make that "File renamed from [...]" text be generated based on the current diff range?

**Comment by pkaminski** [comment]
It took a while, but I think the renamed/recreated file messages are now much clearer and more useful.  Take a look!

**Comment by mkow** [comment]
Yup, works well now. And I really like the colored paths diff, comparing the paths was quite annoying before!
