### ISSUE TITLE
Crash: No such user when processing directives: <name>

### ISSUE THREAD

**Issue by johamster** [Reviewable/Reviewable#1159]
In a draft comment, I wanted to add a reviewer using `+reviewer:@...`. For selecting a reviewer, I usually type the colleagues name. Then, hitting `Enter` converts it into the colleague's ID. For some reason, the name was not replaced by the ID. Then, reviewable got stuck with the message:

`No such user when processing directives: <colleagues's name>`

From then on, I couldn't do anything anymore. When reloading reviewable, the same draft comment was loaded from the database and led to the same crash again, I assume.

Didn't try to reproduce it again but can do if required.

**Comment by johamster** [comment]
I reproduced it. I typed the following, i.e., adding a non-existent reviewer and attempting to add yet another reviewer:

`+reviewer:@<non-existent-name> +rev`

Then, reviewable suggests to auto-complete to "+reviewer:@". When I now hit enter to accept the auto-completion it crashes.

We are on an enterprise instance v4323.6848.

**Comment by pkaminski** [comment]
Thanks, fix out for review.  I'll squeak it into the next enterprise release, likely tomorrow.
