### ISSUE TITLE
File list dropdown seems to be gone

### ISSUE THREAD

**Issue by schreter** [Reviewable/Reviewable#1167]
After the upgrade of Reviewable Enterprise a few weeks ago, the UI changed a bit. The problem: the file list which was previously available as a drop-down on the rabbit icon top left is now gone (instead, the top bar is expanded).

I have to review quite frequently large changes encompassing tens to hundred files. It was quite handy that I could jump around the review via this drop-down.

Is it now available elsewhere? If so, where?
If not, can it be resurrected?

Thanks.

**Comment by hongha912** [comment]
Hi @pkaminski any update for this?

**Comment by pkaminski** [comment]
The files button shown above has been available for a few months now and will pop up the file matrix if it's been collapsed.  Is it not working for you?

**Comment by hongha912** [comment]
@pkaminski I meant for the sidebar feature?

**Comment by pkaminski** [comment]
We expect to launch the sidebar early next year — still a few finishing touches needed to make it usable.
