### ISSUE TITLE
Performance regression with Firefox 113

### ISSUE THREAD

**Issue by matzf** [Reviewable/Reviewable#1168]
For no good reasons, I've been running Firefox 113.0.2 (released May 2023, ~13 months ago) and I noticed that recently (in the last two weeks or so, i.e. around the time of 10th to 21st June 2024) the reviewable UI has suddenly become unusably slow. The review pages still load reasonably quickly, but scrolling shows the gray background for many seconds before the content is drawn. Editing comments is also impossibly slow.

When switching to a recent Firefox (127.0.2) or even old-ish Chromium (112.0.5615.49, released April 2023, ~14 months ago), everything is perfectly snappy.
Feel free to ignore this if you consciously no longer want to support older Firefox versions. Running a more recent Firefox is perfectly acceptable for me.

**Comment by earlAchromatic** [comment]
Hey @matzf. We support Firefox ESR (115) so 113 is outside of our support window. I did double check performance on ESR and didn't notice any slowdowns. Perhaps that would be an option if you prefer not to use the most recent version.
