### ISSUE TITLE
Visiting repositories page results in regular "crash" page 

### ISSUE THREAD

**Issue by AutomatedTester** [Reviewable/Reviewable#117]
STR:

1. Login (I am a new user which may make a difference)
2. click repositories page (I have access to over 1000 repos on github)
3. Start looking for the repo of your choice (perferably near the bottom)
4. Get Crash page. 

I had that page 3 times before giving up on the site.

![repository_connections_-_reviewable](https://cloud.githubusercontent.com/assets/128518/8519436/a7c8e96c-23ca-11e5-936e-4f94f749d935.jpg)

**Comment by pkaminski** [comment]
Sorry about that, 1000 repos is way higher than I imagined possible...  I'll figure out a more efficient way to check the permissions tomorrow.

**Comment by AutomatedTester** [comment]
No problem :) I am an admin on the Mozilla org which tends to break
services using github api. I broke Travis CI in a similar way :)

David Burns
Email: david.burns@theautomatedtester.co.uk
URL: http://www.theautomatedtester.co.uk/

**Comment by pkaminski** [comment]
I've replaced the per-repo authorization requests with a single (potentially huge) request that should be more efficient.  Testing it at scale is a challenge, though, so could you please give it another try to see if the page works for you now?  Thanks!

**Comment by pkaminski** [comment]
I'm going to assume this is fixed, but please reopen if not.
