### ISSUE TITLE
Quoted code gets misformatted in comments

### ISSUE THREAD

**Issue by mkow** [Reviewable/Reviewable#1170]
Pasting a link to code in a comment (e.g. `https://github.com/gramineproject/gramine/blob/ca715b9ca1addd4d846975d5f4a2d1d58804f2b9/pal/src/host/linux-sgx/enclave_framework.c#L69-L89`) results in the linked code being quoted, but as some weird table instead of a normal code listing. Example where this happened: https://reviewable.io/reviews/gramineproject/gramine/1955#-O2ogg8W0RZFiiwAJCrx.
This worked correctly in the past, looks like some regression.

My browser: Firefox 128.0.3.

**Comment by mkow** [comment]
Is this actually completed? The bug is still present for me, I just tested.

**Comment by pkaminski** [comment]
Sorry, I didn't get a chance to push it yet — it's live now.  I really wish GitHub's "Fixes #NNN" auto-closing mechanism had a way to wait until the update was actually deployed...

**Comment by mkow** [comment]
Works now, thanks!

> I really wish GitHub's "Fixes #NNN" auto-closing mechanism had a way to wait until the update was actually deployed...

Yup, I agree...
