### ISSUE TITLE
UI: Title not linking to PR, actual link is tiny 

### ISSUE THREAD

**Issue by drahnr** [Reviewable/Reviewable#1180]
![Untitled](https://github.com/user-attachments/assets/ae2542ba-f960-48e8-92f6-7ccaf2bd5f14)

I find it rather unexpected that the PR title in the page does _not_ link to the actual PR, while the icon (blue) brings me to the github user's page, while I'd have anticipated them to be a unit that brings me to the github PR page.

At the same time there is a tiny link that I missed on first and second usage that actually links back to the PR page.

**Comment by pkaminski** [comment]
Hey Bernhard, thanks for reporting this issue.  We actually have a pretty complete redesign of this area that's pending implementation in the near future; it'll get rid of the PR title from the status bar and the Changes box, and introduce a new Pull Request box instead with a much clearer link to GitHub.  Consequently, I'd rather not mess around with this dead-end design too much, especially as the status bar's layout is infamously fragile.

I agree that it doesn't make sense to link the author and not the title, though, so we removed the link from the avatar instead.  Hopefully this will reduce confusion somewhat while we work towards the larger redesign.
