### ISSUE TITLE
DroidSansMono is not rendering all characters with fixed spacing correctly

### ISSUE THREAD

**Issue by im-sj** [Reviewable/Reviewable#1187]
As an example, with comments including arrow characters, the default font makes things look shifted

                ┌─────────────────────────┐
                ┌─┐┌─┐┌─┐┌─┐┌─┐┌─┐┌─┐┌─┐┌─┐  nav/approach
                ▲─┘└─┘└─┘└─┘└─┘└─┘└─┘└─┘└─┘  side of lane
                ├─────────────────────────┘

See this with default font:
![image](https://github.com/user-attachments/assets/52fcda69-876e-491f-8274-0841d44e3b95)

VSCode and other editors make it look fine (including this text box for filing issues):
![image](https://github.com/user-attachments/assets/46bdcfd7-cc21-4ff1-9b32-cfd5df3d49ae)

Switching to "Courier" font works which means that there might be some rendering issues with DroidSansMono for some characters.

**Comment by pkaminski** [comment]
You're right, Droid Sans Mono is missing a bunch of useful glyphs.  We've been planning to switch to a more modern font for a while now but I'll try to hurry that along.  In the meantime, you can work around the problem by setting a custom diff font in your account settings (as you noted).

**Comment by pkaminski** [comment]
We switched to using Liberation Mono for diffs instead, which should fix the issue.
