### ISSUE TITLE
Feature Request: ERB Syntax Highlighting

### ISSUE THREAD

**Issue by derekharmel** [Reviewable/Reviewable#1188]
Hello Reviewable team,

First, I ❤️  Reviewable! I've been using it for years.

Would it be possible to enable syntax highlighting for ERB (.erb) which is the default templating language Ruby and Ruby on Rails? My team writes a lot of ERB and not having syntax highlighting is a bit of a hinderance. 

It appears that highlight.js supports it, so I'm hoping this is something simple: https://github.com/highlightjs/highlight.js/blob/main/src/languages/erb.js

Thanks!

**Comment by pkaminski** [comment]
Shucks, thanks!  This is indeed quite simple — done.  Let me know if it's not working for some reason as I don't have convenient ERB files lying around to test with.

**Comment by derekharmel** [comment]
@pkaminski Amazing! Thank you so much! It's definitely working.
