### ISSUE TITLE
Comment previews scroll up/down by 1px

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#119]
When I preview a comment that's more than a line or two tall, I usually get an unnecessary vertical scrollbar:

![screen shot 2015-07-06 at 12 51 20 pm](https://cloud.githubusercontent.com/assets/98301/8528312/5a8a2f92-23e0-11e5-88ad-40f4e7ff9f99.png)

It goes up/down by 1px. It would be nice to not have the scrollbar.

**Comment by pkaminski** [comment]
This is a regression, will fix.

**Comment by pkaminski** [comment]
Looks like a regression in the Chrome renderer, since Firefox continues to look fine.  I hacked up a workaround, should be fine until they break it again.

**Comment by danvk** [comment]
Looks like this has regressed:
![screen shot 2015-07-27 at 4 45 42 pm](https://cloud.githubusercontent.com/assets/98301/8917264/087429b0-347f-11e5-96d5-de5fe71f1594.png)

(I'm on Chrome 45 beta)

**Comment by pkaminski** [comment]
FFS Chrome...  I hope you don't mind, but I'm going to wait until v45 hits stable to address this in case this is a beta bug that they'll actually fix.

**Comment by danvk** [comment]
Sounds good, just consider it a heads up that this might regress

**Comment by pkaminski** [comment]
Chrome v45 has been released, but I don't see the scroll bar issue so looks like they fixed the bug during the beta.  Can you confirm?

**Comment by danvk** [comment]
I'm on Chrome 45.0.2454.85 (Official Build) (64-bit) and still seeing this:

![screen shot 2015-09-17 at 11 42 31 am](https://cloud.githubusercontent.com/assets/98301/9938005/33cbedfc-5d31-11e5-814f-17064baef4cf.png)

https://reviewable.io/reviews/hammerlab/pileup.js/251#-JzNDmOGPxxzbwe-XqhJ

**Comment by pkaminski** [comment]
This is just #167 writ small: the code styling requires an extra pixel of height for some reason.  I haven't come up with a general solution yet so in the meantime I bumped the area sizer's height to give the contents a few extra pixels.
