### ISSUE TITLE
Option to use dropdown for "Checks"

### ISSUE THREAD

**Issue by mgalgs** [Reviewable/Reviewable#1195]
It looks like there was a change recently to change the "Checks" dropdown panel to a full screen modal pop-up:

![image](https://github.com/user-attachments/assets/760c0161-81c7-4951-a016-7d46724dff8a)

I know it's the same number of clicks to activate and hide, but I still much prefer the old way personally...

Any chance we can get a setting to select between the dropdown style and the modal style for the "Checks" panel?

**Comment by pkaminski** [comment]
We're moving away from all dropdowns on the toolbar as part of a larger redesign leading toward a sidebar.  Unfortunately, the new design cannot accommodate these kinds of dropdowns so we can't offer it as an option.

Are there specific things you miss about the old dropdown, or is it just that you got used to it?

**Comment by mgalgs** [comment]
Got it... Yes, I was "used to it", but the new one is objectively more visually jarring and disruptive. I don't like how the content I'm interested in gets displayed far away from where I clicked (eye tracking and all that), and how the rest of the content on the page gets blurred out (visually distracting, similar to animations).

Not a huge deal, and hopefully the sidebar will allow for more flexibility. Thanks for your consideration.

**Comment by pkaminski** [comment]
You make some fair points — perhaps we can mitigate those without giving up on our overall design.  Let me try out a few things...

One clarification:  is it the blurring specifically that's distracting, or the overall fading out of the background?  (In other words, is it the `blur(2px)` filter, or the `background-color: white; opacity: 0.7;` that's the problem?)  I assume you have animations turned off?

**Comment by mgalgs** [comment]
Nice! Like I said, not a huge deal but if there are easy tweaks that can be made now before the sidebar update I'm all for it...

I think it's more the `blur(2px)` filter itself. Although I do feel like it's less distracting in dark mode, so maybe the background color fade is also part of it... Yes, I do have animations turned off.

Regarding the pop-up location, I can't really envision a way to make it display closer to the checks wheel in the nav... It seems like the only logical place to put it is in the center... I understand that you can't go back to the old way due to framework updates, but I do feel like the core of the "distracting" nature of the new approach is the pop-up location, not so much the blur effect... So that's a tough one. :shrug:

**Comment by pkaminski** [comment]
So I've been playing around with positioning and styling to make the modal feel more like a dropdown but so far we've failed to find a happy medium.  (Internally, some folks feel that having a less blurry backdrop and moving the dialog closer to the mouse pointer is actually more distracting!)  I'm curious, now that's it's been a week do you still find the new UI irksome or has it grown on you by any chance?

**Comment by pkaminski** [comment]
> I do hope that you'll consider a "Checks" area as a feature for the future side-nav.

Currently we're seeing the sidebar as being purely for navigation:  it'll include the file matrix, a discussion list, and more-or-less the stuff you see in the toolbar at the moment.

> I really miss the top-nav file matrix drop-down

I got your back on this one!  Collapse the file matrix, then click on the files icon in the toolbar (not the counter) to pop up it as a modal.  😊  (You can also assign a keyboard shortcut to the action if you'd like.)

**Comment by mgalgs** [comment]
> in the toolbar (not the counter)

I'm not totally sure which toolbar or counter you're referring to. Do you mean the "File matrix" panel near the top of the page? The issue I'm referring to isn't with the file matrix itself (the current panel is perfectly usable even as a non-modal), it's the fact that you have to hunt to find it (potentially long scroll-up). Jumping around files seems like a common enough action that it would be nice to make it 1-click, even from deep within a review, like anywhere here:

![image](https://github.com/user-attachments/assets/4029c23d-d803-4b0b-be23-b280fb2fc62e)

Even if it's just something clickable that scrolls you up to the file matrix panel or opens the file matrix modal. I know every pixel matters, but so does every second while doing code review. Could be something small. It would be nice to not have to rely on a keyboard shortcut.

**Comment by mgalgs** [comment]
Just a thought:

![image](https://github.com/user-attachments/assets/5cdbc723-0f10-4fac-8ea3-9c6419c475b0)

**Comment by earlAchromatic** [comment]
If you click the discussion button in the right hand corner, it will show the status bar buttons you normally see in an active review.

![image](https://github.com/user-attachments/assets/eca625f4-768d-419f-892a-f5403e24cb2c)

Then you will see the files icon that takes you to the matrix:

![image](https://github.com/user-attachments/assets/185133f6-3239-43f4-9d6e-735bb51d9469)

**Comment by mgalgs** [comment]
@earlAchromatic thanks!! That's perfect.
