### ISSUE TITLE
Review vertical page layout efficiency is really low

### ISSUE THREAD

**Issue by nate-thirdwave** [Reviewable/Reviewable#1198]
When dropping in to a review, I've noticed that the vertical UX of the page has gotten really inefficient where it's many many vertical pixels before I can get to the actual meat of the review. Moving the check statuses to their own "card" has exacerbated this, but  the other header cards have contributed in their own ways  The spacing between the cards even hoovers up a lot of space.

Somewhat frustratingly, my monitor has a lot of horizontal space, even if I rotate the whole thing into portrait mode, I end up utilizing maybe a third of the width for actual material.  When my monitor is in horizontal (standard) mode it's over 2160 pixels tall and yet I still cant get a single line of code review in the first page with the default zoom and a standard 100% scaling on Ubuntu. 

Can the layout of the upper "cards" for everything from commit log to reviewers to the checks get densified? Maybe put some of them side-by-side or massage them into some other responsive format?   There's a lot of dead space in the layout right now.

Below: The entire first screen's worth of a review when I have my browser be halfwidth of a 4k monitor.
![image](https://github.com/user-attachments/assets/c15e4740-984f-4d50-b19c-d931d9d5a89d)

**Comment by pkaminski** [comment]
Hey Nate, have you tried collapsing (some of) the panels?  The collapsed panels will reflow horizontally and you can either expand them to see the contents as needed, or click on them to get a full-screen modal instead.  (Also, the file matrix will end up in a sidebar in the foreseeable future...)

**Comment by pkaminski** [comment]
@nate-thirdwave — ping.
