### ISSUE TITLE
Add basic keyboard shortcuts

### ISSUE THREAD

**Issue by kevinxyz** [Reviewable/Reviewable#12]
Wishlist of keyboard shortcuts, from Reitveld (GCR):
![gcr](https://cloud.githubusercontent.com/assets/670053/4360674/1b3e6b80-427e-11e4-92ed-b6a11374f434.png)

**Comment by pkaminski** [comment]
Basic keyboard shortcuts are now available and fully customizable (hit ? for a cheatsheet as usual).  Apologies for the month-long delay -- life got in the way.  Please open new issues if you find bugs or if you need me to add more commands for binding.  Thanks!

**Comment by al-the-x** [comment]
Sorry to comment on an old issue, folks. What about the keyboard shortcut for "Publish"...? Did that land?

**Comment by al-the-x** [comment]
Sorry, I should have checked [the default key bindings](https://reviewable.io/bindings.json) first. I just found "Publish all comments": `sendAll()`... I'll map that in my custom binding file.
