### ISSUE TITLE
Line comments should be displayed in the GitHub Files Changed view

### ISSUE THREAD

**Issue by Kwpolska** [Reviewable/Reviewable#120]
Not everybody likes Reviewable, or wants to use it.  By posting your comments as top-level comments instead of per-line comments, and by not including any context there, you’re making it harder for those people to work or even see the feedback.  This sucks.

**Comment by pkaminski** [comment]
Sorry @Kwpolska, it's certainly not my intention to make life difficult for others.  However, the GitHub API constrains what I can do while still delivering the features that Reviewable users are looking for.  For a full discussion, see #14, but the short of it is that there's no way to post per-line comments in GitHub while generating only a single notification / message, and impossible to post line comments outside the delta region.  As for providing extra context, this is on the to-do list as #39.  Can you think of other ways to smooth over the experience?

Ultimately, though, it's up to each repo's owners to make a collective decision whether the trade-offs are worth it, knowing that they likely won't please everyone.

**Comment by Kwpolska** [comment]
Thanks for your response, I’ll work on that in my project.

I can’t think of any improvements, other than including the code with e-mails and comments.
