### ISSUE TITLE
Key binding to copy line path of comment

### ISSUE THREAD

**Issue by larryhudson** [Reviewable/Reviewable#1201]
Hey there, I'm really enjoying Reviewable, thanks for all your work!

It would be great if we could have a custom key binding for the 'Copy line path' when you are viewing or creating a comment. I would love to be able to jump through the comments that need attention with '.', and then hit 'c' to copy the line path of the comment that I am focusing on - ideally without opening the little context menu.

Let me know what you think :) thanks again!

**Comment by pkaminski** [comment]
Good idea — done!  Check out the updated [`bindings.json`](https://reviewable.io/bindings.json).

**Comment by larryhudson** [comment]
Thank you! I was specifically talking about the 'copy line path' for a comment, but copying the file path is useful too.
