### ISSUE TITLE
Link to custom key bindings docs is broken

### ISSUE THREAD

**Issue by larryhudson** [Reviewable/Reviewable#1202]
Hi again, while customising my key bindings, I realised the 'You can customize these shortcuts and add more' link at the bottom of the shortcuts list is broken.

It is linking to "https://docs.reviewable.io/#/accountsettings?id=custom-key-bindings" whereas it should be "https://docs.reviewable.io/accountsettings#custom-key-bindings".

**Comment by pkaminski** [comment]
Oh man, thanks for reporting this!  It turned out we had a few dozen of these links spread throughout the codebase — I forgot to update them when we switched to a new docs site generator.  Should all be fixed now.
