### ISSUE TITLE
Show pull request's branch name in reviewable UI

### ISSUE THREAD

**Issue by dbertram** [Reviewable/Reviewable#124]
While it's great that reviewable shows me the PR # at the top of all of the PR-level comments, it'd be really helpful if it also showed the name of the branch the PR is coming from.

For context, my company mostly has PRs coming in from branches within the same repo, rather than from forks of the repo. I find I still need to view the PR in GitHub so I can see the branch name, which I use to checkout the PR on my dev machine. I do have aliases set up to help with checking out PRs based on the PR#, but it's almost always better if I can just use the PR's branch name since it's usually a lot more descriptive than just the PR#.

**Comment by pkaminski** [comment]
This is actually already accessible if you click on the small "N commits" link under the file matrix.  The branch names will also become much more prominent in a major redesign coming in the next few days.

**Comment by dbertram** [comment]
Ah, cool. Thanks for the quick response!
