### ISSUE TITLE
Allow image upload on comments

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#125]
If you drag an image into a draft comment box on GitHub, it uploads the image to their servers and inserts the markdown to display it. If you do the same on Reviewable, it takes you to a new page showing just the image.

It would be nice to match this feature—images are particularly helpful when reviewing UI code.

**Comment by aztlan2k** [comment]
I agree, this is one feature that I miss from GitHub.  

When working on UI code, it's always nice to be able to include screenshots, mockups, etc... with pull requests.  Being able to take a screenshot and paste it into the pull request flow is really useful.  

Unfortunately, with Reviewable, I need to take a screenshot... save it to a file... upload that file to some service where i can get a permalink... and then include the link in markdown within the review comment.   

Not as nice of an experience.

**Comment by marcinwyszynski** [comment]
![wecanafforapony](https://cloud.githubusercontent.com/assets/571786/11558167/50039aa8-99b1-11e5-9576-4285e9bdbe50.jpg)

**Comment by pkaminski** [comment]
Oh frabjous day, you can now insert images into comments!  Paste, drag-drop, or even select from a file picker to your heart's content.

Note that non-image files are not currently accepted, because they require different security constraints that would be tricky to implement in such a way that the files would be accessible both from Reviewable and directly from GitHub.

**Comment by gilbertbw** [comment]
I am trying to add a comment to an image and it's not working. Has this feature been removed?

**Comment by pkaminski** [comment]
Sorry, there was a regression — should be fixed now.

**Comment by davidtobe13** [comment]
![Image](https://github.com/user-attachments/assets/c0b665e8-90f2-4eab-8927-fa105d33ce63)
