### ISSUE TITLE
Make relevant commit messages more obvious

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#126]
When I'm reviewing individual commits, I often want to refer to the description of the changes I'm reviewing. This is an error-prone process, as I need to figure out what revision I'm on, then match that to the original review discussion list and find the appropriate "New commits in rN" entry. It would be nice to call this out right up top somewhere.

**Comment by pkaminski** [comment]
The commit titles for the current diff range are available in the changes dropdown, and link to the full commits on GitHub.  Is that sufficient?

**Comment by jdm** [comment]
Could you screenshot what you mean? I don't see this information in the changes dropdown.

**Comment by pkaminski** [comment]
Sure, it should look something like this:
![image](https://cloud.githubusercontent.com/assets/1646896/8715011/956e433a-2b30-11e5-950a-d333c5662701.png)

If you don't see the "Commits in rN:" section then something's gone wrong -- can you show a screenshot of your dropdown?

**Comment by jdm** [comment]
Aha, so that's what you meant by dropdown :) I've never tried clicking that before.

**Comment by pkaminski** [comment]
Heh, yeah, *that* dropdown.  Is it sufficient?

**Comment by jdm** [comment]
It's working for me now that I know about it!

**Comment by pkaminski** [comment]
Excellent.  Discoverability of this and other features is next on my hit list.
