### ISSUE TITLE
NETWORK_ERR: XMLHttpRequest Exception 101

### ISSUE THREAD

**Issue by pkaminski** [Reviewable/Reviewable#127]
@larsbergstrom I'm seeing these errors crash Reviewable within 30ms of loading the page, with all instances so far attributed to unauthenticated users visiting Servo reviews with Chrome.  All I have to go on are IP addresses that seem to point at Google proxies in MTV.  I'm guessing it might be some kind of plugin that restricts network connections but not sure how reproduce or investigate.  Can you let me know if you hear any complaints about these crashes, and perhaps put me in touch with somebody experiencing them?  Thanks!

**Comment by larsbergstrom** [comment]
@pkaminski I'll ask around and see if we can figure out who it is! We're not actively collaborating on code with anybody at Google right now, though we do have lots of architectural & standards discussions with them, so I'm not super surprised to hear they're looking at some reviews.

**Comment by tabatkins** [comment]
What effect does it have on the page being looked at?  I can ask around the team on Monday and see who's been hitting up Servo reviews in the office.

**Comment by pkaminski** [comment]
Thanks!  The PRs that it's happened for so far are: servo/servo#6411, servo/servo#6561, servo/servo#6616, servo/servo#6593, servo/servo#6536, servo/servo#6629, and servo/servo#6582.  Oddly, the referrer is often www.google.com/url?..., www.google.ru/url?..., or www.google.co.uk/url?... -- I'm not sure what that means.  The effect would be an immediate crash with a page-blocking error dialog like the one shown in #117 (but with this error at the bottom of the dialog), so it's not exactly subtle.

**Comment by pkaminski** [comment]
This has mysteriously stopped happening ~3 months ago.  Perhaps Google fixed their crawler?
