### ISSUE TITLE
Can't scroll horizontally in the file matrix

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#129]
See https://reviewable.io/reviews/servo/servo/6205 . It's impossible to select revisions past r10 on my screen.

**Comment by pkaminski** [comment]
Yeah...  I've known about this issue for a very long time now, and still haven't managed to come up with a good design that would let you access any range of revisions.  :disappointed:  I'll give it another try.

Also, I gotta say that's an impressive number of obsolete files you've got in the PR.

**Comment by pkaminski** [comment]
OK, my solution's not ideal, but it's better than not being able to access revisions and every fancier design I tried fell on the uncompromising altar of CSS:

- The file matrix will now overflow the main (white) rendering area to use the entire window's width when necessary.
- If it's even wider than the window, it'll scroll horizontally.  The scroll bar is at the bottom, but most (all?) browsers should auto-scroll when dragging a revision range close to the edge.
- Hidden files no longer participate in setting the first column's width until revealed.

I believe this addresses the issue.
