### ISSUE TITLE
Fully reviewed revisions are sometimes selected as "next unreviewed diffs"

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#130]
For example, on https://reviewable.io/reviews/servo/servo/6490 the default revision I'm sent to is r16 against r15, in which all of the files shows have green eyes marked beside them. The "mark as reviewed" button remains greyed out whatever I do, and I always have to select a more appropriate revision manually. If I ever press the "next unreviewed diffs" button, it automatically sends me back to r16 against r15.

**Comment by pkaminski** [comment]
Oops, thanks for finding this bug in the range proposal algorithm -- it broke when dealing with obsolete files in some cases.  Fixed.
