### ISSUE TITLE
UI makes it appear though you are at the end of the page

### ISSUE THREAD

**Issue by AutomatedTester** [Reviewable/Reviewable#131]
When you reach the end of the discussion section the page looks like it has ended. Perhaps adding a further box around it all to signal to the user that the page still has some things further on if it is not obviously visible (below the fold).

![fix_broken_references_-_1_to_review_-_1_unreplied_-_reviewable](https://cloud.githubusercontent.com/assets/128518/8801336/b47857fe-2fb1-11e5-98aa-0d09f9fe304b.jpg)

**Comment by pkaminski** [comment]
Usually the scroll bar is supposed to serve this purpose, but I keep forgetting that OS X has "improved" the UI by removing this important cue.  Thanks for reminding me -- I'll think of some other way to make it clear that there's more content below the fold.

**Comment by pkaminski** [comment]
I added a new indicator that appears in the lower-right corner when a section gap is straddling the fold.  Hopefully this will be a sufficient cue that there's more content below, please reopen if not.
