### ISSUE TITLE
Reviewable button missing from a PR

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#133]
https://github.com/servo/servo/pull/6722

**Comment by Walkman100** [comment]
I can see it?

**Comment by pkaminski** [comment]
It's possible the first attempt at inserting the button failed for some reason, though I can't find any trace of this in the logs.  It's also possible there was a race in editing the PR description that the author won -- e.g., they opened the PR and immediately started editing the description, Reviewable added the button a few seconds later, then the author inadvertently overwrote this with their own changes.  Unfortunately, GitHub doesn't support atomic edits or any other kind of concurrency control on metadata.

Reviewable is persistent, though, and will keep trying to put the button in any time the PR is updated or the review visited by somebody with admin rights, so the button will eventually show up.  Ironically, edits to the description don't trigger a change event that Reviewable can respond to by checking if the button is there.  Changing the labels or the assignee will trigger a resync, though, so you can always do that (or visit the review via your Reviewable dashboard) to get the button to show up.

**Comment by jdm** [comment]
Good to know. Thanks!
