### ISSUE TITLE
allowing comments on binary files

### ISSUE THREAD

**Issue by savvopoulos** [Reviewable/Reviewable#135]
See issue #26 for previous discussion:
while file level comments are not important in the common case (because you can add a comment anywhere in the file), it'd be nice to be able to comment on binary files in any way, even if this means representing binary files as a one-line change (on which one could comment).

**Comment by pkaminski** [comment]
This is now available.

**Comment by MatthewY-Circle** [comment]
Is this feature still around? I can't find a button for it.

**Comment by elias6** [comment]
I am trying to add a comment to a binary file in a pull request and I can't figure out how to do it. What am I supposed to do?

**Comment by pkaminski** [comment]
@badz0 Bohdan, could you please check whether there's a regression here?  There should be a "start a new discussion" button for binary files.

**Comment by badz0** [comment]
The "start a new discussion" button is on its position as expected. @elias6 is there such button for your file? If there's no please provide more details. Is it a public repo?
![image](https://user-images.githubusercontent.com/12611322/64715658-93851c00-d4c9-11e9-8a3a-28be4fd6ee98.png)

**Comment by elias6** [comment]
Oops... I thought this was for GitHub in general and not for any third-party tools. I think my comment can be disregarded.

**Comment by debbiehmartin2** [comment]
Losing one Cryptocurrency can be a devastating thing to experience, the fact that it is almost impossible to recover a Stolen or lost Crypto coin hurts more than anything. When a person gets scammed of their money while investing in a crypto currency platform the only thing they can think of is how to report the company and get back their money. Most victims of the scam contact their wallet account provider, their bank or the law enforcement, a few end up hiring a lawyer to sue the company but after all these stress they still can't get their money back. Please everyone should be careful where they invest their money. Cryptocurrency has made many rich and at the same time made so many broke and desperate. Few weeks ago I was referred to Rustik Cyber Hack Service Funds Recovery and I was able to get back all my bitcoin that was Stolen through a fake investment company. If you want to recover your cryptocurrency that was stolen or lost I recommend you to Rustik Cyber Hack Service are reliable and trustworthy. contact them I wish you all the best. 


Rustik Cyber Hack Service

Email: rustikcyberhacksservice @ gmail com

Call/WhatsApp (+ 1) 38. 63. 4 8. 78. 38,

Telegram: Rustikcyberservice
