### ISSUE TITLE
Subscription access for all admins

### ISSUE THREAD

**Issue by teamon** [Reviewable/Reviewable#137]
Hi,

We have few people added to the "Owners" team, but only I can edit the reviewable subscription details (as the one who subscribed at the first place).

Would it be possible to allow access to subscription edit for all organization admins?

/cc @chytreg

**Comment by pkaminski** [comment]
Hmm, that could be a bit tricky, especially since supporting multiple independent subscriptions per organization (e.g., for separate teams) is a design goal.  Can you say more specifically which parts of the subscription you'd like to let others edit?

**Comment by chytreg** [comment]
I think the only need is to change additional organisation part 

![](https://dl.dropboxusercontent.com/s/6xjvdgxp2ierud8/2015-07-27%20at%2010.30%202x%20%281%29.png?dl=0)

This is our last case:
teamon is admin on A, B - he managed subscription on organisation A, and configure organisation B with reviewable
chytreg is admin on A, C - and want add organisation C to subscription of organisation A

**Comment by pkaminski** [comment]
OK, I see how that would make sense for you.  I think it's a pretty rare use case, though: adding a new org doesn't happen too often (I assume?) and you're the only customer using the cross-organization feature at this point.  Also, to make this change, I'd need to revisit the security constraints and redesign a good chunk of UI to allow for accessing other people's subscriptions, so it would get pretty tricky.

Let me suggest a slightly kludgy workaround: create a new GitHub user, make them a (non-owner) member of org A with no access to any repos, have them take over the subscription, and share the credentials among the owners of A.  Subscribing doesn't require any special permissions (beyond membership) so the security exposure of sharing the credentials would be limited to manipulating the subscription -- though of course you'd need to rotate credentials in case an owner leaves, etc.  (To "take over" a subscription, just have the new account subscribe then cancel the old subscription.  Do it near the end of your billing cycle to avoid being charged twice for the overlap.)

I realize this is not ideal but do you think it might work for you?

**Comment by chytreg** [comment]
Yes, it's rather rare than often use case. I'm fine how it works now. 
@teamon Do you have any thoughts on this issue?

**Comment by teamon** [comment]
If this is huge change I'm fine with how it works now, there are for sure more important issues to be addressed :)
