### ISSUE TITLE
Earlier revisions should not show comments from later revisions

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#142]
In https://reviewable.io/reviews/servo/servo/6741 Ms2ger left three comments on one line in separate revisions, but they all show up when viewing the very first revision and it is quite confusing.

(First comment in CSSStyleDeclaration.rs)

#136 is related.

**Comment by pkaminski** [comment]
Discussion porting across revisions is a core feature of Reviewable, and one of the fundamental invariants is that all discussions are showing all the time (to be amended to "either all or none" with #94), so this is pretty unlikely to change.  For the specific case you mention, note that 2 of the 3 comments have a red corner label, which indicates that the mapping is of poor quality and the comment might not relate to the line in the current revision.  You can click on a corner label to switch the diff to the exact revision the comment was made on.
