### ISSUE TITLE
Request: Make "merged" status visible/more prominent in PR view

### ISSUE THREAD

**Issue by dbertram** [Reviewable/Reviewable#145]
I frequently enter reviewable.io from notification emails for comments that have been made on PRs. While the "reviews" page makes a PR's status (merged, active, etc.) clear, if you go directly into a PR I don't see any clear indicator of its status. Am I missing something, or is it not included in that view at all?

It's happened to me a few times where I enter a PR in reviewable.io via a link in my email, make a comment, and then later realize that the PR I just commented on has already been merged; usually because I've ended up looking at something in the PR via github.com directly.

It would be great if the PR view made this more obvious. Maybe copy github and include the merged/deleted events in the review discussion section at the top of a PR in reviewable? Or possibly a header or footer indicating that the PR branch has been merged and/or deleted.

**Comment by pkaminski** [comment]
Good point @dbertram.  I changed things so that the toolbar will now reflect the PR's closed/merged status even if the review is not officially complete.  There's a small button that lets you go back to normal review mode in case you need to for some reason.  (The button may look a bit mysterious right now, but help mode is coming very soon.)  Hopefully this will make the state of the PR obvious enough -- if not, I can punch up the styling a bit.

**Comment by dbertram** [comment]
I'm seeing deleted/abandoned status clearly on the review page, but I'm not seeing any indication for merged PRs.

For example, the below review was deleted, and shows that status in the header:

![image](https://cloud.githubusercontent.com/assets/864848/9408224/b016acb6-47de-11e5-8261-ccbddf3b48bc.png)

This review was merged, but doesn't show any indication of that (that I could see):

![image](https://cloud.githubusercontent.com/assets/864848/9408232/c63387da-47de-11e5-92ab-8b75d75813d7.png)

Bug, or I just missing something?

**Comment by pkaminski** [comment]
Smells like a bug...  Can you give me the repo and PR number of the
offending PR?  Thanks.


On Fri, Aug 21, 2015 at 5:30 AM, Dane Bertram <notifications@github.com>
wrote:

> I'm seeing deleted/abandoned status clearly on the review page, but I'm
> not seeing any indication for merged PRs.
>
> For example, the below review was deleted, and shows that status in the
> header:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/864848/9408224/b016acb6-47de-11e5-8261-ccbddf3b48bc.png>
>
> This review was merged, but doesn't show any indication of that (that I
> could see):
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/864848/9408232/c63387da-47de-11e5-92ab-8b75d75813d7.png>
>
> Bug, or I just missing something?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/145#issuecomment-133410538>
> .
>



-- 
Piotr Kaminski, Founder, reviewable.io

**Comment by dbertram** [comment]
Those screenshots are both from private repos, so I can't really publish that info here, sorry.

**Comment by pkaminski** [comment]
Could you send the information to support@reviewable.io please?  I need to understand what state the PR is in, as there's nothing obviously wrong with the code in this area.  Thanks!
