### ISSUE TITLE
Request: Include PRs where you are mentioned via an alias/org team in "My Reviews"

### ISSUE THREAD

**Issue by dbertram** [Reviewable/Reviewable#149]
If this has already been implemented, then I might be seeing a bug.

The workflow on my team is to use organization teams/aliases to notify those who should be involved in a code review. e.g. "[PR description]\n\n@[team alias] please review."

Currently, when someone creates a new review and mentions me (via a team alias), I get the notification email from GitHub, but the PR does not show up in "My Reviews" on reviewable.io.

**Comment by pkaminski** [comment]
That sounds like a good idea.  I thought those PRs would already be included by GitHub's `involves` query, but apparently not.  I'll try to add it in -- the code is easy, but I'm concerned about the invasive auth scopes that GitHub currently requires to get a list of your teams.

**Comment by pkaminski** [comment]
Never mind, the auth was a non-issue after all.  This is now implemented, and you should see all team-mentioned reviews on your dashboard.

**Comment by dbertram** [comment]
Sweet! Thanks for the quick implementation, @pkaminski!
