### ISSUE TITLE
Slow PR albeit patch isn't that large

### ISSUE THREAD

**Issue by nox** [Reviewable/Reviewable#150]
https://reviewable.io/reviews/servo/servo/7227

I can't seem to load the only diff in that PR.

**Comment by pkaminski** [comment]
Interesting, the file is definitely small enough that Reviewable should have no trouble computing the diff.  Looks like you accidentally found some way to wedge the algorithm.  Thanks -- I'll dig into it!

**Comment by pkaminski** [comment]
This was indeed a bug in the post-diff delta optimizer.  Fixed.
