### ISSUE TITLE
Logout button needs a tooltip

### ISSUE THREAD

**Issue by ryan-williams** [Reviewable/Reviewable#152]
Could not figure out what the icon meant:

![](http://cl.ly/image/2L1Z3K1E1y1t/Screen%20Shot%202015-08-21%20at%205.21.45%20PM.png)

Clicked it, got logged out; slightly annoying.

**Comment by pkaminski** [comment]
Hey Ryan, as discussed in #53 I'm not going to use tooltips in Reviewable.  However, the new help system is live now, so you can hit F1 to get help for whatever your mouse cursor is over, or for the page overall.  This is cued by a small indicator in the lower-right corner, and also by a more noticeable popup next to the mouse cursor for new users.  As an existing user, I automatically switched off the "noob" treatment for the first 14 days, so you don't get bugged about buttons you already know and use often -- but if you'd like to turn those back on, just hit F1 and enable the "point out new features" toggle.  You should then have no problem discovering the help for new controls.

Please let me know how this works for you!

**Comment by ryan-williams** [comment]
Cool, hadn't tried that, looks neat, thanks
