### ISSUE TITLE
Function name in diffs

### ISSUE THREAD

**Issue by mmlb** [Reviewable/Reviewable#153]
It'd be great if reviewable would display the name of function that encapsulates a hunk, similar to what git does.

**Comment by pkaminski** [comment]
From #208, it would also be nice to be able to quickly expand the diff to show an entire function.

**Comment by tracernz** [comment]
We're looking at adopting Reviewable for our project. Both of these suggestions would be extremely help, and the original suggestion is a sticking point for me. :+1:

**Comment by mmlb** [comment]
@pkaminski actually I have recently had a slightly weird review experience where this seems like a UX bug. I had a diff where a resource seemed to be cleaned up twice. I had to expand the unchanged context lines to notice that it was happening in 2 different functions. git would have separated those into different hunks.

**Comment by pkaminski** [comment]
@mmlb, can you clarify or perhaps send a screenshot to support@reviewable.io?  If the lines were in two different functions then I assume there was a "collapsed" area in between them (i.e., they were in two different "hunks"), which should've been a pretty strong hint even if the indentation lined up.  But I probably misunderstood what you saw.

**Comment by mmlb** [comment]
@pkaminski screenshots sent. You are correct that there are "collapsed" areas between the different lines, but there is no indication of functions being crossed. So its up in the air whether the lines are in different functions or whether there are just a bunch of unchanged lines in between, where terminal git training makes the latter interpretation much more likely.

**Comment by pkaminski** [comment]
I've taken my best shot at implementing this.  It relies on the syntax highlighting regexes and correct indentation so I'm sure it won't work in all cases, but hopefully at least most of them.  You can now also expand the diff to encompass the whole function/method/class/whatever by clicking on the declaration header (@sasha-s).  Let me know if you spot bugs.

Note one design decision:  I only show the declaration header below a collapsed section if it doesn't already appear further up the diff, either in the diff itself or as a declaration header.  I'm not sure yet if this is the right thing to do (to save on space and repetition), or if I should consistently show the declaration header below every collapsed section.  Feedback welcome.

**Comment by mmlb** [comment]
Thanks! I don't have any reviews right now and am neck deep into something so can't artificially check this out. From your description it sounds about right. :smile:

**Comment by mmlb** [comment]
@pkaminski I'm not seeing this showing up at all :(. I'm currently looking at .go and .md files. Also, what's the declaration header you mention?

**Comment by pkaminski** [comment]
The feature relies on indentation so it mostly won't work with .md files unless you actually indent the content of the sections.  As for .go, it turns out that its highlighter doesn't identify functions, unlike those for all the other languages.  I'll figure out a workaround shortly.

**Comment by mmlb** [comment]
you also mention syntax highlighting though which the md files do exhibit which led me to think it would work there.

**Comment by pkaminski** [comment]
OK, Go is fixed and I ~~hacked~~ carefully engineered a workaround for Markdown's lack of indentation, so it should show section titles as well.

**Comment by mmlb** [comment]
Awesome! Thanks for the -hack- *ehem* work around

**Comment by sasha-s** [comment]
thanks, function names do work with Go now.
