### ISSUE TITLE
Feature request: delete branch after merge

### ISSUE THREAD

**Issue by mmikulicic** [Reviewable/Reviewable#154]
In our workflow we delete branches after merge, but we have to switch back to github to do so. Would it be possible to offer a button to delete a branch after merge?

Thanks

**Comment by pkaminski** [comment]
Hey @mmikulicic, this is already available but you need to make this decision before you merge:
![image](https://cloud.githubusercontent.com/assets/1646896/9615265/0d705ec2-50ac-11e5-8c3a-9b4f25888dd2.png)
Use the small "cycle" button to the right to switch between "retain" and "delete".  But enough people have found this UI unintuitive that I'm going to queue it up for a redesign...
