### ISSUE TITLE
Small change not shown due to performance concerns and "show diff" button not working

### ISSUE THREAD

**Issue by tschneidereit** [Reviewable/Reviewable#155]
In [this review](https://reviewable.io/reviews/mozilla/shumway/2361#-) of moderate size, the last two diffs (`test/unit/pass/{displayObject,graphics}.js`) are hidden to prevent CPU melting. They're somewhat large, but the changes are very small.

More importantly, there's no way to show them, as the "show diff" button just silently does nothing.

**Comment by tschneidereit** [comment]
Hmm, now that I marked the files as reviewed, they're happily shown if I select the right changes range in the file matrix.

**Comment by pkaminski** [comment]
Apologies, this was a regression.  Fixed.
