### ISSUE TITLE
Auto-expand the full conversation when opening a permalink

### ISSUE THREAD

**Issue by radix** [Reviewable/Reviewable#156]
For example, I wanted to link to this conversation: https://reviewable.io/reviews/rackerlabs/otter/1702#-JyJXhTbrGKaZqQ8zg9_

Opening that link only shows the last message, when really I wanted to show the whole context of the conversation.

**Comment by pkaminski** [comment]
Implemented, please give it a try.

**Comment by radix** [comment]
wow, very fast! Thanks @pkaminski :)
