### ISSUE TITLE
Support for .gitattributes -diff

### ISSUE THREAD

**Issue by Mikulas** [Reviewable/Reviewable#158]
Hi, this is a followup from gitter:

> Hi! is .gitattributes -diff supported? we have dependencies in repo, but it clutters reviews a lot…
> @Mikulas To be honest, I wasn't aware of .gitattributes -- thanks for the tip! I should be able to add support for -diff specifically but it'll take a bit of work to reproduce git's semantics (attribute inheritance, overrides, etc.). Could you please open an issue to track this? Thanks!

Relevant docs:
http://git-scm.com/docs/gitattributes#_description
http://git-scm.com/docs/gitignore#_pattern_format

**Comment by apinstein** [comment]
This is cool! Took me a while to figure out what it actually means, this is it:

in repo/.git/config
```
[diff "ignoregenerated"]
  command = echo "Suppressed diff of generated file: $1\\\\n\\\\c"
```

in repo/.gitattributes:
```
classes/generated/* diff= ignoregenerated
```

Are you just proposing to use `-diff` as the hint instead? Because the problem with what I showed above is that .git/config doesn't sync to remotes and wouldn't be available to you...

**Comment by pkaminski** [comment]
Yep, my intent is just to detect `-diff`.  I haven't really thought about what to do if a custom differ is set -- perhaps treat it as a binary file (needs reviewing but not diffable)?

**Comment by apinstein** [comment]
The weird thing about `-diff` is that it causes generated files to show up in diff as “Binary file changed”, which seems maybe a little scary if you don’t understand why?

Maybe you could ignore other canonical `-diff` analogs like `-diff=ignoregenerated`?

**Comment by pkaminski** [comment]
That sounds like a reasonable idea too.  I think once I can parse `.gitattributes` and apply entries to files in the review, we can easily experiment with the right semantics.

**Comment by apinstein** [comment]
Agreed, thanks! That’s exciting.

**Comment by thockin** [comment]
This sounds like a good feature for us - we have a lot of generated files.

**Comment by pkaminski** [comment]
This is now implemented, but the `.gitattributes` file-pattern-matching "spec" is exceedingly vague, so I don't have high confidence that I've correctly replicated `git`'s semantics.  @Mikulas, @apinstein, I would really appreciate it if you could test with any existing `.gitattributes` files you might have and report any surprises (and successes!) here.  Thanks!

**Comment by Mikulas** [comment]
This is great, thank you very much 😄 Will try and report back.

**Comment by Mikulas** [comment]
@pkaminski Our `.gitattributes` also contain definitions such as 
```
*.php diff=php
```

which in theory should hint git how to find „functions“. There are mulltiple built in regexes (https://git-scm.com/docs/gitattributes#_defining_a_custom_hunk_header).

However, Reviewable now hides those php source files by default and we have to click ”show diff“ for each file.

> Custom diff specified in .gitattributes: php.

Could Reviewable please show those files as well when using builtin diffs?

**Comment by apinstein** [comment]
We have that exact same problem. Our current file looks like:

```
*.php                                                                   diff=php
**/*[-\.]min.js                                                         diff=ignoregenerated
classes/virtualtour/om/*                                                diff=ignoregenerated
classes/virtualtour/map/*                                               diff=ignoregenerated
conf/classmap-virtualtour-conf.php                                      diff=ignoregenerated
skins/tourbuzz/default/www/shared/css/shared.css                        diff=ignoregenerated
```

**Comment by pkaminski** [comment]
I changed the logic a bit:  if the `diff=<token>` token matches one of the known code highlight languages, then it will force the diff (in that language), ignoring the file extension, size, and contents.  If the token doesn't match then the diff will be blocked as before.  I think this will address your scenarios, please give it another try!

**Comment by apinstein** [comment]
I am being told it works nicely now!

**Comment by thockin** [comment]
Is there a spec for how to use this?

**Comment by pkaminski** [comment]
Basically follow the [git spec](http://git-scm.com/docs/gitattributes#_description).  `-diff` will disable diffing, `diff` will force it, `diff=<language>` will force it with highlighting for that language, and `diff=<notalanguage>` will disable it.

**Comment by thockin** [comment]
great!  Thanks.
