### ISSUE TITLE
Reviewable suspiciously escapes commas followed by spaces in PR titles

### ISSUE THREAD

**Issue by nox** [Reviewable/Reviewable#160]
https://reviewable.io/reviews/servo/servo/7559

![capture d ecran 2015-09-08 a 12 54 30](https://cloud.githubusercontent.com/assets/123095/9733071/db31ea66-5628-11e5-8ec7-7d9ca453effb.png)

**Comment by pkaminski** [comment]
What, I don't even...  Will investigate.

**Comment by pkaminski** [comment]
This was a bug in my markdown escaping regex.  Fixed -- the broken title should update a few seconds after the next time you reload the review page.
