### ISSUE TITLE
Highlight changed line background

### ISSUE THREAD

**Issue by mmlb** [Reviewable/Reviewable#161]
When reviewing a PR where 1 or 2 characters are all that is changed in a line I have to work extra hard to find all the changes. The defaults of light red/green on white does not make it any easier. It'd be nice if the current colors were used as the background color for the line and the change itself a bit darker.

**Comment by mmlb** [comment]
Hmm actually just noticed this is done in `unified` diff mode, so I'm asking for `side-by-side` mode to be like `unified`

**Comment by pkaminski** [comment]
I'm not going to make this change for everyone, but you can easily apply a custom stylesheet yourself.  Just put these in a file (e.g. a gist), serve it with mime type style/css (e.g., via https://rawgit.com/), and put the URL in the custom stylesheet field of your account settings:

```
.two.column.diff .diff.line:not(.keep) .line.wrapper:not(.empty) .left.line.content {
  background-color: #FBDDDD;  /* rgba(91, 220, 114, 0.20) on white */
}
.two.column.diff .diff.line.base:not(.keep) .line.wrapper:not(.empty) .left.line.content,
.two.column.diff .diff.line.whitespace:not(.keep) .line.wrapper:not(.empty) .left.line.content {
  background-color: #FFF7F7;  /* rgba(91, 220, 114, 0.05) on white */
}

.two.column.diff .diff.line:not(.keep) .line.wrapper:not(.empty) .right.line.content {
  background-color: #DDF7E2;  /* rgba(91, 220, 114, 0.20) on white */
}
.two.column.diff .diff.line.base:not(.keep) .line.wrapper:not(.empty) .right.line.content,
.two.column.diff .diff.line.whitespace:not(.keep) .line.wrapper:not(.empty) .right.line.content {
  background-color: #EFFCF1;  /* rgba(91, 220, 114, 0.05) on white */
}

.two.column.diff .diff.line .left.line.content .delta {
  background-color: rgba(240, 92, 92, 0.30);
}
.two.column.diff .diff.line.base .left.line.content .delta,
.two.column.diff .diff.line.whitespace .left.line.content .delta {
  background-color: rgba(240, 92, 92, 0.15);
}

.two.column.diff .diff.line .right.line.content .delta {
  background-color: rgba(91, 220, 114, 0.30);
}
.two.column.diff .diff.line.base .right.line.content .delta,
.two.column.diff .diff.line.whitespace .right.line.content .delta {
  background-color: rgba(91, 220, 114, 0.15);
}
```

Or just use this URL where I did the above for you: https://rawgit.com/pkaminski/2922da3d58f76a8ed7bf/raw/highlight_lines_in_two_columns.css  :smile:

**Comment by mmlb** [comment]
This'll work thanks!
