### ISSUE TITLE
Comments should resize to show images

### ISSUE THREAD

**Issue by ryan-williams** [Reviewable/Reviewable#167]
I added an image to a comment and got this:

![](http://cl.ly/image/432C383x3K1P/Screen%20Shot%202015-09-16%20at%204.59.54%20PM.png)

The comment box is scrollable so I can pan over my image within that short comment box, which is not the best experience obviously.

**Comment by pkaminski** [comment]
Hmm, yeah.  Rendered markdown is typically smaller than the source text but there's clearly exceptions.  Not sure how to handle it without having the height jump back and forth as you switch between write and preview modes.  I'll think about it...

**Comment by pkaminski** [comment]
Fixed.
