### ISSUE TITLE
Webhook (or similar) for notifications

### ISSUE THREAD

**Issue by jonathanj** [Reviewable/Reviewable#168]
I'd personally like some way to receive notifications about new, updated, published etc. reviews (and when the author has addressed the review comments and is ready for another round) in a structured data format so that I can write integrations with our existing workflows that are more direct and less spammy than the default Github methods of notification.

**Comment by sasha-s** [comment]
We would also like to have webhooks.

**Comment by sasha-s** [comment]
We do need slack integration badly.

**Comment by Babacooll** [comment]
Same here, slack integration is really needed :) !

**Comment by kushal** [comment]
I got impatient and threw together some a simple go webapp for this, see https://hackernoon.com/a-lighter-pull-request-workflow-972301e30c5#.2mucfaepq

**Comment by pkaminski** [comment]
Cool!  And apologies for still not having this built in, but Reviewable's architecture makes this non-trivial (many hook-worthy events don't currently touch the server) so simpler / higher priority issues have always won out.

**Comment by tsuna** [comment]
I'm just getting started with Reviewable and stumbled upon this issue when Googling for "Reviewable slack notification".  Any chance that we can get some sort of Slack integration so we can follow code reviews there?

**Comment by pkaminski** [comment]
Hey Benoit, this issue is definitely not closed!  The feature attracts consistent interest from users (and potential users) and will get implemented sooner or later, but it hasn't yet risen to the top of the priority list.

**Comment by OlafSzmidt** [comment]
Would be interested in this!

**Comment by aphexcx** [comment]
Still desperately need this for our team; this is our #1 most requested feature and is making us start to look elsewhere (codacy etc) because of how disruptive it is to our workflow. Reviewers need to be notified when their action is required, and PRs frequently languish for far longer than they should because attention was not drawn to them.

**Comment by pkaminski** [comment]
So, given how GitHub, Slack, and Reviewable have evolved, I'm actually wondering if this is still needed.  Let me pitch a new plan and let's see what the feedback is.

First, GitHub has a new Slack app that is more [configurable](https://github.com/integrations/slack#configuration) so you can, e.g., limit it to just posting about new PRs and reviews.  It's also open source, so you in principle you (or I) can contribute any features needed to improve the experience.  I am also currently working to integrate with GitHub's review system, so in the near future most everything published from Reviewable will show up as a GH review.  And recently Reviewable started including the review status description generated by a custom review completion condition in the published message, so you can generate machine-readable data that way and read it out via any of GitHub's notification mechanisms.  It also includes an updated listed of people being waited on.  I think this effectively covers all the reasons given for having a custom Reviewable integration for Slack -- am I right?

I think another reason to stick to the GitHub notification system is that, with the upcoming integration with GH reviews, it'll become a lot more practical to have activity on a single review spanning both systems, so any notification system specific to Reviewable would miss events originating from GitHub.

**Comment by johlju** [comment]
I agree with @pkaminski that notifications should come from GitHub (or any other Reviewable supported platform) - Reviewable (or any other review tool) updates GitHub, GitHub sends out a webhook that a change occurred. There are also an ecosystem of GitHub Apps that can be used to further enhance the automation when GitHub is updated.

**Comment by pkaminski** [comment]
I'm going to take silence as assent and close this issue.

**Comment by aphexcx** [comment]
Just got notified about this.

The issue with using github notifications (which we already do) is that reviewable comments posted to PRs are extremely verbose and ill-suited to the short status notifications we are looking for in our slack channel. 

Here is an average notification:
![screen shot 2018-06-19 at 3 28 53 pm](https://user-images.githubusercontent.com/2283165/41627615-d568de00-73d5-11e8-97fa-d16f7b5fecb7.png)

These are awful to read, and create mountains of spam in our channels, but they're still better than not being notified at all. Are you saying there's a way to modify what Reviewable comments to the PR? What I want is a simple 1-2 line thing saying '@user commented' or '@user resolved a discussion' or '@user approved this review'.

**Comment by pkaminski** [comment]
Right, but 1) those notifications should normally start out collapsed (your screenshot has a "show less" link at the bottom, which is the state I expect it started in?), and 2) I'm actively working on posting line comments as such in GitHub whenever possible, which will exclude them from the summary posted in Slack.  Between these two things I expect the experience will become good enough.  If not, we can try to contribute a change to GitHub Slack plugin to cut off the summaries after the first `-------------` line, which seems like a general and useful enough change that there's a fair chance they'd accept it.

**Comment by pkaminski** [comment]
So unfortunately sending native line comments isn't feasible due to API limitations (see #437 for details), which means we're onto plan B.  I have PRs pending to change the Slack plugin to cut off the summary after the first `<hr>` but the repo owner has been non-responsive so far.  Feel free to add some +1 reactions to the issue... https://github.com/integrations/slack/issues/633

**Comment by abinoda** [comment]
Hi all – I'm the founder of [Pull Reminders](http://pullreminders.com), a Slack app that streamlines Reviewable and GitHub code reviews with customizable reminders and alerts. With Pull Reminders, you can set up recurring reminders for pending code reviews as well as receive DMs in real-time for things like reviews, comments, etc.

There are a handful of teams seeing good results using Pull Reminders alongside Reviewable and @pkaminski  was kind enough to suggest that I post here in case anyone here may find it helpful. You can learn more about Pull Reminders at http://pullreminders.com and/or ping me here with questions!

cc: @aphexcx @johlju @OlafSzmidt @tsuna @kushal @sasha-s @jonathanj @Babacooll @randywallace

**Comment by pkaminski** [comment]
Welp, Pull Reminders got bought by GitHub and my proposed changes to GitHub's Slack plugin roundly ignored, so I've had a change of heart on this issue.  Reviewable will now send review status updates to a webhook of your choice -- see the [Headway post](https://headwayapp.co/reviewable-changes/review-status-notifications-webhook-188778) for details.
