### ISSUE TITLE
Option to show one file per page

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#17]
For reviews with lots of files, the model of showing the changes to all files on a single page really breaks down. Other code review tools, e.g. Gerrit, show a single file per page.

There are clearly tradeoffs here, but it would be nice to have an option of seeing a single file per page. I'd happily trade the convenience of seeing all diffs at once for pages that loaded dramatically faster.

**Comment by danvk** [comment]
In light of recent performance issues (#60) and "diminishing returns", is this something you'd be open to revisiting? Sometimes the way to be fast is to do less.

**Comment by pkaminski** [comment]
It's now possible to open a file in its own tab/window by holding down the appropriate modifier key (whatever your browser normally uses: cmd/ctrl, shift) when clicking on a filename.  When you hold down the modifier key a button also appears at the top of the file matrix to open each file in its own tab/window.  It's not exactly the "mode" that you originally asked for but I think it's the best compromise given the overall design.

**Comment by danvk** [comment]
Thanks for adding this. The per-file view would be more useful if you could navigate from one file to another from it.

**Comment by pkaminski** [comment]
That's a good idea, let met think how to shoehorn it into the UI.

**Comment by pkaminski** [comment]
The single-file mode is now mo' betta', check it out.

**Comment by danvk** [comment]
Cool! Can we get the `n` and `p` shortcuts to go to the next/previous file working in this view, too?

**Comment by pkaminski** [comment]
These shortcuts work for me, though I just noticed that `shift+n`/`shift+p` were broken and fixed those.  Can you verify that `n` and `p` work for you in the normal view for this review?  If so, they should work in single file view too.

**Comment by danvk** [comment]
Sure enough, they don't work for me on the regular review page, either. I tried removing my [custom `bindings.json` file][1] and reloading the page, but this also had no effect.

[1]: https://gist.githubusercontent.com/danvk/cdb92d27f4092697ade9/raw/bindings.json

**Comment by pkaminski** [comment]
Did you try `shift+n` and `shift+p`?  The plain `n` and `p` will only
navigate to files that aren't yet reviewed at the latest revision (i.e.,
ones that makes up the red unreviewed counter).  Also, did you try on
different reviews?

On Mon, May 18, 2015 at 6:59 PM, Dan Vanderkam <notifications@github.com>
wrote:

> Sure enough, they don't work for me on the regular review page, either. I
> tried removing my custom bindings.json file
> <https://gist.githubusercontent.com/danvk/cdb92d27f4092697ade9/raw/bindings.json>
> and reloading the page, but this also had no effect.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/17#issuecomment-103298695>
> .
>



-- 
Piotr Kaminski, Founder, reviewable.io

**Comment by danvk** [comment]
I've been using https://reviewable.io/reviews/hammerlab/cycledash/513 as a test case. Shift+n and Shift+p _do_ work on the one-file page for that review. They don't have an effect on the regular review page, however.

**Comment by pkaminski** [comment]
Since you're the author of that PR, you're not expected to review any files
so `n` and `p` will never do anything (and the counter will never be red).
However, I can't reproduce your issue with `shift+n` and `shift+p` -- for
me, they work fine on both pages.  Make sure that you've got your diff
bounds set so that the diffs are non-empty, though, since those shortcuts
skip empty deltas.  (If you don't want any "smarts" to your file cycling,
you can bind `nextFile()` and `prevFile()` to your favorite keys instead.)

On Mon, May 18, 2015 at 8:09 PM, Dan Vanderkam <notifications@github.com>
wrote:

> I've been using https://reviewable.io/reviews/hammerlab/cycledash/513 as
> a test case. Shift+n and Shift+p *do* work on the one-file page for that
> review. They don't have an effect on the regular review page, however.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/17#issuecomment-103313714>
> .
>



-- 
Piotr Kaminski, Founder, reviewable.io

**Comment by EricCousineau-TRI** [comment]
Apologies to comment on an old issue, but in the documentation:
https://docs.reviewable.io/files.html#single-file-mode
> Reviewable automatically enters a single file mode [...]

Can I ask if it's possible to add a UI affordance (toggle?) for this, given that the logic seems to already exist?

The modifier+click makes it work, but feels a bit odd - esp. given all the existing polish and awesomeness that is Reviewable! :wink:
