### ISSUE TITLE
Navbar isn't populated when through navigating comments via keyboard

### ISSUE THREAD

**Issue by bpflanz-adfin** [Reviewable/Reviewable#171]
When you jump through the comments (using the keyboard shortcuts j/k or shift-j/shift-k), if you land in the middle of a file, the navbar doesn't contain the file-specific information in the top left (i.e., file name and revisions block).

I'm seeing this in Chrome Version 45.0.2454.93 (64-bit) on Ubuntu 14.04.3 LTS.

**Comment by pkaminski** [comment]
Thanks for the report.  I found and fixed a bug where the navbar filename info got detached from the page's DOM in some circumstances, though I think it was unrelated to using keyboard shortcuts.  Please let me know if you can still reproduce this.

**Comment by bpflanz-adfin** [comment]
I still see this happening.

Steps to reproduce:
I loaded up the demo review (making sure to reload the app in a cache-busting way), and selected at the very top that I want to see all diffs from first to most recent revision. Then I started navigating through the comments using shift-j. Once I wrapped around to the top, the navbar was missing the filename.

I'm also not convinced that this is related to keyboard navigation, but I wanted to share how I produced the error.

**Comment by pkaminski** [comment]
Reproduced.  Sorry, I'll look into it today.

**Comment by pkaminski** [comment]
More bugs found and fixed.  Hopefully this is the last of them, but I wouldn't bet on it...

**Comment by bpflanz-adfin** [comment]
This time I agree that it's fixed; thank you for the super-fast response!
