### ISSUE TITLE
RFE: Add option to display line numbers

### ISSUE THREAD

**Issue by bpflanz-adfin** [Reviewable/Reviewable#172]
Having read the discussion on this matter in Issue #20 , I'd like to add two reasons why I want line numbers in diffs:

1) I find that the line numbers anchor me while reading the diffs.
2) At times (surprisingly frequently), I'm writing comments on a thing that is done multiple times in close proximity, in which case I'd rather just leave one comment in which I say "also on lines 27 & 34". Similarly, there are cases where I'm explaining the requested change in terms of other parts of the code, in which case it's often much simpler for me to refer them to specific line numbers.

**Comment by pkaminski** [comment]
Great use case, thanks.  I'm now tracking this feature request in #147.
