### ISSUE TITLE
Commit check status summary should have the names of the checks, rather than just the status.

### ISSUE THREAD

**Issue by tomprince** [Reviewable/Reviewable#173]
Right now, I see a bunch of 'build started' or 'build successful' with no context of what build.

**Comment by pkaminski** [comment]
Ah, yeah, that could be annoying.  I think when I was designing the feature most services included the service name in their status message, so I chose not to show it separately.  Could you let me know which check services you're using, and perhaps add a screenshot of what the status looks like in the GitHub PR?  Thanks.

**Comment by tomprince** [comment]
We are using custom ones from buildbot. You can see an example at https://github.com/ClusterHQ/flocker/pull/1972

**Comment by pkaminski** [comment]
Fixed.  Reviewable will now show the name of the source in the dropdown if it's not already included in the description.
