### ISSUE TITLE
Make branch name selectable.

### ISSUE THREAD

**Issue by tomprince** [Reviewable/Reviewable#176]
When reviewing a PR, I often want to checkout the corresponding code. It seems like the branch currently isn't selectable, though.

**Comment by pkaminski** [comment]
Do you  mean the branch name in the Changes section?  I can select both the source and target branch names fine, and copy/paste them.  What's your browser and OS?
![image](https://cloud.githubusercontent.com/assets/1646896/10177456/23a20010-66af-11e5-8917-a1d1f0821227.png)

**Comment by tomprince** [comment]
Firefox 41.0 on OSX. I can't seem to select anything in the Changes section.

**Comment by pkaminski** [comment]
Interesting, seems specific to OS X.  Will fix.

On Tue, Sep 29, 2015 at 1:49 PM, Tom Prince <notifications@github.com>
wrote:

> Firefox 41.0 on OSX. I can't seem to select anything in the Changes
> section.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/176#issuecomment-144187462>
> .
>



-- 
Piotr Kaminski, Founder, reviewable.io

**Comment by pkaminski** [comment]
Should be fixed, please reopen if you still have problems.
