### ISSUE TITLE
Review comment replies don't always get usable line numbers

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#178]
See this post on github, which includes a bunch of comments apparently assigned to line 0 in various files: https://github.com/servo/servo/pull/7807#issuecomment-145678322

**Comment by pkaminski** [comment]
Weird bug, I'll investigate.  Do you see the issue only in the posted comments, or also in Reviewable proper?

**Comment by jdm** [comment]
The comments appeared on the right lines when I visited the review via the big button in the original PR description.

**Comment by pkaminski** [comment]
I tracked it down to a combination of a poor design decision I made a year ago, and a more recent race condition in computing some data.  I'll push a fix tomorrow.  I'll have to see if this affects the "line NN" links in the upper-right corners of discussions too, though.  And I may have to bite the bullet and write a proper data flow framework in JS, those race conditions are killing me...

**Comment by pkaminski** [comment]
Ended up deploying tonight, so this should be fixed now.

**Comment by jdm** [comment]
Thanks!
