### ISSUE TITLE
Allow anyone to mark a comment as acknowledged

### ISSUE THREAD

**Issue by sherriman** [Reviewable/Reviewable#182]
Often as pull request will have many reviewers, or get handed off to someone else.

* As a reviewer I would like to be able to mark a comment as acknowledged, no matter who it is waiting on.  This will let me mark all open items on a review as resolved.
* I would like to be able to make a comment and acknowledge it at the same time.  This allows me to leave a final comment and mark that there is no work remaining.

**Comment by pkaminski** [comment]
Thanks Scott, I'll try to think of a way to cleanly do review handoffs.  For your second question, this got added recently: try clicking on the small circled checkmark icon under a draft message to change its disposition to "FYI only".

**Comment by edmorley** [comment]
I hit this today - the CI checks on the GitHub PR page are still yellow for Reviewable, since I'm not able to mark the comments from a previous reviewer as acknowledged.

**Comment by tricket** [comment]
Chiming in to add my support for some sort of undo or override -- we try to use the FYI setting, but if we forget, a response of, "Thanks, the comment looks good!" can suddenly lock up the review. In our case, this happened when someone was leaving for a few days, which meant we couldn't progress until they returned.  Having the ability for someone else to acknowledge, or to undo / change the state to FYI, would greatly help.

**Comment by trevor-vaughan** [comment]
:+1:

**Comment by ckrough** [comment]
We use the application as a agile team and would even prefer that team members be able to Ack without any sort of administrative override.

**Comment by pkaminski** [comment]
Question for everyone else on this thread: assuming a feature exists that would allow someone to resolve any discussion, overriding all other participants, who should it be accessible to?  Repo admins only, anyone with push permissions, or anyone who can see the review?

**Comment by sherriman** [comment]
For my use case, anyone that who can see the review.

**Comment by The-Compiler** [comment]
I guess for me "anyone with push permissions" would be best, to prevent abuse. I guess that'd be something for a repository setting page? :wink:

**Comment by tricket** [comment]
For us, anyone who can see the review would be best, but if that complicates things, we can adjust our permissions to match something more strict. 

--Tom

**Comment by trevor-vaughan** [comment]
Ideally, for me, it would be a setting specific to Reviewable and outside
of the GitHub permissions altogether.

Alternatively, allowing a selection like "anyone", "write access", etc...
would be great.

Thanks,

Trevor

On Wed, Jan 20, 2016 at 12:47 AM, tricket <notifications@github.com> wrote:

> For us, anyone who can see the review would be best, but if that
> complicates things, we can adjust our permissions to match something more
> strict.
>
> --Tom
>
> Sent from my iPhone
>
> > On Jan 19, 2016, at 5:46 PM, Piotr Kaminski <notifications@github.com>
> wrote:
> >
> > Question for everyone else on this thread: assuming a feature exists
> that would allow someone to resolve any discussion, overriding all other
> participants, who should it be accessible to? Repo admins only, anyone with
> push permissions, or anyone who can see the review?
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/182#issuecomment-173094984>
> .
>



-- 
Trevor Vaughan
Vice President, Onyx Point, Inc
(410) 541-6699

-- This account not approved for unencrypted proprietary information --

**Comment by pkaminski** [comment]
Thanks for the feedback everyone.  Clearly nothing short of full customization will satisfy everyone, but I won't be able to ship that right away.  For this Friday's release I'm going to go with requiring push permissions by default (otherwise reviews in public repos would be trivial to vandalize) and admin permissions when a participant has set their disposition to "blocking" (part of the new feature set).  Let's see how far that gets us first.

**Comment by pcraum** [comment]
:+1:

**Comment by d-weber** [comment]
:+1:

**Comment by grichard** [comment]
:+1:

**Comment by sherriman** [comment]
Sounds good.  I don't have many public repos so I didn't consider that possibility.  Would the following work?
* If the repo is private - Anyone with access
* If the repo is public - Push permissions

**Comment by ckrough** [comment]
I like the push permission idea. That seems to jive well with the concept that github set forth in their collaboration config.

If a user is considered a collaborator with `write` access in github, then they may acknowledge comments on behalf of other reviewers. Otherwise they are a reviewer, but are not permitted to make unilateral decisions.

**Comment by trevor-vaughan** [comment]
The issue that I face is that I have VERY few people with write access but
I want a nice sizeable chunk of reviewers.

This eliminates force push accidents and other fun things.

Trevor

On Thu, Jan 21, 2016 at 10:50 AM, Chris Krough <notifications@github.com>
wrote:

> I like the push permission idea. That seems to jive well with the concept
> that github set forth in their collaboration config.
>
> If a user is considered a collaborator with write access in github, then
> they may acknowledge comments on behalf of other reviewers. Otherwise they
> are a reviewer, but are not permitted to make unilateral decisions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/182#issuecomment-173613434>
> .
>



-- 
Trevor Vaughan
Vice President, Onyx Point, Inc
(410) 541-6699

-- This account not approved for unencrypted proprietary information --

**Comment by edmorley** [comment]
> This eliminates force push accidents and other fun things.

GitHub now supports marking certain branches as 'protected' which prevents force pushes - and you can also insist on a green CI run before it can be merged:
https://github.com/blog/2051-protected-branches-and-required-status-checks

(Though this likely doesn't solve the entire problem depending on your definition of "other fun things" :-))

**Comment by trevor-vaughan** [comment]
That may indeed solve the issue.

On Thu, Jan 21, 2016 at 11:05 AM, Ed Morley <notifications@github.com>
wrote:

> This eliminates force push accidents and other fun things.
>
> GitHub now supports marking certain branches as 'protected' which prevents
> force pushes - and you can also insist on a green CI run before it can be
> merged:
> https://github.com/blog/2051-protected-branches-and-required-status-checks
>
> (Though this likely doesn't solve the entire problem depending on your
> definition of "other fun things" :-))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/182#issuecomment-173618072>
> .
>



-- 
Trevor Vaughan
Vice President, Onyx Point, Inc
(410) 541-6699

-- This account not approved for unencrypted proprietary information --

**Comment by pkaminski** [comment]
You can now dismiss participants from a discussion via a dropdown on their avatar in the new participants rollout.  Please let me know if it solves your problem(s) or if further work is needed.
