### ISSUE TITLE
Get listed on GitHub integrations page

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#183]
ReviewNinja and Code Climate, which exist in a similar space to Reviewable, are already listed there:

https://github.com/integrations

**Comment by pkaminski** [comment]
This is in progress, I started the process minutes after they made the announcement.

**Comment by danvk** [comment]
Cool, glad you're on top of it!

**Comment by pkaminski** [comment]
There were some concerns about data retention in the privacy policy that I just managed to address today, and everything else is ready, so this should be coming soon.

**Comment by pkaminski** [comment]
And it's live!
