### ISSUE TITLE
RFE: Add LGTM button to top-level comments

### ISSUE THREAD

**Issue by bpflanz-adfin** [Reviewable/Reviewable#185]
The mechanism of indicating that the reviewer is done with a review is currently a bit... strange. Just hitting "Acknowledge" on the review doesn't send a strong signal to the author that the PR is mergeable. And sending an "LGTM" comment means that the author has to again respond to which you then ack. Instead, I think there should be an LGTM button (maybe grayed out if there's stuff that this particular reviewer still has to respond to?) which would send an "LGTM" comment that doesn't require a response. I would imagine this could use the same underlying mechanism as the "FYI" comments on the code itself.

**Comment by pkaminski** [comment]
I just retested, and sending an LGTM top-level comment does not make an otherwise completed and mergeable review incomplete.  True, the unreplied counter goes up by one (and turns red), but this doesn't preclude merging as long as everything else is in order.  Please let me know if you have an example where this isn't true.

That said, I agree that more explicit LGTM'ing would be desirable for some teams.  My plan at the moment is to 1) expose review completion as a GitHub "status check", 2) enable teams to customize the review completion condition, then 3) see how this gets used and consider introducing further controls, either standard or customization-only.

**Comment by bpflanz-adfin** [comment]
Agreed, it doesn't prevent merging, but it does leave a red "unreplied" counter, which makes it look like there's still something to do on that review when looking at the dashboard. IMO, the dashboard should allow the user to determine the next action with a glance.

I love your suggestions for your future plans regarding requiring LGTM'ing as a status check, but I feel that this issue (#185) is an easier thing and a bit of a prerequisite anyway.

**Comment by pkaminski** [comment]
Agreed that the dashboard could be clearer in this scenario.  However, I don't think adding an LGTM status is necessarily an easier thing to do:  it requires new UI, extends the model, breaks compatibility with a mixed Reviewable + GitHub flow, and may interact with #159, #182, and the custom completion condition mechanism.  Plus I want to see what people do with the customizations first -- there may be better ideas to steal and standardize there.

**Comment by bpflanz-adfin** [comment]
Fair enough.
Is there any (relatively easy) way to get non-red notifications on LGTM, without the button? That's really the main thing I'm asking for with this ticket.

**Comment by pkaminski** [comment]
Apologies for the delayed reply -- I've been trying to come up with a satisfactory solution and I think I may have something.  Very soon, I'm going to add a review completion status to the PR's status checks (#159), and soon after allow the condition to be customized.  This will lead to more situations where some indicators are red but the review is considered complete.  While so far I've been hiding "success" status check indicators from the dashboard as they were redundant, my idea is to now show them instead.  This way a complete review with all counters zero will still show the merge button, but a complete review with non-zero (possibly red) counters will now be distinguished by a green status checkmark.

I realize this isn't exactly what you were after, but do you think it's close enough for now?  (This doesn't necessarily mean that an explicit LGTM button won't make an appearance in the future.)

**Comment by bpflanz-adfin** [comment]
Thanks for your thoughtful response.
What you're talking about in #159 looks pretty close to what I'm looking for. I'd envision an LGTM button interacting nicely with that, in that it would effectively mark every remaining comment resolved, etc. Having said that, I think it would make most sense to close this RFE, and I'll think about it again once I've spent some time with whatever comes out of #159.

**Comment by pkaminski** [comment]
OK.  The completion condition customization feature is coming next month, so let's close this for now and revisit later.  Thanks!
