### ISSUE TITLE
Can't figure out actual list of commits under review

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#186]
When I'm done reviewing a PR and ready to merge it, I need to know what the actual makeup of commits looks like. If there are commits that don't need to be separate, I will ask the submitter to squash them and force push before I merge. I don't seem to be able to find this information out from Reviewable's interface, since it only deals in revisions.

**Comment by pkaminski** [comment]
The information is mostly there [1]  in the synthetic "New commits in rNN" messages but it's not in a very convenient form for your use case.  At this point it's probably easiest to open the GitHub PR and view the commit list there by clicking on the "N commits" link in the Changes section.  I could probably change that link to show a popup list of current commits instead -- would that work for you?

[1] This is a historical list and doesn't account for rebasing.

**Comment by jdm** [comment]
Which link do you mean by "change that link"?

**Comment by pkaminski** [comment]
![commits](https://cloud.githubusercontent.com/assets/1646896/10555553/acd8a14e-7425-11e5-8668-fc8c39193a92.png)

**Comment by jdm** [comment]
Oh, that would be handy. I didn't notice that was a link, actually.

**Comment by pkaminski** [comment]
I think the virtual Commits file takes care of this need nowadays, as you can diff between "base" and the latest revision to see exactly what commits are (still) part of the PR.
