### ISSUE TITLE
Clicking on white space next to "Draft" in new review comment closes box

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#187]
Sometimes after opening a box to write a new comment in a review, I click the white space next to the "Draft" text. This causes the box to close, which is surprising.

**Comment by pkaminski** [comment]
This is intentional, and was implemented based on other users' requests; one person's feature is another person's unwelcome surprise, I guess.  I think I'm going to leave it as-is for now, though, unless more people complain.
