### ISSUE TITLE
Leading spaces in commit messages are mangled

### ISSUE THREAD

**Issue by stefano-maggiolo** [Reviewable/Reviewable#189]
See for example the commit https://github.com/cms-dev/cms/commit/99d9aa91d5a9544995b0a92acfc289d7c7ed4868 which loses the leading spaces in https://reviewable.io/reviews/cms-dev/cms/487#-

**Comment by pkaminski** [comment]
Looking at the commit diffs on GitHub and on Reviewable side-by-side I don't see any discrepancies -- they look exactly the same to me, including leading spaces, in both one and two column modes.  What am I missing?  Could you please post a screenshot that demonstrates the problem?  Thanks.

**Comment by stefano-maggiolo** [comment]
Mmm, indeed now that I look back at it I see that in reviewable the commit message is repeated twice and I was looking at the one not well-formatted. I am new to the interface so I'm not sure I get why it is repeated twice, or whether it is ok for the second copy not to preserve leading whitespaces.

Attaching screenshot anyway just in case:
<img width="828" alt="screen shot 2015-10-22 at 9 19 28 pm" src="https://cloud.githubusercontent.com/assets/485490/10677197/c03e2452-7902-11e5-973a-06bec9a3da88.png">

**Comment by pkaminski** [comment]
Ah, I see what you mean now.  That's a bug in escaping the plain-ASCII formatting of the commit message into HTML.  Will fix.

**Comment by pkaminski** [comment]
This should now be fixed going forward, but previously captured commits will remain as-is.
