### ISSUE TITLE
Ability to set the billing contact for a subscription

### ISSUE THREAD

**Issue by jwpeddle** [Reviewable/Reviewable#192]
Currently things seem set up to make the person that started the subscription the billing contact. However, at my company at least, the person with the credit card is not involved in the reviewable process. It would be handy to make sure they can receive the email without working something out on my end.

**Comment by pkaminski** [comment]
Also requested by @dbhakta and @cschmit.

**Comment by pkaminski** [comment]
Now also requested by @pjnorton.

**Comment by pkaminski** [comment]
This is now available in the subscription panel, under your card details.  Note that the email address you enter is not validated (or double-opted-in), so check for typos before you confirm!
