### ISSUE TITLE
RFE: Add summary of number of lines added/deleted/changed for all files

### ISSUE THREAD

**Issue by bpflanz-adfin** [Reviewable/Reviewable#193]
It's useful having the number of lines added/deleted/changed on a per-file basis in the files matrix, but it would also be helpful to have the sum of all of those, perhaps right above or right below the files matrix. This would give the reviewer a quick at-a-glance idea of the complexity (and potential duration) of the review.

**Comment by pkaminski** [comment]
Good idea, I added it to the lower-right corner of the changes box (at least provisionally -- didn't like how it looked above/below matrix).  Note that the counts won't be accurate if the review goes into single-file mode, or if diffs get throttled.  In those cases, and also if there are any binary files, etc., an ellipsis will be appended.

**Comment by bpflanz-adfin** [comment]
Looks great; thank you!
