### ISSUE TITLE
RFE: Add keyboard shortcut for going from inside the review up to the dashboard

### ISSUE THREAD

**Issue by bpflanz-adfin** [Reviewable/Reviewable#194]
My preference would be "u" (for "up"), as, in a sense, this matches GMail for going from a message up to the inbox/label/search from which you accessed the message. Of course, as long as the functionality is supported, the actual shortcut doesn't matter as I can always customize it for myself.

**Comment by pkaminski** [comment]
Easy enough.  There's a new binding available now, though you'll have to make a custom config to use it as I don't want to bind it by default:
```
[null, "Return to reviews dashboard", "navigate('/reviews')"]
```
