### ISSUE TITLE
Open GitHub PR in same tab

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#195]
The Reviewable link in the PR description on GitHub opens in the same tab.
The link back to GitHub from Reviewable opens GitHub in a new tab.

It feels like these links should behave in the same way. I'd prefer if they both opened in the current tab. My main use case for going back to GitHub is to click the "Merge" button, so I'm usually done with Reviewable at this point anyway.

**Comment by pkaminski** [comment]
This was brought up in #81 and I made some counter-arguments there, but I think I've come around since.  Accepted, will fix.
