### ISSUE TITLE
Can't reply to a comment on a deleted file

### ISSUE THREAD

**Issue by larsbergstrom** [Reviewable/Reviewable#197]
In the review for https://github.com/servo/servo/pull/8288, there is a comment on a deleted file. I wanted to reply to it, but that comment does not appear anywhere in the reviewable UI (though it shows in the "unreplied counter").

**Comment by pkaminski** [comment]
I assume you're referring to `.gitmodules`?  That file wasn't actually deleted, but rather got turned into an empty file.  You're right, though, there's a bug where comments don't show up on empty files for some reason -- will fix.  As a workaround in the meantime, change the diff bounds so the diff isn't empty and the comment will show up.

**Comment by larsbergstrom** [comment]
Great, thanks for the fast investigation, as always!

**Comment by pkaminski** [comment]
This should be fixed now.  The bug was in mapping line numbers between the base/non-base variants of a revision, when no other revisions were present in the mapping chain.
