### ISSUE TITLE
cannot set default review mode for an org

### ISSUE THREAD

**Issue by rbtcollins** [Reviewable/Reviewable#199]
The default (only show since 'last reviewed' is confusing because last reviewed is a global, not a per-user thing. Most orgs I'm in have each reviewer review the full diff, not just the changes since the last review by anyone. One way to mitigate that would be to allow setting the review for an entire org.

**Comment by pkaminski** [comment]
I think this is essentially the same issue as #200, let's just merge the discussion into that.
