### ISSUE TITLE
Reviewable detects file as binary even though it's not

### ISSUE THREAD

**Issue by dstufft** [Reviewable/Reviewable#207]
Reviewable is detecting a binary file here https://reviewable.io/reviews/pypa/interoperability-peps/56 but that is not a binary file. I'm assuming it's doing so because it has a formfeed character in it but that doesn't seem like it's something that should be triggering the file to be binary.

**Comment by pkaminski** [comment]
I typically consider all invisible control chars as binary to avoid confusing situations where they cause differences between revisions but show no visible deltas.  (I had to make an exception for CR/LF, of course.)  But I changed the design to treat formfeeds like tabs: they're OK for text files, and will display as a red ␌ (unicode form feed symbol) in the diff.  Let me know if this works for you!
