### ISSUE TITLE
Support expanding the diff to the function level and to the file level.

### ISSUE THREAD

**Issue by sasha-s** [Reviewable/Reviewable#208]
Right now I have to click "expand" 10 times when I need to see more context.
Opening a file in a new tab/window could potentially use scrolling to auto-expand.

**Comment by pkaminski** [comment]
Expanding the whole file is already supported via the Collapsed dropdown menu:
![image](https://cloud.githubusercontent.com/assets/1646896/11327209/c24500ce-9133-11e5-9c98-ff0ed40365f9.png)

I agree that function-level expansion would be cool too -- I'll add that to the existing #153 feature request.
