### ISSUE TITLE
Is there a way to choose a dark background theme?

### ISSUE THREAD

**Issue by Thatkookooguy** [Reviewable/Reviewable#209]
I want to try and select a theme like ```monokai``` or ```paraiso.dark``` for highlight.js. Although I can get the text color to change, the default text color remains black, and the default background color remains white.

Is there a way to change that?

thanks!

**Comment by pkaminski** [comment]
Sorry, either this got broken at some point or it never worked...  I'll see if I can fix it.

**Comment by pkaminski** [comment]
OK, it should be fixed now, though the effect isn't entirely satisfactory as the rest of the UI is still dark-on-white.  You might also want to change the background-color for this rule, which is used to fill in "empty" areas of the diff (and should differ from the normal code background), to make things less jarring:
```
.diff.line .line.wrapper, .diff.line .empty.line.wrapper .hljs {
  background-color: #f2f2f2;
}
```

Let me know if you run into any other issues!
