### ISSUE TITLE
Do not generate links that contain underscore followed by colon

### ISSUE THREAD

**Issue by dtolnay** [Reviewable/Reviewable#210]
GitHub mangles them. Compare:

> `_[main.go, line 64 \[r1\]](https://reviewable.io:443/reviews/abc/xyz/709#-K3jfxR9Jy5hq4r_OnKZ:-K33ujfR5hxqN1r_OnX_:-1808041007) ([raw file](https://github.com/abc/xyz/blob/3810f806e70820dc297c1db6e5b916aacef46fb2/main.go#L64)):_`

_[main.go, line 64 \[r1\]](https://reviewable.io:443/reviews/abc/xyz/709#-K3jfxR9Jy5hq4r_OnKZ:-K33ujfR5hxqN1r_OnX_:-1808041007) ([raw file](https://github.com/abc/xyz/blob/3810f806e70820dc297c1db6e5b916aacef46fb2/main.go#L64)):_

> `_[main.go, line 64 \[r1\]](https://reviewable.io:443/reviews/abc/xyz/709#-K3jfxR9Jy5hq4r_OnKZ:-K33ujfR5hxqN1r_OnX_x:-1808041007) ([raw file](https://github.com/abc/xyz/blob/3810f806e70820dc297c1db6e5b916aacef46fb2/main.go#L64)):_`

_[main.go, line 64 \[r1\]](https://reviewable.io:443/reviews/abc/xyz/709#-K3jfxR9Jy5hq4r_OnKZ:-K33ujfR5hxqN1r_OnX_x:-1808041007) ([raw file](https://github.com/abc/xyz/blob/3810f806e70820dc297c1db6e5b916aacef46fb2/main.go#L64)):_

**Comment by pkaminski** [comment]
Oh joy.  I guess correct parsing is tough.  I'll implement a workaround.

**Comment by pkaminski** [comment]
I switched to using stars instead of underscores to indicate italics, which takes care of the issue (until somebody has a filename with a star in it, but oh well).

**Comment by dtolnay** [comment]
Thanks for the quick fix!
