### ISSUE TITLE
Allow fast forward merge

### ISSUE THREAD

**Issue by stefano-maggiolo** [Reviewable/Reviewable#212]
When a PR branch has no merge conflicts, and even more when it includes the tip of the destination branch, it would be nice to be able to do a fast forward merge.

(I don't see any reason to do a non-FF merge in these cases, so using FF as default in this case would be ok for me, but I don't know if other people might want non-FF.)

**Comment by Mikulas** [comment]
We are using merge commits even for ff-able branches to mark deployable points of history. While this clutters history if you mostly merge single commits, for larges PRs it's ok.

That being said, I would also like FF as and option. And also an automatic rebase followed by a non-ff merge. At that point, it kind of leaves the realms of code review tool though.

So please do not remove the current behaviour, make it an option.

**Comment by pkaminski** [comment]
I'm not able to rebase through GitHub's API -- even if there are no conflicts -- so that's a no-go.  I should be able to do FF merges by rewriting the branch ref directly.  This would definitely be an option -- do you think it makes sense to let anybody with push privileges pick it per-merge, or have admins set it per-repo, or something else?  (Keeping in mind that I want to avoid complicated configuration options.)

**Comment by stefano-maggiolo** [comment]
It seems on par with the "keep branch around" settings, but if you start to have more options like that it becomes a mess. For me I wouldn't mind having it as a repo setting (as in "do ff merge whenever possible") with a warning I need to accept before merging a PR that cannot be ff'ed, if I have that option enabled.

[The avantage over per-PR would be just simplicity of configuration, not that I want to preserve the privilege of deciding the merging strategy.]

**Comment by kr** [comment]
My ideal would be "ff-only"—a way to prohibit merge commits entirely (on master) for a given repo.

**Comment by pkaminski** [comment]
Fast forward merges are now available, and you can control whether they're available in your repos via the repository settings panel.

**Comment by pkaminski** [comment]
Given GitHub's surprise launch of Rebase & Merge (which I'll be integrating shortly), is there any reason to keep Fast Forward merge as well?  If nobody speaks up, I'll remove it.
