### ISSUE TITLE
Allow for different sections/findings in the general comment

### ISSUE THREAD

**Issue by stefansiegl** [Reviewable/Reviewable#213]
Hi,

As briefly mentioned on gitter, I would like to discuss the possibility to extend the section of reviewable where general comments on a PR can be put (basically the upper part of a review). 

We use comments on a source level in a way that one initial review item covers exactly one "problem". This is very helpful as multiple problems can arise easily in one file alone. And it helps to separate the discussion of these issues (as sometimes not all of them really needs to be implemented).

In the general section we only have one thread to discuss matters. We usually use this section for "a) everything that does not match one file alone, b) where the reviewer does not really know which file this addresses or c) when there is a need for sth where a realization file does not yet exist".

Just think on the reviewer executing some exploratory tests and some of them fail. He describes the tests in the general section together with issues that span potentially multiple files and other questions/suggestions. All within the one available thread.

To improve clarity and to allow for independent threads of communication what I propose is the option to have multiple general threads of discussion. In the example above the reviewer would then create multiple comments on a top level where the discussions are then focussing only one comment instead of having everything in a big conversion.

I hope I could express my suggestion in a clear way, otherwise please get back to me :)

Cheers,
Stefan

PS: Thanks for the great work!

**Comment by pkaminski** [comment]
Thanks Stefan, that's very clear.  The current workaround is to attach such discussions to an arbitrary line (e.g., the first one) in an arbitrary file but I agree it would be nice to support this workflow directly.  I'll give it some thought, and let's also see if anybody else chimes in here with similar needs.

**Comment by pkaminski** [comment]
Note also that this is related to #118, where the top-level discussion always being considered as resolved is confusing and occasionally leads to issues being "lost".

**Comment by The-Compiler** [comment]
I'd also like to see something like this. Looking at big reviews I had in the past (before I knew about reviewable :wink:), I had to re-read the whole comment thread multiple times to see if there's anything still unresolved. Then I'd definitely have liked something like multiple comment threads where I can mark them as resolved separately.

As an example, see https://github.com/The-Compiler/qutebrowser/pull/962 - there are nearly 70 top level comments, about multiple things that needed attention.

Some examples:

- Can you please add some tests? (if there are no tests at all, i.e. this is not applicable to a given line)
- Your changes broke this and that, but I don't know why, can you please take a look?
- Could you please follow the style guide everywhere?

**Comment by pkaminski** [comment]
Thanks for the +1!  I intend to add this feature shortly after the new discussion semantics are in place, perhaps by end of month or in February.

**Comment by pkaminski** [comment]
This is now live.
