### ISSUE TITLE
Commenting in-line on a diff does not play nicely with some browser extensions

### ISSUE THREAD

**Issue by sigmavirus24** [Reviewable/Reviewable#214]
I use some browser extensions that like to retain control of the keyboard. If I try to create a comment in-line in reviewable, the comment box auto-closes because it couldn't grab the keyboard/input focus immediately.

My options appear to be:

1. Don't use reviewable
2. Disable the extension each time I want to use reviewable and lose the shortcuts/muscle memory I have built up for everything else.

**Comment by pkaminski** [comment]
Browser extensions are the bane of every ambitious web app.  :disappointed:  That said, I already have a few exceptions built into the "delete empty draft on blur" behavior, so perhaps I could add another.  What's the extension you're using, what is it doing to focus, and is there a way to detect it in the DOM?  Thanks.

**Comment by sigmavirus24** [comment]
@pkaminski yeah. Sorry, I meant to ask if there was another way. Perhaps a configuration option that allows users to not have those auto-close?

As for the plugin, I'm using Pentadactyl on Firefox. I have no clue if there's a way to detect it in the DOM to be honest. I'm happy to help if you can give me some pointers.

**Comment by pkaminski** [comment]
So I tried to install Pentadactyl to see what it does, but it appears that the current release is not compatible with Firefox 43 and https://github.com/5digits/dactyl/issues/99 doesn't inspire confidence in the future of the add-on.  Can you take a look at the Inspector and see if there's any unusual classes applied to the top elements (html, body), or to the comment draft textarea?

I'm generally very reluctant to add config options, both to keep the user experience streamlined and to manage the internal complexity of the code.

**Comment by sigmavirus24** [comment]
Ah, I have a clone that I install using the tooling in the repo. It installs fine on Firefox 43 for me that way.

I can't open the comment draft textarea to check that for you unless there's another place to look.

> I'm generally very reluctant to add config options, both to keep the user experience streamlined and to manage the internal complexity of the code.

That's reasonable.

**Comment by pkaminski** [comment]
If you temporarily disable the add-on, you should be able to create a new draft and type in a word or two (but don't send it).  Then when you turn the add-on back on and reload the page, the draft should still be there for you to inspect.  Also, Pentadactyl probably deals with all textareas the same way, so you should be able to check for distinguishing classes / other features on any web page that has a textarea, not just Reviewable.

**Comment by pkaminski** [comment]
As a last-ditch effort I was looking through the add-on's source code for any markers I could access, and may have found something.  Can you check if `window.dactyl` return something non-`undefined` in the JavaScript console?  If so, I can have a fix in minutes.

**Comment by sigmavirus24** [comment]
@pkaminski I'm so sorry for the delay. I've been really busy.

I didn't see anything added to the text field by Pentadactyl and `window.dactyl` is undefined for me.

**Comment by sigmavirus24** [comment]
So here's something interesting, if I open Firefox's console, it cannot see window.dactyl. If I use Pentadactyl's JS REPL, I can see it. I'm going to throw together a quick html page to see if I can see it from there. That'll might be more authoritative than Firefox's console.

**Comment by sigmavirus24** [comment]
So I just threw together

```
<html>
  <body>

    <script>
      console.log(window.dactyl);
    </script>

  </body>
</html>
```

And with the console open, I loaded it but it's showing `undefined`. So that doesn't seem to be something you'll be able to see.

I guess my workflow will have to be to disable it to use reviewable when I need to. I looked for other things in Pentadactyl's source that might give me a hint but I didn't see it setting many (if any) attributes on the window object. Also, perhaps, Firefox is doing a good job of separating the idea of the webpage's window and the browser/chrome object's window.

Sorry for the trouble @pkaminski

**Comment by pkaminski** [comment]
Sorry we couldn't find a way to make this work.  :disappointed:  If development of the plug-in picks up again, perhaps you can request that it inject some kind of marker into the page / global JS context that I'd be able to check for.  Or let me know when the plug-in is updated to be installable on the latest version of Firefox and I'll poke around some more...
