### ISSUE TITLE
Not allowing requests to https://api.github.com

### ISSUE THREAD

**Issue by mhaamann** [Reviewable/Reviewable#217]
It seems that the error is due to me following a public repo. How I can stop doing that in reviewable?
https://www.dropbox.com/s/xkt0rtpglu7klck/Screenshot%202015-12-11%2009.07.32.png?dl=0

Our PR's from our private repos work fine.

**Comment by pkaminski** [comment]
I'm pretty sure you're seeing the error because `tgandrews/atom-jsdoc` was renamed.  It's another symptom of #170.  GitHub is redirecting the API requests, which is not allowed by CORS.  Let me figure out quickly if there's a workaround, otherwise I'll need to raise it with GitHub support...  For now, you can toggle off "Also show pull requests from all repos to which you can push", though obviously that's not ideal.

**Comment by mhaamann** [comment]
I believe i pressed that button. All though it is hard to confirm since it disappears quite fast. Can you disable it for me from your point of view?

**Comment by pkaminski** [comment]
Yes, you successfully turned the option off.  Is the CORS error still happening?

**Comment by mhaamann** [comment]
yes it is. Same error in console:
https://www.dropbox.com/s/gln0tv7z4d20y5b/Screenshot%202015-12-11%2010.07.53.png?dl=0

**Comment by pkaminski** [comment]
I can't figure out where `tgandrews/atom-jsdoc` is coming from on your Reviews page.  I issued all the same calls as the page does (under your account) and it doesn't show up in any of the responses for me.  Any chance you can find the request that includes "tgandrews" in the response by searching in the Network panel?

It also appears that working around the failure is not possible, so my only option is to disable the error message altogether, which would be pretty drastic.  I'm going to engage with GitHub support to see if they can implement a workaround on their end but that'll take time...

**Comment by pkaminski** [comment]
Please hang on; I've found a workaround but it requires invasive changes in the library I use to communicate with GitHub so I need to test it thoroughly.

**Comment by pkaminski** [comment]
OK, I pushed a new version that I believe fixed this bug.  Can you confirm?  Thanks.

**Comment by mhaamann** [comment]
Its working! That was fast. Thanks
