### ISSUE TITLE
Firefox: Can't paste when writing a comment

### ISSUE THREAD

**Issue by gowong** [Reviewable/Reviewable#219]
Pressing ctrl+v and right-clicking and clicking paste both don't work in the comment input box.

**Comment by pkaminski** [comment]
Reproduced, will look into a fix right away.

**Comment by pkaminski** [comment]
Sorry about this -- I didn't adequately test the image uploading feature, which broke pasting in Firefox.  It's now more-or-less fixed, in that you can paste both text and images (!) into comments in Firefox.  The only remaining bug I've found is that undo/redo of the pastes acts strangely (undo selects all the text, redo moves the cursor to the end of the field) but there doesn't appear to be a way around it.  Hopefully Mozilla will fix the bug below at some point...

https://bugzilla.mozilla.org/show_bug.cgi?id=846674
https://github.com/danialfarid/ng-file-upload/issues/1183
