### ISSUE TITLE
Enable php syntax highlighting for .phpt files

### ISSUE THREAD

**Issue by tsusanka** [Reviewable/Reviewable#221]
Files with `.phpt` extension are pretty much PHP files. The extension is used by some (like PHPUnit or Nette Tester) to distinguish between "normal" code files and tests.

Could you enable syntax color higlighting for these?

**Comment by pkaminski** [comment]
Sure, added.  In principle, the language for unrecognized file extensions is supposed to be automatically detected, but in practice this is hit-and-miss, and it looks like while `.phpt` contains PHP code, the overall layout is somewhat different.  Anyway, let me know if the highlighting works reasonably well -- if not, you'll probably need to add a new language definition to https://highlightjs.org.

**Comment by tsusanka** [comment]
It works well, thank you!
