### ISSUE TITLE
Acknowledge comment does not work with keybinding

### ISSUE THREAD

**Issue by gibiansky** [Reviewable/Reviewable#223]
Pressing `y` does nothing, though the help screen says it will acknowledge the current comment.

(`d` works for "Done", so clearly the right comment is selected)

(In case it matters, I checked the chrome console and no errors are reported when I press `y`)

**Comment by pkaminski** [comment]
I can't reproduce this, which will make it hard to debug.  Some things to try:
1.  Do you have a custom keybindings file?  If so, could you upload it here?
2.  Does it not work on all reviews / discussions, or just some?
3.  Can other people reproduce the problem on the same reviews?
4.  Does it happen in all browsers, and with extensions disabled?

Let's see if we can narrow it down.

**Comment by gibiansky** [comment]
1. No custom keybindings file.
2. Starting a Chrome incognito window. Sign in with Github. Press Shift-j to go to next unresolved comment. Press y. Nothing happens. Chrome console has these things in it: 404 for `https://api.github.com/repos/kariusdx/pipeline/labels?per_page=100&_nocache=980745`
3. Starting a firefox incognito window. Repeat the process. Nothing happens. Firefox console has the following in it: `FIREBASE WARNING: set at /reviews/blah/revisions/r3/captureTimestamp failed: permission_denied`

I have only tried this on one review so far. Do not have any open reviews yet other than this one.

**Comment by pkaminski** [comment]
Just to confirm:  the comment you're on has an `Acknowledge` button?  `Shift-j` can bring you to an unresolved comment that you've already acknowledged and is waiting on somebody else, in which case 'y' would (and should) have no effect.

**Comment by gibiansky** [comment]
Uh, maybe I'm confused about the reviewable UI.

There is a the comments all have checkmarks in circles. I assumed clicking on that was the same as acknowledging it. 

I am currently code reviewing my own code -- writing comments and then replying to them. Kind of a strange thing to do I guess. 

What is the circle+checkmark button, then, if not the same thing `y` does...?

**Comment by pkaminski** [comment]
Ah!  The round checkmark button is "resolve" (and doesn't currently have a bindable command).  It's basically a hack to enable self-reviews and disappears as soon as a discussion has multiple "stakeholders".  This is admittedly all a bit confusing right now (especially for unusual workflows, like self-review) and it's the next big thing I want to redesign, likely by the end of the month.  One tip in the meantime: make liberal use of F1 to figure out what's what -- there's a lot of useful help text in there!

**Comment by gibiansky** [comment]
Ok. Perhaps `y` should "resolve" when "acknowledging" doesn't make sense?

If resolving and acknowledging happen in mutually exclusive contexts, I think they should be merged as concepts. They seem identical?

**Comment by pkaminski** [comment]
Unfortunately, the two actions are neither identical nor even mutually exclusive.

**Comment by gibiansky** [comment]
Oh, Damn. Oh well. Maybe just a shortcut for resolve then.
