### ISSUE TITLE
Review Status not Reported to GitHub.

### ISSUE THREAD

**Issue by jGleitz** [Reviewable/Reviewable#224]
We’re having [a PR](https://github.com/Beagle-PSE/Beagle/pull/353) for which Reviewable fails to update its status report on GitHub:

Reviewable evaluates the status correctly:

![reviewable-settings](https://cloud.githubusercontent.com/assets/4305652/12071482/08cfdad2-b0b0-11e5-9e2b-bd9f04703cd7.png)

But fails to report it:

![reviewable-status](https://cloud.githubusercontent.com/assets/4305652/12071483/0abd2016-b0b0-11e5-92fc-033456456f82.png)
![github-status](https://cloud.githubusercontent.com/assets/4305652/12071484/0cead022-b0b0-11e5-8bc9-2424b7ff8d5d.png)

Additionally (don’t know if that’s related), hitting the “Acknowledge” button on Reviewable has no noticeable effect.

Please note that I removed the link to Reviewable from the PR’s description **after** the issue occured (hoping I could get Reviewable to react in any way)

**Comment by jGleitz** [comment]
We disabled the requirement for Reviewable because we really needed that PR. Still, its irretating that Reviewable didn’t send status updates.

**Comment by pkaminski** [comment]
Sorry about that -- there was a bug in processing some newly created PRs that I failed to catch in time.  :cry: It's fixed now; all statuses should be up to date again, and the GitHub event queue will catch up over the next hour to get everything back in sync.

I'm looking into "Acknowledge" functionality now, will update this issue to let you know what I find.

**Comment by pkaminski** [comment]
I found and fixed the bug with acknowledging discussions -- it was indeed closely related.

My sincere apologies for the slow response on this critical bug.  I'll send you instructions in private on how to directly trigger a pager alert in case you run into something this bad again.
