### ISSUE TITLE
Checkboxes/Task Lists Don't Display in Reviewable

### ISSUE THREAD

**Issue by kabirsikand** [Reviewable/Reviewable#227]
Looks like checkmarks like the list below don't show up in the reviewable markdown:
 - [ ] this is an unchecked box
 - [x] another checked box
   - [x] an indented checked box
   - [ ] an indented unchecked box

**Comment by kabirsikand** [comment]
<img width="577" alt="screenshot 2016-01-06 15 54 04" src="https://cloud.githubusercontent.com/assets/1432209/12158310/beb9b4f4-b48d-11e5-8d4e-3ce0ec23821f.png">
<img width="581" alt="screenshot 2016-01-06 15 54 10" src="https://cloud.githubusercontent.com/assets/1432209/12158312/c0e3c968-b48d-11e5-9124-cf43abddaed4.png">
<img width="780" alt="screenshot 2016-01-06 15 55 17" src="https://cloud.githubusercontent.com/assets/1432209/12158335/e9d27b08-b48d-11e5-94a0-f78e5eecc8f2.png">

**Comment by pkaminski** [comment]
Ick, indeed -- the checkboxes were getting stripped out by Angular's HTML sanitizer, because security.  I replaced them with non-interactive icons instead, since toggling a checkbox is equivalent to editing the comment and Reviewable intentionally doesn't support that.  I realize this is likely not ideal for many common uses of checkboxes so please feel free to open another issue, but at the moment I can't really see how to make it work.  :disappointed:

**Comment by kabirsikand** [comment]
Can we get icons instead? Or maybe checkboxes that live in reviewable instead of GH? Why would you not allow checkboxes...I don't think they send update emails to subscribers, so it should be fine to edit in-place (send the edits over immediately), without using Reviewable's batching, right?

**Comment by pkaminski** [comment]
> Can we get icons instead?

I made the change to generate icons for comments written in Reviewable, but forgot to do the same for ones that originate in GitHub.  I'll add that in and deploy it by end of day -- sorry.  Note though that the icons will only appear in new (or newly updated) comments and are not retroactive.

> Or maybe checkboxes that live in reviewable instead of GH?

That could be a nice feature, but please open a new issue so we can debate it and gauge interest properly.

> Why would you not allow checkboxes...I don't think they send update emails to subscribers, so it should be fine to edit in-place (send the edits over immediately), without using Reviewable's batching, right?

GitHub uses an undocumented internal API for toggling the checkboxes without triggering notifications.  Also, there are no IDs that link the HTML checkboxes to the markdown source, so it's not at all obvious how to go about matching a click to the right `[ ]` to toggle.  And finally, Reviewable purpose doesn't allow comment edits (#225) and it's not clear whether toggling checkboxes should count as such or not...

**Comment by kabirsikand** [comment]
Made https://github.com/Reviewable/Reviewable/issues/229

**Comment by pkaminski** [comment]
I deployed the fix so GitHub comments should now get their checkboxes rendered as icons too.  It should be somewhat-retroactive, resyncing comments if you reload the review page.
