### ISSUE TITLE
GitHub API 404 when going to custom review completion page

### ISSUE THREAD

**Issue by The-Compiler** [Reviewable/Reviewable#230]
When trying to set up custom review completion logic, I get a red banner:

>  Error: GitHub error 404 on GET https://api.github.com/orgs/the-compiler/repos: Not Found

That should be `users/the-compiler`, as I'm not an organization.

**Comment by pkaminski** [comment]
Huh, apparently something got confused.  I think it's specific to your account (or at least, doesn't break for all accounts) since it works fine for one of my own personal repos.  I'll look into it and fix tomorrow.

**Comment by pkaminski** [comment]
Looks like it was a spurious case-sensitive comparison, should be fixed now.  Can you verify?  Thanks.

**Comment by The-Compiler** [comment]
Thanks for the quick fix! I don't get the banner anymore, but now I get an infinite loading circle animation (waited several minutes now). I tried in qutebrowser and Chromium. Should I open a separate issue for that?

**Comment by pkaminski** [comment]
That's very odd.  Can you check the Network panel in the browser's developer tools to see if any requests failed or stalled?  I'll also try to reproduce this locally by resetting my state to make sure the first-time initialization works correctly.  We can keep debugging things in this issue.

**Comment by The-Compiler** [comment]
This are the requests I see when clicking the cog wheel:

![reqs](https://cloud.githubusercontent.com/assets/625793/12287704/ee599486-b9ce-11e5-9499-8911d090d025.png)

The first two happen immediately, the third one about 15s later.

**Comment by pkaminski** [comment]
Thanks, that screenshot combined with telemetry data provided a crucial clue.  I think the bug was more unwarranted case-sensitivity to your username, and this time a global search should've gotten them all.  One more try?

**Comment by The-Compiler** [comment]
Works fine now, thanks!
