### ISSUE TITLE
Custom review completion settings are hard to find

### ISSUE THREAD

**Issue by The-Compiler** [Reviewable/Reviewable#231]
I just spent several minutes finding the custom review settings as I wanted to report #230.

Places I looked at:

- Repositories: I'd have expected clicking a repository to get me to some repository settings page, but nothing happens.
- Clicking my avatar -> Gets me to user settings, no "repository settings" link or anything.

Then after more frustration I found out I had to go to some in-progress review, click the health icon, and then click the settings icon there.

**Comment by pkaminski** [comment]
Acknowledged.  A repo settings page is coming in the near-ish future (once there's another setting or two to access), most probably accessed via the repository link you tried.  (Though right now clicking that link should bring you to a repo-specific dashboard page, so if nothing happens then that's another bug.  Please file if reproducible!)

**Comment by The-Compiler** [comment]
Oh, I guess I misremembered this - indeed clicking it brings me to the reviews pending for that repo.

**Comment by pkaminski** [comment]
Clicking on the repository link now brings up a settings panel.
