### ISSUE TITLE
F1 overlay gets annoying after some time

### ISSUE THREAD

**Issue by The-Compiler** [Reviewable/Reviewable#232]
I found the "F1" overlay quite useful when using reviewable the first time, as it wasn't immediately obvious I could use it to get help for whatever I'm looking at.

However, now I know, and seeing that thing pop up every time I rest my mouse over an element after a few milliseconds is quite annoying.

I think it'd make sense to have an user setting to deactivate this, or maybe automatically do so after the user has used "F1" the first time.

**Comment by pkaminski** [comment]
There are two kinds of F1 popup:  the obnoxious one that pops up right next to your mouse cursor, and the discreet one that shows up in the lower-right corner of the screen.  The obnoxious one is supposed to only show up when you haven't used the feature yet or haven't opened its help snippet.  Once you've done either, it should switch to the discreet one forevermore.

Do you have a reproducible case where the obnoxious one keeps popping up?  If so, let me know which one it is, I may have typo'd the flag.  Thanks!

**Comment by The-Compiler** [comment]
Ah, indeed - I thought it might be better to disable it globally once F1 is used on any feature, but I agree it might make more sense to do this per feature.

After pressing F1 in the places where I haven't yet, indeed I get the more discreet one.
