### ISSUE TITLE
Clicking on Publish leads to lost comments?

### ISSUE THREAD

**Issue by bubenkoff** [Reviewable/Reviewable#233]
Clicking on Publish button leads to infinite spinner being shown
and some comments are lost when i refresh the page after a minute or so
 
![add code files - 5 to review - 1 unreplied - reviewable](https://cloud.githubusercontent.com/assets/427136/12261934/97ebfb3e-b924-11e5-8d9b-73646aba5e5e.png)

**Comment by pkaminski** [comment]
I think Firebase (the datastore behind Reviewable) is having availability issues right now.  I got woken up by my pager and I'm investigating.  Losing comment is almost certainly unrelated to hitting Publish -- rather, they were never saved in the first place.  If you see the red "signal warning" in the lower-right corner of the screen, you might want to stop working until it disappears, as it means that some writes haven't completed for >5s.

**Comment by bubenkoff** [comment]
yes there was a signal warning
well, if this is all possible, it looks like a overall signal warning :)
I would expect to see a similar offline mode as in google docs then, where
you explicitly warned that you might loose the content you've entered, if
you refresh the page

On 12 January 2016 at 12:10, Piotr Kaminski <notifications@github.com>
wrote:

> I think Firebase (the datastore behind Reviewable) is having availability
> issues right now. I got woken up by my pager and I'm investigating. Losing
> comment is almost certainly unrelated to hitting Publish -- rather, they
> were never saved in the first place. If you see the red "signal warning" in
> the lower-right corner of the screen, you might want to stop working until
> it disappears, as it means that some writes haven't completed for >5s.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/233#issuecomment-170878360>
> .
>



-- 
Anatoly Bubenkov

**Comment by pkaminski** [comment]
Yeah, the problem is that the datastore isn't actually going offline (which shows a nice overlay, etc.).  This is some new failure mode, I'm seeing it for the first time.  :disappointed:  I'll definitely protect against it better in the future... once I know what it is.

**Comment by pkaminski** [comment]
I haven't yet figured out the root cause (looks like something on the Firebase side) but I added in code so that if a "delayed write" condition persists for more than 10 seconds the app will force itself into offline mode (with an appropriate warning) until all writes clear.  That should at least prevent people from losing more than 10-15 seconds worth of work.

My apologies for the data you lost, I hope it didn't take too long to recreate...

**Comment by bubenkoff** [comment]
thank you very much!
