### ISSUE TITLE
Performance issues with large review requests

### ISSUE THREAD

**Issue by pbalcer** [Reviewable/Reviewable#238]
As requested in #237, new issue for performance problems in general.

During review of https://github.com/pmem/nvml/pull/581 (which is quite large) I found the overall performance and responsiveness of reviewable to be pretty much unusable. I'm afraid I can't seem to pinpoint one culprit - I believe the issue to be systematic. There seem to be no difference between firefox or chrome.

```
cat /proc/cpuinfo | grep "model name" | uniq
model name  : Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
```

```
free -hm
             total       used       free     shared    buffers     cached
Mem:           31G       8,5G        22G       581M       480M       5,6G
-/+ buffers/cache:       2,4G        28G
Swap:           0B         0B         0B
```

```
lsb_release -a
No LSB modules are available.
Distributor ID: elementary OS
Description:    elementary OS Freya
Release:    0.3.2
Codename:   freya
```

For all intents and purposes this is ubuntu 14.04. Updated this morning.

```
firefox --version
Mozilla Firefox 43.0.4
```

```
google-chrome-stable --version
Google Chrome 48.0.2564.82 
```

```
glxinfo | grep "OpenGL renderer"
OpenGL renderer string: Mesa DRI Intel(R) Sandybridge Desktop 
```

**Comment by pkaminski** [comment]
Thanks for the extra info -- there's something strange going on.  The review isn't that big (number of files usually has a bigger impact on performance than size of individual diffs), your machine is more powerful than mine (I'm still on an i7-860 @ 2.8GHz, and with less RAM), and we're both using Chrome, yet the performance is perfectly acceptable over here.  The only difference is that I'm testing on Windows, but I was under the impression that Chrome performance was generally comparable across platforms.

Could you load the review via https://reviewable.io/reviews/pmem/nvml/581?debug=digest and, after a bit of use (scrolling the page, creating a comment) report the three "digest" numbers in the lower-right corner?  For comparison, mine are around 12ms 14ms 632ms.

Also, do you have any butterflies on the page?  If so, try clicking on one and toggle off "Point out new features" in the bottom-left corner of the page, see if that improves matters.

Another thing to try is to turn off animated transitions via a toggle in your account dropdown at the top of the page.

Just trying to gather more data to narrow things down...

**Comment by pbalcer** [comment]
Oki, did some testing as you asked.

Turning off butterfly did help, so did turning off animated transitions.
Although I think that the animated transitions 'helping' was a subjective, because the animation itself wasn't smooth, now it just waits for whatever it needs to do and only then it shows the comment box.

My digest numbers are:
chrome
 - idle: 14ms 15ms 27ms
 - scrolling: 14 27 115ms
- new comment click - 12ms 16ms 525ms (sometimes >1000ms)

firefox
 - idle: 19ms 27ms 98ms
 - scrolliing: 17ms 20ms 98ms (it's way smoother here)
 - new comment click: 16ms 29ms 329ms (also peaks much higher)

My suggestion: Implement digest numbers charts that can correlate actions with numbers.

The perceived feeling of unresponsiveness generally in applications/games usually does not come from the 'average' performance, rather how much it 'stutters'. Imagine a game that works at 60fps but once in a while it takes 100x the time to render a frame. The experience would be intolerable.

I tried to profile it with chrome dev tools, I found that function 'c' took 45% of the time (I left it running for a minute while I played around). I realize the js is uglified so this might not help much ;)

But damn, the depth of those function call stacks ;) These js script apps are far more complicated than the kernel itself.

**Comment by juliensnz** [comment]
Hello,

I get also an issue with a large PR: https://github.com/akeneo/pim-community-dev/pull/3933

Chrome crashes after 20 seconds of freeze. I could be very nice to be able to paginate reviews to avoid this kind of issues.

Thanks a lot for your work !

**Comment by pkaminski** [comment]
Thanks for the extra details @pbalcer, and sorry for the very delayed reply -- I've been incredibly busy with other bugs.  It sounds like you're getting an "adequate" experience but you're after a perfectly smooth one, and while I'd love that too I'm not actually sure it's possible with today's browsers.  And if it is, almost certainly not with Angular.  Perhaps when I replatform the frontend in the nebulous future...

@juliensnz, your PR has 2605 files (after accounting for renames) and 1295 commits!  The review loads for me in ~4 minutes and takes a few more to compute file rename matches (one time only), which I actually think is not unreasonable for a monster of that size.  I'll take a look at the profile because extreme examples like this can reveal issues that will benefit more reasonable ones too, but I don't consider anything over a few hundred files to be practically reviewable and don't intend to optimize for that use case.

**Comment by pbalcer** [comment]
My experience with reviewable has significantly improved since I've created this issue, and I no longer have any issues with performance. Thanks for your hard work, I really appreciate it!
