### ISSUE TITLE
Cannot publish at all

### ISSUE THREAD

**Issue by jGleitz** [Reviewable/Reviewable#239]
Both my girlfriend and me get this error as soon as we try to publish anything:

![f-is-undefined](https://cloud.githubusercontent.com/assets/4305652/12531783/7e00343a-c1fb-11e5-9361-e794b31a3d83.png)

The error message covers the header bar containing the “publish” button.

Completely clearing my browser’s local data did not help.

**Comment by pkaminski** [comment]
On it.

**Comment by jGleitz** [comment]
Update: I was able to publish a comment on Beagle-PSE/Beagle#607, but not on Beagle-PSE/Beagle#633. I’m able to publish a file’s changed review state on both PRs.

Mabe this helps to narrow it down, as the issue only seems to occur for me for comments on relatively new PRs.

**Comment by pkaminski** [comment]
I believe the bug had to do with brand-new discussions initiated by PR author.  In any case, a fix is deploying now, will ping when it's ready to test.

**Comment by pkaminski** [comment]
Deployed, can you give it another try please?

**Comment by jGleitz** [comment]
> Deployed, can you give it another try please?

I did, and everything works fine as far as I can see.

Thanks for fixing this of fast!
