### ISSUE TITLE
No access to Reviewable at all: “out of quota”

### ISSUE THREAD

**Issue by jGleitz** [Reviewable/Reviewable#240]
I face a new issue in the moment:

![out-of-quota](https://cloud.githubusercontent.com/assets/4305652/12531873/2ae6ec02-c206-11e5-9f9e-9b96f57c42fc.png)

I have neither added an application to GitHub in the last week, nor have I used GitHub particularly much today (In fact I barely touched it at all). My girlfriend informed me that she is facing the same issue.

**Comment by jGleitz** [comment]
The message is gone and I can use Reviewable again. #239 persists, though. I’ll report back if this issue occurs again.

**Comment by pkaminski** [comment]
This was likely a burst quota issue.  If it's not persistent then I'll write it off as likely caused by unusually high activity (reloading a page to try to work around a bug?).  I'll close the issue but please follow up if it recurs.

**Comment by jGleitz** [comment]
Unfortunately, this is back.

I have used Reviewable far more before, so it seems to me like Reviewable must issue a lot more requests to GitHub now, as I never ran out of quota before.

**Comment by pkaminski** [comment]
The update made no changes to code that makes GitHub requests, so I'm pretty sure the timing is coincidental.  I checked and your account's long-term quota is fine so it likely is a burst quota issue.  Could you keep the Network debugging panel open and, next time you see the error, check which GitHub requests failed, with what codes and what responses?  A screenshot could be useful, but be careful not to accidentally post your access token.

**Comment by jGleitz** [comment]
> so it likely is a burst quota issue

sounds right, because I already can access Reviewable again. I will post information about the requests next time I see this error.

I however had a look into my network panel and noticed that )eviewable issues a *lot* of requests to GitHub. Loading Beagle-PSE/Beagle#602 gave me these requests:

![requests](https://cloud.githubusercontent.com/assets/4305652/12532276/57bf9242-c210-11e5-8b21-6268e184f93c.png)

There are some more requests not in view, I counted **34** requests to `api.github.com`. I did nothing but loading the review.

**Comment by jGleitz** [comment]
Note that this many requests seems to be specific for this PR, loading others leads to significantly less requests.

**Comment by pkaminski** [comment]
Well, there's one request per version of each file in the PR.  This is
usually OK, since past 25 files Reviewable goes into single-file mode so it
won't try to fetch them all at once.  But let me know what you find out.


On Sat, Jan 23, 2016 at 11:50 AM, Joshua Gleitze <notifications@github.com>
wrote:

> Note that this many requests seems to be specific for this PR, loading
> others leads to significantly less requests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/240#issuecomment-174215794>
> .
>



-- 
Piotr Kaminski, Founder, reviewable.io

**Comment by pkaminski** [comment]
Has this recurred in the last two weeks?

**Comment by jGleitz** [comment]
No.
