### ISSUE TITLE
404 for branch containing “#”

### ISSUE THREAD

**Issue by jGleitz** [Reviewable/Reviewable#241]
I noticed this 404 when analysing Reviewable’s requests:

![404](https://cloud.githubusercontent.com/assets/4305652/12532337/e9aaba82-c211-11e5-9bcc-d5114a42273c.png)

It reproducibly happens for Beagle-PSE/Beagle#602 and Beagle-PSE/Beagle#613 , but not for others, so I’m assuming that the `#` in the branches’ name is the issue. 

The failed request doesn’t seem to affect Reviewable’s functionality anyhow, so this is only to inform you about this edge case (using `#` in something that generates URLs is a bad idea in the first place, but git and GitHub allows us to do so).

**Comment by pkaminski** [comment]
Looks like I forgot to escape something in https://github.com/pkaminski/hubkit, will fix.

**Comment by pkaminski** [comment]
Fixed, I believe.
