### ISSUE TITLE
Comment Is Closed When Pasting Content

### ISSUE THREAD

**Issue by jGleitz** [Reviewable/Reviewable#242]
If I open a comment and paste content to it (I do that quite often), Reviewable reproducibly pastes that content and closes the comment directly afterwards.

This only happens if my cursor is not hovering the comment, if I hover, this bug doesn’t occur.

The behaviour can be seen in this video: http://owncloud.joshuagleitze.de/index.php/s/GZ71wBcebEvlaY5

**Comment by pkaminski** [comment]
This is really fixed now.

**Comment by jGleitz** [comment]
This reappeared for me.

**Comment by pkaminski** [comment]
Fixed again.  The pasting library I use is a moving target, so I rolled back its version and locked it down for now so I can update and check it manually.  FYI, this is the issue that broke things:  https://github.com/layerssss/paste.js/issues/24
