### ISSUE TITLE
Autocomplete for PR openers and other commenting on a PR

### ISSUE THREAD

**Issue by justin808** [Reviewable/Reviewable#245]
There's no autocomplete for the github id of the PR submitter (or other commenters) for comments. That would be helpful!!!!

> The @-mention autocomplete currently pulls from repo contributors / team members, but yeah, I should add other people involved in the PR like GitHub does.

**Comment by pkaminski** [comment]
Done.  Autocomplete will now include PR author, PR assignee, any commenters, and anybody previous @-mentioned.
