### ISSUE TITLE
Milestones missing from Reviews screen

### ISSUE THREAD

**Issue by jamiejhill** [Reviewable/Reviewable#247]
Please include the Milestones from GitHub alongside each PR in the Review screen. It should also be possible to filter on milestones.

**Comment by pkaminski** [comment]
I added full support file milestones: on the dashboard and on the review page, including setting/clearing with +/- (just like labels).  Note that the milestone for existing reviews will be filled in lazily, so some milestones may be missing from the dashboard until something has caused the review to sync (e.g., visiting it, or any number of automatic background events).
