### ISSUE TITLE
“One unreviewed file” even though everything is reviewed

### ISSUE THREAD

**Issue by jGleitz** [Reviewable/Reviewable#249]
I sometimes get the icon for “one unreviewed file” in the overview, although everything is reviewed:

![unreviewed](https://cloud.githubusercontent.com/assets/4305652/12830862/b627b1d6-cb91-11e5-982c-c8a71c260833.png)

If I open the review, everything is counted correctly:

![header](https://cloud.githubusercontent.com/assets/4305652/12830877/d11fa098-cb91-11e5-8911-385ec0bdc42e.png)

This happens from time to time, but I haven’t recognised a pattern for this behaviour yet. If it occurs, I never find a way to remove that red icon from the overview.

In the moment, I’m having this issue for Beagle-PSE/Beagle#652.

**Comment by pkaminski** [comment]
This can happen when there are renamed files in the review, but would usually show "1+" on the dashboard in that case.  Are there renamed files in this review, or other reviews where you've observed this bug?

**Comment by pkaminski** [comment]
Actually I'm pretty sure this is due to the rename.  I'll see if I can fix it.

**Comment by pkaminski** [comment]
This should be fixed going forward.  To manually fix currently broken reviews, you can toggle the review mark off/on for all renamed files in the review.
