### ISSUE TITLE
Disposition Selector Hidden

### ISSUE THREAD

**Issue by jGleitz** [Reviewable/Reviewable#250]
If a new discussion was started on a Review, the disposition selector of the discussion above is hidden by it:

![hidden select](https://cloud.githubusercontent.com/assets/4305652/12871666/6322842a-cd85-11e5-893e-1ad4754e670e.png)

After reloading the page, the selector is not hidden any more, but the disposition icons of the discussion below are over the selector:

![overlay-issue](https://cloud.githubusercontent.com/assets/4305652/12871673/a371298c-cd85-11e5-9135-f73884ff6d38.png)

**Comment by pkaminski** [comment]
Thanks for the report -- I thought I had this handled, but apparently not quite.  This is what trying to get the `z-index` right feels like:
![4800-puzzle-never-goes-flat](https://cloud.githubusercontent.com/assets/1646896/12877804/67ae6340-ce54-11e5-96f8-3cf11e842b65.gif)

**Comment by pkaminski** [comment]
This should be fixed now, but I wasn't able to reproduce the first condition you showed so I may have missed something.  Can you check again please?  Thanks.

**Comment by jGleitz** [comment]
As far as I can see, this is fully fixed.

**Comment by lukeasrodgers** [comment]
Not sure if this is related, or even a bug or just a feature -- but I can't figure out how to adjust my disposition after having left a review comment:

![screen shot 2016-02-18 at 5 55 29 pm](https://cloud.githubusercontent.com/assets/816444/13160980/eb0f5458-d668-11e5-9e37-f9b5e86d7c8e.png)

I would like to be able to request that a teammate review my new commit. Is this only possible if someone else has entered the discussion/review already?

**Comment by pkaminski** [comment]
Hey @lukeasrodgers, that's a feature.  :smile:  The top-level review discussion is special and always treated as resolved, hence nobody can set their disposition on it.  However, any comments you post will show up as unreplied for others, so a simple "PTAL" should be enough to attract your reviewer's attention.  If you do want to track the resolution of a top-level (not file-specific) issue, you can click the "Start a new discussion" button below and set your disposition on it as normal.

Currently the "who does this discussion look unreplied to" list is not surfaced, which I suppose contributes to the confusion, but I thought that would be too much information to show...

**Comment by lukeasrodgers** [comment]
Gotcha thanks @pkaminski
