### ISSUE TITLE
Mark all files as un-reviewed, or undo mark all as reviewed

### ISSUE THREAD

**Issue by puremourning** [Reviewable/Reviewable#252]
There is a shortcut - shift-X by default - which allows you to mark all files in the current diff as reviewed. This is super useful. However, it would be very handy to have the inverse, or an undo, as an accidental shift-X on a large review can cause some pain :).

So the use-case is a user accidentally marks all files as reviewed. She wants to get back to the previous state.

**Comment by pkaminski** [comment]
A small undo link now appears under the button after clicking it (or using the equivalent keyboard shortcut).  It disappears again once the state has changed, e.g. review marks or diff bounds.

**Comment by puremourning** [comment]
Thanks!
