### ISSUE TITLE
Dropping characters on Rendering

### ISSUE THREAD

**Issue by cicorias** [Reviewable/Reviewable#254]
I'm using Chrome v48.0.2564 and seeing dropping of letters in the rendering, but the tooltip shows the "oringinal" text OK:

Below, it's "notification" and "localDevice"..   see [https://reviewable.io/reviews/thaliproject/Thali_CordovaPlugin/551#-](https://reviewable.io/reviews/thaliproject/Thali_CordovaPlugin/551#-)

![image](https://cloud.githubusercontent.com/assets/1080406/13183836/a9bf2804-d706-11e5-8768-30ff92711425.png)

**Comment by pkaminski** [comment]
I can't reproduce this issue in Chrome v48.0.2564 on Windows 10:
![image](https://cloud.githubusercontent.com/assets/1646896/13194198/47ee2d64-d73d-11e5-8ecb-75f240df515a.png)

But then again, I don't see the diff you've snapshotted above in that PR at all.  It actually looks like a mashup of two different files, and the string on the bottom line of the snapshot isn't even well formed.

Are you able to reproduce this consistently?  What's your platform and have you applied any customizations to Reviewable (e.g., font, stylesheet, etc.)?  Did you visit any reviews prior to this one that may have had the string "of the session" or "Bay VERSION" in them?  Thanks.

**Comment by pkaminski** [comment]
Oh, and also what tooltip are you referring to?  The only "tooltip" Reviewable shows for most elements is a prompt to hit F1/h to view the help snippet.

**Comment by cicorias** [comment]
Chrome upgraded to 49 and it doesn't reproduce. If it happens again I'll grab more.

It was the tooltip that showed the original text

**Comment by pkaminski** [comment]
OK, thanks.  But I swear there's no such tooltip built into Reviewable, so if you saw it then perhaps a browser extension hijacked the page?
