### ISSUE TITLE
Disable "F1 / ?" Tooltip

### ISSUE THREAD

**Issue by Bekt** [Reviewable/Reviewable#255]
Currently, the "F1 / ?" tooltip follows the mouse all the time and becomes a distraction. 

Having a toggle to disable this would be nice.

<img width="269" alt="screen shot 2016-02-23 at 10 29 25 am" src="https://cloud.githubusercontent.com/assets/1221480/13258350/72a88b0c-da18-11e5-90eb-84ea8c57b9c1.png">

<img width="248" alt="screen shot 2016-02-23 at 10 29 32 am" src="https://cloud.githubusercontent.com/assets/1221480/13258351/72a90622-da18-11e5-8b41-3c80e027a87e.png">

<img width="229" alt="screen shot 2016-02-23 at 10 29 40 am" src="https://cloud.githubusercontent.com/assets/1221480/13258353/72a9bb30-da18-11e5-95a6-fbea52d5c28e.png">

<img width="247" alt="screen shot 2016-02-23 at 10 27 58 am" src="https://cloud.githubusercontent.com/assets/1221480/13258352/72a9a00a-da18-11e5-8a5e-24e3ba573bd4.png">

**Comment by pkaminski** [comment]
Hey @Bekt, the tooltip goes away* automatically once you've used a control (or hit F1 / the tooltip to view the help popup), so they should disappear on their own as you use the app.  You can also disable them (for two weeks) by opening the help screen (F1 or h) and turning off the toggle in the lower-left corner:
![image](https://cloud.githubusercontent.com/assets/1646896/13267657/513c94c0-da33-11e5-8cf7-e5fa101d3779.png)
Does that help?

* It actually relocates to a subtle indicator in the lower-right corner.

**Comment by Bekt** [comment]
Ahh true, thanks.
