### ISSUE TITLE
How do I Mark the Changelog as Read?

### ISSUE THREAD

**Issue by jGleitz** [Reviewable/Reviewable#257]
I like the new Changelog feature, giving me an option to stay up to date with Reviewable’s features.

However, I expected the red bubble to go away once I read the Changelog, but this wasn’t the case. I didn’t find a button to mark the Changelog as read, either.

Now having a red bubble for something not interesting for me is a little annoying. How can I make it go away?

On a side note: The first time the user sees the read bubble, they will click on the “Support” button. If the entry “Changelog” had a read bubble too, they’d immediately know what the read bubble on the “Support” button is refering to.

**Comment by pkaminski** [comment]
Meta answer: good points/ideas, but I'm limited in what I can do because I'm using a third-party service (https://headwayapp.co).

I hacked in an animation so that the badge goes down to the Changelog entry when opening the support menu.

Currently, the only way to mark changes as read is to click on each one to read it.  I agree they should be marked as read when opening (closing?) the dropdown, and probably also when following the Changelog link in the support menu.  I'll ask them to add an API that would let me do that.

**Comment by jGleitz** [comment]
I just discovered the “What’s new” overlay, in which I can click on changelog items and they will be marked as read. This is absolutely sufficient.

However, I didn’t discover this overlay until now. I always clicked on the link that brought me to changelog.reviewable.io and on that site, there is no way to mark entries as read.

So for me, it seems that the two real issues are:

 1. It’s very unclear to me how I can trigger the changelog overlay. I only managed to do that by accident and can’t reproduce it (is it even possible if everything is marked as read?)
 2. There should either be a way to mark entries as read on changelog.reviewable.io, or the user should not be brought there from the Support menu at all (and always be shown the overlay, which would also solve 1.).

**Comment by pkaminski** [comment]
You get the overlay by clicking directly on the red badge.  There's no way to access it once the badge disappears.  (But if you want to experiment you can delete the headwayapp.co cookie to reset things.)

The changelog.reviewable.io site is there so people can review the full changelog, whereas the overlay will just show the most recent 4 changes.  I could make the Changelog menu item just show the overlay but then there'd be no way to get to the full log...  I'm not happy with how this works right now either but I can't change anything inside the overlay (it's a secure iframe from the service provider).  Any other ideas?

**Comment by jGleitz** [comment]
I see…

> Any other ideas?

Not really. This bug was mainly to inform you that I was confused, which not necessarily means that you did something wrong. But apart from wrapping changelog.reviewable.io into an iframe to provide a “mark as read” button, I don’t have much ideas.

Well, maybe you could just mark everything as read if the user clicks on the link to changelog.reviewable.io.

**Comment by pkaminski** [comment]
So, it took some nasty hacking and the layout still isn't perfect, but I think things are a bit better now.  Give it a try?

**Comment by jGleitz** [comment]
I think this solution is actually pretty cool. The changelog overlay still doesn’t quite fit into the rest of the page’s layout, but given that you can’t change that, the functionality is pretty neat.

**Comment by jGleitz** [comment]
As the user now gets the overlay, there is a clear way to mark changelog entries as read. I think it’s sufficient.
