### ISSUE TITLE
Does reviewable change the assignee?

### ISSUE THREAD

**Issue by larsbergstrom** [Reviewable/Reviewable#258]
Hi!

Sorry if I'm pointing the finger incorrectly here, but we're having a problem where one of the (unfortunately many) services that run with my account is unassigning reviews. See, for example, the following:
https://github.com/servo/servo/pull/9940#event-583378779

I don't suppose this is reviewable, is it? It could also be travis or appveyor...

**Comment by jdm** [comment]
My suspicion is that when reviewable modifies the PR comment to include the button link, it ends up overwriting an assignee that was modified since the PR was opened.

**Comment by pkaminski** [comment]
Your accusation is likely correct -- sorry.  I recently deployed some server-side changes in preparation for a new feature, but they were supposed to stay dormant until everything else was ready.  Looks like that failed.  I turned off the new logic for now to stop the bleeding and will test (even more) thoroughly before turning it on again.  :(

@jdm The assignee override is separate from the badge insertion but runs at at the same time, so your suspicion is well placed.  Do you have another service that modifies the assignee?  A race condition is certainly one thing I didn't test for...

**Comment by larsbergstrom** [comment]
@pkaminski Thanks for turning it off so quickly!

And, indeed, @jdm has a service that we use (https://github.com/servo/highfive/) that auto-assigns PRs to reviewers, identifies code that might need special review, etc.

**Comment by pkaminski** [comment]
I made some fixes to reduce the window of opportunity for racing and deployed the new logic again.  Races are technically still possible but shouldn't occur in practice.  Please let me know if you see otherwise, though!

**Comment by larsbergstrom** [comment]
Great - thanks much! We'll keep an eye on it.
