### ISSUE TITLE
Code coverage integration

### ISSUE THREAD

**Issue by jonathanj** [Reviewable/Reviewable#260]
Code coverage is an important part of writing code and reviewing it, knowing where your tests have failed to check behaviour is very valuable. Running and checking coverage yourself is a bit of a pain and so it is common to find developers (and reviewers) being lazy about generating the coverage and comparing it to coverage on the master branch.

There are a multitude of code coverage services but currently [codecov.io](https://codecov.io/) seems to be paying special attention to the integration aspect of code coverage, they have a [Chrome extension](https://chrome.google.com/webstore/detail/codecov-extension/keefkhehidemnokodkdkejapdgfjmijf) that overlays coverage on Github diff and file views.

Codecov support in Reviewable would be a very valuable tool for reviewers, seeing at a glance that some line of code is not covered by the tests can alone improve the quality of a review. [Codecov's API](https://codecov.io/api) seems fairly straightforward and informative.

**Comment by pkaminski** [comment]
Good news after 5 years:  Reviewable will now show coverage in the diffs!  We currently only support the Codecov report format and you'll need to configure the connection manually in your repository's settings.  (See [the docs](https://docs.reviewable.io/repositories.html#code-coverage) for more details.)

Please give this a try and let me know how it's working for you before I announce it more widely.  😄
