### ISSUE TITLE
Alt text of review button doesn't make sense in context

### ISSUE THREAD

**Issue by dtolnay** [Reviewable/Reviewable#262]
The current button as added to PRs is:

> This change is \<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>

Which means the alt text looks like:

> This change is Review on Reviewable

It would make more sense as just:

> This change is Reviewable

**Comment by pkaminski** [comment]
Oops, I missed that when tweaking the button.  Will be fixed on the next push, likely tonight.  (Though not retroactive.)
