### ISSUE TITLE
Mark as reviewed button position

### ISSUE THREAD

**Issue by plebioda** [Reviewable/Reviewable#264]
I think it would be much better to have the 'mark as reviewed' button at the end of the diff. If the diff is long enough you need to scroll up after reading it in order to mark the file as reviewed.

**Comment by pkaminski** [comment]
Do you mean the per-file mark as reviewed button?  
![image](https://cloud.githubusercontent.com/assets/1646896/13890350/30a0a6e2-ed08-11e5-8b8b-1f4d8d638565.png)
If so, I do plan to stick a copy on the end of the diff too, but in the meantime the file header should be getting stickied in the toolbar when it scrolls out of view, along with the button.
![image](https://cloud.githubusercontent.com/assets/1646896/13890336/1cf2880e-ed08-11e5-9b03-963eb6d80d46.png)
Does that work for you?

**Comment by plebioda** [comment]
Yes this is what I meant.

Ok that looks fine. I didn't notice this button before. Thanks !

**Comment by tomato42** [comment]
> If so, I do plan to stick a copy on the end of the diff too, but in the meantime the file header should be getting stickied in the toolbar when it scrolls out of view, along with the button.

suggestion to do something even simpler, at least for now: add info to the help message of that other button that says something along the lines of "oh, and if that button scrolls past the top end of screen, you can also find it in the top left corner of the status bar"

**Comment by pkaminski** [comment]
It took a while, but there's now a "mark reviewed and go to next file" button at the bottom of every file you're supposed to review.
