### ISSUE TITLE
I can't be mentioned

### ISSUE THREAD

**Issue by Artur-** [Reviewable/Reviewable#266]
If you try to mention me using @Artur- in Reviewable, the face of some other guy will turn up - the one with the GitHub account "Artur" without the ending dash

**Comment by pkaminski** [comment]
According to GitHub, that username is invalid!
> Login may only contain alphanumeric characters or single hyphens, and cannot begin or end with a hyphen

Did your username get grandfathered in or you found a way to bypass the validation?

**Comment by Artur-** [comment]
It was apparently registered before GitHub came up with that restriction.

**Comment by pkaminski** [comment]
Let me check with GitHub support as to what the historical restrictions were, so I can adjust my regex accordingly.  Grumble, never trust a spec...

**Comment by pkaminski** [comment]
GitHub support came through with historical info and I updated the regex.  You should now be mentionable.
