### ISSUE TITLE
Explicitly prompt new users to authorize access to their organizations

### ISSUE THREAD

**Issue by erikwright** [Reviewable/Reviewable#270]
Onboarding should prompt you to auth your organization if you are a member of a subscribed organization.

Right now, this is all that a user sees after giving basic auth to Reviewable:

![image](https://cloud.githubusercontent.com/assets/187063/14080840/726301a4-f4d5-11e5-8851-822a4c884ba1.png)

It's really not obvious what to do next. It turns out that I need to click at least one of those green buttons, but I was legitimately not sure which one.

Reviewable should sync the usernames associated with each organization. When I do the initial auth, it should show me the icons of my organizations with a "authorize Reviewable to access my PRs in these organizations" or similar prompt.

**Comment by pkaminski** [comment]
Welcome overlay added.
