### ISSUE TITLE
Allow hiding of stalled issues

### ISSUE THREAD

**Issue by erikwright** [Reviewable/Reviewable#271]
Once you've clicked "Include 11 stalled reviews" there is no way to hide them again. This is really annoying when you are first exploring the tool and not even quite sure what that button is going to do.

Even the back button doesn't work, there doesn't appear to be a history entry for the page state prior to showing the stalled reviews.

**Comment by pkaminski** [comment]
The idea was that you'd just go back to click on Reviews in the top navbar, but I agree that's not ideal and there's no good reason to hide the button after it's clicked.  I changed it into a toggle button instead.
