### ISSUE TITLE
Navigating to Reviewable.io should not give a marketing landing page for logged-in users.

### ISSUE THREAD

**Issue by erikwright** [Reviewable/Reviewable#272]
Github doesn't try to re-sell me on every visit. Nor should Reviewable.

![image](https://cloud.githubusercontent.com/assets/187063/14081208/8bf167ee-f4d7-11e5-9731-0f5eb8b0b054.png)

![image](https://cloud.githubusercontent.com/assets/187063/14081219/9eb01b78-f4d7-11e5-8eae-1099e3aa7700.png)

![image](https://cloud.githubusercontent.com/assets/187063/14081239/b9959616-f4d7-11e5-919a-06cf14890f9d.png)

**Comment by pkaminski** [comment]
This is a regression, will fix.

**Comment by pkaminski** [comment]
Fixed.
