### ISSUE TITLE
Emailed comments are not formatted properly.

### ISSUE THREAD

**Issue by erikwright** [Reviewable/Reviewable#273]
Markdown comments from Github are not formatted properly. Email headers / quoted bits are not elided.

![image](https://cloud.githubusercontent.com/assets/187063/14081286/f8876106-f4d7-11e5-9da8-c2817a29d1ad.png)

![image](https://cloud.githubusercontent.com/assets/187063/14081293/08d2a548-f4d8-11e5-84d9-ee3d327362e1.png)

**Comment by pkaminski** [comment]
Just to confirm, this is specific to emailed comments, right?  Or are you seeing it for comments entered via the GitHub UI as well?

**Comment by erikwright** [comment]
I have seen other comments that seemed correctly formatted, so I'm guessing
that it's specific to emailed comments.

**Comment by pkaminski** [comment]
I'll take a look at this together with #63 within the next couple weeks.

**Comment by pkaminski** [comment]
Formatting of emailed comments should now be much improved.  GitHub does its level best to screw up the formatting, though, and I have a forest of regexes to make it look reasonable again, so it's likely there'll be a bunch of corner cases to fix.  Please open new bugs as you find them!
