### ISSUE TITLE
API limit exceeded by toggling "Also show pull requests you're not involved with"

### ISSUE THREAD

**Issue by erikwright** [Reviewable/Reviewable#274]
I turned this on, and didn't see any new PRs in the list.

Then I turned it off, and saw:

```
Failed to update your list of open reviews: Error: GitHub error 403 on GET https://api.github.com/search/issues: API rate limit exceeded for erikwright.. Try again.
```

**Comment by pkaminski** [comment]
Unable to reproduce.  Did the button say how many stalled reviews you have?  They should show up in the list immediately, then load details in the next few seconds.

Hitting the button (in either state) doesn't do a `/search/issues` fetch on GitHub -- it's just an internal filter.  Getting the 403 above at that moment was probably just a coincidence.  (Some of the other toggles on that page, or reloading it often, can quickly use up GitHub's 30 searches/minute quota, though.)

**Comment by erikwright** [comment]
I reproduced it easily.

I navigated to http://reviewable.io. The dashboard displayed immediately,
and I did nothing except toggle this option.

The number of stalled reviews didn't change. There was about a 10-15 second
delay where nothing happened. And then the error popped up.

**Comment by erikwright** [comment]
I used the dev tools to see what is happening.

https://api.github.com/user/teams?access_token=1b97dca1f1aeb9b722e78c967e38e56f841bec8e&per_page=100&_nocache=579432
https://api.github.com/user/repos?access_token=1b97dca1f1aeb9b722e78c967e38e56f841bec8e&per_page=100&_nocache=243769
https://api.github.com/search/issues?access_token=1b97dca1f1aeb9b722e78c967e38e56f841bec8e&per_page=100&_nocache=584236&sort=created&order=asc&q=type%3Apr%20involves%3Aerikwright%20state%3Aopen
https://api.github.com/search/issues?access_token=1b97dca1f1aeb9b722e78c967e38e56f841bec8e&per_page=100&_nocache=898189&sort=created&order=asc&q=state%3Aclosed%20type%3Apr%20involves%3Aerikwright%20closed%3A%3E2016-03-27T10%3A12%3A36-0400
https://api.github.com/user/teams?access_token=1b97dca1f1aeb9b722e78c967e38e56f841bec8e&per_page=100&_nocache=579432
https://api.github.com/search/issues?access_token=1b97dca1f1aeb9b722e78c967e38e56f841bec8e&per_page=100&_nocache=96276&sort=created&order=asc&q=type%3Apr%20team%3AShopify%2Fcrafters%20team%3AShopify%2Fteam%20team%3AShopify%2Fchannels%20team%3AShopify%2Fdata-modelling%20team%3AShopify%2Fchannel-engagement%20state%3Aopen
...

Followed by a whole ton more requests to repos? and issues?. Eventually
they are throttled.

I hope that helps.

**Comment by pkaminski** [comment]
Careful, the URLs you posted above include your GitHub access token.  I edited your message to take them out but you should immediately revoke your authorization for Reviewable anyway at https://github.com/settings/applications.  Reviewable will prompt you to re-authorize next time you visit.

Some more questions:
1.  If you close all Reviewable tabs, wait a full minute, then visit the dashboard and just wait there without clicking anything, does the error repro?
2.  Is your "Also show pull requests you're not involved with..." toggle on, at the bottom of the page?
3.  Did you authorize `read:org` access?  (I'm guessing yes, based on the URLs above.)
4.  What is the number of stalled reviews in the "Include NN stalled reviews" button?  (Or is the number missing altogether?)

Thanks!

**Comment by pkaminski** [comment]
Ping.  I genuinely can't reproduce this.  Can you confirm that *new* requests for github.com/search/issues appear after you hit the "Include stalled reviews" button?

**Comment by erikwright** [comment]
I can confirm that everything appears to be in an idle state before I click
that button. Then a steady stream of requests takes off.

1. If you close all Reviewable tabs, wait a full minute, then visit the
> dashboard and just wait there without clicking anything, does the error
> repro?
>

Yes. I opened a new tab, opened developer tools, clicked "Preserve Log" and
navigated to Reviewable. I immediately see the spinner where the review
list should be and a series of requests. When it reaches around 130 I see
failures and the error message.


> 2. Is your "Also show pull requests you're not involved with..." toggle
> on, at the bottom of the page?
>

Yes, this is the toggle that causes the failure.


> 3. Did you authorize read:org access? (I'm guessing yes, based on the
> URLs above.)
>

[image: Inline image 1]


> 4. What is the number of stalled reviews in the "Include NN stalled
> reviews" button? (Or is the number missing altogether?)


This button is missing altogether when I navigate to this page with that
toggle already enabled.

**Comment by erikwright** [comment]
FYI, I have access to 1270 repos according to the GitHub dashboard.

It seems logical to me that it would have some upper bound on the amount of
data that can be fetched in this manner.

**Comment by pkaminski** [comment]
OK, based on the assumption that the root cause is the high number of repos, I built an alternative query strategy for this case.  Can you give it another try?  You might still get errors, but hopefully they'll be *different* errors.  :)

**Comment by erikwright** [comment]
Seems a lot better. I have no idea how complete the list is (but at least
it warns me). There were no load errors.

Also, every minute or two it sends off another batch of 100 or so requests.
I have no idea if this is attempting to refresh the list or to complete the
dataset.

It's a shocking amount of data transfer (after 10 minutes, 9.3MB).

Also, I hit refresh, and then I did hit the "failed to fetch" (quota)
error. So whatever it's doing to know how to stay in its quota is only
sufficient for a single load.

On the other hand, I was pleasantly surprised that navigating to a review
immediately after loading the list didn't trip the quota, nor did returning
to the review list by hitting the "Reviews" button or the browser's back
button. I tried going between the list and reviews as fast as I could,
triggering 600+ requests, without any quota errors. Occasionally it blocks
for a moment while loading a review – is it waiting for the quota to
replenish?

[image: Inline image 1]
...
[image: Inline image 2]

**Comment by pkaminski** [comment]
Glad to hear it's kinda working.  To be honest, given the number of repos you have access to -- there's just no way that toggle will work well for you due to the way GitHub's PR indexes are structured.

The list gets refreshed every minute, and is kept cached in the background if you jump to a review so you can easily come back.  Many of the responses also have ETags for reliable caching, so on subsequent requests Reviewable should get a bunch of 304's, which doesn't count against (some) quotas.  The amount of data is huge because GitHub's API doesn't provide a way to select the (few) fields Reviewable is interested in, sending the entire object every time.

The review loading delays may be due to quota -- you'd have to check for 403's in the network logs.  Reviewable is built to detect those and, if GitHub provided a `retry-after` value, automatically retry them.

All that said, Reviewable really isn't designed to handle review management at that kind of scale, and GitHub's native UI remains the tool of choice there.

**Comment by erikwright** [comment]
We're on the same page. I don't really care if this UI works, I just care that there not be really prominent and broken things that are begging to be clicked on. Thanks for taking care of this one (I'm happy with the current state).

**Comment by pkaminski** [comment]
BTW, I also spotted an additional bug where the "Include N stalled reviews" counter didn't account for the "show pull requests not yet connected to Reviewable" setting, and another one where flipping the latter toggle didn't immediately update the review list.  :(  Both fixed.
