### ISSUE TITLE
Merge button merges regardless of GitHub merge settings

### ISSUE THREAD

**Issue by Artur-** [Reviewable/Reviewable#275]
GitHub recently added a "squash merging" option and the possibility to disable merge commits. Reviewable should take these into account and act accordingly. Right now it seems all changes are merged using a no-ff merge commit regardless of the setting.

**Comment by pkaminski** [comment]
Yup, this is on the todo list.  There's some complications because GitHub doesn't give access to the repo's "allow merge" and "allow squash" flags.

**Comment by tleyden** [comment]
@pkaminski is there currently *any* way to squash multiple commits on a PR into a single commit via reviewable.io?  Or do I need to do a `rebase -i` and a force push on the branch?  (or use reviewable for review, and then github for actual merge + squash)

**Comment by pkaminski** [comment]
Sorry, there's currently no way to squash merge via Reviewable, your best bet is to do it via GitHub.  Adding squash support is high on my priority list but there's some prereqs before it.

**Comment by pkaminski** [comment]
Squash merges are now available through the dropdown attached to the merge button.  Note that your GitHub repo settings about whether normal / squash merges are allowed are *not* respected, because there's no API to read them.  However, you can set similar restrictions via Reviewable's repository settings panel.

**Comment by Artur-** [comment]
Tried "Squash & Delete branch", got "Unable to merge branch: GitHub error 422 on PUT `https://api.github.com/repos/<the>/<repo>/pulls/<pr>/merge`: Invalid request.
For 'properties/commit_message', nil is not a string.

**Comment by pkaminski** [comment]
Oops, please reload the page and give it another try now.

**Comment by Artur-** [comment]
:+1: works now
