### ISSUE TITLE
Guide popover interacts badly with auto-collapsing discussion editor

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#276]
I noticed a couple of issues with the guides when playing around with the auto-collapsing discussion editor.

* If I click “Follow up…” on the discussion to get the panel, don’t type anything, and press F1 while hovered over any of the buttons, clicking inside of the help popover remove focus from the editor, which causes the editor to dismiss, which causes the help panel to jump to the upper-left corner (except for the hole in the backdrop which stays in the same place). I can also trigger this by cmd-tabbing to another window.
* Similarly if I do the same thing but click outside the help popup, it remove focus from the editor and dismisses it. Since I’m clicking on a dark backdrop behind the help popover, I expected it to simply dismiss the popover but leave focus in the editor. With the way it works right now, if I view a help topic for the editor when I haven’t typed anything, the only way to dismiss the help without closing the editor is to press F1 twice.

This is with Safari 9.1 (11601.5.17.1) on OS X 10.11.4.

**Comment by pkaminski** [comment]
Fixed.

**Comment by kballard** [comment]
That was fast! And it seems to work. Thanks!
