### ISSUE TITLE
Auto-collapsing discussion editor animation issues

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#277]
When playing around with the auto-collapsing discussion editor and guides, I kept seeing an issue with the animation. For a single frame of the animation the page renders wrong, but it goes by so fast that I'm not quite sure what it's actually doing, it mostly just appears as a "blink" in animation and looks bad.

I can reliably reproduce the issue by clicking on "Follow up...", hovering over any element, pressing F1, and then clicking on the backdrop. Occasionally it “blinks” when showing the help popover, but it seems to always “blink” when closing the help popover and the editor at the same time.

On the same note, occasionally when showing the guide on other elements, the guide popover itself appears to "blink". As before, it's hard to tell exactly what's going on since it goes by so fast, but my impression is it's showing the popover in the final state before jumping to the start of the animation.

Reproduced with Safari 9.1 (11601.5.17.1) on OS X 10.11.4.

**Comment by pkaminski** [comment]
Reproduced in Safari, but since it doesn't happen in Chrome or Firefox I'm going to put the blame on Webkit.  I'll track it in #281 along with other Safari glitches and look at it as time allows, but Safari is a low-priority platform for me at this point.
