### ISSUE TITLE
Repository Connections page loses switches when showing guide

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#278]
On the Repository Connections page, when I show a guide (or show all the guide zones) all the switches vanish. This looks particularly odd when showing a guide for the switch itself, since the guide ends up pointing at blank space.

Reproduced with Safari 9.1 (11601.5.17.1) on OS X 10.11.4.

**Comment by pkaminski** [comment]
Reproduced in Safari, but since it doesn't happen in Chrome or Firefox I'm going to put the blame on Webkit.  I'll track it in #281 along with other Safari glitches and look at it as time allows, but Safari is a low-priority platform for me at this point.
