### ISSUE TITLE
Reviewable doesn't set the status check immediately

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#279]
After creating a PR (and verifying that Reviewable picked it up), several minutes later when I looked at the PR in GitHub again I noticed there was no status check for it. I actually noticed this when the CI build finished and the PR got marked as passing all status checks, which surprised me because I knew it hadn't been reviewed yet.

I sent an email about this, and in the email I theorized that Reviewable wasn't setting status checks on provisional revisions, although when I check the PR now it has the status check (despite still being a provisional revision). So I'm not really sure what's going on, since I would have expected Reviewable to set the status check immediately.

**Comment by pkaminski** [comment]
This is as intended:
![image](https://cloud.githubusercontent.com/assets/1646896/14333385/500bb79c-fc03-11e5-9339-0926e8f3aa6e.png)

You can access the dialog from here:
![image](https://cloud.githubusercontent.com/assets/1646896/14333407/66413a78-fc03-11e5-9738-e870f5c60a3c.png)

The intention is to accommodate organizations that may not be using Reviewable for all PRs by default, even though the repo is connected.

A better way to access these settings is coming.

**Comment by kballard** [comment]
Ok, great, I'll change that, thanks.
