### ISSUE TITLE
detection of go funcs detects closures

### ISSUE THREAD

**Issue by mmlb** [Reviewable/Reviewable#283]
Attached is a screen shot of a review where the 3rd hunk shows the problem. The detection should have equivalent of `^func `

![2016-04-08-140819_3192x2317_scrot](https://cloud.githubusercontent.com/assets/708570/14393157/5de291e2-fd93-11e5-963b-cd21c3a86aa3.png)

**Comment by pkaminski** [comment]
A function literal could be "named" by being assigned to a variable.  Is this not a common pattern in Go?  If not, then I agree it would be more useful to show the nearest function statement instead.

**Comment by pkaminski** [comment]
I changed the detector to grab either funcs that start a line (modulo whitespace) or that are immediately preceded by `:=`.  Please let me know if it's still broken!

**Comment by mmlb** [comment]
yes its possible in go to assign a func to a var thereby naming it. It just seems odd to me to use that as the context for the change. I can't think of an instance where I would only want the inner-func, I always want to know the top-level func to give me the context I'm looking for.
