### ISSUE TITLE
TypeScript syntax highlighting

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#285]
This might be as simple as saying that `.ts` and `.tsx` file are JavaScript, which is mostly true.

For example http://jsbin.com/mesigugoro/edit?html,output

**Comment by pkaminski** [comment]
`.ts` should already be working, but `.tsx` requires a separate language definition, see https://github.com/isagalaev/highlight.js/issues/878.  That issue was closed but I'm not convinced it was actually fixed.  Could you point me to a public review with some `.tsx` files so I can do some testing?  Thanks.

**Comment by danvk** [comment]
Here's [a jsbin with highlightjs][1] showing that language=javascript works fine for TSX files.

I can't point you to any public reviews of my own using TSX, but here's a public PR in someone else's repo: `https://github.com/willowtreeapps/tsx-boilerplate/pull/8`.

[1]: http://jsbin.com/bosodoceja/edit?html,output

**Comment by pkaminski** [comment]
Using `javascript` isn't perfect since it won't properly highlight many TypeScript-specific bits, but it's better than `typescript` or letting it go unhighlighted.  I've made the change in Reviewable.

I also opened isagalaev/highlight.js#1155 to get a proper `tsx` language definition in place.

**Comment by danvk** [comment]
Which version of highlight.js is Reviewable using? There was a [fix for TypeScript][1] that went out in 9.4.0. I'm losing syntax highlighting in many of my TSX files, and I suspect this might be the cause.

[1]: https://github.com/isagalaev/highlight.js/issues/1136

**Comment by pkaminski** [comment]
I upgraded to 9.4.0 a few days ago.  Did it make things worse?

**Comment by danvk** [comment]
Looks like I'm running into https://github.com/isagalaev/highlight.js/issues/1190

**Comment by danvk** [comment]
FYI this issue finally got closed in highlight.js. So the next release should fix it for Reviewable.

**Comment by pkaminski** [comment]
I integrated highlight.js 9.7.0, so isagalaev/highlight.js#1190 should be fixed.  No ETA on isagalaev/highlight.js#1155 though.

**Comment by pkaminski** [comment]
https://github.com/highlightjs/highlight.js/issues/1155 was fixed and I just integrated the release, so this should now be fixed at long last!

**Comment by pkaminski** [comment]
The highlightjs release was buggy so I had to temporarily roll this back, but I expect it'll back in a few days.
