### ISSUE TITLE
Let me configure the Reviews page to show all PRs from a specific set of repos

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#286]
I've configured Reviewable to be connected to 10 repos from my organization, 6 of which I care about and review PRs on, 4 of which I don't. Those 6 repos I am marked as Watching. I'd love it if the Reviews page would show me all PRs from those 6 repos, not just PRs I'm involved with.

I did see the checkbox at the bottom "Also show pull requests you're not involved with from all repos to which you can push", but when I tried checking that, and then unchecking "Show pull requests not yet connected to Reviewable", I first got an API rate limit error from GitHub, and then after waiting a couple of minutes and refreshing, I got a warning that the GitHub query returned partial results. So it seems like that setting isn't usable for me.

I think the simplest way to handle this is to provide a configuration where I can say "Show me all repos I can push to and/or are watching from the selected organizations", so I can turn it on just for my particular organization. Presumably by just looking for repos from a specific organization it can avoid getting partial results or API rate limits (because it's querying fewer repos).

For context, before using Reviewable, my workflow was to use a bookmark to the https://github.com/pulls page that executed a search that looks like `is:pr is:open repo:postmates/foo repo:postmates/bar repo:postmates/baz repo:postmates/qux repo:postmates/quux repo:postmates/corge`. This would show me all the open PRs from the repos I care about (although it doesn't live-update). So I'm looking to do something similar with Reviewable, where I have a single page that I'm confident will show me all of the PRs that I might want to review.

**Comment by kballard** [comment]
FWIW even selecting the "watched" option for "Also show pull requests you're not involved with …" still hits the partial query results warning.

**Comment by pkaminski** [comment]
In theory, Reviewable should be issuing the exact query you show above (and a few extra ones, for closed PRs, involvement, etc.).  Can you confirm that you only have those 6 repos marked as "watching" and no others, and provide a screenshot of the state of the toggles at the bottom of the page?  Could you also check what requests to `/search/issues` are being made from the page?  (Be careful to elide the `auth` query param if you post them here.)

Let's make sure Reviewable is making the correct requests, and if it is, we can try to figure out why GitHub is reporting the results as incomplete.

**Comment by TravisEz13** [comment]
My workflow is similar to what @kballard  mentions, query the PRs for an accurate list of repo's, but in my case, this does not correspond to the PR's I'm mentioned in or that my Org enabled.  I'd like to be able to provide an accurate list of the repo's I own reviewing.

**Comment by pkaminski** [comment]
Sorry, I don't quite follow @TravisEz13.  If you mark the repos you're responsible for as "watched" and set your toggles like so in Reviewable:
![image](https://cloud.githubusercontent.com/assets/1646896/14516100/89e69ed0-01b4-11e6-90a9-afb7f9d62b55.png)
How does Reviewable's list differ from what you'd like to see?  Too many reviews, too few reviews, incomplete results, ...?

**Comment by TravisEz13** [comment]
I missed the option to limit it to only watched or 'starred' repos.  I don't really want to watch all the repos, but it works.  May try switching to 'starred' later.

**Comment by kballard** [comment]
Oh I'm definitely watching more repos than just those 6. But those 6 are the only repos that I watch that are connected to Reviewable. I watch some other repos (with very high volume) that aren't connected, so Reviewable shouldn't be looking for PRs from them (I don't have the switch selected that makes it show PRs from non-connected repos).

Here's the toggles:

<img width="1507" alt="screen shot 2016-04-14 at 10 38 48 pm" src="https://cloud.githubusercontent.com/assets/714/14552284/b3ff446e-0291-11e6-95b2-5bdcbcdc9da4.png">

(Also note how this screen shows zero PRs; with the switch off it shows 3 PRs involving me that have all been Merged, so they're dimmed. Turning on the switch causes those PRs to vanish)

When I checked the switch, it made a bunch of requests for `user/teams`, `user/repos`, `user/subscriptions`, `search/issues`, and 6 of my watched repos (but not any of the ones I actually care about).

The first `issues` request was for open PRs that involve me (https://api.github.com/search/issues?per_page=100&sort=created&order=asc&q=type%3Apr%20involves%3Akballard%20state%3Aopen, URL sanitized to remove `access_token` and `_nocache` parameters). Then closed PRs (https://api.github.com/search/issues?per_page=100&sort=created&order=asc&q=state%3Aclosed%20type%3Apr%20involves%3Akballard%20closed%3A%3E2016-04-11T22%3A38%3A32-0700). Then apparently it was looking for PR's from the various teams I'm a member of, both open PRs (https://api.github.com/search/issues?per_page=100&sort=created&order=asc&q=type%3Apr%20team%3AOpenEmu%2Fdevelopers%20team%3Apostmates%2Fhackers%20team%3Afish-shell%2Fcontributors%20team%3Arust-lang%2Frust-push%20team%3Apostmates%2Fios%20state%3Aopen) and closed PRs (https://api.github.com/search/issues?per_page=100&sort=created&order=asc&q=state%3Aclosed%20type%3Apr%20team%3AOpenEmu%2Fdevelopers%20team%3Apostmates%2Fhackers%20team%3Afish-shell%2Fcontributors%20team%3Arust-lang%2Frust-push%20team%3Apostmates%2Fios%20closed%3A%3E2016-04-11T22%3A38%3A33-0700).

At that point, it fetched the second page of `user/subscriptions` and a couple more pages of `user/repos`. And then a weird one. It looked for open PRs from a variety of users, some of which are organizations and some are plain old users (https://api.github.com/search/issues?per_page=100&sort=created&order=asc&q=type%3Apr%20user%3Aapple%20user%3Afish-shell%20user%3Ajaminguy%20user%3Ajfro%20user%3Ajweinberg%20user%3Akballard%20user%3AOpenEmu%20user%3Apostmates%20user%3Arust-lang%20state%3Aopen), then the equivalent search for closed PRs. As best I can figure, every user in the list owns at least one repository that I'm watching. But I don't know why it would look for all PRs from those users, there's no reason for me to be looking at PRs from repos I'm not watching and all those users have repos that I'm not watching. Then it looked for a second page of open PRs (https://api.github.com/search/issues?per_page=100&sort=created&order=asc&q=type%3Apr+user%3Aapple+user%3Afish-shell+user%3Ajaminguy+user%3Ajfro+user%3Ajweinberg+user%3Akballard+user%3AOpenEmu+user%3Apostmates+user%3Arust-lang+state%3Aopen&page=2&per_page=100, incidentally this one uses `+` instead of `%20` for spaces which is a curious change) and closed PRs. And then more pages, ending up in a total of 6 pages of open PRs and 5 pages of closed PRs.

Then it fetched info about 6 repos I follow (e.g. https://api.github.com/repos/apple/swift-evolution?per_page=100), though as I said before, not any of the repos that are actually connected to Reviewable. Then it fetched the labels for these repos. And then a bunch of github avatars, as well as info on a small handful of PRs (e.g. https://api.github.com/repos/apple/swift/pulls/2188?per_page=100).

At this point it stopped. Then about 2 minutes later it all started back up again, making what looks to be roughly the same set of PR queries, followed up by then fetching info about a whole bunch of repos it hadn't fetched before, ones I'm not even watching, such as https://api.github.com/repos/macvim-dev/macvim?per_page=100. And as I wait longer it seems to keep doing this in cycles, running all those same PR searches.

The net result of all of this is it appears as though it wasn't even trying to filter based on what repos are connected to Reviewable, despite the fact that I don't have it set to show PRs that aren't connected. What's more, it is using an overly-broad search for open PRs, looking for all PRs by any user that owns a repo that I follow, instead of just searching for PRs from the specific repos I'm watching (and filtering that list to just the repos that are connected to Reviewable).

All of this also explains why I hit the API rate limit error the first time I turned on this switch. It's doing a *lot* of queries in a short time.

**Comment by pkaminski** [comment]
Ah, I think I understand the miscommunication:  the "Show pull requests not yet connected to Reviewable" toggle refers to individual PRs, not repos.  It's possible to use Reviewable in an ad-hoc way on selected PRs without connecting the corresponding repo, so the reviews list pays no attention to whether a repo is connected or not even when the toggle is switched off.

The weird query for users/organizations you're seeing is a fallback strategy, when the number of repos you have push permission for is too high.  Instead of forming a bunch of queries for those repos (they won't fit into one request), I query for the hopefully smaller number of distinct owners instead and post-filter for the repos of interest.  But due to the breadth of this query it's fairly likely to return incomplete data.

I think the subset of PRs you're trying to fetch is reasonable, so I added a new "connected repos" constraint on the toggle.  No guarantees since I only did minimal testing, but give it a try!

**Comment by kballard** [comment]
Excellent, it seems to work! Thanks!

I turned it on with "watched" off, and after 10 seconds the list refreshed to show PRs from the 2 repos that my organization has connected that I'm not watching (none of the ones I'm watching have open PRs at the moment). I then re-enabled the "watched" flag and those PRs disappeared, but I assume it's all working properly now because I'm no longer getting the "partial results" warning.

**Comment by kballard** [comment]
So, my coworker tried turning on this feature, and it didn't work for him. The PR list didn't update at all when he turned it on, and then after refreshing the page, the page just ended up showing the loading indicator indefinitely (not even showing the PRs involving him). We checked the web inspector and it didn't look like there were any outstanding requests, but didn't have time to investigate any further.

**Comment by pkaminski** [comment]
I'm pretty sure I know where things got stuck, though I don't know why.  Can you get your coworker to join this thread, post his/her username, and a screenshot of the toggles' state on the review page?  At a minimum, I can jiggle things so that there's a timeout and error message of some sort, but naturally I'd prefer to fix it.

**Comment by kballard** [comment]
My coworker is @ekimia, hopefully he'll see this mention, if not I'll ask him about it on Monday. As for the toggles, I told him what to set (and watched him do it) so I know how it was set up, which is identical to the way I have it set up. The following is a screenshot of my toggles, but his looked the same.

<img width="1453" alt="screen shot 2016-04-15 at 8 56 52 pm" src="https://cloud.githubusercontent.com/assets/714/14578912/a1357c5c-034c-11e6-8629-a96b59baaa46.png">

If it matters, I had him enable "connected", then "watched", then disable "Show pull requests not yet connected to Reviewable.", and then finally enable "Also show pull requests you're not involved with from all repos to which you can push.". But I'm guessing the order doesn't matter since the problem still occurred after refreshing the page.

Some sort of timeout/error is a good idea too, though obviously fixing it is best (but the timeout/error would be good for cases where things still don't work right).

Also, when I change the state of those toggles, it would be nice to show the loading indicator again. Right now, if I change them after the page has loaded, there's no indicator telling me that it's trying to load new data.

**Comment by pkaminski** [comment]
The issue for @ekimia was that permissions were denied for some repos -- I've no idea why.  I switched to a different (and more efficient) way of checking permissions and also fixed the error reporting so it shouldn't just hang any more.  I also now dim the list when doing a load in response to a settings change.

Please give it another try!

**Comment by kballard** [comment]
I just hit the permissions error myself. I looked at a review, then clicked back to the Reviews page, and got an error saying

> Failed to fetch a list of your reviews: Error: Permission denied for apple/swift. Try again.

And as a result, the reviews list is empty. If this permission error was the only error, the reviews list shouldn't be empty (in fact, the expected contents of the reviews list doesn't even contain any PRs from apple/swift).

After reloading the page, there was no more error, and it showed me 2 reviews. However, the last time I looked at this page (earlier today) it also showed 2 greyed out "Merged" PRs, and those PRs aren't listed anymore. I'm not sure what the criteria is for showing recently-merged PRs, so maybe it legitimately doesn't want to show those anymore, I'm just noting it here in case it really should be showing them anyway.

**Comment by pkaminski** [comment]
The bad news is that looking into the permission error has opened up a can of worms.  The good news is that I finally have a repro for an issue I've been trying to figure out for months.  I'm digging through layers of abstractions to get to the bottom of it...  Stay tuned.

**Comment by kballard** [comment]
Oh dear. I'm glad you finally have a repro though!

FWIW, the permissions errors I've personally seen (I got another one this morning) have been on repos that don't have any PRs hooked up to Reviewable. Fixing the issue for good would be great, but if it's going to take a while, you might consider having your server keep a list of all repos that have ever had a single PR hooked up to Reviewable, so that way anyone with "Show pull requests not connected…" off can then avoid even looking up any info at all about repos that have never had a Reviewable PR.

**Comment by pkaminski** [comment]
OK, I hunted down 3+ error-handling bugs and can no longer repro bad behavior, so I'm hoping at least one of them was responsible for the issue you saw as well.  Let me know if it recurs, though.
