### ISSUE TITLE
Direct links to comments are slow to load

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#29]
For example, when I click [this link](https://reviewable.io/reviews/hammerlab/cycledash/387#-JdEk8aM7eQm-YwjERZC), I can count 6-7s between the click and the comment being visible. 3-4 of these seconds are _after_ the Reviewable page loads. I see it calculate diff stats, then scroll to the comment. The order of operations should be reversed—Reviewable should scroll to the comment ASAP.

Here's a video of it happening: http://cl.ly/3F191v0P0W3I

You can see the diffstats loading on the right hand side of the page, followed by the scroll to the comment.

**Comment by pkaminski** [comment]
With overall performance improved, and the new auto-single-file mode for large reviews, I think it's unlikely I'll put more work into this.
