### ISSUE TITLE
Support for bitbucket.org

### ISSUE THREAD

**Issue by akurdyukov** [Reviewable/Reviewable#293]
Do you have any plans to support bitbucket.org?

**Comment by pkaminski** [comment]
Nope, sorry.  Reviewable is built against GitHub's API rather than directly on top of git, so it would be a big effort to port to another platform and at this point I don't there's sufficient demand for it.

**Comment by bronumski** [comment]
@pkaminski This is a real shame. I have been using reviewable for the past year and really loved it but have now had to move to bitbucket which is severely lacking to say the least. Bitbucket also has an API, maybe you could find out if there is any demand to target a different provider. You would definitely get my vote.
