### ISSUE TITLE
Mangled "No newline at end of file" display 

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#295]
Reviewable:

![screen shot 2016-04-26 at 2 34 12 pm](https://cloud.githubusercontent.com/assets/98301/14829919/015fcbb0-0bbc-11e6-8f4a-a5997d0d73fc.png)

GitHub:

![screen shot 2016-04-26 at 2 34 28 pm](https://cloud.githubusercontent.com/assets/98301/14829922/039ff148-0bbc-11e6-8d62-3e827e8d53fb.png)

It's clearer what's going on in the GitHub UI, and the tooltip makes it completely transparent. Reviewable should do something similar.

**Comment by pkaminski** [comment]
Looks like a regression, will fix.

**Comment by pkaminski** [comment]
So I was able to reproduce this once, in Chrome 50 on OS X 10.10.5, but as soon as I reloaded the page it showed the correct symbol (like the GitHub one).  I wasn't able to reproduce in other browser/OS combinations at all.  Can you characterize when and how you're able to reproduce this?  Thanks.

**Comment by danvk** [comment]
I just saw this again on Mac OS X / Chrome 49.0.2623.87. Refreshing did not fix the problem.

I'd send a link but it was in a private repo.

**Comment by pkaminski** [comment]
That's OK, I don't think it's repo-specific anyway.  I wonder if it has
something to do with webfont loading.  Do you have a custom source code
font set for your account?  Are there any obvious differences in the
Network panel fetch order / latencies between working and non-working page
loads?  I'll keep trying to repro this over here as well.

On Thu, Apr 28, 2016 at 1:44 PM, Dan Vanderkam <notifications@github.com>
wrote:

> I just saw this again on Mac OS X / Chrome 49.0.2623.87. Refreshing did
> not fix the problem.
>
> I'd send a link but it was in a private repo.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/295#issuecomment-215554340>
>



-- 
Piotr Kaminski, Founder, reviewable.io

**Comment by danvk** [comment]
I don't have a custom font. FWIW, I've never seen this render correctly on Reviewable.

**Comment by pkaminski** [comment]
I still can't get it to repro, no matter how much I clear the cache, restart the browser, etc.  Can you reproduce it at https://reviewable.io/reviews/pkaminski/sample/3?  The first file (`fancy.foo`) has no final newline at r3.

Could you also try setting a custom monospace font that's already installed on your machine, to see if that makes a difference?

I need some extra data to have a chance of figuring this out.  :(  Thanks.

**Comment by kswoll** [comment]
Our team started seeting this again as well.  And yes, when I look at your sample above, it appears.  Our team does not like to end files with newlines, so it's kind of causing us a lot of noise in our code reviews because we mistakenly think there's actually a problematic newline character.

**Comment by kswoll** [comment]
I should add that I'm using Chrome

> Version 59.0.3071.115 (Official Build) (64-bit)

It does not happen in MS Edge, Internet Explorer, or FireFox.

**Comment by pkaminski** [comment]
For some reason I now managed to reproduce the issue right away -- it looks like Chrome has some problems with displaying the combining prohibition symbol.  I changed the characters to non-combining ones so it should now look pretty much like the GitHub notification in all browsers.

Thanks for attracting my attention back to this issue!

**Comment by kswoll** [comment]
Thanks @pkaminski! :)
