### ISSUE TITLE
Failed to publish: Cannot read property '$ref' of undefined

### ISSUE THREAD

**Issue by nvanbenschoten** [Reviewable/Reviewable#296]
I'm getting the following error when pushing a large set of responses.

![screen shot 2016-04-27 at 8 02 22 pm](https://cloud.githubusercontent.com/assets/5438456/14871725/173c5cb2-0cb3-11e6-8ead-cef14c2b27fd.png)

Let me know if there's any other information I can provide about the issue.

**Comment by pkaminski** [comment]
Hi Nathan,

For some reason, I don't see this exception in my error capture system,
which would make it much easier to debug.  Can you check in your network
panel if requests to getsentry.com are being blocked, perhaps?  Thanks,

    -- P.


On Wed, Apr 27, 2016 at 5:05 PM, Nathan VanBenschoten <
notifications@github.com> wrote:

> I'm getting the following error when pushing a large set of responses.
>
> [image: screen shot 2016-04-27 at 8 02 22 pm]
> <https://cloud.githubusercontent.com/assets/5438456/14871725/173c5cb2-0cb3-11e6-8ead-cef14c2b27fd.png>
>
> Let me know if there's any other information I can provide about the issue.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/296>
>



-- 
Piotr Kaminski, Founder, reviewable.io

**Comment by nvanbenschoten** [comment]
Hi Piotr,

I'm not seeing any requests to getsentry.com (being blocked or otherwise). I am however seeing a 403 error when loading https://api.github.com/orgs/cockroachdb/teams.

**Comment by pkaminski** [comment]
Sorry about that, I made a guess at the error and deployed a fix -- can you
confirm it's working now?

And incidentally discovered that I introduced a bug into my exception
capture a couple days ago.  No wonder things have been so quiet...  :(

    -- P.


On Wed, Apr 27, 2016 at 5:11 PM, Nathan VanBenschoten <
notifications@github.com> wrote:

> Hi Piotr,
>
> I'm not seeing any requests to getsentry.com (being blocked or
> otherwise). I am however seeing a 403 error when loading
> https://api.github.com/orgs/cockroachdb/teams.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/296#issuecomment-215269989>
>



-- 
Piotr Kaminski, Founder, reviewable.io

**Comment by nvanbenschoten** [comment]
Piotr, that worked 👍  Thanks for the extremely fast fix and thanks for the hard work on Reviewable!
