### ISSUE TITLE
Is reviewable editing lots of comments?

### ISSUE THREAD

**Issue by larsbergstrom** [Reviewable/Reviewable#297]
I'm trying to track things down, but over the last day or so, one of either Reviewable, AppVeyor, or Travis has been editing lots of random comments in PRs as me without changing the content. e.g.,
https://github.com/servo/servo/pull/10892#issuecomment-215601699

Do you know if there's been a change to Reviewable that might cause this?

**Comment by pkaminski** [comment]
Sorry, my bad.  I rewrote some of the comment-handling code recently and in a misguided burst of enthusiasm decided to normalize newlines to make my regexes simpler.  Unfortunately, this caused Reviewable to think that it needed to patch up every comment when looking for `:lgtm:` emojis to replace with images.  It should be fixed now.  :blush:

**Comment by larsbergstrom** [comment]
Thanks for the quick fix! :-)
