### ISSUE TITLE
Don’t inhibit horizontal scroll

### ISSUE THREAD

**Issue by SimonSapin** [Reviewable/Reviewable#298]
https://reviewable.io/reviews/servo/servo/10815 currently has 58 revisions, which makes the file matrix table overflow my 27" monitor. That’s ok, horizontal scrolling is a bit of a pain but I’ll survive it in such an extreme case. Except the scrollbar is not there! There seems to be no way to reach the right-most columns to click on their headings to change the revision range being reviewed.

I’ve had to go into devtools to remove the `overflow-x` class on a `<div>` (the next sibling to `<div id="file-matrix-anchor">`). Could this (or some variation) be the default style?

**Comment by pkaminski** [comment]
I can't reproduce this -- I can see the horizontal scrollbar fine for that review, at the bottom of the file matrix:
![image](https://cloud.githubusercontent.com/assets/1646896/14909024/91d621e8-0d93-11e6-9e63-222ade7775bf.png)
Which browser/OS are you using?

**Comment by SimonSapin** [comment]
Ah! I see it now, never mind :)

(I was thinking of the viewport’s top-level scrollbar. This scrollbar one was not visible since the file matrix, with 30 files, is *also* (almost) taller than my monitor… FWIW this is Firefox on Linux / GNOME 3)

**Comment by pkaminski** [comment]
I do need to find a better way to deal with reviews with lots of revisions.  So far my thoughts have been around compressing the matrix horizontally when needed, or perhaps a kind of "magnifying glass" dynamic focus-based zoom effect...  Or maybe I'll just wait for everyone to start working in VR and have the file matrix wrap all the way around you instead.  :stuck_out_tongue:

**Comment by SimonSapin** [comment]
Another trick for this situation: CTRL + scroll (or whatever it is in your browser) to zoom out the entire page. In this case for me text is smaller than what’s comfortable to read but still readable while the whole table is visible. (Of course this only works to some extent: making a much bigger table entirely visible would make the text unreadable.)

**Comment by pkaminski** [comment]
Yes, that is admittedly the most straightforward approach.  Perhaps I could
refine it a bit and scale just the file matrix (independently on each
axis?) so that it just fits into the window...  As long as there's a button
to toggle this off, you could at least choose your poison.


On Thu, Apr 28, 2016 at 11:28 PM, Simon Sapin <notifications@github.com>
wrote:

> Another trick for this situation: CTRL + scroll (or whatever it is in your
> browser) to zoom out the entire page. In this case for me text is smaller
> than what’s comfortable to read but still readable while the whole table is
> visible. (Of course this only works to some extent: making a much bigger
> table entirely visible would make the text unreadable.)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/298#issuecomment-215636973>
>



-- 
Piotr Kaminski, Founder, reviewable.io
