### ISSUE TITLE
Complete @-mentions in markdown editor

### ISSUE THREAD

**Issue by pkaminski** [Reviewable/Reviewable#3]

**Comment by dannykopping** [comment]
:+1:

**Comment by pkaminski** [comment]
This is now implemented, though in a somewhat limited fashion:  in organizations it'll complete to an organization member or team (only ones "visible" to the user), and in personal repos it'll complete to a collaborator.  Searching for users outside of those subsets is pretty expensive, and hopefully not too common, though I could see improving on this limitation in the future.
