### ISSUE TITLE
Some way to manually switch to single-file mode

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#302]
I like how Reviewable switches to single-file mode when the diff is large enough, but I'd love a way to trigger this behavior for reviews that don't cross the threshold. Right now I'm doing a review that's pretty large but still under the threshold, and it's causing noticeable lag when typing comments, so I'd rather use single-file mode in this case. I'm thinking it could be a widget in the bunny dropdown.

**Comment by pkaminski** [comment]
Yup, this is planned.  See #261.
