### ISSUE TITLE
Reviews spam my history with duplicate entries

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#303]
My history is getting spammed with entries created by Reviewable I'm not sure what causes it, but my guess is every time I jump between files or comments.

![screen shot 2016-05-13 at 4 51 18 pm](https://cloud.githubusercontent.com/assets/714/15264700/0c4bd588-192b-11e6-8b66-93ad29f66dea.png)

**Comment by pkaminski** [comment]
Which browser/version?  Reviewable manipulates the address bar URL to include the anchor of the currently focused discussion, but at least in Chrome only the latest URL is included in the history.

**Comment by kballard** [comment]
Safari 9.1 on OS X 10.11.4.

**Comment by pkaminski** [comment]
Reproduced.  I think this is a bug (or "design decision" if you want to be generous) in how Firefox and Safari treat `replaceState` calls that only change the URL anchor.  Chrome and Edge (!)  both handle this correctly, by including only one entry in the history for all URL variants.  Unfortunately I don't see any way to work around the bug as there's no flag or API for manipulating a browser's "long term" history (rather than the immediate history stack).

I think the utility of surfacing navigation state via the URL outweighs keeping the history clean in two (arguably) broken browsers so I'll stick with the current behavior.  Sorry.

**Comment by kballard** [comment]
Looking at it today, merely jumping around in Reviewable isn't creating history entries. In fact, it's not even creating tab-local history entries (if I jump to a new file I cannot hit back). However, I did manage to create a new history entry after marking a file as reviewed. But I only got one in the review today.

My suspicion right now is that interacting with comments is connected to creating new history entries, because I resolved 2 comments in the current review, and then when I later marked a file as reviewed a history entry showed up in the global history menu (but still no local forward/back history). In the review I was doing that the screenshot came from I created 52 comments, which would explain the large number of history entries.

**Comment by pkaminski** [comment]
Currently Reviewable only modifies the URL when you select a discussion (creating a draft automatically selects it too), which accounts for your observations.  No history on file navigation is captured in #116.

I use the `replaceState` API which specifically overwrites the last entry in the "local" history, but apparently browsers differ in how they treat it wrt the "global" history.  The [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_replaceState()_method) even call this out explicitly:

> history.replaceState() operates exactly like history.pushState() except that replaceState() modifies the current history entry instead of creating a new one. Note that this doesn't prevent the creation of a new entry in the global browser history.

AFAICT this is a (bad) design decision on the part of Firefox and Safari developers and there's nothing an app can do to affect this behavior except to stop managing the local history altogether.

**Comment by kballard** [comment]
I see. That's really unfortunate. I'm going to go file a radar on Safari's behavior right now.

**Comment by kballard** [comment]
Submitted as rdar://problem/26372816.
