### ISSUE TITLE
"</details>" in email

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#305]
Here's how a discussion shows up in Reviewable:
![screen shot 2016-05-17 at 4 59 46 pm](https://cloud.githubusercontent.com/assets/98301/15339122/ed8d4b3a-1c50-11e6-84c9-f9db74050c5f.png)

and in the corresponding email:
![screen shot 2016-05-17 at 4 59 25 pm](https://cloud.githubusercontent.com/assets/98301/15339120/ec69896c-1c50-11e6-98f6-596ff141040c.png)

The backticks and `</details>` shouldn't be there.

**Comment by pkaminski** [comment]
Interesting.  Can you post the original comment's markdown source, and note whether there's a final newline or not?  Thanks.

**Comment by danvk** [comment]
It was probably this:

    Use template strings rather than concatenation:

    ```javascript
    `s2geojson-origin-${i}-${id}`
    ```

I have no idea if there was a trailing newline. Is it possible to view the markdown source in Reviewable after the comment has been published?

**Comment by pkaminski** [comment]
Fixed.

For future reference, there's no user-accessible way to look at markdown in Reviewable after publishing, but I usually just edit the comment on GitHub to see that.  (Or, given a PR number, I can pull out the raw data.)
