### ISSUE TITLE
Display number of files to review for individual reviewers

### ISSUE THREAD

**Issue by seckin206** [Reviewable/Reviewable#306]
Assume that;
- I have a pull request with 10 files
- Developer A comes early and reviews(marks as reviewed) all files.
- Now when developer B arrives, I want him to see 10 files to review, not 0 files to review on the top bar.

Our workflow requires many people to review a single branch, so our definition for unreviewed files are the ones that are not seen by at least N people. The current behaviour also creates problems in navigation since `jump to next unreviewed file` does not work properly(according to our definition of `unreviewed`) 

Here is a screenshot:
![My view](https://i.imgur.com/DglB7FD.png)

It shows `9` files to review because another developer made a pass before me.

**Comment by pkaminski** [comment]
I added the capability for custom review completion conditions to override the review state of files' revisions.  I also updated the UI to understand the difference between a personally-reviewed file, and an overall-reviewed file.  I believe this is sufficient to address your use case -- here's a sample completion condition derived from the default one that requires two reviewers to consider a file revision reviewed.  Please see [the FAQ](https://github.com/Reviewable/Reviewable/wiki/FAQ#can-i-customize-what-makes-a-review-complete) for how to make use of it.

```javascript
let reasons = [];  // pieces of the status description
let shortReasons = [];  // pieces of the short status desc.
const summary = review.summary;  // shortcut to summary

let numReviewedFiles = 0;
_.each(review.files, file => {
  _.each(file.revisions, fileRev => {
    fileRev.reviewed = fileRev.reviewers.length >= 2;
  });
  if (_.last(file.revisions).reviewed) numReviewedFiles++;
})
const numFilesLeft = summary.numFiles - numReviewedFiles;
if (numFilesLeft) {
  reasons.push(
    `${numReviewedFiles} of ${summary.numFiles} files reviewed`
  );
  shortReasons.push(
    `${numFilesLeft} file${numFilesLeft > 1 ? 's' : ''}`
  );
} else {
  reasons.push('all files reviewed');
}

if (summary.numUnresolvedDiscussions) {
  reasons.push(
    summary.numUnresolvedDiscussions +
    ' unresolved discussion' +
    (summary.numUnresolvedDiscussions > 1 ? 's' : ''));
  shortReasons.push(
    summary.numUnresolvedDiscussions + ' discussion' +
    (summary.numUnresolvedDiscussions > 1 ? 's' : '')
  );
} else {
  reasons.push('all discussions resolved');
}

const completed =
  !summary.numUnresolvedDiscussions &&
  !numFilesLeft;

let discussionBlockers = _(review.discussions)
    .where({resolved: false})
    .pluck('participants')
    .flatten()
    .where({resolved: false})
    .map(user => _.pick(user, 'username'))
    .value();

let fileBlockers = _(review.files)
    .filter(file => _.isEmpty(_.last(file.revisions).reviewers))
    .map(file => _(file.revisions).findLast(
      rev => !_.isEmpty(rev.reviewers)))
    .pluck('reviewers')
    .flatten()
    .compact()
    .value();

if (!completed && _.some(fileBlockers, user => !user)) {
  fileBlockers =
    fileBlockers.concat(review.pullRequest.assignees);
}

let shortDescription;
if (completed) {
  shortDescription =
    summary.numFiles + ' file' +
    (summary.numFiles > 1 ? 's' : '') + ' reviewed';
} else {
  shortDescription = shortReasons.join(', ') + ' left';
}

return {
  completed,
  description: reasons.join(', '),
  shortDescription,
  pendingReviewers:
    _.uniq(fileBlockers.concat(discussionBlockers), 'username'),
  files: review.files
};
```
