### ISSUE TITLE
Automatically collapse quoted code blocks in a comment

### ISSUE THREAD

**Issue by davidmason** [Reviewable/Reviewable#307]
Sometimes we want to clearly refer to a specific range of lines in a discussion, but maintaining a comment on range of lines across diffs is generally not possible as they may become disjoint.

As a workaround, we can include the lines under discussion in a code block

    ```elm
    drink up me hearties =
      case hearties of
        [] -> me
        cap'n :: lads -> drink up me lads |> up cap'n
    ```

but this can bloat the discussion, particularly since it is usually needed when a discussion is referring to more than a few lines.

A solution is to automatically collapse quoted code blocks, so they are available for reference but not pushing the discussion text out of view. Quoted blocks that are only 3 lines or less should not be collapsed by default since they are not as obstructive.

## Syntax

Quoted code blocks with no empty lines can use this syntax:

    > ```elm
    drink up me hearties =
      case hearties of
        [] -> me
        cap'n :: lads -> drink up me lads |> up cap'n
    ```

A single leading `>` is enough for an entire block of lines, cancelled only by an empty line. This means that code with empty lines must either:-

have newlines removed:

    > ```elm
    import Graphics.Element exposing (show)
    main = drink rum ye scurvies |> yarrrrrr
    drink up me hearties =
      case hearties of
        [] -> me
        cap'n :: lads -> drink up me lads |> up cap'n
    yarrrrrr = show
    rum = (+)
    ye = 0
    scurvies = [1, 2, 3, 4, 5]
    ```

or use the indented syntax with every line quoted, so each line begins with `>` followed by **5** spaces:

    >     import Graphics.Element exposing (show)
    >     
    >     main = drink rum ye scurvies |> yarrrrrr
    >     
    >     drink up me hearties =
    >       case hearties of
    >         [] -> me
    >         cap'n :: lads -> drink up me lads |> up cap'n
    >     
    >     yarrrrrr = show
    >     rum = (+)
    >     ye = 0
    >     scurvies = [1, 2, 3, 4, 5]

**Comment by pkaminski** [comment]
Thanks for the great spec!  Implemented.
