### ISSUE TITLE
Rust syntax highlighting is somewhat broken

### ISSUE THREAD

**Issue by nox** [Reviewable/Reviewable#308]
The syntax highlighter used in Reviewable seems confused by pattern alternatives:

<img width="586" alt="capture d ecran 2016-05-21 a 10 50 06" src="https://cloud.githubusercontent.com/assets/123095/15447413/0a669916-1f42-11e6-9245-25d45d378975.png">

**Comment by pkaminski** [comment]
Thanks, reported against highlight.js: https://github.com/isagalaev/highlight.js/issues/1182

**Comment by pkaminski** [comment]
I integrated highlight.js 9.5.0 so this should be fixed now.
