### ISSUE TITLE
Unread files in the review page doesn't reflect the file matrix state

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [Reviewable/Reviewable#309]
Here is the PR in the review page:

<img width="926" alt="screen shot 2016-05-23 at 10 11 03" src="https://cloud.githubusercontent.com/assets/407891/15464390/4b3fa0b6-20cf-11e6-94e4-ae67bf8f78bc.png">

and here is it's file matrix:

<img width="780" alt="screen shot 2016-05-23 at 10 12 59" src="https://cloud.githubusercontent.com/assets/407891/15464394/54d1cb72-20cf-11e6-9928-ccd2dbeee38b.png">

as no file is reviewed by me (aka red eye), I would expect the icon to be red in the review page

**Comment by BenjaminVanRyseghem** [comment]
After marking 2 files as reviewed:

<img width="968" alt="screen shot 2016-05-23 at 10 23 51" src="https://cloud.githubusercontent.com/assets/407891/15464597/a26a4f48-20d0-11e6-81ee-6906ddd163fc.png">

<img width="558" alt="screen shot 2016-05-23 at 10 23 30" src="https://cloud.githubusercontent.com/assets/407891/15464598/a26b5c08-20d0-11e6-9bc4-b7e8a2b69e27.png">

**Comment by pkaminski** [comment]
Fixed!
