### ISSUE TITLE
Review check error: ReferenceError: summary is not defined

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#311]
I just changed our review check to use the 2nd example (the one that checks assignees and disregards the PR author). It initially worked, but I just noticed that the PR I'm reviewing right now says

> Review check error: ReferenceError: summary is not defined at evalmachine.<anonymous>:75:5 at evalmachine.<anonymous>:89:3 at ContextifyScript.Script.runInNewContext (vm.js:1815)

**Comment by kballard** [comment]
After modifying the PR to add myself as an assignee (is there any way to do this in Reviewable besides adding a `+@foo` comment?), the review check status went back to normal.

**Comment by kballard** [comment]
And I'm getting it again. Looks like the error is triggered whenever the PR would otherwise be marked as done. The issue appears to be because line 75 references an undefined variable `summary`. The first example defines it at the top using

```js
const summary = review.summary;  // shortcut to summary
```

But the second example doesn't define it.

**Comment by pkaminski** [comment]
Yep, that was a paste-o, sorry about that; fixed.

And yes, the `+@` and `-@` directives are the only way to manipulate assignees in Reviewable at this point.  I may add a UI at some point, but it'll just insert the directives in a top-level message anyway...
