### ISSUE TITLE
Make the "Reviews" button a link

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [Reviewable/Reviewable#312]
So that one can CMD+click, or right-click "Open in a new tab"

**Comment by pkaminski** [comment]
Implemented.  Note that this wasn't as simple as it appears since those buttons also need to sign you in if you hit them on the home page when signed out, so please let me know if you see any weird side-effects.

**Comment by BenjaminVanRyseghem** [comment]
thanks 👍 

So far so good :smile:
