### ISSUE TITLE
Avoid reviewing an already reviewed commit

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [Reviewable/Reviewable#313]
Here is a workflow we usually have at work

```
        | (commit X)
        | task 1
    |  /
    |/
    |
    | feature 1
   /
|/
|
| master
```
so we have:

PR1 : feature 1 -> master (to follow and review the progresses along the way)
PR2: task 1 -> feature 1

So we review the **commit X** from *task 1*, consider it good,
and merge PR2.

Now **commit X** is part of *feature 1* and, as is, is to review in PR1.

But we already validated it. So it's some extra noise to us.

**Comment by pkaminski** [comment]
Yup, I think this is the same as #253.
