### ISSUE TITLE
"Reply inline" option

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#314]
If a reviewer leaves a comment like:

```
Do this.
Do that
And this other thing.
```

Then it would be convenient to have a way of easily replying to each task individually, i.e. to prefill the reply with:

```
> Do this.
> Do that
> And this other thing.
```

So that I could expand it to:

```
> Do this.

Done.

> Do that

Done.

> And this other thing.

I disagree with this.
```

This would be similar to expanding the "..." Show Trimmed Content button in a Gmail reply.

You could argue that the reviewer should have left three independent comments, but that ship has already sailed, right?

**Comment by pkaminski** [comment]
The workaround is obviously to copy/paste the previous comment manually, and add a `> `.  Only one quote mark is needed per paragraph (it's only canceled by a blank line) so it's usually not a lot of extra work.  One downside is that you won't get any of the formatting this way.

Do you think it's worth adding an extra UI button just for this functionality?  Or maybe trigger it automatically if the first and only character typed in a reply is a `>`?

**Comment by danvk** [comment]
Critique had "Reply" and "Reply with quote" links for this.

I think the Gmail treatment of a clickable "..." button is subtle while still being clear and effective:

![screen shot 2016-05-26 at 11 49 58 am](https://cloud.githubusercontent.com/assets/98301/15580828/0c629dba-2338-11e6-8e4b-d629ee94ad13.png)

**Comment by danvk** [comment]
And as you say, it's not a huge inconvenience to manually quote. Just thought I'd file this to track it as an item of interest for other users as well.

**Comment by pkaminski** [comment]
Would the approach in #320 be satisfactory, @danvk?

**Comment by danvk** [comment]
It would.

**Comment by pkaminski** [comment]
OK, I'll implement it that way.
