### ISSUE TITLE
Should LGTM mark files as reviewed?

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#316]
I frequently `:lgtm:` reviews and publish, then have to go back and click "Mark as reviewed" / Publish to get the "Merge" button to show up.

Doesn't `:lgtm:` imply that I've reviewed all the files?

**Comment by pkaminski** [comment]
I asked this question on Twitter a while ago: https://twitter.com/reviewableio/status/719599761284796416

The feedback was positive but not unanimous, so I'm waiting until I have a spot in the UI to turn this feature off before introducing it.

**Comment by GrayHatter** [comment]
2¢: no, if you assign part x to Alice, and part y to Bob, Alice should be able mark :LGTM: without signing off on anything of part y. (separated by what she has marked as reviewed)

As a part of the discussion I had with my team today; reviewable, required checks, signoffs, etc. should be made easy as they can be, but should also be a little bit painful. I can click "mark all as reviewed, and LGTM" with 3 clicks without ever having seen any of the code already, but that would defeat the point of using reviewable. 

Reviewable exists to help me review and signoff on code, the second it tries to do that job for me is the moment I drop it, and never look back.

**Comment by seanf** [comment]
Perhaps instead of marking files as reviewed (or auto-resolving discussions, for that matter), Reviewable could simply warn the LGTM reviewer that some files/discussions seem to be outstanding.

**Comment by SpainTrain** [comment]
> to get the "Merge" button to show up.

Why not set a custom "review completion condition"?  We have done that to great success (for other purposes).

![selection_250](https://cloud.githubusercontent.com/assets/380032/19787356/3ff6942c-9c70-11e6-9923-969046dc25d1.png)

I'll voice emphatic opposition to this idea.  As noted by @GrayHatter, LGTM and reviewing files are just categorically not the same thing and there are valid use cases for keeping them separate.  I do support @seanf's idea of warning on unreviewed files when posting an LGTM, as it can be an easy thing to miss.
