### ISSUE TITLE
Add "expand whole file" option for each file with hidden code

### ISSUE THREAD

**Issue by bpflanz-adfin** [Reviewable/Reviewable#317]
Sometimes I need fuller context when reviewing a file (such as existent and unchanged values/functions), at which point clicking "Expand" on each elided section one-by-one becomes rather tedious. It would therefore be helpful to have something that allows expanding all such sections for a single file. While my first thought was to have this in the header of the file, it's probably better if it's available no matter how far you've scrolled through the file, so either next to each normal "Expand" or in the floating header.

**Comment by pkaminski** [comment]
This is already available for the (admittedly very discreet) Collapsed dropdown:
![image](https://cloud.githubusercontent.com/assets/1646896/15589133/54352668-2346-11e6-8f8d-37b468d4630a.png)

**Comment by bpflanz-adfin** [comment]
Ah. Sorry I missed that; I should have expected it there given the rest of the UI. Thanks for pointing it out!
