### ISSUE TITLE
Allow adding a file-level comment

### ISSUE THREAD

**Issue by bpflanz-adfin** [Reviewable/Reviewable#318]
Currently I have to associate file-level discussions to a specific file, which implies a misleading context. Examples might be "Why are you removing this file?" or "This whole thing shouldn't exist because the feature already exists in the standard lib." Providing a way to start a file-level discussion would solve this problem most elegantly.

**Comment by pkaminski** [comment]
Please see #26 -- I decided not to address this directly, since the workarounds of adding a comment on an arbitrary line or creating a top-level discussion are sufficient IMO and don't warrant adding new UI for this case.
