### ISSUE TITLE
Box-with-arrow glyph constantly flashes as I type

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#322]
When typing comments on a review, particularly on long reviews, the little box-with-arrow glyph (that you see when pressing command) constantly flashes on/off as I type. I feel like maybe Reviewable is showing the glyph briefly whenever I press any key instead of just when I press command. I'm also wondering if this constantly flashing is a big reason why typing comments in large reviews is extremely slow (to the point where I end up opening a text editor, typing my comment in there, and pasting it into Reviewable).

Similarly, the glyph shows up if I hold shift or control, even though those don't cause links to open in new windows.

This is with Safari 9.1.1 on OS X 10.11.5.

**Comment by kballard** [comment]
Chrome also displays the glyph when pressing shift or control, but I'm not noticing it flashing when I type (and typing is much faster). However, tapping command repeatedly shows that Chrome is, for whatever reason, much faster about showing/hiding the glyph on this huge review, which may explain why I'm not seeing it when typing (because it's hidden again before the window paints) and why typing is much faster.

If it makes a difference, I have animations disabled (in an attempt to increase performance on huge reviews).

**Comment by pkaminski** [comment]
Safari drives me nuts sometimes...  Unfortunately, I'm traveling for the next 3 weeks and left my Mac at home, so won't be able to look into the issue until I get back unless it repros in Firefox or IE.  Sorry.

**Comment by kballard** [comment]
I just saw this happen in Chrome. I was typing a comment on the 3rd revision of a PR and the glyph started flashing as I typed. Not nearly as much as it flashes in Safari, and until now I hadn't seen it flash at all in Chrome. My guess is that it's always been flashing, but that for some reason the show/hide is slower in Safari than Chrome, so most of the time in Chrome you just don't even see it because the window never painted while it was briefly visible.

**Comment by pkaminski** [comment]
Still no luck reproducing this in Chrome/Windows (with explicit code to tell me when the state changes, so it's not just that it's flashing too fast), thus it may be a Mac-specific issue.  This is plausible because I need to sniff the correct keycode for the command key on that platform.

Could you try an experiment?  Load up Reviewable with a `?debug=digest` query param and try holding down a key to repeat in a draft text area (or typing really fast, <100ms between keystrokes).  When you do this, does the little white "light" in the lower-right corner digest overlay blink, or not?  Normally it shouldn't, and if it does that certainly explains the performance problems you've been seeing (though doesn't hint at why it's happening).  Thanks.

**Comment by kballard** [comment]
It blinks, a lot, in both Safari and Chrome.

**Comment by kballard** [comment]
In a review today, Chrome became extremely slow when writing comments too, similar to the behavior I've been seeing with Safari. I was scrolled such that there were no box-with-arrow glyphs on-screen though so I couldn't tell if that was flashing a lot.

**Comment by pkaminski** [comment]
I have a suspicion: does this only start happening after you press a command-key combo while on the Reviewable page, and then later type that key (or keys) in the comment (without holding down command)?

**Comment by kballard** [comment]
Wow, I think you're right. I just opened a new page, opened a new comment, started typing. No flashing. I pressed ⌘A to select everything, then started typing again. Now whenever I press A the glyph flashes, and when I press other keys it doesn't.

I suspect this happens often on long reviews because the simplest way to cancel a comment is to press ⌘A followed by delete (rather than mouse over to the trash can icon), and of course A is a very common character to type in reviews. And I may be typing other cmd keys too, like ⌘T or ⌘N to open new tabs/windows.

**Comment by pkaminski** [comment]
I *may* have just fixed this, but since I don't have access to a Mac for testing at the moment, I may also have broken it even worse.  Could you give it a try please?

**Comment by kballard** [comment]
Looks like you fixed it! Though for some reason in Chrome, pressing Shift still shows the glyph (so typing capital letters makes it flash). I'm not seeing this in Safari, it only shows when pressing Cmd there.

**Comment by pkaminski** [comment]
Yay!  Bare Shift is a valid link click modifier in Chrome, whereas it isn't in Safari (AFAICT from reading random web pages).  The glyph has a short delay before starting to fade in and the fade in cancels as soon as another key is typed (even if Shift is still held down), so in my testing at "normal" typing speed I don't see the glyph appear at all.

**Comment by kballard** [comment]
Huh, you're right, shift-click opens a new window when cmd-click opens a new tab. I never knew that. Of course, I don't use Chrome very much. And based on what you said, I'm probably only seeing the glyph flashing because I turned off animations (which was done in response to the performance issues, so I may turn that back on again now that the cmd key is fixed).
