### ISSUE TITLE
Menubar glitch

### ISSUE THREAD

**Issue by erikwright** [Reviewable/Reviewable#328]
Note the weird white box next to the thumbs-up. It appears to be the diff range control.

![image](https://cloud.githubusercontent.com/assets/187063/15755380/8c65971e-28ca-11e6-89a8-e6d71223952d.png)

**Comment by pkaminski** [comment]
This is working as expected: the diff range controls are lined up against the longest path in the review (presumably you have a file with a path that extends all the way to the range control?), and in the toolbar the range control is simply cut off if it overflows onto the right-hand menu.  Sometimes it overflows at an unfortunate spot that makes it look weird but I can't think of anything to do about that.

**Comment by erikwright** [comment]
Sure. I would have expected it to just not show up until there was enough
space for it or something. Anyway, just a minor glitch.
