### ISSUE TITLE
single, non-auto diff mode is not respected if the column control is too wide

### ISSUE THREAD

**Issue by erikwright** [Reviewable/Reviewable#330]
1. View a diff
2. Set it to manual, single mode.
3. Drag the column bar to some value more than half of the max possible given your window width (160 works for me).
4. Un-toggle "single"

Expected: A side-by-side diff view
Actual: A single diff view.

It was not obvious why it wasn't doing what we wanted. Randomly toggling auto on/off fixes it (auto will decrease the column count to fit):

1. Toggle auto on (you see a side-by-side view with a decreased column control).
2. Toggle auto off (the side-by-side view remains, and the column control keeps its decreased value)

But some more toggling breaks it again:

1. (Starting in auto-off/single-off mode like after the last steps)
2. Toggle auto on
3. Toggle "single" on (you see a unified diff with the original, high column count)
4. Toggle auto off (no change)
5. Toggle single off

Expected: A side-by-side diff view like we saw at the beginning of this sequence (since we have simply toggled each of the controls away from and back to their starting state).
Actual: A single diff view.

We spent several minutes playing with this and it just appeared broken. I was finally able to characterize the behaviour after a few additional minutes of playing with it myself.

**Comment by pkaminski** [comment]
This is working as expected, so merging with #324.
