### ISSUE TITLE
Reloading while reviewing often changes the revision range

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#332]
If I reload while reviewing, Reviewable tends to change the revision range for the current file such that the start is the base and the end is the revision that the comment I was replying to had been made at. For example, I was reviewing a file with the range set to (r5,r8) with my last reviewed version being r5, and I was replying to a comment written on r6. After reload, the revision range was set to (⊥,r6).

**Comment by pkaminski** [comment]
This is likely working as designed, but let's merge this discussion with #329.
