### ISSUE TITLE
Confusing revision ordering for "Review each commit separately"

### ISSUE THREAD

**Issue by erikwright** [Reviewable/Reviewable#335]
Something really weird is going on in the following screenshots.

**"Review each commit separately"** is chosen (and was chosen immediately, before any feedback was received.

The file matrix shows that **base:r1** is selected.

The comment is on a line that was added in **r3**.

The diff for loaders.py shows a span of **base:r1**.

But the diff contents correspond to **r2:r3**.

![image](https://cloud.githubusercontent.com/assets/187063/15830666/a7f3f186-2be7-11e6-8ffc-bd8ffb33cd30.png)

![image](https://cloud.githubusercontent.com/assets/187063/15830679/b5f53484-2be7-11e6-8f6f-9b16a9e85a18.png)

![image](https://cloud.githubusercontent.com/assets/187063/15830693/c855ecd6-2be7-11e6-8c80-a0a54d298279.png)

Notice what it looks like if I manually select **r2:r3**:

![image](https://cloud.githubusercontent.com/assets/187063/15830836/562b4a4c-2be8-11e6-9498-60c2b870e3a8.png)

Finally, I understand what happened:

![image](https://cloud.githubusercontent.com/assets/187063/15830910/bbcefa9c-2be8-11e6-944f-44a1907db613.png)

I had a previous PR, merged to master, but reverted the merge. Then, on my original feature branch, I made the fix. Finally, on a new feature branch, I reverted the original revert and then merged in the fix. So the calendar order of commits is "fix", "revert", "merge". So in fact my change appears in both **r1** _and_ **r3**.

I don't know if this is a useful way to view the diff. Consider that the ultimate goal is to merge to master. So what I'm most interested in is the series of changes to master. What I naively expected to see was two revisions: r1 (the revert-of-revert) and r2 (the fix/merge). In hindsight I see that I needed to structure my tree differently in order to get that result, and perhaps I should have. It would be amazing if the tool did something smarter in this scenario, though.

I submit this mainly as food for thought, as this seems like a bit of an edge case for your UX.

**Comment by pkaminski** [comment]
Picking "Review each commit" mode signals to Reviewable that you take responsibility for keeping the commit history clean and forces it to create one revision for each commit.  If you want Reviewable to exercise discretion about how to structure revisions then you need to leave it in "Combine commits for review" mode.

I can't tell from your description, but if the file in question is identical under r1 and r3, then this may also be related to https://github.com/Reviewable/Reviewable/issues/319.
