### ISSUE TITLE
Review is missing one of the changed files

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#336]
A PR I'm looking at right now has 23 changed files in GitHub, but Reviewable only shows 22 changed files. The review only has one revision, and it completely omits the very first file that GitHub and `git diff --stat` show. The file in question was deleted in the PR, but Reviewable shows the other 7 deleted files just fine.

**Comment by pkaminski** [comment]
I won't be able to investigate without knowing which PR you're talking about, but is it possible that Reviewable decided the first file was renamed?  Look for a "cross-over arrow" icon in the file matrix on a "created" file, and a reference to the missing deleted file in the file's diff section.

**Comment by kballard** [comment]
Ah, that's it! I didn't see the crossover icon before because I'd already clicked the eye button to mark that file as reviewed, and that makes it hard to see the crossover. I also wasn't expecting Reviewable to use different logic for rename detection than GitHub does (which I believe matches the default git rename threshold).
