### ISSUE TITLE
Enable word-selection via double-click

### ISSUE THREAD

**Issue by erikwright** [Reviewable/Reviewable#337]
It would be convenient to be able to do standard word-selection by double-clicking. Currently this will open a discussion.

**Comment by pkaminski** [comment]
Unfortunately, doing so would require changing the UI gesture for creating a comment, or add a 300ms delay to interpreting that click to ensure it's not a double-click.  Given that creating comments is a primary use case for Reviewable I'm not willing to make any compromises on that front.
