### ISSUE TITLE
Should iterate your privacy terms

### ISSUE THREAD

**Issue by Arthraim** [Reviewable/Reviewable#339]
Hi guys 
I don't like your "privacy terms". For privacy repos, I would worry about the safety of my Intellectual properties.
I actually prefer github's: https://help.github.com/articles/github-terms-of-service/#f-copyright-and-content-ownership

**Comment by pkaminski** [comment]
Hey, thanks for actually looking at the policy!  Did you also see the [Terms of Use](https://github.com/Reviewable/Reviewable/blob/master/legal/terms.md), sections 4 and 6, which address your concerns directly?  The way I see it, the privacy policy is more about personal information / data sharing, and the terms more about how we handle your content and IP rights.  Please let me know if you still have concerns about IP after looking at these sections.  Thanks!

**Comment by pkaminski** [comment]
Closing for lack of further feedback.
