### ISSUE TITLE
"drafts" button does nothing

### ISSUE THREAD

**Issue by erikwright** [Reviewable/Reviewable#340]
The drafts button has a red "1" badge.

![image](https://cloud.githubusercontent.com/assets/187063/15868372/94ea26f4-2cb5-11e6-9f62-62abc47c29d7.png)

And there is a draft comment shown under the "Publish" drop-down.

![image](https://cloud.githubusercontent.com/assets/187063/15868409/b5ab3504-2cb5-11e6-836f-9b417b06deaa.png)

But clicking the drafts button does nothing (likewise the comment element in the "Publish" dropdown).

Note that clicking the comment element navigates to a fragment (`#-KJfEQz93gMaGwNJfSdK`) but this doesn't change the view.

The drafts button _does_ work if I change the diff span to include the entire range from base to latest (r5) for all files.

Apparently the discussion that the draft was on is already resolved. Maybe that has something to do with this?

![image](https://cloud.githubusercontent.com/assets/187063/15868507/216996b4-2cb6-11e6-8081-addbde7712d0.png)

**Comment by pkaminski** [comment]
I haven't been able to reproduce this so far; drafts on resolved discussions should work normally.  In the diff configuration where navigating to the draft doesn't work, does the discussion with the draft show up on the page at all?  If so, I can't think of any reason why it wouldn't be navigable...

**Comment by davidmason** [comment]
Similar issue but this is not the drafts button, rather the to-reply button to the left of it.

I had a red 4 next to the to-reply button but clicking it did nothing. When I expanded to include the base revision, I could click to-reply to jump to the comments. All 4 of the comments were on deleted files.

![Comment visible when base revision is included](https://cloud.githubusercontent.com/assets/482026/16550319/8be923e2-41ec-11e6-864f-791b63254236.png)

![Comment not shown when base revision is excluded](https://cloud.githubusercontent.com/assets/482026/16550320/94b8f452-41ec-11e6-8572-73be73d3db46.png)

**Comment by pkaminski** [comment]
@davidmason The instance you found is now fixed.  This turned out to be a problem with discussions that were created on a "elided" file (binary or too long to show) not being mapped correctly when the file was displayed in a line-oriented way (as an empty file in your case).

@erikwright I don't have enough information about your scenario to tell if it was the same problem or not.  Closing the issue for now but please reopen if you observe it again and we can gather more data.
