### ISSUE TITLE
Don't hide single-participant "satisfied" discussions

### ISSUE THREAD

**Issue by erikwright** [Reviewable/Reviewable#341]
Karl's disposition is "Satisfied". Does that mean that I don't even have to look at the comment?

![image](https://cloud.githubusercontent.com/assets/187063/15868757/31a90aae-2cb7-11e6-8037-571f88768eb7.png)

I think his intent was "I want to leave a comment, but I don't expect a response." Instead, I didn't even see the comment (later I discovered it in an e-mail that I had received but not looked at).

What is the way to leave a comment, ensure that it will be seen and ack'd by the PR author, but not require the comment author to return and acknowledge the response/discussion?

**Comment by pkaminski** [comment]
At the moment, marking a comment satisfied when you're the only author on the thread will resolve it *and hide it*.  (This is mentioned in the fine print under the "satisfied" state.)  It was meant as a sort of "never mind" mechanism for discussions that got sent out but had not yet attracted participants.  I agree that the implementation is not ideal, as previously discussed [in chat](https://gitter.im/Reviewable/Reviewable?at=573627230cb634927f7eae0a).

For now, I recommend sending a normal message that starts with FYI, as it'll show up as resolved too but will not be hidden (i.e., will bump the unreplied counter).

I'll use this issue to track fixing the current semantics.  I may either just discard the special "hide discussion" semantics, or do that and add a new way to hide a single-participant discussion post facto (e.g., a "never mind" disposition).

**Comment by erikwright** [comment]
So there is some special handling of messages that begin with FYI?

Is there a list of other similar logic based on message contents?

I'm concerned that correct usage of Reviewable relies substantially on lore.

**Comment by pkaminski** [comment]
No lore, the special prefixes are shown when you create a new empty draft
(and disappear when you start typing).

**Comment by erikwright** [comment]
Hmm. OK, I see it now. The message says "Start with FYI or BTW to bypass".
It's definitely not clear to me what that means.

**Comment by pkaminski** [comment]
I struggled to find a good, short word there -- suggestions gratefully
received.

**Comment by echochamber** [comment]
How about just have a 4th option:
Blocking
Discussing
Satisfied
(FYI/Context/???)

The last one would have the same behavior as Satisfied except not be hidden by default.

**Comment by pkaminski** [comment]
That's pretty much what I have in mind, except that Satisfied will start to behave "normally", and a new disposition (perhaps "Never mind"?) will be usable for hiding a solo-participant discussion.

**Comment by pkaminski** [comment]
Fixed.  The new disposition is called "withdrawn".
