### ISSUE TITLE
`n` keybinding has stopped working

### ISSUE THREAD

**Issue by metajack** [Reviewable/Reviewable#343]
`n` used to take me to the next unreviewed file in the current revision. During https://reviewable.io/reviews/servo/servo/11530 on one of the revisions it worked for the first 3 files then took me back to the first one even though there were still several unreviewed files to go. I ended up doing the rest of the review by scrolling and clicking with the mouse.

**Comment by pkaminski** [comment]
What did the file counter in the toolbar say, and what color was it?  What diff range was selected at the time?

**Comment by pkaminski** [comment]
Ping.  I'll need more information to figure out what might be going on.

**Comment by metajack** [comment]
Sorry, I've been watching for this to happen again so I can get you the info you need. Perhaps it's best to close this, and I'll reopen when I can get you more info.

**Comment by pkaminski** [comment]
OK, closing for now.  If it does happen again, please try to capture as much as possible of the client's state via screenshots, and also try clicking on the counter with a mouse to determine whether the problem is with the keyboard binding or the function.  Thanks.
