### ISSUE TITLE
Top-level replies from Reviewable shouldn't need context in Github's copy

### ISSUE THREAD

**Issue by darkvertex** [Reviewable/Reviewable#344]
Hey,

It seems right now if I reply something simple like "_Looks good._" that I intend to be short and sweet, if replied at the top-level (PR-level) Reviewable still attaches a quote of the last reply from someone else for context.

Now, I can totally understand that when we're commenting in a specific code line, as the Github copy does not appear in the line but at the top level... so that's fine, however if I'm replying AT the top level, I'm just adding to the existing main thread and I don't see a point to the quoting of the last response. It's superfluous.

Can we get rid of context in top-level replies? Or provide a checkbox to disable it ourselves?

**Comment by pkaminski** [comment]
Agreed and removed.
