### ISSUE TITLE
Not all commits appearing in a review

### ISSUE THREAD

**Issue by nox** [Reviewable/Reviewable#346]
https://reviewable.io/reviews/servo/servo/11754

Could this review get reset so that I can review it properly?

**Comment by pkaminski** [comment]
Reset.

**Comment by nox** [comment]
There are 30 commits and I see only r1 and r2. That is still broken to me.

**Comment by pkaminski** [comment]
Argh, I swear there were 30 revisions there, but I forgot to force a snapshot and it got reset back again.  :(  Fixed and snapshotted now, so it'll hold.
