### ISSUE TITLE
Have some common reviewers buckets for team-managed projects

### ISSUE THREAD

**Issue by didrocks** [Reviewable/Reviewable#348]
As discussed yesterday on gitter, let's try to define a spec for this awesome reviewable tool to support more team-managed projects!

Right now, everyone having commit rights on a project would have a red counter as remaining actions as long as they didn't review a particular PR. This is great to ensure that everyone can have a say on every merge.

However, on bigger projects, you want to ensure that no PR is lost if your project gets popular, hence the proposal to have a common bucket for people having access rights.

Basically:
- a PR is considered to not have any pending actions for the whole committer/reviewer team if all files/pending actinos have been reviewed/answered at least by one person of the committer team excluding the author (note here that if the PR author is from the committer team, he isn't considered for this PR as being part of the committer team).
  -> so, the ball in the author's court
- if the above isn't matched, we expect this PR to be in the committer/reviewer team pool.

We can even imagine that projects can tweak their rule, like: we should at least have 2 reviewers fully acknowledge all raised questions and reviewed every diff to consider the PR as mergeable. But this would be an advanced feature :)

**Comment by pkaminski** [comment]
Looking at this with fresh eyes I'm wondering if we could leverage the `pendingReviewers` feature of custom review completion conditions.  If you take a look at https://github.com/Reviewable/Reviewable/wiki/FAQ#can-i-customize-what-makes-a-review-complete, you'll see that you can write a (per-repo) code snippet that determines whether a review is complete and, among other things, optionally lists the users whose action is needed to advance the review.  The default logic looks at review participants, assignees, etc., but you could rewrite it to also know about an arbitrary committer/reviewer team pool.  Then in the reviews dashboard (https://reviewable.io/reviews) I could have special filter terms that select only reviews waiting on the author, or waiting on at least one reviewer (or on an assignee, etc.).  You could bookmark such a view.  What do you think?

**Comment by didrocks** [comment]
I like that idea!

I need to look at the syntax of the custom review completion conditions, but from a quick look, this is something achievable. That way, each project can implement their own conditions like one or more reviewer, using the review participants, assignees and such, one or more full +1 votes from the reviewer team.
I think that would as well help us resolved the kind of issues we are seeing when we raised a point, answered somewhere else (like IRC or gitter), change our vote to ACK it with "OK", but the author never ack the vote change which prevents us to then merge via reviewable?
We can even imagine sharing those in a gist to create some ecosystem around it.

I am a little bit less clear about the reviews dashboard with those special filters. I can see multiple case:
- reviews ready to be merged (review complete from the algorithm and all discussions resolved)
- reviews waiting on the author (review complete, still unresolved discussions, action on author's side)
- reviewing waiting on at least one reviewer (review uncomplete, independent of resolved or unresolved discussions)
- new review (review uncomplete, no discussion raised at all)
So, you may implement those kinds of special filters view that we could bookmark? ^

**Comment by pkaminski** [comment]
> I think that would as well help us resolved the kind of issues we are seeing when we raised a point, answered somewhere else (like IRC or gitter), change our vote to ACK it with "OK", but the author never ack the vote change which prevents us to then merge via reviewable?

That's odd, an "OK" response should not require acknowledgement to resolve the discussion.  Do you have an example where this happened?

> I am a little bit less clear about the reviews dashboard with those special filters. I can see multiple case:
> * reviews ready to be merged (review complete from the algorithm and all discussions resolved)

Aside: a review being complete is independent from discussions being resolved if you're using a custom completion condition.  

> * reviews waiting on the author (review complete, still unresolved discussions, action on author's side)
> * reviewing waiting on at least one reviewer (review uncomplete, independent of resolved or unresolved discussions)
> * new review (review uncomplete, no discussion raised at all)

Note that your custom completion condition could also return some boilerplate `pendingReviewers` in this case.

> So, you may implement those kinds of special filters view that we could bookmark?

As a concrete proposal, consider the following set of filters (all requiring a PR to be open):
* `+needs:review`: review is incomplete
* `+needs:fix`: PR is not mergeable, or other commit check is not successful
* `+needs:merge`: PR is ready to merge
* `+needs:author`: review is incomplete and author is in `pendingReviewers`, or `+needs:fix` is true
* `+needs:reviewer`: review is incomplete and non-author is in `pendingReviewers` or `pendingReviewers` is empty

These could be mixed and matched and the queries bookmarked as usual.  Feedback?

**Comment by pkaminski** [comment]
Ping -- thoughts on my concrete proposal?

**Comment by segfly** [comment]
> That's odd, an "OK" response should not require acknowledgement to resolve the discussion
We've noticed this happening too - I ended up just disabling the check for open discussions. We now go off LGTM alone.

>+needs:review: review is incomplete
+needs:fix: PR is not mergeable, or other commit check is not successful
+needs:merge: PR is ready to merge
+needs:author: review is incomplete and author is in pendingReviewers, or +needs:fix is true
+needs:reviewer: review is incomplete and non-author is in pendingReviewers or pendingReviewers is empty

I like these alot. However, the one I think I would use the most which is missing:
* `+needs:mylgtm:` Open reviews that list me as a pending reviewer

I don't know if that can be acheived with the above, because I'm not quote groking what `+needs:author:` and `+needs:reviewer:` is supposed to do.

**Comment by pkaminski** [comment]
> > That's odd, an "OK" response should not require acknowledgement to resolve the discussion

> We've noticed this happening too - I ended up just disabling the check for open discussions. We now go off LGTM alone.

Would love to dig into it if you happen to have a concrete example.

> I like these alot. However, the one I think I would use the most which is missing:
> +needs:mylgtm: Open reviews that list me as a pending reviewer
> I don't know if that can be acheived with the above, because I'm not quite groking what +needs:author: and +needs:reviewer: is supposed to do.

Yeah, I think `+needs:me` would make sense -- you can't really compose it from the others.

Do you also want a "doesn't need fix" filter, say `+passing`?

**Comment by segfly** [comment]
> Do you also want a "doesn't need fix" filter, say +passing?

Yeah, I think that would be nice when combined with the other filters.
One thought: Instead of new filters, what about allowing negation of existing ones?
`+passing` = `!needs:fix:`

**Comment by pkaminski** [comment]
I had some concerns about negation but worked through them, and settled on `-` as the prefix (so `-needs:fix`).  I implemented all the filters discussed above but _only_ in the forthcoming Vue-model rewrite, as the extra data requirements made it too messy to backport to the current stable version.  This means the feature won't be available until the new version launches, which will still take a while -- sorry!

**Comment by dhbradshaw** [comment]
With the vue model underway, are we ready to revisit this?

**Comment by pkaminski** [comment]
The filters listed above have been implemented for years, but I don't know if this satisfies the original issue raised.  If so, this can be closed.
