### ISSUE TITLE
Show more than just the most recent comment in a discussion on a specific line

### ISSUE THREAD

**Issue by echochamber** [Reviewable/Reviewable#350]
At least the last 2, maybe 3. Most of the time when I am reading the comments on a specific line I'd like to read more than the just the most recent comment so if there was a conversation I could remember the context around it.

**Comment by pkaminski** [comment]
I guess the optimal default depends on a lot of factors (how big the review is, how many reviews you're participating in, how long ago you last looked at the discussions, etc.).  Expanding the full thread is just one click away, though, if you need more context.  What are your thoughts on that?

**Comment by echochamber** [comment]
My thoughts are that when there are multiple comments on a single line of a revision, the newest one is usually a response to the previous one, so just being able to see at least one more comment would be nice more often than not. This is only really ever an issue when I switching between tasks and don't remember the context of the discussion, or if I'm coming back to an open PR after a weekend.

Expanding the comments is one click away, I just think this would be a nicer default :)

**Comment by pkaminski** [comment]
I posted a Twitter poll to gather some anecdata: https://twitter.com/reviewableio/status/747609085957177345

**Comment by echochamber** [comment]
Good idea, left my vote!

**Comment by pkaminski** [comment]
Looks like the majority vote was for 2 comments, and even more importantly 1 (current setting) received no votes.  I'll try bumping up to 2 comments soon and see how it goes.

**Comment by pkaminski** [comment]
Now showing last 2 older comments for all discussions.

**Comment by echochamber** [comment]
@pkaminski Thanks!
