### ISSUE TITLE
Show line numbers in diffs

### ISSUE THREAD

**Issue by echochamber** [Reviewable/Reviewable#351]
Its probably one of the features of GitHub PRs I miss most when using reviewable. Have set up clicking the line number on comments to open the correct line in my IDE, but thats a few extra clicks:

1. Open a comment on a line I don't intend to submit.
2. Click the line number to go to it in my IDE.
3. Trash the comment.

It would be really nice to be able to have line numbers on the diffs and click them to open that line in my IDE. Just showing line numbers would be fine also since I could just manually goto line in my IDE since I usually have the file open already anyway. Or is there a way to already do this I am unaware of?

Thanks in advance!

**Comment by pkaminski** [comment]
Hey, please take a look at the discussion in #147, and add your use case there.  Thanks!
