### ISSUE TITLE
Pressing shift while writing a comment makes the text input lag

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#352]
Pressing and holding shift makes the link icons next to the filenames in the file matrix appear when using reviewable. Releasing shift makes them disappear. However, pressing any other key also makes them disappear, even if shift remains pressed. When writing a comment, every time I write a capital letter there is a palpable delay before it appears - first all the icons appear, then they disappear (since I've already pressed the desired letter), and then the letter appears. This behaviour becomes _really_ annoying if there are a bunch of characters that require alternating between casing in rapid succession.

**Comment by jdm** [comment]
https://reviewable.io/reviews/servo/servo/11727 is an example of a review where I'm experiencing this problem.

**Comment by pkaminski** [comment]
Quick bit of extra info: do you have animations turned on or off?

**Comment by jdm** [comment]
They are turned off.

**Comment by pkaminski** [comment]
Fixed.  A performance issue with the Angular digest was compounded by the lack of a 100ms delay when animations were turned off.  I fixed both, so if you type reasonably quickly you shouldn't see the icon popping up any more.

**Comment by jdm** [comment]
Thank you for addressing it so quickly!
