### ISSUE TITLE
Require status checks for reviews

### ISSUE THREAD

**Issue by dcramer** [Reviewable/Reviewable#354]
I can't see a way to disable the merge button when status checks are unfinished/failing. We configure this in GitHub's settings, and it'd be nice to do the same here.

**Comment by pkaminski** [comment]
If the failing checks are required in GitHub then the merge button shouldn't show.  If they're not required, then the merge button will show but in red.  What's showing up on your screen, and what PR is it for?

**Comment by dcramer** [comment]
https://github.com/getsentry/sentry/pull/3626

**Comment by pkaminski** [comment]
Your protection settings in GitHub exclude admins, you're an admin, ergo you can merge (though the button should be red).
