### ISSUE TITLE
All the acknowledged issues in a review have reappeared and won't disappear

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#355]
Last time I looked at [this review](https://reviewable.io/reviews/servo/servo/11727) three days ago it was behaving as expected. Now all of the issues that I have marked acknowledged or satisfied in the past are appearing in their expanded form - they still show the checkmark that indicates that I've acknowledged them, but they don't shrink.

**Comment by pkaminski** [comment]
Can you get a screenshot?  Also, I think your link is broken.

**Comment by jdm** [comment]
Fixed the link.
<img width="652" alt="screen shot 2016-07-07 at 11 16 34 pm" src="https://cloud.githubusercontent.com/assets/27658/16676524/e48ebd6e-4498-11e6-99c0-dbc82c5fae5f.png">

**Comment by pkaminski** [comment]
Ah, I know what happened.  I recently changed the semantics of "satisfied" disposition for single-participant discussions due to #341.  I didn't announce the change because I didn't think anybody used it more than occasionally -- sorry.  You'll need to switch your disposition to the new "withdrawn" to the the solo discussions resolved.

**Comment by jdm** [comment]
There are several dozen review comments there, and the review is not complete yet. That's really unfortunate :(

**Comment by pkaminski** [comment]
Want me to hack up a quick script to switch all your "satisfied"
dispositions to "withdrawn" on that review?  Any others?

On Thu, Jul 7, 2016 at 8:41 PM, Josh Matthews <notifications@github.com>
wrote:

> There are several dozen review comments there, and the review is not
> complete yet. That's really unfortunate :(
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/355#issuecomment-231268109>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABkhMP8GgbEDU5PXGZClENSi9i5WLdXdks5qTcbzgaJpZM4JHq6L>
> .
>



-- 
Piotr Kaminski, Founder, reviewable.io

**Comment by jdm** [comment]
It seems like this is the only one that would benefit. That would be great!

**Comment by pkaminski** [comment]
Fixed!

**Comment by pkaminski** [comment]
Actually, this made be realized I made a mistake: a solo 'satisfied' should still resolve a discussion, just not make it disappear (i.e., it should still appear as unread to others).  I've made the fix and will push it soon.

**Comment by jdm** [comment]
Thanks!
