### ISSUE TITLE
Some new files are hidden because they have no changes or open comments

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#358]
In https://reviewable.io/reviews/servo/servo/11624 I changed the review to combine all revisions; I do not believe that anybody else had opened it before that. It is now hiding a number of files which are added in the PR, which is not supposed to happen.

**Comment by jdm** [comment]
I just loaded the review again and the problem isn't appearing any more. Very confusing!

**Comment by pkaminski** [comment]
That's odd.  How many revisions were there before you combined?  There's only 1 commit in the PR now, but I can't tell if that's how it always was, or if it got rebased and squashed.  Do you remember what the diff bounds were before you switched review styles?  Did the "show unreviewed diffs" in the Changes box activate after the review style finished switching?  I'm wondering if some diff ranges got stuck with obsolete revision objects and just needed to be refreshed, which is what would've happened when you reloaded the page (among other things).

**Comment by jdm** [comment]
There were at least 10 revisions before I switched it.

**Comment by jdm** [comment]
I think the bounds were showing the very first revision before the switch. I don't know about "show unreviewed diff" unfortunately.

**Comment by pkaminski** [comment]
I added code to force a reset of the diff ranges after the review style change is complete.  I think there's a good chance this will fix the behavior you observed but I can't be sure, since I never managed to repro.  Please reopen if the issue recurs.

**Comment by jdm** [comment]
Thanks!
