### ISSUE TITLE
Support quoting the highlighted block of text in a first comment

### ISSUE THREAD

**Issue by bpflanz-adfin** [Reviewable/Reviewable#359]
It might be worth evaluating whether it's possible (and reasonable) to support quoting a highlighted block of text in a new comment that's started while the text is still highlighted. This behaviour would be like that which is described in the changelog at http://changelog.reviewable.io/5017, but for new comments rather than replies to existing comments.

One approach that occurs to me, is that you could add a keyboard shortcut to create a comment on the first line of a highlighted block. It might be a little strange, that the shortcut - necessarily - can't do anything without the highlighted block, so there are probably better approaches.

**Comment by pkaminski** [comment]
Implemented.  Turns out I needed just a tiny bit of magic to make it work with plain old mouse clicks.
