### ISSUE TITLE
Cannot review own PR

### ISSUE THREAD

**Issue by dannykopping** [Reviewable/Reviewable#36]
In our team, I generally review PRs; however, for transparency, I'd like to be able to review my own PRs, mark files as reviewed and comments, etc. Currently I cannot mark files as reviewed in my own PR.

When I try to use the keyboard shortcut `x` to mark a file as reviewed, the app throws this exception:
`Error: Cannot read property '$revRange' of undefined`

**Comment by pkaminski** [comment]
I saw the exception in my tracker -- I'll fix that shortly.

For comments, you are of course free to comment on your own review, but you won't be able to resolve any discussions.  I think it would actually make sense in general for a commenter to be able to close out their own comment before anybody else has replied so I'll throw that in.

For review marks, I figured that preventing the author from setting them would reduce the potential for confusion.  I could imagine adding a way to override this but I'd want to add some indication of mark ownership to the file matrix first, and I haven't figured out a clean UI for that yet.  Suggestions appreciated.

And I'd just like to add that in my experience it's valuable to have everyone (even junior team members) doing reviews -- not only is it a learning opportunity for them, but they often spot issues that are in the blind spot of a more experienced PR author.  Not that this ever happened to *me* of course!  :wink:

**Comment by dannykopping** [comment]
Maybe this could simply be a config option, and once enabled everything remains the same? I'm assuming you have some simple equality check to enable/disable the review buttons, so this could just short-circuit that

**Comment by pkaminski** [comment]
My threshold for introducing a behavior configuration option is quite high -- they're hard to remove in the future and eventually lead to the dreaded "settings dialog of doom" (see: Eclipse).  I'd rather put in the extra thought to make things "just work" as much as possible.  Besides, knowing who marked a revision as reviewed would be useful in multi-party reviews anyway, so might as well figure out how to do it.

**Comment by pkaminski** [comment]
Two new features are live: resolve your own discussion before anybody else has jumped in, and mark files as reviewed in your own PR (with indicators in the file matrix as to who reviewed what).  This should now let you self-review your PRs -- let me know if anything else is needed.
