### ISSUE TITLE
Reviewable button in Github looks funky

### ISSUE THREAD

**Issue by xiongchiamiov** [Reviewable/Reviewable#364]
I'm seeing this in all pull requests:

![image](https://cloud.githubusercontent.com/assets/23369/16995308/7cce70bc-4e60-11e6-969f-778b521539aa.png)

I have done a hard refresh, but otherwise not looked much into it.

![image](https://cloud.githubusercontent.com/assets/23369/16995460/69702c26-4e61-11e6-909f-d34a3dec9a5b.png)

**Comment by pkaminski** [comment]
Yay for consistent SVG rendering across platforms.  Could you check which of the following fonts you have installed on your machine please?  `Droid Sans, Helvetica Neue, Helvetica, Segoe UI, Arial`  Also, what is your browser's default sans-serif font?  Thanks.

**Comment by xiongchiamiov** [comment]
Droid Sans - ❌ 
Helvetica Neue - ✅ 
Helvetica - ✅ 
Segoe UI - ❌ 
Arial - ✅ 

The default sans-serif is Helvetica.

As far as I know, these are all the standard options for OS X and Chrome, but I wouldn't discount the possibility of me having changed something.

In the inspector, the active font definition is `font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";` - the "computed" tab unfortunately doesn't tell me which one it's actually using.

**Comment by pkaminski** [comment]
Weird, I have the same fonts / settings and similar platform (Chrome 50.0.2661.86 on OS X 10.10.5) but can't reproduce the issue.  I changed the styling from `letter-spacing` to `textLength`, which apparently may be more reliable.  Can you see if that fixed the problem for you?  There's a number of caching layers between you and the image, so you can try hard-reloading it directly from https://reviewable.io/review_button.svg.  (It'll show up huge, that's OK.)

**Comment by pkaminski** [comment]
Ping -- can you verify please?

**Comment by xiongchiamiov** [comment]
Yep, looks good (with just a soft refresh) on both the direct link and in pulls.
