### ISSUE TITLE
remove triple dots in file paths

### ISSUE THREAD

**Issue by justin808** [Reviewable/Reviewable#365]
Please make the path show up without shrinking to use the triple dots driving me nuts, b/c there's extra space and I have to mouse over. Just make it wrap, maybe!

>On Wednesday, July 20, 2016, Piotr Kaminski <piotr@reviewable.io> wrote:
>Ideally, the paths would only contract when they run out of space (and even more ideally, contract only as much as needed), but this gets *really* tricky to implement.  Since long paths often push out the revisions table to the point where many revisions become unreachable, always collapsing them is the safer default.  But definitely open an issue so I remember to tackle the harder problem on day.

**Comment by thockin** [comment]
+1, I really rely on seeing the whole path when I use github

**Comment by justin808** [comment]
@pkaminski How about at least showing the path when files are moved. It's great we have so many keyboard shortcuts, but I have to grab the mouse to see the file name. In fact, can you just put a keyboard handler on showing the path, ASAP?

![2016-08-11_14-13-19](https://cloud.githubusercontent.com/assets/1118459/17609154/ea0408c6-5fcd-11e6-8dfb-3d06987339a0.png)

**Comment by pkaminski** [comment]
What I did instead is to start including the target filename in the rename message.  Hopefully that'll do for now.

**Comment by r3m0t** [comment]
Can you use this to do it? http://stackoverflow.com/a/1841142/177712

**Comment by pkaminski** [comment]
Thanks, but the actual measuring is not the problem -- it's hooking into all the right UI and data events to update the measurements, and not killing performance in the process.  😄

**Comment by pkaminski** [comment]
I was fixing a nearby bug and put this in as a target of opportunity.  It should add/remove the elisions automatically based on available space, number of revisions, etc.  It makes a guesstimate about the line stats width, though, since it would be too expensive to recompute all the time.
