### ISSUE TITLE
squash & merge removes commit descriptions

### ISSUE THREAD

**Issue by pcgilday** [Reviewable/Reviewable#366]
When using the new squash & merge feature (which is great btw, thanks for adding 😄 ), the preview window only displays the commit summaries not the descriptions. This means you have to re-add any useful descriptions that are desirable even after a squash. I believe the desired behavior here would be to leave the summaries and descriptions to allow the user to remove and/or clean up any descriptions that are not desired.

**Comment by pkaminski** [comment]
You're right -- I've changed the behavior to match what GitHub does.

**Comment by pcgilday** [comment]
Thank you, reviewable is a great tool and I really appreciate how quickly you address issues!
