### ISSUE TITLE
Merge is broken

### ISSUE THREAD

**Issue by dcramer** [Reviewable/Reviewable#367]
```
Unable to merge branch: GitHub error 422 on PUT https://api.github.com/repos/getsentry/sentry/pulls/3770/merge: Invalid request. For 'properties/commit_message', {"title"=>"Disable unused frequency sketches", "message"=>""} is not a string.
```

Happens consistently on any PRs I try to merge from the PR list action.

**Comment by pkaminski** [comment]
What kind of merge are you doing?

**Comment by dcramer** [comment]
@pkaminski the reviews list doesnt give me it a choice, it just says "Merge & Retain Branch"

**Comment by pkaminski** [comment]
Thanks, that should be enough context to debug.  BTW, you might want to do your first merge from within the review, as that gives you access to a dropdown with some options.  The choices you make here will become defaults, which are used by the button on the reviews page.

**Comment by pkaminski** [comment]
Fixed.
