### ISSUE TITLE
Unclear error "Failed to publish: Comment changed while rendering markdown."

### ISSUE THREAD

**Issue by SpainTrain** [Reviewable/Reviewable#368]
Every so often when I attempt to publish comments I receive an error "Failed to publish: Comment changed while rendering markdown."  I find this error problematic because

- I am not totally sure what I did wrong (or what was the pathological sequence of events)
- I am not sure what I should do to resolve the situation

Reloading the page and trying to publish again seems to work, but a clearer message and suggested solution would reduce my anxiety about losing my comments.

**Comment by pkaminski** [comment]
Sorry about that -- this is an internal error that's due to some race condition I haven't managed to track down yet.  I'd love to figure out how to fix it but in the meantime I'll add an "internal error" annotation to prevent confusion.

**Comment by SpainTrain** [comment]
Gotcha.  Thanks!

Is there anything I could do on my end to collect helpful debug data?

**Comment by pkaminski** [comment]
Actually, I had a bit of an epiphany and realized that a number of apparently random issues had a common cause in a corner case of Firebase transaction semantics.  I devised a workaround and these errors (and some others, that were normally hidden from users) will no longer show up.
