### ISSUE TITLE
Allow expand/collapse all comments.

### ISSUE THREAD

**Issue by mmlb** [Reviewable/Reviewable#37]
Would be nice.

**Comment by pkaminski** [comment]
That's easy enough to add, but can you explain your use case?  The discussions track your last-read comment and collapse as soon as you acknowledge, so they should generally show you what you need.  If that's not the case then I'd really like to understand how the mechanism is failing you.  Thanks!

**Comment by mmlb** [comment]
hey @pkaminski sorry for not responding earlier, it seems your question was buried under other notifications.

So, its mostly to be able to go back and expand all comments so that I can find something that was mentioned earlier and may have forgotten. And once you allow "expand all", "collapse all" should also be an option.

Since using reviewable a bit more for past 3 weeks, it would also prefer for hidden comments to not be on its own line. There are times when I want to take a look at the full-diff one a review with many comments throughout the diffs, having a line breaking up the diff to note a hidden comments breaks my reading flow. I can break this out into another issue if you want, but it is kind of related.

**Comment by pkaminski** [comment]
Thanks Manuel, that makes sense.  Would a review-wide search function (that reaches into collapsed comments) also satisfy your use case, or do you need the browsability of being able to see all the text?

Hiding resolved comments also makes sense but it is somewhat separate -- could you open up a new issue please?

I'll probably end up implementing both features, just need to figure out a non-intrusive UI for them and how to keep the page scrolled to the same relative position as everything reflows...

**Comment by mmlb** [comment]
hmm, not sure if review-wide search would be useful to me personally. having a keyboard shortcut for expand/collapse and then `Ctrl-f` works just fine :wink: 

Actually just made me think of also expand/collapse for diff too.

Will post new issue for hiding comment.

**Comment by pkaminski** [comment]
Added show/hide all comments from a small drop-down menu in the comment header.  Didn't try to prevent the page from scrolling, though.

**Comment by yselivonchyk** [comment]
Is there a screenshot of how to use this feature by any chance?

**Comment by pkaminski** [comment]
Hey @yselivonchyk, we actually redesigned and improved this feature since 8 years ago (!).  You can see a bit of how it works now in this [changelog post](https://changelog.reviewable.io/improved-discussion-navigation-247347).  Let me know if that helps!
