### ISSUE TITLE
Failed to publish: Markdown rendering throttled

### ISSUE THREAD

**Issue by joey-si** [Reviewable/Reviewable#370]
When trying to publish a batch of 138 comments the first time, I ran into the following issue:

![image](https://cloud.githubusercontent.com/assets/19915552/17314344/74d88228-5818-11e6-9635-06d07f8b89df.png)

It seems like the only solution is to individually publish comments, which results in 138 distinct emails. Is there a solution to this, such as a way to add comments in batch per-file?

**Comment by pkaminski** [comment]
Nah, it's not that bad.  What happens is that Reviewable tries to render comments in the background, as you're working on the review.  Sometimes this doesn't work or it gets behind for some reason, in which case it will catch up when you publish.  If there are many comments and a lot weren't pre-rendered then the publish will fail with the error above, but it'll make progress each time you try.  So just keep hitting Publish every minute or so and everything will go out eventually.

This situation occurs only once every few months (across all Reviewable users) so it's quite rare.

Let me know if you're still seeing the error after 3-4 such attempts, as there might be something else going on, though.
