### ISSUE TITLE
Bad redirect between repositories

### ISSUE THREAD

**Issue by ebullient** [Reviewable/Reviewable#372]
We did that thing you're never supposed to do (for reasons, we swear).

But this PR: https://github.com/gameontext/gameon-room-nodejs/pull/4 gets redirected in reviewable to this: https://reviewable.io/reviews/gameontext/nodejs-room/4, which is a different repository.

**Comment by pkaminski** [comment]
"Reasons", eh?  I heard that one before...  Actually, I said that one before...  :)

Fixed, and updated the code to deal a little bit more gracefully with rename cycles.

**Comment by ebullient** [comment]
Thank you! =)
