### ISSUE TITLE
Round-robin github accounts

### ISSUE THREAD

**Issue by xarg** [Reviewable/Reviewable#373]
Initial discussion: https://twitter.com/humanfromearth/status/758954066374381569

It would be nice to have a way to use multiple accounts to access github's API thus circumventing the API rate limits.

**Comment by pkaminski** [comment]
This is becoming a common enough problem that I'll probably add this soon-ish.  The backend implementation is pretty simple but I need to think through the UI design, and how this interacts with connecting/disconnecting and repo settings multi-save.  One idea would be to have a pool of repo admin volunteers at the organization level and bring them in when the primary connector's quota has fallen below a given threshold, perhaps only for PR sync operations as those are an order of magnitude more expensive (in terms of API calls) than any others and have non-trivial overhead anyway.

**Comment by xarg** [comment]
Any updates on this?

**Comment by pkaminski** [comment]
Yep, I've prototyped a fix and will start testing it in production tomorrow.  When quota gets low (or there's a chance we'll hurt burst quotas / abuse detection), it will automatically distribute the workload to other repo admins that have also signed into Reviewable so it should be pretty much transparent.

**Comment by pkaminski** [comment]
Looks like it's working.  I'm still trying to get burst quota overruns under control but the admin pooling is doing its job as far as the main quota is concerned.
