### ISSUE TITLE
Occasionally comments disappear from Reviewable UI

### ISSUE THREAD

**Issue by david-german-tri** [Reviewable/Reviewable#374]
In this Reviewable post to GitHub containing comments from @amcastro-tri, you can see a comment that begins "This could be inferred from a call..."

https://github.com/RobotLocomotion/drake/pull/2970#issuecomment-236210243

@liangfok replied to that comment in Reviewable.  His remarks begin with "That `0` is concerning".  Reviewable posted @liangfok's reply to GitHub, and that post proves that @amcastro-tri's comment was visible in Reviewable at that point in time:

https://github.com/RobotLocomotion/drake/pull/2970#issuecomment-236212618

However, @amcastro-tri's comment is _no longer_ visible in Reviewable, leading to confusion:

https://reviewable.io/reviews/RobotLocomotion/drake/2970#-KNrEMSiEPmxehXcgVNd

**Comment by pkaminski** [comment]
Unable to reproduce -- both comments show up in Reviewable for me:
![image](https://cloud.githubusercontent.com/assets/1646896/17383813/d500f7fa-598c-11e6-819a-10465b9fdf0c.png)
Can you attach a snapshot of what you see to compare?  Thanks.

**Comment by david-german-tri** [comment]
Huh.  I can now see both comments in Reviewable as well.  That was definitely not true this morning, but I no longer have an old tab to screenshot.  ¯\_(ツ)_/¯

Thanks for taking a look!  I'll let you know if I see something like this again.
