### ISSUE TITLE
Perceptible pause before new comment textareas are focused

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#375]
This means that I often end up invoking keyboard shortcuts for the main reviewable interface when I start typing comment text after clicking on a line to leave a new comment on it.

**Comment by jdm** [comment]
This might actually be caused by another issue I've noticed, where a new comment field appears, the disappears for a short period of time, then reappears.

**Comment by pkaminski** [comment]
There is indeed a short delay before a new discussion draft opens but it should be <300ms (+300ms animation time, if you have those turned on).  I haven't been able to reproduce the comment field "bouncing" as you describe.  Can you specify the review you see this happening on (as review size can affect digest cycle time, and hence the delay), as well as the browser and OS you see it happening in?  Thanks.

**Comment by pkaminski** [comment]
A couple more questions:  Did this start happening in the last couple days?  Subjectively speaking, how good is your network connectivity / latency?

**Comment by jdm** [comment]
The review I saw this on was https://reviewable.io/reviews/servo/servo/12700, using the Firefox 50 nightlies, and this only started happening in the past few days. The network I'm using is not particularly great.

**Comment by pkaminski** [comment]
I haven't been able to reproduce this yet, including in Firefox 50.0a2 and with animations turned on or off.  I also tried in Chrome with network throttling turned on to GPRS-equivalent (i.e., painfully slow) but nothing untoward happened.  (I don't see a way to artificially throttle the network in Firefox.)

To test a hypothesis, could you turn on `Firebase.enableLogging(true)`, create a new discussion, and send me the resulting console output?  (By email just in case there's private stuff in there.)  Thanks.

**Comment by jdm** [comment]
I emailed the log to support@reviewable.io.

**Comment by pkaminski** [comment]
Thank you, the log clarified what's going on.  I'm researching a fix.

**Comment by pkaminski** [comment]
Fix deployed.  I'm pretty sure it'll fix this issue, the only question is whether it'll cause any other ones...
