### ISSUE TITLE
Comments are disappearing.

### ISSUE THREAD

**Issue by JanisGruzis** [Reviewable/Reviewable#376]
When I write multiple comments (last time it was 42) only some were left after publish (8 comments). This happened 3 times in span of 2 days. All times i didn't go afk or did anything weird. Cant 100% repeat this behavior.

**Comment by pkaminski** [comment]
Uh-oh, this sounds really bad, but I'll need more details to figure out what might be going on.  Do you mean that, when hitting publish, many of the drafts are deleted but corresponding published comments don't appear in Reviewable?  Or do the drafts stay and just not get published?  Do those comments show up in the GitHub message that gets sent out?  Can you point me to a review where this happened?  Thanks.

**Comment by pkaminski** [comment]
I just deployed a fix for #375 that might affect this issue too.  Please let me know if you're still seeing the problem or if it (appears to) have gone away.  Thanks.

**Comment by pkaminski** [comment]
Actually, I just rewrote some key parts of the publishing code, and I'm confident this bug is fixed.  Apologies for not catching this earlier!
