### ISSUE TITLE
Suggestion: Show the PR author if someone is mid-review

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#378]
I'd love it if the PR author could see if someone is in the process of writing a review. That way they can hold off merging it if someone else already approved it (since the review-writer's feedback is probably valuable). It might be useful to show this to everyone, but the PR author seeing it is by far the most important.

It's also probably useful to show how long ago the in-progress review was last modified. For example, if I start drafting a comment on a PR, then forget about it, 3 days later the PR author shouldn't still be waiting for me to publish my review. This could be an exact time, or it could just be a few buckets like "less than half an hour ago", "less than 24 hours ago", "older than 24 hours".

**Comment by pkaminski** [comment]
I like this idea -- I'll add it to the queue.

A related feature request that's in my queue is to notify users by email if they've had unsent drafts pending for more than N hours, which would help reduce the number of stale drafts.

**Comment by kballard** [comment]
Bump.

I just had a coworker merge a PR while I was in the middle of reviewing it, because I had already acknowledged her response to my older comments (thus resolving them), but hadn't yet published the new review. Because the button went green on her screen, she just went ahead and merged it (it went green because a coworker LGTM'd it separately).

**Comment by jwnimmer-tri** [comment]
FWIW, in our project's use of reviewable, we have it enforce an "all assignees must post an LGTM before merge" rule.  So if I start a review, I make sure I'm an assignee; then it can't merge until I post my LGTM.

**Comment by kballard** [comment]
We have our custom review conditions set up so that if a PR has assignees, they must all LGTM. But we don't generally use assignees, so that doesn't really help.

**Comment by pkaminski** [comment]
This is now implemented in the beta, showing whether somebody has pending drafts (of any kind) and how long ago they last interacted with the review.  (The location and layout isn't great, but it'll do for now until a bigger UI do-over.  Also it only reports on people using the beta version for the time being.)  And #510 (coming soon) should take care of the "acknowledge before reply" problem accidentally resolving discussions prematurely.
