### ISSUE TITLE
Reviewable badge injected into my pull request comments w/o permission

### ISSUE THREAD

**Issue by cohart** [Reviewable/Reviewable#38]
Hi guys, I've never installed or heard of reviewable until Friday, when this script...
```
<!-- Reviewable:start -->
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ad60/grupo-ml-rails/7)
<!-- Reviewable:end -->
```
...started to appear in the comments of every pull request I make. I never signed up, installed, or authorized reviewable to have access to my github account. So where is this coming from??

**Comment by pkaminski** [comment]
Hi Colin, sorry to hear you're having trouble with Reviewable especially as you didn't sign up for it.  However, @logicdevil did and connected a bunch of ad60 repos including grupo-ml-rails -- so it's not your PRs that are being targeted specifically but rather all PRs in those repos (thanks to logicdevil's admin powers).  They're probably trying out Reviewable for ad60 to improve the PR code review process for ad60.  I'd love to hear any feedback you might have if you decide to give it a try too!  Thanks.

**Comment by cohart** [comment]
@pkaminski Thanks for all the info! Was quite startled when the badge just started appearing!

**Comment by pkaminski** [comment]
NP, hope you guys can work it out -- would love to have you on board.  BTW, the information about who connected a repo is available on the Reviewable Repositories page, but you need to sign up to view it.  :stuck_out_tongue:
