### ISSUE TITLE
Consider adding alt-text to buttons

### ISSUE THREAD

**Issue by erikwright** [Reviewable/Reviewable#380]
One of my colleagues suggested that it would be helpful to show an alt-text when hovering over icons.

I like that there is detailed help available with the `F1/?` thingy, but maybe just having (for example) "Send Now" on the appropriate icon would be useful. On the other hand, the detailed help message does give more context which might otherwise be missed.

**Comment by pkaminski** [comment]
Most icons have alt text (for accessibility) but I'm purposely staying away from hover tooltips.  I think having multiple ways to get help would be confusing and popups on active elements get annoying in a hurry once you do know the UI.
