### ISSUE TITLE
Repositories list never shows up?

### ISSUE THREAD

**Issue by larsbergstrom** [Reviewable/Reviewable#382]
I've been trying to visit:
https://reviewable.io/repositories#

In order to enable reviewable on the servo/webrender GitHub repository.

But, the page never completes loading. I've tried both on Firefox and Chrome. Is there a trick?

**Comment by pkaminski** [comment]
No trick, though if you have a lot of repos it can take a while to fully initialize.  Can you show me where it gets stuck for you, and perhaps also see what's going on in the Network pane?

**Comment by larsbergstrom** [comment]
Console says:
```
raven.js:703 GET https://api.github.com/user/orgs?access_token=7066c7d2e0c057dcde524986da86e40a0c0d3fdf&per_page=100&_nocache=462878 403 (Forbidden)(anonymous function) @ raven.js:703m.end @ superagent.js:1157q @ hubkit.js:199(anonymous function) @ hubkit.js:145c.Promise @ hubkit.js:14j.request @ hubkit.js:143i.fetchOrganizations @ connector.js:46a.fetchRepositories @ repositories.js:79(anonymous function) @ repositories.js:201g @ angular.js:4718j.instance @ angular.js:10375n @ angular.js:9284g @ angular.js:8641(anonymous function) @ angular.js:8500link @ angular-route.js:1063(anonymous function) @ angular.js:1247ra @ angular.js:9955n @ angular.js:9356g @ angular.js:8641(anonymous function) @ angular.js:8500(anonymous function) @ angular.js:8865d @ angular.js:8658m @ angular.js:9406k @ angular-route.js:1012$broadcast @ angular.js:18026(anonymous function) @ angular-route.js:652g @ angular.js:16404(anonymous function) @ angular.js:16420$eval @ angular.js:17703$digest @ angular.js:17516c.$digest @ fixes.js:12$apply @ angular.js:17811c.$apply @ fixes.js:22(anonymous function) @ angular.js:1761g @ angular.js:4718g @ angular.js:1759ea @ angular.js:1779(anonymous function) @ reviewable.js:6k @ jquery.js:3094fireWith @ jquery.js:3206ready @ jquery.js:3412g @ jquery.js:3428
extensions::uncaught_exception_handler:8Error in event handler for (unknown): SyntaxError: Unexpected token u in JSON at position 0
    at chrome-extension://boamfheepdiallipiieadpmnklbhadhc/hotkeyListener.js:1:80
```

And here are two images (from chrome):
<img width="557" alt="network" src="https://cloud.githubusercontent.com/assets/475847/17501238/81e5ec8c-5da2-11e6-8d33-6d4502308378.png">
<img width="551" alt="console" src="https://cloud.githubusercontent.com/assets/475847/17501239/81e67d5a-5da2-11e6-94bd-24f3fe7aab08.png">

**Comment by larsbergstrom** [comment]
<img width="551" alt="console" src="https://cloud.githubusercontent.com/assets/475847/17501255/b51ffba6-5da2-11e6-8df0-89745338f0e9.png">

**Comment by pkaminski** [comment]
Thanks, though you really didn't want to publish your access token.  You'll want to revoke it in GitHub ASAP and sign in to Reviewable again.

The API query failure is normal, and the syntax error is in some extension you're running.  Maybe try with extensions turned off?

**Comment by larsbergstrom** [comment]
Yeah, I'd noticed after uploading the image and already revoked/re-added it.

I've tried with no extensions in both Chrome and Firefox. Hrm.

**Comment by pkaminski** [comment]
I'll dig around after dinner...  Can you attach a screenshot of what the stuck page looks like, and a list of the scopes you have authorized (from the account dropdown)?  Thanks.

**Comment by larsbergstrom** [comment]
<img width="1411" alt="pagescopes" src="https://cloud.githubusercontent.com/assets/475847/17501961/75448482-5da9-11e6-9d3c-d15d207efedc.png">

**Comment by larsbergstrom** [comment]
The spinner just spins forever...

**Comment by pkaminski** [comment]
Gah, this is what happens when you put a parenthesis in just the wrong place, and inadvertently remove the error handler...  Thanks JavaScript.  Fixed.

**Comment by larsbergstrom** [comment]
Great, thanks! It worked fine for us now.

On Aug 8, 2016, at 9:42 PM, Piotr Kaminski <notifications@github.com> wrote:

Gah, this is what happens when you put a parenthesis in just the wrong
place, and inadvertently remove the error handler... Thanks JavaScript.
Fixed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Reviewable/Reviewable/issues/382#issuecomment-238437814>,
or mute the thread

**Comment by ThomasMldr** [comment]
@larsbergstrom As a sidenote, this error:

> extensions::uncaught_exception_handler:8Error in event handler for (unknown): SyntaxError: Unexpected token u in JSON at position 0
    at chrome-extension://boamfheepdiallipiieadpmnklbhadhc/hotkeyListener.js:1:80

is caused by the [EasyReader](https://chrome.google.com/webstore/detail/easyreader/boamfheepdiallipiieadpmnklbhadhc) chrome extension.
