### ISSUE TITLE
Line width wrapping seems slightly broken

### ISSUE THREAD

**Issue by sherm1** [Reviewable/Reviewable#385]
We use a standard 80-character line and the Reviewable viewer knows that. But it seems to be wrapping at 78 characters leading reviewers to think line lengths have been exceeded. I'm seeing this in Chrome, with side-by-side diffing, and very wide windows with plenty of space. (I haven't tried it in other configurations.)

**Comment by pkaminski** [comment]
Hmm, that's odd.  Could you post a screenshot of a line that reaches or exceeds the wrap point (to show how many characters fit), along with the margin settings popup that shows the margin width setting, and the user settings dropdown that shows any font customizations you may have made?  Thanks.

**Comment by sherm1** [comment]
Here is the 78-character line that wrapped with the margins popup showing:
![image](https://cloud.githubusercontent.com/assets/4088016/17540271/a838a72c-5e69-11e6-926f-7adfd4d2763c.png)

**Comment by sherm1** [comment]
Is this the dropdown you meant:
![image](https://cloud.githubusercontent.com/assets/4088016/17540319/00b21082-5e6a-11e6-917a-624f30ad26f9.png)

The syntax highlighting URL is: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/styles/vs.min.css

**Comment by pkaminski** [comment]
Thanks, reproduced and fixed.  It turns out I wasn't using the right calls to get fractional pixel values when computing the line width necessary for a given font / margin setting.

**Comment by sherm1** [comment]
Thanks, @pkaminski. Should I be seeing that change already? I'm still seeing wrap-at-78.

**Comment by sherm1** [comment]
Never mind -- seeing the fix now. Thanks!

**Comment by sherm1** [comment]
I thought I saw this fix, but on closer inspection Reviewable had auto-set the line width to 100. I dragged it back to 80 and it still seemed to be wrapping at 78.

**Comment by pkaminski** [comment]
I assume you reloaded the page?  Are you still seeing the issue on the same line?  Here's what my repro looks like for me:
![image](https://cloud.githubusercontent.com/assets/1646896/17568887/94f8ab58-5efa-11e6-839b-fcfdfa1c6d1e.png)

Can you check the width of that line in your browser?  It should be set to 555.438px, not 555px.  Thanks.

**Comment by sherm1** [comment]
Just saw this in a review I'm doing:
![image](https://cloud.githubusercontent.com/assets/4088016/17573639/9ca6192e-5f10-11e6-8c42-0c88660533c1.png)

The wrapped line is exactly 80 characters:
```
  // auto& input_vector = input_port.get_vector(context); // where the return is
12345678901234567890123456789012345678901234567890123456789012345678901234567890
```

I don't know how to check line width in Chrome -- please advise.

**Comment by pkaminski** [comment]
Thanks for the new repro; fixed.  It turns out that even though Chrome reports a given width for an unconstrained line, sometimes if you set the line to exactly that width it'll wrap anyway.  I added 0.1px of extra space when computing the width to compensate, but we're now firmly into the realm of guesses and workarounds so please let me know if you spot any further discrepancies.

**Comment by sherm1** [comment]
Thanks, @pkaminski -- looks good now.
