### ISSUE TITLE
Black "long line" dashes appear on every line

### ISSUE THREAD

**Issue by ggould-tri** [Reviewable/Reviewable#386]
(possibly specific to Chrome?)

See attached screenshot:  Even lines that are not long still show the http://changelog.reviewable.io/7245 style black dashes.

![screenshot from 2016-08-12 10-33-11](https://cloud.githubusercontent.com/assets/17596413/17626008/59546314-6079-11e6-9a18-c4dd4bdc3422.png)

**Comment by pkaminski** [comment]
Arrgh, sorry about that.  Could you please let me know your OS, browser (and version), and any font customizations made in Reviewable (account dropdown)?  Thanks.

**Comment by ggould-tri** [comment]
Ubuntu 16.06, Chrome:
```
50.0.2661.102 (Developer Build) Ubuntu 16.04 (64-bit)
Revision	496034c629901db4564ba5613e2d736635eeb082
OS	Linux 
```
Account dropdown:
![screenshot from 2016-08-12 15-20-21](https://cloud.githubusercontent.com/assets/17596413/17634388/5cb250c6-60a0-11e6-8f00-eb2d5a0e1859.png)

**Comment by pkaminski** [comment]
Is Chrome v50 the latest for Ubuntu?  I have v52 running on Windows and OS X here.  If v52 is available could you try upgrading to it please?

**Comment by ggould-tri** [comment]
Good call.  I updated to `51.0.2704.79 (Developer Build) Ubuntu 16.04 (64-bit)` and the problem now seems gone.

**Comment by liangfok** [comment]
I'm still observing this problem using OS X 10.11.6 and Safari 9.1.2:

![screen shot 2016-08-12 at 4 48 05 pm](https://cloud.githubusercontent.com/assets/1388098/17636715/fedcf8f4-60ac-11e6-9613-a3d741ba6e1c.png)

I will now check to see if I need to update the browser.

**Comment by liangfok** [comment]
According to Apple's App Store, I am running the most recent version of the OS X and Safari.

**Comment by pkaminski** [comment]
Thanks for the heads-up, I implemented a workaround for Safari's bug -- should be fine now.

**Comment by liangfok** [comment]
Thanks! I confirm the problem's gone on my OS X / Safari.
