### ISSUE TITLE
FR: better Go context

### ISSUE THREAD

**Issue by thockin** [Reviewable/Reviewable#387]
Hit this one today.  Similar to how type definitions were before (thanks) this did not show a hint of the indent context.

This code:

```
options := vol.VolumeOptions{
    Capacity:                      claim.Spec.Resources.Requests[0],
    AccessModes:                   claim.Spec.AccessModes,
    PersistentVolumeReclaimPolicy: api.PersistentVolumeReclaimDelete,
    CloudTags:                     &tags,
    ClusterName:                   ctrl.clusterName,
    PVName:                        pvName,
    PVCName:                       claim.Name,
}
```

Only the last line was a diff, so what I saw was:

```
    CloudTags:                     &tags,
    ClusterName:                   ctrl.clusterName,
    PVName:                        pvName,
    PVCName:                       claim.Name,
}
```

It would have been neat if the hint at this section said `options := vol.VolumeOptions{`.  In fact, maybe the hint could always show the most recent line that was less-indented, or something?

**Comment by pkaminski** [comment]
@mmlb, do you have an opinion on this?  Also see #283.

**Comment by sasha-s** [comment]
showing the most recent line that was less-indented would work well in many cases: switch, for loops, if statements, structs.
the only case I know where is it less clean, is a multi-line return statement, something like
```go
return a,
    f(x),
    c,
    d
```

**Comment by pkaminski** [comment]
Wouldn't it end up showing the `} else {` in an else clause, though?

**Comment by thockin** [comment]
I'd call that a very minor failing

**Comment by mmlb** [comment]
@pkaminski my opinion is that you should try to match whatever git shows. This allows one to correlate diffs in git command line with reviewables and avoid having to reinterpret diffs between review/feedback and local revs due to said feedback.

**Comment by thockin** [comment]
yeah, on further consideration, if I am in an "if", I am in a function, and
I'd rather see which function I am in than the "if" condition.  at the file
scope, showing var definitions is still attractive

**Comment by pkaminski** [comment]
I think having different logic inside vs outside functions would just create more confusion, though.  Plus that would require more work than just tweaking the regex so I don't think it's worth it.
