### ISSUE TITLE
Repository settings multiple repos dropdown z-order issue

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#388]
The multiple repositories dropdown in repository settings is showing up behind a bunch of the settings instead of showing up over everything. Notably, the text of the condition function and review state, and the line number bar of the review state, show up over it, which makes it really hard to read most of the repos.

I'd attach a screenshot except nearly all of these repos are private repos.

This occurred with Safari 9.1.2 on OS X 10.11.6 (15G31).

**Comment by pkaminski** [comment]
Thanks, fixed.
