### ISSUE TITLE
Provide more context in messages sent out when hitting Publish

### ISSUE THREAD

**Issue by thockin** [Reviewable/Reviewable#39]
From a discussion by email:

If I were offering requirements I'd say something like:

1) Email sent for every review/response pass, but not each individual comment (unlike GitHub)

2) Email sent to all related parties, including the author of the response (unlike GitHub which omits the author)

3) Email has enough quoted material to be useful without going to web UI - e.g. comments quote the code, responses quote the comment (unlike GitHub)

4) Well-formatted responses to email get back integrated to the comments (github does reasonably well here, but mangles quoted material)

5) Certain phrases carry meaning - e.g. "ACK" with no other content == acknowledge.  This is mostly for clean integration with the reviewable "acknowledge" feature.

**Comment by pkaminski** [comment]
1) is already in place, 2) is not feasible, and 4)/5) is #63.  Renaming this issue to cover 3) -- provide more context in the emails.

**Comment by pkaminski** [comment]
New comments now quote 3 lines of immediately preceding code, and responses quote the previous message (unless the response includes quotes itself).
