### ISSUE TITLE
IntelliSense for code reviews

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#390]
This would be hard to implement but could also be a great feature and differentiator for Reviewable.

For languages that support it, it would be great if I could hover over a symbol and get type information and documentation (e.g. Javadoc/jsdoc) about it, just like you would in an IDE. This would greatly aid the reviewer in understanding the code.

Implementation-wise, this would probably require some sort of integration with your continuous integration system, i.e. you'd have to build the project and send type information to Reviewable.

**Comment by pkaminski** [comment]
Yeah, this would be awesome but would be hard to bring off.  I'd probably try to integrate with Sourcegraph's API first since this is the exact problem they're trying to tackle.

**Comment by xarg** [comment]
Seems Sourcegraph made a chrome extension for this kind of stuff. Would be great to see an integration with Reviewable.

https://chrome.google.com/webstore/detail/sourcegraph-for-github/dgjhfomjieaadpoljlnidmbgkdffpack?hl=en

**Comment by pkaminski** [comment]
Closing in favor of #519.
