### ISSUE TITLE
Highlights for changes not visible

### ISSUE THREAD

**Issue by peluse** [Reviewable/Reviewable#391]
This looks like it may be an issue with some setting on my system or monitor but I wanted to see if anyone had any suggestions or if this is happening to anyone else.  I have a MacBook Pro running the latest OSX on bare metal and Win10 in a parallels VM. I use the retina display and have an external 34" ultrawide LG connected via thunderbolt. With one exception, it makes no difference whether I use Windows or OSX, Safari, Chrome or Firefox I can't see the highlighted red/green changes. Every once in a while, yeah this is strange, when I use IE in Windows with single view I can see them clear as day. Sometimes though, that doesn't work. I was thinking it was the LG but I also have the problem on the built in retina display.
Is anyone aware of some magical setting somewhere? (I've played with all the monitor controls, contrast, brightness, color, etc., as well as the OS color settings)
-Paul

**Comment by pkaminski** [comment]
Wow, that sounds really weird.  One idea: can you take a screenshot of some diffs (e.g., at https://reviewable.io/reviews/Reviewable/demo/1) and post it here?  This would let us determine if it's a hardware or software issue.

**Comment by peluse** [comment]
Tell me about it :) So just now single/unified worked on Chrome but still not side by side.
 2 screenshots uploaded.  Thanks for the quick response!

<img width="1649" alt="wide" src="https://cloud.githubusercontent.com/assets/4650360/18067485/e96b5f68-6df1-11e6-9cd7-b1bc912d95e7.png">
<img width="1032" alt="single" src="https://cloud.githubusercontent.com/assets/4650360/18067486/e96c8d7a-6df1-11e6-94b1-66d1c8b4f2d2.png">

**Comment by pkaminski** [comment]
Ah, that's not a bug, that's a feature.  :wink:  In side-by-side mode, only the actual deltas are highlighted because the role of the line (add/remove) is implied by which side it's on.  See https://github.com/Reviewable/Reviewable/wiki/FAQ#can-i-customize-how-the-source-code-is-displayed (search for "diff lines with edits to be highlighted in two-column mode") for how to override this.

**Comment by peluse** [comment]
AWESOME, thanks!!!
