### ISSUE TITLE
⌘V no longer pastes

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#396]
Starting recently, pressing ⌘V no longer pastes text into comments. It actually works sometimes, but most of the time it doesn't work. The Edit menu is highlighted but nothing happens. Curiously, if I use my mouse to select Edit->Paste, that works. Similarly ⌥⇧⌘V for Paste and Match Style doesn't work either.

I started noticing this yesterday. However, I was on vacation for the week prior, so this could have started any time in the past 10 or so days.

I'm using Safari 9.1.3 on OS X 10.11.6.

**Comment by pkaminski** [comment]
Sorry about that, it's likely due to a recent update to the paste-handling library.  Could you please quickly check if you can reproduce at http://gh-pages.micy.in/paste.js/?  Thanks.

**Comment by kballard** [comment]
In the first two fields on that page, pastes work just fine (though manually selecting Paste doesn't trigger the event, but pressing ⌘V does). In the third content-editable field, if the field has contents, pasting works. If the field is empty, pasting does nothing (but in this case, even manually selecting Paste does nothing).

In Reviewable, the pasting is broken regardless of whether there's contents or not. Although very rarely it works. For example, I just tried it in a comment, and after hitting paste quickly 4 times in a row one of them worked, but then trying another 30 pastes did nothing.

**Comment by pkaminski** [comment]
Fixed, by disabling the custom paste handler on Safari.  Since Safari doesn't support pasting in images anyway it wasn't adding any value there.  Some days it really feels like Safari is taking on IE's mantle...
