### ISSUE TITLE
Indicate aggregate commits' object size, not just net lines changed

### ISSUE THREAD

**Issue by jwnimmer-tri** [Reviewable/Reviewable#399]
Consider the following:
1. Developer (accidentally) commits large binary files to their branch, along with (intended) source edits.
2. Developer commits the removal of the large binary files from their branch, but leaves the older commits that added them intact; in other words, nothing got squashed.
3. Developer submits PR.
4. Reviewers LGTM on the source edits.  Nobody notices the binary files in the commit history.
5. PR gets merged (not using squash, per project conventions).

At this point, I believe that master will contain history that includes large binary data, which makes cloning slow and everyone sad, and nobody happened to notice.

I wonder if there is a way for reviewable to help prevent this?

For example, somewhere near the "File Matrix", it could show the total size of all commits in the branch, instead of just the net-lines-per-changed-file?

**Comment by pkaminski** [comment]
Interesting challenge -- thanks for the use case!  As far as I can tell, though, GitHub doesn't provide data about total size of all commits and computing this in Reviewable would get super expensive for larger reviews.

But another idea might be to include files that delta away from and back to the base between captured revisions in the file matrix, whereas normally they get discarded.  They'd qualify as "obsolete files" and be hidden by default, though, so it might not be helpful in preventing oversights.

It may also be the case that this scenario is sufficiently rare that after-the-fact removal (e.g., with `bfg` https://help.github.com/articles/removing-files-from-a-repository-s-history/#removing-a-file-added-in-an-older-commit) is a reasonable approach.

Thoughts?

**Comment by jwnimmer-tri** [comment]
Thanks for the response.  I agree this is a bit rare, and certainly there are other ways to prevent it.  I would say I was curious if review could be one tool in the basket, but it sounds like it would be challenging, given the APIs.

Tracking "obsolete files" could be a minor win, but once the PR is iterating, reviewers are already likely to see the changes in real time, so I won't put too high a value on that enhancement.

Though I wonder, does github tell us if they are are binary or large files somehow?  It seems that reviewable knows not to show me diffs for them.  Perhaps that information is enough to call it to our attention somehow?

In any case, if this is difficult, I am fine to close the enhancement request.  I am likely to want a git hook in any case, so warn developers up-front if they are heading down a dangerous path.

**Comment by pkaminski** [comment]
> Tracking "obsolete files" could be a minor win, but once the PR is iterating, reviewers are already likely to see the changes in real time, so I won't put too high a value on that enhancement.

It would work on the first revision too, tracking "obsolete" files that had diffs and reverted back to base before the first revision was snapshotted.  But still, the reviewer would have to go looking for them, so I agree it would be a minor win at best.

> Though I wonder, does github tell us if they are are binary or large files somehow? It seems that reviewable knows not to show me diffs for them. Perhaps that information is enough to call it to our attention somehow?

The current heuristics rely on fetching the file contents, but basic size information is also available in the git trees fetched server-side while Reviewable is constructing revisions.  Typically, trees only get fetched for commits at the head of each revisions, not the intermediate ones that are bundled inside (in aggregate commits mode), but combined with the idea above of scanning all commits it could provide the information necessary to prominently call out "large abandoned files" in the UI.

The caveat, though, is that Reviewable aggregates commits in part to reduce the workload on the servers.  Sometimes people create PRs with hundreds of commits, and fetching the full repo tree metadata for each would be prohibitively expensive, both in CPU time and your GitHub API quota.  So if I implemented the feature above it wouldn't work reliably -- and in fact might fail precisely in the cases where it would have been most useful.

**Comment by jwnimmer-tri** [comment]
Alright, from my point of view this is okay as-is.  Thanks for the discussion!

I'll look into enforced interlocks at other points of our process.
