### ISSUE TITLE
Make hidden comments completely unobtrusive.

### ISSUE THREAD

**Issue by mmlb** [Reviewable/Reviewable#40]
Split out from discussion in #37 

I was thinking an icon on the file-tab with number of comments, possibly using colors to mark un-replied/acked comments.

**Comment by pkaminski** [comment]
Just to clarify: you only want resolved comments (ones that get collapsed down to a single line) to be hidden, right?  I think hiding unresolved ones is too dangerous...

**Comment by mmlb** [comment]
Actually no. I'd settle for that, but would rather be able hide all comments at my discretion.

I'd like to be able to go into _zen mode_ when reviewing diffs, once I've read a comment I want it out of my way without first having to handle the comment. Having it blocking the code is getting in the way of me reviewing the code/comment when the comment has broader implications than just what is on the line.

Hiding comments may seem dangerous but what is most important is the code and being able to follow it at all times. Hiding the code is more dangerous.

Sorry for continually expanding the issue, the irritation this issue causes me is one of those back-of-the-mind things that only gets defined when actually looking at it.

**Comment by pkaminski** [comment]
Great, thanks for clarifying -- that's why I like to take the time to work out what's really needed first. :smile:  I'll give this some thought and hopefully come back with an idea...

**Comment by mmlb** [comment]
Great, thanks.

**Comment by pkaminski** [comment]
Resolved discussions are now automatically collapsed into a small marker in the gutter, which can be clicked to expand them.  Note that when first resolving a discussion it will stay inline in the code, to make it easier to reopen if you closed it accidentally, but all further views of the file (or rediffs) will show the marker instead.

#94 will track the bigger feature of being able to hide unresolved discussions .
