### ISSUE TITLE
`-@<username>` not removing assignee

### ISSUE THREAD

**Issue by SpainTrain** [Reviewable/Reviewable#402]
At some point the functionality for removing a PR assignee using `-@` syntax quick working for us.  Regardless how many comments I make with the directive, the user is not removed from the PR.

Possible confounding factor: my username has capital letters, which has tripped up other apps before (including even Github's `hub` app).

LMK if I can provide more useful info.  Thanks!

**Comment by pkaminski** [comment]
Thanks for the precise report!  You nailed both the timing (bug introduced in late July) and the cause (case-sensitive regex).  Fixed.

**Comment by SpainTrain** [comment]
If only I could do that for my own code :laughing: 

Thanks for the blazing fast turnaround! :tada:
