### ISSUE TITLE
Cannot use "<...>" in review comment

### ISSUE THREAD

**Issue by oasisfeng** [Reviewable/Reviewable#406]
The "<...>" inside review comment is completely erased. How can I input "<...>" in comment?

**Comment by pkaminski** [comment]
Comments are written in Markdown, which is a superset of HTML, so any `<tags>` are interpreted as HTML elements (and deleted if they're not on a safe whitelist).  You can however escape them in a number of ways:
```
  \<foo\>
  `<foo>`
  ```<foo>```
```
