### ISSUE TITLE
Incorrect PR branch status

### ISSUE THREAD

**Issue by SpainTrain** [Reviewable/Reviewable#407]
For the past week or so Reviewable has been incorrectly reporting that PR branches are out-of-date with target branch and cannot be merged.  It seems to get resolved after some amount of time (though we haven't payed close enough attention to comment on latency).

Apologies if this is a GH issue, but https://status.github.com/ reports no issues.

**Comment by SpainTrain** [comment]
As an additional note, the UI in GH reports the correct state of the branch vis a vis target branch

**Comment by pkaminski** [comment]
Could you point me to a couple PRs that are currently in this state so I can investigate?  I recently fixed the logic determining whether a fast forward merge is possible, and that's also used in determining if a branch is out-of-date (since GitHub doesn't provide this property directly via the API).  Chances are that it's too aggressive and I need to figure out a better out-of-date condition.

**Comment by SpainTrain** [comment]
Currently this one is https://reviewable.io/reviews/homezen/hz-web-api/278

**Comment by pkaminski** [comment]
Thanks -- for comparison, do you also have a PR that GitHub agrees is out-of-date?

**Comment by SpainTrain** [comment]
https://reviewable.io/reviews/homezen/hz-webapp/2038

**Comment by pkaminski** [comment]
Thanks.  I've reached out to GitHub support since there's no apparent difference between these PRs in the API results and my previous guesses clearly aren't working out.

**Comment by SpainTrain** [comment]
Thanks!

**Comment by pkaminski** [comment]
I've updated the status logic based on my conversation with GitHub.  I'm still not 100% convinced it's correct, though -- can you let me know if you spot any more state mismatches this week?  Thanks.

**Comment by SpainTrain** [comment]
It has been looking good so far.  We will keep and eye out and let you know if we see this issue again.

/CC @pcgilday

**Comment by pkaminski** [comment]
I'm going to assume this is fixed!

**Comment by SpainTrain** [comment]
> I'm going to assume this is fixed!

It certainly appears to be :smile_cat: 

Thanks again!
