### ISSUE TITLE
Keyboard shortcut for Publish?

### ISSUE THREAD

**Issue by elliotchance** [Reviewable/Reviewable#408]
Sometimes reviews only take a few seconds because there are no serious changes since the last review. Since using the mouse takes *so* much time, it would be great if there was a keyboard shortcut for Publish.

**Comment by pkaminski** [comment]
I'm not going to bind one be default due to the risk of accidental publication, but the command is available for binding.  See https://github.com/Reviewable/Reviewable/wiki/FAQ#can-i-customize-the-key-bindings.
