### ISSUE TITLE
No way to collapse expanded diffs

### ISSUE THREAD

**Issue by mmlb** [Reviewable/Reviewable#41]
Keyboard shortcuts for exapand/collapase would be nice too (`zR` and `zM` anyone? :smile:  )

**Comment by pkaminski** [comment]
Yeah, it would be nice, but unfortunately this one's not going to happen any time soon: the expansion mechanism mangles the data structures and DOM in such a way that selectively re-collapsing portions of the diff would be extremely difficult.  It's a trade-off I needed to make to avoid spending weeks just on this algorithm.  A workaround is to re-diff (switch diff bounds away and back) to get back to the original collapsed state.

**Comment by mmlb** [comment]
sounds good, F5 works too :D
