### ISSUE TITLE
Removed file appears as "Empty file"

### ISSUE THREAD

**Issue by zvictor** [Reviewable/Reviewable#411]
We have files that were deleted in our repository but reviewable doesn't make it clear, leading to confusion.

The only indicator that it was deleted is a red background color in the respective revision.

It should:
- show an indicator similar to the "renamed file" one.
- state "File removed" instead of "Empty file"

![screen shot 2016-10-20 at 11 30 26](https://cloud.githubusercontent.com/assets/181076/19554381/a210666e-96b8-11e6-8349-f1209ffe24e7.png)

**Comment by pkaminski** [comment]
Agreed.

**Comment by pkaminski** [comment]
This got implemented a long time ago, I just forgot to close the issue.

**Comment by zvictor** [comment]
thank you =)
