### ISSUE TITLE
Font highlighting for CMake code

### ISSUE THREAD

**Issue by jwnimmer-tri** [Reviewable/Reviewable#413]
Would it be possible to add font highlighting for files named `CMakeLists.txt` and `*.cmake`?  In particular, having `#` comments be colored would be a big win for us.

**Comment by pkaminski** [comment]
Sure, as long as you can identify the https://highlightjs.org/ language definition to use (or add one to the project).

**Comment by jwnimmer-tri** [comment]
I think https://github.com/isagalaev/highlight.js/blob/master/src/languages/cmake.js is what we want (shown in their online demo under misc/CMake).

**Comment by pkaminski** [comment]
Cool, I'll add the mappings to tonight's release.

**Comment by jwnimmer-tri** [comment]
Thanks!

I asked around and apparently `*.cmake.in` should also receive this treatment.

**Comment by pkaminski** [comment]
Released.  Please verify, since I had to introduce new kinds of mappings (full filename, two-dotted extension) to make it work.

**Comment by jwnimmer-tri** [comment]
Works on CMakeLists.txt and foo.cmake:
https://reviewable.io/reviews/robotlocomotion/drake/3939

Works on foo.cmake.in:
https://reviewable.io/reviews/robotlocomotion/drake/2407

LGTM, thanks!
