### ISSUE TITLE
Allow editing of reviewer comments after publishing

### ISSUE THREAD

**Issue by sherm1** [Reviewable/Reviewable#416]
GitHub permits PR review comments to be edited later. Because review comments are frequently referenced both during review and after a PR is merged, it can be important to correct mistakes or add clarifications or cross references later. When I make comments in Reviewable I can edit their GitHub translations but those do not get reflected back into Reviewable. Since we use Reviewable extensively most of our archival reference go back to Reviewable, not to GitHub, so the changes aren't seen.

Please consider providing a post-Publish editing capability for Reviewable comments.

**Comment by pkaminski** [comment]
Reviewable doesn't allow editing comments as a matter of principle (see https://github.com/Reviewable/Reviewable/issues/225), but you can always follow up with corrections irrespective of the state of the PR.  Is that sufficient, or are you having trouble with this workflow?

**Comment by sherm1** [comment]
Maybe you could make this configurable? Not all of us value the Principle of Immutability to the same degree. For us, with reasonable social restrictions, it would be better to allow modification. However it is only a minor annoyance so please put it low on your todo list if you decide to accommodate us.

**Comment by pkaminski** [comment]
I understand, and I'm generally in favor of social rather than formal restrictions, but in this case the assumption is wired pretty deeply into Reviewable -- for one, it avoids having to deal with two-way reconciliation of edits.  I'm going to keep the design opinionated for this one, sorry.
