### ISSUE TITLE
Imported GitHub comments can't be acknowledged

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#417]
A review with a bunch of existing comments was recently imported into Reviewable. It managed to map almost all of the comments, which is great. 4 of the comments already had replies, so I want to acknowledge the replies to resolve the comments. I can hit Acknowledge and it appears to work. But if I come back to it later (e.g. if I reload the review), the comments have reverted to their original state, un-acknowledged and un-resolved.

Manually setting my disposition to Satisfied seems to work though.

**Comment by pkaminski** [comment]
Hmm, could be the comment timestamp getting reset during sync, though obviously that's not supposed to happen.  As usual, could you please point me at a concrete example or two?  Thanks.

**Comment by kballard** [comment]
postmates/courier-ios#561 is where I encountered it, but I already manually marked those comments as Satisfied because I needed to move the review forwards.

**Comment by pkaminski** [comment]
I wasn't able to reproduce the issue with the following steps:
1. User A creates a PR.
2. User B creates a new line comment in GitHub.
3. User A replies to the line comment in GitHub.
4. User B acknowledges the discussion in Reviewable.
5. User B (or A) reloads the page.
The discussion remained resolved.

I also poked around the data for postmates/courier-ios#561 a bit and everything looked normal.  For example, the discussion on line 3699 of the `.pbxproj` file would (should?) remain resolved even if your disposition were "discussing".

I'm gonna need more data to investigate this one.

**Comment by kballard** [comment]
Actually, looks like the issue is still happening. The PR author replied to a bunch of the comments (on Reviewable) earlier, and I acknowledged all of them, but now when I look at the PR again, the discussions are still open and I'm marked as Not OK.

The discussion you mentioned is one where I manually set myself to Satisfied. Try looking at the discussion on line 82 of NSError+WebService.m. I just acknowledged it, confirmed that the discussion was resolved, and reloaded. When the page reloaded, it showed up as resolved for a few seconds, and then suddenly that (and the other comments I'd already acknowledged) automatically re-opened themselves and I was set back to Not OK for them.

**Comment by kballard** [comment]
I'm going to leave the referenced comment alone, but I'll be manually marking myself as Satisfied on all other comments in the PR (that I would otherwise acknowledge).

**Comment by pkaminski** [comment]
Thanks, I'll look right now and let you know when I'm done.

**Comment by pkaminski** [comment]
This should now be fixed.  Thanks for helping me figured out what was going on!
