### ISSUE TITLE
Review Summary comments don't seem to be mapped

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#418]
I recently imported a GitHub review that had existing comments (made with GitHub's new review feature). One of the reviews had a review summary included, but Reviewable doesn't seem to show that _anywhere_. It's not even in the top-level discussion.

The review in question is postmates/courier-ios#561.

**Comment by pkaminski** [comment]
Unfortunately GitHub doesn't currently offer an API for the new reviews feature.  They recently added a webhook for related events but oddly enough no way to access the data directly, which is what Reviewable (also) needs to integrate.  https://developer.github.com/changes/2016-10-11-pull-request-review-webhooks/

**Comment by r3m0t** [comment]
@pkaminski the information is already available through the GraphQL API.

**Comment by pkaminski** [comment]
@r3m0t Yes, I know.  I have two concerns about using GraphQL in this case:
1. GraphQL is read-only, and I think it might be confusing to have integration only in one direction.
2. GraphQL is on GitHub's long-term roadmap so it'll probably be a long time before it shows up in GitHub Enterprise, which I also need to support.

Neither of these are deal-killers, but given that a REST API is supposed to be coming "soon" I think it's worth waiting for a little longer at least.

**Comment by pkaminski** [comment]
The API is [now available](https://developer.github.com/changes/2016-12-14-reviews-api/) and I'll do my best to integrate it soon, though due to holiday commitments it might take a couple weeks.

**Comment by pkaminski** [comment]
So, uh, this issue sorta got lost for a bit.  😅  But it's fixed now, as part of a major push to integrate tightly with GitHub PR reviews.
