### ISSUE TITLE
Draft background image aliasing is janky, hurts legibility, on some versions of chrome and safari

### ISSUE THREAD

**Issue by lukeasrodgers** [Reviewable/Reviewable#419]
chrome
![screen shot 2016-10-28 at 12 04 51 pm](https://cloud.githubusercontent.com/assets/816444/19946209/c9c0c7a6-a119-11e6-923b-0359f371c88c.png)

safari
![screen shot 2016-11-02 at 4 36 57 pm](https://cloud.githubusercontent.com/assets/816444/19946492/af6907b4-a11a-11e6-8113-7b1e55d32e79.png)

Occurs on:

* Chrome Version 54.0.2840.71 (64-bit), osx 10.11.6 el capitan
* Chrome Version 56.0.2907.0 canary (64-bit), osx 10.11.6 el capitan
* Safari Version 10.0.1 (11602.2.14.0.7), osx 10.11.6 el capitan (not as bad as chrome)

Looks fine:

* Firefox 49.0.2, osx 10.11.6 el capitan
* Opera 41.0.2353.46, osx 10.11.6 el capitan

**Comment by pkaminski** [comment]
I believe this should be fixed now.  I think it's an engine bug in rendering very light-colored text; switching to a darker color then reducing it again via opacity appears to work better.  Amusingly, Google Drive previews exhibit the same issue, so it's probably not specific to Mac OS!

**Comment by lukeasrodgers** [comment]
Looks fixed to me, thanks!
