### ISSUE TITLE
Unable to sign in to GitHub

### ISSUE THREAD

**Issue by BrianFarnhill** [Reviewable/Reviewable#421]
Currently I don't seem to be able to sign in to GitHub to do my reviews. Have tested in Edge 39 and IE 11 and get the same result.

Repro steps:
1. Browse to https://reviewable.io
2. Click "Sign in to GitHub"

Expected result: Return to reviewable as authenticated user, no longer seeing the "sign in" button
Actual result: The sign in button is still there and I'm treated as unauthenticated

Looking at the JavaScript console I see a few messages about the security certificate not being secure:

    SEC7133: The security certificate protecting this url is insecure : https://status.github.com/api/last-message.json?callback=angular.callbacks._0

There are a few references like that to other URLs as well, but other than that I don't see anything. Let me know if you need me to do any other debugging.

**Comment by pkaminski** [comment]
Hey Brian, I'm not able to repro this with the latest code in Edge 38.14393 or IE 11.321.14393.  Could you help by starting signed out on the home page and capturing the requests on the Edge debugger's Network page?  There should be a series of redirects like so:
https://reviewable-prod.appspot.com/auth
https://github.com/login/oauth/authorize
https://reviewable-prod.appspot.com/auth/callback
https://reviewable.io

Knowing how far this sequence progresses should give me an idea of where to dig.

Also, can you check what your cookie policy settings are?  I only use first-party cookies during sign-in so they shouldn't be a problem, but missing cookies are one thing that could result in an apparent no-op.

**Comment by BrianFarnhill** [comment]
@pkaminski Typical, I go to record it and now it's signing in fine! Urgh - thanks for getting back so quickly. I'll close this one.
