### ISSUE TITLE
Invalid markdown in a Reviewable comment screws up the GitHub comments

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#422]
A coworker put invalid markdown into a Reviewable comment, making the comment end with an unterminated code block (specifically, he accidentally put a stray "x" at the end of the closing code fence). This caused the GitHub comment for that review to degenerate into garbage (the rest of the GitHub comment's formatting was rendered as code instead), and it caused my reply to also be garbage (specifically, it caused the `</details>` to not be interpreted as an HTML tag, so the rest of the GitHub comment was hidden behind a disclosure triangle).

Offhand I'm not really sure how to fix this besides running your own Markdown parser to detect unterminated code blocks and inserting a terminator yourself.

The PR in question is postmates/getitnow-ios#1310.

**Comment by pkaminski** [comment]
I found the discussion and comment in question but AFAICT the comment's HTML was rendered correctly, with `</code></pre>` closing things off at the end.  The reply also looks perfectly normal.

Can you check whether the discussion is rendered correctly in Reviewable?  If so, this sounds like a bug with GitHub's web site renderer instead.

**Comment by kballard** [comment]
The problem is on GitHub, not Reviewable. But the problem is that on GitHub you use a single comment that contains all of the Reviewable comments (which is of course by design), but that single comment uses the original markdown from the Reviewable comments rather than pre-rendered HTML versions. So, for example, here's the tail end of the comment that Reviewable left on GitHub for my coworker's review:

<pre>
*[GetItNow/Classes/Models/Contact.swift, line 176 at r1](https://reviewable.io:443/reviews/postmates/getitnow-ios/1310#-KWDZ78BuQUEL9gZNOp9:-KWDZ78BuQUEL9gZNOpA:b-uatjwt) ([raw file](https://github.com/postmates/getitnow-ios/blob/5a06ccf4c8363b3aeeda79939d2982e2ed3f049b/GetItNow/Classes/Models/Contact.swift#L176)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>         func compare(_ a: (Contact, CLLocationDistance), _ b: (Contact, CLLocationDistance)) -> (Contact, CLLocationDistance) {
>             return b.1 < a.1 ? b : a
>         }
>         return allContacts.lazy.flatMap(getDistance(contact:)).reduce1(compare)?.0
</details>

BTW I feel like using `min` would be slightly more readable:

```
        func getDistance(contact: Contact) -> (Contact, CLLocationDistance)? {
            let distance = MKMapView.distance(from: contact.coordinate(), to: location.coordinate)
            return distance < 75 ? (contact, distance) : nil
        }
        func compare(_ a: (Contact, CLLocationDistance), _ b: (Contact, CLLocationDistance)) -> Bool {
            return a.1 < b.1
        }
        
        return allContacts.lazy.flatMap({ getDistance(contact: $0) }).min(by: compare)?.0
```x

---

*[GetItNow/Classes/Models/Item+Helpers.swift, line 14 at r1](https://reviewable.io:443/reviews/postmates/getitnow-ios/1310#-KWDa-pMtegQJgC8ZIby:-KWDa-pN7AsG92ljMPox:bzdazv6) ([raw file](https://github.com/postmates/getitnow-ios/blob/5a06ccf4c8363b3aeeda79939d2982e2ed3f049b/GetItNow/Classes/Models/Item+Helpers.swift#L14)):*
> group.sortedOptions()!

Is it safe to force unwrap here? `sortedOptions()` depends on `OptionGroup.productOptions` being non-nil. I understand that an `OptionGroup` without any `productOptions` is semantically incorrect, I'm just wondering if we can ever get one in the wild like that.

If that would never happen, we should consider updating `OptionGroup+PMShared.h` with nullability annotations. Looking at it, it seems that we should be able to just blanket-wrap it with `NS_ASSUME_NONNULL`.

---

*[ObjectiveCLibs/Postmates/Model/OrderPricing.swift, line 72 at r1](https://reviewable.io:443/reviews/postmates/getitnow-ios/1310#-KWDZyXSRZwATkDHFzWX:-KWDZyXTrHjq4UclAU9_:b-k2wmuv) ([raw file](https://github.com/postmates/getitnow-ios/blob/5a06ccf4c8363b3aeeda79939d2982e2ed3f049b/ObjectiveCLibs/Postmates/Model/OrderPricing.swift#L72)):*
> ```Swift
>             let taxAmount = max(subtotal, .zero).multiplying(by: taxRatePercent)
>             self.taxAmount = taxAmount
>             let serviceFee = max(subtotal, .zero).adding(taxAmount).adding(merchantFees).multiplying(by: serviceFeePercent)
> ```

BTW lol

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/postmates/getitnow-ios/1310)*
<!-- Sent from Reviewable.io -->
</pre>

Notice how it has the incorrect <code>```x</code> intact in the comment, and if you render this snippet with a markdown renderer, you'll see the entire rest of the comment is stuffed into the code block.

**Comment by pkaminski** [comment]
Ah, I understand now.  This should be alleviated once GitHub ships the new review API that ought to allow posting multiple individual comments in a batch.  In the meantime, if AFAICT code blocks are the only Markdown "mode" that can get stuck, I could probably make a super-simple line-oriented parser that just looks for that syntax.

**Comment by kballard** [comment]
I can't think of any other syntax that can get "stuck" besides code fences. Everything else I can think of is either inline markup, or requires continual effort on each new line to maintain the mode.

**Comment by pkaminski** [comment]
This should now be fixed.  I did my best to figure out what makes for valid code fences but nobody ever accused Markdown of being overspecified, so it's likely I missed some edge cases.

**Comment by luxurystorecc1** [comment]
Duke City Drive: Navigating Albuquerque’s Diverse Sporting Landscape
Albuquerque is a city of high altitudes and high energy, where the gear needs to perform in thin air and intense sun. From the Balloon Fiesta Park to the university courts, the demand for resilient gear is constant. For sneaker collectors in the 505, [iconic silhouette basketball sneakers for street style](https://www.jordan1s.com/) provide the necessary performance and iconic southwestern appeal.

Football remains a cornerstone of the local sporting scene in New Mexico. Fans frequently search for [affordable authentic-style pro football jerseys](https://www.cheapnfl-jerseys.com/) to wear during games under the desert sky. To protect from the high-altitude UV rays, [adjustable team logo basketball caps](https://www.cheapnfl-jerseys.com/collections/headwear-nba-headwear) are an essential gear item for every resident spending time outdoors.

Technical Performance and Desert Quality
The lifestyle of Albuquerque is centered around the outdoors and active living. Professional casual wear, specifically [premium moisture-wicking casual apparel](https://www.peter-milla.com/), is highly sought after for its versatility. For post-hike or post-training recovery, [premium slip-on designer athletic slides](https://www.yeezyboost-350.com/) offer the perfect blend of comfort and modern design.

The soccer community is growing rapidly in the Southwest, with fans opting for [official national team soccer kits](https://www.soccerjerseysstore.com/collections/national-teams). Swimming is a critical part of the local recreation culture, requiring [designer performance swimwear and accessories](https://www.swim-outlet.com/) for athletes at all levels.

For formal events in the city’s historic plazas, a [vibrant red cocktail dress for formal guests](https://www.swim-outlet.com/collections/dresses-red) is a seasonal favorite. For summer weddings, [stylish white bridal and formal dresses](https://www.cheapdressesformal.com/collections/dresses-white) are always in demand. Baseball fans show their pride with [fitted professional baseball league hats](https://www.cheapnfl-jerseys.com/collections/headwear-mlb-headwear), while the local hockey spirit ensures [official league-certified hockey apparel and gear](https://www.custombaseball-jerseys.com/) is a winter must-have.
