### ISSUE TITLE
Put "Reviewable" button in a new comment in GitHub rather than editing the commit message

### ISSUE THREAD

**Issue by jgraham** [Reviewable/Reviewable#424]
An admin on a repo I contribute to just turned off reviewable because he found it annoying that reviewable's edit to the first comment (/commit message) in a PR races with editing the comment for typos. If reviewable simply added a new comment rather than editing an existing one this annoyance would be gone.

**Comment by pkaminski** [comment]
This feature is now available and can be turned on at the admin's
discretion, subject to the trade-offs mentioned above.

**Comment by pkaminski** [comment]
Sorry, forgot to link to canonical issue: https://github.com/Reviewable/Reviewable/issues/397
