### ISSUE TITLE
Crash with Firebase update PERMISSION_DENIED error

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#425]
I withdrew one of my comments on a review, but the PR author replied to the comment anyway. When I went back to Acknowledge it, I got a crash with the following text:

> Firebase update(/reviews/-KWoXkLSrE_9BPHgZcTL/tracker/-KX7h1DccOKhYUr1zGUN/participants/github:714): PERMISSION_DENIED: Permission denied

This is 100% reproducible with this comment. The comment in question is https://reviewable.io/reviews/postmates/getitnow-ios/1324#-KX7h1DccOKhYUr1zGUN

**Comment by kballard** [comment]
After I manually changed my disposition back to Discussing, I was able to Acknowledge the comment.

**Comment by pkaminski** [comment]
Thanks Kevin, the exception was captured -- looks like a logic / security rules bug.  With the details you provided it ought to be a simple fix but I'm currently traveling and won't be able to get to it until EOW.

**Comment by pkaminski** [comment]
This should now be fixed.  Acknowledging a `withdrawn` discussion will retain the disposition.
