### ISSUE TITLE
Explanation for disabled option not discoverable

### ISSUE THREAD

**Issue by edmorley** [Reviewable/Reviewable#427]
Broken out from #397.

**STR:**
1) Open the repository settings page for a public/free repo (eg https://reviewable.io/repositories#edmorley%2Ftreeherder)
2) For the `Reviewable badge` option, hover over the disabled `None` setting.

**Expected:**
Tooltip appears explaining why it's disabled.

**Actual:**
No tooltip.

Instead, I have to perform the following hard to discover steps for finding the reason:
1) Press "F1"
2) Press "h" to enable part of screen selection
3) Click on the option in question
-> "None.     No badges at all (pri­vate re­pos only)."

Note: Step 2 is needed only if there are new features that are being shown - though for beginners this is likely.

**Comment by pkaminski** [comment]
Hmm, it's not meant to be this hard...  When hovering over `None`, you should be able to hit `F1` (or `h`, your choice) and immediately get the relevant help blurb with no further keys or clicks.  Furthermore, if you've never clicked in the option group (or accessed the help), the `F1/h` tooltip should pop up next to your mouse pointer and be available for clicking (otherwise it shows up in the lower-right corner of the screen, to reduce annoyance).

Are you experiencing something different?

**Comment by edmorley** [comment]
> Hmm, it's not meant to be this hard... When hovering over None, you should be able to hit F1 (or h, your choice) and immediately get the relevant help blurb with no further keys or clicks.

It wasn't obvious to me that I could hover over the "None" and that that would cause F1 to jump to the correct place. The workflow that is most common for apps/webapps is that you can just hover over an item and not have to press anything.

> Furthermore, if you've never clicked in the option group (or accessed the help), the F1/h tooltip should pop up next to your mouse pointer and be available for clicking (otherwise it shows up in the lower-right corner of the screen, to reduce annoyance).

I first used Reviewable something like a year ago, took a break and now presuming it's not showing as much help as it did before.

**Comment by pkaminski** [comment]
Thanks Ed, that's good feedback.  The canonical issue for tooltip support that documents my objections is #53.  I'll close this issue for now as things are working as expected, but it's not the first time I've heard this complaint and @mdevs5531 is working on the next major UX update so we'll be sure to take this into consideration!

**Comment by pkaminski** [comment]
Make that @mikesokolsky instead.

**Comment by edmorley** [comment]
Ok thank you :-)
