### ISSUE TITLE
TypeError: Cannot read property 'role' of undefined

### ISSUE THREAD

**Issue by GodCoder** [Reviewable/Reviewable#428]
When I click the Acknowledge btn every time...

**Comment by pkaminski** [comment]
I accidentally introduced a bug last night for a couple hours, but it's fixed now.  Can you please reload the page and try again?  Thanks.

**Comment by pkaminski** [comment]
I thought this was fixed but apparently the deploy with the fix failed silently.  😢 Redeploying...

**Comment by pkaminski** [comment]
I believe this should be really fixed now.  It was an unfortunate overlap of backwards-incompatible authentication in an underlying command-line tool, and `set -e` not existing the deploy process for some reason.
