### ISSUE TITLE
Reviewable Crashes When Acknowledging Comments - TypeError: undefined is not an object (evaluating 'c.role')

### ISSUE THREAD

**Issue by liangfok** [Reviewable/Reviewable#430]
When acknowledging @soonho-tri's comments in https://reviewable.io/reviews/RobotLocomotion/drake/4234#-KXDi4fpluJJiBExzDoL, Reviewable crashes with the following error:

```
TypeError: undefined is not an object (evaluating 'c.role')
```

Here is a screenshot:

![screen shot 2016-11-27 at 10 37 35 am](https://cloud.githubusercontent.com/assets/1388098/20649431/16f9829c-b48e-11e6-9148-503efd6352d2.png)

Interestingly, @soonho-tri experiences the same problem when acknowledging _my_ comments.

**Comment by liangfok** [comment]
Sorry, I should note that I'm using OSX 10.11.6 and Safari 10.0.1.

**Comment by pkaminski** [comment]
Sorry.  Merging into #428, see the full story there.
