### ISSUE TITLE
Too easy to mispost in "no related file" discussion instead of "review discussion"

### ISSUE THREAD

**Issue by jwnimmer-tri** [Reviewable/Reviewable#432]
In my team we are using "no related file" discussions for PR-wide topics not specific to any one file.  I think that they are a great way to capture topical PR meta-threads.

However, whether through inexperience or inattention, it's not unusual for reviewers to post messages intended for "review discussion" into the bottom-most "no related file" discussion accidentally, e.g., posting the ":lgtm:" or "let's try to get this merged soon" or "PTAL", etc. into the topic thread, instead of the review thread.

I wonder if there is some UX affordance or presentation tweak that we can offer to help remind users of which of the two threads they are posting into, to help prevent this kind of accident?  Or alternatively / additionally allow editing or moving of comments between discussions so that we can repair after the fact.

**Comment by mikesokolsky** [comment]
Definitely see how that can get annoying, thanks for bringing it up.  We're starting a major review on the UI right now, this should get addressed during that process.

**Comment by jwnimmer-tri** [comment]
Any updates on the thought process here?  Is this something I should keep an eye our for in the beta?

I'm still setting reviewers PEBKAC into the wrong discussion thread about two times per week on average.

**Comment by pkaminski** [comment]
Sorry, no great news to report here.  The beta is a rewrite of the internals that doesn't touch the UI so it won't be helpful, and I don't have the bandwidth for a non-trivial UI redesign right now.  One simplistic idea, though:  what if I changed the width of the secondary top-level discussions to be the same as those of in-file discussions?  Do you think that might be sufficient, or at least helpful?

**Comment by jwnimmer-tri** [comment]
Unfortunately, its difficult for me to guess what would be better, since I find the current presentation perfectly clear.

I guess that any differentiation to the presentation could only help, so different-width seems worth trying.

Some other random possibly-easy ideas:
- Use "Follow up.." greytext only in the "Review discussion" box; in "no related file" reword to be "Reply..." to match in-file discussions?
- Tweak the "no related file" discussion box header somehow, maybe adding in the purple corner, or add header text "no related file" instead of the line number?

**Comment by pkaminski** [comment]
I implemented your ideas; they were better and easier than mine.  Top level discussion now have a "no file" notation where the line number would be, and ones created from now on will have a purple corner with a snapshot of the then-current revision.

I'll reserve bigger UI layout changes (width, section breaks) for later, in case the changes above prove insufficient.  As for "follow up" vs "reply", these are driven by your current reply state on the discussion and either can appear on any type of discussion, so they're not useful for discriminating.

Closing for now, but please reopen if you find that these changes didn't help (enough).
