### ISSUE TITLE
New top-level comment immediately shows as needing acknowledgement

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#434]
If I write comment in the top-level review discussion, upon publishing, that comment immediately is badged as "New" and has an "Acknowledge" button. If I reload the page, both of those go away.

**Comment by pkaminski** [comment]
I believe this was (yet another) side-effect of my attempt at improving the data layer's performance by moving it into a shared worker.  After a few days I've decided it's too flaky and rolled it back for the foreseeable future.  Please try again, it should be fixed now.
