### ISSUE TITLE
.jsx files not syntax highlighted

### ISSUE THREAD

**Issue by ibrahima** [Reviewable/Reviewable#435]
According to #47, it seems like JSX files should be supported by the syntax highlighting, but files that end in .jsx aren't being highlighted for me. Does the syntax highlighting only work on .js files with embedded JSX?

**Comment by pkaminski** [comment]
The `.jsx` file type wasn't explicitly mapped so whether the higlighting triggered or not depended on whether the content analysis heuristics decided it was JS.  I've added the mapping so this should work consistently now.

**Comment by ibrahima** [comment]
Awesome, thanks for the amazingly fast response!
