### ISSUE TITLE
Managed to merge master into a feature branch w/o knowing how I did it

### ISSUE THREAD

**Issue by dparton** [Reviewable/Reviewable#436]
While reviewing code, I pressed either a button or a keyboard shortcut that merged master into that feature branch. I'm not sure what it was, but it was certainly unintended. This operation may be "too easy" to do.

**Comment by pkaminski** [comment]
Sounds like you hit the "merge changes from master to PR branch" button in the Checks dropdown.  This is the equivalent of GitHub's "merge changes" button, and like that button has no confirmation.  See #400 for a previous discussion of this.

At this point, my guess is that matching GitHub's behavior is still the right thing to do, but the button needs to be more explicit about its effects (i.e., have some text).  Assigning to @mikesokolsky who's planning the next iteration of the UI.
