### ISSUE TITLE
GitHub webhooks broke

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#439]
We noticed today that our webhooks seem to have broken. Starting at 2:16 PM PST, events sent to https://reviewable-prod.appspot.com.github started returning a 307 code (which GitHub treats as an error). I also noticed a separate hook https://reviewable.firebaseio.com/queues/github.json that was marked as returning a 401 error.

I ended up turning off the repository, which deleted the first hook but not the second. Then I manually deleted the second. Then I re-added the repository, which added a hook https://reviewable-prod.appspot-preview.com/github (not quite the same as the original).

So what happened? And am I going to notice hooks breaking in my other configured repositories too? What about that reviewable.firebaseio.com hook that was just sitting around in an error state?

**Comment by pkaminski** [comment]
I inadvertently caused the problem by upgrading the server's runtime environment last night.  As you noticed, new connections (and reconnections) now target a different URL and are fixed.  I'm currently running a backfill over all connected repos to fix the problem transparently for everyone.  I don't have an ETA but it's making progress and I expect it to complete later today.

The second hook to `https://reviewable.firebaseio.com/queues/github.json` shouldn't have been there.  This hook form is used only in development and should never appear in production, so I'm rather mystified how it ended up there.  Please let me know if you ever spot it again -- unfortunately, GitHub facilities for getting metrics and error reports on an app's own hooks are inexistent, so I have no visibility into these issues.

**Comment by kballard** [comment]
So far every repository that we've hooked up to reviewable that I've looked at has that reviewable.firebaseio.com hook. For example, here's a (public) repo that has that hook: https://github.com/postmates/PMHTTP.

**Comment by pkaminski** [comment]
Thanks, I'll take care of this in the backfill run too.

**Comment by pkaminski** [comment]
All right, 24k repos scanned and everything should be working again.  As a bonus, I now have a "bulletproof" (hah!) script to wrangle all webhooks back to normal automatically for next time things blow up.
