### ISSUE TITLE
Line wrap character count is incorrect; lines wrap too early

### ISSUE THREAD

**Issue by ggould-tri** [Reviewable/Reviewable#441]
See the images below:  Line is <80 characters, but appears wrapped at ~75 chars despite 80 character margin setting (note tooltip visible in upper right of image).

Image is from https://reviewable.io/reviews/RobotLocomotion/drake/4634#-K_ABNwDigvI0hKRDlYI

![screenshot from 2017-01-02 11 35 39](https://cloud.githubusercontent.com/assets/17596413/21592908/bb1fdf48-d0df-11e6-98b7-1dc5fd803f48.png)

**Comment by pkaminski** [comment]
Unable to reproduce with default settings in Chrome / Windows but font metrics can be very squirrely.  What's your OS / browser, and what are your font face and size settings in the account dropdown?

![image](https://cloud.githubusercontent.com/assets/1646896/21596757/74fa6816-d0f4-11e6-9077-aac53c77f130.png)

**Comment by pkaminski** [comment]
Ping.  Can you provide more details please?

**Comment by ggould-tri** [comment]
OS is Ubuntu 14.04 ("Trusty"); browser is Chromium 53.0.2785.143 (the default Trusty install).
Fonts are default: "DroidSansMono" and "89%"

**Comment by pkaminski** [comment]
Thanks, reproduced on that platform.  I bumped up the font metrics fudge offset by 0.03px to fix this.

**Comment by ggould-tri** [comment]
This issue seems to be back:
Line wraps with 81 character width:
![Screenshot from 2021-07-12 09-36-48](https://user-images.githubusercontent.com/17596413/125297294-1f01ab00-e2f5-11eb-9860-831c1a01725b.png)
Line is only 78 characters wide:
![image](https://user-images.githubusercontent.com/17596413/125297400-304ab780-e2f5-11eb-8052-0edff2ccd6c8.png)

OS is Ubuntu 18.04 (bionic); browser is "Google Chrome 91.0.4472.114 (Official Build) (64-bit)"; Fonts are default: "DroidSansMono" and "89%"
![Screenshot from 2021-07-12 09-42-35](https://user-images.githubusercontent.com/17596413/125297877-a64f1e80-e2f5-11eb-9707-48ca0f5357a1.png)

**Comment by pkaminski** [comment]
@cgiroux86 do you have access to a Linux box/VM to reproduce and debug, by any chance?

**Comment by cgiroux86** [comment]
Not currently, but I can set up my Windows machine to dual boot Ubuntu.  I'll try to get a repro for this.
