### ISSUE TITLE
Sentiments Bar Missing Reviewer LGTM

### ISSUE THREAD

**Issue by liangfok** [Reviewable/Reviewable#442]
@ggould-tri gave the following PR an LGTM stamp, which shows up in Github's GUI here: https://github.com/robotlocomotion/drake/pull/4615#issuecomment-269987597. This LGTM, however, does not show up in Reviewable's sentiments bar here: https://reviewable.io/reviews/robotlocomotion/drake/4615. Any idea why the LGTM does not appear in Reviewable?

**Comment by pkaminski** [comment]
Yep, the emoji was uppercased (`:LGTM:`) and the lookup for display was erroneously case-sensitive -- fixed now (and retroactive).  Thanks!
