### ISSUE TITLE
Please add option to never collapse code and keep each file on separate page for speed.

### ISSUE THREAD

**Issue by johnpflynn** [Reviewable/Reviewable#446]

**Comment by pkaminski** [comment]
Thanks for dropping by!  These features requests are already tracked in #304 and #261, though, so I'll close this issue as a duplicate.  (Well, #261 is for showing one file at a time on a single page, but auto-opening a tab for each file could make for a pretty bad DoS, so it's probably not what you meant.  :)  You can quickly open all files in separate tabs by holding down `ctrl`/`cmd` and clicking on the "All" button that will then appear in the file matrix header.)
