### ISSUE TITLE
Feature request: Repo settings "sets"

### ISSUE THREAD

**Issue by lilyball** [Reviewable/Reviewable#447]
Editing repo settings is error-prone, because I have to remember which repos use the same settings (and which ones use different settings). I think a much better model for repo settings would be to let me create named settings "sets" divorced from any repo, and then for each repo I just select the settings set that it should use. This has two clear benefits:

1. I can see at a glance the distinct settings available, and browse them.
2. Any changes to a settings set automatically apply to all repos that use it.

It should also be easy to clone a settings set, so I don't have to manually copy all the settings if I want to make a variant for a subset of my repos.

**Comment by pkaminski** [comment]
I can see the benefit but I'm not sure it outweighs the additional complexity.  From a security point of view it's not clear who should be allowed to edit a "set" -- only people who have admin rights to all the repos using it?  Only org owners?  Or if it's some lesser bar, then people may be able to affect the settings of repos they don't have admin rights for (and may not even know exist).

A variant on this approach would be to allow a repo to "slave" its settings to another.  You could then create empty settings-placeholder repos and set permissions appropriately, and separately from the repos that are slaved to them.  I'm still not sure the extra complexity would really be worth it, though.

**Comment by kballard** [comment]
I have to admit I didn't consider the problems of varying repo permissions. One possibility is that you could edit a "set" if you have appropriate access to all of the repos that are configured with the set, and if you don't, then there could be a convenient way to clone the set and update all repos you do have access to to use the clone. That said, this certainly is complex.

To give some clarity on the problem I have, we have something on the order of 200 repos (that I can see). Nearly all of them are not hooked up to Reviewable, but a small subset are. And most of that subset all shares a single config, but at least one repository has a different version of the config.

In all of this mess, there's no way to see which repos have actually been customized. So, for example, I just edited the completion conditions for 6 repos that should all have the same settings. I would actually like to add the same change to a 7th repo that has a modified version of the same settings, but I'm not sure if that's the only repo using the modified form or if someone's also taken those settings and applied it to an 8th repo. Or if there are any other repos I don't know about that have been customized in some fashion. So I'd love to be able to see all of the distinct repo settings setups that exist, so I can make intelligent decisions about which ones to modify.

**Comment by pkaminski** [comment]
Coming back to this after a few years and I'm now more convinced it's needed.  I think the "inherit settings from another repo" (aka "slave") design is the simplest thing that could work.  Combined with #722, which would allow you to keep settings as a file in a repository, I'd see it working like this:

A repository's settings can be set to one of three options:  (a) UI settings (like now), (b) file settings (#722), or (c) inherited from another repo.  Inherited settings cannot be tweaked: it's all or nothing.  (If we decide to support partial overrides we'd make that available through the file option only.)  You can inherit from any repo in the same organization that you can see when editing the settings.  If another admin opens the settings and doesn't have access to the source repo, they'll only see "setting inherited from another repo" to avoid leaking potentially sensitive repo names.  They can still switch the option or point to another repo, of course.

Inheritance can only be one level deep:  you can only point to a repo using option (a) or (b), and any repo being pointed to by another cannot switch to option (c).  This is mainly to keep things simple and maintainable -- if really needed we could relax this restriction.

We might want to mark repos using options (b) or (c) with a special icon on the page, so you can tell they're set up differently without having to open their settings.

As part of this change, we'd also remove the "prototype repo" option and instead let an organization owner set a default repo to inherit settings from for new repos.  We might want to make this part of the "connect all current and future repos" toggle.

**Comment by pkaminski** [comment]
Random idea that I didn't think all the way through:  what if we replaced the current settings UI with a text editor for the file-based variant (#722) of the settings instead?  Saving would either commit directly to the repository or open a pull request, at the user's option.  This would let us shed a bunch of UI code and put an end to debates over what settings to surface in the UI.  The downside is that changing simple settings would be more challenging (though I think most developers / admins could handle it) and we wouldn't be able to provide any custom UI for guidance (such a disabling inapplicable options, or having a "Set to Codecov" shortcut button).

**Comment by snoack** [comment]
This issue should now be addressed through our just released file-based repository settings feature, and specifically through its [master settings](https://docs.reviewable.io/repositories.html#applying-a-settingsyaml-file-to-multiple-repositories) sub-feature allowing for `overrides` per set of repositories.
