### ISSUE TITLE
Highlighting for Bazel (Python) code

### ISSUE THREAD

**Issue by jwnimmer-tri** [Reviewable/Reviewable#449]
Could we get Python syntax highlighting enabled for Bazel source files? The https://bazel.build/ system is awesome and we use it in https://github.com/RobotLocomotion/drake.  Its build recipes are written in a subset of Python, so the Python highlighting should work great.

Or is there a way to have repository-specific configs where we can add them ourselves?

Details:
 1. The filenames are `BUILD.bazel` and `*.bzl` at minimum. 
 2. Most projects use `BUILD` instead of `BUILD.bazel` -- so that would be nice to claim too, unless it conflicts with some other claim to that filename.  (Though http://pantsbuild.org uses `BUILD`, it seems at first glance to python-ish also?)
 3. Bazel also has one project-wide `WORKSPACE` file that would be nice to highlight (also Python), though perhaps that filename is too overloaded.
 4. FWIW we also have `-*- python -*-` [hints atop our files](https://github.com/RobotLocomotion/drake/blob/680a42e42c15d23d659666ab73726d606340c7e6/tools/BUILD#L1) if that was helpful for hinting the rendering.

An example PR is at RobotLocomotion/drake#4717 if that helps.

**Comment by pkaminski** [comment]
Hey Jeremy, as of a couple months ago you can configure this yourself per-repo: https://github.com/Reviewable/Reviewable/wiki/FAQ#how-do-i-tell-reviewable-that-a-file-is-generated-and-should-not-be-reviewed.  Specifically, create a `.gitattributes` file at the root that looks something like this:

```
*.bazel diff=python
**/*.bzl diff=python
BUILD diff=python
WORKSPACE diff=python
```

You may be the first person to try this out in the wild, so please let me know if it works -- or doesn't!

**Comment by jwnimmer-tri** [comment]
Thanks, will do!  I have the github firehose turned on for Reviewable, so remember seeing that go by, but I didn't succeed at digging it up.  I'll report back iff we have problems.
