### ISSUE TITLE
Open-review-by-link is broken by anchor part

### ISSUE THREAD

**Issue by Mikulas** [Reviewable/Reviewable#450]
<img width="1582" alt="screenshot 2017-01-23 14 18 13" src="https://cloud.githubusercontent.com/assets/192200/22205367/d1c76e6c-e176-11e6-9f90-19a16b4ce5f5.png">

Urls with anchors to events/comments do not work:

`https://github.com/org/repo/pull/1300#event-932783238`

expected behaviour is as if I pasted this url instead `https://github.com/org/repo/pull/1300`

**Comment by pkaminski** [comment]
Thanks, fixed.

**Comment by Mikulas** [comment]
Great, thank you :)
