### ISSUE TITLE
Review each commit separately isn't working

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#451]
I just submitted a PR and tried to set it to "Review each commit separately". It said "restructuring review" for a few seconds, but then that went away, and nothing happened. The PR still only has a single revision containing everything, even though it insists it's set to "Review each commit separately".

The PR in question is postmates/getitnow-ios#1405 (non-public).

**Comment by kballard** [comment]
It has 31 commits, if that makes a difference.

**Comment by pkaminski** [comment]
Yep, that makes all the difference.  In "review each commit separately" mode there's a default cap of 20 commits per update; if this number is exceeded they'll be collapsed into a single revision.  The limit is both to protect Reviewable's servers from being overloaded and the UI from becoming unwieldy.

The limit is "per update", so for a connected repo if you push a few commits at a time you won't hit it.  I can also override the limit on a per-repo basis if needed and have done so up to a limit of 30 in the past.  (Note that this limit is not part of repo settings and will not be inherited by new repos even if you set the overridden repo as the settings prototype.)

**Comment by kballard** [comment]
It would be nice if the UI told me why switching that didn't do anything.

In any case, I don't want to make any repo changes. I actually wish I could split this PR up 18-20 revisions, most of them covering one commit each, and then one or two revisions for the rest of the commits, but I can't think of any way to have a reasonable UI for configuring that.

**Comment by pkaminski** [comment]
Agreed that feedback on this partial failure would be nice.

I considered building a custom revision splitting UI but always decided against it on grounds of complexity.  I think a better route is to improve Reviewable's auto-splitting heuristics -- can you think of a rule that would've resulted in your desired split in this case?

**Comment by kballard** [comment]
I don't think there's any automated rule that would work for my case. In this PR I have 18 commits that all do the same thing but to different parts of the codebase (porting the app from one library to another), and the remaining commits are just a bunch of smaller changes that are scattered across the app. So my ideal split here is to show each of those 18 commits as a separate revision, and then the remaining commits as 1 or 2 revisions.

Incidentally, if Reviewable's behavior was to split the first 19 commits and then dump the rest of them into the 20th revision, that would actually work almost perfectly for this PR.

**Comment by pkaminski** [comment]
OK.  I think splitting up to the limit is likely to be even more confusing in the average case since it'll initially look like things worked until you get a nasty surprise further on in the review.  I'll make sure some feedback makes it back to the UI for now, and work over time to raise the limit as both server and client are able to deal more efficiently with a large number of revisions.
