### ISSUE TITLE
Access from Crimea

### ISSUE THREAD

**Issue by cblp** [Reviewable/Reviewable#453]
If I open Reviewable from Crimea, I get

> OFFLINE. Reason: no connection to Firebase

In console I see such errors:

```
firebase.js:168 GET https://reviewable.firebaseio.com/.lp?start=t&ser=... net::ERR_CONNECTION_TIMED_OUT
firebase.js:168 GET https://reviewable.firebaseio.com/.lp?start=t&ser=... net::ERR_TIMED_OUT
```

ping
```
$ ping -c 10 reviewable.firebaseio.com
PING reviewable.firebaseio.com (104.154.130.226): 56 data bytes
64 bytes from 104.154.130.226: icmp_seq=0 ttl=44 time=155.484 ms
[...same...]
64 bytes from 104.154.130.226: icmp_seq=9 ttl=44 time=159.458 ms

--- reviewable.firebaseio.com ping statistics ---
10 packets transmitted, 10 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 155.035/156.858/159.458/1.521 ms
```

traceroute
```
$ traceroute reviewable.firebaseio.com
traceroute: Warning: reviewable.firebaseio.com has multiple addresses; using 104.154.130.226
traceroute to reviewable.firebaseio.com (104.154.130.226), 64 hops max, 52 byte packets
 1  * * *
[...same...]
64  * * *
```

Unfortunately, I can't help with debugging from Crimea, I already flew to Moscow, and Reviewable works here.

Does Firebase have any political reasons? If so, why don't they respond HTTP 451 instead?

**Comment by pkaminski** [comment]
Darn, I was going to ask you to follow up with these tests (from Crimea):
- Load https://reviewable.firebaseio.com/.lp?start=t&ser=...&cb=2&v=5 from your browser, paste the response.
- Try to `ping` and `tracert` `s-usc1c-nss-130.firebaseio.com`.
Sounds like we'll have to wait until next time somebody's in Crimea.

Firebase runs in Google data centers (in central US), and AFAIK there are no Google-side blocks on connections there.  It's more likely to be some kind of block (or bad DNS?) from the Crimea side.

**Comment by pkaminski** [comment]
No further reports over 10 months, so closing for now.
