### ISSUE TITLE
Renaming an enabled repository that has an review in-progress causes an error.

### ISSUE THREAD

**Issue by danieljy** [Reviewable/Reviewable#454]
To reproduce:

* Create a repository.
* Enable it with reviewable.
* Create a pull request on this.
* Rename the repository in github.
* Visit reviewable.io/reviews (notice the error that comes up).

This can be solved by going into reviewable.io/repositories and enabling the repo under the new name. Presumably, this enablement can be done automatically instead.

**Comment by pkaminski** [comment]
Renaming repos is a known pain point (see for example #170, #372) but I can't reproduce a flat-out error using the steps above.  I tried with both a public and a private repo, and in both cases the PR ends up detached from the review (and the repo appears disconnected), but there's no explicit error on the Reviews page (or any other page) that I can see.  What error showed up for you?

Note also that any webhook event from the renamed repo will cause Reviewable to realize what happened and mirror the rename internally, reattaching the review to the PR and making the connection look enabled again.  This event can be most anything: a comment on any PR or issue, a new PR, etc., so in most cases Reviewable will catch up quickly enough that you might not even notice the discrepancy.  (Ironically, GitHub doesn't fire an event when a repo is renamed, though.)

**Comment by pkaminski** [comment]
I finally tracked this down and fixed it.  Sorry!  Still running a sweep over old reviews to fix them up, but should be done soon-ish.
