### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by antis81** [Reviewable/Reviewable#456]
Hi! Just wondering, is there is any plans for integration with GitLab? Don't know how much overhead that would mean, just asking…

**Comment by pkaminski** [comment]
Hi Nils -- GitLab is a completely different beast from GitHub API-wise, and I have no plans to integrate with it.  However, the GitLab folks are looking at Reviewable to see which features make sense to port over to GitLab, so you may want to join the discussion there:  https://gitlab.com/gitlab-org/gitlab-ce/issues/27116

**Comment by hopeseekr** [comment]
Much has changed for both GitHub (mostly for the negative) and GitLab (mostly for the positive) since this ticket was closed because "We tightly coupled ourselves to GitHub and are going to go out of business if GitHub goes down. Damn :-/"

My corporation and several more legal clients have transitioned off of GitHub and GitHub Enterprise (and Bitbucket, but good god!) to GitLab primarily because of GitLab's new featuresets and GitHub being acquired by Microsoft.

I used to use Reviewable.io religiously in 2016-2017, as a paying customer and CTO, and brought you sizable four digit revenues yearly. But I've been forced off it due to it lacking support for anythign other than GitHub and changing winds.

Please :-/ Pass this issue comment up to the highest levels, you owe it to your corporation for the business owners to be fully aware of why they are losing valuable customers and why the trend is likely to continue and increase.

**Comment by pkaminski** [comment]
So this [came up on Hacker News](https://news.ycombinator.com/item?id=19103208) recently and I dug up some usage numbers:

> So answering myself, with numbers pulled from https://expandedramblings.com:
GitHub: 31M users
BitBucket: 6M users, 1M orgs
GitLab: 100K orgs
The GitLab number tallies with Emily's answer, which gives me some moderate confidence that these numbers are in the right neighborhood. I'm also going to assume that the users-vs-teams numbers are all in roughly the same proportion.
Based one these numbers it doesn't make much sense to target BitBucket unless either 1) they're growing much faster than GitHub (unlikely) or 2) their customers are a much better fit for Reviewable (possible, but it would have to be a truly significant difference in userbase composition). Targeting GitLab doesn't appear to make sense at all (as a business), though perhaps they're growing fast.

So while I've heard lots of good things about GitLab and they appear to have momentum on their side, an apparent 50x user differential makes it hard to make a business case for supporting them at this point.  If you have better numbers on GitLab's users or growth, please share -- I'm definitely willing to listen and change my mind.

**Comment by hopeseekr** [comment]
I still hope that your CEO and owner(s) of Reviewable's corporation are fully aware that they are one capricious decision and/or feature release blitz by GitHub and/or Microsoft before they're completely out of a marketable product.

It clearly isn't a way I would ever commission or allow my core software product to be developed.

**Comment by pkaminski** [comment]
Heh, I _am_ the CEO and owner of Reviewable.  :)  And yes, of course any product built on a platform owned by somebody else is always at risk of being superseded at a moment's notice -- that's the deal, whether on GitHub or GitLab.  Other products / business plans have different trade-offs, and as a business owner you need to pick risks you're comfortable with.

**Comment by hopeseekr** [comment]
OK, fair enough. BitBucket's code review is so atrocious I've gotten several clients ported to GitLab just because of it and the horribleness of Bamboo CI. I really miss being able to use reviewable.

**Comment by AlecBenzer** [comment]
I understand that this is a big amount of work to bite off, but FWIW I'll echo that I'd also be quite happy if this happened. :)

And am also somewhat skeptical of GitLab's ability to effectively incorporate features of reviewable into their review tool: https://gitlab.com/gitlab-org/gitlab-foss/issues/27116#note_247082079

**Comment by bronumski** [comment]
@pkaminski Would love to see this ported to bitbucket. Our team was using reviewable in my previous job and it is a great product, really makes for easy pull requests and code reviews. I see enough comments from people who praise your product but are then for one reason or another having to switch to bitbucket and then forced to use the horrendous bitbucket PR UX. I cannot tell you if the effort of supporting another platform would give you the return you want but I can tell you that you will have many people championing your product.

**Comment by hopeseekr** [comment]
Maybe Atlassian should place an offer to buy Reviewable?

Then they can replace bitbucket's attrocious code review product and it might actually be worth using...
