### ISSUE TITLE
Holding command when going to tab makes cmd-clicking not work as expected

### ISSUE THREAD

**Issue by lilyball** [Reviewable/Reviewable#458]
If I'm holding command when I switch to the the tab for https://reviewable.io/reviews#-, and then I click one of the reviews without letting go of command, it doesn't open in a new tab as expected but instead behaves as though I didn't press command.

As best I can figure, Reviewable doesn't check if command is held when clicking at all, it instead watches for command to be pressed and released and updates some internal state that it consults when clicking links. But this means that if I press or release command while in some other tab, the Reviewable tab doesn't notice, and its internal state may be incorrect.

**Comment by pkaminski** [comment]
AFAICT this got fixed at some point, perhaps when we migrated the page to Vue.
