### ISSUE TITLE
How do I get back to the PR on GitHub from Reviewable?

### ISSUE THREAD

**Issue by morelazers** [Reviewable/Reviewable#459]
I always find myself hitting back then refresh, couldn't find a keyboard shortcut or anything similar.

Sorry if this has been raised before.

**Comment by pkaminski** [comment]
Hitting the back button works well, but there's also a discreet link in the top-right corner of the Changes box:
![image](https://cloud.githubusercontent.com/assets/1646896/23828079/6b427a46-067a-11e7-90ac-0b4eeaed913f.png)
