### ISSUE TITLE
Empty diff for file mode change

### ISSUE THREAD

**Issue by marczych** [Reviewable/Reviewable#462]
I reviewed a PR today whose only diff was changing the mode of a file from 755 to 644. Before taking any actions, it says "Review complete: all files reviewed, all discussions resolved". However, at the top of the page it says "Review in progress", 0 revisions, and "+ 1 provisional". The file matrix is empty and there and the bottom of the page is the "Start a new discussion button".

So it appears that there is an issue with PRs that _only_ have file mode changes but perhaps file mode changes aren't displayed at all in Reviewable? I checked another PR that has a diff on a file and a file mode change and I'm not seeing any indicator of the file mode change in Reviewable but I do in GitHub (`100644 → 100755`).

**Comment by pkaminski** [comment]
Indeed, Reviewable currently ignores file modes altogether.  :(  Fixing this will require changes throughout the stack.

**Comment by pkaminski** [comment]
This should be fixed going forward (not retroactive).
