### ISSUE TITLE
Present C/C++ header code before implementation code

### ISSUE THREAD

**Issue by jwnimmer-tri** [Reviewable/Reviewable#465]
In #7, we downvoted being able to curate the order of the file matrix.  Fair enough.

However, for something like C or C++ in particular, it's common to have multiple source files for the same logical component, e.g., `foo.h` and `foo.c` are intimately related.  Given alpha-sorting, we end up next'ing to `foo.c` first and then `foo.h`, when >95% of the time we'd like to review the header before the implementation.  Right now, this means fumbling around with `n` and `p`, remembering whether you're on the header (hit `x p`) or implementation (hit `x n n`).

Would be possible to either hard-code a different sort, or have a repository preference for it?  (I don't think a per-user preference would be the right answer here.)

At a minimum, I'm looking to sort by the `{fullpath, extension}` pair where `fullpath` sorts alpha like now, but when two `filepath`s are identical, sort by `extension` with some customization beyond just alpha-sorting the extensions.

If we're hard-coding a fix, one reference for C++ source extensions is https://bazel.build/versions/master/docs/be/c-cpp.html#cc_library which says:
- C and C++ source files: .c, .cc, .cpp, .cxx, .c++.C
- C and C++ header files: .h, .hh, .hpp, .hxx, .inc

Of course if the repository gets a sort predicate, then we could implement any heuristic we wanted.

**Comment by pkaminski** [comment]
I like this idea.  I doubt that different repos would want to order extensions differently, so I think it's worth hardcoding and calling out in the docs/FAQ that I'm happy to add more rules for other languages.

**Comment by dnoe** [comment]
Yes please, this is very annoying! I'd always like to see the header file of the same name before the source file if they are in the same directory when reviewing a PR. Right now I end up doing a lot of scrolling up and down to address this.

**Comment by mattklein123** [comment]
+1

**Comment by dmitry-xnor** [comment]
Critique does this (at Google). GitHub does not, but then there are a lot of other things that GitHub "does not".

**Comment by pkaminski** [comment]
This should now be fixed for the beta (https://beta.reviewable.io) and will make its way to the stable release later this month, followed by Enterprise likely in March.
