### ISSUE TITLE
Mixing // and /* */ style comments confuses syntax highlighting (at least for Go)

### ISSUE THREAD

**Issue by klausman** [Reviewable/Reviewable#466]
Given code like this:

```
/* func bla() {
  // Handle the frobnizer
  frob()
}*/
```
The Reviewable UI will syntax highlight the last two lines as if they were not commented out.

**Comment by pkaminski** [comment]
Which language are you seeing this for?  I tried to reproduce [here](https://jsfiddle.net/23m69f6a/2/) but couldn't get it to fail in Go, Java, or JavaScript, using either HighlightJS 9.7.0 (the one currently integrated into Reviewable) or 9.10.0 (current stable release, which I should update to).

**Comment by klausman** [comment]
I just now tried to reproduce it (it was originally in Go, on this review: 

https://reviewable.io/reviews/netsec-ethz/rains/8#-Kh6aYAWwriA9Sc35fAV

It's not always reproducible, but it works just now with Chrome in Incognito Mode and using that exact link.

Note how below my comment, line 28 and following are syntax highlighted as "not commented out" up until the closing `*/` around line 45 (just before `return nil`).

**Comment by pkaminski** [comment]
Thanks, that helped me locate and fix the bug.  Note that the correct style will only show up in a two-column diff, since a unified diff the commented-out section is considered "unchanged" and will use the left-hand-side's styling.
