### ISSUE TITLE
Keyboard shortcut for copying branch name

### ISSUE THREAD

**Issue by marczych** [Reviewable/Reviewable#467]
I always have a bit of a hard time copying the branch name from Reviewable. The method in #176 works but it's a little finnicky because the branch name is a link so you can't single click it and it's also usually split onto multiple lines and I end up getting whitespace on either side. I'll admit it's a minor complaint but I do it often enough that it would be nice to make it easier if it isn't too much trouble.

I looked through the default keybindings file and didn't see anything regarding the branch name. In order of most to least preferred:

 - Keyboard shortcut to copy the branch name to the clipboard.
 - I realize that copy support can be a mixed bag, so maybe a keyboard shortcut to highlight the branch name which can be followed by `mod c` to copy it would work?

**Comment by pkaminski** [comment]
Yeah, this seems easily addressable.  A few questions:
1. Do you just need the source branch, the target branch, or both?
2. If the branches are in different repos (displayed as `owner/repo:branch`), do you want the fully qualified name or just the plain branch name?
3. What do you use this for?  If it's to check out the branch, would it be more useful to just put the full `git checkout <branch>` command on the clipboard?

Thanks.

**Comment by marczych** [comment]
1. Personally, I'm only interested in the source branch.
2. I don't use Reviewable with forks so it's a non issue for me.
3. It's _usually_ to check out the branch but sometimes for diffing or merging so copying just the branch name is most flexible.

**Comment by pkaminski** [comment]
I added a mini-button and `copyHeadBranch()` command.  Clipboard support is pretty solid on modern browsers but do let me know if you run into issues.

**Comment by marczych** [comment]
This is glorious, thank you! I just informed some of my nearby coworkers and one said "Oh thank god". =)
