### ISSUE TITLE
Fix jsx syntax highlighting

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#47]
As soon as you hit the first tag in a [jsx][1] file (e.g. `LatestComments.js` at https://reviewable.io/reviews/hammerlab/cycledash/463), the highlighting breaks:

![screen shot 2015-02-25 at 4 19 23 pm](https://cloud.githubusercontent.com/assets/98301/6380777/1e19ce06-bd0a-11e4-9302-888f0fc38794.png)
_(the `var` in `var Comment` isn't highlighted.)_

This is probably a highlight.js issue -- they say [it works][2] but I say otherwise. GitHub handles JSX files fine.

[1]: http://facebook.github.io/react/docs/jsx-in-depth.html
[2]: https://github.com/isagalaev/highlight.js/issues/494

**Comment by pkaminski** [comment]
I think this is a highlight.js bug here: https://github.com/isagalaev/highlight.js/blob/master/src/languages/javascript.js#L47  It expects an XML sections to end with ">;", whereas your XML is parenthesized.  Changing the pattern to />\)?;/ would probably fix it for your case but I don't know if that's sufficiently (or too) general.

Probably worth opening an issue against highlight.js and trying to submit the fix to see what they say...

**Comment by pkaminski** [comment]
I'll keep this open as a tracking issue but mark as wontfix (from the Reviewable side).

**Comment by danvk** [comment]
Here's my upstream PR: https://github.com/isagalaev/highlight.js/pull/767

**Comment by danvk** [comment]
My upstream change was merged. I'm not sure when the next highlight.js release will be, though.

**Comment by pkaminski** [comment]
Great!  I'll keep an eye out and let you know when the updated module made
it into Reviewable.

On Fri, Feb 27, 2015 at 9:11 AM, Dan Vanderkam <notifications@github.com>
wrote:

> My upstream change was merged. I'm not sure when the next highlight.js
> release will be, though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/47#issuecomment-76431135>
> .
>



-- 
Piotr Kaminski, Founder, reviewable.io

**Comment by danvk** [comment]
FYI this will go out in the 8.5 release of highlight.js, which they're tracking [here](https://github.com/isagalaev/highlight.js/milestones/8.5). Their time estimate is ~2 weeks.

**Comment by pkaminski** [comment]
Integrated highlight.js v8.5, so this should be fixed now.
