### ISSUE TITLE
Add an option for a text-only link to the review

### ISSUE THREAD

**Issue by jgraham** [Reviewable/Reviewable#470]
Some https://gitgub.com/w3c/web-platform-tests contributors have complained that the reviewable link is intrusively large. An option for a much smaller text-only link (e.g. just the word `[reviewable]` might help assuage these concerns.

**Comment by pkaminski** [comment]
While I would consider adding such a feature for private (paid) repos (where you can already turn the badge off altogether), in public ones the badge serves the function of marketing-in-lieu-of-payment.  I think that right now it strikes a reasonable compromise between visibility / branding and unobtrusiveness, being roughly the size and saturation of GitHub's own buttons on the page.  Sorry, but providing the service for public repos isn't free and this is my way of recouping some of the costs...

**Comment by jgraham** [comment]
To be honest it's not clear that adding a button which causes people to request that the tool is turned off entirely is a marketing win. I agree with your comparison to GitHub itself, but I also think it's worth comparing to tools such as Travis which are happy to integrate with GitHub in a less extravagant way and are nevertheless a success. For an open source project the repos are obviously all public, so as far as I can tell there's no way to pay you in your current subscription model.

**Comment by pkaminski** [comment]
IIUC the concern about the button is only for reviews that are not desired, so I think this is best addressed via #471.

And I'm happy to make exceptions to the subscription model is somebody wants to pay me more.  😉
