### ISSUE TITLE
Some ideas for making massive diffs more tolerable

### ISSUE THREAD

**Issue by marczych** [Reviewable/Reviewable#472]
I've been reviewing a particularly massive diff in Reviewable: https://reviewable.io/reviews/iFixit/iFixitAndroid/265

I know it's been talked to death in various issues over the years but I found some workarounds that made it possible to review the diff that I think could be incorporated into the normal workflow. Of course, large PRs are bad but sometimes they are unavoidable. Also, I would argue that Reviewable's value over GitHub as a code review tool is at least linearly proportional to the size of the diff and how long the PR is open.

First, some things I've noticed:

1. Loading the main page (linked above) routinely took ~5 minutes - during most of which the UI was mostly unresponsive and Chrome even prompted to kill the tab (just ignore it and eventually it loads).
1. Once the page was loaded, typing into a comment box easily had a few second delay for every character pressed.
1. Using "special single-file mode" as I saw you refer to it in another issue was _very_ usable. I URL hacked my way to it (something like https://reviewable.io/reviews/iFixit/iFixitAndroid/265/adsf) and used `x` and `.` to review a file and move on to the next one. Everything was very responsive in this mode.
1. Once I reviewed all of the files in special single-file mode, I realized that there were top level discussions that I had to resolve but I couldn't view. Also, there was no way to publish the files I reviewed or the comments I made so I was forced to suffer through the long page load of the main page to do so. Even publishing the comments took a minute or two and I think it even timed out with errors that indicated that it failed (it did work, though). I eventually looked into customizing keyboard shortcuts and bound `Cmd + Enter` to publish all comments (`["mod+enter", "Publish all comments", "sendAll()"],`) which worked from the special single-file mode and was pretty snappy.

So I had come up with reasonable workarounds that made it possible to review the files but the PR author still had to do the same (at one point he said he wanted to try a different computer to get it to load). While I could explain the process to him, it would be great if Reviewable made it easier to do this. I'm speculating, but it seems like the biggest difference between those two modes is the file matrix which could be making things slow. Maybe hiding it if there are more than a certain number of files/revisions and having a toggle to display it? I'd much prefer a fast page load and a hidden file matrix to an absurdly long page load with the file matrix displayed. If that works as well as I hope, I think it should solve all of the problems I described above.

**Comment by pkaminski** [comment]
Thanks for the detailed report!  On my machine, I have the main page loading in ~3.5 minutes with the file matrix on, in ~50 seconds with the file matrix off, and the special single-file mode loading in ~20 seconds.  So while the file matrix is clearly the main performance culprit here, there's other things going on as well.

The long term solution is to 1) offload as much data processing as possible to a web worker (I've got this running in dev right now, but won't be ready for beta for another month or two), and 2) switch from Angular to something that scales better, likely Vue.js (later this year).  In the meantime, I like your idea of automatically overriding the user's preference when there are too many files and have implemented a 200 file threshold.  It won't be perfect but it should give us a quick win.

BTW, you can enter the special single-file mode by cmd/ctrl-clicking on a file path anywhere it appears in the UI (file matrix or file header).
