### ISSUE TITLE
setCurrentDiscussionDisposition keybindings don't work for new discussions

### ISSUE THREAD

**Issue by marczych** [Reviewable/Reviewable#473]
I recently added the following to my custom keybindings file which I have found to be very useful:

```json
[
    "mod+shift+d",
    "Set disposition to \"discussing\"",
    "setCurrentDiscussionDisposition('discussing')"
],
[
    "mod+shift+s",
    "Set disposition to \"satisfied\"",
    "setCurrentDiscussionDisposition('satisfied')"
],
[
    "mod+shift+b",
    "Set disposition to \"blocking\"",
    "setCurrentDiscussionDisposition('blocking')"
],
```

However, I noticed that it sometimes wouldn't work and I eventually figured out that it didn't work on _new_ discussions (it worked just fine on discussions that have been published). A fix would be much appreciated. =)

**Comment by pkaminski** [comment]
Good catch, fixed!

**Comment by marczych** [comment]
Great, thanks for the quick fix! I've already used it several times. =)
