### ISSUE TITLE
Sometimes the merge button doesn't show (even though the bunny does)

### ISSUE THREAD

**Issue by romrell4** [Reviewable/Reviewable#475]
![screen shot 2017-05-02 at 12 23 09 pm](https://cloud.githubusercontent.com/assets/15692420/25632788/370fe5c0-2f32-11e7-9527-4100a40854fa.png)

**Comment by romrell4** [comment]
If I refresh the page, the green button shows to "Merge and Delete branch"

**Comment by pkaminski** [comment]
Huh, that's really strange -- the visibility conditionals for the merge button and the bunny are exactly the same (though they are in separate places in the DOM).  Do you have animations turned on or off?  Perhaps the animation is misfiring and failing to push the button into view.

**Comment by pkaminski** [comment]
Ping.

**Comment by romrell4** [comment]
Animations are on

**Comment by pkaminski** [comment]
I tried playing with this a bunch but haven't been able to reproduce.  Is this something that happens to you somewhat regularly?  What is the action immediately preceding the failure that makes the PR mergeable -- publishing comments?

**Comment by romrell4** [comment]
It only happens every once in a while... I'll let you know next time it happens and what exactly happened before the bug

**Comment by pkaminski** [comment]
Closing for now, I'll reopen if you get a repro.
