### ISSUE TITLE
Inexplicable diff bounds selection

### ISSUE THREAD

**Issue by mgalgs** [Reviewable/Reviewable#478]
I've been noticing that sometimes the diff bounds that Reviewable selects when I visit a review that I've previously reviewed in the past don't make a ton of sense.  I assume I'm just missing something...

For example, here's a review where I had reviewed some files in prior revisions.  On loading the page, I would have expected the left diff bounds to be set to the last revision I've reviewed (the eyeballs) and the right limit to be set to the newest revision with changes to that file (or maybe just all the way to the right since that would be the same thing).  In this case, `PresenterTools.jsx` looks fine, but I'm not sure what happened to `LiveVideo.jsx`...

![image](https://cloud.githubusercontent.com/assets/152014/26421042/69e4521c-4079-11e7-86e5-1fba8ff62f3a.png)

I'm using "Review each commit separately".

What am I missing here?  My workaround is to click the eyeball to get the left bounds set and then the highest revision (`r5` in this case) to get the right bounds set, which makes it look like this:

![image](https://cloud.githubusercontent.com/assets/152014/26421294/64347c56-407a-11e7-984d-f0273fd589ae.png)

**Comment by pkaminski** [comment]
Hey Mitchel, while the bounds-picking algorithm is complex and likely has bugs, in this case it's behaving as desired/expected.  The key fact is that you're in "review each commit separately" mode.  In that case, Reviewable will attempt to 1) create one revision per commit and 2) ensure that a diff never spans more than one revision (i.e., one commit).  So in your example the algorithm first determines that the next commit (revision) that has not been reviewed for all files is r4, then sets the diff bounds to r3..r4 for all files except for ones where r3 == r4, in which case it sets a nil diff so the files will be skipped in this round.  Once you mark `PresenterTools.jsx` as reviewed at r4, Reviewable will suggest that you review the next commit and will set the bounds to r4..r5 for all files (modulo nil diffs).  This is the way you get the commit-by-commit review style you requested.

From your description of what you expect it sounds like you're actually looking for the "combine commits" review mode instead, where indeed the auto-diffs will always be from the last reviewed revision to the latest one.  Let me know if that works better or if it still doesn't meet your expectations!

**Comment by mgalgs** [comment]
Ah, makes sense! I didn't realize that you had to iterate through the commits like that. I set it to "review separately" since I'm coming from Gerrit where you very much review each commit separately, and honestly wasn't sure what difference that setting was making in reviewable. I'll go ahead and switch it back.

Thanks again for the amazing tool.
