### ISSUE TITLE
Make Reviewable link open in a new tab

### ISSUE THREAD

**Issue by manishrjain** [Reviewable/Reviewable#485]
Instead of consuming the current one.

**Comment by pkaminski** [comment]
While link do you mean?

**Comment by manishrjain** [comment]
The link that gets shown when you create a PR in Github. The one with the big Reviewable button.

**Comment by pkaminski** [comment]
Ah, the badge link.  No can do, since Markdown strips `target` from `a` tags.  Sorry.
