### ISSUE TITLE
Reviewable approval should link to github approval

### ISSUE THREAD

**Issue by ryanmcnamara** [Reviewable/Reviewable#489]
Github "Review approvals" are disconnected from reviewable approvals or "lgtm"s which is a bit annoying.

Is it reasonable to say that when someone signs off on a PR in reviewable it should add their approved review in github?

**Comment by pkaminski** [comment]
Yes, I need to figure out how to reconcile the two systems.  This is also related to #437 and #463.

**Comment by eternoendless** [comment]
Reviewable is a much more powerful review tool than GitHub, but integration friction discourages usage.

Right now my team is forced to approve pull requests twice (once on reviewable, once on GitHub), and even though it's not really such a big deal, the lower the integration friction is, the easier it will be to convince them to use reviewable for reviews.

So please, please add this soon 🙂

**Comment by pkaminski** [comment]
I'm currently focused on wrapping up the client data model rewrite.  As soon as that goes into beta/canary, my top priority will be to improve the integration with GitHub's review system.  So -- soon!

**Comment by such** [comment]
hey
any update on this?

**Comment by pkaminski** [comment]
This is just about at the top of my to-do list at this point.  I just shipped the review requests integration, and will now be focusing on promoting the beta to stable while designing the reviews integration.  Some of my ideas require #510 to launch first though -- we'll see.  I'll post my design here for vetting when it's ready.

**Comment by tomato42** [comment]
I think it's more or less obvious, but integration in the other way, when the changes are needed, if I explicitly asked for issues to be resolved, marking the github review as "Request changes" would also be nice, as that status is show in the list view of PRs

**Comment by pkaminski** [comment]
I shipped #510, so modulo bug fixing this feature is next.  My idea is to tie dispositions on the top-level discussion to GitHub review state:  satisfied = approved, discussing = comment, blocking = request_changes (other active dispositions will be disallowed).  The LGTM button will become an Approve button that appears only after Acknowledge has been clicked and switches the disposition to Satisfied in addition to inserting the :lgtm: (or whatever's configured).  Dismissing discussion participants ties in to dismissing reviewers.

The Publish button changes to "Publish & Approve" if your disposition is Satisfied, and "Publish & Block" if it's Blocking (could be "Publish & Request Changes" but that seems a touch long).  The dropdown from the Publish button will gain a new line of radio buttons above the preview with "Approve", "Comment" and "Request changes" choices, that will sync with the top discussion's disposition.

Each participant's review approval state will be reflected in their status blob, which is currently just a red disc for people who are being waited on.  I'll add a satisfied/blocking icon to the disc as appropriate, and show it in grey if the person isn't being waited on.

Lots more to be done with review integration but I think that covers the approval bits.  Any feedback?

**Comment by johlju** [comment]
Really looking forward to this! 😃  And hopefully down the line it will be possible to review in either GitHub and Reviewable and the state is reflected in either! 😃 

Apologize if I'm not following you entirely and maybe repeating below what you are already thinking. 

Do you want to approve a PR and send blocking comments at the same time? 🤔 
Maybe the Approve button should not show until all blocking comments from that reviewer has been resolved (or that will be resolved on publish)? Or maybe it should show but be "greyed", to show that "you can approve, but you still have blocking comments that are unresolved"? Otherwise we might come in a blocking state if there is no way to withdraw a blocking comment (I'm still learning the new).

Thinking that maybe the "Publish"-button could be smart, that if there are review comments that are blocking it will automatically be set to "Publish & Block", if there are no blocking comments it will be set to "Publish & Approve"

**Comment by timbotnik** [comment]
Also looking forward to this - I'd just like to make sure that one reviewer can still trigger (force?) "approval" even if there are unresolved discussions etc.

**Comment by pkaminski** [comment]
Apologies for the delay in following up but I was busy with bug fixes and trying to figure out how to address the very astute comments.  My proposal above was for a straightforward "manual" approach, but @johlju I agree that it would be much better if Reviewable could suggest the right approval state based on its default semantics.  At the same time, @timbotnik is right, users need to be able to override the approval state no matter what the review might look like.

Modifying the proposal above, a user's approval state can be "automatic" or "manual":  in automatic, Reviewable will adjust the Publish button automatically, while in manual it will stick to whatever the current approval state is.  It starts out automatic, and stays that way as long as the user only changes approval state by hitting the Publish & * button.  If the user manually changes disposition or adjusts their approval state from GitHub, it flips over to manual.  It's not clear if there needs to be a way to switch back to automatic or not.

Another complication is that the current LGTM button is customizable to insert arbitrary emojis and text into a top-level message, which can then be picked up by a custom review completion condition.  It's not clear if this text needs to be injected when hitting Publish & Approve (perhaps only if it switches state?), or when the user manually changes to the Satisfied disposition, or whether it should only be bound to the Approve button on the discussion.  Similarly, it's not obvious whether this text should be recognized in a message and trigger a disposition change.  Perhaps keep it bound to the button only and expect people to update their conditions to use the review approval states that will be surfaced as part of this work?

**Comment by johlju** [comment]
I agree that any automatic state should be able to be overriden. 

I think LGTM comment in top level become obsolete when this change can make a GitHub approval. That status should be able to be catched, and much cleaner than looking for LGTM. Though, maybe the LGTM comment needs to be kept for a while so users can change any automation? It’s a breaking change in that sense. I personally would not need the LGTM in top level discussion if this change can make a GitHub approval.

**Comment by johlju** [comment]
Regarding flipping back to automatic once in manual. Maybe that will be discovered when we use the beta of this change. If you will make a beta of this.

**Comment by pkaminski** [comment]
Update:  I've got this implemented now, with a design that follows the spirit of the discussion above but differs in a number of details.  However, I'm holding back the release until I can also post line-level comments correctly (#437).

**Comment by pkaminski** [comment]
Launched -- let me know how it goes!

**Comment by johlju** [comment]
Looking good so far!  🎆
