### ISSUE TITLE
Resolved hidden comments gets shown when resizing window or moving window to another screen

### ISSUE THREAD

**Issue by johlju** [Reviewable/Reviewable#490]
Sometimes when I review large pieces of code I usually start on a screen that is in portrait orientation and when i get to a code section where I need to see the code more expanded, I move the window to a screen that is in landscape orientation. When I do that (or move it back) all the comments I have acknowledge (by pressing the Acknowledge button), and has been automatically hidden, are shown again, making it harder to re-read the code. 

This is really a minor issue, but if it easy solvable then I would love for it to keep those review comments, that was hidden, as hidden.

**Comment by pkaminski** [comment]
Nice catch!  Took a bit of work to track this down but the fix was fairly straightforward.  Thanks!
