### ISSUE TITLE
Whitespace changes are hidden again when moving between monitors

### ISSUE THREAD

**Issue by johlju** [Reviewable/Reviewable#492]
This is really a minor issue. But when I move the window from one monitor to the next, the whitespace changes "view" is hidden again. This is on a Windows box, in Chrome.

This seems to only happen when the windows is so small (when I drag in the title bar) so it is resized so that it goes from side-by-side to "single-view" (get's hidden here) and then back to side-by-side when maximized on the next monitor (when snapping the title bar to the top of the screen on the new monitor).

![whitespace](https://user-images.githubusercontent.com/7189721/28705465-2a7467c8-7370-11e7-99f9-0600c047f101.gif)

**Comment by pkaminski** [comment]
Stupid bug, now fixed -- thanks for spotting!
