### ISSUE TITLE
UI not loading due to MIME type mismatch in JS/CSS

### ISSUE THREAD

**Issue by PlagueHO** [Reviewable/Reviewable#494]
Hi There,

Since about 12 hours ago the Reviewable UI no longer loads, with most UI elements missing and nothing clickable. This appears to be because two files are not able to be loaded in the browser:
```text
The resource from “https://reviewable.io/css/45b25c41.app.css” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).[Learn More]  136
The resource from “https://reviewable.io/js/192f4964.libs.js” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).[Learn More]
```
I have tried two different Windows 10 machines and 3 browsers (Firefox, Chrome and Edge), all with the exact same result.

This is what I actually see in the browser:
![image](https://user-images.githubusercontent.com/7589164/28735491-8d4c1db8-7439-11e7-8992-8727399a1910.png)

I have also rebooted all my networking hardware and flushed caches.

I am based in New Zealand but I have spoken with people using Reviewable in other countries and they're *not* seeing this issue. So possibly this is an issue with a local content distribution network?

Thank you!

**Comment by pkaminski** [comment]
Huh, I guess one of Fastly's edge nodes in NZ got a bad deploy.  I tried rolling back to the previous version and forward again to bounce things but I have no idea if it'll help, since I don't know how Fastly's purges/deploys work.  Is it working now?  If not, I'll try deploying a new version with some trivial difference.

**Comment by PlagueHO** [comment]
Hi @pkaminski - that fixed it! Way to go :grin:

Thanks very much for the awesome fast response! Closing issue.
