### ISSUE TITLE
Presentation of symlinks is confusing

### ISSUE THREAD

**Issue by ggould-tri** [Reviewable/Reviewable#496]
When an author commits a unix symlink, reviewable presents the actual text of the symlink without any indication that this is a special file.  This is confusing to reviewers, and will be doubly so for those who do not know the details of how symlinks work (ie, that a symlink is in fact a regular file containing the name of its target with no terminal newline).

Reviewable should probably present files with git file mode `120000` differently.

**Comment by dwsjax** [comment]
Someone is using my accounts and made himself admin

**Comment by pkaminski** [comment]
Agreed.  If you happen to have it handy, could you paste in a screenshot of how GitHub handles those diffs?  Thanks.

**Comment by ggould-tri** [comment]
Surprisingly, github has exactly the same confusing presentation.  So on the one hand it's no worse than theirs, but on the other hand it's a chance to get ahead of them :smile:.

(I can't send you a screenshot, unfortunately, as this is from a proprietary repo)

**Comment by pkaminski** [comment]
Heh, no problem, I thought maybe they were doing something smarter already.  😛

**Comment by pkaminski** [comment]
Note: related to #462, as both require the file mode to be captured.

**Comment by pkaminski** [comment]
This should be fixed going forward (not retroactive).
