### ISSUE TITLE
formatting issue with nested string interpolation (JS/TS)

### ISSUE THREAD

**Issue by levilansing** [Reviewable/Reviewable#498]
Nested string interpolation causes the code formatting to be wrong for the rest of the file. In this example, the code formatting believes there are two separate interpolations (rather than 2 nested), where the second one doesn't end, so the remainder of the file will be formatted as if it's inside a string.

```
`hello ${foo ? `Mr ${name}` : 'there'}`;
<---------- 1 ------------>           <- 2 -...
```

**Comment by pkaminski** [comment]
I'm unable to reproduce this.  If you take a look at https://reviewable.io/reviews/pkaminski/sample/6#-, file `bar.js` at `r5`, it looks to me like everything's getting highlighted correctly.  Can you point me to a PR that demonstrates the issue, or see if you can reproduce it directly with HighlightJS, e.g. building on https://jsfiddle.net/q19sxnd3/ ? Thanks.

**Comment by levilansing** [comment]
Ahh, looks like my example only works in TS. I just assumed JS has the same problem- my mistake. Here are a couple examples:

https://reviewable.io/reviews/levilansing/reviewable_formatting_test/3#-

Looks like the issue is in HighlightJS. Was able to repro once I added in the typescript formatting: https://jsfiddle.net/91twpfa2/2/

**Comment by pkaminski** [comment]
Thanks, reported upstream.  Hopefully a fix will come sometime soon.

**Comment by rictic** [comment]
This should be fixed now in the latest highlight.js release.

**Comment by pkaminski** [comment]
I've updated highlight.js to 9.15.10.  Presuming this bug is fixed -- closing.
