### ISSUE TITLE
PR assigned to team not appears on Reviewable dashboard

### ISSUE THREAD

**Issue by premist** [Reviewable/Reviewable#499]
I recently changed review workflow on our repo to team oriented so everyone on the team can give a review to PRs without needing to assign specific person.

![screen shot 2017-08-23 at 12 07 55 pm](https://user-images.githubusercontent.com/291078/29597146-b8468db6-87fb-11e7-8f17-3cf1cd6cc0f9.png)

However, it seems like members on the team can't see requested PRs on reviewable.io dashboard's "Involving me" section.

**Comment by pkaminski** [comment]
You're right, this doesn't work right now for two reasons.  One is that Reviewable just doesn't integrate with GitHub's review system at all, including in the PR list (see #497).  Two -- and more seriously -- GitHub queries don't seem to have a filter for selecting PRs to be reviewed by a team!  I tried using `review-requested:`, `reviewed-by:`, and `team:` but none of them selected a test PR where I added a team as a reviewer.  Maybe I'm missing something -- can you figure out how to do it?

**Comment by premist** [comment]
I get emails about the PRs that my team is assigned on, but like you mentioned seems like it's not accessible by API or webhook. I tried to use GitHub's GraphQL API to see if it's possible, but it returns `reviewRequest` object with `reviewer: null` which is useless.

![image](https://user-images.githubusercontent.com/291078/29600540-82d3ccc8-8811-11e7-8ced-d32215317d9b.png)

**Comment by premist** [comment]
Are there any practices on asking for reviews for other team members?

**Comment by pkaminski** [comment]
I pinged GitHub support about queries -- we'll see if they come up with something we missed.  In the meantime, as long as you don't need a formal review request for purposes of branch protection, I'd recommend just @-mentioning the team in the PR description or a comment.  This will get it into the team's mailbox and also have it show up on Reviewable's dashboard for members of that team.

**Comment by premist** [comment]
Sounds good. I just notified team members to tag a team on comment whenever they create a new PR. Since Reviewable is already required branch protection check for all pull requests, it should be fine. Thanks for the suggestion!

**Comment by pkaminski** [comment]
It turns out there's an undocumented `team-review-requested:org_name/team_name` query clause, so I'll be able to add this to Reviewable after all.

**Comment by premist** [comment]
Awesome!

**Comment by c-andy-martin** [comment]
I would very much like to see this feature added to reviewable

**Comment by pkaminski** [comment]
This is now live on the beta: PRs will appear in the "involving my teams" section, along with @-mentions of your teams.  GitHub's queries normally only consider direct membership but I added a workaround so that your ancestor teams will also be taken into account, in case you're using team nesting.
