### ISSUE TITLE
"Review each commit separately" only produces one revision for many commits

### ISSUE THREAD

**Issue by SimonSapin** [Reviewable/Reviewable#502]
https://reviewable.io/reviews/servo/servo/18533
![screenshot from 2017-09-18 14-19-39](https://user-images.githubusercontent.com/291359/30541768-01438aec-9c7d-11e7-9b30-053d645756be.png)

Switching to "combine commits for review" and back doesn’t help.

**Comment by pkaminski** [comment]
Hey Simon, this is expected:  Reviewable limits the number of revisions it will create for any given push to avoid overloading both the servers and the UI.  This number is typically 20 in "review each commit" mode, and I already raised it to 30 for `servo/servo`.  I could probably raise it higher still but I don't think dealing with 37 revisions would be practical in the current UI...

**Comment by SimonSapin** [comment]
Thank for raising the limit. This might help in the future.

I agree that the UI tends to become impractical, but for what it’s worth having a limit still is unfortunate because many-commits PRs are the ones where looking at commits separately and tracking which commit has been reviewed is especially valuable.
