### ISSUE TITLE
Help tooltips still "pop" on hover when animated transitions are disabled

### ISSUE THREAD

**Issue by aboyett** [Reviewable/Reviewable#505]
While trying out Reviewable, several colleagues have commented on the busy nature of the UI which can be confusing while trying to understand an unfamiliar system (especially when coming from the Spartan UI of Gerrit's GWT interface.)

I suggested they disable animated transitions which has mostly helped, however there appear to be several elements that still animate/move in some way. The first one I've been able to identify is the tooltip containing "F1" and "?" that appears on hover still performs it's little grow and shrink animation when appearing even when animation transitions are disabled by the user. Could this effect also be disabled when animations are disabled?

**Comment by pkaminski** [comment]
Yep, looks like an oversight on my part.  Will fix.

**Comment by pkaminski** [comment]
Fixed.  The tooltip now pops up with no animation, though honestly I'm not sure if it's significantly less distracting than the previous behavior.  Perhaps I should keep a fade-in even when animations are disabled, like I do when it appears in the bottom-right corner of the window instead?
