### ISSUE TITLE
"Allow edits from maintainers." is unchecked by Reviewable

### ISSUE THREAD

**Issue by asashour** [Reviewable/Reviewable#508]
Noticed in Vaadin project, when a [PR](https://github.com/vaadin/framework/pulls) is created with "Allow edits from maintainers.", then when it is changed by `Reviewable`, the status is always set back to unchecked.

**Comment by pkaminski** [comment]
Thanks -- reproduced.  This appears to be a bug in the GitHub API.  I've raised it upstream and will report back here with the resolution.

**Comment by pkaminski** [comment]
GitHub acknowledged the bug but declined to fix for now so I've implemented a workaround.  Should be working fine now -- please let me know if you find otherwise.

**Comment by asashour** [comment]
Thanks a lot for your quick response, it works fine now.
