### ISSUE TITLE
Allow commenting on files that are not changed in the PR

### ISSUE THREAD

**Issue by smondet** [Reviewable/Reviewable#51]
It would be nice to be able to "add" files to the review even if they are not part of the initial diff.

**Comment by pkaminski** [comment]
Hi Sebastien -- this seems somewhat outside Reviewable's remit but it might be possible.  What's the use case and how common is it?  Is the workaround of making a trivial no-op change to the file and pushing it to the PR sufficient?

**Comment by smondet** [comment]
The no-op change would be messy (it would make the git history artificially dirty).

And it can be the reviewer's initiative to add a file:
in order to comment on something that did not change (for example some place where a change is missing, or some inconsistency with other changes).

The other use-case is to do "snapshot" code reviews (i.e. a discussion based on the global state of a given work-in-progress branch, instead of just a "merge proposal").

**Comment by pkaminski** [comment]
OK, that's fair.  I'll put this on the to-do list but to be honest it's not a very high priority right now, as it would require a bunch more UI and GitHub API integration.  For now it's probably easiest to mention the file in another comment and let the author's subsequent change add the file to the review.

**Comment by pkaminski** [comment]
This is sufficiently outside the scope of Reviewable's primary use case, would significantly complicate the code if added, and can be worked around as described above, that I'm going to take it off the to-do list for the time being.

**Comment by adam505hq** [comment]
Would be nice. Sometimes changes introduced by author of PR require changes in other parts of the code. Then suggestion for other files or even other repos would be great.
