### ISSUE TITLE
New discussion semantics

### ISSUE THREAD

**Issue by pkaminski** [Reviewable/Reviewable#510]
The ad-hoc evolution of the discussion system has left it a bit of a confusing mess and I've been mulling over some simplifications and improvements.  I'm recording the proposal here for feedback and ultimately as a spec to follow when I implement this.  I believe this new approach is overall easier to grok and covers all the important workflows I can think of.  Did I miss anything?

Also cc'ing some people who previously offered ideas or concerns about discussion management:  @david-german-tri, @kballard, @sherriman, @tricket, @jdm, @kleptine, @fearphage, @davidmason, @nictuku, @marczych, @florianjourda, @trainman419, @mikesokolsky, @nicolasartman, @adyates.  (Apologies if you're no longer using Reviewable or not interested!)

---

### Executive summary

The Discussing disposition becomes simply "I'm not gonna resolve it, but you're welcome to".  Resolution is driven solely by dispositions; the invisible state that determined "OK" and "Not OK" is gone.  Comment prefixes (such as "FYI") now just change the disposition.  Disposition changes and acknowledgements must be published to commit them, even if made without a corresponding comment.  A new Working disposition lets you block a discussion and mark it as something you need to come back to.  A new Informing disposition lets you start a resolved discussion that will reach everyone.

### Dispositions

The disposition system stays but the meanings are tweaked.  The dispositions that make you an active participant are:
- Satisfied: the discussion is resolved and finished, as far as you're concerned.  Cannot be selected when starting a new discussion.
- Informing: the discussion is resolved but still active.  Can only be selected when starting a new discussion.
- Discussing: the discussion isn't resolved but you're OK with somebody else resolving it.  There's no longer a way to say "OK to resolve unless somebody else makes a comment", which was (roughly) the previous definition of Discussing.
- Working: the discussion isn't resolved until you finish working on something (used to flag a discussion for you to come back to after you finish something offline; takes priority over Blocking).
- Blocking: the discussion isn't resolved and you want the final say.

Passive participants encompass the other dispositions: Following, Mentioned, and Dismissed.  The Withdrawn disposition is retired since Satisfied now performs its function, and Informing works as the old Satisfied when specified on a new discussion.

Disposition changes will be buffered as a kind of draft and will only be applied when publishing, just like marking a file reviewed.  Disposition changes do not mark the discussion as read unless they are part of a reply.

Only active participants can be dismissed, and doing so only requires push permissions (not admin).

### Resolved and unreplied

A discussion is resolved if and only if at least one participant is Satisfied and none of the participants are Working or Blocking, or if there are no active participants left.  (Participants who are Discussing are essentially abstaining from the decision.)

An unresolved discussion is unreplied for you (counted as red) if one of the following rules applies and none of the preceding rules apply to anybody else.  A resolved discussion is unreplied for you only if rule 1 applies.
1. You are a participant or one of the participants is Informing and you have unread comments (even if the discussion is resolved), or you are Working.
2. You are the PR author and the discussion has only one active participant (who isn't you).  This applies even if you have no unread comments, i.e. you acknowledged the discussion without replying.
3. You are not the PR author, the discussion has only the PR author as active participant, and you have unread comments.
4. You are Blocking and the last comment is not yours.
5. You are Discussing and the last comment is not yours.
6. You are Blocking.
7. You started the discussion and are still an active participant.
8. You are an active participant.

If you have draft state on the discussion (a reply, etc.), the future value is used when computing the resolved state in your view.  The discussion is also considered replied &mdash; even if the draft state will cause it to become unreplied for you once published &mdash; unless you have unread comments newer than your draft reply or acknowledgement.  Your published state is still used in all other participants' views.

### Acknowledge button

The Acknowledge button becomes contextual, depending on your role and the discussion's state.  It always marks the discussion as read but can have additional effects based on the first applicable line in the table below:

| Role | Discussion | Button label | Effect |
| ----- | --------- | -------- | ------ |
| Informing | Resolved with no other participants | Retract | Sets disposition to Satisfied. |
| Informing | Resolved | Conclude | Sets disposition to Satisfied. |
| Active participant, not Satisfied | Unresolved with no other participants | Retract | Sets disposition to Satisfied. |
| Not Satisfied | Unresolved and switching to Satisfied would resolve | Resolve | Sets disposition to Satisfied. |
| PR author not Satisfied, or anyone Working | Unresolved | Done | Sets disposition to Satisfied and creates a "Done." message. |
| Blocking | Unresolved and nobody Working | Accept | Sets disposition to Satisfied. |
| Any | Unread comments | Acknowledge | Sets disposition to Following if passive participant or not a participant. |

Additionally, the New Comments ribbon gets a small "mark as read" link added to it, in case you want to do so without messing up your disposition.

Marking comments as read (explicitly or in conjunction with a reply) when you're an active participant is now also buffered, and applied only when Publishing.  This avoids situations where a discussion shows up as unreplied to somebody else before your reply was published, due to rule 4 or higher above.

### Comments

A comment that creates a new discussion will default the disposition to Blocking.  A user's first reply to an existing discussion will default the disposition to Discussing if not already an active participant.  Both defaults can be persistently overridden per-user, per-situation (initial / reply comment as reviewer / author).

If a comment starts with one of the following keywords it will set the corresponding disposition (ignoring the defaults and default overrides above), unless manually changed by the user for that comment:

| Prefix              | Initial comment | First reply    | Subsequent reply |
| --------------- | ------------------ | ------------- | ------------------- |
| FYI, BTW         | Informing           | Discussing   |                              |
| Minor, Nit       | Discussing         | Discussing   |                              |
| OK, Done, LGTM |                       | Satisfied       | Satisfied              |
| Working, Will do | Working            | Working       | Working              |

### Transition plan

Most of the semantics are either new or close enough to the old ones that they shouldn't cause any adjustment issues.  However, the definition of Discussing is changing such that discussions that may have required a user's input to resolve before will no longer do so, which would upset reviews in progress.

To handle this, Reviewable will automatically convert Discussing dispositions as follows when syncing a review (e.g., when a review is loaded, when an event is triggered for a connected repo, etc.):
- Discussing/Not OK ⇒ Blocking
- Discussing/OK and discussion resolved ⇒ Satisfied
- Discussing/OK and discussion unresolved ⇒ Discussing (and flagged so it doesn't get converted again)

This will be a minor annoyance for people still using the old UI since they'll need to explicitly switch dispositions to resolve a discussion (instead of just hitting Acknowledge) but should otherwise be as semantically backwards- and forwards-compatible as possible.

For reviews that haven't been upgraded yet, the old semantics will be respected as much as possible when computing resolution and red counts -- this matters for the reviews dashboard, since it doesn't trigger syncs.  Eventually, after a few months to a year (to give Enterprise customers time to upgrade), the old algorithm will be removed altogether.

**Comment by kballard** [comment]
BTW, haven't read the proposal yet, but you should change 🡒 (U+1F852 RIGHTWARDS SANS-SERIF ARROW) to something else (perhaps →), because 🡒 isn't present in any font shipped on macOS.

**Comment by pkaminski** [comment]
Gah, OS X strikes again.  Changed to U+21d2 RIGHTWARDS DOUBLE ARROW -- is that one supported?  (I don't like the basic arrow because the arrowhead is too small in my default font, so it almost looks like a dash.)

**Comment by kballard** [comment]
Yeah that works.

**Comment by kballard** [comment]
Ok, I gave this a quick read, and overall, I think it's a good plan.

Is there any practical difference between Working and Blocking besides the Acknowledge button? I realize there is a semantic difference, I'm just trying to figure out if I missed a behavioral difference.

> Additionally, the New Comments ribbon gets a small "mark as read" link added to it, in case you want to do so without messing up your disposition.

🎉

**Comment by pkaminski** [comment]
> Is there any practical difference between Working and Blocking besides the Acknowledge button? I realize there is a semantic difference, I'm just trying to figure out if I missed a behavioral difference.

Yes -- this one was actually specifically for you!  😄  If a reviewer starts a discussion as Blocking and the reviewee replies as Working then, after the reviewer acknowledges the reply, the discussion will only show up as unreplied for the reviewee.  If the reviewee replied as Discussing then the discussion would remain allocated to the reviewer per rule 4.  So basically, Working takes priority over Blocking when deciding whose red counter to increment.

**Comment by kballard** [comment]
Oh awesome, that does sound exactly like what I want!

> A comment that creates a new discussion will default the disposition to Blocking. [Should this default be different for discussions initiated by the PR author?]

Probably not. I don't know what else you'd default it to for PR authors, and it might be confusing to have different defaults.

**Comment by johlju** [comment]
>A comment that creates a new discussion will default the disposition to Blocking. [Should this default be different for discussions initiated by the PR author?]

Maybe this is the intended behavior...

Most of the the time if a PR author initiates a discussion it’s because to say maybe “does this look okay?” or “Should we do this differently?”  So a PR author discusses instead of blocking his own PR. I as the reviewer would like to write a reply as either discussing, blocking, working or satisfied (resolve). 
The PR author could also say “I made this line better!” and as the reviewer I would like to be able to acknowledge (resolve) the discussion because I felt there was no need to comment on it.

**Comment by kballard** [comment]
As a PR author if I'm commenting on my own PR, it's either because I want to ask a question of someone else ("does this look ok?"), which I'm expecting an answer to and therefore it won't get resolved until I'm done with it anyway (so Blocking is fine), or it's because I just want to call out something for reviewers to see, and that discussion definitely shouldn't get resolved until the reviews are over (which means Blocking is correct).

As a PR author, if I want some other disposition I can certainly set that on my comment.

**Comment by pkaminski** [comment]
It sounds like at a minimum this default should be separately overridable (i.e., initial comment as reviewer, initial comment as author, and initial reply).  The remaining question then is what's the most commonly desired initial disposition for an author-initiated discussion, and if it's not Blocking whether it's worth breaking consistency with the reviewer-initiated default.

My intuition is to stick with Blocking, if only to avoid the potential surprise of having one's question resolved away and disappearing with no reply when one doesn't understand the disposition system very well yet.  The "look, isn't this nice" use case is adequately handled by using the BTW or FYI prefix, I think (or explicitly changing the disposition on the draft, of course).

**Comment by johlju** [comment]
We should make it easy for new users, if your opinion is that Blocking is that, then I’m happy with that.

**Comment by kballard** [comment]
I think the best thing for new users is to have the default be the same for PR authors as for other reviewers.

**Comment by davidmason** [comment]
@seanf @aeng @djansen-redhat this looks relevant to the team, you might want to have a read.

**Comment by dsmilkov** [comment]
Curious what's the timeline on this? The [TensorFlow.js](https://js.tensorflow.org/) team uses Reviewable and would benefit greatly from a simplified discussion state. E.g. if the default state is: the PR author can easily resolve comments left by the reviewer without having the reviewer go back and explicitly resolve the comment. If the reviewer wants to come back, it leaves a special type of comment. Right now, a lot of the PR authors reply with Done/Ack/Sounds good/Thanks! but that wont trigger the comment to fully resolve.

**Comment by pkaminski** [comment]
What do you think about "Consulting"?  To me it implies both non-blocking and a wider distribution.

**Comment by kballard** [comment]
"Consulting" does not make much sense to me. Maybe "Advisory", or "Commentary"?

What's the grammatical context here? Right now the disposition dropdown says "After sending this comment you'll be:". Will it still say it that way? Because the existing "Discussing", "Satisfied", and "Blocking" names are descriptions of your state, but "Aside", "Digression", etc. are just nouns. "Consulting" would be a state description, except the name just doesn't give me any idea as to its meaning.

I suppose you could list it as "Non-Blocking", though the issue with that is since there's an explicit "Blocking" state, the other states are implicitly non-blocking already.

**Comment by nicolasartman** [comment]
I think both Consulting and Noting are good choices. The disposition dropdown would then read "After sending this comment you'll be: Noting/Consulting" as in "Noting this" or "Consulting with the team."

**Comment by kballard** [comment]
"Consulting" sounds like it's the same thing as "Discussing". These BTW comments are things that don't actually need any response from other people or any followup from you, so you're not actively consulting on them, you're just leaving a note.

**Comment by johlju** [comment]
I sometimes make a 'Satisfied' comment starting with text "Non-blocking: " when I suggest something that would be good/recommended to have/do, but will not hold the PR if it's not done. So "Informing" or "Suggesting" maybe? 

/cc @PlagueHO

**Comment by johlju** [comment]
@pkaminski I always use the Withdrawn disposition when I review my own work. I make review comments (publish), I make 'Done' comment on them when I'm done (and publish) then I withdraw the comment (each step can be a day or days in-between). This is so the correct workflow is used even when there are no community reviewer to review my own PR's. Will that still work (even if the dispositions to be used might have changed)?

**Comment by nicolasartman** [comment]
Interesting—I was thinking of Aside/Noting/Consulting as a way to solicit feedback from the team, initiated by the reviewee.

For example: E issues a pull request and asks R to review it. E notes that they're unsure about their use of "word-break: break-word" in some CSS. R posts a reply of "use overflow-wrap: break-word, because CSS is silly" and either resolves it, or leaves it open since others may need to weigh in before it's updated and resolved.

If that can be handled by opening a comment with "Discussing" status, then something like Noting seems good for this and I agree that consulting doesn't seem to fit. If not, then having something that covers that case and likely has a name like Consulting would be great.

**Comment by pkaminski** [comment]
So the state I'm trying to describe is one where the discussion is resolved (by default -- somebody could still choose to block it if they want to) but everybody continues to be pinged with updates.  It differs from Satisfied because that won't ping updates to people not already in the discussion.  It differs from Discussing because it makes the discussion resolved by default (rather than being neutral, and hence requiring an extra Satisfied to resolve).  So it could be used both for notifications (resolved but everybody sees it) and for non-binding consultation (everybody is welcome to chime in but it doesn't block the review).

I'm not sure if there's a single word that could encompass both these intents, but that's where my initial ideas of Aside and Background came from.  (Though neither of those fits grammatically into the "You are / After publishing you will be / XX is" context, which I intend to keep.)  Naming is hard.

**Comment by pkaminski** [comment]
@johlju Yes, your workflow should still be fine.  In fact, clicking Done will now automatically switch your disposition to Satisfied (which will have an effect equivalent to the old Withdrawn) so there'll be one less step.

**Comment by johlju** [comment]
> So the state I'm trying to describe is one where the discussion is resolved (by default -- somebody could still choose to block it if they want to) but everybody continues to be pinged with updates

@pkaminski I thought something along the lines 'remittance' but that is like discussing too. What about just 'commented' or 'statement of opinion'?

**Comment by johlju** [comment]
@pkaminski In the end, I guess you have to go what you feel is most appropriate, and when we start work with it maybe we find a better word to use. 🙂

**Comment by pkaminski** [comment]
I've finally decided to bite the bullet and release this.  Please help test over the weekend if you're around, especially on reviews started under the old semantics -- thanks!

**Comment by gkaempfer** [comment]
I believe we're stuck in infinite review loops. Everything is acknowledged/green/LGTM/satisfied but the "drafts" is red (with zero drafts) and there is a message stating "1 disposition change and 1 acknowledgement to send". We're unable to resolve this or merge...
I opened issue #556
