### ISSUE TITLE
Add review for commit messages

### ISSUE THREAD

**Issue by mnonnenmacher** [Reviewable/Reviewable#512]
It should be possible to review commit messages the same way as file changes can be reviewed, with opening a discussion for this specific commit message. Otherwise it is hard to discuss required changes in commit messages, especially in PRs with many commits.

**Comment by pkaminski** [comment]
Please see #507.

**Comment by mnonnenmacher** [comment]
Sorry, I should have checked the closed tickets better. I still think treating commit messages like file changes would be benefitial for the tool, but maybe it's impossible to do it right if you don't rely on something like Gerrits Change-Id.
