### ISSUE TITLE
File matrix scroll bar hidden

### ISSUE THREAD

**Issue by bstaletic** [Reviewable/Reviewable#514]
When a PR has too many revisions for the file matrix to fit on the screen, the file matrix get a horizontal scroll bar. However, this bar is hidden behind other web page elements.

Observed with [this pull request](https://reviewable.io/reviews/Valloric/ycmd/857#-).

**Comment by pkaminski** [comment]
Acknowledged.  Since this is a fairly rare situation and I intend to rewrite that part of the UI from scratch anyway, I think I'm going to let it go for now.
