### ISSUE TITLE
Add ⌘⏎ shortcut for previewing+blurring a comment

### ISSUE THREAD

**Issue by ryan-williams** [Reviewable/Reviewable#52]
I rely on this shortcut heavily on github; it works in all text-compose fields there I think? e.g.

![](http://f.cl.ly/items/1V0T1d3L1m3n1n3n0H2q/Screen%20Shot%202015-02-27%20at%201.29.31%20PM.png)

**Comment by danvk** [comment]
Ryan & I chatted about this—we'd both be happy if ⌘⏎ / ^⏎ were aliases for preview + defocus. For people coming from Gerrit/Rietveld/GitHub, it feels a bit uncomfortable to have all those editable text fields live on the page.

**Comment by ryan-williams** [comment]
what @danvk said

**Comment by pkaminski** [comment]
I can provide a bindable command for "send comment now" but I won't add it to the hotkeys by default, as it's not an action I want to encourage.  It sounds like that's not really what you want anyway.

Can you expand on why having text fields on the page is uncomfortable, other than you're not used to it?

What would be gained by having a "preview + defocus" command over the current "preview"?  Having a comment (in preview mode) focused doesn't seem like a big deal, especially since if you're a keyboard-centric user you'll probably immediately hit "j" to jump to the next one anyway.

**Comment by ryan-williams** [comment]
is there a hotkey for "preview" that I can use when I'm done typing a comment?

**Comment by pkaminski** [comment]
Sure, same as on GitHub -- it's even listed in the cheatsheet.

**Comment by ryan-williams** [comment]
Cool. Thoughts on making ⌘⏎ also do that?

**Comment by pkaminski** [comment]
No, as most people would expect that to send, but you can easily do it yourself.  :smile:  https://github.com/Reviewable/Reviewable/wiki/FAQ#can-i-customize-the-key-bindings (also linked from bottom of cheatsheet)

Please let me know if this resolves the issue.

**Comment by ryan-williams** [comment]
OK I'll try that, thanks

**Comment by ryan-williams** [comment]
while we're here, ⌘⇧P is not working for me to generate a preview of a comment I'm writing right now, and I can't figure out why

Here's a screengrab:

![](http://f.cl.ly/items/241l0W3A0A0i1E3K1V1N/Screen%20Shot%202015-02-27%20at%202.53.32%20PM.png)

**Comment by pkaminski** [comment]
I think that's #48, sorry.  Will get to that early next week.

**Comment by danvk** [comment]
I've tried to set this up by pointing Reviewable at this gist:
https://gist.githubusercontent.com/danvk/cdb92d27f4092697ade9/raw/bindings.json

I can hit Cmd-Shift-P while drafting a comment (as usual), but Control-Enter and Command-Enter have no effect. I _am_ seeing them listed when I hit '?', so they are being loaded:

![screen shot 2015-03-04 at 2 23 23 pm](https://cloud.githubusercontent.com/assets/98301/6491273/1a9d4e40-c27a-11e4-825d-52e39a2c52eb.png)

any idea what's going on?

**Comment by pkaminski** [comment]
I tried your gist in Chrome / Windows and the shortcut works fine, not sure what's going on.  Perhaps something Mac-specific?  I'll ask a friend with a Mac to take a look.

Note that "mod" will resolve to ⌘ on a Mac and ctrl on Windows, so you don't need to specify "control" explicitly.  Also, you can just add the shortcut to the existing toggle command like so:

```
[["mod+shift+p", "mod+enter"], "Toggle draft preview", "toggleCurrentDraftPreview()"],
```

**Comment by danvk** [comment]
Thanks for following up. I'd like both ⌘⏎ _and_ ^⏎  to toggle the preview, so maybe I should just avoid "mod" altogether.

**Comment by pkaminski** [comment]
Ah, OK.  In that case you should use the "command" and "ctrl" modifiers
("control" is not a thing).

On Wed, Mar 4, 2015 at 12:01 PM, Dan Vanderkam <notifications@github.com>
wrote:

> Thanks for following up. I'd like both ⌘⏎ *and* ^⏎ to toggle the preview,
> so maybe I should just avoid "mod" altogether.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/52#issuecomment-77234498>
> .
>



-- 
Piotr Kaminski, Founder, reviewable.io

**Comment by danvk** [comment]
OK, it's working for me now, though inconsistently. But perhaps that's just #48.

**Comment by pkaminski** [comment]
Cool, if it's working at all then it's not a bindings issue.  Getting to #48 soon, need to fix some race conditions in the subscriptions code first...
