### ISSUE TITLE
Reviews that I've been assigned to, and then removed from, still show up as "assigned to me" rather than "involving me"

### ISSUE THREAD

**Issue by macmason-tri** [Reviewable/Reviewable#520]
Order of events:

1. Somebody assigns me a review (+@me).
2. Somebody else removes me from the review (-@me, +@themselves, in this case).
3. The review remains in my "assigned to me" section, rather than "involving me" (which is where it seems like it should be).

Other facts:
1. The pictures alongside the review show up correctly.
2. The scripts that determine if merging is permitted work correctly.
3. This is stable across hard refreshes in my browser.

So I think it's just a bug in how the sections are populated.

**Comment by macmason-tri** [comment]
An enterprise instance. @jwnimmer-tri knows more of the details.

**Comment by pkaminski** [comment]
OK, that's still on the stable stream then.  I've revamped the internals of this page heavily in the beta stream so it's probably best to wait until this reaches Enterprise and check again, likely in late February or early March.

**Comment by macmason-tri** [comment]
Sounds good.

**Comment by pkaminski** [comment]
The new dashboard now uses the same data for the avatars as it does for categorization, so I'm confident this will be fixed when the beta rolls out.
