### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by christensonb** [Reviewable/Reviewable#521]
A reviewer posted a review that an empty file should be removed.
Before seeing that review I posted a commit that had removed the file.

Reviewable won't let me acknowledge his commit, and it hangs on loading the deleted file, and it won't let me publish.

Eventually it would let e reload it correctly.

**Comment by pkaminski** [comment]
Sounds weird.  Could you please point me to the review/PR?  Were you using the stable version or the beta (beta.reviewable.io)?

**Comment by pkaminski** [comment]
Closing due to lack of details.
