### ISSUE TITLE
We would like to be able to completely ignore certain paths from being reviewed / diffed

### ISSUE THREAD

**Issue by kidoman** [Reviewable/Reviewable#526]
We vendor all our Go libraries. Included behemoths like `cloud.google.com/go` and family. Every once in a while, we update these libraries and that completely breaks the Reviewable UI / experience.

We had a review recently, which had over 1079 files to be reviewed, with the majority of the files lying under the path `src/vendor`.

We created a file called `.gitattributes` under `src/vendor` with contents:

```
* -diff
```

but this didn't help much. We also added a custom review done condition (as suggested by P):

```
_.forEach(review.files, file => {
  if (_.startsWith(file.path, 'src/vendor')) {
    _.forEach(file.revisions, rev => {
      rev.reviewed = true;
    });
  }
});
```

This helped but is not a complete solution (as written by P).

We would like to be able to cleanly ignore these files (and the folder `src/vendor`) from within Reviewable.

**Comment by pkaminski** [comment]
Closing in favor of #527.
