### ISSUE TITLE
Redirection to beta with an error

### ISSUE THREAD

**Issue by Seybo** [Reviewable/Reviewable#528]
I often get redirected to beta.reviewable and getting this error there
![image](https://user-images.githubusercontent.com/10584167/37699101-de6abcd2-2d0b-11e8-8f72-b90a914cfa4e.png)
Then i have to manually remove `beta.` from the address bar and it loads the page without redirect to `beta` anymore. And there is no error.
But next time it redirects again. And I don't understand how to avoid it. Is there a way?

**Comment by pkaminski** [comment]
Thanks for reporting the bug, I'm going to look into it tomorrow. In the
meantime, you can append `?stable` to a Reviewable URL to prevent the
random redirect to the beta.

**Comment by pkaminski** [comment]
So at first glance this exception doesn't get thrown from within the core app code.  However, I have a suspicion:  are you blocking Mixpanel in your browser by any chance?  There's a bug in their code that can throw spurious top-level `SyntaxError`s, though previously it only manifested in Safari and I can't reproduce it in Chrome with uBlock Origin active on my own machine.  Nonetheless, I have a [fix pending](https://github.com/mixpanel/mixpanel-js/pull/170) that they said they'd pull this week.

If possible, could you try loading https://beta.reviewable.io with your ad blocker (or all extensions) disabled to confirm this diagnosis?  Thanks!

**Comment by pkaminski** [comment]
https://beta.reviewable.io now has the Mixpanel fix integrated -- please let me know if this addressed the issue.  Thanks!

**Comment by Seybo** [comment]
Hey! No, it didn't work. But i've found a plugin that causes the problem.
Here it is: https://chrome.google.com/webstore/detail/vk-music-%E2%80%94-download-music/jdnmpoggedgajbelgfgmlogehjkkfilp

**Comment by pkaminski** [comment]
Ah, OK.  Looks like that extension leaks exceptions to the top level, which Reviewable intercepts and, since it's nigh-impossible to determine who caused the error, shuts down as a precaution.  Sorry, but you'll either need to get the extension fixed or disable it to work with Reviewable.
