### ISSUE TITLE
Require all assignees to sign off a file before it's marked as reviewed

### ISSUE THREAD

**Issue by faern** [Reviewable/Reviewable#530]
We have a workflow where we usually have multiple reviewers. We want everyone assigned on a PR to have reviewed and accepted every file and every discussion before we merge. But reviewable seems to classify a file as reviewed as soon as one of the assignees checks a file.

Is there any way to configure this?

**Comment by pkaminski** [comment]
Yes, you can do this by creating a custom review completion condition.  If you visit the settings panel for your repo (by clicking on its name on the Repositories page) you'll see some sample code and the data it operates on.  The second example condition in the drop-down menu is closest to what you're looking for: it checks that every file has been reviewed by every designated reviewer (either the requested reviewers, or assignees if no requests).  You can teak it to always use assignees, and extend it to perform a similar check on the discussions by checking that all assignees are participants in every discussion, and consider the discussion to be resolved.

I'm going to close this issue but please don't hesitate to ping back with any questions once you've gotten your feet wet.
