### ISSUE TITLE
Can't load any reviews (Cannot read property 'pull' of undefined)

### ISSUE THREAD

**Issue by mgalgs** [Reviewable/Reviewable#531]
As of about 10 minutes ago I haven't been able to get any reviews to load.  I've been using Reviewable for a long time and haven't seen this issue before.

The error message is:

```
Error: Permission check for directangular/unicorn failed: Cannot read property 'pull' of undefined
```

This is a private repository.  I'm signed in and can view the PR on GitHub just fine.

I'm able to reproduce the error every time I load any PR.  I've tried two different private repos and they're both having this same issue.

I've also tried from an Incognito window and see the same issue (after signing in to GitHub).

**Comment by al-the-x** [comment]
Maybe @pkaminski's auth token between Firebase Auth and GitHub was revoked / expired?

**Comment by belden** [comment]
This is resolved for me now.

**Comment by mgalgs** [comment]
Seems to be fixed.

**Comment by pkaminski** [comment]
GitHub had a major regression in their API.  There was nothing I could do, and the app should've put up a GitHub warning sign on the page as soon as GitHub announced the issue on https://status.github.com/messages around 12:02 PDT.  Sorry in any case!
