### ISSUE TITLE
Too big change causes Reviewable to crash the tab

### ISSUE THREAD

**Issue by tsuoanttila** [Reviewable/Reviewable#533]
We had a recent change in one of our project that touched a number of files. The changes are not big, but opening this in Reviewable makes the Chrome tab crash. Tested also with Firefox, but end result was the same. Most likely out of memory error.

The same size PR used to work in the older Reviewable, but since going all `beta.reviewable.com` I can't review the change.

**Comment by elmot** [comment]
Here it is
https://beta.reviewable.io/reviews/vaadin/framework/10762#-

**Comment by tsuoanttila** [comment]
The actual review was done using command line `git` and `grep -E`, but had to be able to access Reviewable enough to mark them reviewed. And unfortunately for us, the old UI was just disabled, so we actually had to temporarily remove the review requirement to be able to merge. If we run into similar performance issues, we'll ping again!

We know it's not designed for such big reviews, thanks for looking into it anyway!

**Comment by pkaminski** [comment]
FYI, the old UI is still accessible for now by appending `?stable` to a URL -- I mentioned this in the beta announcement but it was easy to miss I guess.

**Comment by elmot** [comment]
One more PR to profile your code. It takes minutes to be loaded
https://reviewable.io/reviews/vaadin/framework/10962.
We do not open a bug because it is loaded after several minutes.

**Comment by pkaminski** [comment]
Thanks @elmot, this helped me locate three separate performance regressions, one of which was deep in the infrastructure!  Should be better now, though still not _fast_ given that there's ~3000 files in the PR.
