### ISSUE TITLE
Clicking "Acknowledge" occasionally pins browser to top of review page

### ISSUE THREAD

**Issue by jwilm** [Reviewable/Reviewable#534]
Following up from [Twitter](https://twitter.com/reviewableio/status/979086905198329856). This isn't 100% reproducible, but it will cause the browser to scroll all the way to the top of the screen, and it then prevents the window from being scrolled down which means the page needs to be reloaded (which can be very time consuming!).

**Comment by pkaminski** [comment]
Does it happen with Reviewable's animations turned on, off, or both?

**Comment by jwilm** [comment]
I had no idea that the animations could be turned off. I'll try it out. This was never reliably reproducible for me; if I don't see it happening, I wouldn't consider it proof that turning off animations solves it.

**Comment by pkaminski** [comment]
I haven't been able to reproduce this so far, with animations on or off.  My hypothesis is that the code computes a bad (likely negative) offset, then keeps trying to scroll to it, preventing any other scrolling.  However, in my experiments so far, the scrolling always stops after the given duration which is 300ms if animations are on, and 0ms if animations are off.  So for the bug to manifest, both the offset and duration values would have to become corrupted, and I don't see any way for the latter to happen at the moment.

Can you confirm my experiments on your machine?  Try running the following line from the console and see if it causes the symptoms you observed:

```
$('html').velocity('scroll', {offset: '-1000000px', easing: 'ease-in-out', duration: 300})
```

Another way to validate the hypothesis is -- next time the page gets stuck at the top -- try to see if running the following line will get it unstuck:

```
$('html').velocity('stop')
```

**Comment by bstaletic** [comment]
This actually happened to me today for the first time.
Firefox 59.0.2 64bit, animations on.
It does look like it is related to scrolling. When it happened I was able to scroll down a few pixels before reviewable scrolled back up.

Setting the offset to a negative value did scroll to the top, but then functioning remains normal.

**Comment by jwilm** [comment]
I just had this happen with animations disabled. Running `$('html').velocity('stop')` does not fix it. I'm leaving the tab open in case you are available to debug with me @pkaminski

**Comment by pkaminski** [comment]
Sorry, I wasn't available.  :(  But given that `$('html').velocity('stop')` doesn't abort the scroll it may well be a bug in Velocity.  Unfortunately, the library hasn't been updated in a while and I'll have to switch to a different animation framework in the UI redesign.  In the meantime, I'll see if I can bypass Velocity for this animation, and if not then remove it altogether.

**Comment by jwilm** [comment]
I've still got the tab open if there's anything you'd like to try :)

**Comment by pkaminski** [comment]
The only thing I can think of is to capture a short performance trace and see if any animation frames are being fired, and if so whether the code points to Velocity.  Not entirely trivial, but if you happen to be a web developer feel free to give it a try!  (The code is minimized but I can map offsets back to the source.)

**Comment by jwilm** [comment]
Here's what I see:

![image](https://user-images.githubusercontent.com/4285147/38770870-4f7e6138-3fce-11e8-9e69-f6262adc4cba.png)

Here's the profile exported from firefox "performance" tool.

[profile.json.gz](https://github.com/Reviewable/Reviewable/files/1910664/profile.json.gz)

**Comment by pkaminski** [comment]
I just realized -- did all the reported incidents happen in Firefox?  If so, I'm inclined to suspect a Firefox bug of some sort instead.  In any case, I modified the code to use `window.scrollTo()` directly, let's see if that fixes it.  Please follow up if you observe the issue again and I'll reopen.

**Comment by jwilm** [comment]
@pkaminski in my case, yes.

I'll make sure to report back if there are any further issues, but last time there was a 16 day period without a problem :upside_down_face:.

Thanks for the patch!

**Comment by bstaletic** [comment]
The one time it did happen to me it was in firefox.
