### ISSUE TITLE
Allow me to search for text across all files in this PR

### ISSUE THREAD

**Issue by dplassgit** [Reviewable/Reviewable#536]
Sometimes when I'm doing a review I want to see where the code in a file is used in other places in the PR. So I would like to be able to search for code within the PR.

(Alternatively, let me "expand all diffs" with one click so I can use browser ctrl+F)

**Comment by pkaminski** [comment]
Hey David, could you expand a bit on this feature request?  Is the issue that Reviewable is in single-file mode and you want all files to be shown at the same time?  (There's a button for that as of the beta.)  Or that some diffs have been throttled, showing no content until you scroll past them?  Or that you want to see / search the full contents of all the files, even outside the delta areas?  Thanks!

**Comment by dplassgit** [comment]
All three things. 

If Reviewable is in single-file mode, and I see a symbol used, I want to search the rest of the PR for that symbol to see where it is defined.

If Reviewable has throttled diffs (not sure what that means) and I see a symbol used in a non-throttled diff, I want to search the rest to the PR for that symbol to see where it is defined.

**Comment by pkaminski** [comment]
The first two things are already handled by the "Show all diffs anyway, at your own peril" button that appears just above the first file when either condition obtains.  The latter is handled by the dropdown menu in any "Collapsed" section in any file that offers "Expand everything: all files".  I don't think this use case is common enough to warrant making these bits of UI more obvious, or combining them behind one button.

In any case, in general there's no guarantee that all use sites are in files included in the PR anyway.  I think that integrating Soucegraph (per #519) would be a better approach to this issue.
