### ISSUE TITLE
Cannot subscribe on beta

### ISSUE THREAD

**Issue by fpeter8** [Reviewable/Reviewable#537]
In the Repositories page all Subscribe buttons are grey and cannot be clicked.

This affects the beta site only (using the stable link allowed us to subscribe).

**Comment by pkaminski** [comment]
Wow, sorry about that, and thanks for finding a workaround!  I'm not sure what happened but I added some extra logging to the page if it's not ready after 5 seconds.  Are you able to reproduce the issue, by any chance?

**Comment by pkaminski** [comment]
Actually, I managed to track this down and fix it.  It only affected users with no existing subscriptions at all and most users will end up with an automatic trial subscription before attempting to sign up, so it went undetected for quite a while.  Thanks again for reporting the issue and apologies that I let it slip through!

**Comment by fpeter8** [comment]
Awesome, thanks
