### ISSUE TITLE
Can't open reviews: stuck on ¨mapping renamed files"

### ISSUE THREAD

**Issue by t-bast** [Reviewable/Reviewable#539]
Hello,

We're running into an issue where it looks like there's a race condition between various github plugins.
We just added waffle.io integration to our repositories, and since then it's been impossible to open reviews in reviewable: it stays stuck on "Mapping renamed files".

I've diagnosed the root cause: waffle.io automatically adds a "review" label to the pull request. When I remove this label manually, reviewable starts working again. So it looks like the fact that both reviewable and waffle are interacting with the PR breaks something in the reviewable flow...

**Comment by pkaminski** [comment]
Thanks, I've reproduced this by adding a "review" label manually, so waffle.io is innocent.  Will fix ASAP.

For other people who reported the issue and that I've pointed here, could you please confirm whether your PRs have a "review" label on them?  Thanks.

**Comment by pkaminski** [comment]
Sorry about this issue, it should be fixed now.  The label was aliasing an internal property, and there was a bug in the infrastructure framework's protection against this.

**Comment by t-bast** [comment]
Thanks for the quick investigation!
