### ISSUE TITLE
add hotkey for canceling a comment-compose

### ISSUE THREAD

**Issue by ryan-williams** [Reviewable/Reviewable#54]
also add it to tooltip per #53

**Comment by danvk** [comment]
in light of #49, Cmd-A + backspace + ESC will work :)

**Comment by pkaminski** [comment]
I'll add a bindable command but I don't think I'll bind it by default.  (While it's safe since drafts are never permanently deleted, it would be pretty confusing/scary to hit this by mistake.)

**Comment by pkaminski** [comment]
There are now bindable commands for trash draft and send draft, but they're not bound by default.  Take a look at https://reviewable.io/bindings.json if you'd like to add a custom shortcut for them.
