### ISSUE TITLE
Current beta on firefox - Up and Down arrow keys not moving the cursor

### ISSUE THREAD

**Issue by bstaletic** [Reviewable/Reviewable#540]
I'm using the latest firefox (stable, not beta or nightly) and while writing a review comment I am unable to use up and down arrow keys to move the cursor in order to edit previously written text.

**Comment by pkaminski** [comment]
Unable to reproduce in FF 59.0.2 on Windows 10.  Could you please provide more details about your platform?  Also, can you confirm whether you observe the same issue in the stable version (https://reviewable.io?stable)?  Thanks.

**Comment by bstaletic** [comment]
Managed to reliably repro the bug and it does happen with both stable and beta.
Firefox version 59.0.2 64bit.
If my comment is not the first one in the conversation, rather is a reply  then I can't use up and down arrow keys.

**Comment by pkaminski** [comment]
Thanks, reproduced with this extra detail.  I'm impressed how long it went unnoticed in stable!  I'll take a stab at it early next week -- it's weird it only affects replies, since they use the exact same draft comment widget.

**Comment by pkaminski** [comment]
This appears to be a regression in Firefox's implementation of `Element.focus()` when called soon after another element that had focus was destroyed.  I added a workaround (in the beta only) that makes it work consistently for me now.

**Comment by bstaletic** [comment]
Thanks! It works.
