### ISSUE TITLE
View file tree for code reviews

### ISSUE THREAD

**Issue by Rleahy22** [Reviewable/Reviewable#541]
To get a better understand of the organization of the code we're reviewing it would be great to show the file tree for files in the review.  Bitbucket has this functionality and it was very helpful when doing reviews.

**Comment by blakelee-pendo** [comment]
+1

**Comment by pkaminski** [comment]
Yep, I plan to experiment with turning the file matrix into a more tree-like view in the next major UI update.  This won't happen soon, though -- sorry.

**Comment by pkaminski** [comment]
This got shipped a while ago, but I forgot to close the issue.
