### ISSUE TITLE
Feature Request: Always put *.md (specially Readme.md) files on top of the review list

### ISSUE THREAD

**Issue by rajan61005co** [Reviewable/Reviewable#542]
While reviewing packages/module it would be pretty helpful if the first thing you review is the nice description of what the package is really about.

**Comment by johlju** [comment]
I agree to this in some degree, I sometime scroll to the README.md and/or the CHANGELOG.md but that is not true for all PR’s if the contributor did not add that (that will become the first review comment). 

Would it be better to be able to view the PR description instead? On GitHub a template can be used to get the user to provide more information regarding the PR than just a description, like properties around the PR (unit test, follow guidelines, etc.). That would probably not be in any of the .md files.

**Comment by pkaminski** [comment]
Neat idea but I'm concerned there would be a significant portion of folks (even if a minority) that would be surprised and confused by this.  It's also not clear whether to move *.md's to the top of all the files, or only to the top of the directory they show up in.

Do you think the file grouping feature proposed in https://github.com/Reviewable/Reviewable/issues/527 could be a reasonable alternative?  You could modify your review completion snippet to create a "readmes" (or whatever) group and put anything that looks like a doc into it.  It would then show up before the default group of all the rest of the files.

**Comment by pkaminski** [comment]
Closing in favor of #527.
