### ISSUE TITLE
Time limit for reviewers to act - timestamps in review state payload

### ISSUE THREAD

**Issue by george-harness** [Reviewable/Reviewable#544]
I would like to use reviewable as a `PAIR code review` system. I would like to allow for developers to be able to move forward even if their pairs are busy with something else and unresponsive. On the other side allowing self-review is often miss-used and some developers use it to fast track their changes before anyone can react.

To balance these two I would like to create a reaction/followup timeout for the PR completion check. Let's say if no one reviewed for 24 hours, the PR review is considered completed. Similarly, if a discussion is in a blocked state 24 hours after the author responded it is considered resolved from a completion check point of view.

Note that I am not looking for integrating the timeouts into the discussion business logic (even this might be a good idea). All I am asking is to enhance the review state payload with the needed timestamps for such a check to be possible to script out.

**Comment by george-harness** [comment]
Sounds good. I am glad you like it. I am looking forward to it.

**Comment by mkow** [comment]
+1 to this feature.

We have similar time-based policies in a project I'm developing, but with longer periods (example requirement: either 2 approving reviews or 3 if the pull request is new (submitted less than 5 days ago)).
Optimally we'd like to have access to PR creation time, current time and last action time for each reviewer.

I'm not sure how triggers should be configured, but in our case reevaluation doesn't need to be too frequent.

**Comment by pkaminski** [comment]
This is now implemented, with a summary in the recent [announcement](https://headwayapp.co/reviewable-changes/improvements-to-completion-conditions-86689).  I also added a `lastActivityTimestamp` for discussion participants, and a `timestamp` for (newly made) file review marks -- let me know if you need more timestamps for other things.  Full docs will be included in the brand-new user guide, coming your way soon!

**Comment by mkow** [comment]
Thank you!
I just updated our script and the fields you added seem to be enough for all our needs :)
