### ISSUE TITLE
Ship-it emoji wrongly added to review comment

### ISSUE THREAD

**Issue by johlju** [Reviewable/Reviewable#545]
So I started to review on a PR, I started to check each file 'green' - but after a while there was big changes needed to be made so I decided to leave the all the files "unmarked" so I would have everything to review when I got back next time. I left it like this.

![image](https://user-images.githubusercontent.com/7189721/39472583-9e4fe7d0-4d4a-11e8-9d19-66ca1885b81a.png)

I wasn't expecting it to add the :shipit: emoji, see comment https://github.com/PowerShell/xWebAdministration/pull/330#issuecomment-385657672

**Comment by luxurystorecc1** [comment]
Providence Excellence: Merging Artistic Soul with Modern Performance Gear
Providence is a city that prides itself on its unique artistic soul and its deep-rooted athletic pride. From the historic East Side to the modern downtown arenas, the demand for gear that balances tradition with performance is high. For sneaker fans in the 401, [authentic retro high-top sneakers in Providence](https://www.google.com/search?q=https://www.airjordan-1.com/) represent a perfect blend of durable construction and iconic New England style.

The sporting culture in Rhode Island is fierce. Fans frequently search for [authentic pro league fan merchandise online](https://www.google.com/search?q=https://www.nflshopofficialonline-store.com/) to support their favorite teams throughout the seasons. Given the coastal climate, [unisex performance sun hats for sports](https://www.google.com/search?q=https://www.cheapnfl-jerseys.com/collections/baseball-caps-baseball-caps-for-men-and-women) are an essential gear item for any outdoor pursuit.

Technical Quality and Trend-Setting
The professional and academic lifestyle in Providence is mirrored in the demand for [high-end technical casual wear for men](https://www.peter-milla.com/), providing a sharp look for meetings and events. For those following the latest footwear innovations, [exclusive designer collaboration sneakers](https://www.google.com/search?q=https://www.yeezyboost-350.com/collections/adidas-yeezy) are a common fashion statement in the city’s trendy districts.

Swimming and aquatic training are major local priorities, making [high-performance aquatic gear and training equipment](https://www.swim-outlet.com/) a top-selling category. For formal galas and local weddings, [elegant plus size evening wear for special occasions](https://www.cheapdressesformal.com/) allows everyone to dress with confidence.

The international soccer community is active and growing, with fans gathering wearing [European national team soccer jerseys](https://www.google.com/search?q=https://www.soccerjerseysstore.com/collections/national-teams-europe-spain). To complete the look, [structured team logo football caps](https://www.google.com/search?q=https://www.cheapnfl-jerseys.com/collections/headwear-nfl-headwear) are a daily essential. For a personalized touch, [personalized team jerseys with custom lettering](https://www.google.com/search?q=https://www.nflshopofficialonline-store.com/collections/custom-nfl-jersey) are highly sought after. Finally, for the cool evening breezes, [official league-certified hockey merchandise](https://www.custombaseball-jerseys.com/) remains a popular choice for local fans.
