### ISSUE TITLE
Number of files reviewed doesn't seem correct

### ISSUE THREAD

**Issue by johlju** [Reviewable/Reviewable#548]
Reviewed a big PR with a lot of renames, here; https://github.com/PowerShell/xNetworking/pull/330
It has a total of 248 changed files. But when publishing the [review comments](https://github.com/PowerShell/xNetworking/pull/330#issuecomment-386869256) it says that I reviewed 475 files of 676? 🙂 

```
Reviewed 475 of 676 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.
```

I was expecting it to say, "Reviewed 248 ot 248 files at r1", and that it was review comments, not "all discussions resolved".

Please not that I got the error message in issue #547 if that could have caused this problem.

**Comment by pkaminski** [comment]
#510 was released so this should now be fixed as well.
