### ISSUE TITLE
Cannot see who has reviewed certain files in new UI

### ISSUE THREAD

**Issue by brendan-roche** [Reviewable/Reviewable#549]
Since last beta was promoted to live UI, I cant see anywhere in the UI where you can see who has reviewed certain files. In the old UI their avatar would appear next to the file in the matrix. 

I think knowing who reviewed certain files is very important as sometimes with multiple reviewers you want to ensure someone with more experience in certain areas of the application has reviewed those files.

Is this something I'm missing with new UI, or was it removed for another reason?

**Comment by pkaminski** [comment]
This was a bug that slipped through the months of beta-testing.  Thanks -- fixed!

**Comment by brendan-roche** [comment]
Wow thanks so much @pkaminski, thats very impressive turn around time to fix that!

**Comment by pkaminski** [comment]
It was an embarrassing two-line fix, <50 characters total...  All the code was there (and meant to be there), but there was a disconnect in the data pipeline to the UI.
