### ISSUE TITLE
let ⌘? show keyboard shortcut list even while a text input element has focus

### ISSUE THREAD

**Issue by ryan-williams** [Reviewable/Reviewable#55]
I was composing a comment and wanted to see what shortcuts were available for e.g. submitting it as a draft or killing it, but couldn't find a way to while the input element had focus.

In desperation, I clicked out of the comment-compose element to try to `blur` it only to find myself with a second, unwanted comment-compose element open. It's a trap!

**Comment by pkaminski** [comment]
Huh, is ⌘? a de-facto standard?  It doesn't work in GitHub or Gmail...  You can always hit Esc to blur an input element (I thought this was standard enough to not bother adding to the cheatsheet, but perhaps not?).

**Comment by ryan-williams** [comment]
hm, I guess I got ⌘? from slack; it works in their OSX and web apps (which are actually the same afaict) and seems to me like a convention worth adopting. Asana also seems to use ⌘?, and neither supports "?" by itself afaict.

Relying on ⎋ for these things sits poorly with me because:
* I feel like it doesn't work some of the time / in various apps, either because they're accidentally or intentionally overriding it or it's just inherently a kind of clumsy or half-supported browser convention, like tabbing through all focus-able elements on a page
* it's in an inconvenient place on many (most?) keyboards
* In the examples discussed, it's an extra or indirect step (e.g. bringing up the hotkeys is currently either "?" or ⎋?, depending on aspects of the page's state).

**Comment by pkaminski** [comment]
OK, sounds harmless enough anyway.  Will add.

**Comment by pkaminski** [comment]
⌘/ will now bring up the cheatsheet, like in Slack.  ⌘? is apparently already bound by the OS on Macs.

**Comment by ryan-williams** [comment]
cool, thanks @pkaminski !
