### ISSUE TITLE
Writing 'Done.' ending with full stop does not change the disposition correctly

### ISSUE THREAD

**Issue by johlju** [Reviewable/Reviewable#551]
Not sure about this one. I don't have enough data (tested enough), but I think if a user writes 'Done.' the review comments does not change to the right disposition, but writing 'Done' without full stop does.

Posting this issue so you can double check, and I will report back if you need more information.

**Comment by johlju** [comment]
I can't acknowledge review comments for some reason and I think it has to do with 'Done.' having a full stop at the end. 🤔

**Comment by pkaminski** [comment]
I can believe the old disposition system is flaky, but I don't think it's because of the period; I double-checked and all the regexes are currently `/Done\.?/` or `/^(ok|lgtm|done)\b/i`.  In any case, this stuff will be going out the window by the weekend, when I put the new system into service.

**Comment by johlju** [comment]
Since you gonna release the new disposition system soon, let close this. I can ask the contributors to chnage to 'Done' when I see it's flaky (happened today again).
