### ISSUE TITLE
support for plain commits without PR

### ISSUE THREAD

**Issue by ShawnTalbert** [Reviewable/Reviewable#552]
Just trying out the product, and it seems to only allow me to start a review based on pull requests. Well, we don't do PRs. I need to do reviews on plain old commits to a repo, and/or a review across all commits for a given short-lived branch.

Is that possible? If not, please consider this a feature request :)

**Comment by pkaminski** [comment]
Hey Shawn, thanks for trying out Reviewable.  This feature request sounds somewhat pretty similar to #452 in implementation even if the intention is slightly different, so let's redirect the discussion there.  Thanks!
