### ISSUE TITLE
Trying LGTM a PR resulted in a permission denied

### ISSUE THREAD

**Issue by johlju** [Reviewable/Reviewable#557]
The PR https://reviewable.io/reviews/powershell/auditpolicydsc/37

In the "PR description comments" I acknowledge the last comment, then when I clicked the 'LGTM' button I got this error.

![image](https://user-images.githubusercontent.com/7189721/40608161-e6c57766-626a-11e8-8a41-4a6c0623ffbc.png)

**Comment by johlju** [comment]
It keeps crashing after refresh, and clicking again.

**Comment by johlju** [comment]
After publishing the pending resolved comments I could click the LGTM button.

**Comment by pkaminski** [comment]
I think I found the root cause in my logs -- your top-level discussion's disposition got stuck in a disallowed state somehow.  I'll fix it when I get back this afternoon -- sorry!

**Comment by johlju** [comment]
No worries. Expected some minor problems with such a big change 😃

**Comment by pkaminski** [comment]
Actually, the fix was simpler than expected so it's up now.  Please let me know if you run into this again!
