### ISSUE TITLE
allow multiple independent reviews for the same PR for assignees

### ISSUE THREAD

**Issue by alzix** [Reviewable/Reviewable#560]
Currently it is pretty hard to do independent reviews in on the same PR.
Ticking "mark file as viewed" button affects other reviewer statuses.
There should be an option to "mark file as viewed" without affecting other reviewers.
On the other hand joint reviews may also be appealing to some users

**Comment by pkaminski** [comment]
Hey Alexander, are you familiar with the "Include changes in files previously reviewed only by others" checkbox, at the bottom of the Changes box?

![image](https://user-images.githubusercontent.com/1646896/40893797-5ff038f4-6759-11e8-906a-4d7de7b1f4df.png)

If this doesn't work quite right for you, please also take a look at the discussion in #404 -- the semantics get pretty subtle around the edges.  Thanks!

**Comment by alzix** [comment]
i need more explanation. #404 describes modifications to be applied to `custom review completion condition`. But it seems the configuration format has changed since then.
In addition what bothers me is how the green/red marking for a file are kind of personal. They represent MY state of the review. How other reviewers can modify my state?

**Comment by pkaminski** [comment]
A review is a collaborative endeavor, so the review marks will reflect other reviewers' actions.  However, you can still easily tell if you personally reviewed a file by whether the mark is bright green.  If it's bright red, then Reviewable thinks you still need to review the file, and if it's grey-ish (with either a green or red outline) then Reviewable knows you haven't reviewed the file but thinks you don't need to.  Of course, the default logic doesn't know your specific workflow but it's still a pretty good guess for most people.

The custom review completion condition format has been extended but has remained backwards-compatible, so everything in #404 should still work.  If you're having trouble, let me know what logic you'd like to encode and I can help you translate it to JS.

**Comment by alzix** [comment]
> I didn't realize the custom review completion conditions could actually control the red/green marks on individual files.
That part :)

**Comment by pkaminski** [comment]
You can do something like this in your completion condition code:

```
_.forEach(review.files, file => {
  _.forEach(file.revisions, rev => {
    rev.reviewed = /* custom logic here */;
  });
});

return {
  files: review.files, // ... other properties, as documented
}
```

Note that the `reviewed` flags are global, i.e. "is this file considered reviewed at this revision".  If `reviewed == false` then the mark reviewed button will be red even if other people have reviewed the revision.

**Comment by pkaminski** [comment]
Ping -- did you find a configuration that works for you?

**Comment by pkaminski** [comment]
I'm going to assume you're set and close the issue, but please follow up if you need more help.
