### ISSUE TITLE
Not able to merge code from Reviewable: `At least 1 approving review is required by reviewers with write access`

### ISSUE THREAD

**Issue by nictuku** [Reviewable/Reviewable#561]
Reviewable shows this error from GitHub when I try to merge:

```
Unable to merge branch: GitHub error 405 on PUT https://api.github.com/repos/microclusters/cloud-functions/pulls/1/merge: At least 1 approving review is required by reviewers with write access.
```

I own the repository, so what am I missing? Thanks!

**Comment by pkaminski** [comment]
You (or another repo admin) turned on required reviews from the GitHub side, and Reviewable doesn't yet post GitHub-compatible review approvals (see #489, to be fixed soon).  In the meantime, you need to either remove the review requirement from branch protection or manually approve the review in GitHub.

**Comment by uday-3773** [comment]
hello

**Comment by UDPN-zhangXueFeng** [comment]
Initial code submission

**Comment by olegreigo** [comment]
ok

**Comment by biz-intel** [comment]
> 

Yo, it's 2023 yet still I'm having same issue

**Comment by pkaminski** [comment]
This has been fixed for many years now.  If you're having some kind of problem nonetheless, please open a new issue.  Thanks.

**Comment by fahhem** [comment]
@24greyhat @biz-intel Could either of you explain the problem you're running into? We post Github-compatible Approvals now, so we don't know of a reason you're receiving this error.

You can also email support@reviewable.io if you prefer. I'd be happy to look into what's actually going on here, we don't want zombie issues anymore than you want to deal with them!

**Comment by fahhem** [comment]
My understanding of this problem from the one person that responded is that this is a GitHub setting they have enabled (see [branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches)) that we are reflecting in our UI.

If that's the case, and if you truly have nobody else in your organization, then there's no need to create a fake user to approve your PR's. Just remove branch protection (only users with write access can push anyway, so even public repos aren't writable by everyone).

**Comment by 1234567Yang** [comment]
This solved the problem for us. Hopefully it's useful to someone

<img width="2464" height="1059" alt="Image" src="https://github.com/user-attachments/assets/b6d5afb4-b5e8-4fed-96cb-2e8cbb512238" />

**Comment by pkaminski** [comment]
You can do the same from within Reviewable: https://docs.reviewable.io/reviews#approval-levels
