### ISSUE TITLE
Renamed file treated as two 

### ISSUE THREAD

**Issue by jason-hollister-payjoy** [Reviewable/Reviewable#563]
A file in an open review was renamed. Reviewable correctly recognized that it had been renamed, and I was able to mark the file as reviewed -- or so I thought. After I had published my review, the review status showed 3 out of 4 files had been reviewed. But there were only 3 files, including the one which had been renamed. I was able to resolve the issue by the following means:
- removed the "reviewed" status from this renamed file 
- setting the file's revision bars to cover the original through the renamed version
- marking the file "reviewed"
- setting the file's revision bars to cover the rename through the final version
- marking the file "reviewed" again.
- publish
At that point, Reviewable reported that 4 out 4 files had been reviewed.

**Comment by pkaminski** [comment]
Hey Jason, I assume this is the same event as in #562?  It sounds like a bug, let me dig into it.  Could you also point me to the PR (in a private email to support@reviewable.io if necessary) so that I can try to replicate the rename structure exactly?  Thanks.

**Comment by jason-hollister-payjoy** [comment]
Hi Piotr,
Yes, it is; it’s even the same PR! My colleague apparently decided to report the problem as well.

— Jason Hollister, PayJoy

**Comment by pkaminski** [comment]
I found and fixed some edge case bugs in the handling of renamed files, which I'm pretty sure covers your issue as well.  Thanks for reporting!
