### ISSUE TITLE
Superfluous organization OAuth permissions messages

### ISSUE THREAD

**Issue by zware** [Reviewable/Reviewable#564]
I currently have two banners at the top of my reviews page, each saying:

```
Although you appear to have the correct authorization credentials, the <org> organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to whitelist this app, visit https://help.github.com/articles/restricting-access-to-your-organization-s-data/
```

As these organizations are not using Reviewable, these banners are only an annoyance for me, and take up a large percentage of my screen.  It would be nice if they could be, in order of preference: made to be dismissible (once for all time), moved to the bottom of the page, or combined.

**Comment by pkaminski** [comment]
Hey Zachary, what you're seeing is a generic display of errors received in the response to Reviewable's GraphQL query to GitHub.  I agree that these are unnecessarily annoying, and while I don't think making them permanently dismissable is a good idea, special-casing to combine and move them to the bottom of the page would be a fine improvement.

Unfortunately, I haven't been able to reproduce these errors even after turning on third-party app restrictions, which makes it hard to special-case them.  I also think it's weird you're getting such errors because GitHub's _modus operandi_ is to pretend that access-restricted resources simply don't exist, without providing any feedback to that effect to the app.

Anyway, I'll keep poking around for some way to repro, but if you could look at the GraphQL responses on that page, find one of the error structures, and paste it over here (with the org redacted), I could take a stab at doing it "blind".

**Comment by zware** [comment]
Thanks for looking into it!  I finally managed to find the errors:

## Org 1

### Query
```json
{
  "query": "\n    query ($query: String!, $after: String) {\n      search (type: ISSUE, first: 100, after: $after, query: $query) {\n        pageInfo {hasNextPage, endCursor},\n        issueCount,\n        nodes {\n          ... on PullRequest {\n            \n    id, number, title, url, state, createdAt, updatedAt,\n    author {login, avatarUrl, ... on User {databaseId, name}},\n    repository {name, isPrivate, owner {login}},\n    reviewRequests (first: 100) {\n      nodes {\n        requestedReviewer {\n          ... on User {login, name, avatarUrl, databaseId}\n        }\n      }\n    },\n    assignees (first: 100) {nodes {login, name, avatarUrl, databaseId}},\n    labels (first: 100) {nodes {name, color}},\n    milestone {title, description}\n  \n          }\n        }\n      }\n    }\n  ",
  "variables": {
    "query": "type:pr involves:zware state:open"
  }
}
```

### Response (with redactions)
```json
{
  "data": {
    "search": {
      "pageInfo": {
        "hasNextPage": false,
        "endCursor": "..."
      },
      "issueCount": 34,
      "nodes": [
        "..."
      ]
    }
  },
  "errors": [
    {
      "message": "Although you appear to have the correct authorization credentials,\nthe `org1` organization has enabled OAuth App access restrictions, meaning that data\naccess to third-parties is limited. For more information on these restrictions, including\nhow to whitelist this app, visit\nhttps://help.github.com/articles/restricting-access-to-your-organization-s-data/\n",
      "type": "FORBIDDEN",
      "path": [
        "search",
        "nodes",
        20,
        "reviewRequests",
        "nodes",
        0,
        "requestedReviewer"
      ],
      "locations": [
        {
          "line": 14,
          "column": 9
        }
      ]
    }
  ]
}
```

## Org 2

### Query

```json
{
  "query": "\n    query ($query: String!, $after: String) {\n      search (type: ISSUE, first: 100, after: $after, query: $query) {\n        pageInfo {hasNextPage, endCursor},\n        issueCount,\n        nodes {\n          ... on PullRequest {\n            \n    id, number, title, url, state, createdAt, updatedAt,\n    author {login, avatarUrl, ... on User {databaseId, name}},\n    repository {name, isPrivate, owner {login}},\n    reviewRequests (first: 100) {\n      nodes {\n        requestedReviewer {\n          ... on User {login, name, avatarUrl, databaseId}\n        }\n      }\n    },\n    assignees (first: 100) {nodes {login, name, avatarUrl, databaseId}},\n    labels (first: 100) {nodes {name, color}},\n    milestone {title, description}\n  \n          }\n        }\n      }\n    }\n  ",
  "variables": {
    "query": "state:closed type:pr involves:zware closed:>2018-06-10T09:36:47-0500"
  }
}
```

### Response (with redactions)
```json
{
  "data": {
    "search": {
      "pageInfo": {
        "hasNextPage": false,
        "endCursor": "..."
      },
      "issueCount": 17,
      "nodes": [
        "..."
      ]
    }
  },
  "errors": [
    {
      "message": "Although you appear to have the correct authorization credentials,\nthe `org2` organization has enabled OAuth App access restrictions, meaning that data\naccess to third-parties is limited. For more information on these restrictions, including\nhow to whitelist this app, visit\nhttps://help.github.com/articles/restricting-access-to-your-organization-s-data/\n",
      "type": "FORBIDDEN",
      "path": [
        "search",
        "nodes",
        0,
        "repository"
      ],
      "locations": [
        {
          "line": 11,
          "column": 5
        }
      ]
    }
  ]
}
```

**Comment by pkaminski** [comment]
Thanks, I gave the special-casing a shot -- let me know if it works.

**Comment by zware** [comment]
I believe the "org 2" message disappeared just due to the PR that caused it no longer appearing in the query results, but the "org 1" message is now at the bottom of the page with apparently customized wording.  This is a big positive step, thank you!

I do still think the message is superfluous, though: I have done everything I know how to do to ask Reviewable to *not* show me things from outside the one org that does use Reviewable :).  However, I understand that a proper fix to that is likely a much larger change, and with the banner now at the bottom of the page it's much easier for me to ignore.  I'm satisfied with the change that you've made, but having some way to explicitly tell Reviewable to ignore everything from a given org would be even better.

Thanks!

**Comment by pkaminski** [comment]
Glad to hear it's working!  My concern with dismissing the warning forever is that you'll be left with no indication that the PR list isn't complete, and no way to undo your decision in the future.  I think the grey banner at the bottom strikes a reasonable balance and you can always use a custom stylesheet (via a browser extension) to get rid of it...  I can add a class to it that's easier to match if you'd like to go that route.

**Comment by zware** [comment]
I think the part where we're not seeing eye-to-eye is that, from my point of view, the PR list *is* complete without the PRs from the other orgs, especially since I have selected "Also show pull requests you're not involved with from all repos to which you can push." with "limited to only connected repos" also selected (which I probably should have mentioned previously, sorry!  However, I still get the OAuth message regardless of how I twiddle the settings at the bottom of the page).

But again, I am satisfied with the current solution.  My reviews page has been much prettier today :)
