### ISSUE TITLE
Opinion: `Discussing` disposition should require visible action (comment?) to resolve

### ISSUE THREAD

**Issue by dhalperi** [Reviewable/Reviewable#566]
(Copying/summarizing from gitter: https://gitter.im/Reviewable/Reviewable?at=5b280defaeb8fa0c072668c8)

In general, I like the new `Discussing` disposition because anyone can mark the comment as resolved. I will often use this type of comment on a review for two different styles of comments:

1. Q: Should this spanner support metric nuts, is that unneeded for some reason, or is there a future plan to do this?
2. Typo: `spaner` -> `spanner`.

Intended behavior from author:
1. Either a) explanatory comment & resolve; or b) some change, push, respond to comment, resolve; or c) start a larger discussion.
2. Push fixed code, comment "Done", & resolve.

In cases 1a/1b/2, I am perfectly happy with a reviewer self-resolving the comments. In 1c, I assume author will leave the comment unresolved, or perhaps they'll mark it as `Working`.

Right now, however, there's a third option available in both 1/2: push the resolved button. This on its own does nothing but silently update disposition, which AFAIK is essentially invisible to reviewers.

I don't generally want to make comments like this blocking, because I trust my team to do the right thing generally, but it'd be nice to be able to confirm that every comment was responded to "easily".

The pre-populated "Done/Resolved" comment would handle that well.

**Comment by pkaminski** [comment]
(cc'ing @kballard, @nicolasartman, and @dsmilkov, who provided useful feedback on discussion semantics in the past.)

There's more context about the use case in the chat log referenced in OP.  I think (at least) two interpretations of the request are possible:  as a kind of soft-post-commit workflow, where people can resolve discussions and merge but you'd like to look over those spots again; or as a disposition that means "resolve if you want, but if you do please tell me why you did".

I think changing the semantics of the current Discussing disposition is a non-starter; I'm also not terribly excited about adding a new disposition.  However, I could imagine having a modifier flag on Discussing that's something like "courtesy reply requested", and a user-level setting for a default value implicitly set to last used.  Then if an action -- such as clicking the primary discussion button, or changing dispositions -- would resolve the discussion, and no reply was yet created, and at least one participant was Discussing-reply-requested, then Reviewable would automatically create a reply "Resolved." (like it does for "Done." now).  This reply could be edited or deleted so there would be no _guarantee_ that a resolution would generate a comment, but the vast majority of users would likely follow the path of least resistance.

Does such a mechanism sound plausible?  Would it address the original request?  Is the added complexity worth it?

**Comment by dhalperi** [comment]
@johlju the your comment exactly highlighted the dilemma. The commentor has to set the disposition, but the responder is the one who knows whether it's 1a/1b/1c. The commentor doesn't have the information to choose the different dispositions according to your algorithm.

**Comment by johlju** [comment]
@dhalperi I see what you getting at, but I'm am not sure that is true in all cases. Personally as a reviewer with the current information (the code) I know the change/information I'm asking for is informational, blocking or a discussion. If I'm adding a blocking comment, I expected it to be resolved, either by code change or explanation why it's done that way it is. A blocking comment, can turn into a discussion, or informational, or the other way around, by me changing my disposition, depending on responses I get. 

@pkaminski Cannot determine if the modifier flag will address the original request, but like the idea, but original requester have to determine if it worth the effort. If it's added should it be off by default so the current behavior is kept? If it is on default, and if there were a comment 'Resolved' added by default, I would not remove it. To many extra clicks. :)

**Comment by pkaminski** [comment]
@johlju I would keep the flag off by default, so current behavior would be unaffected.

I had an idea on how to address this issue from a different angle.  I could introduce a per-user switch that lets you treat disposition changes as if though they were new comments, so that discussions where another participant changed dispositions without writing a comment would still show up as unreplied.  I could even list who changed dispositions and to what, but that's probably not a good approach since I don't keep a history, so the information would disappear when the next change happened.  Hence I imagine you'd just see a "new dispositions" yellow stripe in the discussion with a generic "Some participants changed their disposition." notification underneath.

@dhalperi What do you think about the first and second proposals?

**Comment by dhalperi** [comment]
@pkaminski I'd turn on both options if they were there... Definitely the second proposal seems a huge win.

**Comment by pkaminski** [comment]
After ruminating on this for a while, I think the first proposal ("courtesy reply requested") is better addressed through social convention and explicit requests in your comment.  The second proposal (that I'm now calling "trust but verify") still sounds good to me.  I have a fairly unobtrusive design in mind and will be moving on it soon.

**Comment by pkaminski** [comment]
I implemented "Trust but verify", changelog post coming soon.  Look for the settings gear icon in the disposition dropdown to get started.  I'll close this issue for now but please don't hesitate to provide further feedback.
