### ISSUE TITLE
Ability to check who reviewed what

### ISSUE THREAD

**Issue by george-harness** [Reviewable/Reviewable#568]
I advocated for using reviewable in my company and very often when someone has a need comes to me instead of you :).

One thing that I was asked several times (for some long reviews) - "how I can see what you did review already."

This actually might be very easy to provide. Just extending the eye file matrix selector to allow for choosing a particular reviewer perspective should make this possible.

**Comment by pkaminski** [comment]
Hey George, thanks for being an ambassador for Reviewable on your team!  I think what you're asking for probably already exists.  As you noticed, the eye icon indicates the last reviewed revision for each file, and the avatars to the left of the cell row show _who_ has review marks for that revision.  Is that what you needed?

**Comment by george-harness** [comment]
This is limited though, it combines all the reviewers together and does not allow for checking which reviewer - reviewed what. Also, it does not allow to switch the matrix to see what changes happened after the reviewer last reviewed it (exactly what will happen if the reviewer click the eye in his account)

**Comment by pkaminski** [comment]
I think this works differently than you imagine.  For example, if A and B reviewed r1 and B and C reviewed r2, then the matrix will show an eye in r2 and show only B and C as reviewers.  You're right that there's no way to discover that A last reviewed it at r1, though.  This is a conscious trade-off to avoid presenting an overwhelming amount of data -- the file matrix is already the most complex visualization in the app.

I think your idea of having a "POV" selector for the matrix is clever but I'm preparing for a larger UI rework (that, among other things, will gain a dedicated "people" section) so I'd rather fold some solution to this into the new design.  Thanks for bringing up the idea!

**Comment by pkaminski** [comment]
This information is now available from the file review state dropdown.
