### ISSUE TITLE
New GitHub reviews integration 

### ISSUE THREAD

**Issue by lplewa** [Reviewable/Reviewable#569]
in the changelog, you wrote: "Semantics are exactly the same as on GitHub, though Reviewable will limit you to "Comment" if you lack write permissions to the repo, since other states wouldn't be respected by GitHub anyway." 

I don't understand why you are limiting this functionality as on GitHub I can "approve PR" without write permission and it will be visible in "reviewers", so you are limiting functionality compared to GH.

please check this PR as an example, pbalcer do not have write permission but he still could "approve PR" through GitHub interface.
https://github.com/pmem/pmdk/pull/3051

**Comment by pkaminski** [comment]
You're right, though if you look carefully you'll notice that approvals and change requests from users with no write access are actually shown differently in the UI:  grey vs colorful.  So these are effectively two extra states and as I couldn't think of any important use cases that these enabled I decided to avoid the additional complexity and leave them out.  And while there's an argument to be made for feature parity with GitHub I never considered that to be a binding requirement.

What's your use case for allowing non-writers to approve or request changes on a PR that couldn't be handled with comments or emojis?  (Especially considering that Reviewable's custom review completion conditions make it easy to check for emojis from any participant, and support a special collection of :lgtm: emoji.)

**Comment by marcinslusarz** [comment]
The use case is pretty obvious: the whole team reviewing PRs and one person making the final decision and merging.
This wouldn't be a problem, if you wouldn't take away the LGTM button...

**Comment by pkaminski** [comment]
Ah, so IIUC comments and emojis are sufficient for your use case, but you'd like to have a convenient button for creating them?  I can bring back the LGTM button for people who don't have write permission, it just won't approve the PR via GitHub's API.  Would that resolve your problem?

**Comment by marcinslusarz** [comment]
Yes, bringing back LGTM button would be enough. 

However I like the idea of closer integration between Reviewable and GitHub and I think making it possible to "approve" pull requests from Reviewable for people without write access would be even better.

**Comment by pkaminski** [comment]
The LGTM button is back now.  I'm not very keen on introducing more approval states, even if it is to match GitHub, but I'll keep an eye out for demand in this area.

**Comment by marcinslusarz** [comment]
Thank you..
