### ISSUE TITLE
Hovering file name does not always match up with the files

### ISSUE THREAD

**Issue by tavinathanson** [Reviewable/Reviewable#57]
![screen shot 2015-03-03 at 4 29 54 pm](https://cloud.githubusercontent.com/assets/322932/6472751/a0a90848-c1c2-11e4-921b-79a31684b5dc.png)

Based on this screenshot, I would assume that `locus.py` is the file above `gtf.py`. However, the file above `gtf.py` is `gene.py`. `locus.py` is further down:

![screen shot 2015-03-03 at 4 31 53 pm](https://cloud.githubusercontent.com/assets/322932/6472783/d399e4e8-c1c2-11e4-808c-d49ba968df88.png)

I assume this is a bug?

**Comment by pkaminski** [comment]
That does look like a bug.  To help reproduce, can you tell me anything about how you were navigating the page immediately prior to ending up in this state?  For example, were you scrolling with trackpad, scrollbar, cursor keys, page up/down, etc., were you scrolling up or down, or clicked on a filename from the matrix or drop-down shortcut list, ...  Also, are you able to reproduce this condition?  Thanks!

**Comment by tavinathanson** [comment]
Hey Piotr, I was mostly scrolling using the "n" keyboard shortcut, mixed in with some mouse wheel scrolling. I was also using "x" to mark files as read, mixed in with some manual clicking. I wasn't using the matrix at all: I was just scrolling through the full files.

As for reproducing, I'm not currently able to.

**Comment by pkaminski** [comment]
OK, thanks Tavi.  I'll see if I can track this down, or perhaps put in a fallback interval updater to recover transparently when it happens.

**Comment by pkaminski** [comment]
Hey Tavi, I wasn't able to reproduce exactly what you saw, but I did get close by changing the window width to cause the diffs to reflow.  Were you by any chance doing anything along those lines when the bug occurred?  Perhaps messing with the line length, or anything else that would cause a reflow.

**Comment by pkaminski** [comment]
OK, I found and fixed two separate issues that affected filename stickiness, so hopefully you won't run into this problem again.  Please reopen if you do...

**Comment by tavinathanson** [comment]
Thanks for addressing this!
