### ISSUE TITLE
Can't "Publish and Approve" when doing self-review

### ISSUE THREAD

**Issue by johlju** [Reviewable/Reviewable#570]
I really miss being able to check the "Approve" or "Request Change" when I'm doing self-review. When there is no other reviewer available in the community I need to self review my PR's, but I still want to follow the normal review process.

Is it possible to un-grey those two? 😃 

![image](https://user-images.githubusercontent.com/7189721/42272435-5b44e8dc-7f86-11e8-9e24-80bd42c8a8a9.png)

**Comment by pkaminski** [comment]
Not possible, sorry.  This is a GitHub limitation -- the API call will return a 422 error if you try to set any state other than Commented when you're the PR author.
