### ISSUE TITLE
GitHub reviewer not considered as a requested reviewer by Reviewable

### ISSUE THREAD

**Issue by pcorpet** [Reviewable/Reviewable#571]
See https://reviewable.io/reviews/bayesimpact/bob-emploi-internal/8214 (internal access required, so I think that you might need to use your reviewable creds to see it).

Github has pcorpet and zozoens31 as reviewers, but the reviewState in Reviewable has   `"requestedReviewers": [],`

I'm not sure whether it works in other cases.

**Comment by pkaminski** [comment]
Hey Pascal, by the time I checked GitHub didn't have any requested reviewers listed for this PR either.

Note that requested reviewers are automatically removed by GitHub as soon as they file a review.  They can be requested again at that point.  I think this semantics is weird but I've decided not to mess with it in Reviewable.  Could this account for the symptoms you observed?

**Comment by pcorpet** [comment]
Ah, I see. Is there a way to list the GitHub reviewers in the Reviewable state then?

**Comment by pkaminski** [comment]
Yes, you can look at `review.pullRequest.approvals` -- I forgot to update the docs, will do that now.
