### ISSUE TITLE
Checks menu doesn't seem to open unless scrolled to top of page

### ISSUE THREAD

**Issue by hjdarnel** [Reviewable/Reviewable#572]
On Chrome v 67.0.3396.99

When I click on the Checks menu, regardless of what the status of the checks actually are, it won't open unless I'm scrolled to the top of the page. It'll appear clicked, with a purple border. 

![image](https://user-images.githubusercontent.com/7868899/42478735-6ea78754-839b-11e8-808f-59ec12840118.png)

**Comment by pkaminski** [comment]
Thanks, reproduced -- it must be a recent regression.  Will fix shortly.

**Comment by pkaminski** [comment]
Fixed!  Thanks again for the report.
