### ISSUE TITLE
Checks button does not open if page is scrolled down

### ISSUE THREAD

**Issue by zozoens31** [Reviewable/Reviewable#573]
Expected behaviour:
- When I click on the checks button in the review page header, the list of checks and their status opens.

- Faulty behaviour:
- When I click on the checks button in the review page header when the page is scrolled down, the list of checks does not appear anymore, although the button itself has its selected state (with purple top border).

Expected behaviour (still working when at top of the page)
<img width="628" alt="screen shot 2018-07-10 at 09 58 02" src="https://user-images.githubusercontent.com/8383947/42496907-ce857974-8427-11e8-8eb9-3c408e0e8c29.png">

Faulty behaviour (when scrolled down)
<img width="523" alt="screen shot 2018-07-10 at 09 58 17" src="https://user-images.githubusercontent.com/8383947/42496910-d04c307c-8427-11e8-88ca-76b8e851cac6.png">

Issue was discovered on macOS 10.13.1 Chrome 67.0.3396.99 but was also spotted on different settings (eg Ubuntu Bionic Beaver)

**Comment by pkaminski** [comment]
I just fixed this earlier today (#572) -- can you please double-check after refreshing the page?  Thanks.
