### ISSUE TITLE
Auto-expand large diffs on revision selection

### ISSUE THREAD

**Issue by zware** [Reviewable/Reviewable#575]
When reviewing a file with many changes (enough to have the "This diff is pretty big, and showing it will slow things down." warning shown), if I've already clicked "show anyway" and then change the revision range, it would be nice to not have to click "show anyway" again.

It also seems like the threshold for that warning is quite low.  Allowing it to be customized would be another way to solve this issue for me.

**Comment by pkaminski** [comment]
So it's not terribly convenient, but such a button does exist:  if at least one diff is hidden and you scroll back to between the top-level discussion and the files, you'll find a message area with a "Show all diffs anyway, at your own peril" button.  Once you press that, all automatic diffing / file throttles will be disabled until you leave the review.  Will that do for now?

In the future, I want to at least make access to this button more convenient, and perhaps also scale the throttles to your machine's power.

**Comment by zware** [comment]
I had seen that button, but either didn't understand or notice that it was a "for good on this page" setting; I'll try to remember it next time I need it.

The future plans also sound good to me :+1:

Thanks for the quick response!
