### ISSUE TITLE
New GitHub reviews integration appears to defeat Jenkins bot integration commands

### ISSUE THREAD

**Issue by jwnimmer-tri** [Reviewable/Reviewable#576]
See, for example, in https://github.com/RobotLocomotion/drake/pull/9104#pullrequestreview-135497639.  Hongkai posted some jenkins bot requests as part of the top-level discussion thread.  Prior to the GH review integration, this would have kicked off some new builds, because Jenkins noticed a new GH comment and responded.  In this case, I had to click through to the GitHub PR page and post the bot comment again, in order for the builds to begin.  I suspect that the "reviewed N days ago" message is somehow different because its a GH review comment, not a PR comment, that Jenkins isn't seeing it anymore.

I am not fluent in the GH vs Reviewable vs Jenkins notification flow, so possibly this is a Jenkins deficiency, but it would be nice to have at least some work-around built into reviewable in the meantime.

**Comment by pkaminski** [comment]
This sounds like Jenkins not watching for reviews, just issue comments.  Given that the reviews API was introduced over a year ago I don't think this is excusable but I know very little about Jenkins.  Perhaps @jamiesnape (from https://github.com/RobotLocomotion/drake/issues/2000) knows more?  Failing that, do you know precisely which plugin you're using to connect Jenkins to GitHub?

The only workaround I can think of would be to use the "single message send" function in Reviewable, as that uses (and will continue to use) the old comment API.  It's activated by the small "arrow out of box" icon below a draft.

**Comment by jwnimmer-tri** [comment]
Actually, I think that would be a fine work-around (just a little user doc / training), especially if the underlying issue is on Drake's Jenkins setup side.  I will try it next time I need to talk to the bot.

**Comment by jamiesnape** [comment]
Yes, not Reviewable's fault. Jenkins only knows about the GitHub issue comment API.

**Comment by pkaminski** [comment]
OK, I'll close this from my side -- hopefully there's an upgrade to the Jenkins plugin, but otherwise the workaround will have to do.  Thanks.
