### ISSUE TITLE
Bug in default github approval template

### ISSUE THREAD

**Issue by wli** [Reviewable/Reviewable#577]
For the template "Explicit approval required via GitHub's review system", it looks like either the github API changed from under you (possibly from an array to a dict), or there was a misunderstanding in how lodash shorthand for `_.filter` works.

State
```
> approvals  # from line 14
{wli: "approved"}
> numApprovals  # from line 16
0
```

Current code (incorrect)
```
# Evaluates to 0
let numApprovals = _.filter(approvals, 'approved').length;
```

Proposed change (correct)
```
# Evaluates to 1
let numApprovals = _.filter(approvals, a => a === 'approved').length;
```

Furthermore, I didn't test this but the following line (18) is probably wrong too
```
const numRejections = _.filter(approvals, 'changes_requested').length;  # Current
const numRejections = _.filter(approvals, a => a === 'changes_requested').length;  # Proposed
```

**Comment by pkaminski** [comment]
Yeah, sorry about that.  I fixed it to use `where` instead of `filter` soon after launch, but I guess a few people had already built on top of the broken version.  :(

**Comment by pkaminski** [comment]
Actually there were two more bogus `filter`s left -- will push a fix shortly.  Thanks for pointing this out!
