### ISSUE TITLE
Disposition dropdown has weird z-index

### ISSUE THREAD

**Issue by marczych** [Reviewable/Reviewable#578]
After upgrading to Enterprise v1863.2875, I'm seeing a weird z-index value for the disposition dropdown on a top-level discussion:

![image](https://user-images.githubusercontent.com/1094445/43214718-f1fedba2-8fee-11e8-8823-d64b99739913.png)

I can't make a line-level discussion overlap with the next file's revision indicator but that could theoretically have the same issue.

**Comment by pkaminski** [comment]
Thanks, will be fixed in next release.  In the long term I plan to redesign the UI around the toolbar that should make all this `z-index` malarkey unnecessary.
