### ISSUE TITLE
Did not get the option to approve PR

### ISSUE THREAD

**Issue by johlju** [Reviewable/Reviewable#579]
When reviewing PR https://github.com/PlagueHO/WSManDsc/pull/22 with https://reviewable.io/reviews/plagueho/wsmandsc/22 I did not get the option to Approve the PR. I could just "comment". Though, I could approve it through GitHub approval. 

Is there something preventing Reviewable to send approval's  in this case (is this by design)? 

I rarely review PR's in a repo that I don't have collaborator permission to, so haven't seen this before. In this WSManDsc repo I only have contributor permission (regular user).

**Comment by pkaminski** [comment]
Hey Johan, this is likely working as expected.  While GitHub allows anyone to approve/block a PR, only the actions of those with write permissions carry weight; others are disregarded.  I personally think this is confusing so Reviewable only allows approve/block if you have write (collaborator) permissions.
