### ISSUE TITLE
Provide visual distinction for stalled reviews

### ISSUE THREAD

**Issue by nate-tri** [Reviewable/Reviewable#580]
When unhiding stalled reviews, there's no obvious way to determine which reviews became visible and thus which reviews need extra attention to get out of the stalled state.  It would be nice to have some visual distinguisher for reviews that are stalled.

Ideas (one of):  
 - Another icon (clock, slow motion)
 - Highlight rows

**Comment by pkaminski** [comment]
Good idea, implemented via an extra icon.  We'll see if people complain at the visual noise.  (Highlighting wouldn't work quite as well, since the list is striped for improved readability.)
