### ISSUE TITLE
Signing doesn't work with Edge

### ISSUE THREAD

**Issue by lanthaler** [Reviewable/Reviewable#581]
Signing in with Edge doesn't work. The OAuth dance happens but the status on Reviewable isn't updated.
 Tested with

Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

**Comment by pkaminski** [comment]
There turned out to be two regressions, one likely caused by a change in Edge's treatment of cookies and one due to bitrot in the redirect auth code path.  Both fixed now and Edge should be working again -- sorry!

**Comment by lanthaler** [comment]
Thanks, it's working again
