### ISSUE TITLE
setCurrentDiscussionDisposition() does not work on discussions with pending draft

### ISSUE THREAD

**Issue by zware** [Reviewable/Reviewable#582]
I use [keybindings](https://github.com/zware/dotfiles/blob/cf26dffa5e2022f45519b9443ff0334330fe80d9/reviewable/bindings.json#L57-L60) for setting disposition, which works very well in most situations (thank you so much for the custom keybinding feature!).  However, when responding to comments on a PR of mine, I am unable to change my disposition on a discussion via keybinding after I have created a draft comment in that discussion.

**Comment by pkaminski** [comment]
Apologies, there was a bug in handling that specific case.  Fixed!

**Comment by zware** [comment]
Works great, thanks for the rapid response as always!
