### ISSUE TITLE
Reviewable shows as offline if Github auth errors are encounted

### ISSUE THREAD

**Issue by julianvmodesto** [Reviewable/Reviewable#583]
### Symptom:
Reviewable is marked as offline with `no connection to Firebase, X pending writes`

### Potential Cause:
In the logs, it seems that the Firebase call failed due to Github credentials that no longer work:

```
Queue item https://my-reviewable.firebaseio.com/queues/polls/poll_0 processing error: GitHub error 403 on POST https://git.liveramp.net/api/graphql: Sorry. Your account was suspended.
Exception metadata: {"fingerprint":["Hubkit","403"],"level":"warning"}
{ Error: GitHub error 403 on POST https://git.my-github.net/api/graphql: Sorry. Your account was suspended.
```

The account used for the request (I omitted the full trace logs) is indeed now suspended. The account is still being used to connect a particular repo, but it seems that this request marks all of my Reviewable instance offline.

**Comment by pkaminski** [comment]
Huh, that's strange.  While suspended accounts can lead to weird errors they really shouldn't be affecting the Firebase side of things.  I asked GitHub support to suspend a test account of mine so I can try it out directly and figure out what's going on.

In the meantime, note that any repo admin can reconnect the repo, without cooperation from the suspended account if that helps get you unstuck.

**Comment by pkaminski** [comment]
I got a sample suspended account set up but was unable to get it into the state needed to observe the 403 errors.  However, I'm pretty sure the GitHub API failures are unrelated to Firebase being offline.  Is the offline state reproducible?  If so, I recently pushed some changes to make it easier to debug the root cause.  Also, please double-check that there's no extension interfering with the connection.

**Comment by pkaminski** [comment]
I think the offline part of this report is unrelated to the suspended user, so merging that into #587.  As for suspended users, I don't think there's much more that I can do, since they completely lose access to the GitHub API.
