### ISSUE TITLE
Code listings expanded from github links look funky

### ISSUE THREAD

**Issue by mgalgs** [Reviewable/Reviewable#584]
When you add a comment with a link that uses Github's line range notation (see example below) it looks a little funky on Reviewable:

![image](https://user-images.githubusercontent.com/152014/44479096-6f237c80-a5f4-11e8-9646-4100605011c3.png)

Seems to be losing its indentation, and the striped table doesn't really help either.

It looks fine on Github:

![image](https://user-images.githubusercontent.com/152014/44479113-7a76a800-a5f4-11e8-9eb5-d1bcfd443b61.png)

---

Here's an example link that makes use of the line range notation: https://github.com/Reviewable/Reviewable/blob/5ebe71ab2023a212b3d4418c8a408bc16401111a/docs/index.html#L3-L9

Thanks for the awesome tool!

**Comment by pkaminski** [comment]
Thanks for the report -- fixed!  It took a while because I had to understand and update the third party library that's used to extract the styles from GitHub's site.
