### ISSUE TITLE
Typing drafts extremely slow

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#59]
I'm viewing base..r3 on https://reviewable.io/reviews/hammerlab/cycledash/513.

When I type a reply in the draft comment box, there's a painful amount of lag—if I type quickly, it can take over a second for the text to show up. @pkaminski are you seeing this, too?

**Comment by pkaminski** [comment]
No, when I load that page my delay even when holding down a key to
autorepeat is probably <200ms.  I assume you tried reloading the page,
restarting the browser, etc?

On Thu, Mar 5, 2015 at 10:06 AM, Dan Vanderkam <notifications@github.com>
wrote:

> I'm viewing base..r3 on
> https://reviewable.io/reviews/hammerlab/cycledash/513.
>
> When I type a reply in the draft comment box, there's a painful amount of
> lag—if I type quickly, it can take over a second for the text to show up.
> @pkaminski <https://github.com/pkaminski> are you seeing this, too?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/59>.
>



-- 
Piotr Kaminski, Founder, reviewable.io

**Comment by danvk** [comment]
It does persist when I reload the page & restart the browser. It seems to be worse in Chrome than in Safari. If I mash the keyboard, the final text show up ~500ms after I finish typing. Not enough to prevent work, but enough to be noticeable and bothersome.

I'm on a Late 2013 Macbook Pro running Yosemite.

Are you doing anything non-trivial in the `keydown`/`keypress` handler? I do notice the "Draft saved" message flickering a lot as I type.

**Comment by pkaminski** [comment]
I'm hunting down some friends with older machines to try to reproduce this.  For the record, can you confirm that it also happens in incognito, no-extensions mode?

Every key press triggers an Angular digest cycle, which for this review on my machine are <10ms each, but probably much longer on yours.  If you're feeling adventurous, you can load a dev version of the site at https://reviewable-dev-piotr.firebaseapp.com/reviews/hammerlab/cycledash/513 and report the digest times printed to the console as you're typing.  (Note that you'll need to authorize this app separately, and you'll probably want to revoke your authorization once you're done testing.)

**Comment by pkaminski** [comment]
We've been unable to reproduce this on a mid-2011 Macbook Air, so it appears there's more going on than just CPU differences.  My friend reported that, in normal touch-typing use, the delay was on the order of 100-200ms, and could only get more severe delays by wailing on the keyboard.  The digest time reported in the console was typically below 15ms.

I'd like to confirm the digest times on your machine: if they're higher, then we have a systemic issue to reproduce; if they're similar, then we can focus on optimizing the textbox.  Thanks!

**Comment by danvk** [comment]
Opening in an incognito window made no difference.

I loaded up the review on your dev version and mashed on the keyboard. Here's what I see in the console:

```
reviewable.js:113 digest 8ms
reviewable.js:113 digest 15ms
reviewable.js:113 digest 12ms
reviewable.js:113 digest 7ms
reviewable.js:113 digest 12ms
reviewable.js:113 digest 7ms
reviewable.js:113 digest 11ms
reviewable.js:113 digest 14ms
reviewable.js:113 digest 23ms
reviewable.js:113 digest 16ms
reviewable.js:113 digest 14ms
reviewable.js:113 digest 14ms
reviewable.js:113 digest 23ms
reviewable.js:113 digest 11ms
reviewable.js:113 digest 20ms
reviewable.js:113 digest 19ms
reviewable.js:113 digest 11ms
reviewable.js:113 digest 26ms
reviewable.js:113 digest 16ms
reviewable.js:113 digest 13ms
reviewable.js:113 digest 26ms
reviewable.js:113 digest 35ms
reviewable.js:113 digest 14ms
reviewable.js:113 digest 34ms
reviewable.js:113 digest 21ms
reviewable.js:113 digest 9ms
reviewable.js:113 digest 17ms
reviewable.js:113 digest 13ms
reviewable.js:113 digest 47ms
reviewable.js:113 digest 22ms
reviewable.js:113 digest 28ms
reviewable.js:113 digest 28ms
reviewable.js:113 digest 27ms
reviewable.js:113 digest 17ms
reviewable.js:113 digest 44ms
reviewable.js:113 digest 21ms
reviewable.js:113 digest 26ms
reviewable.js:113 digest 24ms
reviewable.js:113 digest 27ms
reviewable.js:113 digest 50ms
reviewable.js:113 digest 6ms
reviewable.js:113 digest 26ms
reviewable.js:113 digest 23ms
reviewable.js:113 digest 14ms
reviewable.js:113 digest 16ms
reviewable.js:113 digest 38ms
reviewable.js:113 digest 9ms
reviewable.js:113 digest 6ms
reviewable.js:113 digest 17ms
reviewable.js:113 digest 15ms
reviewable.js:113 digest 13ms
reviewable.js:113 digest 4ms
reviewable.js:113 digest 14ms
reviewable.js:113 digest 10ms
reviewable.js:113 digest 14ms
reviewable.js:113 digest 22ms
reviewable.js:113 digest 16ms
reviewable.js:113 digest 15ms
reviewable.js:113 digest 15ms
reviewable.js:113 digest 16ms
reviewable.js:113 digest 8ms
reviewable.js:113 digest 15ms
reviewable.js:113 digest 9ms
reviewable.js:113 digest 12ms
reviewable.js:113 digest 37ms
reviewable.js:113 digest 30ms
reviewable.js:113 digest 10ms
```

many of the times are around 10ms, though the average is closer to 20ms and some are higher (up to 50ms). Is this anomalously slow? I do tend to be a fast typer.

**Comment by pkaminski** [comment]
The digest latencies are a bit higher than I would've expected, especially since your machine isn't that old, but it's the variance that's really striking to me.  The latencies aren't affected by typing speed -- rather, if your typing speed exceeds 1/latency the system will tend to lag.  100 WPM is ~8 CPS, which the latencies in your sample should be able to handle easily, even with any additional overhead that's not included in the measurement.

Given these numbers, I'll make some changes to the system in production and ping this issue when it's ready for another test.  Thanks!

**Comment by danvk** [comment]
Sounds good, thanks!

**Comment by pkaminski** [comment]
I deployed a new version that should almost completely eliminate any latency when writing drafts.  Please give it a try and confirm -- thanks!  The only downside is that the draft won't be saved until you stop typing for at least 250ms, but I figure that must happen occasionally even for you.  :wink:

**Comment by danvk** [comment]
It's much better now, thanks!

**Comment by danvk** [comment]
This seems to have regressed — I'm typing a top-level comment on https://reviewable.io/reviews/hammerlab/pileup.js/205 in single-page mode on a brand new macbook and the UI can't keep up with me.

**Comment by pkaminski** [comment]
Unable to reproduce, on that review or others.  Can you try to run the page with digest debug enabled (https://reviewable.io/reviews/hammerlab/pileup.js/205?debug=digest) and watch the bottom-right corner of the screen as type: does the little dot blink as you type, or only changes state when you stop for >100ms?  Also, what numbers do you see (min/med/max) after typing for a bit?  Thanks.

**Comment by danvk** [comment]
Huh, the issue seems to have gone away since this morning. Maybe it was on my end.
