### ISSUE TITLE
Allow commits with multiple authors to share a revision

### ISSUE THREAD

**Issue by EricCousineau-TRI** [Reviewable/Reviewable#592]
See discussion here:
https://github.com/RobotLocomotion/drake/pull/9510#pullrequestreview-159097335

**Comment by EricCousineau-TRI** [comment]
Just to check, is there a tracking issue for the new sidebar you mentioned?

**Comment by pkaminski** [comment]
No, though I should've probably made one.  But there are bigger happenings afoot -- news soon.  :)

**Comment by pkaminski** [comment]
Fix deployed.
