### ISSUE TITLE
Unexpected change in merge commit messages

### ISSUE THREAD

**Issue by jellonek** [Reviewable/Reviewable#595]
I'm not sure if it's caused by something on reviewable side or on gh side, but starting from monday i see that after merging PR through reviewable interface merge commit message have different structure. Before monday it commit topic was something like "Merge pull request #XXX from Org/project/branch" with name of PR as a commit content (e.g. https://github.com/Mirantis/virtlet/commit/47fc8a93482aa7ec32793e306fbf5f8b47c4d4ea) while now I see merge commits containing only PR name, without "Merge pull request" header (e.g. https://github.com/Mirantis/virtlet/commit/b5c9b48278ca7cfd07ec833ce7e7adc6dbd55c45 and https://github.com/Mirantis/virtlet/commit/15bd4c0c1e722b55b29b0838ad397d5c407275c3).

Was that desired change, somewhere described, or is that a bug?

**Comment by pkaminski** [comment]
I did rewrite some of the merge UI code recently, but what you describe sounds like a bug.  What merge flavor are you using -- full or squash? -- and did you change it recently?  Is the commit message that shows up in git the same as the one you see in the preview if you activate the merge button dropdown?  Also, I just pushed some fixes in this area, so it's possible that the problem was accidentally addressed -- please give it a try at your convenience.

**Comment by alex-xnor** [comment]
We're experiencing this too at @xnorai. We're using and have been using squash-merges. This has happened as recently as two hours ago, so I don't think the changes you refer to in your previous comment accidentally fixed anything. Some of the affected merges happened without touching the drop-down at all; I am not sure if opening the drop-down would change anything, but I cannot currently test this at this time as I have no test repositories and no PRs waiting for merge on our production repository.

**Comment by alex-xnor** [comment]
It looks like if you open the drop-down, it shows the right thing (elaborate merge message with PR title, PR number, commit summaries, etc.), but the message that is actually used if you merge it without opening the drop-down, will not use the text that would have appeared in the text box and will instead just use the PR title. If the drop-down is opened and the text is changed, the text in the text box will be used. I am not sure if opening the drop-down without changing the text is sufficient or not.

**Comment by pkaminski** [comment]
Thanks for that detail -- it narrowed things down and I quickly found and fixed the bug.

**Comment by jellonek** [comment]
For historical completion - on our side we are using "create a merge commit" what could be seen under urls provided by me in first comment.

Thx for update!
