### ISSUE TITLE
Possibility to create file diff line comments

### ISSUE THREAD

**Issue by Pyton** [Reviewable/Reviewable#597]
Hi.

First of all good job. This tool is really cool. But in current shape is useless for me.

When I tried using tool on one PR I saw that comments which are created "inline" are converted to top-level comments. It's very annoying especially if few people will do CR for bigger PR. Then in GH I can see very looong comments.

The better option would be using GH method to do CR in file diffs.

There is REST API for this: https://developer.github.com/v3/pulls/comments/#create-a-comment

You can even create small top-level comments with summary etc. 
Integrating Reviewable with GH line comments allows users to don't use the tool and do CR in old-school way.

**Comment by pkaminski** [comment]
Sorry, what you're asking for is unfortunately (still!) not possible due to limitations in GitHub's API.  Please see #437 for the canonical issue and discussion.
