### ISSUE TITLE
Checkboxes never appear to be checked

### ISSUE THREAD

**Issue by aedelstein** [Reviewable/Reviewable#605]
If I put the following text into a Reviewable text box:
```
- [x] Task 1
- [ ] Task 2
```
it appears like this:
![image](https://user-images.githubusercontent.com/4365598/48928562-63bf4600-eeae-11e8-8e0b-cee77847153d.png)
i.e., the checkbox by "Task 1" is not marked checked.

This contrasts with how this would appear in, e.g., Github:
![image](https://user-images.githubusercontent.com/4365598/48928596-c1ec2900-eeae-11e8-9092-6a246cb73964.png)

**Comment by pkaminski** [comment]
Thanks, this was indeed a regex that wasn't catching a variance in GitHub's markdown rendering.  Fixed.
