### ISSUE TITLE
Back navigation broken

### ISSUE THREAD

**Issue by dedan** [Reviewable/Reviewable#607]
When I'm in a review and then click on the 'reviews' button in the header, I come back to the overview of all reviews, but it is empty. When I reload the page I see my open reviews again:

https://my.pcloud.com/publink/show?code=XZqLRg7ZkXiANlomcH7YYcKHTXaq90LUy9Mk

**Comment by pkaminski** [comment]
I can't quite reproduce but something is definitely wonky.  I rolled back the site due to an unrelated regression -- did that happen to fix your issue?  (Might help me narrow down when it was introduced.)  Thanks!
