### ISSUE TITLE
PR assigned to team not reflected in review status

### ISSUE THREAD

**Issue by mweaverh** [Reviewable/Reviewable#608]
When a PR is assigned to a team it does not block merge.
Looking at the Review State (under completion condition), there's nothing about the team assignee in "requestedReviewers".

Related to #499.

**Comment by pkaminski** [comment]
Indeed, requested reviewer teams are not currently part of the review state -- I can add that in.  Of course they won't block merging by default but you'll be able to write a condition that takes them into account.  I assume that's what you're looking for?

**Comment by mweaverh** [comment]
Yes, that would fit our needs. Thanks!

**Comment by pkaminski** [comment]
I've added a `pullRequest.requestedTeams` property to the review state.  It's not documented yet, but please give it a try and let me know if it works for you before I publicize it.  (The property is not backfilled on existing reviews until something forces a PR sync, e.g. visiting the review in a browser.)  Thanks!

**Comment by mweaverh** [comment]
Thanks for this fix. 

But I didn't think it through thoroughly: I will need some way to resolve individual members of the requested teams (the logic being: If `required` reviewers does not overlap with each of `requestedTeam[*].members`, then review is not complete). 

AFAICT it is not possible to query GitHub from the review state (or?). Can that be part of the requestedTeams property? 
Something like:
```javascript
  "requestedTeams": [
      {
        "name": "seattle-seahawks"
        "members": ["russellw", "ethomas", "dougbald"]
      }
    ],
```
It should probably resolve through nested teams, so that "members" contains only individuals.

**Comment by pkaminski** [comment]
You're right, you can't query GitHub from your condition code.  It's not impossible for Reviewable to resolve team members before invoking your code, but there are potential problems:  i) if the repo is not connected, there's no guarantee that Reviewable will have access to credentials that allow the API call, and ii) the completion evaluation is time-sensitive, and a call fetching members is potentially expensive.

I'm also not completely clear on your proposed logic -- AFAIK, requested reviewers / teams are automatically removed from the list by GitHub as soon as a requested reviewer or any member of a requested team publishes a review.  So using those to determine completion is likely to be problematic.

**Comment by pkaminski** [comment]
It's been over a year so I'm going to close this issue, but happy to reopen (or create a new one) if more is needed.
