### ISSUE TITLE
Add "more closed PRs" option to reviews view

### ISSUE THREAD

**Issue by dkeitel** [Reviewable/Reviewable#612]
As discussed on Gitter, we would like to be able to see more recently merged PRs in the Reviews view to avoid having to context switch out of Reviewable.

The enhancement would be to add an additional link or toggle similar that would just say "more closed PRs" and as a result would bump the time horizon by a week at a time and re-fetch all the things.

Another option would be to make the limit of showing 3 recently merged / closed PRs user-configurable, communicating to the user the additional load time should they deviate too far from the default.

**Comment by pkaminski** [comment]
This is now implemented.
