### ISSUE TITLE
@something in comments leads to "No such user when processing directives: something"

### ISSUE THREAD

**Issue by manuel-hegner** [Reviewable/Reviewable#616]
I created a code review at https://reviewable.io/reviews/bakdata/conquery/229#-.
Whenever I try to publish it (requesting changes) I get the error `Error: No such user when processing directives: NotNull` and it does not publish the review.

This happens with Firefox and Chrome.

**Comment by jwnimmer-tri** [comment]
FYI I'm only a reviewable user (not a developer), but to me this looks like the same thing as #614.

**Comment by manuel-hegner** [comment]
Thank you very much. This is the problem!
I would then like to change this issue to:
If a @username annotation is not resovable it should just be printed as a plaintext instead of blocking the publishing.

**Comment by pkaminski** [comment]
Yep, fair enough.  I think these used to be ignored until a recent refactoring, where they started being treated like assignee and reviewer directives (hard fail).  But that's pointless and annoying, so I reverted back to the old tolerant semantics effective immediately.
