### ISSUE TITLE
Copying code changes selection

### ISSUE THREAD

**Issue by trchen1033** [Reviewable/Reviewable#618]
Tested on: Chrome 72.0.3626.119 / macOS 10.14.1

How to reproduce:
1. Open some code review page
2. Select multiple lines of code with mouse
3. Press Command+C (or through the top menu Edit -> Copy)

Expected behavior: Copies the selected code
Actual behavior: The selection getting adjusted, often excluding the first line or the last line of selection. Also there is a single unicode no-break space (0xa0) inserted on every empty line.

**Comment by pkaminski** [comment]
Expanding the selection to cover full lines is intentional, but it should never shrink or drop a partial line.  If you see shrinkage that's a bug, in which case a screencast would be ideal to help me track it down.  If that's not possible, please provide as much additional details as you can, e.g., one or two column diff, contents of the lines and selection segments that got shrunk, etc.

The no-break spaces on empty lines is a known issue, I'll see if I can address it.

**Comment by trchen1033** [comment]
I think it happens only when you select backwards, i.e. mouse down on the last line then mouse up on the first line. Selecting forwards works as you described (I personally find this "feature" annoying, but I won't argue with that.).

**Comment by pkaminski** [comment]
Both issues should now be fixed, thanks for reporting.  I put in the selection extension since it's hard to hit the exact beginning/end of a line due to the tight layout, especially with the pointer cursor.  Also, it's pretty rare to want to copy multiple lines of code without grabbing full ones.

**Comment by trchen1033** [comment]
@pkaminski The bug of selecting backwards deselects the first and last line has regressed again.

**Comment by pkaminski** [comment]
I'm unable to reproduce so far, in either Chrome or Firefox, with one or two column layouts.  Can you provide more details about your actions and environment, or perhaps capture a quick video where perhaps I can spot what you're doing differently?  Thanks.

**Comment by trchen1033** [comment]
I think I found the issue. Our company seems to deploy an old version of Reviewable (v1975.2968). I confirm that the issue does not reproduce on `https://reviewable.io/reviews/Reviewable/demo/1`.

**Comment by pkaminski** [comment]
Yep, this got fixed in 2071.3450, released on 2019-03-11.  Please encourage your sysadmin to upgrade!
