### ISSUE TITLE
Reviews fail to load in latest version of Chrome

### ISSUE THREAD

**Issue by benbelow** [Reviewable/Reviewable#619]
On loading any reviews in reviewable, my team is getting the following error: 

`Error: Duplicate keys detected: 'group- -dir-<directoryName>/'. This may cause an update error.`

This has been tracked down to the latest version of chrome: 

on upgrading from Version 72.0.3626.118 to Version 72.0.3626.121, the issue appeared.

**Comment by pkaminski** [comment]
This is a regression in my code, sorry.  I was trying to fix it last night and made most cases better, but apparently made a few much worse.  Will continue working on it today, expect a fix within 2-3 hours.

**Comment by pkaminski** [comment]
This should be fixed now, but I'll keep an eye out for further regressions.
