### ISSUE TITLE
Text selection is flaky

### ISSUE THREAD

**Issue by thockin** [Reviewable/Reviewable#62]
When I review a large block, I frequently find myself highlighting a block of code to focus and keep track of where I am.  Reviewable does not allow this and instead does somethign weird - text highlighting appears later, if at all, and sometimes it opens an edit box when I didn't want one.

A previous tool I used had native select and highlight behavior, and trapped double-click as a signal to edit.  Much more intuitive and friendly.

thoughts?

**Comment by pkaminski** [comment]
Hey Tim, the text selection behavior you're seeing sounds like a bug.  You should be able to select code easily, even across collapsed and message sections.  Can you please provide browser and layout (one- vs two-column) details, and perhaps record a short screencast to share what you're seeing?  Making text selection useful requires active intervention from JavaScript so you may be affected by general performance issues, which we're also trying to track down.

As for double-clicking, I'm not a big fan -- I don't know of any modern web UIs that still use this gesture, so it wouldn't be very discoverable.

**Comment by thockin** [comment]
I went to try to repro it and it seems to be behaving better - I am not
sure why - I did not restart the browser or anything.

I can't say what many modern UIs do, but I can speak to a different code
review tool we use, which saves single-clicks for code cross-references
(e.g. click a symbol to go to its definition) and uses double click to open
a comment box.  It works really well for this.  I found it surprising that
single click on non-link-looking stuff had immediate effects.

**Comment by pkaminski** [comment]
If the performance issue has gone away I'm going to close this issue for now.  If it recurs, please reopen, try reloading the page with `?debug=digest` (a new option I just added) and report the min/med/max values from the lower-right corner of the screen after using the app for a bit.

As for double-clicking, I beg to differ with the other tool.  :smiley:  I'm going to stick with single-clicking given that creating a comment is one of the most common actions when performing a code review.  If I get around to integrating a cross-referencing engine, I'll probably bind that to ctrl-click (cmd-click), which has a long tradition in IDEs.
