### ISSUE TITLE
Unable to access PR reviews via URL textbox

### ISSUE THREAD

**Issue by EricCousineau-TRI** [Reviewable/Reviewable#620]
I am trying to initialize a Reviewable review on a PR, but cannot seem to reach the PR via the URL textbox.

Even if I try a PR for a repo that has Reviewable enabled, I can't see anything:
> ![image](https://user-images.githubusercontent.com/26719449/53992550-17b1ad80-40fb-11e9-90a0-f6c2ce95dbed.png)

**Comment by pkaminski** [comment]
I assume this is on GitHub Enterprise?  Which version?

**Comment by EricCousineau-TRI** [comment]
This is actually public GitHub
(Thanks for the quick response!)

**Comment by pkaminski** [comment]
Whoops, missing API preview media type.  Fixed.
