### ISSUE TITLE
Flickering when opening the Reviews page

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#621]
When the Reviews page is opened, the list of reviews changes several times during the first few seconds. I counted three times, to be precise. The loading spinner is shown before the first change, but after that, there is no visual indication that something is still loading and is going to change in a second or two.

This behavior is annoying. Usually some kind of intermediate version of the list is shown to be for just long enough that I pick one of the reviews and click it, and the list changes a split second before the click, so I end up clicking on some other random review instead. Also, it gives the wrong impression: I might start wondering “why is this one still awaiting my action?” — only for it to jump to a different group a second later.

Why should the Reviews page show the wrong version of the list (basically a lie) for the first few seconds? If the loading the status of every review takes long, then so be it. In my opinion, the spinner should be shown instead of the list for as long as needed, until there is a final version that won't keep changing under my mouse.

**Comment by pkaminski** [comment]
I think what may be happening is that the spinner goes away once all the PRs have been queried from GitHub, but before all their details have been loaded from Reviewable's database.  This results in all the rows appearing at once but then possibly getting resorted as more details are loaded.  Does that seem to match what you're seeing?  If so, I'll look into a fix.  If not, a short screencast of your issue would be appreciated.  Thanks.

**Comment by feldgendler** [comment]
I don't know what happens inside. What I see is the PR list appears, and then some of them jump from category to category (awaiting my action, reviewed by me etc) a few times.

BTW, I can't reproduce this when simply refreshing the page. Maybe something has to have changed since last time for this to happen.

**Comment by pkaminski** [comment]
This can be hard to reproduce since a shared web worker will do its best to cache the data that makes it re-sort.  In any case, I've made some changes that should keep the spinner up on initial page load until all the data is ready and the list has been sorted into its final configuration.  Note that since it updates in real time items may still jump around later.

**Comment by feldgendler** [comment]
Of course. Changes that happen later are fair game.

I confirm that the problem is gone. Thanks a lot!
