### ISSUE TITLE
Feature: more prominent display of commit messags

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#623]
Commit messages are important, at least in our workflow.

Currently, the only place we can see them is in the “Review discussion”. We can't see them while reviewing files without scrolling to the top and losing context.

I don't know what the best way to display the commit messages is. Here is a bunch of ideas, one or more of which you might decide to implement.

1. Tooltips on the cells of the revision strips for individual files (full commit message, author, timestamp).

2. Tooltips on the cells and/or header of the file matrix (same as above).

3. Tooltip on the top right corner of the discussion frame where the revision number is shown (same as above).

4. When looking at a particular file: a block at the top containing a brief history (author, time, first line of commit message) of this particular file between the revisions selected for comparison. This list should only contain the messages of those commits where the file actually was modified, sort of like what `git log` does when given a particular file name.

5. While dragging over a revision strip or the file matrix: a tooptip or some other area where you see a brief history of the range over which you have dragged so far. While dragging, normal tooltips are unavailable, so this would be helpful.

**Comment by pkaminski** [comment]
Yep, something along the lines of suggestion 4 above will show up once there's a sidebar to put it into.  There's already lots of related issues (#186, #228, and #284) so I'm going to close this as a duplicate.
