### ISSUE TITLE
Feature: search

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#624]
Often when reviewing a large PR, I have to check out the branch, for a typical reason: I want to search (for example, where is this newly introduced function used?).

If the PR is small, I can try the browser's search. If it's so big that only one file at a time is shown, there is no way to search.

I think the search should act on what you would see on your screen if all the diffs (between the currently selected revisions) could be shown at the same time.

**Comment by pkaminski** [comment]
In general, my search strategy is to outsource it to a Sourcegraph integration (#519).  It looks like they support [searching within commit diffs](https://docs.sourcegraph.com/user/search#commit-diff-search), so I think this would address your issue?

**Comment by feldgendler** [comment]
Probably. As long as I don't have to locate the same line in two places manually, it's all good.
