### ISSUE TITLE
Diff skipped to avoid melting your CPU

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#627]
I got the message “Diff skipped to avoid melting your CPU” and a button to display the diff anyway. I clicked it, and this was the monster diff:
![screen](https://user-images.githubusercontent.com/5643138/54687090-0c0eaf80-4b1b-11e9-9ced-16cb19ae1575.png)
I don't think this whould have made my CPU even slightly warm.

**Comment by pkaminski** [comment]
The heuristics for when to back off from diffing are pretty tricky -- they take all diffs done so far into account, among other things, so it's possible for a relatively small diff to break the camel's back.  Also, note that it's pretty hard to estimate the size of a diff _before having done it_, which is the whole point of diff throttling.  😉

**Comment by feldgendler** [comment]
So what's your heuristic? How do you do it now?

**Comment by pkaminski** [comment]
There are currently two separate heuristics:

The first one caps how much time Reviewable spends diffing up-front.  It
releases diffs queued in the same batch for up to 10 seconds, with up to 5
diffs outstanding at any given time (to extract a bit of parallelism).
Once the 10 seconds is up the rest of the batch is discarded with the
"melting" warning and diffs are triggered either explicitly, or implicitly
when the file comes into view or is likely to be the next one you go to.

A second heuristic looks at the size of a completed diff and the total size
of diffs displayed so far, and makes a judgement call on whether that would
be too much to show on the page.  If so, it's held back with a different
error code.

**Comment by feldgendler** [comment]
OK, I get it: if an innocent diff is so unlucky to be behind a really big one, it might get blamed for CPU-melting, while in fact it's the previous diff that took most of the 10 seconds.
