### ISSUE TITLE
File menu should be scrolled to the current fle

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#628]
When the pop-up file menu (from the button on the top bar), it should be automatically pre-scrolled so that the currently-viewed file is visible.

This is similar to how dropdown-list controls work: when they are opened, the dropdown is pre-scrolled so that the currently selected item is visible.

(For me, the top use case for this menu is this: when the PR is so large that I have to view files one by one, I use this menu when I want to go back after having clicked “Mark as reviewed and go to next file”.)

**Comment by pkaminski** [comment]
Agreed, but that dropdown is on the way out so I'm not putting any more effort into it.  Instead, the file matrix will end up in a new sidebar and I'll make sure it scrolls to the right spot automatically.

**Comment by feldgendler** [comment]
Didn't know about those plans. I hope it's going to be good.
