### ISSUE TITLE
Feature request: highlight trailing whitespace

### ISSUE THREAD

**Issue by dhalperi** [Reviewable/Reviewable#629]
copied from gitter on request: Dan Halperin @dhalperi 09:52
Is it possible to make reviewable warn on/highlight trailing whitespace in a diff?

**Comment by pkaminski** [comment]
Actually, it appears I was wrong:  Reviewable already changes trailing spaces into middle dots and highlights them in red.  If this is not sufficiently visible you can override the style for `.trailing` in a custom stylesheet.  Let me know if it stopped working at some point!

**Comment by dhalperi** [comment]
Just checking: is this what you meant by "highlights in red"?

<img width="406" alt="Screen Shot 2019-03-26 at 12 03 54 PM" src="https://user-images.githubusercontent.com/526415/55026016-541c4f00-4fbf-11e9-9552-f83d0f595f50.png">

**Comment by dhalperi** [comment]
(from public PR https://reviewable.io/reviews/batfish/batfish/3235)

**Comment by pkaminski** [comment]
Yep, the little red dots.  It's subtle by default on purpose, since many (most?) people don't care.
