### ISSUE TITLE
Responding to an email goes to wrong place in UI

### ISSUE THREAD

**Issue by thockin** [Reviewable/Reviewable#63]
I responded by email to a line comment and it showed up as part of the top-level review discussion in the UI.

**Comment by pkaminski** [comment]
Yeah, that's "working as expected" right now, but it's certainly not ideal.  It's low priority as so few GitHub users bother to reply via email.

**Comment by pkaminski** [comment]
This should also accept something like "ACK" to acknowledge a discussion.

**Comment by pkaminski** [comment]
Fixed!  Reviewable will now do its best to parse through GitHub's messed-up rendition of emails, split up comments, and handle acknowledge, disposition, and label / milestone / assignee directives.  Some details in the FAQ: https://github.com/Reviewable/Reviewable/wiki/FAQ/_edit#can-i-reply-to-reviewable-comments-by-email.  I'm sure there'll be plenty of corner cases where the scores of regexes get things wrong, so please open bugs as you find them.
