### ISSUE TITLE
Visual glitch

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#630]
A picture is worth a thousand words. (I just didn't know how to describe this.)
![screen](https://user-images.githubusercontent.com/5643138/54921376-e829e000-4f05-11e9-9ae3-305997044a04.png)

**Comment by pkaminski** [comment]
This is as expected.  The filename / revision cells slide onto the toolbar as you scroll.  If you happen to stop half-way then it'll overlap as there's no way I found to limit the width of the revision cells until the header is fully on the toolbar.

**Comment by pkaminski** [comment]
This is as expected.  The filename / revision cells slide onto the toolbar as you scroll.  If you happen to stop half-way then it'll overlap as there's no way I found to limit the width of the revision cells until the header is fully on the toolbar.
