### ISSUE TITLE
Permission denied when collapsing (or uncollapsing) file groups

### ISSUE THREAD

**Issue by rams3s** [Reviewable/Reviewable#631]
When using the new grouping feature (https://changelog.reviewable.io/directory-tree-and-grouping-92404), we encounter a permission denied error when we collapse/uncollapse a group.

![image](https://user-images.githubusercontent.com/1265835/54942560-a6ae2a80-4f2f-11e9-9e6a-cee43e66ad49.png)

Reloading the page after the crash properly applies the modification though.

Here is the code we added to our custom review completion condition script:
```
let code_extensions = [
  ".cs",
  ".cpp",
  ".h",
  ".js"
  ];

_.forEach(review.files, file => {
  _.forEach(code_extensions, extension => {
      if (_.endsWith(file.path, extension)) {
      file.group = "1. Code";
      return;
    }
  } );
  if (file.group == undefined && _.startsWith(file.path, "Assets")) {
    file.group = "2. Assets";
  }
} );
```

**Comment by pkaminski** [comment]
Apologies, there was a bug dealing with group names that contained periods.  Fixed.

**Comment by rams3s** [comment]
Thank you! ;)
