### ISSUE TITLE
"Review each commit separately" isn't working for a PR with only 8 commits

### ISSUE THREAD

**Issue by goldfrapp04** [Reviewable/Reviewable#632]
Hello!

I learned from https://github.com/Reviewable/Reviewable/issues/516 and https://github.com/Reviewable/Reviewable/issues/502 that "Review each commit separately" won't work properly for PRs with >20 commits. However, my (private) PR only has 8 commits, and it still won't work. I did try to set it before starting reviewing.

<img width="638" alt="Screen Shot 2019-03-28 at 5 50 03 PM" src="https://user-images.githubusercontent.com/8966063/55201806-fe43d480-5181-11e9-974d-e149c31b866a.png">

**Comment by pkaminski** [comment]
Hey Shia, if you let me know which PR this is for I can take a look.  There are other potential reasons why Reviewable might not be able to separate commits but they're pretty rare.

**Comment by goldfrapp04** [comment]
Sure! https://reviewable.io/reviews/scalyr/scalyr/2830#-

**Comment by pkaminski** [comment]
Looks like you caused the aggregated `r1` to get snapshotted today at 3:17pm PST, presumably before you tried to switch the review style to separate commits.  Creating a discussion draft or marking a file as reviewed will do this, even if you immediately delete the draft or rescind the mark.  Did you do anything in the review before trying to switch styles?

**Comment by goldfrapp04** [comment]
Aha, I think I might've left a discussion draft. Well, bummer! Thanks for looking into it. It'd be great to have the error message surfaced somehow, but I understand that might be tricky / might not be the best use of developer time.

**Comment by pkaminski** [comment]
There should be a warning in the review style dropdown that shows up if any revisions have already been snapshotted...
