### ISSUE TITLE
Add an option to show usernames instead of (or in addition to) icons

### ISSUE THREAD

**Issue by mr-salty** [Reviewable/Reviewable#637]
I find it difficult to tell who is involved in a review from their icons - part of the issue comes from people using the default icons, part of it is because my eyesight isn't the best and the icons are pretty small. I'd prefer to see the names instead.

I did a quick mockup (I know the dots are out of place but you get the idea)

![reviewable-names](https://user-images.githubusercontent.com/7683836/55841038-a0a57580-5afb-11e9-9d9a-25c94db8c13a.png)

**Comment by pkaminski** [comment]
Good idea, done!
