### ISSUE TITLE
Custom merge commit message

### ISSUE THREAD

**Issue by AlecBenzer** [Reviewable/Reviewable#639]
It would be great to have the ability to control what the default "merge commit" message is for a given PR. GitHub's/reviewable's default (i.e., listing out all the different commits in the PR w/ their descriptions) can be really noisy for workflows where people make lots of small commits all the time.

One path may be an option to default to the PR's description (what I think is often a more sensible option). A more advanced path may be to add an extra field to the completion condition function result containing the message to use for the merge commit.

**Comment by pkaminski** [comment]
Nice idea -- I added support for `defaultMergeCommitMessage` and `defaultSquashCommitMessage` to the completion condition output, and now also include `title` and `body` in the `review.pullRequest` state.  Please let me know if you find any breakage, as testing was fairly casual.  :)

(For cross-reference, this was previously [touched upon in chat](https://gitter.im/Reviewable/Reviewable?at=5928b1f6fa63ba2f7683c1f0) and rejected, but your proposed solution neatly sidesteps the issues identified there.)
