### ISSUE TITLE
"Review discussion" clipped

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#64]
On https://reviewable.io/reviews/hammerlab/pileup.js/20:

![screen shot 2015-03-06 at 11 48 16 am](https://cloud.githubusercontent.com/assets/98301/6529434/b339b77e-c3f6-11e4-994a-b626a6654f7e.png)

I see the message in "Review discussion" clipped mid-line about 50% of the times that I open that page. Some kind of race condition?

**Comment by pkaminski** [comment]
Yes, racing between loading images in the discussion and calculating the cutoff height (for hiding older comments).  It's on the to-fix list, will get there soon.

**Comment by pkaminski** [comment]
I believe this is fixed now, though being a race condition it's a bit difficult to test.  Please reopen if you still see it.

**Comment by EricCousineau-TRI** [comment]
I think this may be happening again?
See here:
https://github.com/RobotLocomotion/drake/pull/13128#pullrequestreview-438592326

> ![image](https://user-images.githubusercontent.com/26719449/87682984-7d319780-c74e-11ea-9f46-388fcd5d2286.png)

It only happened once, though...

**Comment by pkaminski** [comment]
@badz0, looks like we might still have a (very rare?) race condition in the discussion panel sizing code.  I don't think it's worth putting a lot of work into rooting it out for now given how hard it is to repro, but something to keep in mind if you happen to be looking at this code at some point anyway...

**Comment by badz0** [comment]
Sure, I'll check it out.

**Comment by EricCousineau-TRI** [comment]
Just an FYI, saw it again just now:
> ![image](https://user-images.githubusercontent.com/26719449/87827295-a20a3580-c848-11ea-93d6-867fd8350883.png)
Same PR:
https://reviewable.io/reviews/robotlocomotion/drake/13128

**Comment by pkaminski** [comment]
There's an image in that thread, so it's likely the race condition with image loading rearing its ugly head once again.  For the record, which browser / version are you using?

**Comment by EricCousineau-TRI** [comment]
I'm using Firefox 78.0.2 (64-bit), from Ubuntu 18.04's apt repository:
```sh
$ dpkg -s firefox
...
Architecture: amd64
Version: 78.0.2+build2-0ubuntu0.18.04.1
...
```

**Comment by pkaminski** [comment]
This should be fixed (again).
