### ISSUE TITLE
Feature request: show binary object size

### ISSUE THREAD

**Issue by nate-tri** [Reviewable/Reviewable#640]
The current diff view for a binary file appears to show no information other than "binary file".  It would be useful to see the size of the binary file or binary change. That way there's the ability to reject large binary files by review. 

As a first approximation, even just showing the size in the file-level review box would be useful.  Integration of that information into the file matrix is optional in my opinion.

Reviewable: v2056.3350
GitHub: Enterprise 2.13.22

**Comment by pkaminski** [comment]
Implemented.
