### ISSUE TITLE
Focus doesn't follow click on discussions

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#646]
When I click a draft comment and hit Cmd-Shift-P to toggle preview, it toggles the first comment that I left, not the one I clicked. It seems like focus isn't getting updated. This has been happening for a few weeks.

**Comment by pkaminski** [comment]
Thanks for reporting -- fixed.  This was actually broken a while ago, as part of migrating the draft component to Vue, but nobody noticed.

**Comment by danvk** [comment]
Confirmed the fix, thanks!
