### ISSUE TITLE
Feature Request: Completely remove an organization

### ISSUE THREAD

**Issue by kdechant** [Reviewable/Reviewable#647]
When I created by account, Reviewable connected itself to all the organizations I have access to, including a couple of companies I used to work for. Now I see PRs from all of them on the Reviewable dashboard. (Notably: PRs I opened at a past job which haven't been merged yet.)

I only want to use Reviewable with repos from my current job (which already has a subscription) and I want to completely remove all references to the other organizations. I see an option to convert them to the free plan, but that's not what I want. I want it so that Reviewable doesn't even know they exist. Is that possible?

(I'm aware that the owners of those orgs can revoke access in the OAuth settings, but I don't work there any more and I don't have control over that.)

**Comment by pkaminski** [comment]
Hey Keith, sorry for the confusion.  Reviewable did not in fact "connect" itself to your other organizations -- rather, it's listing all the PRs you have access to (and are involved with) on your dashboard.  It's up to the admins of those other organization to revoke your membership if it's no longer appropriate.  In the meantime, you can set a default filter on the dashboard for your current organization's name (as long as it's sufficiently unique).  (It's also possible to open repo-specific dashboards, but there's no such option at the organization level yet.)

**Comment by kdechant** [comment]
I think the UX is confusing here. I see the "Subscribed to Auto Trial plan" next to my old employer's GitHub organization, which made me worry that Reviewable was sending the owners an email about this "subscription" or that it would somehow show up in the organization's GitHub profile.

When I created by Reviewable account, it would have been nice to have a choice of which GitHub organizations to add and which to ignore completely. Instead, they just all appeared automatically, which got me worried.

Thanks for the tip on the default filters. I wouldn't have found that feature on my own.

**Comment by pkaminski** [comment]
Trial plans are individual, though it does mean that you must've clicked through to a review in that org at some point.  However, other org members are not affected by your trial.  It's possible that Reviewable will show up in some admin dashboard of third-party apps that are authorized for the org -- this is unavoidable, and the admin has the option of enacting third-party app controls.

I agree that picking orgs up front would be preferable.  Unfortunately, this is only available in the (relatively) new GitHub Apps integration mechanism, which isn't yet at API parity with OAuth integrations so Reviewable needs to stick to OAuth for the time being.
