### ISSUE TITLE
Can't search page for reviewer names

### ISSUE THREAD

**Issue by thockin** [Reviewable/Reviewable#65]
The only place the UI shows the name or handle of a reviewer is in a tooltip.  This makes it impossible to search for names.  E.g. "I know David responded to this PR..."  I can't just ^FDavid.

**Comment by pkaminski** [comment]
To clarify, if I found a way to enable search for names without actually displaying them (other than in the tooltip), would that satisfy the request?

**Comment by thockin** [comment]
I guess it would satisfy this bug.  It might still be unsatisfying for large projects where many people contribute.

**Comment by pkaminski** [comment]
Addressed using invisible text -- I think avatars are sufficient for identifying users most of the time, and don't want to waste real estate on names.  Note that you can only search over comment authors, and hidden comments will not be found (but #37 will help with this).
