### ISSUE TITLE
No syntax highlighting for handlebars/htmlbars

### ISSUE THREAD

**Issue by kevinkucharczyk** [Reviewable/Reviewable#651]
I work on an Ember codebase, which uses .hbs (htmlbars) templates, and there's no syntax highlighting for those files at all (making it harder to perform reviews).

HighlightJS itself does support htmlbars: https://highlightjs.org/static/demo/

**Comment by pkaminski** [comment]
I added the language and file extension mapping to the bundle, should be working now.  (Including all languages by highlight.js is space-prohibitive, so I add them on demand.)
