### ISSUE TITLE
inconsistent hex highlighting (in Go)

### ISSUE THREAD

**Issue by tbg** [Reviewable/Reviewable#652]
See
https://reviewable.io/reviews/cockroachdb/cockroach/38206#-LhewDCY9W0aASf82_Ix

The highlighting for the hex map values is confusing.

![image](https://user-images.githubusercontent.com/5076964/59752533-b618e780-9282-11e9-8bcd-db73ba43f89c.png)

I have no idea what's going on here, and I don't really mind that much, but I'm curious to learn what this is about.

**Comment by pkaminski** [comment]
Heh, that was a fun one.  I believe this should fix it once it gets merged and makes its way upstream: https://github.com/highlightjs/highlight.js/pull/2060

**Comment by tbg** [comment]
Thanks Piotr, really appreciate it. I'm relatively sure I saw examples where the "first f or d" rule didn't apply? See "intro" in the screens above. Anyway, maybe that's fixed by the priority adjustment.

**Comment by pkaminski** [comment]
Sorry, I think it's actually _last_ `f` or `d`.  Basically, AFAICT the tweaked regex was forcing all numbers to end in one of `[dflsi]`.

**Comment by pkaminski** [comment]
I believe this fix actually got pushed out a while ago.
