### ISSUE TITLE
Reviewable needs a poke after clicking "Update branch" in GH

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#655]
1. Enable "Require branches to be up to date before merging" for a repository in GH.
2. Start a PR.
3. Have it approved.
4. Add something to `master` so that the PR branch goes out of date, but not something that would conflict with the PR.
5. Click "Update branch" on the PR.

Expected: The review is still approved.

Actual: the approval is missing (and the PR cannot be merged) until someone _opens_ this PR in Reviewable. At that moment, it becomes approved without any user action.

**Comment by pkaminski** [comment]
I'll need some more information to investigate:
1. What kind of approval are you referring to?  The GitHub-native review approval, or Reviewable's commit status check (possibly mediated by a custom review completion condition)?
2. Is the repo in question connected in Reviewable?

Thanks.

**Comment by feldgendler** [comment]
1. The latter. We did not customize the completion criterion.
2. Yes.

**Comment by pkaminski** [comment]
I haven't been able to reproduce this so far.  Do you see this behavior consistently, or only occasionally?  Something that would fit the symptoms is if the pool of admin accounts for the repo is running low on GitHub API quota (hourly or burst), Reviewable will postpone updating the review status until sufficient quota is available.  Loading the review would force a refresh, though, using the quota of the user who loaded the page.

Next time you see this happen, please let me know the repo, PR number, and time (ideally down to the minute), and I can check the logs for evidence for or against the above hypothesis.  Thanks.

**Comment by feldgendler** [comment]
I haven't seen this in a while.

**Comment by feldgendler** [comment]
Saw this again.
https://github.com/tectonic-network/tectonic/pull/1360 (private repo)
The merge commit created by the “Update branch” button is 35005697afc4b3deb62fd6e1125ae2fbed6b032d (time: Wed Jul 3 16:03:33 2019 +0200)
This is what I see now on the GH PR page:
![screen](https://user-images.githubusercontent.com/5643138/60598268-af26c480-9dac-11e9-8534-1c447db80a1d.png)
(expected: the `code-review/reviewable` row should be green)
If I simply open the Reviewable page for this PR and close it without doing anything, it will change to green.

**Comment by feldgendler** [comment]
This is how I see this PR in Reviewable's PR list:
![screen](https://user-images.githubusercontent.com/5643138/60598485-13498880-9dad-11e9-8e19-83a823c896f7.png)
(so it shows one unreviewed file)

**Comment by feldgendler** [comment]
AH, OK, I think it's “base commit changes”. Sorry for confusing you.
