### ISSUE TITLE
GitHub Reviews integration is sometimes confusing

### ISSUE THREAD

**Issue by marczych** [Reviewable/Reviewable#657]
Hey Piotr,

I was alerted to a PR in my organization that was very misleading: the review in Reviewable was approved (the GitHub commit status was passing) but the GitHub review was _not_ complete because one user had requested changes. I'm not exactly sure how that happened but I'm pretty sure that the user didn't intend to request changes because he resolved the discussion and published his comments so it was either a user error or possibly a bug in Reviewable's heuristic for the default publish state.

In any case, this scenario is confusing because Reviewable is saying that the review is both completed and incomplete. This isn't entirely accurate because they are independent systems, but from a user's point of view the code review system isn't consistent with itself.

I'm not sure how to solve this. Some possible options:

1. We can require GitHub Reviews for PRs but that's an extra step and state for code reviewers to make sure they have set correctly and will likely cause more pain for us than it's worth.
1. I'm not seeing any way to disable GitHub Reviews (https://stackoverflow.com/questions/39041656/how-to-disable-github-code-review-on-pull-requests).
1. Can we disable the GitHub Review integration in Reviewable? We still want the comments of course but maybe not the top level approve, comment, request changes state? I'm not sure what's possible here, though.
1. In lieu of disabling the integration, can Reviewable always set it to passing so it's effectively ignored?
1. Can/does/should the custom completion condition support setting the review status and overriding what the user selects when publishing?
1. Can Reviewable set everyone's review state to passing when the Reviewable state is passing?

Like I said, I'm not sure what the right thing to do here is or what is even possible. Let me know what you think!

**Comment by marczych** [comment]
I just came across the recent discussion here: https://gitter.im/Reviewable/Reviewable?at=5d14e739d65dae046f9e8b2a

I'll try out `disableGitHubApprovals` and report back.

**Comment by pkaminski** [comment]
`disableGitHubApprovals` was going to be my first suggestion -- let me know how that goes!

**Comment by marczych** [comment]
`disableGitHubApprovals` worked out great!

The only documentation I could find for it was in the changelog here: https://github.com/Reviewable/Reviewable/commit/37a18c41b155d39897840e68820e9ac4175bcb6a

On second thought, these docs are great: https://docs.reviewable.io/#/repositories?id=custom-review-completion-condition-idcompletion-condition

However, only the first comes up in search results e.g. Google. Are these docs indexed by search engines?

**Comment by pkaminski** [comment]
Apparently the docs weren't indexed by Google, thanks for letting me know.  :(  Not sure why, but I requested indexing and will follow up to make sure it happens.  I think Bing is already indexing the docs but their webmaster tools UI is pretty confusing.

**Comment by marczych** [comment]
I'm still not seeing most of the docs pages in search results. The [homepage](https://docs.reviewable.io/#/) works fine e.g. "reviewable support chatroom". But "reviewable filter reviews" doesn't yield https://docs.reviewable.io/#/dashboard?id=filter-reviews. Not a big deal for me because I know to search in the docs now but it might make it harder for others to find stuff.

Also, it seems like DuckDuckGo doesn't ever return docs.reviewable.io e.g. "reviewable docs". 🤷‍♂

**Comment by pkaminski** [comment]
Yeah, something's broken -- I opened https://github.com/Reviewable/Reviewable/issues/661 to track.  Might need to change to another renderer.  :(
