### ISSUE TITLE
Erratic "Mark as Reviewed" button behavior

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#658]
Sometimes everything is reviewed, but the "Mark as Reviewed" button at the top of the review page is not disabled. Clicking it does nothing visible, and doesn't make it disabled as it used to do.

This started recently (maybe a couple of days ago).

**Comment by feldgendler** [comment]
Example PR currently in this state.
[pr.txt](https://github.com/Reviewable/Reviewable/files/3345443/pr.txt)

**Comment by pkaminski** [comment]
Is this only for reviews with renamed files, by any chance?

**Comment by feldgendler** [comment]
I've checked a few, and so far it seems so.

**Comment by pkaminski** [comment]
This should be fixed now, but not retroactive.  Please report if it happens again going forward -- thanks.
