### ISSUE TITLE
Hovering over directory tree with long file names in file matrix yields very jumpy resizing

### ISSUE THREAD

**Issue by alex-xnor** [Reviewable/Reviewable#659]
In our repository, some of our code lives in a directory structure with long paths. The [directory tree feature](https://changelog.reviewable.io/directory-tree-and-grouping-92404) added a while ago tries to abbreviate this. When hovering over any of the subdirectory labels, it expands to show the full path of that directory. However, when that path is very long, the whole matrix gets re-layed-out, and everything shifts all over the place. This makes it a little harder to use, because I have to make sure not to hover over any of the directory labels (move mouse outside of the file matrix 'till it's in the right vertical position, then move the mouse directly onto the row I want).

![Screenshot](https://user-images.githubusercontent.com/29713761/60469870-127cef00-9c13-11e9-9e23-4dc4f73329d3.gif)

I am using Firefox 67.0.4 on Ubuntu 16.04.6.

**Comment by pkaminski** [comment]
I applied a quick fix to prevent the layout from jumping around when moving the mouse around the matrix, but this may result in some long paths getting clipped even when _not_ hovering over them if all filenames are short and there aren't many revisions.  A proper fix would require bringing back manual width computation for the matrix which I'm loathe to do, as it was a source of much trouble...
