### ISSUE TITLE
Mouse wheel doesn't scroll file list in Safari

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#66]
In Safari, using the mousewheel to scroll the file list under the rabbit icon scrolls the page instead:

![](http://f.cl.ly/items/3X021S1T3o0I0I3n0727/Screen%20Recording%202015-03-10%20at%2004.37%20PM.gif)

(this looks odd due to GIF compression, but you get the idea.)

This does't happen in Chrome.

**Comment by pkaminski** [comment]
Works in Chrome and Firefox, so looks like it's a Safari bug.  I'll try to look for workarounds.

**Comment by pkaminski** [comment]
A friend played with this for a while, and apparently scrolling that pane will sometimes work and sometimes not.  We tried a few possible workarounds from the web but nothing made it work consistently.  At this point, I'm going to call it as a bug in Safari and mark as won't fix, unless somebody has ideas on other workarounds to try.
