### ISSUE TITLE
Don't flatten comment threads when failing to attach to a line

### ISSUE THREAD

**Issue by dennwc** [Reviewable/Reviewable#660]
Currently, when loading of existing comment threads fails due to Reviewable unable to find code line to attach them to, it flattens all threads and presents them as top-level discussion comments.

Instead, it will be nicer to present those threads as top-level discussion threads, even without a specific line to attach the thread to.

**Comment by pkaminski** [comment]
Indeed, that would be nicer.  (The current behavior is because top-level discussion threads were implemented long after comment importing.)

**Comment by pkaminski** [comment]
<details><summary>Internal notes:</summary>
To reproduce this, try adding a comment on a deleted line in GitHub.  It's not consistent, though.  Look in <code>comments.ts</code> for <code>mapPullRequestComment</code> for the algorithm, and in <code>extractComments</code> for the fallback code if the mapping fails.
</details>
