### ISSUE TITLE
Docs are not indexed by Google

### ISSUE THREAD

**Issue by pkaminski** [Reviewable/Reviewable#661]
The docs web site at https://docs.reviewable.io is not being indexed by Google, no matter how many times I ask it to do so.  Looks like Docsify (used to generate the docs) isn't compatible with Google's crawler (ref https://github.com/docsifyjs/docsify/issues/231).  Looks like Docsify will support static HTML generation in v5 (https://github.com/docsifyjs/docsify/issues/657) but I really wanted to avoid that, so maybe it's time to look for another dynamic renderer that is crawler-friendly.

**Comment by dhbradshaw** [comment]
![image](https://user-images.githubusercontent.com/231662/86593680-4774fd80-bf5b-11ea-9c48-febc10f1e0d4.png)

**Comment by dhbradshaw** [comment]
And it looks like it finally got indexed!

![image](https://user-images.githubusercontent.com/231662/86919280-9b175080-c0ed-11ea-983d-a3c018c563bb.png)
