### ISSUE TITLE
Discussion dismissal settings

### ISSUE THREAD

**Issue by marczych** [Reviewable/Reviewable#662]
Currently, anyone with push permissions to the repo can dismiss anyone else from a discussion. It'd be great to have some settings for that so it isn't so easy for the PR author to merge a PR after bypassing important discussions. Perhaps an admin-only setting would work well?

**Comment by pkaminski** [comment]
I added an option to the repo settings panel that lets you choose between push or admin permissions required for dismissing.

**Comment by marczych** [comment]
Awesome, thank you!
