### ISSUE TITLE
Very large PR in the past makes home page unusable

### ISSUE THREAD

**Issue by alex-xnor** [Reviewable/Reviewable#664]
A while ago, we had a review on a very large PR (~2000 files, ~100,000 added lines, ~100,000 removed lines, mostly renames, ~10 revisions). I don't particularly expect Reviewable to handle this very well, so we reviewed it outside of Reviewable and then unblocked the merge using a custom completion condition [as suggested here](https://gitter.im/Reviewable/Reviewable?at=5d38f7ce0bb0ac39beacd5a2).

We thought that after it was merged, Reviewable wouldn't care about it any more, and we could move on. However, even though it's all merged and we don't plan to review it any more and have no desire to revisit that review, the reviewable.io home page, which normally shows all PRs that are waiting for your review, is completely unusable, hanging on load. While I would expect bad performance when visiting the review itself, the home page should probably not hang, especially due to a PR that is "done" as far as Reviewable is concerned.

**Comment by pkaminski** [comment]
Hey Alex, that is indeed unexpected and undesirable.  What stage of loading does the page stop at?  (i.e., what's the last spinner message you see)  My guess is that it's trying to load file information for the review and getting bogged down there, but I wouldn't expect it to cause a delay of more than some tens of seconds at worst.

Also, this should fix itself within 3 days after the PR was closed, since it'll fall outside the default horizon for the closed PRs query.

**Comment by alex-xnor** [comment]
It gets stuck on "Loading data".

**Comment by pkaminski** [comment]
Yep, that's the stage where it loads review data from Firebase.  :(  Could you please open the page, wait a while (30 seconds or so, say), then run `Truss.computedPropertyStats.log()` from the console and paste the results here?  I can't imagine 2000 files taking so long to load in and of themselves, so perhaps the real issue is an unoptimized computation somewhere.

**Comment by alex-xnor** [comment]
I had a tab open in the background and it did actually finish loading after a while, I was just impatient. It took about a minute. (In contrast with the review page itself [1]) This isn't great but I don't think it counts as "unusable" any more, especially after knowing that it resolves after three days, so I'm closing this issue.

[1] Which hung for about 30 minutes before displaying a Reviewable error page saying roughly (paraphrased from memory) "Reviewable had a problem but it doesn't look like our fault, here's why: undefined: 0: out of memory"

**Comment by alex-xnor** [comment]
Here's the result after it finished:

```
Truss.computedPropertyStats.log()
b.verificationNeeded:  1.48s  (18.5%)      75 upd /    255 runs  (29.4%)  5.81ms / run 4ab7c065.libs.js:19:12000
 a.directReviewLevel:  1.43s  (17.9%)   51079 upd / 150374 runs  (34.0%)  0.01ms / run 4ab7c065.libs.js:19:12000
a.draftReviewMarkRef:  0.76s   (9.5%)     125 upd /  51204 runs   (0.2%)  0.01ms / run 4ab7c065.libs.js:19:12000
               a.num:  0.57s   (7.1%)   99400 upd /  99426 runs (100.0%)  0.01ms / run 4ab7c065.libs.js:19:12000
   a.draftReviewMark:  0.51s   (6.4%)   51079 upd / 102283 runs  (49.9%)  0.00ms / run 4ab7c065.libs.js:19:12000
           a.renamed:  0.48s   (6.0%)       0 upd /  51079 runs   (0.0%)  0.01ms / run 4ab7c065.libs.js:19:12000
              a.list:  0.37s   (4.7%)    2375 upd /   4699 runs  (50.5%)  0.08ms / run 4ab7c065.libs.js:19:12000
       a.reviewLevel:  0.31s   (3.8%)   53386 upd / 104472 runs  (51.1%)  0.00ms / run 4ab7c065.libs.js:19:12000
a.lastReviewedByUser:  0.22s   (2.7%)    2307 upd /   4660 runs  (49.5%)  0.05ms / run 4ab7c065.libs.js:19:12000
     a.nearestUnkept:  0.21s   (2.6%)    4614 upd /   4614 runs (100.0%)  0.05ms / run 4ab7c065.libs.js:19:12000
           --- Above:  6.34s  (79.3%)  264440 upd / 573066 runs  (46.1%)  0.01ms / run 4ab7c065.libs.js:19:12000
           === Total:  7.99s (100.0%)  523487 upd / 855830 runs  (61.2%)  0.01ms / run 4ab7c065.libs.js:19:12000
undefined
```

**Comment by pkaminski** [comment]
Thanks, looks like the delay isn't coming from computed properties as they only add up to 8s.  We'd need to go to full-on profiling to track it down, which may not be worth it.

**Comment by alex-xnor** [comment]
I tried using the Performance tab of the developer tools to record. There seems to be some overhead in enabling that since I waited like 5 minutes and it was still going, whereas it finished after 1 minute without. But here are some screenshots (probably not so useful because all the names are minified, but it's something). The first screenshot shows the whole recorded history:

![reviewable1](https://user-images.githubusercontent.com/29713761/61907359-22ba7e00-aee2-11e9-89d8-8d7f894932c0.png)

This second screenshot zooms in on the second part which appears to have a very regular, repeating structure:

![reviewable2](https://user-images.githubusercontent.com/29713761/61907391-3534b780-aee2-11e9-89a1-b6a98118e705.png)

If it matters, I'm using Firefox 68.0.1 on Ubuntu 16.04.6. Hopefully this provides some insight if you are trying to look into it.

**Comment by pkaminski** [comment]
Yeah, this is going to be all but impossible to interpret.  :(  I see some stuff related to computed properties, but it's hard to tell whether it's just the 8s reported by Truss getting blown out by the profiler instrumentation or something else.  Honestly, these profiles are hard to read even with all debugging symbols present, so I don't see a good way to move forward at this point.
