### ISSUE TITLE
Provide option to insert Reviewable badge at top of PR description

### ISSUE THREAD

**Issue by pkaminski** [Reviewable/Reviewable#666]
As suggested by @dozoisch:

> We're using Reviewable for pretty much all our reviews in our private repos. I say pretty much because sometimes I (derp) just forget about the button and since the button is at the bottom of the PR description, and go directly to the files view in GitHub.
> 
> I saw that there are some options to put the description in the body of the description, in a comment or hide it completely. It would be awesome if we could set it so it is inserted at the top of the description instead of the bottom as a 4th option, so that it's accessible without having to scroll the view.

**Comment by aaronfi** [comment]
Got this working.  Will post a PR tomorrow.

![image](https://user-images.githubusercontent.com/5179129/77246325-5c639600-6be3-11ea-81ec-188e49f8c3b8.png)

![image](https://user-images.githubusercontent.com/5179129/77246311-24f4e980-6be3-11ea-8e5b-1aa5d6feaa27.png)

**Comment by aaronfi** [comment]
Three PRs now merged -- this just needs deploying.  Will rely on @pkaminski to deploy.

**Comment by pkaminski** [comment]
Deployed!  Thanks @aaronfi, and please give it a try @dozoisch.

**Comment by dozoisch** [comment]
Amazing 🙌 thanks

**Comment by dozoisch** [comment]
Set all our repos to it! Works really well and had some people on the team comment on the fact that it awesome it was at the top now =)
