### ISSUE TITLE
PR list: Middle-click on the PR line does not work

### ISSUE THREAD

**Issue by misha-tectonic** [Reviewable/Reviewable#667]
What works:

- Clicking on a PR line in the list of PRs opens this PR.
- Cmd+Clicking on the PR line opens this PR in the new tab.

What does not work:

- Middle-button clicking on a PR line does not open this PR in the new tab.

Middle-button clicking works only on _names_ of PRs in the list.

**Comment by pkaminski** [comment]
Bogdan, could you take a look at this please?  Thanks.

**Comment by feldgendler** [comment]
This has changed now: middle-clicking anywhere on the PR line opens it in the new tab, but a foreground instead of a background one. Normally middle-clicking a link in Chrome opens it in a background tab, this is what I expect.

**Comment by pkaminski** [comment]
@badz0 can you see if this is possible, and if so apply the fix to any other middle-button handlers?  Thanks.

**Comment by feldgendler** [comment]
Instead of handling the middle click, I would suggest to make the entire element a link. Then the browser will handle various clicks on it consistently with other links, including middle click to open in the background.

**Comment by jwnimmer-tri** [comment]
I also used to be able to do right-click "Open in new Tab" on the PR list, but that stopped working a few days ago.  (FF 68.0.2, Ubuntu).

**Comment by pkaminski** [comment]
> Instead of handling the middle click, I would suggest to make the entire element a link. Then the browser will handle various clicks on it consistently with other links, including middle click to open in the background.

That's tricky, as it's a table row and there are nested links in there.

> I also used to be able to do right-click "Open in new Tab" on the PR list, but that stopped working a few days ago. (FF 68.0.2, Ubuntu).

Recent pushes didn't touch the dashboard AFAIK so not sure what could have changed...

**Comment by feldgendler** [comment]
> That's tricky, as it's a table row and there are nested links in there.

Alright, just the full width of the table cell is enough. (I would actually apply it to all the cells except the last column where there is a link.)

**Comment by bitdancer** [comment]
I also noticed the right-click-open-in-new-tab stopped working, in FF on linux.  I though it was working as of last Wednesday, but I can't be 100% sure.  Also, hovering over the title no longer shows the URL of the link, which I used to use to find the issue number.  I see that the issue number is now on the far right, so that isn't as big of an issue, but I really depend on right-click-open-in-new-tab for my normal workfow, so that problem is really bugging me.  I personally would be fine if just the title were a normal link that the browser would handle like all other links.

**Comment by KarolisL** [comment]
On Safari `Version 12.1.2 (14607.3.9)` middle-clicking the row opens two new tabs with the same content: one in background, and second in foreground (focused). Cmd-clicking works as expected.


Please forgive me for using MacOS Internet Explorer. :-))

**Comment by pkaminski** [comment]
I believe this should be fixed now, hopefully making everybody happy (modulo perhaps ~Internet Explorer~ Safari -- who knows what's going on there).  There are some scenarios where Reviewable needs to take control of the middle click if you haven't granted sufficient authorization prior to opening the review, but for most established users the middle click (or cmd/control click) will now pass through to the browser and let it do its thing most anywhere within a row.  (Two small exceptions:  the cell with the PR link won't link to the review, and the bit of padding around a merge button will be non-active as well.)

Let me know if this works for you or if you find more flaws!

**Comment by bitdancer** [comment]
Works for me, thanks!

**Comment by KarolisL** [comment]
Looks like it is fixed in ~~Internet Explorer~~ Safari. Thank you!
