### ISSUE TITLE
Terraform (and HCL) syntax highlighting

### ISSUE THREAD

**Issue by misha-tectonic** [Reviewable/Reviewable#668]
Please add Terraform (.tf) and HCL (.hcl) syntax highlighting.

There is a separate highlight.js "plugin" for that: https://github.com/highlightjs/highlightjs-terraform

**Comment by pkaminski** [comment]
I'll see what I can do, but I'm currently using the highlight.js web-based package builder to make a custom package so adding a separate "plugin" may well require a completely different build mechanism.  (Or perhaps I'll get lucky and I can just load it in as an additional dependency -- we'll see.)

**Comment by pkaminski** [comment]
Added.
