### ISSUE TITLE
"end" key scrolls to the bottom of the page while typing a comment

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#67]
I would expect it to move the cursor to the end of the comment box, rather than scrolling the page to the bottom.

I saw this on both Safari & Chrome on OS X.

**Comment by pkaminski** [comment]
Unable to reproduce on Windows, so looks like it's specific to OS X.  I don't do anything special with the comment boxes though -- they're just textareas.  Can you check if this happens on non-Reviewable pages with textareas too?

**Comment by danvk** [comment]
Looks like home/end behave oddly across the web on OS X. Lame :)
