### ISSUE TITLE
Unmapped GitHub line comments

### ISSUE THREAD

**Issue by bb010g** [Reviewable/Reviewable#670]
Reviewable is reporting "Reviewable was unable to map this GitHub line comment to the right spot--sorry!" on the review https://reviewable.io/reviews/piroor/treestyletab/2368 for the issue https://github.com/piroor/treestyletab/pull/2368. As per https://github.com/Reviewable/Reviewable/issues/14#issuecomment-143932944, I'm opening an issue for this case.

Reviewable is on by default for pull requests I create, but not for the target repository. I did create and do own the issue, but I do not own or have special permissions in the repository. I first visited the Reviewable URL after all aforementioned comments were present. There have been five commits pushed total, all associated to the PR during creation with their branch. The review shows one revision for that set. There is one comment that succeeds to map, the first in the thread, and it is the first in time at 2019-08-23T01:22:57Z, responding to the fifth, latest commit, which is the final commit in the first (and only) revision. There are six comments that fail to map, spanning the range of time from 2019-08-23T01:53:22Z to 2019-08-23T02:16:44Z (~23 minutes, starting ~30 minutes after the initial mapped comment), coming from the same user, and responding to diffs from the second, second, second, fourth, fourth, and fourth commits, respectively (again, all commits in that first revision created initially along with the PR).

On the side, is there a way to manually associate comments that failed mapping to their proper revisions & lines? It'd be really handy for cases like this where even if the issue gets fixed, unless the fix is retroactively applied to the reviews that (re)produced it, Reviewable is just a lot less useful without the creation of a new PR or deletion & resubmission of problematic GitHub comments directly to Reviewable.

**Comment by pkaminski** [comment]
Hey @bb010g, thanks for letting me know.  I'm currently traveling so won't be able to take a proper look at this until after the weekend -- sorry.

At this point, I'm focusing Reviewable on the whole-team-adoption use case so it's unlikely that I'll add a way to manually locate GitHub comments.  (In fact, I'm considering removing the "all my PRs" setting altogether, as it seems to create more problems than it solves...)

**Comment by bb010g** [comment]
No problem about the delay.

I'd be disappointed if automatic Reviewable on every personal PR was removed, as it can still be handy on more complex change sets and it's a nice way to introduce Reviewable & get them on board for repo- or org-wide usage.

**Comment by pkaminski** [comment]
I finally got a bit of time to look into this -- thanks for providing a clean case for me to examine!  It turned out that the comment mapping logic itself was fine, but the revision splitting algorithm didn't deal appropriately with GitHub review comments posted in one review but targeting multiple commits.  This is now fixed but not retroactive, sorry.
