### ISSUE TITLE
Undocumented properties in the review state object

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#672]
The review state object de facto has properties not shown or described in the documentation (https://docs.reviewable.io/#/repositories?id=completion-condition):

`pullRequest.title`
`pullRequest.body`
`pullRequest.requestedTeams`
`pullRequest.approvals`

Also, the property `discussions[...].target.base` is mentioned in the document but not present de-facto.

**Comment by pkaminski** [comment]
Thanks -- all of these should be fixed momentarily.

**Comment by feldgendler** [comment]
Verified, thank you!
