### ISSUE TITLE
Simple settings flag to turn off extra styles

### ISSUE THREAD

**Issue by brendanwalters** [Reviewable/Reviewable#674]
https://docs.reviewable.io/#/accountsettings?id=custom-stylesheet notes that "We also have a few extra styles used to highlight tabs, trailing whitespace, and lack of final newline that you can customize:" but explicitly choosing a standard CSS style (e.g. from highlight.js) still applies those extras on top.

Instead of requiring users to host a custom CSS file to specifically override those extra styles, a checkbox or set of checkboxes to turn them off from the settings dropdown would be very helpful, particularly with the visible characters inserted into hard tabs, which are visually distracting (especially in languages like Go where use of hard tabs is standard and enforced by formatting tools).

**Comment by pkaminski** [comment]
I try pretty hard to keep settings minimal by having sensible defaults and leaving everything else to external files.  In this specific case, Go diffs should already be suppressing hard tabs but there was a small regression -- sorry, and fixed.
