### ISSUE TITLE
No way to detect discussions requiring attention

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#677]
I'm trying to mimic the logic that Reviewable uses to select discussions requiring a user's attention. The "to reply" count in the top bar cycles among such discussions when you click it. However, in the custom completion function there seems to be no way to see if there are any attention-needing discussions for a particular user.

I filed a non-blocking review comment:

```json
    {
      "numMessages": 1,
      "resolved": false,
      "participants": [
        {
          "username": "feldgendler",
          "disposition": "discussing",
          "resolved": true,
          "lastActivityTimestamp": 1567520188356
        },
        {
          "username": "wojciech-tectonic",
          "disposition": "following",
          "resolved": false,
          "lastActivityTimestamp": 1567520188356
        }
      ],
      "target": {
        "file": "kraken/burner/controller/cmd/main.go",
        "revision": "r4",
        "base": false,
        "line": 20
      }
    }
```

The PR author acknowledged it:

```json
    {
      "numMessages": 1,
      "resolved": true,
      "participants": [
        {
          "username": "feldgendler",
          "disposition": "discussing",
          "resolved": false,
          "lastActivityTimestamp": 1567520188356
        },
        {
          "username": "wojciech-tectonic",
          "disposition": "satisfied",
          "resolved": true,
          "lastActivityTimestamp": 1567520351529
        }
      ],
      "target": {
        "file": "kraken/burner/controller/cmd/main.go",
        "revision": "r4",
        "base": false,
        "line": 20
      }
    }
```

After this, I had this discussion as needing attention (it was showing that somebody's disposition had changed). After I acknowledged that, the discussion no longer needed my attention. However, nothing in the input to the completion function has changed: after I acknowledged the discussion, its description was exactly the same as in the second snippet.

**What I'm trying to do:**

We have a robot that merges eligible PRs automatically as soon as all tests pass and the review is completed. The moment the completion function says `completed: true`, the PR might get auto-merged. But we don't want to do that while people still have unread messages in Reviewable, even if they are in resolved discussions. In other words, if a particular review participant would see a nonzero "to reply" count in the top bar which would take them to some discussions when clicked, I want my function to block the review and put that user in `pendingReviewers` so that they notice it and read/acknowledge the message. Every discussion participant has to have seen everything in it for the PR to be auto-merged.

Is there a way to achieve this that I'm not seeing, or is it something that needs to be added to the discussion descriptions fed to the custom completion function?

**Comment by pkaminski** [comment]
This is intentional:  a discussion's unread status is for that user only, and cannot be used to decide whether a review is complete or not.  Use the resolution status for that.  In the scenario you describe, your disposition is `discussing` which specifically means that you don't care whether the discussion gets resolved or not -- and by extension, whether it blocks the PR from merging or not.

Correct use of the disposition system should address this issue; note that you can set your disposition defaults to `blocking` to default to (roughly) your preferred semantics.  Is there a reason why this doesn't work for your team?

**Comment by feldgendler** [comment]
Here is the scenario: sometimes a reviewer wants to leave a comment without blocking the review. It goes like "I'd do it this way, but it's up to you". The PR author should read it and decide if to follow the advice. We use the distinction between blocking and non-blocking comments to reflect the difference between "must change" and "up to you".

We don't want to auto-merge the review before the author has read the comment so that they have a chance to decide whether to act on it. We don't want to file the comment as blocking, either, because if the author decides to not follow the advice, they will have to comment and wait for the reviewer to resolve the discussion (that's one round-trip longer).

Why do we want to block on unread? Because any unread messages have the potential to be replied to (continuing the discussion) or causing the author to add more changes to the PR. That's the whole point of ever writing a message. If I can't be sure that a message I'm about to post will reach the other participants _before_ the PR is merged, I have to resort to other means of communication such as Slack. I'd really prefer to keep all communication related to a PR in Revieweble discussions.

**Comment by pkaminski** [comment]
I think you may be confused about the disposition semantics -- your scenario should work perfectly with the existing system.  You just need to leave your non-blocking comment with a disposition of "discussing".  This leaves the discussion unresolved (i.e., blocking merge).  When somebody else replies to the comment, they can either set their disposition to "satisfied" (which would resolve the discussion and potentially trigger a merge), or use any other disposition  (e.g., "discussing" or "blocking") to keep the discussion unresolved and preventing a merge.

The only kind of comment you can make that would create an already-resolved discussion that wouldn't block a merge is if you use the "informing" disposition.  This is intended precisely for side conversations that shouldn't impact the review and the merge.

Does this make sense?

**Comment by feldgendler** [comment]
Alright, it seems like for our workflow, _Informing_ is harmful: it risks sending the message into nowhere. So let's forget about _Informing_, and say we always use _Discussing_ for non-blocking comments.

Exhibit A.

Suppose one raises a non-blocking comment (_Discussing_). Two other people join and exchange messages, all staying _Discussing_. Then one decides he has nothing more to say, and clicks the default button, which is _Resolve_. It sets their status to _Satisfied_ and resolves the discussion, which can cause the PR to be merged before the other two participants have a chance to do anything.

Exhibit B.

One raises a _Blocking_ comment. The PR author disagrees that the code needs to be changed, and posts their objection in the discussion. He is in favor of closing the discussion, so his disposition is _Satisfied_. The discussion-starter posts one more argument in favor of changing the code, but ends his message with "...but it's up to you". He decides not to insist, so that the PR author can consider this new argument and decide whether to change the code. It should be OK to not change it. The discussion-starter changes their disposition to _Discussing_. But because the PR author is already _Satisfied_, this resolves the discussion and can merge the PR before the author can consider making the change.

**Comment by feldgendler** [comment]
I've posted my vision of the ideal world in https://github.com/Reviewable/Reviewable/issues/683. It would resolve these scenarios for us, as well as many other cases.

**Comment by pkaminski** [comment]
Scenario A is working precisely as expected and desired.  None of the participants cares whether the discussion gets resolved or not, so when one decides to resolve it that's that.  If you care, set your disposition to Blocking.

Scenario B is indeed unsupported in the current scheme: once somebody is Satisfied, you must stay Blocking to prevent the discussion from resolving.  At that point, there's no way to say "feel free to resolve after you've read my comment" any more.  Note, however, that you are warned that switching your disposition to Discussing will resolve the discussion.

Let's take the conversation on how to improve on these semantics to #683.
