### ISSUE TITLE
Files declared unreviewed by custom function not shown as such to reviewer

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#678]
This is the PR description:  [1811.txt](https://github.com/Reviewable/Reviewable/files/3570253/1811.txt)

According to our policy, this PR has to be reviewed by both people listed as assignees. In this PR, these would be `feldgendler` (that's me) and `misha-tectonic`. However, the last revision of the only file in the PR has been reviewed only by `misha-tectonic`.

For this reason, our custom review function produces the following result for this PR:

```js
{ completed: false,
  description: '1 of 1 file unreviewed; unread messages for 1 participant',
  shortDescription: '1 unreviewed file; unread messages',
  pendingReviewers: [ { username: 'feldgendler' }, { username: 'yael-frank' } ],
  disableGitHubApprovals: true,
  files:
   [ { path: 'kraken/doc/state-machines/tks-manager.md',
       revisions:
        [ { key: 'r1', reviewed: false },
          { key: 'r2', reviewed: false },
          { key: 'r3', reviewed: false },
          { key: 'r4', reviewed: false },
          { key: 'r5', reviewed: false },
          { key: 'r6', reviewed: false } ] } ],
  debug:
   [ [ 'Assignees', [ 'feldgendler', 'misha-tectonic' ] ],
     [ 'Checking for empty reviewer set' ],
     [ 'Checking for unreviewed files' ],
     [ 'Failure', '1 of 1 file unreviewed', [ 'feldgendler' ] ],
     [ 'Checking for unresolved discussions' ],
     [ 'Failure',
       'unread messages for 1 participant',
       [ 'yael-frank' ] ] ] }
```

As you see, all six revisions are declared as unreviewed (because a review from me is missing), and I am listed in `pendingReviewers`. Reviewable shows this PR in the _Awaiting my action_ list. So far, so good.

However, when I open the PR in Revieable, I see gray 0 for "unreviewed" in the top bar, and clicking it doesn't navigate to the file I haven't reviewed. The eye is grey.

**Expected result:** the top bar shows me a nonzero unreviewed count, and clicking it lets me navigate to what's left to review (revisions where my function set `reviewed: false` AND not marked as reviewed by me).

Also, the eye on those files should perhaps be red. Grey should be for files with `reviewed: true` but which I personally haven't reviewed.

**Comment by pkaminski** [comment]
Hmm, I have a theory as to what's going on...  Is there an "Include changes in files previously reviewed only by others" checkbox in the Changes panel at the top?  If so, could you turn it on and see if it produces the expected behavior?

The "unreviewed 0" counter was a bug that I've now fixed, sorry.

**Comment by feldgendler** [comment]
The checkbox was on, and still is.

After your fix, the review now behaves exactly as I expected, thank you!
