### ISSUE TITLE
PR does not appear in My Reviews

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#679]
Here is the PR: 
[2033.txt](https://github.com/Reviewable/Reviewable/files/3572991/2033.txt)

Here is the output of our custom completion function for this PR:
```js
{ completed: false,
  description: '4 of 4 files unreviewed; all discussions resolved',
  shortDescription: '4 unreviewed files; all discussions resolved',
  pendingReviewers: [ { username: 'feldgendler' } ],
  disableGitHubApprovals: true,
  files:
   [ { path: 'kraken/api/postman/tectonic-demo.postman_environment.json',
       revisions: [ { key: 'r1', reviewed: false } ] },
     { path:
        'kraken/api/postman/tectonic-integration.postman_environment.json',
       revisions: [ { key: 'r1', reviewed: false } ] },
     { path:
        'kraken/api/postman/tectonic-minikube.postman_environment.json',
       revisions: [ { key: 'r1', reviewed: false } ] },
     { path: 'kraken/api/postman/tectonic.postman_collection.json',
       revisions: [ { key: 'r1', reviewed: false } ] } ],
  debug:
   [ [ 'Assignees', [] ],
     [ 'A global reviewer must review in addition to the assignees',
       [ 'feldgendler', 'misha-tectonic' ] ],
     [ 'Checking for empty reviewer set' ],
     [ 'Checking for unreviewed files' ],
     [ 'Failure', '4 of 4 files unreviewed', [ 'feldgendler' ] ],
     [ 'Checking for unresolved discussions' ],
     [ 'Success', 'all discussions resolved' ] ] }
```

**Expected:** PR appears in _Awaiting my action_ for me because `pendingReviewers` in the output of the custom completion function includes me.
**Actual:** PR does not appear anywhere in _My Reviews_.

**Comment by pkaminski** [comment]
If this is a bug, it's unrelated to the completion condition as it can't affect the presence or absence of a PR in the list.  Do you perhaps have a query filter set, or maybe the PR is old (stalled) and elided by default?

**Comment by feldgendler** [comment]
No filter, not stalled.

Once I do something with the review (such as mark something as reviewed), the review starts appearing in _My Reviews_.

> unrelated to the completion condition as it can't affect the presence or absence of a PR in the list.

I thought the function can put the PR in someone's _Awaiting my action_ list by including them in `pendingReviewers`. Quoting you from Gitter:

> Does the repo have a custom review completion condition and was that changed recently? It has full control over the users being awaited by a review.

**Comment by pkaminski** [comment]
Ah, I think I see what's going on.  The condition output can affect placement of the PR on the list (moving it from one section to another), but not presence.  The list contents are driven solely by GitHub PR queries, so if you haven't touched a PR in any way it likely won't appear on the list.

You may wish to experiment with other mechanisms to expand the range of PRs returned by the query:
1. Request review by a team you're a member of.
2. Turn on "also show pull requests you're not involved with from all repos to which you can push", optionally filtered down to avoid pulling in too much.
3. If you're using a mono repo at work, try using a repo-specific listing page (https://reviewable.io/reviews/<i>owner</i>/<i>repo</i>).

Once you get the PR onto your list somehow, the condition will lift it up to the top section.

**Comment by feldgendler** [comment]
> Turn on "also show pull requests you're not involved with from all repos to which you can push", optionally filtered down to avoid pulling in too much.

At least at first glance, this seems to solve the problem for me. I don't know what I don't know, so I'll reopen this if I find out about reviews that should be visible but aren't.
