### ISSUE TITLE
Review crashes Reviewable

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#68]
I'm consistently getting a crash screen whenever I visit:
https://reviewable.io/reviews/hammerlab/cycledash/510#-Jk4SZm6c46pR6_wG8Tr

![screen shot 2015-03-11 at 1 50 30 pm](https://cloud.githubusercontent.com/assets/98301/6602996/98d2a69a-c7f5-11e4-80db-dd0d7068cfa8.png)

cc @ihodes

**Comment by pkaminski** [comment]
Apologies, the server had a bit of a heart attack this morning, exact cause unknown yet.  Everything should be back to normal now, and my next goal is to make it more reliable and redundant.
