### ISSUE TITLE
Links to comments broken

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#680]
1. Focus a discussion.
2. Copy the URL from the address bar. (The fragment part contains a unique discussion key.)
3. Open that URL in a new tab.

**Expected:** the same discussion is focused.
**Actual:** the PR is opened as if the URL had no fragment. No discussion is focused.

Fallout from the recent front-end rewrite?

**Comment by pkaminski** [comment]
Yep, something regressed.  Will fix.

**Comment by pkaminski** [comment]
Fixed.
