### ISSUE TITLE
Feature request: discussion IDs in custom function input

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#681]
It would be useful to have the discussion keys that are used as fragment in the URL, in the discussion object in the custom completion function input. When diagnosing problems, it would be very helpful to be able to find which discussion object corresponds to which discussion in the UI.

**Comment by pkaminski** [comment]
I've been keeping internal IDs out of that structure on purpose so far.  I can see how it would be helpful, but given that the need should be only occasional is the included filename / revision / line info sufficient?  (It won't help for top-level discussions, but those are also reasonably rare in my experience.)

**Comment by feldgendler** [comment]
We are using that, which is far more awkward. And it's not enough if there is more than one discussion attached to the same line.

If you're doing it on purpose, what's the purpose? Can't imagine what harm it would do if the IDs were there. Most of the time, just a useless property to be ignored, but occasionally useful for debugging.

**Comment by pkaminski** [comment]
I'm generally not keen on revealing internal data (even if harmless), but in this case since selecting a discussion in the UI already shows the ID in the anchor I guess I might as well do it.
