### ISSUE TITLE
"Unable to capture head commit" on certain PRs

### ISSUE THREAD

**Issue by misha-tectonic** [Reviewable/Reviewable#682]
https://reviewable.io/reviews/tectonic-network/tectonic/2036 gives "Review broken: Unable to capture head commit".

AFAICT, the review in GH is OK: base and PR branches exist.

Please tell me what other information is needed.

**Comment by pkaminski** [comment]
Apologies -- this was a side-effect of a change I pushed last night that looked stable for a few hours.  Rolled back while I figure things out.  If you load a broken review it should get automatically fixed within 15 seconds or so.
