### ISSUE TITLE
Discussion-resolving semantics don't support iterative consensus

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#683]
This is a feature request / invitation for a discussion. You will amost certainly close it because that's not how Reviewable works. I still hope that something useful comes out of it, maybe in the form of slight tweaks to the existing logic.

# Iterative consensus

OK, here is what I call **iterative consensus**.

A discussion has N participants. They can append messages to the discussion and/or declare that they think a consensus is reached. One can post a message, call consensus, or do both at the same time.

A consensus mark posted by a participant is cleared when a new message is posted to the discussion (but not when someone posts a consensus mark without a message). This is because, even if the participant agrees with everything said so far, they still haven't had a chance to take a stance towards this new message. The database tracks the consensus marks from each participant separately.

When the discussion has consensus marks _from all participants_ simultaneously, it becomes resolved.

A discussion is brought to a participant's attention if the last message in it is written by someone other than this participant, AND there is no consensus mark from this participant.

There is no such thing as "marking as read" without any other action. Everything is transparent (everyone can see everyone's consensus marks). If a discussion is brought to your attention, you cannot just snooze it (except by removing yourself from the discussion). You must either post a comment, or indicate that you have no objections, or do both.

# How it could be used in Reviewable

Let's forget for a moment that Reviewable already exists and has established workflows.

Rule: The PR author is automatically added as a participant to every discussion, and cannot leave.

Rule: The discussion-starter can leave (or get dismissed by someone else).

Rule: Anyone @-mentioned in a discussion is automatically added to it as a participant. They can leave (or get dismissed by someone else).

The numbers below are alternative scenarios. 1.1.1 and 1.1.2 are two alternative continuations of the scenario 1.1. 

1: A reviewer wants the PR author to change their code. The reviewer posts a discussion without a consensus mark. The author is automatically a participant.

1.1: The PR author makes the change and posts _Done_ with a consensus mark.

1.1.1: The discussion-starter is satisfied with the change. They post a consensus mark without a message, and that resolves the discussion.

1.1.2: The discussion-starter is not happy with the change. They post a comment without a consensus mark, and the scenario is restarted.

1.2: The PR author disagrees that the change is necessary. They post a comment about it with a consensus mark.

1.2.1: The discussion-starter agrees and decides not to insist. They post a consensus mark without a comment, and the discussion is resolved.

1.2.2: The discussion-starter insists that the change is necessary. They post a comment without a consensus mark, and the scenario is restarted.

1.2.3: The discussion-starter has a further argument but decides to leave the decision to the PR author. They post a comment with a conensus mark. The scenario continues in the same way as after 2.

2: A reviewer wants to suggest a way for the PR author to improve the code, but doesn't think it should block the review. They post a discussion with a consensus mark. The author is automatically a participant.

2.1. The PR author decides to do the change. They add a commit, then post _Done_ with a consensus mark. The scenario continues in the same way as after 1.1.

2.2. The PR author decides not to do the change. They post a consensus mark without a comment, and the discussion is resolved.

3: One of the participants in an ongoing discussion wants to hear from yet another person, who is currently not a participant. They @-mention that person.

3.1. The invited person thinks the code needs to be changed. They post a comment without a consensus mark. The scenario continues roughly as after 1, except that everything now needs to be vetted by all participants.

3.2. The invited person doesn't think the code needs to be changed. They post a comment with a consensus mark. The other two participants can agree (post consensus marks) or keep posting comments.

3.3 The invited person doesn't have an opinion (for example, doesn't really have knowledge of the subject). They post a comment and leave the discussion.

# Informational comments

The above logic can simulate almost every scenario that's possible in Reviewable today, while ensuring that every message is read and considered.

The two scenarios that are left are _Working_ and _Informing_. They can be solved by adding the ability to post a message without clearing any current consensus marks from other participants, and without explicitly bringing the discussion to the attention of others. For all intents and purposes, it is as if the informational comment wasn't written, but it is there if you look, and it's delivered by email like normal comments.

4: The PR author wants to let the discussion-starter know that work is in progress. They post an informational comment like "Working on it". This doesn't bring the discussion to anyone's attention, but If anyone cycles through unresolved discussions, they'll see that comment and won't wonder why the PR author is not reacting.

5: A reviewer wants to inform the PR author about something without suggesting a code change. They post an informational comment. The discussion starts out as resolved because it has no messages (zero non-informational messages are treated like there already is a consensus).

# Conclusion

The iterative consensus logic can simulate pretty much everything that's possible in Reviewable discussions today, with much simpler rules that are easier to explain. I have read the rules in https://docs.reviewable.io/#/discussions several times, and I can apply them mechanically, but I don't understand why exactly they are the way they are, and I'm often confused as to which disposition to use when.

I don't really expect that you drop everything and switch to iterative consensus. Plus it probably would break some people's workflows in ways I don't see. But this is something we would be happy to use, and if we could simulate this somehow, escpeciall in three-way discussions, it would make us happier.

Thank you for your attention!

**Comment by pkaminski** [comment]
Thanks for working this out in such detail!  So as I understand it, the main new idea your approach brings to the table is a sort of "conditional satisfaction" that gets negated if any new comments get posted.  As it happens, this is pretty much how Reviewable originally worked, some 5 years ago:  you could only reply to or acknowledge a discussion, and these were also the only ways to mark a discussion as read, so the read timestamp essentially doubled as the approval timestamp.  I thought this was a very clever and convenient method of managing discussions.

It didn't work out.  Users by and large didn't "get it" and couldn't get used to this way of working.  I tried a number of improvements to both make things clearer and satisfy more use cases but they didn't help.  It's entirely possible that something more like your scheme would've found the usability sweet spot, but it's not what I came up with and eventually threw in the towel and switched to the explicit disposition system we have now.  As you've guessed correctly, that ship has sailed.

If you'd like to propose changes they must work within the current framework.  I could imagine some kind of "conditionally satisfied" disposition that changes to blocking if more comments are posted, but we'd have to work through the details and I'm honestly not sure if the added complexity would be worth it so it might not make the cut anyway.  Still, I'm happy to keep the discussion going (even though I'm going to close this issue 😄).

As for the complexity of the current rules, I'm not sure what you mean:  the entire resolution algorithm fits in one sentence.  "A discussion is resolved if and only if at least one participant is Satisfied or Informing and none of the participants are Working or Blocking, or if there are no active participants left."  If you mean the logic for what's unreplied -- yes, that's much more complex, but there should be no need for users to ever think about that explicitly.  It's in the docs just for completeness' sake.

**Comment by feldgendler** [comment]
OK, let's first look into the key difference between iterative consensus and what's implemented now.

In today's logic, discussion participants are seens as _taking sides_. Alice is in the Blocking party, Bob is in the Satisfied party, Charlie is undecided. If Alice changes her mind and leaves the Blocking party, the discussion will be resolved. It is therefore important for Bob to convince Alice to switch (possibly by changing the code).

In your current system, people have standing votes. They are assumed not to change their minds except by explicit action. The system has tricky rules for when to demand that users act, and what default action to suggest that they do. The rules are designed to help the participants proceed to more agreeable states. Discussing is more agreeable than Blocking, and Satisfied is more agreeable than Discussing. People are not expected to revert to less agreeable states.

Under my iterative consensus rules, anything anyone says is assumed to have the potential to change anyone else's mind in any direction. Any message might contain a world-changing revelation that will make everyone want to switch. Until every participant has seen the new message, we cannot disprove this hypothesis.

I can actually come up with an only-slightly-contrived example of how that can go.

Alice (disposition: Blocking): This code is wrong. It increases the `priority` variable, but it should in fact be decreased for that process.
Bob (disposition: Satisfied): This code is right. I think that process should run with a high priority, for such-and-such reasons.
Charlie (disposition: Discussing): Hey, did you guys know that the scheduler gives _more_ time to processes with _smaller_ `priority` values, and vice versa? I know, it's a little counter-intuitive.
Alice (changes disposition to Satisfied): Really? Thanks, didn't know that! Now I think this code is right and shouldn't be changed.
Bob (changes disposition to Blocking or Working): Really? Thanks, didn't know that! Now I think this code is wrong and should be changed.

In this scenario, the current logic would resolve the discussion right after Alice changed her mind, and Bob wouldn't have a chance to consider switching. There is a workaround: Charlie could predict that this would happen, and set his disposition to Blocking when posting his comment. But you've got to agree that we cannot expect that from Charlie.

Yes, conditional satisfaction would fix this scenario: Charlie's message would invalidate Bob's Satisfied disposition.

OK, now let's think how today's system can be changed in the least confusing way.

**Comment by feldgendler** [comment]
Conditional satisfaction sounds like a good experiment, but instead of it being a different kind of disposition, I think it should be a per-repository setting, at least for now.

If the option is enabled:

1. When a message is posted, all other participants who are Satisfied, revert to Pending (not to Blocking).
2. Pending is a new disposition that is impossible to set manually. The above is the only way you get to Pending.
3. The resolution condition changes to: (today's condition) AND no-one is Pending.
4. When you are in Pending, the suggested action button is Resolve, but writing a comment sets you to Discussing by default (or to Blocking? this part needs more thinking).

The importance of Pending is primarily social. It could be done, like you said, by reverting to Blocking, but Pending lets people see the difference between those who have a blocking opinion, and those who haven't expressed their opinion yet.

**Comment by feldgendler** [comment]
An alternative approach would be to make people's disposition _stale_ when a message is posted (unless they are Working). They would still be Blocking or Discussing or Satisfied or whatever, but stale at the same time. Posting a message and/or explicitly setting the disposition renews your disposition, making it non-stale.

The user experience for a participant with a stale opinion could perhaps be to renew their disposition. But I'd prefer that a user with a stale Blocking disposition had two buttons side-by-side: to keep blocking, and to resolve.

**Comment by pkaminski** [comment]
Thanks, lots of good points to think about there.  Here's my take:

First, I'm still not entirely convinced that "stale on new comment" is a good feature to have, even in principle.  I agree that it would address your sample scenario, but there's any number of other scenarios that it would actually break, the simplest being somebody saying "Good idea, thanks!" in response to a "This is OK as-is but this way might be better" comment, and thus invalidating the resolution.  While I think your experiment with aggressive auto-merging is interesting, in most environments social/cultural accommodation may be a good enough way to handle these scenarios (e.g., PR author noticing that new information may have invalidated a reviewer's position and holding off on merging even though the discussion is nominally resolved).

That said, if we did want to add this feature I feel strongly that 1) it would need to be a new disposition and 2) it would need to be opted-in on a per-user basis, both to avoid confusing "mainstream" users with modifying the semantics of a disposition they're already used to.  My concrete design proposal would be to add a new toggle to the disposition settings page (accessed via the small cog icon off any of your own disposition dropdowns) that says something like "Last word: allow use of an Agreed disposition that agrees to resolve a discussion, but becomes blocking if another comment is posted".  This new disposition would then replace Satisfied in the user's dropdown.  If it becomes stale, it would change icons and switch the blurb to something like "Previously agreed" or "Agreed (stale)".  [There's no technical reason why Satisfied and Agreed would have to be mutually exclusive, but I feel that the disposition menu is long enough already and having two very similar options in it at the same time would just be confusing.]

I don't think there's value in adding staleness tracking to other dispositions.
