### ISSUE TITLE
Cosmetic: labels are overlapping PR title

### ISSUE THREAD

**Issue by misha-tectonic** [Reviewable/Reviewable#686]
Chrome 76, Mac. Labels on the PR are overlapping the PR title (see attachment).

<img width="1198" alt="Screenshot 2019-09-13 at 11 34 15" src="https://user-images.githubusercontent.com/39945810/64874481-65c7e080-d64b-11e9-9084-3d6238c666c8.png">

**Comment by pkaminski** [comment]
@badz0 please take a look, thanks.

**Comment by pkaminski** [comment]
Should be fixed now.

**Comment by misha-tectonic** [comment]
It is, thanks.
