### ISSUE TITLE
Easy to resolve a discussion accidentally

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#688]
1. A reviewer wants to discuss a line of code without necessarily blocking the PR over it. The reviewer posts a comment with disposition: discussing.
2. Another reviewer looks at the discussion (disposition: uninvolved) and sees a Resolve button as the default action.

It's way to easy to click the default button. That sets the second reviewer's disposition to satisfied, and resolves the discussion because no-one is blocking it.

Expected result: the default button shown to the second reviewer is Acknowledge.

**Comment by pkaminski** [comment]
Agreed.  I think the "Resolve" line in https://docs.reviewable.io/#/discussions?id=ending-a-discussion should have the Role modified to say:

> Not Satisfied, either active participant or discussion has only one participant.

Do you think that would work?

**Comment by feldgendler** [comment]
Even simpler: Active participant, not Satisfied.

It doesn't change anything that the discussion has only one participant. That participant is the one to resolve it; random people passing by shouldn't have that as the default action.

**Comment by pkaminski** [comment]
No, your rule would prevent a PR author from one-click resolving a Discussing discussion, which is a core workflow for many teams.  In fact, I think I want to modify the rule further to allow one-click resolve for authors even if multiple reviewers chimed in:

> Not Satisfied, either active participant or PR author.

**Comment by feldgendler** [comment]
Sounds reasonable.

**Comment by pkaminski** [comment]
Change released.
