### ISSUE TITLE
Two reviewers get caught up in a blocking discussion

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#689]
When a reviewer posts a blocking comment, the rules work well. Reviewable believes that the ball is in the author's court and not in the reviewer's. The discussion is shown as requiring attention to the author but not to the reviewer, until the author resonds. So far, so good.

Now imagine there are two reviewers in the discussion.
R1 (disposition: blocking): This function needs to be marked as obsolete.
R2 (disposition: blocking): I'd even delete it completely.
R1 (disposition: blocking): Agreed.

Now Reviewable shows this to R2 as requiring attention again. If R2 replies, the discussion will require R1's attention. Until the author responds, Reviewable will force R1 and R2 to play ping-pong, while in fact they are both just waiting for the author to do something.

Expected result: after the scenario above, R2 sees an Acknowledge button. After acknowledging R1's last comment without writing a new one, the discussion should require only the author's attenton and no-one else's.

**Comment by pkaminski** [comment]
So you can already do this:  if you hover over the "new comment" ribbon, you'll see a "mark read" link that does essentially the same thing as Acknowledge would.  It's admittedly not very discoverable but it's for advanced users only, which seems a fair trade-off.

I can't think of a good way to decide when to show a Resolve vs Acknowledge in this scenario automatically, though.  Can you suggest how to modify the decision table in https://docs.reviewable.io/#/discussions?id=ending-a-discussion to have the desired effect?

**Comment by feldgendler** [comment]
That's right, you can't decide. That's because it's about equally likely that the reviewer will want to side with either opinion: that the code should be changed, and that it should not.

I think the idea of showing just one button is somewhat limiting. May I suggest that there can be situations where there would be two? This is one of such situations. Both Acknowledge and Accept (it's not Resolve because becoming Satisfied wouldn't resolve the discussion) are equally valid choices.

From the UX standpoint, Acknowledge vs. Accept is a weird choice that one can't process without reading the documentation. Renaming the buttons might be a good idea. Acknowledge might have the label Block in this case (because it means keep blocking).

**Comment by pkaminski** [comment]
I think this is a corner case that is sufficiently well served by the current "mark read" UI (which is also clearer than Acknowledge would be in this case).  I'm also not going to add a second reaction button -- the whole point is to have a single "I'm fine with all this" main flow there, and secondary controls for other scenarios.
