### ISSUE TITLE
Preview the email you're about to send

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#69]
One thing I like about the Gerrit workflow is that you can preview the email you're about to send out when you hit publish:

![screen shot 2015-03-11 at 2 31 15 pm](https://cloud.githubusercontent.com/assets/98301/6603920/56d9757e-c7fb-11e4-8920-55198fa27cb3.png)

This shows you everything you're about to send to the author/reviewer in one place. It's a great way to review everything / see that you're saying the same thing a dozen times / see that you're being too harsh, etc.

You can kind of get at this with Reviewable by bouncing on j/k, but you can't see everything in one place. It's definitely a feature I miss.

**Comment by pkaminski** [comment]
I see this as another variant of "zen mode": show just the drafts.  A feature is slowly coalescing here...

**Comment by pkaminski** [comment]
This is now implemented, see the new button on the status bar.
