### ISSUE TITLE
Review completion condition: Access to commit messages

### ISSUE THREAD

**Issue by mkow** [Reviewable/Reviewable#691]
It would be nice if custom review completion scripts could access the commit messages (possibly through an additional field in `revisions.commits`). This would allow to automatically block PRs with suspicious commits in them (e.g. starting with `fixup!`, containing `DO NOT MERGE` or being in format which doesn't match the one used in the project).

**Comment by pkaminski** [comment]
I currently only cache the commit title (first line of the commit message) in my database, would that be sufficient?

**Comment by mkow** [comment]
Should be enough for all my use cases, but probably in the long run it would be good to have access to the whole message.

**Comment by pkaminski** [comment]
Let's stick with the title for now since that's a <1 line change on my side.  Done!  :)

**Comment by mkow** [comment]
Thanks!
