### ISSUE TITLE
Request: consider files in __generated__ directories generated and hide by default.

### ISSUE THREAD

**Issue by seansfkelley** [Reviewable/Reviewable#693]
Per https://github.com/Reviewable/Reviewable/blob/d1ca3194b329cc2b87291041cf63812ee56b7207/docs/files.md#diff-customization, I'm asking to mark directories named exactly `__generated__` and all files in them as generated.

In my case, these directories are generated by Apollo's GraphQL Typescript code generator. I do not know if other tools use the same name.

I would prefer not to use .gitattributes, as I sometimes spot-check them on the command line and would prefer them not to be marked as binary. But if that's now the preferred way to do it, I can just do that and accept it.

**Comment by pkaminski** [comment]
Sure thing -- I can't see this causing any false positives.  Done and released.

**Comment by seansfkelley** [comment]
Looks great, thank you!
