### ISSUE TITLE
Search for draft only or not draft PRs

### ISSUE THREAD

**Issue by ttozser** [Reviewable/Reviewable#695]
I would like to search for draft only or not draft PRs.
In github I can do this with the `draft:true` or the `draft:false` conditions but I can't figure out how to do the same in the PR dashboard of reviewable.
In the [documentation ](https://docs.reviewable.io/#/dashboard?id=reviews-dashboard) only the usage of label search is mentioned.

Side note in github there is another way to search for drafts `is:draft`. However, this doesn't work together with other conditions like `is:open` so it is useless.

**Comment by pkaminski** [comment]
Good idea, shipped the new `draft` atom, along with `open`, `merged` and `closed` (non-overlapping).

**Comment by sschuberth** [comment]
For anyone wondering about the exact syntax, it's described [here](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-for-draft-pull-requests): Use `draft:true` or `draft:false`.
