### ISSUE TITLE
Weird bug when trying to reply to a comment

### ISSUE THREAD

**Issue by marcinslusarz** [Reviewable/Reviewable#696]
Sometimes I'm unable to add a comment to an existing discussion on the code.
Here's the flow: click on the "Reply" box, the message area shows up, but there's no cursor, clicking on it briefly shows a cursor, but in less than 0.5s the whole area disappears. Repeating never helps.

Here's a video showing this: https://youtu.be/-ZxFpdOZhWE

This doesn't always happen. I usually work around it by selecting part of the previous comment (it opens the same area with the selected text) and then clicking in the middle of the pasted text. Refreshing the whole page seems to help too.

I haven't found any way to reproduce it on demand.

**Comment by pkaminski** [comment]
Very interesting -- thanks so much for including the video!  This looks like some sort of race condition, but it's confusing that it's repeatable on the same discussion after it's happened once.  Can you please confirm which browser you're using?  It looks kinda-but-not-exactly like Chrome in the video...

**Comment by marcinslusarz** [comment]
Firefox 60.9.0esr

**Comment by pkaminski** [comment]
So far I haven't been able to reproduce the issue in FF 70 on Win10.  Can you estimate roughly how often you can trigger this?  Perhaps I just need to click more.  :)

When you use your select-and-reply workaround, does the reply also open without focus?  Have you ever observed this bug when creating a new discussion (i.e., clicking on a diff line), or is it exclusive to replies?

So far, I see two unexplained behaviors that may be related:  the lack of focus when a new comment opens, and clicking inside the discussion area deleting the empty comment.  The former could be a race condition or an edge case in how the browser handles focus, but the latter shouldn't be happening at all -- only clicks outside the discussion area ought to discard the empty draft, irrespective of focus.

I noticed that FF 60 ESR will be at end of life in a week or so.  Any chance you could try upgrading to 68 ESR and see if it happens to address the issue?  Or I guess maybe you're waiting for 68.2.0 to trigger the automatic upgrade.

Thanks.

**Comment by marcinslusarz** [comment]
> So far I haven't been able to reproduce the issue in FF 70 on Win10. Can you estimate roughly how often you can trigger this? Perhaps I just need to click more. :)

It happens every few days. I think it depends on what I did earlier, like replying to another comment, but I'm not sure about it. I'll keep an eye on that.

> 
> When you use your select-and-reply workaround, does the reply also open without focus? Have you ever observed this bug when creating a new discussion (i.e., clicking on a diff line), or is it exclusive to replies?

I don't remember, sorry. I'll report the next time it will happen.

> So far, I see two unexplained behaviors that may be related: the lack of focus when a new comment opens, and clicking inside the discussion area deleting the empty comment. The former could be a race condition or an edge case in how the browser handles focus, but the latter shouldn't be happening at all -- only clicks outside the discussion area ought to discard the empty draft, irrespective of focus.

I'm not a web developer, but my guess would be that when it happens the text box does not cover the whole area. That would explain the discarding of the empty draft. The first blink of the cursor could be explained by a glitch in the rendering engine when there's not enough space to fit even one line of text. I'll see if I can verify that with the DOM Inspector.

> I noticed that FF 60 ESR will be at end of life in a week or so. Any chance you could try upgrading to 68 ESR and see if it happens to address the issue? Or I guess maybe you're waiting for 68.2.0 to trigger the automatic upgrade.

Well, Debian 10 was released in July, so I don't foresee an update to 68 for quite some time and I would prefer to not update it myself.

**Comment by pkaminski** [comment]
OK, that sounds rare enough that it's going to be hard to reproduce without a somewhat clearer idea of the conditions under which the bug arises.  Please keep an eye out and let me know when you have any further observations.

FWIW, any click within the entire discussion (not just the draft or text area) should be keeping the draft open, so a too-small text area shouldn't be the culprit.  But I agree that the visual effects fit your scenario, and the text area's size is under programmatic control, so it's not impossible there's some weird edge condition that causes it to shrink and also breaks something else at the same time.

It looks like Debian has major releases on a roughly two year cycle -- I sure hope they'll update the browser before 2021, especially since FF 60 is EOL in a few days!

**Comment by marcinslusarz** [comment]
It happened again today. Unfortunately, I can't find anything suspicious in the DOM that is different from a normal page. The only weird thing is that there are 3 divs covering the space where the cursor should be (draft watermark position textarea, draft sizer relative ui textarea, draft position textarea). But the normal page also has that, so it's probably not a reason of the bug.

If you would like me to test something I'll keep the tab open for a day or two.

I got confirmation of this bug from another person. He's using Firefox 66.

**Comment by pkaminski** [comment]
Yeah, the layout on the draft is pretty hairy.  Unfortunately, I don't think you'll be able to get to any interesting data from your browser -- unless you happen to have the Vue debugger extension installed?

I'm going to add some optional logging when I have a bit of time and let you know how to turn it on.  I doubt it will pinpoint the issue but hopefully it will at least narrow things down.

**Comment by marcinslusarz** [comment]
> When you use your select-and-reply workaround, does the reply also open without focus? Have you ever observed this bug when creating a new discussion (i.e., clicking on a diff line), or is it exclusive to replies?

If I use the select-and-reply workaround, the reply text box opens without focus. I can click anywhere and the cursor shows up. However, if I remove the pasted text and click on the trashcan icon, the bug shows up again as nothing happened.

The bug is exclusive to replies.

I noticed one more thing - clicking **anywhere** closes the draft. This includes the whole lower bar ("WRITE", "PREVIEW", empty space, the cloud upload button, greyed out "post" button), my avatar and the "DRAFT" label. Clicking on the discussion state button brings up the menu with options, but also immediately discards the draft.

Clicking with the right mouse button has exactly the same effect - the draft is immediately discarded.

**Comment by marcinslusarz** [comment]
I think I found out how to reproduce it quickly.

It seems it reproduces only if: I reviewed some files previously, someone posted a new version, I set the range to "all revisions" and then use "my discussions" button.

Here's the whole video, starting with a refresh of the whole page: https://youtu.be/SHTSHhBCkcg

**Comment by pkaminski** [comment]
It's great that you found a way to reproduce the bug consistently!  Even following your instructions I haven't been able to do so yet, but at least you should be able to try some stuff out for me.

First off, I added a focus debugging mode to the app.  Could you please load a review with `?debug=focus` appended to the URL (delete any hash anchor), reproduce the issue, and copy the console to this issue?  That should at least give me an idea about what's going on inside and point in the direction to try next.  Thanks.

**Comment by marcinslusarz** [comment]
```
unreachable code after return statement
3940:1:198
camelCase syntax for events name (in $emit function) will be deprecated in a future release.
Please, make sure to use kebab-case syntax when emitting events from Vue.
index.js:231
/* page loaded, discussion is visible */
/* clicking on "Reply" */
draft -LrKhxCx7dfA1lfsgwlw mounted, focused draft: -LrKhxCx7dfA1lfsgwlw
raven.js:63:6
draft -LrKhxCx7dfA1lfsgwlw mounted, focused draft: null
raven.js:63:6
/* draft is visible, no focus */
/* clicking inside of the draft */
draft -LrKhxCx7dfA1lfsgwlw blurred, empty: true, active: false
raven.js:63:6
draft -LrKhxCx7dfA1lfsgwlw blurred, empty: true, active: true
raven.js:63:6
draft -LrKhxCx7dfA1lfsgwlw focused
/* draft disappeared */
````

**Comment by pkaminski** [comment]
Huh, so this points in a direction I hadn't even considered:  two draft components are getting created, presumably one on top of the other.  Then when you click on the top one the bottom one thinks you clicked "outside", deletes the draft, and this make the top one go away as well.

Could you please check if by any chance there are two discussion components as well (`div.discussion.item` ) for a single discussion?  If there are two, are they both within the same parent `div` or do they have distinct parents?

Thanks.

**Comment by marcinslusarz** [comment]
I see only one div with class="discussion item" covering the area of the discussion where draft without focus is created. Does this answer your question?

**Comment by pkaminski** [comment]
It did answer the question, but raised even more.  :)  I believe after much digging I found that there were indeed duplicated components that were disconnected from the DOM but still tied into some events.  I fixed this and I _think_ this ought to fix your bug as well.  Could you please try again and check?

**Comment by marcinslusarz** [comment]
I can't reproduce it anymore using my usual procedure, so it seems the bug is fixed! I can't be 100% sure because on Friday when the fix was not deployed yet, I couldn't reproduce it as frequently as before. My guess is the bug depends on the state of the review and something has happened which made it harder to reproduce. But today I couldn't reproduce it even once, so I hope it is fixed for good :).

Maybe I'm biased because I sort-of-understand what you fixed, but it seems Reviewable got a bit faster too!

BTW, Debian has just pushed an update of Firefox to version 68 to a stable branch. My tests were done on the old version (60) and I just verified that I can't reproduce this bug on 68 too.

Thank you.
