### ISSUE TITLE
Zero character renders inconsistently

### ISSUE THREAD

**Issue by ahlgreno** [Reviewable/Reviewable#699]
Depending on if it is in a code comment or in the code, there will or will not be a slash from the top right to bottom left. I prefer the zero with a slash but either way I think consistency is best.

![Screen Shot 2019-10-24 at 10 51 04 AM](https://user-images.githubusercontent.com/52678187/67497712-5ecdbe00-f64c-11e9-8e58-52a375941d04.png)

**Comment by pkaminski** [comment]
Hey Ryan, that's weird:  Reviewable uses Droid Sans and Droid Sans Mono for the comment and code fonts by default, and neither has a slashed zero glyph.  Could you check if something in your browser is overriding the default fonts somehow?  Thanks.

**Comment by ahlgreno** [comment]
Seems to be from reviewable css code. 
![Screen Shot 2019-10-24 at 3 03 12 PM (2)](https://user-images.githubusercontent.com/52678187/67517117-dcef8c00-f66f-11e9-93c5-75993970a049.png)

**Comment by pkaminski** [comment]
Got it -- the  `code` segments inside markdown weren't getting their monospace font overridden properly.  Fixed.  Thanks for reporting!
