### ISSUE TITLE
Screenshot scaling is too large

### ISSUE THREAD

**Issue by jxramos** [Reviewable/Reviewable#701]
Anytime I attach a small screen shot snippet it always renders in Reviewable comments as this ginormous image making the readability suffer much. I'm not sure what the best approach would be but its otherwise great to be able to include images into the discussion as I did just now taking a snippet of a README.md file that I wanted to lend feedback to the developer that their formatting may not have come across in their most recent edits.

To lend a of sense of scale I did the dragged-rectangle screen shot on my MacBook PRO which upon saving the image renders as a 776 × 1684 snippet. When I paste that image directly to the clipboard it occupies something like a screen and a half of vertical real estate.

**Comment by jxramos** [comment]
Come to think of it, I just made another screen shot attachment in the same review and it renders fine, I think the problem is with screenshots whose aspect ratios hold their heights greater than their widths.

**Comment by pkaminski** [comment]
Hmm, I don't think I do anything special with images after running the markdown through GitHub's converter.  If you publish the comment and look at it on GitHub what does the image look like?

**Comment by jxramos** [comment]
Aha, yah, it's huge in GitHub itself. Doing a quick inspect it looks like the max-width scaling is where the culprit lies.
```
<img src="https://XYZ.png" alt="✂-1" style="max-width:100%;"> 
```

**Comment by pkaminski** [comment]
Thanks for checking.  I could probably override this styling in Reviewable, but I think it would be better to get a fix pushed into GitHub itself -- otherwise the preview in Reviewable won't reflect what others might see on GitHub.

**Comment by jxramos** [comment]
Wow, I was going to file an issue against github on github, but I can't actually identify which repository is responsible for the github website proper ><
https://github.com/github

Would you happen to know or know the steps for giving feedback to the github team?

**Comment by pkaminski** [comment]
Heh, AFAIK they don't actually use their own issue system.  :/  I usually
just email support@github.com, or there's a form here:
https://support.github.com/contact.
