### ISSUE TITLE
Convenience link for jumping to changed file github page

### ISSUE THREAD

**Issue by jxramos** [Reviewable/Reviewable#702]
There's a workflow that I've come across that I think could be shortened somehow with a convenience link to the parent github file. When examining a PR in reviewable I'll click on the handy PR link at the top right corner...

![image](https://user-images.githubusercontent.com/13857038/68352611-d9babe00-00bb-11ea-893d-d8806773919a.png)

and from there navigate to the _Files changed_ tab

![image](https://user-images.githubusercontent.com/13857038/68352639-f35c0580-00bb-11ea-8a7f-c10c2448474e.png)

and from there navigate to the file of interest and click its _View File_ button.

![image](https://user-images.githubusercontent.com/13857038/68352717-2f8f6600-00bc-11ea-8e65-c2ef76f50819.png)

If somehow that direct link could be included in the reviewable tab for a file that would be excellent. The use case that motivates this is reviewing changes to a markdown where I want to see how that file renders during a review. It's also nice to just jump straight to source without all the surrounding commentary and have them side by side.

![image](https://user-images.githubusercontent.com/13857038/68352523-8d6f7e00-00bb-11ea-9bdf-16deae4ce14e.png)

**Comment by pkaminski** [comment]
Yeah, I can see how that would be useful sometimes, but not sure it passes the bar to have its own UI element.  There's a two-click workaround, though:  if you click on the "line" link in the top-right corner of any discussion (if needed, create a draft first by clicking on any line), you'll navigate to GitHub's view of the file at this commit.  (Unless you've overridden the line link template to go to your editor, then you're out of luck.)

**Comment by jxramos** [comment]
So the file matrix links are very useful, click one it takes you to the file and gives you the scale up animation of the file tab below. However when I click the link for the file path on that tab it just kicks off the animation once more. That could serve a purpose during pair programming where you want some means to point out the file to the other participant. One consideration maybe is to also kick off opening a new tab to the corresponding github link either in the background in addition to re-triggering the animation or just directly open in the foreground.

I never picked up on that line number as a link, that's a fantastic tip I'll put to use for sure. So we have a one click route to that file view if there's an ongoing discussion. Two clicks if I start a discussion. Not bad, I'll spread the word to the team, they'll like it.

**Comment by jxramos** [comment]
Actually, the link link seems to be locked at the revision the comment was opened at. The file tab link may either link to the uppermost revision the file matrix view is slid out to, or just always link to the latest revision of the file regardless of the file matrix view. I'm not sure which one makes sense. For now the two click workaround and being sure to slide to the latest version of the file will be the solution.

**Comment by pkaminski** [comment]
You're right, but if you'd like you can customize the line link template to always take you to the latest revision.  Just set it to `https://github.com/{{owner}}/{{repo}}/blob/{{sha}}/{{path}}#L{{line}}` (instead of the default `https://github.com/{{owner}}/{{repo}}/blob/{{viewSha}}/{{path}}#L{{viewLine}}`), per https://docs.reviewable.io/#/accountsettings?id=line-link-template.
