### ISSUE TITLE
Quoting a highlighted block adds additional, non-highlighted line

### ISSUE THREAD

**Issue by yonch** [Reviewable/Reviewable#703]
To reproduce: highlight a few lines (say lines 2-4 of a file), including all characters, and stopping just before the first character of line 5. Click on the block to add the comment. Lines 2-5 of the file show up.

Desired behavior: lines 2-4 will show up (no character of line 5 was selected)

**Comment by pkaminski** [comment]
Thanks, this should be fixed now.  (And may I just say that it's _tons_ of fun to deal with browsers' radically different implementations of the selection spec.)
