### ISSUE TITLE
No horizontal scrolling on per-file revision bar

### ISSUE THREAD

**Issue by misha-tectonic** [Reviewable/Reviewable#706]
In review UI one can scroll horizontally the list of files/revisions, but not the list of revisions for individual files.

It makes it harder to do reviews with many revisions.

See the https://photos.app.goo.gl/5XJYoHvWcAyGPPbL6 for the illustration.

**Comment by pkaminski** [comment]
Yeah, I can see how that's a pain.  But given that 1) reviews with sufficient revisions to overflow a widescreen monitor should be pretty rare, 2) there's a workaround (going back to the file matrix), and 3) I can't see how to shoehorn scrolling into the file headers, I think this is a "won't fix".

**Comment by misha-tectonic** [comment]
Is there a way to jump from the diff to the corresponding line in the file matrix?

Large PRs tend to touch many files, so finding the file one is currently reviewing in a matrix is also a pain.

**Comment by pkaminski** [comment]
So actually, I remembered #514 and realized that you're scrolling the file matrix without a scroll bar.  This gave me the idea of making the file header behave the same way -- but this time with the scroll bar intentionally hidden.  Should be OK now in Chrome and Firefox, please give it a try!

**Comment by misha-tectonic** [comment]
Lovely, it works exactly as I expected it to.

Thank you.

**Comment by misha-tectonic** [comment]
However the scrollable bar is now z-sorted above the review header. See the attached picture.
<img width="1625" alt="Screenshot 2019-12-03 at 10 41 50" src="https://user-images.githubusercontent.com/39945810/70039099-9fa8e300-15b9-11ea-910f-d9b58eb8bfe7.png">

**Comment by pkaminski** [comment]
This looks normal to me.  The file header will rise over the toolbar while scrolling, then "bed in" and get properly truncated once it has scrolled high enough.
