### ISSUE TITLE
Support emojis in GitHub labels

### ISSUE THREAD

**Issue by ibrahima** [Reviewable/Reviewable#707]
Hi! Random feature request: we've started to use emojis in our PR labels to make things stand out a little more visually. But unfortunately, on Reviewable we just see the raw text of the label without emojis rendered.

For example, this is the label on Reviewable

![image](https://user-images.githubusercontent.com/47774/70085609-6f674180-15c5-11ea-9fa6-08c530820f7e.png)

vs on GitHub

![image](https://user-images.githubusercontent.com/47774/70085620-768e4f80-15c5-11ea-8e47-59dd9fced585.png)

It would be great if Reviewable could render emojis in labels in the future.

Thanks!

**Comment by pkaminski** [comment]
It took us a while, but this is now live.  :)
