### ISSUE TITLE
The page crashes

### ISSUE THREAD

**Issue by DamienCassou** [Reviewable/Reviewable#708]
Since this morning (maybe because I updated to Firefox 71), Reviewable keeps crashing for me:

![2019-12-05-121925](https://user-images.githubusercontent.com/217543/70230887-935b8c00-1759-11ea-97ad-fc7c72dad0a2.png)

It seems it's not related to a particular PR because it happened on all PRs I tried.

Reviewable seems to work fine on Chromium.

**Comment by pkaminski** [comment]
Hi Damien,

Thanks for reporting this.  I did push a minor new release last night but I
only see it happening to you and one other person in your office, and can't
reproduce it locally in Firefox 71.0b12 or 72.0b2, so there's a fair chance
it's something specific to your environment.  Could you please try with
extensions disabled?

If that doesn't help, the error message points to an issue with Indexed DB,
which is only used by the Firebase library.  Their release notes don't show
any relevant changes in the recent past.  As the DB is only used to store
session information, you can try deleting the firebaseLocalStorageDb
Indexed DB for https://reviewable.io and see if things improve when it gets
automatically recreated on the next page load.  (You can wipe local and
session storage at the same time for completeness, as some parts of the
session get stored there as well.)

Let me know how it goes.

Thanks,

    -- P.

**Comment by DamienCassou** [comment]
I tried with a fresh Firefox profile and can still reproduce the problem. I'm on Fedora 31. How to reproduce:

1. in Fedora 31, type `firefox -P`
2. create a profile and start it
3. login on github.com
4. go to a PR
5. click on the "Reviewable" button
6. you get the error of the screenshot above

**Comment by pkaminski** [comment]
I'm not sure what's going on then.  However, it may not be worth investigating since Firefox 71 has another regression that makes it less than ideal for Reviewable: see https://changelog.reviewable.io/regression-in-firefox-71-124418.  Are you able to check if this issue repros in Firefox 72 on Fedora as well by any chance?

**Comment by DamienCassou** [comment]
Piotr Kaminski <notifications@github.com> writes:
> I'm not sure what's going on then.  However, it may not be worth
> investigating since Firefox 71 has another regression that makes it
> less than ideal for Reviewable: see
> https://changelog.reviewable.io/regression-in-firefox-71-124418.  Are
> you able to check if this issue repros in Firefox 72 on Fedora as well
> by any chance?

I've just downloaded Firefox 71 from getfirefox.com and it worked. The
only thing I can think of now is that Fedora's build of Firefox is
buggy.

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by pkaminski** [comment]
Sounds like a minor version update fixed some FF regression.  Thanks for figuring this out!
