### ISSUE TITLE
TypeError seen when viewing diff

### ISSUE THREAD

**Issue by aedelstein** [Reviewable/Reviewable#709]
I have no details about how to reproduce this but when viewing a review (which I've viewed in the past with no problem), every diff is showing up with the error `TypeError: Argument 1 of FileReaderSync.readAsText is not an object`.  Comments still show up on the file but no text is seen.

![image](https://user-images.githubusercontent.com/4365598/70312072-dc0a5800-17e0-11ea-910a-3a5cc2df75ef.png)

Clicking "Try Again" did not help and this happens whether or not there are unreviewed changes in the file.

**Comment by aedelstein** [comment]
Ah, never mind, I see it's mentioned in https://changelog.reviewable.io/ .

**Comment by pkaminski** [comment]
Yup, it should also be fixed in Firefox 72.

**Comment by jwnimmer-tri** [comment]
@pkaminski The broken FF is now the default in Ubuntu 18.04.  Is there any way to automate or set a user preference or something so that `?debug=workers` is always in effect for my sessions?  Editing every review URL after opening it is getting old fast.

**Comment by pkaminski** [comment]
Gah, Firefox made such a mess of this.  :(  I added some user-agent sniffing to Reviewable's bootstrap sequence to force shared workers off for FF71.  Please let me know if that helped.

**Comment by jwnimmer-tri** [comment]
Seems to work a-ok now.  Thank you!
