### ISSUE TITLE
Missing comment on Reviewable

### ISSUE THREAD

**Issue by smondet** [Reviewable/Reviewable#71]
Here:
https://github.com/hammerlab/ketrew/pull/128
@rleonid's first comment "Ok" seems to come from Reviewable.
But I can't see it in https://reviewable.io/reviews/hammerlab/ketrew/128

**Comment by smondet** [comment]
Ok, sorry, turns out the "Ok" was added afterwards through github's edit comment thing.

**Comment by pkaminski** [comment]
Thanks for following up!  Reviewable will sync edits made on comments that originated on GitHub, but won't do so for its "own" comments since they're not supposed to be editable.
