### ISSUE TITLE
Renamed GitHub user does not update name on /repositories page

### ISSUE THREAD

**Issue by misha-ridge** [Reviewable/Reviewable#710]
I have renamed my GitHub account several days ago.

However https://reviewable.io/repositories still shows the old name (see the picture).
<img width="1101" alt="Screenshot 2019-12-09 at 12 53 47" src="https://user-images.githubusercontent.com/39945810/70433885-21e64b00-1a83-11ea-8e88-46d3df6bcbc9.png">

**Comment by pkaminski** [comment]
Please sign out and back in again to force a refresh of cached account data.  (Reviewable will refresh of its own accord every so often, but as it caches hundreds of thousands of users and information changes pretty rarely, it's not very aggressive about it.)
