### ISSUE TITLE
Italic and bold format bug

### ISSUE THREAD

**Issue by gaborvolczer** [Reviewable/Reviewable#716]
Hi,

The following code:

```
To format a block of text bold or italic, you can use underscore (_) or asterisk
(*) characters around the block:
* `_Italic_` or `*Italic*`: _Italic_
* `__Bold__` or `**Bold**`: __Bold__
* `*Is __Combined__*`: *Is __Combined__*
```

looks like this on github:

![image](https://user-images.githubusercontent.com/11292006/73067609-744fbf80-3ea9-11ea-83b6-9e55651ae0e1.png)

but looks like this on reviewable: 

![image](https://user-images.githubusercontent.com/11292006/73067725-b8db5b00-3ea9-11ea-9c6c-ee634150ea40.png)

If there is a special view or settings where I get the same look please let me know. If it's a bug please fix it if possible!

Thanks in advance!

Gábor

**Comment by pkaminski** [comment]
This is an issue in highlight.js, which Reviewable uses for rendering source code.  I poked around a bit but couldn't see an obvious way to fix it, so I opened an [issue](https://github.com/highlightjs/highlight.js/issues/2366) over there and hopefully somebody will help out.

**Comment by pkaminski** [comment]
The latest version of highlight.js fixed this I believe.
