### ISSUE TITLE
Option: do not consider base commit changes as worth reviewing

### ISSUE THREAD

**Issue by misha-ridge** [Reviewable/Reviewable#717]
Our project has a workflow with PRs being merged only if they are up-to-date with master, have been reviewed and pass tests.

However it results in the following situation:

- A review is performed and CI is finished successfully.
- A bot kicks in that brings PR up-to-date with `master`. This causes some files to be marked in Reviewable as unreviewed due to "base commit changes". CI still passes.
- The PR now waits for additional manual review. However in practice this review is perfunctory, as we rely on CI to ensure nothing breaks.

Would it be possible to optionally do not consider "base commit changes"—and only them—as significant?

**Comment by pkaminski** [comment]
This is unfortunately impossible, as Reviewable only computes diffs on the client and a "this revision is superfluous" decision would need to be taken on the server.  This is an early architectural decision that it is far too late to go back on.

BTW, I think #622 is adjacent to your request, but that one is feasible since the comparison the server needs to make is at the SHA level rather than an actual (three-way) diff.

**Comment by feldgendler** [comment]
Alright, can we have an API or some other way to mark revisions as reviewed by a robot?

**Comment by pkaminski** [comment]
The "API" is the review completion condition, where you can mark any given file-revision as reviewed (or not).  Do you have enough information in there to make the marks you want?  If not, could the bot set some label to indicate that the latest commits are no-ops perhaps, that you could then key off in the condition?

**Comment by feldgendler** [comment]
Your suggestion to make automatic update commits machine-recognizable (e.g. by prefixing the commit message) is interesting. It is less precise than actually replicating your four-way diff algorithm, but immensely simpler to implement. The merge commits the robot makes should never have any other changes than the automatic merge. It won't detect any merges from master done manually, but we rarely do that.

**Comment by feldgendler** [comment]
It turns out that the commit message is generated by GH and is not under our control. We could decide by the committer instead.

May I ask you to add the commit author information to the description of every commit in the input to the custom function? If it's difficult to map the raw committer to a GH user, we can settle for the raw committer string. It would be enough for our purposes.

**Comment by pkaminski** [comment]
Yeah, fair enough.  I added author and committer info to the condition input structure.  It will only be present when GitHub has successfully mapped these users to GitHub accounts (which should always be the case for you, I believe), and will only be present for revisions captured going forward (no backfill).

**Comment by misha-ridge** [comment]
Thanks, it solves our problem!

**Comment by pkaminski** [comment]
I'm going to reopen this issue as it's a perennial request and most people can't apply a workaround like above.  I'm thinking about approaching it in the same way as file renaming:  the rename map is computed on the client, saved to the DB, and marked as trusted or not depending on whether the user has write access to the repo.  Trusted maps overwrite untrusted ones.  When a map is updated, the completion condition is triggered on the server.

My idea is to compute "base change maps" on the client just like file rename maps and add a `baseChangeOnly` flag to file revision objects.  We'd also need to figure out how this would work in the every-commit review style and likely surface the inferred `priorRevision` links.  It would then be up to the completion condition to use these flags as desired (the default behavior wouldn't change), and of course we'd provide a sample condition.  Not 100% sure it would work yet but if feels feasible.

**Comment by pkaminski** [comment]
Internal discussion [here](https://app.shortwave.com/t/msg-1c3b3f71-e12f-4d76-9610-515e04e1741a).

**Comment by pkaminski** [comment]
Shipped!
