### ISSUE TITLE
Collapse all discussions

### ISSUE THREAD

**Issue by marcinslusarz** [Reviewable/Reviewable#718]
Unfinished discussions (resolved, but not acknowledged by the author, or just lengthy in-progress ones) are cluttering the view so much, that I can't really start reviewing.

I'd like to temporarily collapse all discussions until I get the big picture of the change and then expand them back.

**Comment by pkaminski** [comment]
Yeah, I feel your pain.  This will require some redesign but we'll get there.  I'll close this issue in favor of #94, which is very similar (collapse vs hide) and any solution would address both.
