### ISSUE TITLE
Show/set PR assignee

### ISSUE THREAD

**Issue by mmikulicic** [Reviewable/Reviewable#72]
We recently introduced a workflow where the assignee in the PR is set back and forth between the reviewer and the reviewee, with the goal of fitting the pending reviews in our custom git issue dashboard frontend.

It would be of great help if reviewable would be able to show (and possibly even set) the current PR assignee.

**Comment by pkaminski** [comment]
Interesting workflow.  :pensive:  Let me think about how I could fit this in nicely.  Do you only want this on the review page, or on the My Reviews dashboard too?

Out of curiosity, what caused you to go with a custom issue dashboard?  Are there features that would make sense to integrate into Reviewable's dashboard?

**Comment by mmikulicic** [comment]
For our particular needs at the moment, having it in review page would be enough, although I can see it could make sense to have a glance who's reviewing (or responsible) of which review.

We created the dashboard for other reasons (e.g. to have an overview of the team wide distribution of tasks), but showing also the review load kinda fits in the place as well. We are still experimenting with the workflow; for example now we are setting the assignee back to the reviewee only if the reviewer LGTMs conditionally to some cleanup and he trusts the reviewee to perform due diligence; basically the assignee is the one responsible for merging the branch.

It could make sense for reviewable as well to have an overview of the review backlog for each team member.

**Comment by pkaminski** [comment]
OK, thanks.  I think maybe I'll just put the assignee next to the author avatar in the review title.  Something like:  `(author) -> (assignee) PR summary...`.  As far as setting goes, I'm considering supporting some special directives in the markdown like `+label:foo` or `+assign:bar`, which would be executed when the comment is published.  That part might come later, though.

> It could make sense for reviewable as well to have an overview of the review backlog for each team member.

That's what the My Reviews dashboard is supposed to be: all the reviews a user is involved in, with red counters signifying that an action is required.

**Comment by mmikulicic** [comment]
On 1 Apr 2015 21:06, "Piotr Kaminski" <notifications@github.com> wrote:
>
> OK, thanks. I think maybe I'll just put the assignee next to the author
avatar in the review title. Something like: (author) -> (assignee) PR
summary.... As far as setting goes, I'm considering supporting some special
directives in the markdown like +label:foo or +assign:bar, which would be
executed when the comment is published. That part might come later, though.

Sounds good. Thanks

>>
>> It could make sense for reviewable as well to have an overview of the
review backlog for each team member.
>
> That's what the My Reviews dashboard is supposed to be: all the reviews a
user is involved in, with red counters signifying that an action is
required.

But AFAIK it only shows your stuff not other people's stuff (grouped by
user). I mean, I'd like to know if a team mate has a long review queue.

**Comment by pkaminski** [comment]
> But AFAIK it only shows your stuff not other people's stuff (grouped by user). I mean, I'd like to know if a team mate has a long review queue.

Ah, I see.  Yes, that would be a nice feature to have, probably integrated with @-autocompletion (once I figure out how to do that).  I'll add it to my wishlist.

**Comment by pkaminski** [comment]
Now showing assignee in both review and dashboard.

**Comment by mmikulicic** [comment]
Thanks!

I even like the icon but, funny thing, a team mate noted: "Looks like a gun at a temple"

**Comment by pkaminski** [comment]
Yeah, I thought it looked a bit like "it's YOUR problem now!", so it seemed appropriate.  As for guns, have you seen the convention to write :shipit: :gun: to cancel an LGTM?  :smile:

**Comment by mmikulicic** [comment]
No, lol!

**Comment by pkaminski** [comment]
Setting the assignee is now supported via `+@` in a comment.

**Comment by mmikulicic** [comment]
Thanks!
