### ISSUE TITLE
Copy to clipboard button for file path

### ISSUE THREAD

**Issue by fpeter8** [Reviewable/Reviewable#720]
We already have a copy to clipboard button for the base branch of the PR. Can I get the same button for the files in the PR? This is a feature I'd rarely use, but when I need to copy the path I cannot because the file names are all links.
Ideally this button would be present at the top of the diff for that file, but if you decide to add it to the file matrix / dropdown I can live with that as well.

**Comment by pkaminski** [comment]
I think a copy button in the file header would be too disruptive in this UI, but note that you can double-click on the file path to select it, ready for copying (per https://github.com/Reviewable/Reviewable/issues/648).  Is that sufficient?

**Comment by fpeter8** [comment]
Yes, that's it, thanks!
