### ISSUE TITLE
Corner case deleting branch from third party repo

### ISSUE THREAD

**Issue by dhalperi** [Reviewable/Reviewable#725]
PR: https://github.com/batfish/batfish/pull/5646 (open source)

* I have Reviewable configured in `SQUASH & DELETE` mode.
* Batfish is configured in `Automatically delete head branches `
* I don't know if the fork is configured this way.
* I don't know if the "let administrators edit this PR" button in github PR UI was checked

When I merged the PR in Reviewable, I got the following error:

<img width="1278" alt="Screen Shot 2020-03-23 at 1 10 06 PM" src="https://user-images.githubusercontent.com/526415/77359054-3e438600-6d08-11ea-848b-4471a3c5c468.png">

My guess is that the message is completely correct and attributable to a race condition/corner case/permissions error. However, you may want to add special handling for this case.

**Comment by dhbradshaw** [comment]
Ok, Reviewable now takes auto-deletion in the repository of the deleted branch into account and will avoid trying to redo the deletion.  It will also remove Retain as an option to show that the branch will be deleted by Github.
