### ISSUE TITLE
Reviewable could not publish

### ISSUE THREAD

**Issue by tequ1lAneio** [Reviewable/Reviewable#726]
title: Request queued but server did not respond.
I can view comments also write some, but I can't publish any way.

**Comment by kod4n** [comment]
I'm also seeing this behavior for repositories I have connected to Reviewable

**Comment by pkaminski** [comment]
Apologies -- Firebase RTDB had an outage this morning.  :(  https://status.firebase.google.com/incident/Realtime%20Database/20004
