### ISSUE TITLE
Support for marking parts of file as reviewed

### ISSUE THREAD

**Issue by lakshayg** [Reviewable/Reviewable#728]
Sometimes there are multiple changes in a file each of which might need to be reviewed by a different reviewer. It would be great to have the ability to mark small chunks of a file as reviewed as opposed to marking the entire file.

Conceptually, I think of this as something similar to `git add --patch` where one can stage a part of the file.

**Comment by pkaminski** [comment]
This was discussed previously in #414, so closing this as duplicate.  But I'd be happy to continue the discussion there, especially if you have ideas for how to address some of the implementation problems I raised!
