### ISSUE TITLE
Crash with Grammarly web extension

### ISSUE THREAD

**Issue by tsemple** [Reviewable/Reviewable#729]
I get a crash when I use the Grammarly web extension. When it highlights an error and I mouse over it, it crashes every time.
![image](https://user-images.githubusercontent.com/2207219/80147683-b94ac700-8568-11ea-880a-c164b5103810.png)

**Comment by pkaminski** [comment]
Aha, so that's where those exceptions are coming from!  However, I put those on the ignore list in the latest release a couple days ago -- could you please double-check that you still get the crash if you reload the page?  If so, the ignore list isn't working like I expect it to.

**Comment by tsemple** [comment]
I was able to repro this today. But I think I'm using an on-premises
reviewable - at least I have to be VPN'd in to access it. It says
v2200.3821.

**Comment by pkaminski** [comment]
Yeah, you're on the Enterprise stream and running a version from October 2019 to boot.  The next release will include this fix, but it just missed the cutoff this month so it won't be until sometime in May.  Or, if it's really irritating, please have your Reviewable admin get in touch and I can cut a private release for them to deploy.  Thanks.
