### ISSUE TITLE
Collapse generated files

### ISSUE THREAD

**Issue by mmikulicic** [Reviewable/Reviewable#73]
In our repos, we have some generated files. It ranges from classic stuff like compiled stubs (e.g. for proto) + Go conventions (put generated code in the repo), to some more exotic stuff like bundling amalgamated (combined) C sources (so that people can build on platforms when the amalgamation script cannot run.)

I know you strive to limit the knobs, but since this seems a common case, would it be possible to give some hints to reviewable that some file patterns should if not be hidden, then at least collapsed by default ?

**Comment by pkaminski** [comment]
Is it possible to recognize these files independent of context?  That is, would it be possible to have a list of patterns to look for globally with minimal false positives?  If so, I'd be game to build such recognition into Reviewable (updating it as users discover new patterns) and collapse them by default with no knobs at all.

**Comment by mmikulicic** [comment]
it would be possible to do for the Go protobuf artifacts, and in general output of popular tools, but no way to cover our specific "amalgamation" use case, which is far more annoying to us, because the diff contains an exact copy (but in bulk) of what is present in the other files.

I wouldn't  mind even a simple way of collapsing the file a partial workaround for our biggest pain.

**Comment by pkaminski** [comment]
Could you provide me some patterns for protobufs and such so I can give it a try?  As for the amalgamated files, are you able to inject some special and unique marker string into them?  I could add it to the patterns, and document it so that others can just use the same marker in their build if they want to take advantage of the feature.  Maybe something like `**GENERATED SOURCE NOT FOR REVIEW**`.

**Comment by mmikulicic** [comment]
`*.pb.go`

`Code generated by protoc-gen-go.`

Ah yes, we can easily add a comment in our generated code, like `Code generated by  scripts/amalgam`

**Comment by pkaminski** [comment]
Cool, it would probably be better if it was a bit more unique since I want to avoid false positives as much as possible.  Also, make sure that the string isn't present verbatim in your build script, or it'll get collapsed too.  :)

**Comment by mmikulicic** [comment]
In order to reduce false positive you could add this checks:

1. String is in a comment (Common line comment markers: `//`, `#`, `%`, `;`. C block comment: `/*`, others?). We do use `/*` block comments
2. Contains also the string "DO NOT EDIT"
3. This text is in the first 3 comment blocks (in order to possibly skip a large copyright block), possibly prepended even to generated files.

**Comment by pkaminski** [comment]
This is now implemented.  I added the patterns for protobufs, and the custom marker string is `GENERATED FILE DO NOT EDIT`.  It must appear on a line essentially by itself (+/- 4 characters at either end to allow for comment syntax), as document in the new FAQ entry.
