### ISSUE TITLE
Reviewable frequently crashing (see attached image)

### ISSUE THREAD

**Issue by asheshjain399** [Reviewable/Reviewable#730]
![Screen Shot 2020-04-27 at 9 10 46 PM](https://user-images.githubusercontent.com/2342194/80446396-95bab000-88cb-11ea-8831-97c5c3e929c7.png)

**Comment by pkaminski** [comment]
Are you on reviewable.io or an enterprise installation?

**Comment by asheshjain399** [comment]
enterprise installation

**Comment by pkaminski** [comment]
Please see #729.  It looks like this issue is having enough of an impact, though, that I'll have to cut an early release with the fix.  You can let your Reviewable admin know to expect that tomorrow if all goes well.  Thanks!
