### ISSUE TITLE
Ability to lgtm / generally comment from the bottom of the page

### ISSUE THREAD

**Issue by kushal** [Reviewable/Reviewable#731]
I've developed a really bad habit of :lgtm:ing before reading because I hate having to scroll back up once I've looked at all the diffs. Could we get the comment box at the bottom of the diffs somehow so I can review in a more linear fashion?

**Comment by cgiroux86** [comment]
Track internal progress/discussion [here](https://app.shortwave.com/s/channel%3Achan-8a8b66c4-2d5c-488c-afd5-8839c495c2e3).
