### ISSUE TITLE
Quote expansion issue

### ISSUE THREAD

**Issue by dhalperi** [Reviewable/Reviewable#737]
I'm having a crazy bug where comments get smaller when a blockquote is expanded. When the quote is collapsed, the box is big enough for it to be expanded; when the quote is expanded, the box is small enough for it to be collapsed.

I took screenshots of the UI and the DOM:

<img width="733" alt="Screen Shot 2020-05-27 at 9 47 57 PM" src="https://user-images.githubusercontent.com/526415/83289248-a6479a00-a199-11ea-8b62-57071a636982.png">
<img width="697" alt="Screen Shot 2020-05-27 at 9 48 02 PM" src="https://user-images.githubusercontent.com/526415/83289257-a8115d80-a199-11ea-9067-3089bdc37248.png">
<img width="804" alt="Screen Shot 2020-05-27 at 9 49 14 PM" src="https://user-images.githubusercontent.com/526415/83289262-aa73b780-a199-11ea-9159-93551400f745.png">
<img width="759" alt="Screen Shot 2020-05-27 at 9 49 21 PM" src="https://user-images.githubusercontent.com/526415/83289265-aba4e480-a199-11ea-9d97-198d964c3c58.png">

Random notes: latest OS X, Chrome up to date, I have animations off. Survived a refresh.

**Comment by dhalperi** [comment]
Noting: in the UI, the full comment is visible only in the "collapsed" quote; when expanded, it's not visible. (ends with the `(^^^` bit).

In the dom, there are two changes visible: `style="height: foopx"` and at the end, `<details>` vs `<details open>`.

**Comment by dhalperi** [comment]
Answering qs from gitter:
>Is the bug reproducible on different messages/reviews?

Not sure. First time I've ever seen it and the PR has been merged. 

> Does it occur only when drafting a reply?

I believe that it happened before I was drafting the reply; because investigating this was why I got into draft mode in the first place.

**Comment by dhalperi** [comment]
Re-loading the PR and getting back into edit mode, the effect is still happening. Blockquote collapsed (note we can see my full comment, the author's full comment, and a lot of extra padding before the end of the dialog):

<img width="700" alt="Screen Shot 2020-05-29 at 10 55 18 AM" src="https://user-images.githubusercontent.com/526415/83290086-ece9c400-a19a-11ea-9dd3-8067c5ce93ee.png">

Blockquote expanded (my comment is truncated, author's is missing):

<img width="704" alt="Screen Shot 2020-05-29 at 10 55 27 AM" src="https://user-images.githubusercontent.com/526415/83290142-04c14800-a19b-11ea-9851-85f6924313df.png">

**Comment by dhalperi** [comment]
Interestingly, on first load (refresh) the quote is collapsed and the dialog looks correct: 
<img width="827" alt="Screen Shot 2020-05-29 at 10 58 15 AM" src="https://user-images.githubusercontent.com/526415/83290332-5964c300-a19b-11ea-981f-78a51e76732a.png">

But upon expanding it, the dialog does not resize up, and then upon collapsing it the dialog *does* resize up.

**Comment by pkaminski** [comment]
@badz0 could you take a look please?

**Comment by pkaminski** [comment]
Should be fixed!
