### ISSUE TITLE
Comment on multiple lines and words

### ISSUE THREAD

**Issue by leoluk** [Reviewable/Reviewable#738]
I haven't been able to figure out how to commit on multiple lines or even words.

Is this possible, and if not, is this on the roadmap?

**Comment by pkaminski** [comment]
At this point, a comment is always attached to a single line.  This assumption is baked pretty deeply into Reviewable and is not likely to change (see #83).  Instead, I'd like to see a feature that lets you reference arbitrary lines in your comment (per #147).
