### ISSUE TITLE
Blockquote adding too many spaces in offset 2-column mode?

### ISSUE THREAD

**Issue by dhalperi** [Reviewable/Reviewable#740]
I think this is new behavior. Using 2-column mode for diff, when I selected a block of text, the quoted code included the "fake" newlines added to align with left side.

<img width="804" alt="Screen Shot 2020-06-03 at 6 32 11 PM" src="https://user-images.githubusercontent.com/526415/83705044-ac3de080-a5c8-11ea-9e81-7ac37d190175.png">

**Comment by pkaminski** [comment]
Thanks, should be fixed now.  Though I don't entirely understand how it was working before -- likely some recent small change in browser behavior.
