### ISSUE TITLE
docs: Weird scaling on images?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [Reviewable/Reviewable#742]
When viewing the docs like this one: https://docs.reviewable.io/#/reviews?id=review-toolbar
I see images scaled like this:
> ![image](https://user-images.githubusercontent.com/26719449/84422923-ba54b800-abeb-11ea-85c3-5810802b9192.png)

It's kinda hard to read :(

Platform: Ubuntu 18.04
Browser: Firefox 77.0.1

Relates #45 in terms of onboarding

**Comment by dhbradshaw** [comment]
Good catch ... thanks!

**Comment by dhbradshaw** [comment]
Should be fixed, or at least better.

**Comment by EricCousineau-TRI** [comment]
Thanks!
It's, uh, a tad bit better in that the aspect ratio is maintained, but uh, the images are then too big and/or low res :(

Is it possible to just have all images stick to their true size (rather than resize relative to window width)?

Full window (still looks kinda bad):
> ![image](https://user-images.githubusercontent.com/26719449/84549024-fdd72100-acd4-11ea-819f-47739727e2ef.png)

Half-window (tons better):
> ![image](https://user-images.githubusercontent.com/26719449/84549080-22cb9400-acd5-11ea-9680-e88421e08379.png)

(also, this image in particular is low-res, so it looks really bad when scaled up?)

**Comment by dhbradshaw** [comment]
Ok, I couldn't get that image to work at pretty much any size because, as you mentioned, it's pretty low-res.  So I replaced it.  I also have it defaulting to avoiding scaling when possible.  What do you think?  Less bad?

**Comment by EricCousineau-TRI** [comment]
Yup, better! Thanks!

It still seems like some of the images ultimately come from different resolutions (e.g. high DPI from a Mac, and then another from a lower-res Ubuntu machine?), but I tried playing with different CSS stuff in Firefox but could see any combo of `max-width`, `width`, `max-height`, and `object-fit` that looked any better.

Ideally, all images would be from the same res, so then `width: auto; max-height: 100%` would look more consistent, but I understand that may be a bit extra.

Thanks!
