### ISSUE TITLE
Docs for `git fetch origin refs/reviewable/pr99999/r1`?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [Reviewable/Reviewable#752]
I've had people point this out to me and it works, but I haven't been able to find the "primary source" for this.

Is this documented somewhere, like Reviewable's user guide?
It's an *awesome* feature, to say the least.

Example:
For PR: https://github.com/RobotLocomotion/drake/pull/13557
```sh
( set -eux;
cd $(mktemp -d)
# Ignore these flags; just avoids downloading whole repo.
# See: https://stackoverflow.com/a/60952814/7829525
quick_flags="--filter=blob:none --depth 1"
git clone --bare ${quick_flags} https://github.com/RobotLocomotion/drake  # A kinda large repo
cd drake.git

git fetch ${quick_flags} origin refs/reviewable/pr13557/r1
git log -n 1 --oneline FETCH_HEAD

git fetch ${quick_flags} origin refs/reviewable/pr13557/r4
git log -n 1 --oneline FETCH_HEAD
)
```

**Comment by pkaminski** [comment]
Yep, this works and will continue to work.  It's not formally documented mainly because I thought of it as internal bookkeeping rather than an externally useful feature but it's safe to depend on it.  (It's mentioned in passing [here](https://docs.reviewable.io/#/files?id=rebasing).  @dhbradshaw, perhaps you want to expand the docs for this feature in light of the above?)

**Comment by dhbradshaw** [comment]
Really interesting.  Eric, can you tell us more about what you use this for and why?

**Comment by dhbradshaw** [comment]
Is the value here that the reference lets you check out any revision of any pr without remembering any hashes?

**Comment by EricCousineau-TRI** [comment]
Yup! It helps if you want to run / review a specific revision locally, or if you get a few revisions in and want to revert back to the same exact hash and your `git reflog` is cluttered (or on another machine).

**Comment by dhbradshaw** [comment]
Sorry this took awhile.  We just switched the docs over to static html.  This involved some changes to the links and I wanted to get that completed figuring this out.  But here's a PR calling for an addition to the docs that calls this out specifically:

https://github.com/Reviewable/Reviewable/pull/759

**Comment by EricCousineau-TRI** [comment]
Thank you!!!
Looking at https://docs.reviewable.io/tips.html#easy-local-revision-checkout now, and it looks great!
