### ISSUE TITLE
Jumping to draft doesn't work in single file mode

### ISSUE THREAD

**Issue by pkaminski** [Reviewable/Reviewable#757]
When in single file mode (due to having too many files in the review), clicking on a draft in the Publish dropdown is a no-op if it's in a different while than currently displayed.

**Comment by pkaminski** [comment]
Also, when clicking on "next unreplied comment" in single file mode, the click just jumps to the next file with such comments rather than directly to the next such comment.

**Comment by pkaminski** [comment]
@badz0, I don't think you ended up fixing this, right?  (Just trying to sort out what issues got fixed but I forgot to close.)

**Comment by badz0** [comment]
Yes, I fixed that.

**Comment by pkaminski** [comment]
Oh, great!
