### ISSUE TITLE
Display the number of commit

### ISSUE THREAD

**Issue by eMxyzptlk** [Reviewable/Reviewable#76]
In our team, we require that each branch (each pull request) represents one and only one commit so the history on the master branch is linear and more compact. We'd like to give more important to the number of commits a Review has. Could you possibly add the count? Perhaps at the top of the page alongside other counts?

Thanks,

Wael

**Comment by pkaminski** [comment]
I added the count in fine print under the file matrix.  It's not important to make it into the status bar, sorry!  But @jyasskin's idea about a small server that watches the PR's commits and sets a status on the PR is better anyway: it'll show up in both the status bar and in GitHub proper.
