### ISSUE TITLE
Failed to publish: Request queued but server did not respond

### ISSUE THREAD

**Issue by tombates6** [Reviewable/Reviewable#760]
We had been commenting on this PR fairly heavily when this error occurred. When I tried to publish a change, a pop-up appeared with the same text as the issue title. I tried opening Reviewable in Chrome and Mozilla with the same result, evn after I restarted my machine. My coworker's side still works fine. What could have caused this error?

**Comment by dhbradshaw** [comment]
Thanks for this report.

Github has had some general problems today but now seems to have more specific problems that are sporadically leaving Reviewable's server api requests hanging.  We're tracking this and trying to isolate the issue.

**Comment by tombates6** [comment]
update: It began working again when I tried it 15 minutes ago.

**Comment by dhbradshaw** [comment]
Thanks for following up.  Hopefully this was a temporary aberration, but we'll keep tracking.
