### ISSUE TITLE
reviewable times out showing old pending review comments

### ISSUE THREAD

**Issue by markdroth** [Reviewable/Reviewable#762]
I started reviewing https://reviewable.io/reviews/grpc/grpc/22346 a few months ago.  I entered a number of comments but did not publish them,  Then the effort got stalled for a while.

Now we're trying to pick it back up and continue with the review.  However, reviewable is not showing me any of the comments that I entered when I first reviewed it.  And when I try to view those comments via the "Publish and Block" pull-down at the top right (the "Published Message Preview" section), it churns for a few seconds and then tells me "Request queued but server did not respond".  There is a "Try Again" button, but when I hit it, the same thing happens.

What happened to my pending comments from a few months ago?  The system seems to know that they should be there, but it won't show them to me.

Is there anything I can do to un-wedge this?  Thanks!

**Comment by dhbradshaw** [comment]
So, we're having general connectivity issues with Github right now and this may just be an example of one of the effects.  Are other reviews working for you while this one fails?  Or are they all having issues on and off?

**Comment by markdroth** [comment]
Looks to be working fine now.  Thanks!
