### ISSUE TITLE
Multi-line Template Literal Coloring Issue

### ISSUE THREAD

**Issue by N-Kass** [Reviewable/Reviewable#767]
## Issue
It seems when there is a multi-line string (specifically in this case it's JS template literals, Reviewable fails to find it's ending and colors beyond actual template text.

## Example
See attached screenshot
![image](https://user-images.githubusercontent.com/825412/89180222-ff68eb00-d599-11ea-95e3-4ec18ed2986a.png)

**Comment by dhbradshaw** [comment]
Thanks for this tip, @N-kass. I just tried to reproduce this.  First attempt failed.  What was the context when you saw this?  Was it just the main review page?  (`/reviews/{org}/{repo}/prNumber#`) ?

**Comment by dhbradshaw** [comment]
![image](https://user-images.githubusercontent.com/231662/89310233-09422b00-d63a-11ea-823b-8b2eb585ff3c.png)

**Comment by dhbradshaw** [comment]
Hmm, looks like comments are working for me as well.
![image](https://user-images.githubusercontent.com/231662/89315219-372a6e00-d640-11ea-8d00-60ae69b3e159.png)

**Comment by dhbradshaw** [comment]
Possibly relatedly, we just had a report that "-1" was parsing oddly in Java:
![image](https://user-images.githubusercontent.com/231662/89530683-88f40500-d7b4-11ea-9bc2-00c8f4af31f3.png)

**Comment by N-Kass** [comment]
Possible related, IDK.
This seems to only happen when looking at the revision of the comment, comparing to an older version.
As you can see in the screenshot, there is a section that has been redacted in the revision, right near the test, perhaps that's related
What we see in the screenshot is only the right side of the view (newer version)

**Comment by dhbradshaw** [comment]
I attempted to recreate here:

https://reviewable.io/reviews/reviewable/reproductions/1

No dice yet.

**Comment by N-Kass** [comment]
I can reproduce this consistently, even with an already merged PR, when comparing base reversion (file diesn't exist) to latest with string literal. 
![image](https://user-images.githubusercontent.com/825412/89580748-80481100-d83e-11ea-8124-b5e8fefda9c3.png)

**Comment by dhbradshaw** [comment]
I added a commit with a copy of the above text and for some reason it's not having the same issue.

https://reviewable.io/reviews/reviewable/reproductions/1

Maybe there's something going on here that I can't see in the screenshot.  Would you be willing to either   
* make a gist with a copy the text we're formatting and link that gist here, or 
* make a pull request to https://github.com/Reviewable/reproductions that triggers the issue?

**Comment by pkaminski** [comment]
What I'm seeing in the original screenshot is that the literal highlighting actually begins on the `/` and runs until the next `/`, suggesting that it's getting parsed as a literal regular expression rather than a division.  This is most likely a bug in higlightjs but it must be quite sensitive to context, since Doug hasn't been able to reproduce it so far.  @N-Kass, if you can identify the exact (and ideally minimal) snippet that triggers the bug as Doug requested above, we can file an issue against highlightjs and get it fixed.  Thanks!

**Comment by N-Kass** [comment]
I'm trying to push a branch to create a PR [here](https://github.com/Reviewable/reproductions) but I lack sufficient priviliges.
The issue just happened again on a new PR for a change in the same file as before (different message location, similar text).

I noticed you tested this on JS files, and you claim context is key, so it's important to note we've only seen this in TS files. We mostly write in TS so it may also occur on JS but without us noticing.

Thanks again.

Noam.

**Comment by pkaminski** [comment]
I forced the language to TS but still failed to reproduce.  The reproduction repo is public, but you'll probably need to fork it to create a PR against it.

**Comment by N-Kass** [comment]
Failed to reproduce this on your repo. Yet it still happens in new PR's for the same file in the same location.
Closing this for now since I cannot add evidence for this.

**Comment by dhbradshaw** [comment]
Sorry this one is so elusive... just for a bit more context, what version of Reviewable are you using?  Is the code having issues on the open web?  Or are you using Github Enterprise?  And if Enterprise, what version number?
