### ISSUE TITLE
Reviewable Embedding Google Doc from Github Breaks Link

### ISSUE THREAD

**Issue by N-Kass** [Reviewable/Reviewable#768]
## Overview
When embedding a Google Doc in Github, all seems to work fine. Link works.
When this PR is opened in Reviewable, when you enter the link, access is denied.
Since the actual link is identical, I can only assume this is some referrer issue. 

## Scenarios
This happens when the link is either in the body of the PR on as a comment. 
This happens when link is (MD) embedded as well as just inserted as text.

**Comment by dhbradshaw** [comment]
I'm having trouble reproducing this.  Can you describe where you embedded the link and post the text that failed?

**Comment by N-Kass** [comment]
I think I confused you by using the word "embedded".
If you place a link to a Google Doc, specifically, in a Github PR the link will work.
When viewing the same PR in Reviewable, clicking the PR results in Google telling us we must request permissions.
I suspect this has to do with the referrer.

Also, it seems the link MD formatting that works in Github doesn't work as expected in Reviewable

**Comment by dhbradshaw** [comment]
I attempted to reproduce this here:
https://reviewable.io/reviews/reviewable/reproductions/2
The link seems to work from both sources if the user has access.

**Comment by N-Kass** [comment]
I can no longer reprodcue this.
Closed issue.

**Comment by dhbradshaw** [comment]
Thanks for following up!
