### ISSUE TITLE
Review dashboard doesn't live update

### ISSUE THREAD

**Issue by benbelow** [Reviewable/Reviewable#771]
I've been using reviewable for a couple of years, and I'm pretty sure for most of that time, the review dashboard has live-updated when there are new revisions, or new comments.

In the last few months, I've found that these live updates have stopped - I need to click on a review and wait a couple of seconds to see any new changes. 

Also worth noting that we recently switched to a rebase/force-push workflow, in case that affects things.

**Comment by dhbradshaw** [comment]
Hmm, thanks for this report.

@badz0 is this something you could look into?

**Comment by pkaminski** [comment]
Actually, I just re-read the OP and I realized that the symptoms fit a disconnected repo:  no automatic updates, but the review syncs when visited.  Can you double-check that the relevant repos are connected on Reviewable's Repositories page?

The workflow shouldn't affect things at all.

**Comment by benbelow** [comment]
Hey, sorry for the delayed response! 

I tried re-connecting the repo, and it's been acting much better, thanks for the advice!
