### ISSUE TITLE
Can no longer copy branch names on review screen

### ISSUE THREAD

**Issue by bitdancer** [Reviewable/Reviewable#772]
I used to be able to (by carefully maneuvering the mouse) copy the branch name at the top right of the review screen.  This no longer seems to work, and I haven't updated my browser.

**Comment by dhbradshaw** [comment]
Does it work to use the copy icon?

![image](https://user-images.githubusercontent.com/231662/90561026-ae462300-e165-11ea-859a-37802c5c5a3e.png)

**Comment by bitdancer** [comment]
Yes, it does, thank you.  Icons are in general not my friends, I'm afraid, and there's no hovertext to tell me what they do.  Even if I'd noticed I would have assumed that it copied the URL, not the text, but if I'd noticed it I could have at least tried it :)

**Comment by dhbradshaw** [comment]
Just out of curiosity, what usually leads you to copy the branch name? (I'm trying to see if there's a faster way to get you what you want.)

**Comment by bitdancer** [comment]
I doubt there is.  I copy it to paste it into a git checkout command.

**Comment by dhbradshaw** [comment]
Hmm, this isn't easier, but it allows more precise checkout:

https://docs.reviewable.io/tips.html#easy-local-revision-checkout
