### ISSUE TITLE
Add shortcuts for next/previous changed line

### ISSUE THREAD

**Issue by melink14** [Reviewable/Reviewable#773]
My first impressions of Reviewable are great so far and really bridges the gap between the custom solution my work has and github!

One shortcut that I miss currently is the ability to jump to the next changed line when doing a code review. Especially useful for longer files htat have a handful of changes it allows me to do a full review without my hands leaving my keyboard.

With just next file, I currnetly have to alternate from keyboard navigation to scrolling to review a file which doesn't fit on my screen.

That being said, it's definitely not a major issue. Thanks!

**Comment by dhbradshaw** [comment]
Hmm, you're right.  Looking at the short cuts I see a lot of handy ways to navigate.  But I don't see the option to jump to the next change _within_ a file there.

**Comment by pkaminski** [comment]
Typically Reviewable only shows changed lines to begin with, so you can just use the space bar or cursor keys to scroll down the page.

**Comment by melink14** [comment]
That's fair though it means you're more likely to miss small diffs since
the browser can easily skip over sections.

The value isn't in just fast navigation but in ensuring every diff is
checked!
