### ISSUE TITLE
List of reviewer icons grows unbounded in the /reviews view of Reviewable

### ISSUE THREAD

**Issue by jxramos** [Reviewable/Reviewable#777]
We have an unusual use case where some github integration pulls in a bunch of affected parties that should participate in a review. When the list is for a big cross cutting PR that involves a lot of folks the reviewer preview can get a bit unwieldy and make the `/reviews` page unusable because the text of the PR can get pushed all the way offscreen.

Some kind of max width and wrapping functionality should work really well here I'd imagine.

Check out this screenshot showing what I mean.
<img width="1558" alt="unbounded reviewer list" src="https://user-images.githubusercontent.com/13857038/94471118-7c20db80-017d-11eb-85c2-b4612c5a7bf8.png">

**Comment by pkaminski** [comment]
Huh, I didn't consider that scenario.  🤔 @badz0 can you think of a quick fix here?

**Comment by pkaminski** [comment]
We now truncate the list of avatars if it gets too long relative to window width.  The formula for where to truncate is a bit of a guess so please let us know if it's not quite right.

**Comment by jxramos** [comment]
Looks good, we get this ellipses being rendered for the reviewer icons and also the PR titles as well. The ratios of the column widths looks good to me too.
