### ISSUE TITLE
Clearly communicate review approval in github and email messages.

### ISSUE THREAD

**Issue by scheib** [Reviewable/Reviewable#78]
Upon completing a review in reviewable.io, a message is appended to the pull request and may be viewed by authors and others not using reviewable.io. 

When comments are made, it is clear in this message that items are to be addressed.

When the review is complete, the message is a bit ambiguous:
> Reviewed files:
> -  index.html @ r3
>
> Comments from the review on Reviewable.io

If all comments and files are reviewed and I publish, I expect something like
"All current files reviewed", "Review complete", "LGTM", etc.

**Comment by jdm** [comment]
This would be valuable for automation based on completing a review.

**Comment by pkaminski** [comment]
Huh, looks like GitHub auto-closed this a bit eagerly.  But yeah, this feature is live now -- there'll be a "Review status" line in every message generated by hitting `Publish`.  Let me know if what you see is sufficient or if you need more information / another format.

**Comment by pkaminski** [comment]
Apologies, I had to roll back the release -- will ping again when it's really up.

**Comment by pkaminski** [comment]
OK, should be up for good this time.
