### ISSUE TITLE
Show commit messages

### ISSUE THREAD

**Issue by duarten** [Reviewable/Reviewable#780]
When reviewing the PR as a series of well-structured commits, it would be great to display each revision's commit message, as that style of development emphasizes good commit messages.

**Comment by pkaminski** [comment]
Hey, so commit messages are actually shown in two places in Reviewable:
1. The commits that comprise each revision are listed in generated top-level comments in the review.  These are mainly useful when you're in "review aggregated commits" style and want to know what new stuff there is to review.
2. When you're within a file scope (i.e., there's a path pinned to the top toolbar), the Changes dropdown in the toolbar will show a list of all commits encompassed by the current diff.  (Note that it doesn't filter out commits that didn't actually affect this specific file -- that's an enhancement tracked in #228.)

Does that address your issue?

**Comment by duarten** [comment]
I'm not sure. I noticed that when I'm in "review each commit separately" mode, each commit shows up as a separate revision, but the commit message is not in any obvious place. My expectation for reviewing each commit separately would be that I could read the commit message introducing the changes before actually diving into the code; ideally, I would be able to comment on the commit message itself.

**Comment by pkaminski** [comment]
If you're in separate-commits review mode, the commit messages are still in the places listed above, and IIRC the dropdown will show the list commits even when not in a file context (as long as you stick with the default diff bounds).

As for reviewing commit messages, that's #507.
