### ISSUE TITLE
Change subsequent PR base (like Github does) when merging chained PRs

### ISSUE THREAD

**Issue by jakebiesinger-storyhealth** [Reviewable/Reviewable#786]
Thanks for your work on this awesome tool!

## Context 
We often chain PRs together:

```
git checkout master
git checkout -b feature1
<hack>
git commit -am 'feature1' && git push

git checkout -b feature2
<hack>
git commit -am 'feature2' && git push

git checkout -b feature3
<hack>
git commit -am 'feature3' && git push
```

Now we go open PRs for each... `feature1`'s base is `master`, `feature2` is based on `feature1`, and `feature3` is based on `feature2`.

## Expect
If we merge feature1 in the Github interface, it automatically changes the base of the subsequent branch, for example:

![image](https://user-images.githubusercontent.com/66106280/98401948-b9ea0d00-2023-11eb-85d7-da5dc13612c8.png)

## Actual

If we merge feature1 in the Reviewable interface, then feature2 is *closed* instead of having its base updated. It's rather frustrating to get things back into a good state from there.

**Comment by pkaminski** [comment]
Huh, that's unexpected.  We just use GitHub's normal merge API, so I expected that this would include the branch swizzling.  Perhaps we need to do that manually -- I'll investigate.

**Comment by pkaminski** [comment]
OK, so it looks like base change is supposed to be triggered by the deletion of a branch, not the merge, per the [docs](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-branches#working-with-branches).  It also looks like using GitHub's ref deletion API doesn't trigger this feature -- it must be built into their frontend.  We'll have to reimplement the feature in Reviewable, but in the meantime a workaround is to change your repo config to have GitHub [automatically delete the head branch](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-the-automatic-deletion-of-branches) instead.

Thanks for finding this bug!

**Comment by pkaminski** [comment]
The fix is now in production, please let us know if you still see this!

**Comment by jakebiesinger-storyhealth** [comment]
Working beautifully. Thank you!
