### ISSUE TITLE
Non-assigned mentions are hard to discover; should allow opt-in option to list them in list of my reviews

### ISSUE THREAD

**Issue by pkarasev3** [Reviewable/Reviewable#791]
If someone merely puts "fyi @your.name " without assigning, it's very easy for this to get lost. Can you just make an option to turn on showing such reviews in the list of "my reviews" ? 

    It used to be by default showing both "@" and "+@" but was changed some months ago to skip the "@" usage. Very frustrating.

**Comment by pkaminski** [comment]
I don't recall any intentional change to this logic -- in fact, we recently fixed #754 so that all @-mentions will be reflected on the dashboard -- but perhaps there's a regression.  I'll play around with mentions tomorrow to see if I can repro, but please also let me know if you happen to have a PR in a bad state that I could take a look at.  Thanks.

**Comment by pkaminski** [comment]
I finally got around to checking this out -- apologies for the delay.  In my test, I had user A create a PR, then post an `fyi @B` top-level message.  This put the review in user B's "Involving me" section of the dashboard.

Is this not working for you?  If so, please specify where and how the mention comment is posted.

Or is your concern that it's showing in a pretty low section?  AFAIK this has always been the case, whereas your report says that something changed recently.

**Comment by pkaminski** [comment]
Ping -- can you provide further details as requested above?  Thanks.

**Comment by pkarasev3** [comment]
Hi, ok it sounds like other people complained about this too and there are some duplicate bug reports. 

How can I know what version of reviewable we're using? is it always running 'live' ?

**Comment by pkaminski** [comment]
If you're using reviewable.io then you're always on the latest.  If you're using an enterprise release, the version is shown at the bottom of the Support dropdown

**Comment by pkaminski** [comment]
Ping -- we need more details to identify and reproduce this bug.

**Comment by pkaminski** [comment]
Closing for lack of details.

**Comment by jwnimmer-tri** [comment]
I'll also probably have my corporate contact ping you with extra info, but here's some repro details that I can share:

Reviewable Enterprise v2200.3821.
GitHub Enterprise Server 2.20.16.

1. Author opens a PR.
2. On the Reviewable page for that PR, in the "Review discussion" box, the author types `FYI @foobar` and then clicks big green "Publish" in the upper right.
3. The GHE Notifications setting on that PR for the foobar user _does_ show them as Subscribed to the PR -- they _do_ get the "FYI" email and subsequent discussions in their message inbox.
4. The Reviewable dashboard for the foobar user does **not** show that PR anywhere.

I expected that the foobar user would see the mentioned PR in their "Involving me" section, but it's not there.  I confirmed that the PR is not filtered out (there is no filter query) and that it's not under the "stale" fold, either.

If the author opens the GHE PR page and posts `FYI @foobar` in a PR comment (not a review comment), then the reviewable dashboard _does_ show the PR in "Involving me".

So possibly a critical element of the repro is to post the mention in "Review discussion".

**Comment by pkaminski** [comment]
Thanks -- the old version you're using explains it.  This is https://github.com/Reviewable/Reviewable/issues/636, which got a workaround released in v2569.4290.  You should schedule an upgrade ASAP!
