### ISSUE TITLE
"Next/Previous personally unreviewed file" shortcut stopped working. 

### ISSUE THREAD

**Issue by benbelow** [Reviewable/Reviewable#800]
I have overridden the default n/p shortcuts to use the "next personally unreviewed version functionality.

This morning I encountered a review that someone else has already completed, and plan to use these shortcuts to navigate as normal - but they do nothing. 

The shortcuts seem to work on other reviews that haven't been reviewed by anyone, matching the default shortcut behaviour. The "?" key shows the overridden behaviour, implying that my custom shortcut bindings are working correctly.

I can replicate this issue on more than one review.

**Comment by pkaminski** [comment]
Thanks for reporting this regression.  I'm currently traveling so it might take me a while before I can dig into it but I should be able to get things fixed by end of the month.

**Comment by pkaminski** [comment]
Man, these semantics get subtle.  Should be fixed now, please give it a whirl.

**Comment by benbelow** [comment]
@pkaminski I've just had an example where I can actually test this again, and appears to be working as expected - thanks!
