### ISSUE TITLE
Generated python grpc stubs not ignored

### ISSUE THREAD

**Issue by gbrel** [Reviewable/Reviewable#805]
It looks like reviewable doesn't ignore files generated as python grpc stubs. As far as I can tell this should be the header that identifies such a file:
```
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
```

Can we have this pattern added in order to ignore these files?

**Comment by pkaminski** [comment]
Hey @anthonykawa, could you please add this pattern to `GENERATED_COMMENT_REGEX` in `diff_worker.js`?  Thanks.

**Comment by pkaminski** [comment]
This should now be live -- please check.
