### ISSUE TITLE
Trying and failing to fetch PNG file content

### ISSUE THREAD

**Issue by pkaminski** [Reviewable/Reviewable#808]
@dhalperi reports that, starting recently, `png` files fail to fetch with the error message `GitHub disregarded the 'raw' media type`.  This error is a failsafe for when we detect that GitHub returned JSON even though we asked for raw file contents -- I believe it's an intermittent bug in their API but I could never get it to happen locally.

1. We should see if we can reproduce it, determine if it actually is a bug in GitHub, and if so report it.  (Otherwise, we're probably misusing the API in some subtle way and should fix that.)
2. We should probably avoid fetching image files based on their extension to begin with.  There's already a map of common image types in `reviews.$reviewKey.files.$fileKey.diffs.$diffKey` and some disabled code to use it for the image diff tool that we have yet to build.  We should revive some of this code to mark the file as an image and present an appropriate message and "see diff on GitHub" button for now.

**Comment by dhalperi** [comment]
For me this does not seem to be intermittent. Happy to set up a time to debug together.

What I did tonight: go to a review where this was an issue, reload with `debug=model,workers`, and look at Chrome dev tools. When I hit the "try again" button I saw 6 requests go - OPTIONS then GET 3x, with response codes 204,200 3x. The 200 GET requests have response headers including `content-length: 102614`, which is the correct value.

I copied the GET as cURL and loaded it in the terminal; the file it created is the correct PNG. Not sure what to check next!

**Comment by dhalperi** [comment]
Response headers:
```
access-control-allow-origin: *
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
cache-control: private, max-age=60, s-maxage=60
content-length: 102614
content-security-policy: default-src 'none'
content-type: application/octet-stream
date: Tue, 26 Jan 2021 03:32:34 GMT
etag: "REMOVED"
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
server: GitHub.com
status: 200 OK
strict-transport-security: max-age=31536000; includeSubdomains; preload
vary: Accept, Authorization, Cookie, X-GitHub-OTP, Accept-Encoding, Accept, X-Requested-With, Accept-Encoding
x-accepted-oauth-scopes
x-content-type-options: nosniff
x-frame-options: deny
x-github-media-type: github.v3; param=raw
x-github-request-id: REMOVED
x-oauth-client-id: REMOVED
x-oauth-scopes: admin:org_hook, admin:repo_hook, read:org, repo, user:email
x-ratelimit-limit: 5000
x-ratelimit-remaining: 4581
x-ratelimit-reset: 1611634306
x-ratelimit-used: 419
x-xss-protection: 1; mode=block
```

**Comment by pkaminski** [comment]
I fixed Hubkit to recognize the `application/octet-stream` content type as valid, which takes care of item 1.  Leaving this issue open for item 2, since there's no point in even trying to fetch image files.

**Comment by pkaminski** [comment]
Reviewable should no longer attempt to fetch files that match its built-in image filename patterns.
