### ISSUE TITLE
Reviewable tab crashed on Publish

### ISSUE THREAD

**Issue by bashir2** [Reviewable/Reviewable#814]
I am trying Reveiwable for the first time. Everything worked great up to the point that I wanted to publish. The Chrome tab crashed every time I tried. Before crashing, it starts to use a lot of memory/cpu. In Firefox too, it starts using more and more memory; I let it go higher and higher until it died at 10+ GB.

Here is the PR I am reviewing:
https://reviewable.io/reviews/GoogleCloudPlatform/openmrs-fhir-analytics/86#-

I have also copied a log from Chrome's developer tools console here:
https://gist.github.com/bashir2/d06876d2ae3d985c13b1184612a13087

**Comment by bashir2** [comment]
I can reproduce this behavior on other PRs too: https://reviewable.io/reviews/GoogleCloudPlatform/openmrs-fhir-analytics/101#-MSe8RDW38b_uAVZRV-B

**Comment by pkaminski** [comment]
I'm not sure why it's eating up memory (that's likely a separate bug in error handling), but it looks like POSTing your message to GitHub is returning a 403 code.  This is a bit of a catch-all code in the GitHub API, so could you please look at the Network debugger to see what the associated message is?  That should let you move forward, and perhaps will provide a hint as to why Reviewable's error-handling is failing so spectacularly.  Thanks!

**Comment by bashir2** [comment]
Thanks for the quick feedback. You are right, I looked at the network request failures and I can see:
```
{
  "message": "Although you appear to have the correct authorization credentials, the `GoogleCloudPlatform` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/",
  "documentation_url": "https://docs.github.com/rest"
}
```
I will follow up with our org owners.

**Comment by pkaminski** [comment]
Thanks.  It doesn't really explain why Reviewable locked up, though, but we are several versions behind on Sentry (the exception tracking library we use), so most likely there's a bug in there somewhere.  We're almost done with the update so hopefully that will remedy the issue.

Tangentially, I believe that Google has an app authorization policy for GitHub that will preclude the use of the SaaS version of Reviewable.  Yours wouldn't be the first team to run into this issue -- please get in touch with support@reviewable.io to discuss options if you'd like.  Thanks!
