### ISSUE TITLE
Fixing the "Unreviewed" button/counter

### ISSUE THREAD

**Issue by pkaminski** [Reviewable/Reviewable#817]
(Reposted with permission on behalf of @mgartner.)

I work for Cockroach Labs where we use Reviewable extensively. I was hoping to point out what I think is a bug. If fixed, it would greatly improve our review workflow.

The "Unreviewed" button and counter at the top of a review seems to be "unreviewed by anyone", rather than "unreviewed by me". Therefore, if a colleague of mine has already reviewed all files, I cannot click that button to navigate to files I have not yet reviewed.

For a concrete example, here is the button and the list of the reviewed files. The "unreviewed" counter should be 2 not 0.

![image](https://user-images.githubusercontent.com/1646896/107378513-0b3de880-6aba-11eb-9d84-0d253c922d41.png)

![image](https://user-images.githubusercontent.com/1646896/107378543-109b3300-6aba-11eb-92c9-3604ae136948.png)

This seems to be the case even with this check box selected:

![image](https://user-images.githubusercontent.com/1646896/107378562-17c24100-6aba-11eb-802d-da296a013415.png)

If I can provide any further information, please let me know.

**Comment by pkaminski** [comment]
This is related to #306, #404, #455, #560, and #750.  In #404 I decided to introduce next/previous _personally_ unreviewed file commands as a kludge.  That issue also explains why the check box doesn't do what you expect:

> Toggling on "Include changes in files previously reviewed only by others" means "first check if a file is considered reviewed, and if it's not then don't pay attention to who reviewed it in the past -- it's in scope".

This means that we effectively support two reviewing modes:
1. Review all files that are not yet considered reviewed at the latest revision.  (checkbox toggled on)
2. Review all files that are not yet considered reviewed at the latest revision unless they were reviewed at a previous revision by somebody else.  (checkbox toggled off)

You can affect whether a revision is considered reviewed by customizing the review completion condition for a repo, but by default it takes a single review mark at that or any later revision.  You could write a condition that considers all files as always unreviewed as a kludge but this would likely have some undesirable side-effects.  Instead, I think we need a third mode:

3. Review all files that have not yet been reviewed by you at the latest revision.

This could be presented as a dropdown similar to the aggregate / separate commits choices but only displayed once there are multiple reviewers:
1. Divide and conquer: review unreviewed files that aren't claimed by others.
2. Follow the sun: review any unreviewed files.
3. Trust no one: review all files personally.

The choice would be sticky per user per review, and the user's latest choice would also set the default for that user in new reviews.  We could also add a per-repo default like I did for the checkbox in #200, but I don't think I ever had any further requests for that feature so it may not be worth the extra complexity and effort.  We'd get rid of the next/prev personally unreviewed file bindings.

How does that sound?

Folks who may be interested in commenting on this:  @mgartner, @lilyball, @seansfkelley, @alzix, @cjancsar, @rbtcollins, @valloric, @feldgendler

**Comment by feldgendler** [comment]
This is a great idea!

**Comment by seansfkelley** [comment]
I think this makes a lot of sense and is a cleaner overall design than purpose-built hotkeys! A few comments/questions in no particular order:

- I agree that per-repo defaults don't sound very useful. This seems like the kind of setting that would be strongly correlated with a person (user preference) rather than a chunk of code (repo preference).
- Is the behavior where "the user's latest choice would also set the default for that user in new reviews" consistent with other configurable things in Reviewable? I haven't thought deeply about this and admittedly I'd personally be unlikely to ever change the setting, but that is a rather surprising way to set a system-wide user preference.
- I'd consider making the default "trust no one" because this is the simplest to understand, even if it creates the most work. Reviewable already has a moderate learning curve and can be overwhelming at first.

**Comment by mgartner** [comment]
The proposal sounds great to me!

**Comment by pkaminski** [comment]
Thanks for the feedback folks!  We'll be moving ahead with this soon, though I think I'll rename "Trust no one" to "Free-for-all" as it has less negative connotations and fits the sequence better.  I think I'll also add a small blurb to the bottom of the dropdown linking to instructions on changing the definition of "unreviewed" for a repo by customizing the review completion condition, since I don't want people to use the free-for-all mode as a kludge for "N reviewers required".

To @seansfkelley's points:
- Yep, Reviewable uses "last set is default" in a few different spots.  It cuts down on explicit configuration and usually isn't too surprising, or at least I haven't heard complaints about the mechanic yet.
- The current default is effectively "follow the sun".  I can see arguments for having any of the three modes as a default:  "free-for-all" because it's the least prescriptive and least surprising coming from other tools, "follow the sun" because we know it works well enough for most folks based on the last few years of experience, and "divide & conquer" because it's the most efficient and most likely to prompt users to learn about the other modes to pick the optimal one for their workflow.  Not leaning towards one yet.

Any further thoughts from anyone before we run with this?  Thanks.

**Comment by rbtcollins** [comment]
Yup, I think you've covered the space well. Thank you for taking the time
to think this through!

**Comment by feldgendler** [comment]
I wouldn't understand what “Free-for-all” means without an explanation (and I'm still not sure why it's called so), but I had immediately understood what “Trust no one” means. Although I agree that it has a negative connotatoin.

**Comment by feldgendler** [comment]
Will there still be a distinction between “red” and “gray” files?

**Comment by pkaminski** [comment]
Good point, free-for-all is pretty idiomatic English and might not be understood by non-native speakers:
> A disorganized or unrestricted situation or event in which everyone may take part, especially a fight, discussion, or trading market.

However, it's such a good fit for the mode, I can't find a reasonable synonym, and I don't want the negative connotation of "trust no one" that I think it's a keeper.  Really they're just meant to be catchy names and will always be displayed with the explanations attached, so I don't think it's going to be a problem in practice.

As for red/grey file counters -- yes, the red counter will follow your personal mode for that review, whereas the grey counter will just count the number of unreviewed files (according to the completion condition).  A non-zero red counter will always override the display of the grey counter, even if the latter is zero.

**Comment by feldgendler** [comment]
I know what “free-for-all” means. But it's not quite the same. It implies that anyone _may_ participate, but anyone may in fact participate regardless of the mode. It's whether you _have to_ review what's already reviewed by others — and that's why “Trust no one” is closer to the point.

**Comment by pkaminski** [comment]
Ah, got it.  I was looking at it through a lens of "what files are we removing from the user's plate?", in which case free-for-all means the user is free to review any files they want.  However, I can see that through a lens of "what files are we requesting the user to review?" this would indeed be confusing.  How about DIY or do-it-yourself instead, then?

**Comment by feldgendler** [comment]
DIY has strong connotations of home improvement projects and such (I'd be confused if it were used to mean something else), but the right metaphor feels to be somewhere in the vicinity of that. Let me think of a few alternatives…

* “Control freak”
* “Meticulous”
* “I don't want to miss a thing”
* “All by myself”

All of these make a point that this is a personal preference rather than a project setting. Of these, the former is quite negative (but precise), and the latter two are pop music references :-) The Aerosmith variant is my personal favorite.

**Comment by feldgendler** [comment]
“Follow the sun” is also quite unobvious. I wouldn't understand it without the explanation — probably because I'm looking at it from the reviewer's perspective. Not sure what to replace it with, though. “Share the work/load/burden”?

An alternative might be to just say what you said above:

* Review unreviewed files that aren't claimed by others
* Review any unreviewed files
* Review all files personally

Not as catchy and somewhat longer, but very precise and doesn't need further explanation.

**Comment by pkaminski** [comment]
We're definitely bikeshedding now but I really like putting in these little touches of whimsy.  :)

I _love_ the Aerosmith variant -- it's a bit long, but it's worth it.

The idea behind "follow the sun" was that whoever's available does the next round of the review, but it is a bit cryptic.  Two other possible ideas:
- "All for one and one for all"
- "All hands on deck"
- "Next available [appointment | reviewer | ]"
- "Jump in the line" (to keep the musical theme)

The UI around this dropdown will need to make clear that this is a personal setting no matter what.

**Comment by pkaminski** [comment]
Putting this in the work queue.  Let's go with these labels at least for now:

1.  Divide and conquer: review unreviewed files that aren't claimed by others.
2.  All for one and one for all: review any unreviewed files.
3.  I don't want to miss a thing: review all files personally.

**Comment by pkaminski** [comment]
This is live and seems to be holding up so far.  Unfortunately we had to drop the fun mode names we came up with -- they were just too opaque without a lot of context. 😞

**Comment by mgartner** [comment]
Thank you!!!

**Comment by mgartner** [comment]
Was this feature reverted? I don't see the new options anymore.

**Comment by pkaminski** [comment]
No, it should be live, but the dropdown only shows up in reviews with more than one reviewer.

**Comment by mgartner** [comment]
Am I missing it here? I found it instantly when I first tried the feature, but not seeing it on this review that's clearly been reviewed by someone else already:

![image](https://user-images.githubusercontent.com/1128750/119388699-7b463800-bc7f-11eb-9c6e-da0f945e28f6.png)

**Comment by pkaminski** [comment]
Ah, I think you might've found a loophole:  since you haven't marked anything as reviewed you're not considered a reviewer yet, and hence it's a single-party review and the dropdown doesn't show.  This is obviously a perverse outcome -- @anthonykawa, we should fix this so the dropdown shows up if the current user is a potential reviewer and there's at least one other reviewer on the books already.  Please prioritize.

**Comment by pkaminski** [comment]
This should be fixed now.

**Comment by mgartner** [comment]
Thanks for the timely fix!
