### ISSUE TITLE
Rare case GitHub's differ outdoes Reviewable's differ in this terrible refactoring PR

### ISSUE THREAD

**Issue by dhalperi** [Reviewable/Reviewable#818]
https://github.com/batfish/batfish/commit/b48335177306e12f0d0a3a09cc1d6d7f466956b0

Very low priority, but since I think you like me reporting these issues;

This PR refactored away thousands of lines of whitespace. GitHub actually seems to have done a better job of lining the diffs up than Reviewable, which is so surprising to me I thought it worth reporting :).

For an example, this segment of `AristaLexer.g4`:

<img width="1261" alt="Screen Shot 2021-02-25 at 2 50 42 PM" src="https://user-images.githubusercontent.com/526415/109229958-ebc0e400-7778-11eb-9eda-09e7ed57e151.png">
<img width="1360" alt="Screen Shot 2021-02-25 at 2 51 00 PM" src="https://user-images.githubusercontent.com/526415/109229967-eebbd480-7778-11eb-8b9e-6f774bfa91af.png">

**Comment by dhalperi** [comment]
PR link: https://reviewable.io/reviews/batfish/batfish/6661#-

**Comment by pkaminski** [comment]
Thanks -- copied into #326, which I'm using to hold all "bad diff" reports.
