### ISSUE TITLE
Comments feel incomplete

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#82]
Having come from using https://critic.hoppipolla.co.uk/ before this, I encountered a UX difficulty when it comes to adding comments. I have a mental hiccup when I've finished writing a comment - it doesn't feel like my changes will be saved while there is an editable textfield sitting there. Not only do I need to unfocus it in order to continue using the keyboard shortcuts on the review, but I also crave a "Save comment" button for peace of mind.

**Comment by pkaminski** [comment]
Yeah, this requires a mental adjustment similar to when Google Docs dropped the save button, but I think it's worth it.  If you'd like, you can hit shift-ctrl-P (shift-cmd-P on Mac) to switch the draft to preview mode, which will hide the input field and remove focus.  If this helps, you can also assign a more convenient shortcut to this (e.g., ctrl-s) with a [custom key binding](https://github.com/Reviewable/Reviewable/wiki/FAQ#can-i-customize-the-key-bindings).  If you don't mind the input field staying on the screen then Esc will unfocus it too.

I won't be adding an explicit save button, though -- Reviewable is not a legacy app.
