### ISSUE TITLE
Respect hg-git extra data for copies/renames

### ISSUE THREAD

**Issue by SanjayVas** [Reviewable/Reviewable#823]
[`hg-git`](https://foss.heptapod.net/mercurial/hg-git) is a Mercurial (Hg) plugin that allows for interacting with a remote Git repository from a Mercurial one. One way in which Mercurial and Git differ is that the former has explicit tracking of copies and renames, as opposed to the latter's use of on-the-fly detection. The latter can be computationally expensive  to do accurately for large numbers of files (see #349).

The `hg-git` design attempts to support lossless two-way migration. For copy/rename tracking, it handles this by adding [extra headers](https://github.com/git/git/blob/a5828ae6b52137b913b978e16cd2334482eb4c1f/commit.h#L262) to the commit object that are visible using the `git-cat-file` command. This ensures that a copy manually tracked using `hg copy` is visible to any clone of a Git repository using `hg-git`. See the [relevant function](https://foss.heptapod.net/mercurial/hg-git/-/blob/8b155da33c49046c4cdcf8f2a136454ad521ea6d/hggit/git2hg.py#L90) in the `hg-git` source code.

If a commit object has these extra headers, Reviewable could use them to display more accurate diffs without having to enable computationally-expensive on-the-fly detection.

**Comment by pkaminski** [comment]
Thanks -- it's a neat idea, but I'm not sure the ROI is there TBH.  How widespread is Git / Mercurial integration among GitHub users, and what percentage of that uses `hg-git`?

**Comment by SanjayVas** [comment]
Just to add more info, it looks like the usefulness would be even more limited as GitHub doesn't allow for fast-forward merging pull requests. As a result, it always rewrites the commits without preserving the extra headers. Therefore, it may be that only directly pushed commits would have these headers.

For some background, I see the lack of explicit copy/rename tracking as a fundamental flaw in Git compared to other VCSs. I was seeing this as a way to end-run around this limitation without changing Git's design, while still using it due to its popularity. Such a workaround involves two parts: 
1. Having a way to pass copy/rename hints through Git. Commit extra headers seems a great place for this.
2. Having tools that understand those hints. The minimum would be direct VCS manipulation (Mercurial + hg-git) and code review that's aware of the hints.
