### ISSUE TITLE
Make review comments apply to a range of lines

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#83]
I often provide review comments that apply to a number of contiguous lines. It would be much clearer if I could select them and show that the comment applies to all of them, like https://critic.hoppipolla.co.uk/showcomment?chain=8508 for example.

**Comment by pkaminski** [comment]
I considered this early on, but decided that the potential bump in clarity is not worth the extra UX complexity.  For the rare cases where a line range is important it's possible to just describe it in the comment instead.  At this point, the assumption that a discussion is attached to a single line is baked too deeply into the code, sorry.
