### ISSUE TITLE
Next personally unreviewed file no longer working

### ISSUE THREAD

**Issue by Cellule** [Reviewable/Reviewable#832]
Since very recently the keybind command `nextPersonallyUnreviewedFile()` stopped working
As far as I remember, my team and I switched `n` keybind to use that instead of `nextUnreviewedFile()` because `nextUnreviewedFile` skipped files reviewed by someone else and I really want to review all files myself

![image](https://user-images.githubusercontent.com/4157103/117181057-d680bb00-ada2-11eb-864b-077b5627422b.png)

Here's the keybinds file I'm using
https://gist.githubusercontent.com/Cellule/094c683e978c734e05fb02292ed6c333/raw/48d59c8d9584f5bc8ede091f3cf67b5a8c7603b0/reviewable-bindings.json

I even noticed that command was removed from https://reviewable.io/bindings.json as well.

**Comment by Cellule** [comment]
I just tested and indeed `nextUnreviewedFile`'s behavior skips files reviewed by someone else making it completely useless.
Sometime the PR creator self reviews and mark files as reviewed. Without  `nextPersonallyUnreviewedFile` it is greatly reducing review convenience and speed when multiple people reviews the same PR

**Comment by pkaminski** [comment]
We removed this shortcut because the functionality has now been fully integrated into Reviewable.  See the [recent post](https://headwayapp.co/reviewable-changes/new-overlap-strategy-193348) for details.

**Comment by Cellule** [comment]
Sorry I missed the post regarding that change. I have updated my keybinds and changed to use that new setting.
Thanks a lot
