### ISSUE TITLE
Allow filtering file matrix by glob

### ISSUE THREAD

**Issue by RaduBerinde** [Reviewable/Reviewable#834]
Reviewable is challenging to use for very large PRs. In most cases, I want to look at the non-test aspects of the change first. It would be super useful if I could hide all `*_test.go` or `*/testdata/*` files.

I realize this has the potential to clutter the UI. One way around that would be to require the user to first configure "presets" for file matrix filters; only if these presets are configured, there would be an extra UI component that allowed selecting a preset.

**Comment by jwnimmer-tri** [comment]
FYI In case it helps, see "Files can also be grouped" at https://docs.reviewable.io/files.html#file-list.

**Comment by RaduBerinde** [comment]
> FYI In case it helps, see "Files can also be grouped" at https://docs.reviewable.io/files.html#file-list.

Interesting, thanks. I will see if I can figure out how to set that up.

**Comment by pkaminski** [comment]
@jwnimmer-tri is right, the file grouping feature is intended to address this use case and I believe fits your requirements really well.
