### ISSUE TITLE
No "next" button on already-reviewed files when using "Review all files personally"

### ISSUE THREAD

**Issue by jakebiesinger-storyhealth** [Reviewable/Reviewable#835]
When in the mode "Review all files personally", 

![Screen Shot 2021-05-05 at 5 36 59 PM](https://user-images.githubusercontent.com/66106280/117236405-79562b00-addd-11eb-9ac5-e0f4ccf0309c.png)

files that have been reviewed by others show up in the top (correctly, yay!)

![image](https://user-images.githubusercontent.com/66106280/117236505-aacef680-addd-11eb-8723-39d452117565.png)

But the button "Mark reviewed + go to next file" is not present, which makes it harder to work in this mode.

![image](https://user-images.githubusercontent.com/66106280/117236676-04372580-adde-11eb-9465-2ed94e20535f.png)

**Comment by pkaminski** [comment]
Thanks -- that's definitely a bug, we'll look into it.

**Comment by pkaminski** [comment]
This should be fixed now -- please let us know if you still see the issue.
