### ISSUE TITLE
Comments cut off mid-sentence

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#838]
I noticed that comments abruptly ended mid-sentence on two code reviews from two different coworkers yesterday, for example:

![image](https://user-images.githubusercontent.com/98301/121380579-fc096300-c912-11eb-878f-e1f1c97485c4.png)

Sadly I don't have much more context I can share (e.g. was there a particular character at that point, like `<` or an emoji?). But wanted to flag in case others are seeing this, too. cc @ludazhao

**Comment by pkaminski** [comment]
Can you confirm whether the comments also appear cut off in the messages posted to GitHub?  Can you let me know one of the PRs so I can check whether this affects the Markdown source too or just the HTML render?  Thanks!

**Comment by danvk** [comment]
@pkaminski they do appear cut off on GitHub as well. Here's the example from the screenshot above: https://github.com/sidewalklabs/cityci/pull/5132

**Comment by pkaminski** [comment]
OK, I confirmed that it's cut off in the Markdown source too, so it's not just a rendering bug.  Assuming this is not a user error the most likely explanation is some kind of race in the widget <-> model <-> database sync.  We'll likely need some more data to find a pattern that could lead to a repro, though.

Were both instances you observed a comment in the main discussion?  Were these drafts written immediately prior to publishing, and perhaps still flushing to the DB?  Did your coworkers notice any issues with Firebase today, as indicated by a yellow or red signal icon in the lower right corner of the page?

**Comment by pkaminski** [comment]
Ping -- looking for a bit more information before things get forgotten:
> Were both instances you observed a comment in the main discussion? Were these drafts written immediately prior to publishing, and perhaps still flushing to the DB? Did your coworkers notice any issues with Firebase today, as indicated by a yellow or red signal icon in the lower right corner of the page?

**Comment by ludazhao** [comment]
@pkaminski Thanks so much for looking into this! The comments were in the inline comments. I don't quite remember the exact timing but I can try to re-pro on my end on writing + immediately publishing. There might be some also network-related issues on my end, so I will make a note to test this off similar settings, will report back if I can re-pro this on my end!

**Comment by pkaminski** [comment]
It's been a while -- did you observe this happening again in the last couple months?

**Comment by ludazhao** [comment]
@pkaminski thanks for the follow-up, I believe we haven't repro-ed this issue since, happy to close this

**Comment by pkaminski** [comment]
Thanks, closing for now.  Please ping the issue if it happens again and we'll reopen!
