### ISSUE TITLE
Reviewable dropped 20+ comments

### ISSUE THREAD

**Issue by nrathi** [Reviewable/Reviewable#839]
Hi, 

I just reviewed a PR yesterday, but only 6 of my ~32 comments were actually published :(. This has never happened to me before, so I'd love to help you debug it if I can. It seems like the comments that were dropped were on new files.

Thanks,
Neha

**Comment by pkaminski** [comment]
Woah, that's not good!  Can you let me know which PR this happened in?  Are the comments also missing from the message published to GitHub?  Are the remaining drafts still in the review, or did they get deleted?  Thanks.

**Comment by nrathi** [comment]
Yeah the comments were totally un-recoverable. My default for new comments is "Discussing", and the one thing I did differently yesterday was "Publish and request changes" instead of "Publish and comment", but I even remembering scrolling through the preview and sanity-checking everything before sending it off. 

You won't be able to see the PR but would the link be helpful? (Do you have logs?)

**Comment by pkaminski** [comment]
Yes, a link to the PR would still be useful even if it's private.  I can at least check Reviewable's own data structures for it.

Were any files renamed in the review?

Can you check whether the missing comments are present in the bulk message posted to GitHub?  (Or ideally send a copy of that message's raw Markdown to support@reviewable.io?)  Thanks.

**Comment by pkaminski** [comment]
Ping -- can you provide the details requested above?  I'd really like to figure this out if possible.  Thanks.

**Comment by nrathi** [comment]
Just sent you an email!

- 1 file was renamed in the review, but I didn't comment on it 
- My comments were kept in 3 files (all old)
- My comments were dropped in 7 files (3 new / 4 old)
- Only the 6 published comments were in the GH message/markdown.

**Comment by pkaminski** [comment]
Summary from email conversation:  this occurred in Reviewable Enterprise v2997.4729.  Since that version has a known draft loss bug (that was fixed in v3024.4796) I'm assuming that this was an extreme instance of it.  If this recurs in the latest version once it's set up we'll dig deeper.
