### ISSUE TITLE
cannot jump to unresolved comments between other people

### ISSUE THREAD

**Issue by mmlb** [Reviewable/Reviewable#84]
I see the comments section showing `0/1!` and the hover text notes that there is an unresolved comment pending other party. Trying to find that one comment in the haystack of many is non-trivial. This should jump to it whether its waiting on someone else or not.

**Comment by TauZero** [comment]
:+1:

**Comment by pkaminski** [comment]
This is indeed annoying, but I haven't yet found a solution that doesn't break one of my UI principles: only red counters are clickable, only counters that mean you have to do something are red.  Also, I think it might be confusing if the button cycles between unreplied comments when the counter is red, and between unresolved comments when grey.  I'll keep thinking of an elegant UI to resolve this, though...

But fear not!  In the meantime, you can use shift+J/shift+K to cycle between unresolved comments!  Check out shift+? for all the default bindings, and https://reviewable.io/bindings.json for other commands that are not bound by default but that you can [bind](https://github.com/Reviewable/Reviewable/wiki/FAQ#can-i-customize-the-key-bindings) yourself.

**Comment by pkaminski** [comment]
Never mind, I fixed it.

**Comment by mmlb** [comment]
:smile: best nm ever
