### ISSUE TITLE
Changing diff bounds loses position with large diff

### ISSUE THREAD

**Issue by gilbertbw** [Reviewable/Reviewable#842]
While re-reviewing a file I have come across a comment and want to change the diff bounds to back to when I raised it.

This keeps focus on the comment I'm looking at, but because the new bounds make the diff count as a 'big diff' I can't see any context. So I have to scroll to the top of the file to click "Show Diff", losing my place.

I would like either a UI fix to this (bring the show diff button down next to the comment I am looking at, and refocus this comment after it has been clicked), or I imagine much easier would be the ability to show the large diff via a keyboard shortcut, and keep the comment in focus after doing so?

**Comment by pkaminski** [comment]
This actually sounds like a bug:  if the user explicitly requested a diff then we should force it through -- the failsafes are supposed to be there only for automatically selected diffs (and perhaps for ones batch-selected via the file matrix header).  Two clarifications:
1. Exactly how did you select the desired diff?  By clicking on the comment's corner label, or by directly manipulating the file's bounds in the revision cells?
2. What's the exact message that was showing at the top of the file?  There are many diff-suppressing conditions that look very similar so it would be good to know exactly which one we hit in this case.

Thanks!

**Comment by gilbertbw** [comment]
Ah I see. In that case yes, it looks like a bug.

1. I have checked and get the same behaviour with both methods.
2. The message I get is "This diff is pretty big, and showing it will slow things down." 

I have a pretty hacky workaround for the time being, I can click the "Show diff" button, then copy the discussion ID from the URL and find it by searching in dev tools > elements.

**Comment by pkaminski** [comment]
This should be fixed now and, barring any regressions, will make it into the next Enterprise build.  Thanks for the report!
