### ISSUE TITLE
Linking to discussion not working

### ISSUE THREAD

**Issue by gilbertbw** [Reviewable/Reviewable#845]
In a very large review I am looking at if I:

1. click into a discussion (not linked to file/code)
2. copy the URL
3. open a new tab
4. paste in the URL

The discussion is not brought into focus.

It seems to work OK with smaller reviews.

**Comment by pkaminski** [comment]
Sounds like a race condition of some sort -- I'll look into it.  Can you give me a rough idea of the review size at which it stops working?  Thanks.

**Comment by gilbertbw** [comment]
Hi Piotr, 

Unfortunately there is a big variance between where I can and can't reproduce this behaviour (we have one outlier very large review):
- on a PR changing 8 files, (+482 −295 lines) it works OK.
- on a PR changing 129 files + 7 obsolete (+33,660 −20,047 lines) it does not work.

It seems to be only discussions not linked to files, inline discussions seem OK, but I may just be getting lucky if it's non deterministic.

**Comment by cgiroux86** [comment]
Hey @gilbertbw, thanks for bringing this to our attention.  We've found a repro for it and are working to get to the bottom of what's happening.  Thanks for bearing with us!

**Comment by pkaminski** [comment]
This should be fixed on reviewable.io now and will make the next Enterprise release.
