### ISSUE TITLE
MP4 support in comments

### ISSUE THREAD

**Issue by Cellule** [Reviewable/Reviewable#847]
Github added support to mp4 recently and now I find myself in an awkward position when I want to upload an mp4 through reviewable (having to either revert back to gif or go back to github to upload it)

https://user-images.githubusercontent.com/4157103/125085213-50316f80-e098-11eb-9759-932d31639c6d.mp4

**Comment by pkaminski** [comment]
Hey @cgiroux86, can you take a look when you've got a moment?  Adding mp4 to the whitelist should be easy, but we also need to check 1) that it renders correctly in both GitHub and Reviewable, and 2) figure out what maximum file size to allow (ideally matching GitHub on this).

**Comment by cgiroux86** [comment]
Will do!

**Comment by cgiroux86** [comment]
@Cellule This is now live, with the caveat that Github will render it as a link (they are aggressive about stripping HTML).  You no longer need to jump through hurdles to upload your mp4/mov to Reviewable!  Let us know what you think :)

**Comment by Cellule** [comment]
I tested it and it works well. Sad that the inline preview doesn't work like Github, but I understand the technical limitation on that front.
It will still make it much easier to share mp4 during review.
Thanks for the quick turn around :D
