### ISSUE TITLE
SAML login error getting turned into 'out of quota', had to resort to inspect to see why it was failing

### ISSUE THREAD

**Issue by nneul** [Reviewable/Reviewable#849]
Fixing this was trivial - I just needed to log out and back in, but the UI didn't make it obvious till I inspected js console/network to see the errors. Please consider looking for a 403 response mentioning SAML and indicating triggering a prompt to re-login to github.

```
{
  "message": "Resource protected by organization SAML enforcement. You must grant your OAuth token access to this organization.",
  "documentation_url": "https://docs.github.com/articles/authenticating-to-a-github-organization-with-saml-single-sign-on/"
}
```

**Comment by nneul** [comment]
Additional headers in the response if they help any:

```
x-github-sso: required; url=https://github.com/orgs/ORGNAME/sso?authorization_request=AxxxxxxxxxxxxxxxxxxxQ
x-oauth-client-id: 7xxxxxxxxxxxxxxxxxxx5
x-oauth-scopes: read:org, repo, user:email
x-ratelimit-limit: 15000
x-ratelimit-remaining: 14861
x-ratelimit-reset: 1626134779
x-ratelimit-resource: core
x-ratelimit-used: 139
x-xss-protection: 0
```

at the very least, should not display a quota error if you can see from the ratelimit that it's not quota related.

**Comment by pkaminski** [comment]
That's odd, the central server-side error handler does a match on `SAML enforcement` in the error message for precisely this reason.  Can you tell me the exact error message Reviewable reported, and the context in which it occurred?  Thanks.

**Comment by nneul** [comment]
In the files section of the review (bottom of page), each file had no content, and only displayed:

(!) Sorry, you've run out of GitHub API quota. [Try Again] [Start a new discussion]

Clicking on try again or force page refresh had no effect on page content.

**Comment by pkaminski** [comment]
Ah, thanks.  Looks like the client-side error handler needs to be updated.

**Comment by pkaminski** [comment]
Should be fixed now, thanks for the report!
