### ISSUE TITLE
Matrix dropdown bunny icon didn't appear after scrolling down

### ISSUE THREAD

**Issue by mdevs5531** [Reviewable/Reviewable#85]
Noticed after scrolling down in a review that was just loaded the upper left corner just had the red seen icon and title, but no purple bunny to trigger the matrix dropdown.  Scrolling back up to the top of the page and scrolling down again cause it to appear.

Updated chrome on OS X, animations enabled.  Haven't been able to reproduce, will post a screenshot and details if I manage to.

**Comment by pkaminski** [comment]
I think this was a kind of race condition in the animation system when the animation "bounces" while part-way through.  I changed the code to be more explicit so it should be fixed now.  Please let me know if you spot it again.
