### ISSUE TITLE
Review completion condition: numUnresolvedDiscussions unexpected identifier (missing destructuring support)

### ISSUE THREAD

**Issue by Cellule** [Reviewable/Reviewable#853]
In the default example "All files reviewed and discussions resolved" I now see an error `numUnresolvedDiscussions unexpected identifier`
![image](https://user-images.githubusercontent.com/4157103/127522258-d654da01-a0ad-463b-99dc-b2eb163b9793.png)

Looks like it's a problem with destructuring. 
I'm guessing the code runs fine when evaled, but it looks weird when editing.

I confirmed destructuring is the issue because the following is fine
```js
// Commit file is a system file Reviewable composes for
// reviewing commit messages.
const numUnresolvedDiscussions = review.summary.numUnresolvedDiscussions;
const commitFileIsReviewed = review.summary.commitFileIsReviewed;
const numFiles = review.summary.numFiles;
const numUnreviewedFiles = review.summary.numUnreviewedFiles;
```

**Comment by pkaminski** [comment]
Huh, the code probably doesn't run fine when evaluated since it's the exact same environment.  :(  @cgiroux86 could you fix please?  Thanks.

**Comment by pkaminski** [comment]
Should be fixed!
