### ISSUE TITLE
Select-and-click quoting appears to be broken

### ISSUE THREAD

**Issue by jakebiesinger-storyhealth** [Reviewable/Reviewable#857]
Howdy!

Normally, I can select a region of code to quote by click-and-dragging over some code and then clicking again in the selected area. Unfortunately, this functionality seems to have gone away in a recent release. Instead, selecting an area opens the comment pane but without any quoted code.

https://user-images.githubusercontent.com/66106280/128727001-2cfdb5ac-3154-4231-9d5b-7ade8a2a62b2.mov

**Comment by pkaminski** [comment]
Sorry about that -- we're working on some big improvements to this feature but managed to regress in the meantime.  😞  I'll get this fixed later today.

**Comment by pkaminski** [comment]
This should be fixed now!
