### ISSUE TITLE
File header missing from the top pane

### ISSUE THREAD

**Issue by mkow** [Reviewable/Reviewable#860]
Since ~this/last week I stopped seeing the filename + diff range for the files I'm looking at:

![broken_top_bar](https://user-images.githubusercontent.com/5244565/129068135-133ef755-aca6-4981-890e-52c5238f65cb.png)

Normally they were right to the rabbit icon, but now they don't show up anymore.

I'm on Firefox 78.12.0esr (64-bit), on Debian.
Happy to help with debugging if needed :)

**Comment by jwnimmer-tri** [comment]
I've been seeing this also.  Firefox 90.0.2 on Ubuntu 18.04.

**Comment by pkaminski** [comment]
Yup, that's a regression -- reproduced.  @cgiroux86, any ideas what might have caused it? Maybe some of the recent styling changes?

**Comment by cgiroux86** [comment]
That's all that I can think of -- looking into it now.  Thanks for the heads up guys.

**Comment by cgiroux86** [comment]
Thanks again -- issue is resolved.

**Comment by mkow** [comment]
Yep, I confirm that it works again now. Thanks for fixing it!
