### ISSUE TITLE
Bug in commit matching

### ISSUE THREAD

**Issue by DamienCassou** [Reviewable/Reviewable#861]
In the following screenshot, Reviewable says that r3 is probably rebased from r2 but I would expect Reviewable to detect that r3 is rebased from r1 instead: the commit messages are exactly the same.

![2021-08-25-095436](https://user-images.githubusercontent.com/217543/130750361-1fa2a065-91c3-4ff4-8cb9-d53c45634ab3.png)

**Comment by DamienCassou** [comment]
The next revision is wrong as well:

![2021-08-25-095719](https://user-images.githubusercontent.com/217543/130750772-2a514928-25e9-40a2-99bb-8f91b8dc1a5a.png)

**Comment by pkaminski** [comment]
Thanks -- we tuned our heuristics to work better in this case (not retroactive, sorry).
