### ISSUE TITLE
Context help does not indicate defered reviews

### ISSUE THREAD

**Issue by gilbertbw** [Reviewable/Reviewable#864]
The context you get on the eye at the top of a file:
![image](https://user-images.githubusercontent.com/2099292/132213784-1c880318-c62e-4c2c-b980-a789e0d88ecd.png)

Does not indicate that one reason for getting the grey crossed through (not reviewed and marking not advised) eye is that the review is deferred. I think it should also link to the help here https://docs.reviewable.io/reviews.html#deferring-a-review.

**Comment by pkaminski** [comment]
Good catch!  I updated the popup help (will show up in the next push) and the docs.  Thanks!
