### ISSUE TITLE
Unable to paste images into comments

### ISSUE THREAD

**Issue by jackiescanlon** [Reviewable/Reviewable#865]
Previously I was able to paste images from the clipboard into Reviewable comments via Ctrl+V or via Right Click>Paste. Now when I do that nothing happens. There is no warning or error, it just doesn't upload the image like it usually does.

This first happened to my coworker last week (2021/09/02). When she reported the problem to me I tested it myself with no problems. However today (2021/09/07) I am now experiencing the same problem.

This is happening in Chrome (I tested using Chrome 93.0.4577.63 on Ubuntu 20.04) but not Firefox.

Troubleshooting we've already attempted:
1. Verifying that the paste works in other applications (i.e., its not our image or screenshot tool that isn't working properly)
2. Pasting into a different comment/Review (i.e., its reproducible for us)

**Comment by cgiroux86** [comment]
Hey @jackiescanlon, thanks for letting us know!  A few questions to help us get to the bottom of things:
1) Are you and your coworker using the same version of Chrome?  Are both of you using Ubuntu?
2) Is it happening in every review now or intermittently?
3) Are there any other updates to your environment that you think could possibly be relevant?

We aren't able to produce a repro on our end of as of yet, but we're working on it -- thanks :)

**Comment by jackiescanlon** [comment]
Thanks @cgiroux86,

1. Negative, my coworker is using 92.0.4515.131. We are both using Ubuntu 20.04.
2. Happening in every review now.
3. I did update chrome recently, I think within the past week. I can't think of any other updates or changes I've done.

Thank you!

**Comment by cgiroux86** [comment]
Thanks for the quick reply @jackiescanlon.  One more question, did you happen to check the console to see if there were any errors when pasting an image?

**Comment by jackiescanlon** [comment]
Actually I did @cgiroux86, but I didn't see anything when I pasted the image.

However, I want to let you know I just realized that I also cannot paste images into Github comments either! Sounds like it might be a Github issue instead that's being manifested into Reviewable. I've submitted a bug report to Github.

I'll report back here if there's any resolution. In the meantime if you'd prefer to close this ticket that's fine with me.

Thanks!
Jackie

**Comment by jackiescanlon** [comment]
Github support got back to me letting me know its an issue with Chromium; the Chromium team has issued a workaround solution:

https://meta.stackoverflow.com/questions/411266/pasting-images-from-the-clipboard-doesnt-seem-to-work-anymore-on-chrome-for-lin/411569#411569

Thanks for your support @cgiroux86 !
