### ISSUE TITLE
Broken keyboard navigation in comment writing textarea

### ISSUE THREAD

**Issue by mkow** [Reviewable/Reviewable#869]
A new bug triggered for me today: If I paste the following:

```
asdf
\```
1234
\```
asdf
```

_(but: you'll need to remove the two backslashes, I didn't manage to escape the backticks properly in GitHub's Markdown)_

into a newly started discussion using Ctrl+V, and then try to change the text cursor position (either via arrow keys or via mouse) then won't work, the cursor just stays on the last line and can't "cross" the code block. Interestingly, Ctrl+Home allows me to "cross" "the border", but then I can't go back. It seems that the cursor just can't end up inside the code block for some reason.

**Comment by pkaminski** [comment]
I'm not able to repro this in either a top-level or line discussion.  The draft field is just a plain `textarea` and we don't have any code to parse code blocks so I'd be very surprised if Reviewable is responsible for what you're seeing.  Perhaps Tribute (the autocompletion library) is going crazy for some reason, as it does need to take over cursor input when there's a popup?  But even so, I don't see how/why it would block mouse clicks.

What browser/OS are you seeing this on?  Does it repro on any review, say the [Reviewable demo](https://reviewable.io/reviews/reviewable/demo/1) one?  Any chance you can record a short video so we can see the exact details of how this happens?

Thanks.

**Comment by pkaminski** [comment]
This reproduces only in Firefox, in both v78 on Linux and v93 on Windows.  Seems like a Firefox bug but if so it's an old one!  Investigating.

**Comment by pkaminski** [comment]
In fact, it appears that creating a new discussion makes the cursor stuck on the current line in all comment text areas.  Replying to an existing discussion works fine until you create a new one, then it breaks too.

**Comment by pkaminski** [comment]
Apologies, I introduced a bug in the PR that left a `user-select: none` on the `textarea`.  Apparently Chrome ignored it, but Firefox did... something... in response.  Fixed now, I believe!

**Comment by mkow** [comment]
I confirm that it's fixed now. Thanks!
