### ISSUE TITLE
Detect source language from shebang

### ISSUE THREAD

**Issue by mkow** [Reviewable/Reviewable#870]
Feature idea: In our project we sometimes have executable unix scripts without extensions, but with shebangs. Currently Reviewable can't detect the language in such files, and doesn't use any syntax highlighting when reviewing these.

Would be nice to have this for the most popular scripting languages (Bash, Python, etc.). I think this doesn't require any heuristic, just a 1-1 mapping (modulo some quirks, like `#!/usr/bin/python` vs `#!/usr/bin/python3` vs `#!/usr/bin/env python` vs `#!/usr/bin/env python3` etc).

What do you think?

**Comment by pkaminski** [comment]
Yeah, we could add that in pretty easily.  Just use a regex like `^#!(?:\/bin/|\/usr\/bin/|\/usr\/bin\/env )(\w+)` to extract the binary name and look it up in a table, plus log anything we don't recognize for analysis.  I think filename should still take priority but if there's no match we can fall back on file contents.

@cgiroux86, this isn't directly related to what you're working on right now but it's also in `diff_worker.js` -- wanna throw it in at some point, at your convenience?

**Comment by mkow** [comment]
> I think filename should still take priority but if there's no match we can fall back on file contents.

Yup, makes sense IMO :)

**Comment by pkaminski** [comment]
Pushed with a few languages in the table.  We'll monitor lookup misses and add more as needed.

**Comment by mkow** [comment]
Works for me, at least for Python. Thanks!
