### ISSUE TITLE
New Reviews have stopped appearing on the dashboard

### ISSUE THREAD

**Issue by benbelow** [Reviewable/Reviewable#877]
As of this morning, I've noticed that new PR's I'm added to as a reviewer are not showing on my dashboard. 

I can access them via the link from the Github Reviewable link (and after commenting from this link, they then appear on the dashboard) - but I rely on the review dashaboard to manage my personal review workflow, and rely on the review appearing there in a timely manner. 

I've checked that the repositories are connected to reviewable (they are), and the dashboard correctly shows "1 open review" for the latest repo with a PR 

![image](https://user-images.githubusercontent.com/8653532/136374743-44b9678b-e4cd-49c8-931e-7df354f2f69b.png)

but clicking through shows me no reviews: 

![image](https://user-images.githubusercontent.com/8653532/136374785-aef283a4-d7e2-4c1c-a129-dabadf0addd9.png)

in addition to them not showing on my dashboard. 

![image](https://user-images.githubusercontent.com/8653532/136374831-afb7b980-efbd-4988-bc98-b58734d4f820.png)
 
This option is set.

**Comment by pkaminski** [comment]
This appears to be a widespread GitHub issue; it seems likely that their issue/PR indexing broke.  Try visiting https://github.com/pulls and doing various searches, especially for `is:open is:pr involves:<username>` — at least for me, these don't bring up any recent PRs.  If that's the case for you as well then there's no workaround possible, we just have to wait until GitHub fixes it.  😢
