### ISSUE TITLE
Changes from a rebase+sqash+amend are sometimes classified as `base commit changes`

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#88]
In https://reviewable.io/reviews/servo/servo/5725 the author addressed review comments while rebasing, squashed the results, and force pushed. Various changes that were part of the new commit were marked as `base commit changes` in the review (see the addition of the new function handle_mouse_event in script_task.rs).

**Comment by pkaminski** [comment]
Thanks for the repro.  A bit busy today and tomorrow, but will investigate ASAP.

**Comment by pkaminski** [comment]
Apologies, there were some mangled offsets in the base delta computation code.  Should be fixed now, and at least the specific case you call out above is handled correctly.  Please poke around and let me know if you see any other discrepancies -- thanks!

**Comment by jdm** [comment]
Thanks for fixing it so quickly :)
