### ISSUE TITLE
Feature Req: Reviews done on GH should register in Reviewable

### ISSUE THREAD

**Issue by mal** [Reviewable/Reviewable#880]
Some people love Reviewable, some people prefer GitHub, in order for PR checks like `code-review/reviewable` to pass it would be nice if Reviewable could recognise when a review has been done in GitHub and update this status.

Right now it seems like a very all or nothing proposal which can create needless friction between opinionated dev teams. Allowing developers within the same team to use the tool that works best for them would be very useful.

This would also help developers unable or unwilling (due to conflicting contracts or otherwise) to grant Reviewable permission to act on their behalf across all of GitHub.

**Comment by pkaminski** [comment]
Hey Mal, I feel your pain.  There's already a related setting in Reviewable (in the repo config panel) where you can tell it to only create a status check for a PR once a review has been visited by someone.  This works well as long as your `code-review/reviewable`  status check is not required, since a missing check wouldn't block merging.  Does that work for you?

An alternative would be to have the status check required but expose the "review visited" flag to the custom completion condition so you could decide whether that warrants marking the review as "complete" yourself.  It's a bit more obfuscated than the approach above, though.  But perhaps there's a reason this might work better for you?

Let me know.

**Comment by mal** [comment]
Thanks for the suggestions Piotr. Unfortunately, at least in my team's case, the former is pretty much a non-starter without a viable alternative to PR guarding. We could conceivably switch to require review approvals in GH's own review system, but that would require Reviewable to push approval state on behalf of reviewers. I found some old issues that appeared to discuss that, but they don't appear to have lead anywhere? It does seem like it may be possible using https://docs.github.com/en/rest/reference/pulls#create-a-review-for-a-pull-request, but perhaps there's other reasons it's not viable?

As to the latter suggestion, for the same kinds of reasons a review simply by visiting also wouldn't pass muster I'm afraid. It does seem that GH is capable of emitting [`PullRequestReviewEvent`](https://docs.github.com/en/developers/webhooks-and-events/events/github-event-types#pullrequestreviewevent) which provides in its payload the `state` which could be used for Reviewable to see when a GH review has been submitted with [`state: APPROVED`](https://docs.github.com/en/rest/reference/pulls#list-reviews-for-a-pull-request--code-samples). This could be verified either by a reviewer whitelist within Reviewable settings, or by asking those that prefer to review via GitHub to grant read-only access to Team information, which could be enough to verify the review validity without requiring the same breadth of access as using Reviewable wholesale.

Thanks for the response. 🙂

**Comment by pkaminski** [comment]
Hmm, I guess I'm confused as to what you're looking for then.  Reviewable does integrate with GitHub's PR approval system by default: when publishing your comments, you can also pick whether to approve or block the PR (and a reasonable default is selected for you based on your current dispositions in discussions).  You should be able to turn on required reviews in your GitHub branch protection settings and turn off the requirement for the `code-review/reviewable` status check as long as you're not doing anything fancy with your completion condition that you want to enforce.

You also have access to GH approval information in your completion condition; look in `review.pullRequest.approvals`.  Note that those will reflect approvals posted either from GitHub or from Reviewable.  You could hardcode a list of "grumpy teammates" into your condition if that would be helpful, as I don't think it'll be practical for us to request a special auth just from them.

Does any of that help?  If not, can you explain some more exactly when you want PRs to be approved in different scenarios?  Thanks.

**Comment by mal** [comment]
Interesting, at the moment when we sign off in Reviewable a comment with a LGTM message gets attached to the PR, but no formal review which is what the GH rule would be looking for. Perhaps it's a case of digging around a bit more in the configuration options, but if we can get to that point it would certainly seem to be viable from your explanation.

As to the completion conditions I suspect it was really me that was confused! 😅 I'll be looking into this approach on Monday as it seems like it could be the most frictionless path for us. Really appreciate you taking the time and putting up with my ignorance in the face of features that from you descriptions you already have in place! Very embarrassing! /o\

**Comment by pkaminski** [comment]
Hey Mal -- no worries, always happy to help!  There's a lot of features there and they're not always easy to find. Let me know if things don't end up working out and we can reopen the issue.  Good luck!
