### ISSUE TITLE
Automatic disposition for "typo" discussions

### ISSUE THREAD

**Issue by jwnimmer-tri** [Reviewable/Reviewable#885]
Under [Checking and changing dispositions](https://docs.reviewable.io/discussions.html#checking-and-changing-dispositions), we have:
- Minor or Nit → Discussing

I assume we don't want to get _too_ carried away here, but I wonder if it's worthwhile to also recognize "Typo" as a keyword akin to "Nit"?  In my team's reviews, it's [frequent](https://github.com/RobotLocomotion/drake/pull/16111#pullrequestreview-811447964) to comment either just `typo` on a line of code with a typo (usually happens within comments in the code), or `typo $misspelledword` to specify to which one.  Having the author reply "Done" for these isn't terribly useful.

This might be less important with #671 on the way, and of course we can try to teach / remind reviews to post `nit typo $misspelledword` by habit, but maybe the review tool's default here could be improved.

**Comment by pkaminski** [comment]
Good idea, it'll go out in the next release!
