### ISSUE TITLE
Ability to opt-out certain drafts from publication

### ISSUE THREAD

**Issue by jwnimmer-tri** [Reviewable/Reviewable#892]
In cases where I'm spending a lot of time on a single in-depth review, as I'm going through the code I'll often make notes to myself like "Working -- come back here to consider whether all of the error conditions are handled".  Those discussions end up mingling with the more typical blocking / informing discussions that are directed to the author.

In some cases, I will circle back to those and do my diligence prior to publishing my comments -- either reworking them into an actual blocking discussion for something that got missed, or just deleting the draft if everything was fine.  This workflow is already well-supported.

In other cases, sometimes I will publish my review even with some of those comments intact.  They remain as red bubbles for me ("Working"), and therefore I will be guided revisit them later.  But if the author happens to have any useful guidance that relates to those topics, they will be able to weigh in and possibly save me some time.  This workflow is already well-supported.

However, in the more difficult reviews, I often find myself wanting one other workflow that is not yet supported.  What I'd like to be able to do is to mark some of those working drafts as "opt-out of publishing" so that when I publish my review checkpoint, the comment is not posted to GitHub at all -- it stays as a local-only draft.  That would allow me to keep margin notes for my unfinished thoughts, without needing to word-smith them in a way that other review participants would need to understand or interact with.  For drafts in this state, I'd like it to be sticky so that I can continue along replying to other open threads, and never accidentally post my margin notes.  Once I've reworked the comment to be ready for others to see, I'd opt-in to publishing that discussion again at which point the green button would post it as usual.

For now, the workaround I've been using is to copy-paste-delete them into a separate document in order to withhold them when I want to post, but that is awkward for anything more than one or two discussions, and tends to lose the line number correlation.

**Comment by pkaminski** [comment]
I like this idea and it aligns well with my own experience; my only concern is the incremental complexity this will add to the draft view, which already has a lot of controls.  Perhaps it would make sense to treat it as a new kind of disposition, like "Holding" or "Preparing".  That would keep the option out of the way, and would also fit nicely into adding some prefixes to trigger the state, like "maybe" or "???".  (The name and prefix would need some more workshopping, obviously.)

**Comment by jwnimmer-tri** [comment]
Yes, I was also imagining this a disposition state.

I don't have any great ideas for the name for this disposition.  I guess "Preparing" is nice.  For "Holding", possibly that would be mistaken as in "Holding up" to block the PR, though this disposition would not do so.  Maybe "Local" or "Private"?

I do like `???` for the magic keyword.

**Comment by sherm1** [comment]
:+1: 
I like "Private" for the disposition -- I think that nicely captures the intent. "Private" would also make a good magic keyword IMO (perhaps with "???" as a synonym).

**Comment by pkaminski** [comment]
How about simply "Drafting" for the disposition?  Magic keyword would be just "???", plus any more good ones we come up with now or later.  (I'm not loving "private" since it could also be referring to a private communication with one other participant, in contrast with publishing a message visible to all reviewers.)

**Comment by sherm1** [comment]
Sounds good. "Draft" would make a good magic keyword also in that case.

**Comment by jwnimmer-tri** [comment]
I'm fine with whatever names.  I was avoiding "Drafting" because in some sense, _all_ discussion drafts are undergoing drafting -- I was trying to keep separate terms for "a draft" (an unpublished comment, but which will be published) vs "a scribble" (a comment that will not be published).  But at some point, a single word can carry only so much weight, and we'll just need to refer people to documentation to understand the semantics.

**Comment by DamrongGuoy** [comment]
This would help me with reviewing a very long PR. :+1:

**Comment by pkaminski** [comment]
Heh, I try to get names right because they strongly influence initial understanding of a feature and changing them later is a major pain.  How about "Considering" , "Contemplating" or "Pondering"?

I think I'm also going to lift reviews with pending drafts up to the "Working on it" section on the dashboard, unless they're already in the "Awaiting my action" section.

**Comment by jwnimmer-tri** [comment]
I like "Contemplating" or "Pondering" as to me they imply a more inward focus.

In my team's local lingo, we use "nit Consider" often in the sense of "Could" from [MoSCoW](https://careerswitchtocoding.com/blog/moscow-the-best-code-review-technique-youre-not-using), so it would be a bit overloaded (for us) to use it for the scribble's disposition.

**Comment by sherm1** [comment]
I can see the "Pondering" disposition now and can select it manually but the "???" magic isn't working for me (stays "Blocking").

**Comment by pkaminski** [comment]
Argh, the curse of the regex strikes again.  Fixed!

**Comment by sherm1** [comment]
Works now, thanks Piotr!

**Comment by jwnimmer-tri** [comment]
Seemingly concurrently with new feature, the little "publish just this one discussion" button on its own in the lower right of the discussion box no longer seems to be operative.

When mousing over it, the cursor remains an arrow -- it does not turn into a finger.  Clicking it doesn't do anything.

This is with FF 96.0 on Ubuntu 20.

![image](https://user-images.githubusercontent.com/17596505/149599191-c10a94b6-ac32-43a6-83e2-15a6143a3a19.png)

**Comment by pkaminski** [comment]
Wow, I was really distracted that day: I messed up the boolean that was supposed to prevent Pondering messages from being sent ad-hoc.  Thanks -- fixed.
