### ISSUE TITLE
Can't acknowledge an issue and write a comment

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#90]
Sometimes it would be nice to comment on an open issue, but acknowledge it as addressed simultaneously. I haven't figured out how to do that.

**Comment by pkaminski** [comment]
There's purposely no way to do that.  Acknowledging an issue will usually resolve it, and would then leave the other person with no notification of a new comment.  This is the price for streamlining read / resolve flags into a single shared one, which I still think is the right thing to do for fine-grained discussions (as opposed to, e.g., coarse-grained GitHub issues, which rightly keep the flags separate).
