### ISSUE TITLE
Reverse comment iteration

### ISSUE THREAD

**Issue by mkow** [Reviewable/Reviewable#900]
Sometimes I click once too many on the top pane navigation buttons ("next unanswered discussion" and "next draft comment") and skip a comment which I wanted to answer. Right now I just search for it with <kbd>PgUp</kbd>, but this method works pretty bad on large reviews.

Feature idea: would be nice if I could just <kbd>Shift</kbd>-click the navigation button to reverse the iteration order, allowing me to go back.

**Comment by schreter** [comment]
+1 :-)

**Comment by pkaminski** [comment]
That's a neat idea and should be easy to implement.  @cgiroux86, could you take a look at some point?  I believe we already have a service that reports currently pressed modifier keys.

**Comment by cgiroux86** [comment]
This is now live -- please let us know if you have any issues.

**Comment by mkow** [comment]
Just tested it and works great, thank you!

**Comment by schreter** [comment]
@cgiroux86 

> This is now live -- please let us know if you have any issues.

Uhm, probably not in Enterprise version (just tried to pull and there was no change since at least 3 weeks).

**Comment by pkaminski** [comment]
I'll be cutting a new release soon, but yeah, expect Enterprise to be 2-4 weeks behind any feature drops.
