### ISSUE TITLE
Auto-merge warning on Approval

### ISSUE THREAD

**Issue by Cellule** [Reviewable/Reviewable#904]
When the github auto-merge setting is enabled
![image](https://user-images.githubusercontent.com/4157103/157118603-1f417588-3028-4a01-8304-b5d80250a8a2.png)

If the current pull request is marked as auto-merge, approving the PR has the effect of merging the PR which the approver might not be aware.
Sometimes you want to approve with nits/minor items that doesn't need to be addressed but want at the very least acknowledgment from the author before merge.

Would be nice to have a warning upon approval that auto-merge is enabled on the Pull Request so the approver can take action (maybe even allow to disable auto-merge before approving ?)

**Comment by pkaminski** [comment]
Agreed, we need to do something here.  At a minimum we should be able to detect when auto-merge is enabled for a PR, extrapolate whether publishing will trigger it, and if so change the button to "Publish & auto-merge".  To prevent merging you can always do something to block the review from completing, depending on your completion condition.

Ideally, we'd also offer an auto-merge toggle like GitHub does.  This is easy from an API standpoint but it's not clear where we could fit the UI.  Perhaps replace the disabled Publish button with an auto-merge toggle with a dropdown like the merge button has?

**Comment by Cellule** [comment]
Yes I'm slowly changing my review style to block more especially when auto merge is enabled, however I have to remember to check in github prior to start the review in reviewable to guide how I will review.

Ideally we'd enable auto-merge only when a PR is approved and the auto merge would be for pending CI checks, but that falls out of scope from reviewable.

**Comment by pkaminski** [comment]
Actually, after digging into this some more I think that determining whether auto-merge will be activated on publish is too hard.  We'd need to be able to emulate all of GitHub's branch protection options in Reviewable to figure out if the new state will satisfy them, including things like code owners, which would require parsing files that aren't part of the review...  We'd also need to prospectively evaluate any custom completion condition, and while such evaluation is reasonably cheap it's not so cheap that we can do it on every potentially relevant change.

It may be that the best we can do here is to have some ambient indicator of whether auto-merge is set for the PR.

**Comment by Cellule** [comment]
I think just knowing that auto-merge is enabled would be enough without needing to know if the approval is the last step to actually trigger the merge

**Comment by Cellule** [comment]
I just saw this live, this is perfect thank you so much !
![image](https://user-images.githubusercontent.com/4157103/188641165-7b453b22-7c1b-467e-b183-5aef750c723b.png)
