### ISSUE TITLE
Linking to discussion - show diff not showing discussion

### ISSUE THREAD

**Issue by gilbertbw** [Reviewable/Reviewable#906]
I am having a similar issue to #845 but with inline comments on large diffs.

When I:

1. click into a discussion within a file (that has a large diff)
2. copy the URL
3. open a new tab
4. paste in the URL
5. The discussion is brought into focus, but the file is not visible and I get the "This diff is pretty big, and showing it will slow things down." message.
6. Clicking "Show Diff" shows the diff, but keeps the view at the top of the file, it does not take me to the comment I want to link to.

**Comment by pkaminski** [comment]
Thanks!  IIUC, the issue is that forcing a large diff doesn't keep the focused discussion in view, is that right?

**Comment by gilbertbw** [comment]
Yes, that's correct.
