### ISSUE TITLE
Bulk updating review completion condition

### ISSUE THREAD

**Issue by gilbertbw** [Reviewable/Reviewable#908]
We are trying to apply our Review completion condition to all our repositories. When clicking Apply to all repositories, The review completion condition, or at least the webhook, is not applied to the other repositories.

When looking at one of the other repositories the review completion condition appears to be there:
![image](https://user-images.githubusercontent.com/2099292/159026207-4836f109-d376-4d50-a1cf-ddc034bcb955.png)

But if I click into it the condition disappears:
![image](https://user-images.githubusercontent.com/2099292/159026275-09f4098e-9340-4100-b98a-2dabb381847d.png)

**Comment by pkaminski** [comment]
Thanks for the report, but I cannot reproduce it so far.  First, let's clarify what you're doing:
1. Open settings for repo A.
2. Edit the completion condition.
3. Click the dropdown arrow on the Apply button.
4. Check another repo B.
5. Click Apply to 2 repos.
6. Open settings for repo A (or is it B?) and fail to see the updated completion condition.

Any corrections to the above?

Also, are you on reviewable.io or on Enterprise, and if the latter then which version (shown in the Support dropdown)?

Thanks.

**Comment by gilbertbw** [comment]
This is what I was doing:
* Open settings for repo A.
* Click the dropdown arrow on the Apply button. (the condition in repo A was already correct)
* Check another repo B.
* Click Apply to 2 repos.
* Open settings for repo B and see the updated completion condition.
![image](https://user-images.githubusercontent.com/2099292/159026207-4836f109-d376-4d50-a1cf-ddc034bcb955.png)
* if I click into it the condition (still in repository B), it disappears:
![image](https://user-images.githubusercontent.com/2099292/159026275-09f4098e-9340-4100-b98a-2dabb381847d.png)

Editing the completion condition before applying (your step 2) seems to work correctly.

**Comment by pkaminski** [comment]
Got it!  Thanks -- fixed.
