### ISSUE TITLE
Line link in review comments points at master revision

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#91]
It should point at revisions under review instead, I believe - the lines under review in https://reviewable.io/reviews/servo/servo/5899 don't exist in master.

**Comment by pkaminski** [comment]
A comment will be automatically mapped to the nearest possible line in every revision, so there's no need to link to a specific diff range.  If the lines don't exist, though, the mapped location might not be very useful, which is probably what you're seeing.  In those cases, the comment's revision label (top-right corner) will normally turn red, depending on how bad the mapping's quality is.  You can always click on the corner label to switch (one side of) the diff to the comment's original one.  I could make this happen automatically when following a comment link too, but it's not clear to me whether picking an arbitrary diff bound would be more or less confusing than leaving it at the default [last seen, latest] range that you get when loading the page without a comment focused.  Thoughts?

**Comment by jdm** [comment]
There's a comment in closeevent.rs with a non-red corner link, but the file is added in the PR. The corner links are black magic to me, as I never know what to expect if I try clicking then.

**Comment by pkaminski** [comment]
Could you provide a link to the specific comment please (clicking on the comment will update the URL in the address bar), and let me know at which revision bounds (left and right) you're seeing the unexpected behavior?  Thanks.

The corner links will just change the diff bounds in the minimal possible way such that the comment can be displayed in its original context (unmapped).

**Comment by jdm** [comment]
https://reviewable.io/reviews/servo/servo/5899#-JoA02X36gSpHCxCafSC is one that links to a file that doesn't exist in master.
https://reviewable.io/reviews/servo/servo/5899#-Jo9vry-dy8sZ_2pYdDj is one that links to a line that doesn't exist in master.

**Comment by pkaminski** [comment]
Ah, I had managed to completely misread your comment -- sorry, I get it now.  I'll see if it's fixable.

**Comment by pkaminski** [comment]
Arrgh, this was always meant to work the way you describe, but a bug prevented the link from being formed correctly.  Fixed.
