### ISSUE TITLE
Top-level @mention comments are (again) no longer moving reviews into the "Involving Me" section.

### ISSUE THREAD

**Issue by nate-thirdwave** [Reviewable/Reviewable#913]
Re-breakage of #636 possibly?

I'm observing this problem again with the current version of reviewable and new PRs. I'm not sure when it started happening again though, since the "working" condition feels very natural.

**Comment by cgiroux86** [comment]
Hey @nate-thirdwave would you mind sending me a relevant comment that isn't moving the review to the "involving me" section? I'm having a hard time repro'ing this one -- thanks!

**Comment by nate-thirdwave** [comment]
![image](https://user-images.githubusercontent.com/96086763/162297408-c322d7b5-c026-4af0-b6a8-6e2b1010473e.png)

Redacted picture of interaction

**Comment by cgiroux86** [comment]
@nate-thirdwave Thanks, should be fixed now!
