### ISSUE TITLE
Disposition dropdown menu is obscured by another comment thread

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#914]
Some z-indices are off.
![screen](https://user-images.githubusercontent.com/5643138/162245748-49a89429-a8e8-408a-b939-a44a57238e71.png)

**Comment by pkaminski** [comment]
Thanks -- this is really hard to repro, though, as it works the vast majority of the time.  I suspect it depends on the (invisible) underlying structure of the diff blocks.  Have you found a spot where it repros consistently by any chance?

**Comment by feldgendler** [comment]
Something has changed in that PR, and it doesn't reproduce there anymore. What should I do if I find such a situation? Dump the entire DOM tree?

**Comment by pkaminski** [comment]
Yeah, dumping the DOM tree is about the only thing that might help us track this down I think.  Please also make note of the ID of the current discussion, as shown in the address bar.  Thanks!
