### ISSUE TITLE
"$USER is blocking this review" should be inspectable

### ISSUE THREAD

**Issue by fahhem** [Reviewable/Reviewable#915]
The workflow requested is for when user Alice has commented on a review for Bob (or anything else that might block the review) and then gone on vacation, that Bob or Carol can view the review, inspect why Alice is blocking the review, then unblock the review by dismissing comments, etc.

Currently, they have to look over the whole PR looking for unresolved code comments, file comments, or PR comments and dismiss them.

Cherry on-top: The "$USER" in the message should be a link to "why they block the review" instead of to github, since users intuitively click that.

**Comment by pkaminski** [comment]
We now have a "dismiss from all unresolved discussions" feature in the participants panel.  Short of anything custom completion conditions might do, blocking discussions is pretty much the only way for a user to block a review, so I think this issue has been addressed.  (Users can also set a review-level blocking sanction, but that's pretty obvious and can already be dismissed via GitHub.  We'll add a built-in way to do so at some point too.)

Agreed @fahhem?

**Comment by fahhem** [comment]
Specifically this:
![image](https://user-images.githubusercontent.com/306100/217092845-bf273988-483b-4a8d-b2a6-77c94ce836af.png)


Yeah, looks good, I'll close and tell the requestors!
