### ISSUE TITLE
Underscores in filenames should be escaped when cross-posting to GitHub

### ISSUE THREAD

**Issue by seansfkelley** [Reviewable/Reviewable#916]
In some projects I work on, tests are idiomatically kept in `__tests__` directories. When Reviewable cross-posts comments on test files to GitHub, the GitHub comment shows that part of the file path as bolded instead of having underscores.

**Comment by pkaminski** [comment]
Hah, indeed!  Fixed.

**Comment by seansfkelley** [comment]
I see the fix, thanks for the quick turnaround!
