### ISSUE TITLE
'end' key will jump to the end of a webpage when used in editing a comment on OSX/Chrome

### ISSUE THREAD

**Issue by jbuck-zoox** [Reviewable/Reviewable#920]
When I am adding a comment, as I edit around, I will hit the 'end' key to go to the end of a line, but it instead goes to the end of the whole webpage.

**Comment by pkaminski** [comment]
@cgiroux86 please take a look.

**Comment by pkaminski** [comment]
This is normal behavior on Macs, and matches what GitHub does (even though some other apps override it).  Given the general mess in this area we're not going to stick our neck out and match GitHub's behavior.

Note that you can override the behavior system-wide with a configuration file if you'd like, though:  https://apple.stackexchange.com/questions/16135/remap-home-and-end-to-beginning-and-end-of-line
