### ISSUE TITLE
Allow reading historical reviews from archived repos

### ISSUE THREAD

**Issue by mkow** [Reviewable/Reviewable#923]
It would be good to be able to read old reviews from archived repositories. Right now trying to do so results in the following error: "Unable to create review: Repository <repo name> archived, ignoring sync".

Btw.: there's a similar issue already (https://github.com/Reviewable/Reviewable/issues/747), but I think that one is about connecting or disconnecting an archived repo, not about repos which were already connected prior to being archived.

**Comment by pkaminski** [comment]
Good point, should be fixed now.

**Comment by mkow** [comment]
I tested it and it works now, thanks!
