### ISSUE TITLE
Code suggestions: Allow easier creation

### ISSUE THREAD

**Issue by VojtaStanek** [Reviewable/Reviewable#925]
Hi!

Thanks for making reviewable, we are using it and loving it! The feature I have missed there for a long time was adding code suggestions - and you have added it! (issue #671)

We find the creation of suggestions a bit cumbersome - especially compared to GitHub, where it's just a click of a button. I would love to see it similarly in reviewable: To have a button in the draft which would add a code suggestion for the line.

It would be helpful for example to show typos in the reviewed code.

**Comment by earlAchromatic** [comment]
Here is the current plan for a more explicit code suggestion creation workflow: 

A new code block created inside of a comment draft defaults to an empty state. The code block will have a new button, 'select lines', which when clicked will impose line selection handles on the diff viewer that immediately surround the current line. These handles can be manipulated to encompass the selection of code that the user wants to capture for their suggestion on a line by line basis.

The selected lines are not added to the code block until the user clicks the button again. The button text will have changed to 'confirm line selection' after the initial click. Once the user confirms the selection, it is added to the code block. 

By making the default selection the current line, we allow the user to double click the button to rapidly add the current line to the new code block while leaving the option to select and add multiple lines. Once the selection is added to the code block, the code block becomes a Quote/Suggestion.

As @pkaminski mentioned above, you will still be able to make a new Quote/Suggestion by selecting the text first and clicking, as an alternative path.

**Comment by earlAchromatic** [comment]
Here is a mock up of the line selection handles:

![Line Selection Sketch](https://user-images.githubusercontent.com/68669571/172485383-21c12e71-26ee-4981-923b-b451610e8723.png)

**Comment by VojtaStanek** [comment]
@earlAchromatic I like it - this is what I want! 😄 Thanks!

**Comment by earlAchromatic** [comment]
@VojtaStanek This feature is now live on SaaS if you want to check it out! Enterprise releases usually happen a few weeks after SaaS releases if that is what you are using.
