### ISSUE TITLE
Reverse comment iteration sometimes picks a wrong comment

### ISSUE THREAD

**Issue by mkow** [Reviewable/Reviewable#928]
This is about this feature: https://github.com/Reviewable/Reviewable/issues/900.
I just noticed a small bug in it which I missed initially: If you have multiple comments in two files and you're in "one file diff at once" mode (aka "don't burn down my CPU") and you're at the first comment in the second file, then reverse iteration moves you back to the first comment in the previous file, not the last one.

**Comment by pkaminski** [comment]
Good catch.  I put in a quick fix, though admittedly without testing -- please give it a try.

**Comment by mkow** [comment]
Yup, works correctly now, thanks!
