### ISSUE TITLE
Acknowledge buttons are missing for issues that don't require a response

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#93]
When I have left an issue that must be addressed but is later addressed by changes elsewhere, it's frustrating to require the PR author to write a comment just so I can mark it resolved.

**Comment by pkaminski** [comment]
When you're the only commenter on a discussion, you should be able to resolve it outright with the round checkmark button in the lower-right corner:
![image](https://cloud.githubusercontent.com/assets/1646896/7460059/381394c4-f255-11e4-820a-fecdde224693.png)
Do you get this button?  If not, can you point me to the discussion you'd like to close so I can investigate?  Thanks.

**Comment by jdm** [comment]
All of my open issues on the left side of https://reviewable.io/reviews/servo/servo/5800 are missing `Done` buttons.

**Comment by pkaminski** [comment]
You're not looking for a `Done` button, but the round checkmark button in the lower-right corner of a thread.  Can you share a screenshot of what one of those comments looks like for you?  (Different users will see a different UI, depending on the authorship of the PR and the comment.)

**Comment by jdm** [comment]
I've used the checkmark button before, and it's not there. Screenshot coming up.

**Comment by jdm** [comment]
![screen shot 2015-05-04 at 3 20 08 pm](https://cloud.githubusercontent.com/assets/27658/7460452/1e801e3a-f271-11e4-98bd-1ede2fed5366.png)

**Comment by pkaminski** [comment]
Ah, OK.  In this case, since another user is involved in the discussion thread, there's no way to resolve it without their acknowledgement.  This is on purpose, so that the discussion doesn't "disappear" (get resolved) without the other person having seen your comment.  There's no need for them to write a comment, though: they can just acknowledge and the discussion will be closed.
