### ISSUE TITLE
Add support for hiding/folding code

### ISSUE THREAD

**Issue by dmcconachie-tri** [Reviewable/Reviewable#933]
Right now the user can expand the view of the code to include extra lines, but there is no way to undo that without reloading the window (that I know of). Being able to collapse would be useful both for hiding previous expanded code that the user no longer wants to see, as well as hiding code that the reviewer is done reviewing. For example if there is a large file with multiple new functions, being able to visually collapse/fold/hide functions that the reviewer is done with could be very useful.

Relates to #414 with perhaps a different first and second step?
- Enable "undo-expand"
- Enable "undo-expand" to collapse/hide adjacent changes
- ...

**Comment by pkaminski** [comment]
I agree this would be useful, but as explained early on in #41 it's (perhaps surprisingly) really hard to implement.  A workaround is to force a rediff by switching bounds away and back to the desired ones -- it's inconvenient, but probably less so than reloading the page.

#414 will address keeping track of reviewed lines, but even there they won't be collapsed until the diff bounds change.

It's not impossible that we'll be rewriting the diff lines renderer at some point to take advantage of our switch from Angular to Vue, which might give us the flexibility to support this feature, but TBH it's not even on the horizon right now so I'm going to close this as duplicate/won't fix to manage expectations.  Sorry!
