### ISSUE TITLE
My Reviews page breaks down when Internet connection is lost

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#934]
# Expected

My Reviews stays usable while offline (perhaps with some indication), and resumes refreshing itself when back online.

# Actual

If an automaitc refresh is attempted while offline, an error banner appears over the My Reviews page and makes it unusable. The page does not recover from this state even when Internet connection is fixed.

The error message is “Hubkit error on GET https://api.github.com/user/teams: Request terminated abnormally, network may be offline”.

Note: this also happes every time I put my laptop to sleep because connectivity is briefly interrupted during certain phases of suspending and resuming.

**Comment by pkaminski** [comment]
Thanks -- the design intention is 1) that the page remains usable when offline and 2) that we should recover transparently from this state when reconnected, so it sounds like there's a bug or two in there somewhere.  We'll get it fixed.
