### ISSUE TITLE
Offline: waiting on permission checks

### ISSUE THREAD

**Issue by mtlynch** [Reviewable/Reviewable#936]
Following [a thread from HN](https://news.ycombinator.com/item?id=31849012), just wanted to report a Reviewable failure I see frequently in hopes that we could figure out the reason. If I just go to https://reviewable.io/reviews#- without navigating through a PR, the page takes ~10s to load, and about 30% of the time, it ends with this error message:

![image](https://user-images.githubusercontent.com/7783288/176964502-6b0c21b8-f654-4a33-b61e-1df3cee557c8.png)

>O F F L I N E
We'll get you reconnected as soon as possible.
Check [@reviewableio](https://twitter.com/Reviewableio) for outage announcements.

>
>Reason: waiting on permission checks

My Internet connection is stable (wired Ethernet on a desktop, 1 Gbps fiber link), and I don't see issues like this on other sites. I'm in Massachusetts, so not too far from us-central. This is an issue I've always seen with Reviewable from different machines and different locations.

Any idea why I'm seeing this so frequently?

**Comment by pkaminski** [comment]
Thanks for writing up a report!  The 10s is mostly spent waiting for GitHub to process the (many) search queries we send to populate the list.  We'll probably look into caching results between page loads at some point but for now the recommended workflow is to keep a dashboard tab open and let it refresh in the background, so it's always ready when you need it.

The error is unfortunately a known issue (#819) that we haven't been able to reproduce in circumstances conducive to debugging it.  It happens to me maybe once every few months so it's really hard to nail down...  If it's more common for you then would you be willing to help out?  I can put in some extra instrumentation and give you some code to run in the JS console next time it happens -- perhaps it can help me snag a clue to unravel the mystery.

Closing this issue as duplicate but if you're game let's keep working (here or in #819) to get this sorted out once and for all.  Thanks!
