### ISSUE TITLE
Include references from other PRs

### ISSUE THREAD

**Issue by BlackVegetable** [Reviewable/Reviewable#940]
<img width="1037" alt="Screen Shot 2022-07-21 at 10 34 08 AM" src="https://user-images.githubusercontent.com/2665839/180267004-9c48b40f-50eb-4091-bccb-927e738e761b.png">

Github allows for references within the same repo, and I think across other repos as well, to notify your PR with a message when it is linked to by another PR. This would be a nice to have for Reviewable.

**Comment by pkaminski** [comment]
Ah, I didn't realize this was notified via the PR events feed.  As such, I think it's a subset of our bigger "show PR events" feature in #887.  Marking as duplicate.
