### ISSUE TITLE
Consistent crashes on Safari

### ISSUE THREAD

**Issue by rytaft** [Reviewable/Reviewable#943]
Every time I try to add a new comment, I get a crash with error message:
```
TypeError: undefined is not an object (evaluating 'bg.get("LPContentScriptFeatures").icon_expanded_looks_like_username')
```
When I reload the page I can edit that comment, but an attempt to add a new comment triggers the same crash.

I am running Safari Version 15.6

**Comment by pkaminski** [comment]
Hey @rytaft, thanks for the report.  The expression quoted in the error message doesn't belong to Reviewable, so this is likely a browser extension throwing a global exception that Reviewable happens to catch.  You should be able to isolate the misbehaving extension by turning them off/on to see when the error goes away.
