### ISSUE TITLE
Feature request: unsubscribe myself from a discussion thread

### ISSUE THREAD

**Issue by misha-ridge** [Reviewable/Reviewable#945]
I'd like to have a way to "see myself out" out of a discussion thread.

I commented on a thread in a long-running PR, and every day there is a new comment there, and it pops up in my "things to look at", even though I really don't want to look at it anymore.

**Comment by pkaminski** [comment]
Thinking about this a bit -- is what you're asking for the equivalent of dismissing yourself from a discussion?  If so, that could make it easier to implement.  Could you perhaps ask somebody else to dismiss you from such a discussion as a test?  Thanks!

**Comment by misha-ridge** [comment]
Yes, this sounds like a self-dismissal, and I can ask somebody else to dismiss me too.

**Comment by pkaminski** [comment]
Let me know how having somebody else dismiss you goes -- I'm not sure those
are exactly the semantics we're looking for. Thanks!

**Comment by misha-ridge** [comment]
Oh, I have completely forgotten that I promised to get back to you on this.

Yes, dismissal does exactly what I'd expect it: I'm still getting e-mail notifications from the thread I am dismissed from, but the PR does not show up in "awaiting my action" section. So self-dismissal would be very useful.

**Comment by pkaminski** [comment]
Cool, this should be pretty easy to implement then -- just a bit of UI work.  I'll bump it up the priority list.
