### ISSUE TITLE
Reviewable slow!

### ISSUE THREAD

**Issue by mbatchelor** [Reviewable/Reviewable#947]
We're seeing serious reviewable performance issues.

**Comment by pkaminski** [comment]
Sorry to hear that @mbatchelor.  Could you please provide some more details to make this actionable?  On which page is Reviewable being slow and under what conditions?  Did it start recently?  etc.

**Comment by pkaminski** [comment]
Ping -- we need more details to debug this.

**Comment by pkaminski** [comment]
I'm sorry, but without further details there's nothing we can do.  Happy to reopen if you can provide them.  Thanks.
