### ISSUE TITLE
Bug: Reviewable crashes for this one PR

### ISSUE THREAD

**Issue by TomerSalton** [Reviewable/Reviewable#949]
When reviewing this specific PR, on load, reviewable crashes with the below message.
It happens to me and some of my team members, both on Firefox and Chrome.
![image](https://user-images.githubusercontent.com/19566424/182321591-a4ad0a04-dade-4628-99f6-e28d117a948e.png)

Would be happy to be assisted with this issue!

**Comment by pkaminski** [comment]
This should be fixed now -- sorry about that.
