### ISSUE TITLE
Font size settings does not apply to comments.

### ISSUE THREAD

**Issue by mmlb** [Reviewable/Reviewable#95]
I tweaked my font settings to 150% and the code updated, but not comments. I just went back and noticed that the font settings is for "Custom code font", can we have setting for the rest of the UI?

**Comment by pkaminski** [comment]
Hmm, that may be tricky.  The code font customization does a bunch of extra work to adapt the display to varying sizes, but doing the same for the rest of the UI may be difficult.  At this point, using the browser zoom function might work better.  Did you try that?

**Comment by mmlb** [comment]
Yup, and that lead to #74 :wink:

**Comment by pkaminski** [comment]
I changed the layout for filenames a while ago so #74 should be fixed.  Do you still see it happening?

**Comment by mmlb** [comment]
No not necessarily, but that was one of the issues. I'm pretty sure the "experience" was less than ideal, but will give it a go for a bit.

**Comment by pkaminski** [comment]
How's it going with the whole-window zoom?

**Comment by mmlb** [comment]
Yeah I think its working out ok :+1:

**Comment by pkaminski** [comment]
Excellent!
