### ISSUE TITLE
PR Review crashes - Cannot destructure property 'width' of 'this.getControlDimensions(...)' as it is undefined.

### ISSUE THREAD

**Issue by daria-sorokina-da** [Reviewable/Reviewable#950]
The following error occurs for one specific pull request:
![image](https://user-images.githubusercontent.com/84312905/182381601-00c4a420-c3de-43c1-9793-583696cccf75.png)

Unfortunately, the repository is private, so cannot send the link.

**Comment by Cellule** [comment]
> Unfortunately, the repository is private, so cannot send the link.

Same for me, I opened the review for the first time, I think there was about 5-6 iterations on it before I opened it
Seems inconsistent, some of my colleagues can open it while others can't. Unclear what is common between them

**Comment by Cellule** [comment]
Seems to come from here where the control is not available yet on the screen before trying to get its bounding rect which causes to destructure on `undefined`
<img width="466" alt="image" src="https://user-images.githubusercontent.com/4157103/182391541-a2deb554-fd61-4ad3-b45a-1b346674a758.png">

**Comment by Cellule** [comment]
oops scratch that it's actually `_get(this, "$refs", "control")` that return `undefined`

**Comment by Cellule** [comment]
Not sure if I'm on the right track, but it looks like the control is disabled (from props) but shows as not "disabled"
<img width="503" alt="image" src="https://user-images.githubusercontent.com/4157103/182392755-fda9bf4b-d6f1-4fcc-b933-606dfb1d27de.png">

Seems related to the new control at the bottom
![image](https://user-images.githubusercontent.com/4157103/182393409-2ab0f9b9-6827-42dd-9acd-d9483273834c.png)

In my case when it crashes, that control is missing at the bottom, where my colleagues that do not have the crash sees it

**Comment by pkaminski** [comment]
Should be fixed now -- sorry about that.
