### ISSUE TITLE
Allow for opting out of auto disposition changes on magic keywords

### ISSUE THREAD

**Issue by boryspoplawski** [Reviewable/Reviewable#953]
I personally find the auto disposition changes really annoying, e.g. not every comment I start with "ok" means the issue is now resolved. Of course I can change the disposition manually back to blocking, but sometimes I forget about it (also why would I need to do it in the first place). For me this applies to most/all of the auto detected keywords.

I understand that some people use and like this feature, but it would be nice that others who do not could have it disabled.

**Comment by pkaminski** [comment]
That's fair, and should also address #944.  What do you think @jwnimmer-tri?

**Comment by jwnimmer-tri** [comment]
It would depend on what the defaults are, and how fine-grained the option went.

If we defaulted `BTW` to off and users could opt-in, that would help with #944.  On the other hand, if it were an opt-out then it would only help a little bit -- it's the _casual_ reviewers who are bitten by #944, and it's unlikely that they would have opted-out.

For my taste though, I would hate to lose the `nit` and `minor` hints -- I use those many dozens of times per day.  I'd be fine with losing OK and FYI (and BTW) magic.  In other words, if it were only an all-magic or no-magic toggle, I'd need to leave it set to all-magic.

**Comment by mkow** [comment]
I'd gladly see some of them disabled, but IMO there are useful ones also.

For me the most annoying one is "ok", which sometimes make me accidentally resolve discussions I didn't intend to (usually with replies like: "Ok, but then implement it in XYZ way", or "Please fix XYZ" - "Can I do it by doing ASDF?" - "ok").
The most useful ones are IMO "LGTM", "FYI", "Will do", "Done".

**Comment by pkaminski** [comment]
My idea -- and I believe the OP request -- was to have a single, per-user on/off switch in an out-of-the-way settings panel.  It sounds like that wouldn't really help most people, though.

It may be time to bite the bullet and admit that "OK" and "BTW" are failures and remove them.  Would that (plus an on/off switch) satisfy everyone here?

**Comment by mkow** [comment]
> It may be time to bite the bullet and admit that "OK" and "BTW" are failures and remove them. Would that (plus an on/off switch) satisfy everyone here?

+1 to this idea from my side :)

**Comment by boryspoplawski** [comment]
> My idea -- and I believe the OP request -- was to have a single, per-user on/off switch in an out-of-the-way settings panel.

Correct, that was my idea too.

For me on/off switch would be enough, since I plan to have it at off :) so +1 from me

**Comment by jwnimmer-tri** [comment]
I guess just to clarify -- for my part, either removing BTW or switching it to mean "Discussing" would both work.  The latter might be a less-jarring change for users who have become accustomed to BTW being non-blocking.

**Comment by pkaminski** [comment]
IMO removing a keyword is less confusing than reassigning it.  I'll get some internal thoughts on this as well, though.

**Comment by pkaminski** [comment]
The on/off toggle is implemented; you can find it in the disposition settings panel, accessed via the cog wheel in the top right corner of any of your disposition dropdowns.

I'll continue to track the potential OK/BTW removal in #944.
