### ISSUE TITLE
Let admins set a default review overlap strategy at the repo level

### ISSUE THREAD

**Issue by pkaminski** [Reviewable/Reviewable#955]
Currently, users can set a review overlap strategy, which then becomes their default for any newly visited reviews.  It would be nice if admins could set a default strategy for the repo too.

It's not immediately clear how to resolve the conflict if both a default repo strategy and a default user strategy are set.

**Comment by tk-woven** [comment]
Thank you for this! :) I was told this was created on behalf of a request I made to a team internal to my company that manages our Reviewable instance, so please allow me to add some info from my experience.

It seems the default for me and some others was "Review any unreviewed files." This had the effect that Reviewable collapsed some diffs from the default view for some reviewers. We usually anticipate all of our reviewers review all of the diffs, so this change caught us a bit off guard. We'd like for our admins to be able to set the default to "Review all files personally."

> It's not immediately clear how to resolve the conflict if both a default repo strategy and a default user strategy are set.

For this, I think we could have 2 options. The first is that admins can disable the ability to select a strategy, should some userbase want to force a particular review strategy. The second could be that individual users' choices override the default.

**Comment by pkaminski** [comment]
Cool, thanks for making the request!  TBH when we originally built the feature we figured repo-level defaults might be needed one day, but decided to wait for somebody to request them first.  :)

> It seems the default for me and some others was "Review any unreviewed files."

This has always been the default AFAIK.

Here's our plan for addressing this issue:

We'll add a default overlap strategy selector to the repository settings.  When a user first visits a review we'll initialize their strategy to the first one from the following list:  repo default, user default, hard-coded default (review any unreviewed files).  If there is a repo default and it differs from the user's we'll add a small "(Repository default)" annotation below the dropdown.  The user will always be able to change the strategy in a review, as we don't believe in letting admins lock out functionality; changing the strategy will still set the user's default as it does now.

Hopefully this will be sufficient.  If it turns out that in practice some users need to regularly override the repo default, we'll add an extra per-user per-repo flag to use their personal default instead.  This would be set/cleared via a link in the annotation, something like "(Repository default. <a href="">Use personal one</a>)" and "(Personal default. <a href="">Use repository one</a>)".

How does that sound?

**Comment by tk-woven** [comment]
Thanks for your great work! Reviewable is such a positive experience for us :)

> This has always been the default AFAIK.

Thanks for confirming. I must have been confused.

> How does that sound?

This will definitely meet our needs. Thank you!

**Comment by pkaminski** [comment]
Launched on SaaS, and will be in the upcoming Enterprise release.

**Comment by tk-woven** [comment]
Thank you kindly, Piotr!
