### ISSUE TITLE
File grouping: file order during review

### ISSUE THREAD

**Issue by Cellule** [Reviewable/Reviewable#958]
We use the following for file grouping
```js
_.forEach(review.files, file => {
  if (/\.spec\.tsx?$/i.test(file.path)) file.group = '9 - Tests';
  else if (/\.gen(\.\w+)+$/i.test(file.path)) {
    file.group = '9 - Generated Files';
    file.reviewed = true;
  }
  else if (/^changelogs/i.test(file.path)) file.group = '1 - Changelogs';
  else if (/shared[\/\-]/i.test(file.path)) file.group = '2 - Shared Files';
  else if (/^backend\/scheduler/i.test(file.path)) file.group = '4 - Scheduler';
  else if (/^backend/i.test(file.path)) file.group = '3 - Backend';
  else if (/^frontend/i.test(file.path)) file.group = '5 - Frontend';
  else if (/^native/i.test(file.path)) file.group = '6 - Native';
  else if (/^gospel/i.test(file.path)) file.group = '7 - Global Procedure Library';
  else if (/^dashboard/i.test(file.path)) file.group = '8 - Dashboard';
  else file.group = "Others"
});
```

The groups work fine
![image](https://user-images.githubusercontent.com/4157103/190032323-2c8b1e5f-f2f5-4671-91d5-01a61c12c4dc.png)

However, recently-ish, I feel about maybe 1-2 months ago, the order of the files as we review no longer follow
From the screenshot above, I would expect to review the changelogs first, then backend, then frontend, etc...
However, when scrolling down, it seems the files follow alpha order of the filepath instead of the groups we've setup
![image](https://user-images.githubusercontent.com/4157103/190032516-02244707-b8f2-43a6-97ef-794952646b2d.png)

Is it intended? a regression? If not is there a way I can control the order the files will appear?
Some of the devs on my team complained that the order the files are being reviewed is a bit off-putting compared to our previous mechanism

**Comment by pkaminski** [comment]
Apologies -- this was a regression introduced around August 3rd.  Thanks for spotting and reporting it!  Should be fixed now.

**Comment by Cellule** [comment]
Confirmed it works like a charm now! Thank you so much for the quick response & fix :D
