### ISSUE TITLE
ctrl-shift-{left,right} does not work on new comments

### ISSUE THREAD

**Issue by mmlb** [Reviewable/Reviewable#96]
First I click a line to start a completely new comment and then start typing multiple words. Then when I try to select the previous words using ctrl-shift-left the cursor disappears and nothing is highlighted. I have to click on the input field for the ctrl-shift-left/right to work.

This also happens if I type some words, navigate back with only the left arrow key and then try to go forward with ctrl-shift-right.

**Comment by pkaminski** [comment]
Reproduced, I'll take a look.  Strangely, clicking in the textarea again (even though it's already focused) makes it work fine.

**Comment by mmlb** [comment]
Yup, also does not happen when clicking to reply to another comment.

**Comment by pkaminski** [comment]
Fixed.  This was a bug in the code that allows you to select and copy code even across comments.
