### ISSUE TITLE
Reviewable hangs indefinitely on "Mapping renamed files"

### ISSUE THREAD

**Issue by mtlynch** [Reviewable/Reviewable#962]
I'm unable to open any Reviewable reviews. It spins on "Mapping renamed files" forever:

https://user-images.githubusercontent.com/7783288/191270848-062aaf86-f5dd-47a3-8e01-95e8cd6a1b24.mp4

Example: https://reviewable.io/reviews/tiny-pilot/tinypilot/895

**Comment by pkaminski** [comment]
I've seen this a couple times, but was never able to reproduce.  I was excited you had a reproducible instance here but it looks like it fixed itself for https://reviewable.io/reviews/tiny-pilot/tinypilot/895?  Do you have any other examples that are still failing by any chance?

**Comment by mtlynch** [comment]
These all still show up for me as stuck on "Mapping renamed files"

* https://reviewable.io/reviews/tiny-pilot/tinypilot/837
* https://reviewable.io/reviews/tiny-pilot/ansible-role-tinypilot/205
* https://reviewable.io/reviews/tiny-pilot/gatekeeper/49

**Comment by pkaminski** [comment]
Dammit.  The first two resolved themselves for me after a couple seconds, and the last one is private.  I'm starting to wonder if the effect is user-specific.

If it happens to you again, could you please gather the following info from the console:
```js
review = truss.store.services.reviewContext.current.review;
JSON.stringify({diffFiles: review.context.diffFiles, revisionsReady: review.revisions.$ready, revisions: _.mapValues(review.revisions, rev => _.pick(rev, 'computingFilemap', 'filemapKey', 'filemap')), filemaps: truss.store.filemaps[review.$key]});
```

Thanks!

**Comment by mtlynch** [comment]
Here's what I see for the private repo:

```javascript
"{\"diffFiles\":true,\"revisionsReady\":true,\"revisions\":{\"r1\":{\"computingFilemap\":true,\"filemapKey\":\"undefined-60faa5f4bf135aa8a4b32d321efe0a8214083446\"},\"r2\":{\"computingFilemap\":true,\"filemapKey\":\"60faa5f4bf135aa8a4b32d321efe0a8214083446-fe7bf1cd7c55559b1def778a9c120fa7962e33a9\"},\"r3\":{\"computingFilemap\":true,\"filemapKey\":\"fe7bf1cd7c55559b1def778a9c120fa7962e33a9-3b853c336a810937056040a2fe97d1a6f3029158\"}}}" 
```

**Comment by pkaminski** [comment]
Thanks one more thing to check in light of the above:  `review.core.lastReconciliationTimestamp` is a number or undefined?

**Comment by pkaminski** [comment]
Never mind, that's going to be `undefined`.  I know where to look now -- thanks!

**Comment by pkaminski** [comment]
Pushing a potential fix now but I need to run to a previous commitment.  Could you try loading that review again in 15 minutes or so?  Thanks!

**Comment by mtlynch** [comment]
Still no luck on the private repo:

```javascript
"{\"diffFiles\":true,\"revisionsReady\":true,\"revisions\":{\"r1\":{\"computingFilemap\":true,\"filemapKey\":\"undefined-60faa5f4bf135aa8a4b32d321efe0a8214083446\"},\"r2\":{\"computingFilemap\":true,\"filemapKey\":\"60faa5f4bf135aa8a4b32d321efe0a8214083446-fe7bf1cd7c55559b1def778a9c120fa7962e33a9\"},\"r3\":{\"computingFilemap\":true,\"filemapKey\":\"fe7bf1cd7c55559b1def778a9c120fa7962e33a9-3b853c336a810937056040a2fe97d1a6f3029158\"}}}" 
```

`lastReconciliationTimestamp` is indeed undefined:

```javascript
> review.core.lastReconciliationTimestamp
undefined 
```

**Comment by pkaminski** [comment]
OK, walking back up the handoff chain between a bunch of processes I think I found the next weak point -- this one likely because the PR got merged, and we didn't try hard enough to bring merged/closed PRs up to date.  Logic fix deployed, please try to refresh again and we'll see if that helped.  Thanks!

**Comment by mtlynch** [comment]
Yep, working now. Thanks!
