### ISSUE TITLE
comment replies are hidden in UI

### ISSUE THREAD

**Issue by mmlb** [Reviewable/Reviewable#97]
PR submitter replied to my comments and I can see the replies in both github, and from github's email. When I go to the review page, the unreplied-discussions badge is red and displays the correct number I expect, but clicking it does not navigate to a discussion. pressing the `j`does not work either.

This became "unstuck" by change the reviews displayed via the revisions bar, and then going back to the full review.

**Comment by pkaminski** [comment]
This will be hard to reproduce so I may need your help to investigate.  Can you check if, when in the "stuck" state, the unreplied comments are actually there?  That is, is it a failure of navigation (comments are there but not navigated to) or content (comments not showing up at all).  Thanks.

**Comment by pkaminski** [comment]
I also just rewrote a part of the discussion-view code that I've been suspicious of for a while, so with a bit of luck you may not be able to repro this any more.  *fingers crossed*

**Comment by pkaminski** [comment]
Never mind, I just reproduced this on the latest version.  :angry:  Digging...

**Comment by pkaminski** [comment]
This was a nasty race condition that I could only reproduce in prod.  Squashed.
