### ISSUE TITLE
Github Checks should be more visible

### ISSUE THREAD

**Issue by BlackVegetable** [Reviewable/Reviewable#978]
From a user I work with:

"The [CI] pipeline checks which are essential for knowing which build pipeline portion failed are hidden away instead of being front and center like Github PRs. This [visibility] is very desirable. As is, [Reviewable's view of checks] is not an intuitive UI."

**Comment by pkaminski** [comment]
Is the complaint that the list of checks is tucked away inside a dropdown?  I'd argue that that way, at least, the red/green donut is always visible and the list is always accessible, compared to GitHub's approach of only showing it at the bottom of one of the PR's tabs.

We'll be moving the list to a sidebar in the near-ish future (along with all the other stuff that's currently in the toolbar).  Would it also be useful to repeat the donut (and perhaps a summary of successes/failures) somewhere near the bottom-of-page review summary area?

**Comment by BlackVegetable** [comment]
> Is the complaint that the list of checks is tucked away inside a dropdown?

This appears to be the complaint. When it matters *which* check is failing/pending, this can be a slowdown in the GUI apparently. 

I'm asking the original requester for more details.

**Comment by pkaminski** [comment]
Ping -- any updates here @BlackVegetable?

**Comment by BlackVegetable** [comment]
I apologize, I'm OOO through December. Check back in in mid January?

**Comment by pkaminski** [comment]
Hey Devin, if you're back at the office, wanna see if you can dig up more details on this?  I'd just like to know what it might entail and how to prioritize it.  Thanks!

**Comment by patrick-oday-cruise** [comment]
To add a different perspective for the same customer:
For the user the automation is just as if not more important than the diffs and user feedback.

To describe two extreme use cases:
1. The PR automation checks are running the same lint, tests, etc that users can run themselves. The automation is mostly double checking that everything is submitted and that is works in the official environments.
2. The PR automation checks are running automation that users are unable to run themselves. Utilizing environments or resources that users don't have access to and potentially run for hours. In this scenario the PR is a platform for coordinating automation.

 I believe that this customer leans towards option 2 with more iteration with automation than iteration with reviewers.

**Comment by pkaminski** [comment]
Thanks, that perspective makes sense.  It almost feels like the situation we were in with commits, where they were incidental for some folks but a primary review artifact for others.  We solved that issue by putting commit messages in a reviewable "file" in the main flow, and I'm wondering if a similar approach might work here too.

Can you say more about the workflow for option 2?  For example, would it be useful to have a history of status checks, be able to attach discussions to them, etc?  If possible, it would be ideal if we could do a short product design session with one or two folks who live in that world.

**Comment by patrick-oday-cruise** [comment]
I think that there are a lot of interesting features in this space but I'm not sure how valuable they would be. As an example:
Each commit could have a marking indicating check success/fail percentage, similar to vscode's [shell decorations](https://code.visualstudio.com/docs/terminal/shell-integration#_command-decorations-and-the-overview-ruler) to indicate command success/fail. However in my experience using an automation iteration workflow it generally goes like:

- Push a commit
- Wait for check results
- Inspect details from failed checks
- Go a few layers into the details from a failed check
- Fix broken tests
- Push a commit & repeat

The aggregation at the github check level isn't too useful. A single github check may represent 10 or 10,000 unit tests. Assuming that we're limited to github's information of: check name, result, short description, and details url; it's unlikely that anything interesting is possible. Most of the time, the iteration to a success result doesn't matter as long as success is achieved as github only cares about the tip of the branch.

I think displaying a check table, similar to the file matrix: hidden behind a user config and at the top of the PR, would remove an interaction for people looking at what has failed and then following the details link.

I'll see about scheduling a product design session with people that have specific workflows to make sure we're all on the same page.

**Comment by pkaminski** [comment]
After some internal debate I think we're on board with moving the checks panel out of the dropdown and likely into the main flow of the page.  This work will happen as part of the reorganization needed for the upcoming sidebar.

Still happy to talk to folks with specific workflows about what changes they'd like to see in the panel, but we're no longer blocking on that.
