### ISSUE TITLE
Add magic keywords to set blocking disposition

### ISSUE THREAD

**Issue by earlAchromatic** [Reviewable/Reviewable#984]
Currently the only magic keyword that lets you change a resolved discussion to unresolved is 'working' which has a particular meaning. It would be nice to have some other keyword options for setting disposition to blocking.

Here's a scenario where this would be useful: you publish your comment with the satisfied disposition and the discussion is resolved. Afterwards you realize a mistake exists that you didn't see before and want to quickly block the discussion again.

Here are a few keywords that could work for this: 'stop', 'hold on', or 'wait'.

**Comment by pkaminski** [comment]
I think if we do this, we should do it together with the other draft-related updates that got merged recently.  I'd probably go with just "stop" and "hold on" (or maybe "hold up"?) -- "wait" feels like it could lead into all kinds of ambiguous phrases.  I think with the new keyword highlighting adding new keywords is much safer than before, too.

As long as it doesn't raise the number of keyword tip lines showing in a new draft I'm in favor.  I'll need to think through that constraint, though, since we have more than 5 dispositions overall but I believe only 5 active ones and a draft will always have one of those selected by default (and hence not showing its tip).

**Comment by pkaminski** [comment]
More keyword suggestions:  "bug", "fix", "important", "critical".

**Comment by mkow** [comment]
Hmm, I think that basically all the keywords you suggested are very context dependent? E.g. "nice catch, we had a similar **bug** here: \<link\>" - which is definitely not a blocking remark.

>  I think with the new keyword highlighting adding new keywords is much safer than before, too.

I really like this change!

**Comment by pkaminski** [comment]
Like other keywords, these would only trigger the disposition if they're the first (non-quoted) word in the comment, so I think they'd be fine for that (e.g., "Bug: this forble won't wrungle if...").

Another random idea:  what if we made all the disposition names (Blocking, Satisfied, etc.) into keywords as well?  No need to advertise them, but if somebody happens to type one in I think switching to that disposition would be the right thing to do.

**Comment by mkow** [comment]
Then maybe require ":", "," or "-" afterwards? Although it will be hard to discover for users without any hints... But usually you either write a full sentence, in which case you would say "A bug" or "The bug" (and this you don't want to match), not just "bug", so I guess the "bug" you want to detect is always "bug:"?

> Another random idea: what if we made all the disposition names (Blocking, Satisfied, etc.) into keywords as well? No need to advertise them, but if somebody happens to type one in I think switching to that disposition would be the right thing to do.

Sounds good if you match them with ":" at the end, mixed feelings without. I would need to think more if there may be some common replies you start with these, but the meaning is different.

**Comment by pkaminski** [comment]
Dunno, we currently support "nit" and "minor", which only make sense when followed with a colon, but we don't require it and it seems to be working out fine.  The in-draft tips seem sufficient to nudge folks into the preferred usage.

For the disposition keywords, I could see requiring a colon or EOL/EOM at the end.

**Comment by mkow** [comment]
Hmm, but "nit" and "minor" are probably much less popular than "bug" and people might have just never hit such cases with them? Anyways, this is just a nitpick, Probably the beginning-of-the-comment requirement will be enough in practice.

**Comment by pkaminski** [comment]
I ended up going with "bug", "major" and "hold on".
