### ISSUE TITLE
Add message selection command palette and remove auto-quoting behavior

### ISSUE THREAD

**Issue by pkaminski** [Reviewable/Reviewable#986]
We should remove the current auto-quoting behavior, where creating a new comment or code block will automatically quote the current selection.  This is often surprising, and we now have many other (and more discoverable) mechanisms for this use case.

The one piece that's missing that we should add is a command palette on message selections that offers a Quote button.  Clicking this will quote-paste the selection into the current draft on the same discussion, creating one if necessary.

**Comment by pkaminski** [comment]
As part of this, it would be nice to improve the quality of text copied from comments.  When pasting into a draft, we should recognize common HTML elements in the selection and convert them to Markdown.  We should also consider adding an extra `\n` after a header for ease of pasting from the Review Discussion into the merge commit description.

**Comment by fahhem** [comment]
Hey @jwnimmer-tri , we only just deployed this a couple days ago, so it will show up in next week's changelog. I can see how that delay is unfortunate, so we'll work on shortening the delay between deploys and changelogs. Ideally, without increasing changelog announcements.

Thank you!
