### ISSUE TITLE
Preserving CamelCase in badge links

### ISSUE THREAD

**Issue by jwnimmer-tri** [Reviewable/Reviewable#988]
When Reviewable posts the "This change is Reviewable" badge, it hyperlinks to a lowercased URL of the review.  For example, the badge in https://github.com/RobotLocomotion/drake/pull/18561 links to https://reviewable.io/reviews/robotlocomotion/drake/18561.

On the other hand, the reviews dashboard respects the camel case.  In my dashboard when I clicked on a review, it takes me to e.g.  https://reviewable.io/reviews/RobotLocomotion/drake/18561.

This inconsistency ends up infecting the Firefox "smart bar" that uses the browser history to inform suggestions, in that the suggestions have random case making it slightly more difficult to use.  Similarly, I find the wordsthataremissingtheirinnercaps more difficult to read, so it's a clarity issue as well.

My request is to use the repository name's canonical casing (`RobotLocomotion`) in the badge in particular, but anywhere else in the UI that demotes to lowercase would also be nice to tidy up.

---

On a related note (maybe a different issue) the same goes for usernames.  When assigning a review via a magic comment, the suggestion/completion options lowercase everything so my reviewer `+@EricCousineau` ends up as `+@ericcousineau` which is more difficult to read / not actually their preferred name.  Because of that, I can never use the suggestion and I need to key it in carefully by hand.

**Comment by jwnimmer-tri** [comment]
I remembered one more place where the lowercasing is frustrating -- when Reviewable posts review comments into the GitHub timeline -- the discussion links there that take me back to reviewable.io use the lowercase, but I'd prefer the native case.

**Comment by pkaminski** [comment]
Thanks!  These should all now be fixed, though not necessarily retroactive.  They were all completely separate issues, BTW.  :)  Please let me know if you spot any other instances of aggressive lowercasing that need fixing...
