### ISSUE TITLE
Cannot log in by just copying-and-pasting URLs

### ISSUE THREAD

**Issue by DemiMarie** [Reviewable/Reviewable#989]
I use [Qubes OS], and use different VMs for Reviewable and GitHub.  Normally, if something uses GitHub-based SSO, copy-and-paste of the URL (via the Qubes Global Clipboard) in each direction is sufficient.  With Reviewable, it fails.

To test this, try to log in to Reviewable with a browser profile not logged into GitHub.

[Qubes OS]: https://www.qubes-os.org

**Comment by DemiMarie** [comment]
I wonder if this was actually a case of PEBKAC: I was looking at the browser logs, not the proxy logs, and did not realize that some requests to Firebase were being blocked.

**Comment by pkaminski** [comment]
Ah, yeah, the connection to Firebase is kinda critical, even just for signing in.  :)
