### ISSUE TITLE
Don't require write access to repository code.

### ISSUE THREAD

**Issue by scheib** [Reviewable/Reviewable#99]
Github Repositories permission https://help.github.com/articles/connecting-with-third-party-applications/#repositories access is too powerful for a code review tool. Reviewing should not require access to commit code to a repository.

**Comment by pkaminski** [comment]
I completely agree, but you need to raise this issue against GitHub.  There's no permission scope for read-only access to the code, as mentioned in the note [here](https://help.github.com/articles/connecting-with-third-party-applications/#types-of-application-access-and-data):
> Note: Currently, you can't scope source code access to read-only. For more information, see OAuth Scopes in the GitHub Developer Documentation.

And you can't have much of a code review tool without access to the code...

**Comment by scheib** [comment]
Has Reviewable opened an issue with GitHub yet? If not, why not, it seems to be in the product's interest.

Can Reviewable work without Repositories permission? Sure it could, and I'd love to do so vs not using Reviewable at all. I'd do a review, and comment back myself directly on the github pull request.

**Comment by pkaminski** [comment]
I, and many others, have raised the issue with GitHub so they're well aware of it.  Feel free to email support@github.com to add your voice to the chorus.  However GitHub doesn't maintain an externally accessible list of issues AFAICT.  And to be honest my impression is that this is an intrinsic fault with GitHub's design that won't be fixed any time soon.

As for working without `public_repo` scope -- yes, it's technically possible, but it would introduce sufficient extra complexity into the UX and internal design that it's not really worth doing.  Especially given that the security concerns are not widespread for public repos (a number of large open source projects have adopted Reviewable), and not relevant to private repos which are Reviewable's bread-and-butter (75% of usage).  Sorry.

**Comment by scheib** [comment]
Thank you for the explanation. I've written to support@github.com.
