### ISSUE TITLE
Changelog link in reviewable.io does not reflect even major UI changes

### ISSUE THREAD

**Issue by nate-thirdwave** [Reviewable/Reviewable#995]
Major UI changes are being rolled out (disposition change, reviewer activity, etc) and no mention is in the changelog (https://changelog.reviewable.io/) as linked from the Support cloud menu in the upper right.

If the concern is that people should not get a "notification dot" for UI updates, can the Changelog link simply be pointed to the github changelog directly instead?  It's incredibly misleading to see a Changelog that is effectively reporting "unchanged" for 6 months, but UI behavior is drastically different.

**Comment by fahhem** [comment]
Hey Nate,

This is something we're actively working on. As you know, it's a balance between the red dot being useful and becoming annoying.

There's a more in-depth changelog that we maintain in [our public repo](https://github.com/Reviewable/Reviewable/blob/master/enterprise/changelog.md), and we're open to suggestions on how best to maintain that balance. I would note that we deploy the latest changes online roughly 2 to 5 times a week to make sure bugs are squashed quickly and features don't linger too long. However, that means updating the public changelog for every deploy would quickly make customers upset.

If you have suggestions on which changelogs would be good to announce, please reply here or send them to support@reviewable.io so we can see it as a team.

Thank you!
Fahrzin Hemmati

**Comment by fahhem** [comment]
Hey @nate-thirdwave, we've announced and are implementing a new changelog strategy, you can see our latest changelog now at https://changelog.reviewable.io/ and read more about the strategy on our blog, which will also have our changelog: http://blog.reviewable.io/
