### ISSUE TITLE
Keyboard shortcuts modal doesn't block keyboard shortcuts

### ISSUE THREAD

**Issue by fahhem** [Reviewable/Reviewable#997]
If I press Ctrl-/, the keyboard shortcuts modal comes up. If I press Esc it goes away.

If I press it while I have an empty draft message open, it still comes up. But if I press Esc, my empty draft message is closed. I have to press Esc again to close the modal.

If I press it while I have a non-empty draft message, the modal comes up. It still takes 2 Esc's to dismiss it, but my non-empty draft message stays open.

**Comment by pkaminski** [comment]
I think we just need to blur any current focus when opening the modal.

**Comment by pkaminski** [comment]
Tip: look for `toggleCheatSheet` in `hotkeys.js`.
